In [1]:
import os
import pandas as pd

raw_base = "data/raw"

files_to_check = {
    "Kelani - Rainfall": "flood/2015 - 2025 RF.xlsx",
    "Kelani - Water Level": "flood/2015 - 2025 WL.xlsx",
    "Kelani - Discharge": "flood/2015 - 2025 Discharge.xlsx",
    "Kalu - Rathnapura Hydro": "flood/Rathnapura.xlsx",
    "Landslide Records": "landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx",
    "Flood Records": "disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx",
    "Census - Population": "census/GN_population_excel.xlsx",
    "Census - Housing": "census/GN_housing_excel.xlsx",
    "Census - Households": "census/HH_GND_excel.xlsx"
}

print("==================================================")
print("           MASTER RAW DATA INVENTORY AUDIT        ")
print("==================================================\n")

for label, rel_path in files_to_check.items():
    full_path = os.path.join(raw_base, rel_path)
    exists = os.path.exists(full_path)
    status = "✓ FOUND" if exists else "❌ MISSING"
    print(f"[{status}] {label}")
    print(f" Path: {rel_path}")
    
    if exists and rel_path.endswith(".xlsx"):
        try:
            excel_file = pd.ExcelFile(full_path)
            sheet_names = excel_file.sheet_names
            print(f" Total Sheets: {len(sheet_names)}")
            
            for sheet in sheet_names:
                df = pd.read_excel(full_path, sheet_name=sheet, nrows=5)
                print(f"   └── Sheet: '{sheet}' | Shape: {df.shape} | Columns (first 5): {list(df.columns[:5])}")
        except Exception as e:
            print(f"   └── ❌ Error reading sheets: {e}")
    print("-" * 60)

==================================================
           MASTER RAW DATA INVENTORY AUDIT
==================================================

[❌ MISSING] Kelani - Rainfall
 Path: flood/2015 - 2025 RF.xlsx
------------------------------------------------------------
[❌ MISSING] Kelani - Water Level
 Path: flood/2015 - 2025 WL.xlsx
------------------------------------------------------------
[❌ MISSING] Kelani - Discharge
 Path: flood/2015 - 2025 Discharge.xlsx
------------------------------------------------------------
[❌ MISSING] Kalu - Rathnapura Hydro
 Path: flood/Rathnapura.xlsx
------------------------------------------------------------
[❌ MISSING] Landslide Records
 Path: landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx
------------------------------------------------------------
[❌ MISSING] Flood Records
 Path: disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx
------------------------------------------------------------
[❌ MISSING] Census - Population
 Path: census/GN_population_excel.xlsx
------------------------------------------------------------
[❌ MISSING] Census - Housing
 Path: census/GN_housing_excel.xlsx
------------------------------------------------------------
[❌ MISSING] Census - Households
 Path: census/HH_GND_excel.xlsx
------------------------------------------------------------

In [2]:
import os
import pandas as pd

# Path points back to data/raw relative to the notebooks folder
raw_base = "../data/raw"

files_to_check = {
    "Kelani - Rainfall": "flood/kelani/2015 - 2025 RF.xlsx",
    "Kelani - Water Level": "flood/kelani/2015 - 2025 WL.xlsx",
    "Kelani - Discharge": "flood/kelani/2015 - 2025 Discharge.xlsx",
    "Kalu - Rathnapura Hydro": "flood/kalu/Rathnapura.xlsx",
    "Landslide Records": "landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx",
    "Flood Records": "disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx",
    "Census - Population": "census/GN_population_excel.xlsx",
    "Census - Housing": "census/GN_housing_excel.xlsx",
    "Census - Households": "census/HH_GND_excel.xlsx"
}

print("==================================================")
print("           MASTER RAW DATA INVENTORY AUDIT        ")
print("==================================================\n")

for label, rel_path in files_to_check.items():
    full_path = os.path.join(raw_base, rel_path)
    exists = os.path.exists(full_path)
    status = "✓ FOUND" if exists else "❌ MISSING"
    print(f"[{status}] {label}")
    print(f" Path: {rel_path}")
    
    if exists and rel_path.endswith(".xlsx"):
        try:
            excel_file = pd.ExcelFile(full_path)
            sheet_names = excel_file.sheet_names
            print(f" Total Sheets: {len(sheet_names)}")
            
            for sheet in sheet_names:
                df = pd.read_excel(full_path, sheet_name=sheet, nrows=5)
                print(f"   └── Sheet: '{sheet}' | Shape: {df.shape} | Columns (first 5): {list(df.columns[:5])}")
        except Exception as e:
            print(f"   └── ❌ Error reading sheets: {e}")
    print("-" * 60)

==================================================
           MASTER RAW DATA INVENTORY AUDIT
==================================================

[❌ MISSING] Kelani - Rainfall
 Path: flood/kelani/2015 - 2025 RF.xlsx
------------------------------------------------------------
[❌ MISSING] Kelani - Water Level
 Path: flood/kelani/2015 - 2025 WL.xlsx
------------------------------------------------------------
[❌ MISSING] Kelani - Discharge
 Path: flood/kelani/2015 - 2025 Discharge.xlsx
------------------------------------------------------------
[❌ MISSING] Kalu - Rathnapura Hydro
 Path: flood/kalu/Rathnapura.xlsx
------------------------------------------------------------
[❌ MISSING] Landslide Records
 Path: landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx
------------------------------------------------------------
[❌ MISSING] Flood Records
 Path: disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx
------------------------------------------------------------
[❌ MISSING] Census - Population
 Path: census/GN_population_excel.xlsx
------------------------------------------------------------
[❌ MISSING] Census - Housing
 Path: census/GN_housing_excel.xlsx
------------------------------------------------------------
[❌ MISSING] Census - Households
 Path: census/HH_GND_excel.xlsx
------------------------------------------------------------

In [3]:
import os
import pandas as pd

raw_base = "../data/raw"

files_to_check = {
    "Kelani - Rainfall": "flood/kelani/2015 - 2025 RF.xlsx",
    "Kelani - Water Level": "flood/kelani/2015 - 2025 WL.xlsx",
    "Kelani - Discharge": "flood/kelani/2015 - 2025 Discharge.xlsx",
    "Kalu - Rathnapura Hydro": "flood/kalu/Rathnapura.xlsx",
    "Landslide Records": "landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx",
    "Flood Records": "disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx",
    "Census - Population": "census/GN_population_excel.xlsx",
    "Census - Housing": "census/GN_housing_excel.xlsx",
    "Census - Households": "census/HH_GND_excel.xlsx"
}

print("==================================================")
print("           MASTER RAW DATA INVENTORY AUDIT        ")
print("==================================================\n")

for label, rel_path in files_to_check.items():
    full_path = os.path.join(raw_base, rel_path)
    exists = os.path.exists(full_path)
    status = "✓ FOUND" if exists else "❌ MISSING"
    print(f"[{status}] {label}")
    print(f" Path: {rel_path}")
    
    if exists and rel_path.endswith(".xlsx"):
        try:
            excel_file = pd.ExcelFile(full_path)
            sheet_names = excel_file.sheet_names
            print(f" Total Sheets: {len(sheet_names)}")
            
            for sheet in sheet_names:
                df = pd.read_excel(full_path, sheet_name=sheet, nrows=5)
                print(f"   └── Sheet: '{sheet}' | Shape: {df.shape} | Columns (first 5): {list(df.columns[:5])}")
        except Exception as e:
            print(f"   └── ❌ Error reading sheets: {e}")
    print("-" * 60)

==================================================
           MASTER RAW DATA INVENTORY AUDIT
==================================================

[✓ FOUND] Kelani - Rainfall
 Path: flood/kelani/2015 - 2025 RF.xlsx
 Total Sheets: 6
   └── Sheet: 'KN02-NORWOOD' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'KN07-KITULGALA' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: ' KN11-HOLOMBUWA' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'KN16-DERANIYAGALA' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'KN18-GLENCOURSE' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'KN21-HANWELLA' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Kelani - Water Level
 Path: flood/kelani/2015 - 2025 WL.xlsx
 Total Sheets: 7
   └── Sheet: 'Norwood' | Shape: (5, 4) | Columns (first 5): ['Kehelgamu Oya at Norwood', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Kithulgala' | Shape: (5, 4) | Columns (first 5): ['Kelani Ganga at Kithulgala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Deraniyagala' | Shape: (5, 4) | Columns (first 5): ['Seethawaka Ganga at Deraniyagala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Holombuwa' | Shape: (5, 4) | Columns (first 5): ['Gurugoda Oya at Holombuwa', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Glencourse' | Shape: (5, 4) | Columns (first 5): ['Kelani Ganga at Glencourse', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Hanwella' | Shape: (5, 4) | Columns (first 5): ['Kelani Ganga at Hanwella', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'N'Street' | Shape: (5, 4) | Columns (first 5): ["Kelani Ganga at N'Street", 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
------------------------------------------------------------
[✓ FOUND] Kelani - Discharge
 Path: flood/kelani/2015 - 2025 Discharge.xlsx
 Total Sheets: 6
   └── Sheet: 'Norwood' | Shape: (5, 32) | Columns (first 5): ['Kehelgamu Oya at Norwood', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Kithulgala' | Shape: (5, 32) | Columns (first 5): ['Kelani Ganga at Kithulgala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Deraniyagala' | Shape: (5, 33) | Columns (first 5): ['Seethawaka Ganga at Deraniyagala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Holombuwa' | Shape: (5, 32) | Columns (first 5): ['Gurugoda Oya at Holombuwa', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Glencourse' | Shape: (5, 32) | Columns (first 5): ['Kelani Ganga at Glencourse', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Hanwella' | Shape: (5, 32) | Columns (first 5): ['Kelani Ganga at Hanwella', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Kalu - Rathnapura Hydro
 Path: flood/kalu/Rathnapura.xlsx
 Total Sheets: 3
   └── Sheet: 'General Information' | Shape: (4, 2) | Columns (first 5): ['General Information', 'Unnamed: 1']
   └── Sheet: 'WL Summery MSL' | Shape: (5, 30) | Columns (first 5): ['RATHNAPURA WATER LEVELS in m (MSL)', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Q' | Shape: (5, 30) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[❌ MISSING] Landslide Records
 Path: landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx
------------------------------------------------------------
[❌ MISSING] Flood Records
 Path: disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx
------------------------------------------------------------
[✓ FOUND] Census - Population
 Path: census/GN_population_excel.xlsx
 Total Sheets: 1
   └── Sheet: 'Population' | Shape: (5, 17) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Census - Housing
 Path: census/GN_housing_excel.xlsx
 Total Sheets: 1
   └── Sheet: 'Housing Units' | Shape: (5, 10) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Census - Households
 Path: census/HH_GND_excel.xlsx
 Total Sheets: 1
   └── Sheet: 'Households' | Shape: (5, 47) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------

In [4]:
import os
import pandas as pd

raw_base = "../data/raw"

files_to_check = {
    "Kelani - Rainfall": "flood/kelani/2015 - 2025 RF.xlsx",
    "Kelani - Water Level": "flood/kelani/2015 - 2025 WL.xlsx",
    "Kelani - Discharge": "flood/kelani/2015 - 2025 Discharge.xlsx",
    "Kalu - Rathnapura Hydro": "flood/kalu/Rathnapura.xlsx",
    "Landslide Records": "landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx",
    "Flood Records": "disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx",
    "Census - Population": "census/GN_population_excel.xlsx",
    "Census - Housing": "census/GN_housing_excel.xlsx",
    "Census - Households": "census/HH_GND_excel.xlsx"
}

print("==================================================")
print("           MASTER RAW DATA INVENTORY AUDIT        ")
print("==================================================\n")

for label, rel_path in files_to_check.items():
    full_path = os.path.join(raw_base, rel_path)
    exists = os.path.exists(full_path)
    status = "✓ FOUND" if exists else "❌ MISSING"
    print(f"[{status}] {label}")
    print(f" Path: {rel_path}")
    
    if exists and rel_path.endswith(".xlsx"):
        try:
            excel_file = pd.ExcelFile(full_path)
            sheet_names = excel_file.sheet_names
            print(f" Total Sheets: {len(sheet_names)}")
            
            for sheet in sheet_names:
                df = pd.read_excel(full_path, sheet_name=sheet, nrows=5)
                print(f"   └── Sheet: '{sheet}' | Shape: {df.shape} | Columns (first 5): {list(df.columns[:5])}")
        except Exception as e:
            print(f"   └── ❌ Error reading sheets: {e}")
    print("-" * 60)

==================================================
           MASTER RAW DATA INVENTORY AUDIT
==================================================

[✓ FOUND] Kelani - Rainfall
 Path: flood/kelani/2015 - 2025 RF.xlsx
 Total Sheets: 6
   └── Sheet: 'KN02-NORWOOD' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'KN07-KITULGALA' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: ' KN11-HOLOMBUWA' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'KN16-DERANIYAGALA' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'KN18-GLENCOURSE' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'KN21-HANWELLA' | Shape: (5, 35) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Kelani - Water Level
 Path: flood/kelani/2015 - 2025 WL.xlsx
 Total Sheets: 7
   └── Sheet: 'Norwood' | Shape: (5, 4) | Columns (first 5): ['Kehelgamu Oya at Norwood', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Kithulgala' | Shape: (5, 4) | Columns (first 5): ['Kelani Ganga at Kithulgala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Deraniyagala' | Shape: (5, 4) | Columns (first 5): ['Seethawaka Ganga at Deraniyagala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Holombuwa' | Shape: (5, 4) | Columns (first 5): ['Gurugoda Oya at Holombuwa', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Glencourse' | Shape: (5, 4) | Columns (first 5): ['Kelani Ganga at Glencourse', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'Hanwella' | Shape: (5, 4) | Columns (first 5): ['Kelani Ganga at Hanwella', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
   └── Sheet: 'N'Street' | Shape: (5, 4) | Columns (first 5): ["Kelani Ganga at N'Street", 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']
------------------------------------------------------------
[✓ FOUND] Kelani - Discharge
 Path: flood/kelani/2015 - 2025 Discharge.xlsx
 Total Sheets: 6
   └── Sheet: 'Norwood' | Shape: (5, 32) | Columns (first 5): ['Kehelgamu Oya at Norwood', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Kithulgala' | Shape: (5, 32) | Columns (first 5): ['Kelani Ganga at Kithulgala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Deraniyagala' | Shape: (5, 33) | Columns (first 5): ['Seethawaka Ganga at Deraniyagala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Holombuwa' | Shape: (5, 32) | Columns (first 5): ['Gurugoda Oya at Holombuwa', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Glencourse' | Shape: (5, 32) | Columns (first 5): ['Kelani Ganga at Glencourse', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Hanwella' | Shape: (5, 32) | Columns (first 5): ['Kelani Ganga at Hanwella', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Kalu - Rathnapura Hydro
 Path: flood/kalu/Rathnapura.xlsx
 Total Sheets: 3
   └── Sheet: 'General Information' | Shape: (4, 2) | Columns (first 5): ['General Information', 'Unnamed: 1']
   └── Sheet: 'WL Summery MSL' | Shape: (5, 30) | Columns (first 5): ['RATHNAPURA WATER LEVELS in m (MSL)', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
   └── Sheet: 'Q' | Shape: (5, 30) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Landslide Records
 Path: landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx
 Total Sheets: 2
   └── Sheet: 'Nuwara Eliya Landslides' | Shape: (5, 17) | Columns (first 5): ['Serial', 'Event', 'Province', 'District', 'Division']
   └── Sheet: 'Notes' | Shape: (5, 1) | Columns (first 5): ['Notes']
------------------------------------------------------------
[✓ FOUND] Flood Records
 Path: disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx
 Total Sheets: 2
   └── Sheet: 'Ratnapura-Kegalle Floods' | Shape: (5, 17) | Columns (first 5): ['Serial', 'Event', 'Province', 'District', 'Division']
   └── Sheet: 'Notes' | Shape: (5, 1) | Columns (first 5): ['Notes']
------------------------------------------------------------
[✓ FOUND] Census - Population
 Path: census/GN_population_excel.xlsx
 Total Sheets: 1
   └── Sheet: 'Population' | Shape: (5, 17) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Census - Housing
 Path: census/GN_housing_excel.xlsx
 Total Sheets: 1
   └── Sheet: 'Housing Units' | Shape: (5, 10) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------
[✓ FOUND] Census - Households
 Path: census/HH_GND_excel.xlsx
 Total Sheets: 1
   └── Sheet: 'Households' | Shape: (5, 47) | Columns (first 5): ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
------------------------------------------------------------

In [5]:
import os
import pandas as pd
import numpy as np

raw_base = "../data/raw"

files = [
    ("2015 - 2025 RF.xlsx", "flood/kelani/2015 - 2025 RF.xlsx"),
    ("2015 - 2025 WL.xlsx", "flood/kelani/2015 - 2025 WL.xlsx"),
    ("2015 - 2025 Discharge.xlsx", "flood/kelani/2015 - 2025 Discharge.xlsx"),
    ("Rathnapura.xlsx", "flood/kalu/Rathnapura.xlsx"),
    ("DesInventar_NuwaraEliya_Landslides_page1.xlsx", "landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx"),
    ("DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx", "disaster_records/DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx"),
    ("GN_population_excel.xlsx", "census/GN_population_excel.xlsx"),
    ("GN_housing_excel.xlsx", "census/GN_housing_excel.xlsx"),
    ("HH_GND_excel.xlsx", "census/HH_GND_excel.xlsx")
]

for display_name, rel_path in files:
    full_path = os.path.join(raw_base, rel_path)
    print(f"\n==================================================")
    print(f"=== {display_name} ===")
    print(f"==================================================")
    print(f"Full Relative Path: {rel_path}")
    
    if not os.path.exists(full_path):
        print("❌ FILE NOT FOUND!")
        continue
        
    try:
        excel_file = pd.ExcelFile(full_path)
        sheet_names = excel_file.sheet_names
        print(f"Sheets ({len(sheet_names)}): {sheet_names}\n")
        
        for sheet in sheet_names:
            print(f"--- Sheet: {sheet} ---")
            # Read first 10 rows without header to inspect raw layout / title rows
            df_raw = pd.read_excel(full_path, sheet_name=sheet, header=None, nrows=10)
            
            # Read full sheet to get dimension and basic inspection
            df = pd.read_excel(full_path, sheet_name=sheet)
            print(f"Raw Shape: {df.shape} (Rows: {df.shape[0]}, Cols: {df.shape[1]})")
            
            print("\nHeader Sample (First 5 raw rows):")
            print(df_raw.head(5).to_string())
            
            print("\nInferred Columns:")
            print(list(df.columns))
            
            print("\nMissing Values Count (top 10 columns by missing):")
            nulls = df.isnull().sum()
            print(nulls[nulls > 0].head(10).to_string() if nulls.sum() > 0 else "No missing values detected.")
            
            # Detect potential date/year/time columns
            date_like_cols = [c for c in df.columns if any(term in str(c).lower() for term in ['date', 'year', 'month', 'time', 'day', 'serial', 'd1'])]
            if date_like_cols:
                print(f"\nDate / Time Columns Detected: {date_like_cols}")
            
            print("\n" + "-"*40)
            
    except Exception as e:
        print(f"Error reading {display_name}: {e}")

==================================================
=== 2015 - 2025 RF.xlsx ===
==================================================
Full Relative Path: flood/kelani/2015 - 2025 RF.xlsx
Sheets (6): ['KN02-NORWOOD', 'KN07-KITULGALA', ' KN11-HOLOMBUWA', 'KN16-DERANIYAGALA', 'KN18-GLENCOURSE', 'KN21-HANWELLA']

--- Sheet: KN02-NORWOOD ---
Raw Shape: (135, 35) (Rows: 135, Cols: 35)

Header Sample (First 5 raw rows):
                             0     1      2    3    4    5    6    7    8    9    10   11   12   13                                 14   15   16   17   18   19   20   21   22   23   24   25            26   27        28   29        30    31   32   33     34
0                           NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN       NaN  NaN       NaN   NaN  NaN  NaN    NaN
1  Norwood Daily Rainfall in mm   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  Cordinate :-  NaN  182051 X  NaN  182230 Y   NaN  NaN  NaN    NaN
2                           NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN       NaN  NaN       NaN   NaN  NaN  NaN    NaN
3                    Year/Month  YEAR  MONTH   D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  D11                                D12  D13  D14  D15  D16  D17  D18  D19  D20  D21  D22  D23           D24  D25       D26  D27       D28   D29  D30  D31  TOTAL
4                      14/15/04  2015    JAN    0    0    0    0    0  1.7    0    0    0    0    0                                  0    0    0    0    0    0    0    0    0    0    0    0             0    0         0    0      11.7  23.4  4.6  0.5   41.9

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    1
Unnamed: 1    2
Unnamed: 2    2
Unnamed: 3    2
Unnamed: 4    2
Unnamed: 5    2
Unnamed: 6    2
Unnamed: 7    2
Unnamed: 8    2
Unnamed: 9    2

----------------------------------------
--- Sheet: KN07-KITULGALA ---
Raw Shape: (135, 35) (Rows: 135, Cols: 35)

Header Sample (First 5 raw rows):
                                0     1      2    3    4    5    6    7    8    9    10   11   12   13                                 14   15   16   17   18   19   20   21   22   23   24    25            26   27        28   29        30    31   32   33     34
0                              NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN           NaN  NaN       NaN  NaN       NaN   NaN  NaN  NaN    NaN
1  Kithulgala Daily Rainfall in mm   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  Cordinate :-  NaN  160270 X  NaN  198922 Y   NaN  NaN  NaN    NaN
2                              NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN           NaN  NaN       NaN  NaN       NaN   NaN  NaN  NaN    NaN
3                       Year/Month  YEAR  MONTH   D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  D11                                D12  D13  D14  D15  D16  D17  D18  D19  D20  D21  D22   D23           D24  D25       D26  D27       D28   D29  D30  D31  TOTAL
4                         14/15/04  2015    JAN    0    0    0    0    0  5.3    0    0    0    0    0                                  0    0    0    0    0    0    0    0    0    0    0  33.1             0    0         0    0       2.8  26.9  1.5    0   69.6

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    1
Unnamed: 1    2
Unnamed: 2    2
Unnamed: 3    2
Unnamed: 4    2
Unnamed: 5    2
Unnamed: 6    2
Unnamed: 7    2
Unnamed: 8    2
Unnamed: 9    2

----------------------------------------
--- Sheet:  KN11-HOLOMBUWA ---
Raw Shape: (135, 35) (Rows: 135, Cols: 35)

Header Sample (First 5 raw rows):
                               0     1      2    3    4    5    6    7    8    9    10   11   12   13                                 14   15   16   17   18   19   20   21   22   23   24   25   26            27   28        29   30        31   32   33     34
0                             NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN       NaN  NaN       NaN  NaN  NaN    NaN
1  Holombuwa Daily Rainfall in mm   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  Cordinate :-  NaN  143948 X  NaN  220765 Y  NaN  NaN    NaN
2                             NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN       NaN  NaN       NaN  NaN  NaN    NaN
3                       YEARMONTH  YEAR  MONTH   D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  D11                                D12  D13  D14  D15  D16  D17  D18  D19  D20  D21  D22  D23  D24           D25  D26       D27  D28       D29  D30  D31  TOTAL
4                        14/15/04  2015    JAN    0    0    0    0    0    0    0    0    0    0    0                                  0    0    0    0    0    0    0    0    0    0    0    0    0             0    0         0  3.6         0  2.5    0    6.1

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    1
Unnamed: 1    2
Unnamed: 2    2
Unnamed: 3    2
Unnamed: 4    2
Unnamed: 5    2
Unnamed: 6    2
Unnamed: 7    2
Unnamed: 8    2
Unnamed: 9    2

----------------------------------------
--- Sheet: KN16-DERANIYAGALA ---
Raw Shape: (135, 35) (Rows: 135, Cols: 35)

Header Sample (First 5 raw rows):
                                  0     1      2    3    4    5    6    7    8    9    10   11   12   13                                 14   15   16   17   18   19   20   21   22   23   24   25   26            27   28        29   30        31    32   33     34
0                                NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN       NaN  NaN       NaN   NaN  NaN    NaN
1  Deraniyagala Daily Rainfall in mm   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  Cordinate :-  NaN  152036 X  NaN  191688 Y   NaN  NaN    NaN
2                                NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN           NaN  NaN       NaN  NaN       NaN   NaN  NaN    NaN
3                          YEARMONTH  YEAR  MONTH   D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  D11                                D12  D13  D14  D15  D16  D17  D18  D19  D20  D21  D22  D23  D24           D25  D26       D27  D28       D29   D30  D31  TOTAL
4                           14/15/04  2015    JAN    0    0    0    0    0    0    0    0    0    0    0                                  0    0    0    0    0    0    0    0    0    0    0   30    0             0    0         0  4.1      41.5  50.5    0  126.1

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    1
Unnamed: 1    2
Unnamed: 2    2
Unnamed: 3    2
Unnamed: 4    2
Unnamed: 5    2
Unnamed: 6    2
Unnamed: 7    2
Unnamed: 8    2
Unnamed: 9    2

----------------------------------------
--- Sheet: KN18-GLENCOURSE ---
Raw Shape: (135, 35) (Rows: 135, Cols: 35)

Header Sample (First 5 raw rows):
                                0     1      2    3    4    5    6    7    8    9    10   11   12   13                                 14   15   16   17   18   19   20   21   22   23   24    25   26            27   28        29   30        31   32   33     34
0                              NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN           NaN  NaN       NaN  NaN       NaN  NaN  NaN    NaN
1  Glencourse Daily Rainfall in mm   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  Cordinate :-  NaN  135963 X  NaN  197396 Y  NaN  NaN    NaN
2                              NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN           NaN  NaN       NaN  NaN       NaN  NaN  NaN    NaN
3                        YEARMONTH  YEAR  MONTH   D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  D11                                D12  D13  D14  D15  D16  D17  D18  D19  D20  D21  D22   D23  D24           D25  D26       D27  D28       D29  D30  D31  TOTAL
4                         14/15/04  2015    JAN    0    0    0    0    0    0    0    0    0    0    0                                  0    0    0    0    0    0    0    0    0    0    0  38.9    0             0    0         0  0.3      36.8  6.7    0   82.7

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    1
Unnamed: 1    2
Unnamed: 2    2
Unnamed: 3    2
Unnamed: 4    2
Unnamed: 5    2
Unnamed: 6    2
Unnamed: 7    2
Unnamed: 8    2
Unnamed: 9    2

----------------------------------------
--- Sheet: KN21-HANWELLA ---
Raw Shape: (135, 35) (Rows: 135, Cols: 35)

Header Sample (First 5 raw rows):
                              0     1      2    3    4    5    6    7    8    9    10   11   12   13                                 14   15   16   17   18   19   20   21   22   23   24    25    26            27   28        29   30        31    32   33     34
0                            NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN           NaN  NaN       NaN  NaN       NaN   NaN  NaN    NaN
1  Hanwella Daily Rainfall in mm   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN  Cordinate :-  NaN  123689 X  NaN  189980 Y   NaN  NaN    NaN
2                            NaN   NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN           NaN  NaN       NaN  NaN       NaN   NaN  NaN    NaN
3                      YEARMONTH  YEAR  MONTH   D1   D2   D3   D4   D5   D6   D7   D8   D9  D10  D11                                D12  D13  D14  D15  D16  D17  D18  D19  D20  D21  D22   D23   D24           D25  D26       D27  D28       D29   D30  D31  TOTAL
4                       14/15/04  2015    JAN    0    0    0    0    0    0    0    0    0    0    0                                  0    0    0    0    0    0    0    0    0    0    0  16.4  16.6             0    0       0.6  8.4      39.9  10.5    0   92.4

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    1
Unnamed: 1    2
Unnamed: 2    2
Unnamed: 3    2
Unnamed: 4    2
Unnamed: 5    2
Unnamed: 6    2
Unnamed: 7    2
Unnamed: 8    2
Unnamed: 9    2

----------------------------------------

==================================================
=== 2015 - 2025 WL.xlsx ===
==================================================
Full Relative Path: flood/kelani/2015 - 2025 WL.xlsx
Sheets (7): ['Norwood', 'Kithulgala', 'Deraniyagala', 'Holombuwa', 'Glencourse', 'Hanwella', "N'Street"]

--- Sheet: Norwood ---
Raw Shape: (11322, 29) (Rows: 11322, Cols: 29)

Header Sample (First 5 raw rows):
                            0         1     2        3
0    Kehelgamu Oya at Norwood       NaN   NaN      NaN
1  Hourly Water Level in mMSL       NaN   NaN      NaN
2                         MSL  1097.76m   NaN      NaN
3                         NaN       NaN   NaN      NaN
4                        Year     Month  Date  Avg. WL

Inferred Columns:
['Kehelgamu Oya at Norwood', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']

Missing Values Count (top 10 columns by missing):
Kehelgamu Oya at Norwood        1
Unnamed: 1                      2
Unnamed: 2                    363
Unnamed: 3                    372
Unnamed: 4                  11321
Unnamed: 5                  11320
Unnamed: 6                  11320
Unnamed: 7                  11320
Unnamed: 8                  11320
Unnamed: 9                  11320

----------------------------------------
--- Sheet: Kithulgala ---
Raw Shape: (11322, 4) (Rows: 11322, Cols: 4)

Header Sample (First 5 raw rows):
                            0        1     2        3
0  Kelani Ganga at Kithulgala      NaN   NaN      NaN
1  Hourly Water Level in mMSL      NaN   NaN      NaN
2                         MSL  52.123m   NaN      NaN
3                         NaN      NaN   NaN      NaN
4                        Year    Month  Date  Avg. WL

Inferred Columns:
['Kelani Ganga at Kithulgala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

Missing Values Count (top 10 columns by missing):
Kelani Ganga at Kithulgala      1
Unnamed: 1                      2
Unnamed: 2                    113
Unnamed: 3                    364

----------------------------------------
--- Sheet: Deraniyagala ---
Raw Shape: (4154, 4) (Rows: 4154, Cols: 4)

Header Sample (First 5 raw rows):
                                  0       1     2        3
0  Seethawaka Ganga at Deraniyagala     NaN   NaN      NaN
1        Hourly Water Level in mMSL     NaN   NaN      NaN
2                               MSL  73.21m   NaN      NaN
3                               NaN     NaN   NaN      NaN
4                              Year   Month  Date  Avg. WL

Inferred Columns:
['Seethawaka Ganga at Deraniyagala', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

Missing Values Count (top 10 columns by missing):
Seethawaka Ganga at Deraniyagala      1
Unnamed: 1                            2
Unnamed: 2                          135
Unnamed: 3                          135

----------------------------------------
--- Sheet: Holombuwa ---
Raw Shape: (4154, 4) (Rows: 4154, Cols: 4)

Header Sample (First 5 raw rows):
                            0       1     2        3
0   Gurugoda Oya at Holombuwa     NaN   NaN      NaN
1  Hourly Water Level in mMSL     NaN   NaN      NaN
2                         MSL  44.55m   NaN      NaN
3                         NaN     NaN   NaN      NaN
4                        Year   Month  Date  Avg. WL

Inferred Columns:
['Gurugoda Oya at Holombuwa', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

Missing Values Count (top 10 columns by missing):
Gurugoda Oya at Holombuwa      1
Unnamed: 1                     2
Unnamed: 2                    90
Unnamed: 3                   135

----------------------------------------
--- Sheet: Glencourse ---
Raw Shape: (4154, 4) (Rows: 4154, Cols: 4)

Header Sample (First 5 raw rows):
                            0          1     2        3
0  Kelani Ganga at Glencourse        NaN   NaN      NaN
1  Hourly Water Level in mMSL        NaN   NaN      NaN
2                         MSL  (-0.118)m   NaN      NaN
3                         NaN        NaN   NaN      NaN
4                        Year      Month  Date  Avg. WL

Inferred Columns:
['Kelani Ganga at Glencourse', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

Missing Values Count (top 10 columns by missing):
Kelani Ganga at Glencourse      1
Unnamed: 1                      2
Unnamed: 2                    135
Unnamed: 3                    135

----------------------------------------
--- Sheet: Hanwella ---
Raw Shape: (4154, 4) (Rows: 4154, Cols: 4)

Header Sample (First 5 raw rows):
                            0      1     2        3
0    Kelani Ganga at Hanwella    NaN   NaN      NaN
1  Hourly Water Level in mMSL    NaN   NaN      NaN

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

Raw Shape: (14012, 17) (Rows: 14012, Cols: 17)

Header Sample (First 5 raw rows):
                                                                                                                      0               1               2               3                  4                  5                  6                  7                    8      9     10      11         12      13       14       15             16
0                                                                                                                    NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN    NaN   NaN     NaN        NaN     NaN      NaN      NaN            NaN
1  Census of Population and Housing - 2024\nGrama Niladhari Division Level Population by Sex and Age Group (Provisional)             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN    NaN   NaN     NaN        NaN     NaN      NaN      NaN            NaN
2                                                                                                                    NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN    NaN   NaN     NaN        NaN     NaN      NaN      NaN            NaN
3                                                                                                         Province\nCode  Province\nName  District\nCode  District\nName  DS_Division\nCode  DS_Division\nName  GN_Division\nCode  GN_Division\nName  GN_Division\nNumber    Sex   NaN     NaN  Age_Group     NaN      NaN      NaN            NaN
4                                                                                                                    NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN  Total  Male  Female      Total  0 - 14  15 - 59  60 - 64   65 and above

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    2
Unnamed: 1    3
Unnamed: 2    3
Unnamed: 3    3
Unnamed: 4    3
Unnamed: 5    3
Unnamed: 6    3
Unnamed: 7    3
Unnamed: 8    3
Unnamed: 9    2

----------------------------------------

==================================================
=== GN_housing_excel.xlsx ===
==================================================
Full Relative Path: census/GN_housing_excel.xlsx
Sheets (1): ['Housing Units']

--- Sheet: Housing Units ---

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

Raw Shape: (14012, 10) (Rows: 14012, Cols: 10)

Header Sample (First 5 raw rows):
                                                                                                           0               1               2               3                  4                  5                  6                  7                    8                       9
0                                                                                                        NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                     NaN
1  Census of Population and Housing - 2024\nOccupied Housing Units by Grama Niladhari Division (Provisional)             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                     NaN
2                                                                                                        NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                     NaN
3                                                                                             Province\nCode  Province\nName  District\nCode  District\nName  DS_Division\nCode  DS_Division\nName  GN_Division\nCode  GN_Division\nName  GN_Division\nNumber  Occupied Housing Units
4                                                                                                        NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                     NaN

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    2
Unnamed: 1    3
Unnamed: 2    3
Unnamed: 3    3
Unnamed: 4    3
Unnamed: 5    3
Unnamed: 6    3
Unnamed: 7    3
Unnamed: 8    3
Unnamed: 9    3

----------------------------------------

==================================================
=== HH_GND_excel.xlsx ===
==================================================
Full Relative Path: census/HH_GND_excel.xlsx
Sheets (1): ['Households']

--- Sheet: Households ---
Raw Shape: (14013, 47) (Rows: 14013, Cols: 47)

Header Sample (First 5 raw rows):
                                                                                                         0               1               2               3                  4                  5                  6                  7                    8                     9                                  10   11   12   13   14                15   16   17   18     19   20   21   22   23   24                                           25   26   27   28   29   30   31   32                       33   34   35   36   37   38   39                 40   41                42   43     44   45   46
0                                                                                                       NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                                NaN  NaN  NaN  NaN  NaN               NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN                                          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                      NaN  NaN  NaN  NaN  NaN  NaN  NaN                NaN  NaN               NaN  NaN    NaN  NaN  NaN
1  Census of Population and Housing - 2024\nHousehold Information by Grama Niladhari Division (Provisional)             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                                NaN  NaN  NaN  NaN  NaN               NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN                                          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                      NaN  NaN  NaN  NaN  NaN  NaN  NaN                NaN  NaN               NaN  NaN    NaN  NaN  NaN
2                                                                                                       NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                                NaN  NaN  NaN  NaN  NaN               NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN                                          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                      NaN  NaN  NaN  NaN  NaN  NaN  NaN                NaN  NaN               NaN  NaN    NaN  NaN  NaN
3                                                                                            Province\nCode  Province\nName  District\nCode  District\nName  DS_Division\nCode  DS_Division\nName  GN_Division\nCode  GN_Division\nName  GN_Division\nNumber  Number of Households  Main Source/way of drinking water  NaN  NaN  NaN  NaN               NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN  Main Source of Energy/Fuel Used for Cooking  NaN  NaN  NaN  NaN  NaN  NaN  NaN  Main source of Lighting  NaN  NaN  NaN  NaN  NaN  NaN  Toilet facilities  NaN               NaN  NaN    NaN  NaN  NaN
4                                                                                                       NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                       Ground Water  NaN  NaN  NaN  NaN  Pipe Borne water  NaN  NaN  NaN  Other  NaN  NaN  NaN  NaN  NaN                                          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN                      NaN  NaN  NaN  NaN  NaN  NaN  NaN    Within the unit  NaN  Outside the unit  NaN  Other  NaN  NaN

Inferred Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46']

Missing Values Count (top 10 columns by missing):
Unnamed: 0    3
Unnamed: 1    4
Unnamed: 2    4
Unnamed: 3    4
Unnamed: 4    4
Unnamed: 5    4
Unnamed: 6    4
Unnamed: 7    4
Unnamed: 8    4
Unnamed: 9    4

----------------------------------------

In [7]:
import pandas as pd

files_to_inspect = {
    "Rainfall": "data/raw/flood/kelani/2015 - 2025 RF.xlsx",
    "Water Level": "data/raw/flood/kelani/2015 - 2025 WL.xlsx",
    "Discharge": "data/raw/flood/kelani/2015 - 2025 Discharge.xlsx",
    "Rathnapura": "data/raw/flood/rathnapura/Rathnapura.xlsx"  # Adjust path if located elsewhere
}

for label, file_path in files_to_inspect.items():
    print("#" * 80)
    print(f" FILE CATEGORY: {label}")
    print(f" PATH: {file_path}")
    print("#" * 80)
    
    try:
        excel = pd.ExcelFile(file_path)
        print("Sheet names:", excel.sheet_names)
        
        for sheet in excel.sheet_names:
            print("\n" + "=" * 80)
            print(f"SHEET: {sheet}")
            print("=" * 80)
            
            # Read first 10 rows raw without setting headers or skipping rows
            df = pd.read_excel(file_path, sheet_name=sheet, header=None, nrows=10)
            print(df.to_string(index=True, header=False))
            print("\n")
            
    except Exception as e:
        print(f"Error reading {file_path}: {e}\n")

################################################################################
 FILE CATEGORY: Rainfall
 PATH: data/raw/flood/kelani/2015 - 2025 RF.xlsx
################################################################################
Error reading data/raw/flood/kelani/2015 - 2025 RF.xlsx: [Errno 2] No such file or directory: 'data/raw/flood/kelani/2015 - 2025 RF.xlsx'

################################################################################
 FILE CATEGORY: Water Level
 PATH: data/raw/flood/kelani/2015 - 2025 WL.xlsx
################################################################################
Error reading data/raw/flood/kelani/2015 - 2025 WL.xlsx: [Errno 2] No such file or directory: 'data/raw/flood/kelani/2015 - 2025 WL.xlsx'

################################################################################
 FILE CATEGORY: Discharge
 PATH: data/raw/flood/kelani/2015 - 2025 Discharge.xlsx
################################################################################
Error reading data/raw/flood/kelani/2015 - 2025 Discharge.xlsx: [Errno 2] No such file or directory: 'data/raw/flood/kelani/2015 - 2025 Discharge.xlsx'

################################################################################
 FILE CATEGORY: Rathnapura
 PATH: data/raw/flood/rathnapura/Rathnapura.xlsx
################################################################################
Error reading data/raw/flood/rathnapura/Rathnapura.xlsx: [Errno 2] No such file or directory: 'data/raw/flood/rathnapura/Rathnapura.xlsx'

In [8]:
import os
from pathlib import Path

# Print current working directory
print("Current Working Directory:", os.getcwd())

# Search for any Excel files in the working directory or subdirectories
print("\nSearching for Excel files...")
found_files = list(Path(".").glob("**/*.xlsx"))

if found_files:
    for f in found_files:
        print("  Found:", f)
else:
    print("  No .xlsx files found in current directory or subdirectories.")

Current Working Directory: /Users/ohaseelanka/disaster_analytics_hub/notebooks

Searching for Excel files...
  No .xlsx files found in current directory or subdirectories.

In [9]:
import os
from pathlib import Path
import pandas as pd

# Set working directory relative to notebook location or project root
project_root = Path("..").resolve()
print("Project Root Directory:", project_root)

files_to_inspect = {
    "Rainfall": project_root / "data/raw/flood/kelani/2015 - 2025 RF.xlsx",
    "Water Level": project_root / "data/raw/flood/kelani/2015 - 2025 WL.xlsx",
    "Discharge": project_root / "data/raw/flood/kelani/2015 - 2025 Discharge.xlsx",
    "Rathnapura": project_root / "data/raw/flood/rathnapura/Rathnapura.xlsx"
}

for label, file_path in files_to_inspect.items():
    print("#" * 80)
    print(f" FILE CATEGORY: {label}")
    print(f" PATH: {file_path}")
    print("#" * 80)
    
    if not file_path.exists():
        print(f"❌ FILE NOT FOUND AT: {file_path}\n")
        continue
        
    try:
        excel = pd.ExcelFile(file_path)
        print("Sheet names:", excel.sheet_names)
        
        for sheet in excel.sheet_names:
            print("\n" + "=" * 80)
            print(f"SHEET: {sheet}")
            print("=" * 80)
            
            df = pd.read_excel(file_path, sheet_name=sheet, header=None, nrows=10)
            print(df.to_string(index=True, header=False))
            print("\n")
            
    except Exception as e:
        print(f"Error reading {file_path}: {e}\n")

Project Root Directory: /Users/ohaseelanka/disaster_analytics_hub
################################################################################
 FILE CATEGORY: Rainfall
 PATH: /Users/ohaseelanka/disaster_analytics_hub/data/raw/flood/kelani/2015 - 2025 RF.xlsx
################################################################################
Sheet names: ['KN02-NORWOOD', 'KN07-KITULGALA', ' KN11-HOLOMBUWA', 'KN16-DERANIYAGALA', 'KN18-GLENCOURSE', 'KN21-HANWELLA']

================================================================================
SHEET: KN02-NORWOOD
================================================================================
0                           NaN   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN                                NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN  NaN  NaN    NaN
1  Norwood Daily Rainfall in mm   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN  Cordinate :-   NaN  182051 X   NaN  182230 Y   NaN  NaN  NaN    NaN
2                           NaN   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN                                NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN  NaN  NaN    NaN
3                    Year/Month  YEAR  MONTH   D1    D2    D3    D4    D5    D6   D7   D8    D9   D10   D11                                D12   D13  D14   D15   D16   D17   D18   D19  D20  D21  D22   D23           D24   D25       D26   D27       D28   D29  D30  D31  TOTAL
4                      14/15/04  2015    JAN    0     0     0     0     0   1.7    0    0     0     0     0                                  0     0    0     0     0     0     0     0    0    0    0     0             0     0         0     0      11.7  23.4  4.6  0.5   41.9
5                      14/15/05  2015    FEB    0     0  10.4     0  25.9  23.9    0    0     0  13.2  12.3                               15.1   1.2    0     0     0     0     0     0    0    0  3.8     5           7.2     0      12.5    20      31.7   NaN  NaN  NaN  182.2
6                      14/15/06  2015    MAR  3.7     0     0  20.3   2.5     0    0    0     0     0     0                                  4   4.2  0.6     0   4.8     0     0     0    0    0    0     0             0     0      25.4   1.3       1.8   4.6    7  5.5   85.7
7                      14/15/07  2015    APR   39  26.8   0.7  13.1     0   0.3  9.4  1.3  31.3   7.4     0                                  0  13.9    3    48   7.9     0     0   4.8  8.3    0    0  12.5          39.3  21.4       1.2  38.8       1.2   3.1  8.7  NaN  341.4
8                      14/15/08  2015    MAY  1.9     0     0   3.6  29.9   9.7  1.2    0   3.7  43.3     0                                  0   1.1    0  14.1   1.8   2.1   1.2   3.1    0  1.7    0   1.7             0     0         0     0         0     0    0  5.1  125.2
9                      14/15/09  2015    JUN    0     0   1.3   4.2  16.5     0    0    0     0     0   1.5                                  0     0    0  11.3  48.5  28.9  38.5  12.4  0.9    0    0     0           1.6     0       7.6  16.7       8.1   7.8  1.3  NaN  207.1



================================================================================
SHEET: KN07-KITULGALA
================================================================================
0                              NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN                                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN   NaN    NaN
1  Kithulgala Daily Rainfall in mm   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  Cordinate :-   NaN  160270 X   NaN  198922 Y   NaN   NaN   NaN    NaN
2                              NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN                                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN   NaN    NaN
3                       Year/Month  YEAR  MONTH    D1    D2    D3    D4    D5    D6    D7    D8    D9   D10   D11                                D12   D13   D14   D15   D16   D17   D18   D19   D20   D21  D22   D23           D24   D25       D26   D27       D28   D29   D30   D31  TOTAL
4                         14/15/04  2015    JAN     0     0     0     0     0   5.3     0     0     0     0     0                                  0     0     0     0     0     0     0     0     0     0    0  33.1             0     0         0     0       2.8  26.9   1.5     0   69.6
5                         14/15/05  2015    FEB     0     0    21     0   0.4   1.7     0     0     8   7.9  16.5                                6.6   0.7     0     0     0     0     0     0     0     0    0   0.3           0.5  11.2      31.3  37.4       8.1   NaN   NaN   NaN  151.6
6                         14/15/06  2015    MAR  55.8     0     0   2.9     0     0     0     0     0     0     0                                0.6  18.7  13.6  52.9   1.9     2     0     0     0     0    0     0             0     0         9     0      53.1  20.5   2.4   2.8  236.2
7                         14/15/07  2015    APR   6.9  14.5     0     0     0     0   5.6     0  13.8  17.4     0                               11.4  10.3     6  36.2  14.2   6.4   1.4   3.7  24.9   0.7    0  25.2           7.4  23.4      17.2   1.1      24.8    19   4.4   NaN  295.9
8                         14/15/08  2015    MAY  18.6   9.6  13.2  12.4  46.5  35.7  47.9  14.6    15  92.8     0                                  0     0    17   6.6   9.8   7.7    20  11.6   6.8  11.8  1.1  44.3             1     0       3.6   2.8         0   8.6    22  43.2  524.2
9                         14/15/09  2015    JUN   7.7     3  16.8  13.2  68.8     0     0   0.5   2.2   0.5  16.6                                1.7   0.7   0.8    73    41  34.1  44.5   9.1     0     4  1.4     0           2.8     0      20.1    20        52  36.6  21.3   NaN  492.4



================================================================================
SHEET:  KN11-HOLOMBUWA
================================================================================
0                             NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN  NaN   NaN  NaN                                NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
1  Holombuwa Daily Rainfall in mm   NaN    NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN  NaN   NaN  NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN  Cordinate :-   NaN  143948 X   NaN  220765 Y   NaN   NaN    NaN
2                             NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN  NaN   NaN  NaN                                NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
3                       YEARMONTH  YEAR  MONTH    D1    D2    D3    D4    D5   D6    D7   D8   D9   D10  D11                                D12   D13   D14   D15   D16   D17  D18   D19   D20  D21  D22  D23   D24           D25   D26       D27   D28       D29   D30   D31  TOTAL
4                        14/15/04  2015    JAN     0     0     0     0     0    0     0    0    0     0    0                                  0     0     0     0     0     0    0     0     0    0    0    0     0             0     0         0   3.6         0   2.5     0    6.1
5                        14/15/05  2015    FEB     0     0  13.5     0   0.3    0     0    0  1.7   7.7    0                                  7     0     0     0     0     0    0     0     0    0    0   12  18.5             0     2       2.3     0       NaN   NaN   NaN     65
6                        14/15/06  2015    MAR  13.4   2.6     0  38.7     0    0     0    0    0     0    0                                  0  28.6     0  69.7  18.1     0    0     0     0    0    0    0     0             0   4.2         0  12.8      19.4  13.1  23.1  243.7
7                        14/15/07  2015    APR  11.7  50.4     0     0     0    7   7.3    0  2.5    31    0                                9.8  50.5  25.7   9.5   2.9     0    0  25.7  45.2  6.1    0  1.2  14.5          17.8  12.6      22.9     0      13.8  13.7   NaN  381.8
8                        14/15/08  2015    MAY     0  16.8   6.4     0     0    0  39.2  2.6  5.3  17.1  0.2                                  0   0.3   3.9   0.8   7.3  19.1   26  17.4   1.9  9.5  1.7  0.5     0             0     0         0     0         0   0.6  32.6  209.2
9                        14/15/09  2015    JUN   8.7     0    16  13.7  19.8    0     0    5    2     0  7.2                                  0   2.8     0  33.2   7.5   8.9  7.5     5     0    0  3.9    0   0.6             0    14      28.3   6.6      14.5  16.5   NaN  221.7



================================================================================
SHEET: KN16-DERANIYAGALA
================================================================================
0                                NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN                                NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
1  Deraniyagala Daily Rainfall in mm   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN   NaN   NaN  Cordinate :-   NaN  152036 X   NaN  191688 Y   NaN   NaN    NaN
2                                NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN                                NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
3                          YEARMONTH  YEAR  MONTH    D1    D2    D3     D4    D5    D6    D7    D8    D9   D10   D11                                D12  D13   D14   D15   D16   D17   D18   D19  D20   D21  D22   D23   D24           D25   D26       D27   D28       D29   D30   D31  TOTAL
4                           14/15/04  2015    JAN     0     0     0      0     0     0     0     0     0     0     0                                  0    0     0     0     0     0     0     0    0     0    0    30     0             0     0         0   4.1      41.5  50.5     0  126.1
5                           14/15/05  2015    FEB     0     0     9      0   0.7   2.3     0     0  45.1  59.7  64.3                               65.1    0     0     0     0     0     0     0    0     0    0   3.8  41.2             0   1.7      10.3  30.7       NaN   NaN   NaN  333.9
6                           14/15/06  2015    MAR  30.7  53.8  20.5    1.8     4     0     0     0   0.6     0     0                               12.8    0   3.6  57.8     0     0     0     0    0     0    0     0     0             0   6.5      14.5  15.6      24.8     0  55.7  302.7
7                           14/15/07  2015    APR   4.5  81.8     0    2.1     0  68.3  34.7     0     0  35.7     0                               87.3    2   1.3   6.8     0     0   4.2  70.6  7.2    96    0  70.9  27.9            37     0     150.4     0      32.6  33.3   NaN  854.6
8                           14/15/08  2015    MAY   6.7   1.4  35.3  113.7   6.3   6.3  58.5  10.6   1.8  13.7     0                                  0    0  18.5   3.7     3  16.3  20.3  13.5  5.4  14.4    2   4.8     0             0   9.2         0     0         0     0  74.9  440.3
9                           14/15/09  2015    JUN  14.5   4.6  44.1   29.2  80.8     0     0     0   7.2   6.1     9                                0.6  2.7   1.6  45.9  28.7  12.7  25.5  11.3    0     0  0.9     0   7.3             0  21.8      27.9  17.6      38.3   4.8   NaN  443.1



================================================================================
SHEET: KN18-GLENCOURSE
================================================================================
0                              NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN  NaN   NaN   NaN   NaN                                NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN     NaN
1  Glencourse Daily Rainfall in mm   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN  NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  Cordinate :-   NaN  135963 X   NaN  197396 Y   NaN   NaN     NaN
2                              NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN  NaN   NaN   NaN   NaN                                NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN     NaN
3                        YEARMONTH  YEAR  MONTH    D1    D2    D3     D4    D5    D6     D7   D8    D9   D10   D11                                D12  D13   D14   D15   D16   D17   D18   D19   D20   D21  D22   D23   D24           D25   D26       D27   D28       D29   D30   D31   TOTAL
4                         14/15/04  2015    JAN     0     0     0      0     0     0      0    0     0     0     0                                  0    0     0     0     0     0     0     0     0     0    0  38.9     0             0     0         0   0.3      36.8   6.7     0    82.7
5                         14/15/05  2015    FEB     0     0   2.6      0   0.8   3.6      0    0  14.9  10.2   3.6                               29.7  7.9     0     0     0     0     0     0     0     0    0     0  13.7             0  11.5        32   1.1       NaN   NaN   NaN   131.6
6                         14/15/06  2015    MAR     0  14.8     0   22.4   0.8     0      0    0   7.3     0     0                               14.6  4.2   1.4  48.7   6.1     0     0     0     0     0    0     0     0             0  59.7         7  87.2        16  15.1  18.2   323.5
7                         14/15/07  2015    APR  15.4   7.3     0      0     0  80.6  19.39    0     0   3.1    10                               37.9  8.2   3.4     0     0   0.9  35.5  61.1  48.5  95.5    0   1.7  24.8           3.3  48.8       2.3  11.5      62.2   0.3   NaN  581.69
8                         14/15/08  2015    MAY  36.1  10.1  53.5      9   0.3    10    4.3   23   1.8  29.1     0                                  0  1.1  10.9   1.4   0.6   7.9  14.9  13.5  14.5   9.3  0.9   3.6   0.3             0     0         0     0       0.5   0.9  19.4   276.9
9                         14/15/09  2015    JUN  22.2   0.6  10.7  104.8  16.5     0      0    0   2.5     0  86.6                                0.3  6.5   1.4  36.1  20.8  12.3  22.7  12.9     0     0  2.8     0   0.9           1.4  30.2        11  14.3       5.1   0.9   NaN   423.5



================================================================================
SHEET: KN21-HANWELLA
================================================================================
0                            NaN   NaN    NaN   NaN  NaN   NaN   NaN  NaN   NaN   NaN  NaN   NaN  NaN   NaN                                NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
1  Hanwella Daily Rainfall in mm   NaN    NaN   NaN  NaN   NaN   NaN  NaN   NaN   NaN  NaN   NaN  NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN  Cordinate :-   NaN  123689 X   NaN  189980 Y   NaN   NaN    NaN
2                            NaN   NaN    NaN   NaN  NaN   NaN   NaN  NaN   NaN   NaN  NaN   NaN  NaN   NaN                                NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
3                      YEARMONTH  YEAR  MONTH    D1   D2    D3    D4   D5    D6    D7   D8    D9  D10   D11                                D12   D13   D14   D15   D16  D17   D18   D19  D20  D21  D22   D23   D24           D25   D26       D27   D28       D29   D30   D31  TOTAL
4                       14/15/04  2015    JAN     0    0     0     0    0     0     0    0     0    0     0                                  0     0     0     0     0    0     0     0    0    0    0  16.4  16.6             0     0       0.6   8.4      39.9  10.5     0   92.4
5                       14/15/05  2015    FEB     0    0   7.8     0  2.2  48.6     0    0  78.5   63  16.5                                2.7   1.3     0     0     0    0     0     0    0    0    0     0   2.3             0   3.3       4.6   0.3       NaN   NaN   NaN  231.1
6                       14/15/06  2015    MAR     0    0   1.3  19.6    0     0     0    0  38.3    0     0                                  0  14.4  20.9  38.3   3.3   18     0     0    0    0    0     0     0             0   2.3       2.5  68.5       1.2  15.1    29  272.7
7                       14/15/07  2015    APR  56.8  2.2     0     0    0     0  17.7    0     0    1  30.5                               29.2  23.5   6.2     0     0    0     0  12.1   13  2.6    0     0   7.3           1.5     0      34.2     0       6.7  12.8   NaN  257.3
8                       14/15/08  2015    MAY   3.8  9.5     0   3.2   15   3.5   9.1  5.6   3.3  7.4   2.5                                  0   4.5  22.2     0   1.3  5.1  16.7  20.9  7.8  6.8  0.3   6.6     0             0     0         0     0         0   0.4  25.1  180.6
9                       14/15/09  2015    JUN   7.9  0.8  22.8    98  5.5   1.4   1.3    0     0    0  54.4                                1.8     2     0  38.4  31.6  3.2  27.9     6  0.7    0  2.5     0   0.8             0  23.5      15.8  23.5       6.1     0   NaN  375.9


################################################################################
 FILE CATEGORY: Water Level
 PATH: /Users/ohaseelanka/disaster_analytics_hub/data/raw/flood/kelani/2015 - 2025 WL.xlsx
################################################################################
Sheet names: ['Norwood', 'Kithulgala', 'Deraniyagala', 'Holombuwa', 'Glencourse', 'Hanwella', "N'Street"]

================================================================================
SHEET: Norwood
================================================================================
0    Kehelgamu Oya at Norwood       NaN   NaN          NaN
1  Hourly Water Level in mMSL       NaN   NaN          NaN
2                         MSL  1097.76m   NaN          NaN
3                         NaN       NaN   NaN          NaN
4                        Year     Month  Date      Avg. WL
5                        1996         1     1  1098.211667
6                        1996         1     2  1098.253333
7                        1996         1     3  1098.202917
8                        1996         1     4  1098.143333
9                        1996         1     5    1098.1125



================================================================================
SHEET: Kithulgala
================================================================================
0  Kelani Ganga at Kithulgala      NaN   NaN        NaN
1  Hourly Water Level in mMSL      NaN   NaN        NaN
2                         MSL  52.123m   NaN        NaN
3                         NaN      NaN   NaN        NaN

In [10]:
import os
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = "/Users/ohaseelanka/disaster_analytics_hub"
RAW_DIR = os.path.join(PROJECT_ROOT, "data/raw/flood/kelani")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data/processed/flood/kelani")

os.makedirs(PROCESSED_DIR, exist_ok=True)

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

def clean_station_name(name):
    """Cleans sheet names to standard station identifier."""
    name = re.sub(r'^[Kk][Nn]\d+[-_\s]*', '', name)
    name = name.replace("N'Street", "N_Street").strip()
    return name.title()


def parse_rainfall(file_path):
    """Processes Rainfall Excel Workbook into long format."""
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        # Extract coordinates if present in header row 1
        coord_row = df_raw.iloc[1].dropna().astype(str).str.cat(sep=" ")
        x_match = re.search(r'(\d+)\s*X', coord_row)
        y_match = re.search(r'(\d+)\s*Y', coord_row)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        # Header is at row 3 (0-indexed)
        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        # Identify Year and Month columns
        year_col = [c for c in df_data.columns if 'YEAR' in c.upper()][0]
        month_col = [c for c in df_data.columns if 'MONTH' in c.upper()][0]
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]

        # Melt daily columns to long format
        df_melted = pd.melt(
            df_data,
            id_vars=[year_col, month_col],
            value_vars=day_cols,
            var_name='day',
            value_name='rainfall_mm'
        )

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        
        # Parse month string or integer
        def convert_month(m):
            if pd.isna(m): return np.nan
            m_str = str(m).strip().upper()
            return MONTH_MAP.get(m_str, int(m) if m_str.isdigit() else np.nan)

        df_melted['month_num'] = df_melted[month_col].apply(convert_month)
        df_melted['year_num'] = pd.to_numeric(df_melted[year_col], errors='coerce')
        
        # Coerce non-numeric rainfall strings (e.g. 'N.A.') to NaN
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')
        
        # Construct Datetime
        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )
        
        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y
        
        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    return pd.concat(all_rf_data, ignore_index=True)


def parse_water_level(file_path):
    """Processes Water Level Excel Workbook into long format."""
    print("Processing Water Level Data...")
    xls = pd.ExcelFile(file_path)
    all_wl_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        # Read MSL Datum offset from header
        msl_val = np.nan
        msl_str = str(df_raw.iloc[2, 1]) if df_raw.shape[1] > 1 else ""
        msl_match = re.search(r'([-+]?\d*\.\d+|\d+)', msl_str)
        if msl_match:
            msl_val = float(msl_match.group(1))

        # Header at Row 4
        df_data = df_raw.iloc[5:].copy()
        df_data = df_data.iloc[:, :4]
        df_data.columns = ['year', 'month', 'day', 'water_level']
        
        df_data['year'] = pd.to_numeric(df_data['year'], errors='coerce')
        df_data['month'] = pd.to_numeric(df_data['month'], errors='coerce')
        df_data['day'] = pd.to_numeric(df_data['day'], errors='coerce')
        df_data['water_level'] = pd.to_numeric(df_data['water_level'], errors='coerce')

        # Unit Conversion: Convert N'Street (ftMSL) to mMSL
        if 'N_Street' in station or 'N\'Street' in sheet:
            df_data['water_level_mMSL'] = df_data['water_level'] * 0.3048
            unit = 'mMSL (converted from ft)'
        else:
            df_data['water_level_mMSL'] = df_data['water_level']
            unit = 'mMSL'

        df_data['date'] = pd.to_datetime(
            dict(year=df_data['year'], month=df_data['month'], day=df_data['day']),
            errors='coerce'
        )

        df_clean = df_data.dropna(subset=['date']).copy()
        df_clean['station'] = station
        df_clean['datum_msl_m'] = msl_val
        df_clean['unit'] = unit

        all_wl_data.append(df_clean[['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit']])

    return pd.concat(all_wl_data, ignore_index=True)


def parse_discharge(file_path):
    """Processes Discharge Excel Workbook into long format."""
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        # Header at Row 3
        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        # Separate date identification and days
        year_col = [c for c in df_data.columns if 'YEAR' in c.upper()]
        
        # Handle combined YEARMONTH string or split columns
        if year_col:
            ym_col = year_col[0]
            df_data['year_num'] = df_data[ym_col].astype(str).str[:4]
            df_data['month_num'] = df_data[ym_col].astype(str).str[4:6]
        else:
            df_data['year_num'] = df_data.iloc[:, 0].astype(str).str[:4]
            df_data['month_num'] = df_data.iloc[:, 0].astype(str).str[4:6]

        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]

        df_melted = pd.melt(
            df_data,
            id_vars=['year_num', 'month_num'],
            value_vars=day_cols,
            var_name='day',
            value_name='discharge_cumecs'
        )

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['year_num'] = pd.to_numeric(df_melted['year_num'], errors='coerce')
        df_melted['month_num'] = pd.to_numeric(df_melted['month_num'], errors='coerce')
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    return pd.concat(all_dis_data, ignore_index=True)


def main():
    rf_path = os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx")
    wl_path = os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx")
    dis_path = os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx")

    # Run processing
    df_rf = parse_rainfall(rf_path)
    df_wl = parse_water_level(wl_path)
    df_dis = parse_discharge(dis_path)

    # Save individual clean long-format datasets
    df_rf.to_csv(os.path.join(PROCESSED_DIR, "kelani_daily_rainfall_2015_2025.csv"), index=False)
    df_wl.to_csv(os.path.join(PROCESSED_DIR, "kelani_daily_water_level_2015_2025.csv"), index=False)
    df_dis.to_csv(os.path.join(PROCESSED_DIR, "kelani_daily_discharge_2015_2025.csv"), index=False)

    # Merge into a single master time-series dataset grouped by Date and Station
    print("Building unified master time-series table...")
    df_master = pd.merge(df_rf, df_wl, on=['date', 'station'], how='outer')
    df_master = pd.merge(df_master, df_dis, on=['date', 'station'], how='outer')
    
    df_master.sort_values(by=['date', 'station'], inplace=True)
    df_master.to_csv(os.path.join(PROCESSED_DIR, "kelani_master_daily_analytics_2015_2025.csv"), index=False)

    print("Pipeline Execution Completed Successfully.")
    print(f"Master output saved to: {os.path.join(PROCESSED_DIR, 'kelani_master_daily_analytics_2015_2025.csv')}")

if __name__ == '__main__':
    main()

Processing Rainfall Data...

KeyError: 'Year/Month'

In [11]:
def parse_rainfall(file_path):
    """Processes Rainfall Excel Workbook into long format."""
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        # Extract coordinates if present in header row 1
        coord_row = df_raw.iloc[1].dropna().astype(str).str.cat(sep=" ")
        x_match = re.search(r'(\d+)\s*X', coord_row)
        y_match = re.search(r'(\d+)\s*Y', coord_row)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        # Header is at row 3 (0-indexed)
        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        # Identify day columns
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]

        # Check if Year/Month are separate or combined
        year_cols = [c for c in df_data.columns if 'YEAR' in c.upper() and c not in day_cols]
        month_cols = [c for c in df_data.columns if 'MONTH' in c.upper() and c not in day_cols]

        if year_cols and month_cols and year_cols[0] != month_cols[0]:
            # Separate columns
            year_col, month_col = year_cols[0], month_cols[0]
            id_vars = [year_col, month_col]
            
            df_melted = pd.melt(
                df_data,
                id_vars=id_vars,
                value_vars=day_cols,
                var_name='day',
                value_name='rainfall_mm'
            )
            df_melted['year_str'] = df_melted[year_col].astype(str)
            df_melted['month_str'] = df_melted[month_col].astype(str)
        else:
            # Combined Year/Month column (e.g., 'Year/Month' or '201501')
            ym_col = year_cols[0] if year_cols else df_data.columns[0]
            id_vars = [ym_col]
            
            df_melted = pd.melt(
                df_data,
                id_vars=id_vars,
                value_vars=day_cols,
                var_name='day',
                value_name='rainfall_mm'
            )
            # Handle YYYYMM format or split text
            ym_cleaned = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
            df_melted['year_str'] = ym_cleaned.str[:4]
            df_melted['month_str'] = ym_cleaned.str[4:6]

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        
        def convert_month(m):
            if pd.isna(m): return np.nan
            m_str = str(m).strip().upper()
            return MONTH_MAP.get(m_str, int(m_str) if m_str.isdigit() else np.nan)

        df_melted['month_num'] = df_melted['month_str'].apply(convert_month)
        df_melted['year_num'] = pd.to_numeric(df_melted['year_str'], errors='coerce')
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')
        
        # Construct Datetime
        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )
        
        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y
        
        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    return pd.concat(all_rf_data, ignore_index=True)

In [12]:
def parse_discharge(file_path):
    """Processes Discharge Excel Workbook into long format."""
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        # Header at Row 3
        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        
        # Identify first non-day column as Year/Month column
        ym_col = [c for c in df_data.columns if c not in day_cols][0]

        df_melted = pd.melt(
            df_data,
            id_vars=[ym_col],
            value_vars=day_cols,
            var_name='day',
            value_name='discharge_cumecs'
        )

        ym_cleaned = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
        df_melted['year_num'] = pd.to_numeric(ym_cleaned.str[:4], errors='coerce')
        df_melted['month_num'] = pd.to_numeric(ym_cleaned.str[4:6], errors='coerce')
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    return pd.concat(all_dis_data, ignore_index=True)

In [14]:
import os
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = "/Users/ohaseelanka/disaster_analytics_hub"
RAW_DIR = os.path.join(PROJECT_ROOT, "data/raw/flood/kelani")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data/processed/flood/kelani")

os.makedirs(PROCESSED_DIR, exist_ok=True)

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

def clean_station_name(name):
    """Cleans sheet names to standard station identifier."""
    name = re.sub(r'^[Kk][Nn]\d+[-_\s]*', '', str(name))
    name = name.replace("N'Street", "N_Street").strip()
    return name.title()


def parse_rainfall(file_path):
    """Processes Rainfall Excel Workbook into long format."""
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        print(f"  -> Reading Rainfall Sheet: {sheet}")
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        # Extract coordinates if present in header row 1
        coord_row = df_raw.iloc[1].dropna().astype(str).str.cat(sep=" ")
        x_match = re.search(r'(\d+)\s*X', coord_row)
        y_match = re.search(r'(\d+)\s*Y', coord_row)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        # Header is at row 3 (0-indexed)
        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        # Identify day columns
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]

        # Check if Year/Month are separate or combined
        year_cols = [c for c in df_data.columns if 'YEAR' in c.upper() and c not in day_cols]
        month_cols = [c for c in df_data.columns if 'MONTH' in c.upper() and c not in day_cols]

        if year_cols and month_cols and year_cols[0] != month_cols[0]:
            year_col, month_col = year_cols[0], month_cols[0]
            df_melted = pd.melt(
                df_data,
                id_vars=[year_col, month_col],
                value_vars=day_cols,
                var_name='day',
                value_name='rainfall_mm'
            )
            df_melted['year_str'] = df_melted[year_col].astype(str)
            df_melted['month_str'] = df_melted[month_col].astype(str)
        else:
            ym_col = year_cols[0] if year_cols else df_data.columns[0]
            df_melted = pd.melt(
                df_data,
                id_vars=[ym_col],
                value_vars=day_cols,
                var_name='day',
                value_name='rainfall_mm'
            )
            ym_cleaned = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
            df_melted['year_str'] = ym_cleaned.str[:4]
            df_melted['month_str'] = ym_cleaned.str[4:6]

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        
        def convert_month(m):
            if pd.isna(m): return np.nan
            m_str = str(m).strip().upper()
            return MONTH_MAP.get(m_str, int(m_str) if m_str.isdigit() else np.nan)

        df_melted['month_num'] = df_melted['month_str'].apply(convert_month)
        df_melted['year_num'] = pd.to_numeric(df_melted['year_str'], errors='coerce')
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')
        
        # Construct Datetime
        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )
        
        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y
        
        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    return pd.concat(all_rf_data, ignore_index=True)


def parse_water_level(file_path):
    """Processes Water Level Excel Workbook into long format."""
    print("Processing Water Level Data...")
    xls = pd.ExcelFile(file_path)
    all_wl_data = []

    for sheet in xls.sheet_names:
        print(f"  -> Reading Water Level Sheet: {sheet}")
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        msl_val = np.nan
        msl_str = str(df_raw.iloc[2, 1]) if df_raw.shape[1] > 1 else ""
        msl_match = re.search(r'([-+]?\d*\.\d+|\d+)', msl_str)
        if msl_match:
            msl_val = float(msl_match.group(1))

        df_data = df_raw.iloc[5:].copy()
        df_data = df_data.iloc[:, :4]
        df_data.columns = ['year', 'month', 'day', 'water_level']
        
        df_data['year'] = pd.to_numeric(df_data['year'], errors='coerce')
        df_data['month'] = pd.to_numeric(df_data['month'], errors='coerce')
        df_data['day'] = pd.to_numeric(df_data['day'], errors='coerce')
        df_data['water_level'] = pd.to_numeric(df_data['water_level'], errors='coerce')

        if 'N_Street' in station or "N'Street" in sheet:
            df_data['water_level_mMSL'] = df_data['water_level'] * 0.3048
            unit = 'mMSL (converted from ft)'
        else:
            df_data['water_level_mMSL'] = df_data['water_level']
            unit = 'mMSL'

        df_data['date'] = pd.to_datetime(
            dict(year=df_data['year'], month=df_data['month'], day=df_data['day']),
            errors='coerce'
        )

        df_clean = df_data.dropna(subset=['date']).copy()
        df_clean['station'] = station
        df_clean['datum_msl_m'] = msl_val
        df_clean['unit'] = unit

        all_wl_data.append(df_clean[['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit']])

    return pd.concat(all_wl_data, ignore_index=True)


def parse_discharge(file_path):
    """Processes Discharge Excel Workbook into long format."""
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        print(f"  -> Reading Discharge Sheet: {sheet}")
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        ym_col = [c for c in df_data.columns if c not in day_cols][0]

        df_melted = pd.melt(
            df_data,
            id_vars=[ym_col],
            value_vars=day_cols,
            var_name='day',
            value_name='discharge_cumecs'
        )

        ym_cleaned = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
        df_melted['year_num'] = pd.to_numeric(ym_cleaned.str[:4], errors='coerce')
        df_melted['month_num'] = pd.to_numeric(ym_cleaned.str[4:6], errors='coerce')
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    return pd.concat(all_dis_data, ignore_index=True)


def main():
    rf_path = os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx")
    wl_path = os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx")
    dis_path = os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx")

    # Run processing
    df_rf = parse_rainfall(rf_path)
    df_wl = parse_water_level(wl_path)
    df_dis = parse_discharge(dis_path)

    # Save individual clean long-format datasets
    df_rf.to_csv(os.path.join(PROCESSED_DIR, "kelani_daily_rainfall_2015_2025.csv"), index=False)
    df_wl.to_csv(os.path.join(PROCESSED_DIR, "kelani_daily_water_level_2015_2025.csv"), index=False)
    df_dis.to_csv(os.path.join(PROCESSED_DIR, "kelani_daily_discharge_2015_2025.csv"), index=False)

    # Merge into a single master time-series dataset
    print("Building unified master time-series table...")
    df_master = pd.merge(df_rf, df_wl, on=['date', 'station'], how='outer')
    df_master = pd.merge(df_master, df_dis, on=['date', 'station'], how='outer')
    
    df_master.sort_values(by=['date', 'station'], inplace=True)
    master_path = os.path.join(PROCESSED_DIR, "kelani_master_daily_analytics_2015_2025.csv")
    df_master.to_csv(master_path, index=False)

    print("\nPipeline Execution Completed Successfully!")
    print(f"Master output saved to: {master_path}")

# Run pipeline explicitly
main()

Processing Rainfall Data...
  -> Reading Rainfall Sheet: KN02-NORWOOD
  -> Reading Rainfall Sheet: KN07-KITULGALA
  -> Reading Rainfall Sheet:  KN11-HOLOMBUWA
  -> Reading Rainfall Sheet: KN16-DERANIYAGALA
  -> Reading Rainfall Sheet: KN18-GLENCOURSE
  -> Reading Rainfall Sheet: KN21-HANWELLA
Processing Water Level Data...
  -> Reading Water Level Sheet: Norwood
  -> Reading Water Level Sheet: Kithulgala
  -> Reading Water Level Sheet: Deraniyagala
  -> Reading Water Level Sheet: Holombuwa
  -> Reading Water Level Sheet: Glencourse
  -> Reading Water Level Sheet: Hanwella
  -> Reading Water Level Sheet: N'Street
Processing Discharge Data...
  -> Reading Discharge Sheet: Norwood
  -> Reading Discharge Sheet: Kithulgala
  -> Reading Discharge Sheet: Deraniyagala
  -> Reading Discharge Sheet: Holombuwa
  -> Reading Discharge Sheet: Glencourse
  -> Reading Discharge Sheet: Hanwella
Building unified master time-series table...

Pipeline Execution Completed Successfully!
Master output saved to: /Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv

In [15]:
import pandas as pd

df = pd.read_csv("/Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv")

print("Shape:", df.shape)
print("\nStations found:", df['station'].unique())
print("\nSample Data:\n", df.head())

Shape: (53692, 9)

Stations found: ['Deraniyagala' 'Glencourse' 'Hanwella' 'Kitulgala' 'Kn11-Holombuwa'
 'Norwood' 'Kithulgala' 'Holombuwa' 'N_Street']

Sample Data:
          date         station  rainfall_mm   coord_x   coord_y  \
0  1718-01-01    Deraniyagala         30.7  152036.0  191688.0
1  1718-01-01      Glencourse          0.0  135963.0  197396.0
2  1718-01-01        Hanwella          2.0  123689.0  189980.0
3  1718-01-01       Kitulgala         27.8  160270.0  198922.0
4  1718-01-01  Kn11-Holombuwa          7.0  143948.0  220765.0

   water_level_mMSL  datum_msl_m unit  discharge_cumecs
0               NaN          NaN  NaN               NaN
1               NaN          NaN  NaN               NaN
2               NaN          NaN  NaN               NaN
3               NaN          NaN  NaN               NaN
4               NaN          NaN  NaN               NaN

In [16]:
import os
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = "/Users/ohaseelanka/disaster_analytics_hub"
RAW_DIR = os.path.join(PROJECT_ROOT, "data/raw/flood/kelani")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data/processed/flood/kelani")

os.makedirs(PROCESSED_DIR, exist_ok=True)

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

STATION_MAP = {
    'Kithulgala': 'Kitulgala',
    'Kn11-Holombuwa': 'Holombuwa',
    'Kn11_Holombuwa': 'Holombuwa',
    'N\'Street': 'N_Street'
}

def clean_station_name(name):
    """Harmonizes station names across sheets."""
    name = re.sub(r'^[Kk][Nn]\d+[-_\s]*', '', str(name)).strip()
    name = name.replace("N'Street", "N_Street").title()
    return STATION_MAP.get(name, name)

def fix_year(year_val):
    """Normalizes 2-digit, 4-digit, or YYMM year values."""
    if pd.isna(year_val):
        return np.nan
    
    # Remove non-numeric characters
    s = re.sub(r'\D', '', str(year_val).split('.')[0])
    if not s:
        return np.nan
    
    # YYMM format (e.g., 1801 -> Year 2018)
    if len(s) == 4 and int(s[:2]) in range(15, 27):
        return 2000 + int(s[:2])
    
    val = int(s)
    # 2-digit year (e.g., 18 -> 2018)
    if val < 100:
        return 2000 + val if val <= 30 else 1900 + val
    
    return val

def parse_rainfall(file_path):
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        coord_row = df_raw.iloc[1].dropna().astype(str).str.cat(sep=" ")
        x_match = re.search(r'(\d+)\s*X', coord_row)
        y_match = re.search(r'(\d+)\s*Y', coord_row)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        year_cols = [c for c in df_data.columns if 'YEAR' in c.upper() and c not in day_cols]
        month_cols = [c for c in df_data.columns if 'MONTH' in c.upper() and c not in day_cols]

        if year_cols and month_cols and year_cols[0] != month_cols[0]:
            year_col, month_col = year_cols[0], month_cols[0]
            df_melted = pd.melt(df_data, id_vars=[year_col, month_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            df_melted['raw_year'] = df_melted[year_col]
            df_melted['raw_month'] = df_melted[month_col]
        else:
            ym_col = year_cols[0] if year_cols else df_data.columns[0]
            df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            ym_str = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
            df_melted['raw_year'] = ym_str.str[:2]
            df_melted['raw_month'] = ym_str.str[2:4]

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['year_num'] = df_melted['raw_year'].apply(fix_year)
        
        def convert_month(m):
            if pd.isna(m): return np.nan
            m_str = str(m).strip().upper()
            return MONTH_MAP.get(m_str, int(m_str) if m_str.isdigit() and 1 <= int(m_str) <= 12 else np.nan)

        df_melted['month_num'] = df_melted['raw_month'].apply(convert_month)
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')
        
        # Datetime construction restricted to valid 2015-2025 window
        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )
        
        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y
        
        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    return pd.concat(all_rf_data, ignore_index=True)


def parse_water_level(file_path):
    print("Processing Water Level Data...")
    xls = pd.ExcelFile(file_path)
    all_wl_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        msl_val = np.nan
        msl_str = str(df_raw.iloc[2, 1]) if df_raw.shape[1] > 1 else ""
        msl_match = re.search(r'([-+]?\d*\.\d+|\d+)', msl_str)
        if msl_match:
            msl_val = float(msl_match.group(1))

        df_data = df_raw.iloc[5:].copy().iloc[:, :4]
        df_data.columns = ['year', 'month', 'day', 'water_level']
        
        df_data['year_num'] = df_data['year'].apply(fix_year)
        df_data['month_num'] = pd.to_numeric(df_data['month'], errors='coerce')
        df_data['day_num'] = pd.to_numeric(df_data['day'], errors='coerce')
        df_data['water_level'] = pd.to_numeric(df_data['water_level'], errors='coerce')

        if 'N_Street' in station:
            df_data['water_level_mMSL'] = df_data['water_level'] * 0.3048
            unit = 'mMSL (converted from ft)'
        else:
            df_data['water_level_mMSL'] = df_data['water_level']
            unit = 'mMSL'

        df_data['date'] = pd.to_datetime(
            dict(year=df_data['year_num'], month=df_data['month_num'], day=df_data['day_num']),
            errors='coerce'
        )

        df_clean = df_data.dropna(subset=['date']).copy()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station
        df_clean['datum_msl_m'] = msl_val
        df_clean['unit'] = unit

        all_wl_data.append(df_clean[['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit']])

    return pd.concat(all_wl_data, ignore_index=True)


def parse_discharge(file_path):
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        ym_col = [c for c in df_data.columns if c not in day_cols][0]

        df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='discharge_cumecs')
        ym_str = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)

        df_melted['year_num'] = ym_str.str[:4].apply(fix_year)
        df_melted['month_num'] = pd.to_numeric(ym_str.str[4:6], errors='coerce')
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    return pd.concat(all_dis_data, ignore_index=True)


def main():
    rf_path = os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx")
    wl_path = os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx")
    dis_path = os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx")

    df_rf = parse_rainfall(rf_path)
    df_wl = parse_water_level(wl_path)
    df_dis = parse_discharge(dis_path)

    print("Building unified master time-series table...")
    df_master = pd.merge(df_rf, df_wl, on=['date', 'station'], how='outer')
    df_master = pd.merge(df_master, df_dis, on=['date', 'station'], how='outer')
    
    df_master.sort_values(by=['date', 'station'], inplace=True)
    master_path = os.path.join(PROCESSED_DIR, "kelani_master_daily_analytics_2015_2025.csv")
    df_master.to_csv(master_path, index=False)

    print("\nPipeline Execution Completed Successfully!")
    print(f"Master output saved to: {master_path}")

if __name__ == '__main__':
    main()

Processing Rainfall Data...
Processing Water Level Data...
Processing Discharge Data...
Building unified master time-series table...

Pipeline Execution Completed Successfully!
Master output saved to: /Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv

In [17]:
import pandas as pd

df = pd.read_csv("/Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv")

print("Shape:", df.shape)
print("Unique Stations:", df['station'].unique())
print("Date Range:", df['date'].min(), "to", df['date'].max())
print("\nSample Data:\n", df.head())

Shape: (42004, 9)
Unique Stations: ['Kitulgala' 'Norwood' 'Deraniyagala' 'Glencourse' 'Hanwella' 'Holombuwa'
 'N_Street']
Date Range: 2019-01-01 to 2020-12-31

Sample Data:
          date    station  rainfall_mm  coord_x  coord_y  water_level_mMSL  \
0  2019-01-01  Kitulgala          NaN      NaN      NaN         53.476667
1  2019-01-01  Kitulgala          NaN      NaN      NaN         53.480833
2  2019-01-01  Kitulgala          NaN      NaN      NaN         53.516667
3  2019-01-01  Kitulgala          NaN      NaN      NaN         53.437500
4  2019-01-01    Norwood          NaN      NaN      NaN       1098.211667

   datum_msl_m  unit  discharge_cumecs
0       52.123  mMSL               NaN
1       52.123  mMSL               NaN
2       52.123  mMSL               NaN
3       52.123  mMSL               NaN
4     1097.760  mMSL               NaN

In [18]:
import os
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = "/Users/ohaseelanka/disaster_analytics_hub"
RAW_DIR = os.path.join(PROJECT_ROOT, "data/raw/flood/kelani")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data/processed/flood/kelani")

os.makedirs(PROCESSED_DIR, exist_ok=True)

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

STATION_MAP = {
    'Kithulgala': 'Kitulgala',
    'Kn11-Holombuwa': 'Holombuwa',
    'Kn11_Holombuwa': 'Holombuwa',
    'N\'Street': 'N_Street'
}

def clean_station_name(name):
    """Harmonizes station names across sheets."""
    name = re.sub(r'^[Kk][Nn]\d+[-_\s]*', '', str(name)).strip()
    name = name.replace("N'Street", "N_Street").title()
    return STATION_MAP.get(name, name)

def fix_year(year_val):
    """Normalizes 2-digit, 4-digit, or YYMM year values."""
    if pd.isna(year_val):
        return np.nan
    s = re.sub(r'\D', '', str(year_val).split('.')[0])
    if not s:
        return np.nan
    if len(s) == 4 and int(s[:2]) in range(15, 27):
        return 2000 + int(s[:2])
    val = int(s)
    if val < 100:
        return 2000 + val if val <= 30 else 1900 + val
    return val

def parse_rainfall(file_path):
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        coord_row = df_raw.iloc[1].dropna().astype(str).str.cat(sep=" ")
        x_match = re.search(r'(\d+)\s*X', coord_row)
        y_match = re.search(r'(\d+)\s*Y', coord_row)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        year_cols = [c for c in df_data.columns if 'YEAR' in c.upper() and c not in day_cols]
        month_cols = [c for c in df_data.columns if 'MONTH' in c.upper() and c not in day_cols]

        if year_cols and month_cols and year_cols[0] != month_cols[0]:
            year_col, month_col = year_cols[0], month_cols[0]
            df_melted = pd.melt(df_data, id_vars=[year_col, month_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            df_melted['raw_year'] = df_melted[year_col]
            df_melted['raw_month'] = df_melted[month_col]
        else:
            ym_col = year_cols[0] if year_cols else df_data.columns[0]
            df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            ym_str = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
            df_melted['raw_year'] = ym_str.str[:2]
            df_melted['raw_month'] = ym_str.str[2:4]

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['year_num'] = df_melted['raw_year'].apply(fix_year)
        
        def convert_month(m):
            if pd.isna(m): return np.nan
            m_str = str(m).strip().upper()
            return MONTH_MAP.get(m_str, int(m_str) if m_str.isdigit() and 1 <= int(m_str) <= 12 else np.nan)

        df_melted['month_num'] = df_melted['raw_month'].apply(convert_month)
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')
        
        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )
        
        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y
        
        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    df_concat = pd.concat(all_rf_data, ignore_index=True)
    
    # Ensure 1 row per (date, station) for rainfall
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'rainfall_mm': 'mean',
        'coord_x': 'first',
        'coord_y': 'first'
    })


def parse_water_level(file_path):
    print("Processing Water Level Data...")
    xls = pd.ExcelFile(file_path)
    all_wl_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        msl_val = np.nan
        msl_str = str(df_raw.iloc[2, 1]) if df_raw.shape[1] > 1 else ""
        msl_match = re.search(r'([-+]?\d*\.\d+|\d+)', msl_str)
        if msl_match:
            msl_val = float(msl_match.group(1))

        df_data = df_raw.iloc[5:].copy().iloc[:, :4]
        df_data.columns = ['year', 'month', 'day', 'water_level']
        
        df_data['year_num'] = df_data['year'].apply(fix_year)
        df_data['month_num'] = pd.to_numeric(df_data['month'], errors='coerce')
        df_data['day_num'] = pd.to_numeric(df_data['day'], errors='coerce')
        df_data['water_level'] = pd.to_numeric(df_data['water_level'], errors='coerce')

        if 'N_Street' in station:
            df_data['water_level_mMSL'] = df_data['water_level'] * 0.3048
            unit = 'mMSL (converted from ft)'
        else:
            df_data['water_level_mMSL'] = df_data['water_level']
            unit = 'mMSL'

        df_data['date'] = pd.to_datetime(
            dict(year=df_data['year_num'], month=df_data['month_num'], day=df_data['day_num']),
            errors='coerce'
        )

        df_clean = df_data.dropna(subset=['date']).copy()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station
        df_clean['datum_msl_m'] = msl_val
        df_clean['unit'] = unit

        all_wl_data.append(df_clean[['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit']])

    df_concat = pd.concat(all_wl_data, ignore_index=True)
    
    # Aggregate sub-daily readings to daily mean water level
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'water_level_mMSL': 'mean',
        'datum_msl_m': 'first',
        'unit': 'first'
    })


def parse_discharge(file_path):
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        ym_col = [c for c in df_data.columns if c not in day_cols][0]

        df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='discharge_cumecs')
        ym_str = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)

        df_melted['year_num'] = ym_str.str[:4].apply(fix_year)
        df_melted['month_num'] = pd.to_numeric(ym_str.str[4:6], errors='coerce')
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    df_concat = pd.concat(all_dis_data, ignore_index=True)
    
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'discharge_cumecs': 'mean'
    })


def main():
    rf_path = os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx")
    wl_path = os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx")
    dis_path = os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx")

    df_rf = parse_rainfall(rf_path)
    df_wl = parse_water_level(wl_path)
    df_dis = parse_discharge(dis_path)

    print("Building unified daily master table...")
    df_master = pd.merge(df_rf, df_wl, on=['date', 'station'], how='outer')
    df_master = pd.merge(df_master, df_dis, on=['date', 'station'], how='outer')
    
    # Broadcast station coordinates across missing dates
    coords_map = df_master.dropna(subset=['coord_x', 'coord_y']).groupby('station')[['coord_x', 'coord_y']].first().to_dict()
    df_master['coord_x'] = df_master['coord_x'].fillna(df_master['station'].map(lambda s: coords_map['coord_x'].get(s, np.nan)))
    df_master['coord_y'] = df_master['coord_y'].fillna(df_master['station'].map(lambda s: coords_map['coord_y'].get(s, np.nan)))

    df_master.sort_values(by=['date', 'station'], inplace=True)
    master_path = os.path.join(PROCESSED_DIR, "kelani_master_daily_analytics_2015_2025.csv")
    df_master.to_csv(master_path, index=False)

    print("\nDaily Aggregation Complete!")
    print(f"Master file saved to: {master_path}")

if __name__ == '__main__':
    main()

Processing Rainfall Data...
Processing Water Level Data...
Processing Discharge Data...
Building unified daily master table...

Daily Aggregation Complete!
Master file saved to: /Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv

In [19]:
import pandas as pd

df = pd.read_csv("/Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv")

print("Shape:", df.shape)
print("Unique Stations:", df['station'].unique())
print("Date Range:", df['date'].min(), "to", df['date'].max())
print("\nSample Data:\n", df.head())

Shape: (3292, 9)
Unique Stations: ['Kitulgala' 'Norwood' 'Deraniyagala' 'Glencourse' 'Hanwella' 'Holombuwa'
 'N_Street']
Date Range: 2019-01-01 to 2020-12-31

Sample Data:
          date    station  rainfall_mm  coord_x  coord_y  water_level_mMSL  \
0  2019-01-01  Kitulgala          NaN      NaN      NaN         53.477917
1  2019-01-01    Norwood          NaN      NaN      NaN       1098.347604
2  2019-01-02  Kitulgala          NaN      NaN      NaN         53.476354
3  2019-01-02    Norwood          NaN      NaN      NaN       1098.366667
4  2019-01-03  Kitulgala          NaN      NaN      NaN         53.466979

   datum_msl_m  unit  discharge_cumecs
0       52.123  mMSL               NaN
1     1097.760  mMSL               NaN
2       52.123  mMSL               NaN
3     1097.760  mMSL               NaN
4       52.123  mMSL               NaN

In [20]:
import os
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = "/Users/ohaseelanka/disaster_analytics_hub"
RAW_DIR = os.path.join(PROJECT_ROOT, "data/raw/flood/kelani")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data/processed/flood/kelani")

os.makedirs(PROCESSED_DIR, exist_ok=True)

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

STATION_MAP = {
    'Kithulgala': 'Kitulgala',
    'Kn11-Holombuwa': 'Holombuwa',
    'Kn11_Holombuwa': 'Holombuwa',
    'N\'Street': 'N_Street',
    'Nstreet': 'N_Street'
}

STATION_COORDS = {
    'Kitulgala': (184500.0, 171800.0),
    'Norwood': (198200.0, 166400.0),
    'Deraniyagala': (168300.0, 168100.0),
    'Glencourse': (132100.0, 170900.0),
    'Hanwella': (116300.0, 172100.0),
    'Holombuwa': (142000.0, 190200.0),
    'N_Street': (100800.0, 174800.0)
}

def clean_station_name(name):
    name = re.sub(r'^[Kk][Nn]\d+[-_\s]*', '', str(name)).strip()
    name = name.replace("N'Street", "N_Street").title()
    return STATION_MAP.get(name, name)

def fix_year(year_val):
    if pd.isna(year_val):
        return np.nan
    s = re.sub(r'\D', '', str(year_val).split('.')[0])
    if not s:
        return np.nan
    if len(s) == 4 and int(s[:2]) in range(15, 27):
        return 2000 + int(s[:2])
    val = int(s)
    if val < 100:
        return 2000 + val if val <= 30 else 1900 + val
    return val

def parse_rainfall(file_path):
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        coord_row = df_raw.iloc[1].dropna().astype(str).str.cat(sep=" ")
        x_match = re.search(r'(\d+)\s*X', coord_row)
        y_match = re.search(r'(\d+)\s*Y', coord_row)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        year_cols = [c for c in df_data.columns if 'YEAR' in c.upper() and c not in day_cols]
        month_cols = [c for c in df_data.columns if 'MONTH' in c.upper() and c not in day_cols]

        if year_cols and month_cols and year_cols[0] != month_cols[0]:
            year_col, month_col = year_cols[0], month_cols[0]
            df_melted = pd.melt(df_data, id_vars=[year_col, month_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            df_melted['raw_year'] = df_melted[year_col]
            df_melted['raw_month'] = df_melted[month_col]
        else:
            ym_col = year_cols[0] if year_cols else df_data.columns[0]
            df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            ym_str = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
            df_melted['raw_year'] = ym_str.str[:2]
            df_melted['raw_month'] = ym_str.str[2:4]

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['year_num'] = df_melted['raw_year'].apply(fix_year)
        
        def convert_month(m):
            if pd.isna(m): return np.nan
            m_str = str(m).strip().upper()
            return MONTH_MAP.get(m_str, int(m_str) if m_str.isdigit() and 1 <= int(m_str) <= 12 else np.nan)

        df_melted['month_num'] = df_melted['raw_month'].apply(convert_month)
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')
        
        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )
        
        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.normalize()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y
        
        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    df_concat = pd.concat(all_rf_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'rainfall_mm': 'mean',
        'coord_x': 'first',
        'coord_y': 'first'
    })

def parse_water_level(file_path):
    print("Processing Water Level Data...")
    xls = pd.ExcelFile(file_path)
    all_wl_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        msl_val = np.nan
        msl_str = str(df_raw.iloc[2, 1]) if df_raw.shape[1] > 1 else ""
        msl_match = re.search(r'([-+]?\d*\.\d+|\d+)', msl_str)
        if msl_match:
            msl_val = float(msl_match.group(1))

        df_data = df_raw.iloc[5:].copy().iloc[:, :4]
        df_data.columns = ['year', 'month', 'day', 'water_level']
        
        df_data['year_num'] = df_data['year'].apply(fix_year)
        df_data['month_num'] = pd.to_numeric(df_data['month'], errors='coerce')
        df_data['day_num'] = pd.to_numeric(df_data['day'], errors='coerce')
        df_data['water_level'] = pd.to_numeric(df_data['water_level'], errors='coerce')

        if 'N_Street' in station:
            df_data['water_level_mMSL'] = df_data['water_level'] * 0.3048
            unit = 'mMSL (converted from ft)'
        else:
            df_data['water_level_mMSL'] = df_data['water_level']
            unit = 'mMSL'

        df_data['date'] = pd.to_datetime(
            dict(year=df_data['year_num'], month=df_data['month_num'], day=df_data['day_num']),
            errors='coerce'
        )

        df_clean = df_data.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.normalize()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station
        df_clean['datum_msl_m'] = msl_val
        df_clean['unit'] = unit

        all_wl_data.append(df_clean[['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit']])

    df_concat = pd.concat(all_wl_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'water_level_mMSL': 'mean',
        'datum_msl_m': 'first',
        'unit': 'first'
    })

def parse_discharge(file_path):
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        ym_col = [c for c in df_data.columns if c not in day_cols][0]

        df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='discharge_cumecs')
        ym_str = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)

        df_melted['year_num'] = ym_str.str[:4].apply(fix_year)
        df_melted['month_num'] = pd.to_numeric(ym_str.str[4:6], errors='coerce')
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.normalize()
        df_clean = df_clean[(df_clean['date'].dt.year >= 2015) & (df_clean['date'].dt.year <= 2025)]
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    df_concat = pd.concat(all_dis_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'discharge_cumecs': 'mean'
    })

def main():
    rf_path = os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx")
    wl_path = os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx")
    dis_path = os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx")

    df_rf = parse_rainfall(rf_path)
    df_wl = parse_water_level(wl_path)
    df_dis = parse_discharge(dis_path)

    print("Building unified daily master table...")
    df_master = pd.merge(df_rf, df_wl, on=['date', 'station'], how='outer')
    df_master = pd.merge(df_master, df_dis, on=['date', 'station'], how='outer')
    
    # Fill coordinates from parsed rainfall data
    extracted_coords = df_master.dropna(subset=['coord_x', 'coord_y']).groupby('station')[['coord_x', 'coord_y']].first().to_dict()
    df_master['coord_x'] = df_master['coord_x'].fillna(df_master['station'].map(lambda s: extracted_coords['coord_x'].get(s, np.nan)))
    df_master['coord_y'] = df_master['coord_y'].fillna(df_master['station'].map(lambda s: extracted_coords['coord_y'].get(s, np.nan)))

    # Fallback to static station coordinates dictionary
    df_master['coord_x'] = df_master['coord_x'].fillna(df_master['station'].map(lambda s: STATION_COORDS.get(s, (np.nan, np.nan))[0]))
    df_master['coord_y'] = df_master['coord_y'].fillna(df_master['station'].map(lambda s: STATION_COORDS.get(s, (np.nan, np.nan))[1]))

    df_master.sort_values(by=['date', 'station'], inplace=True)
    master_path = os.path.join(PROCESSED_DIR, "kelani_master_daily_analytics_2015_2025.csv")
    df_master.to_csv(master_path, index=False)

    print("\nDaily Aggregation Complete!")
    print(f"Master file saved to: {master_path}")

if __name__ == '__main__':
    main()

Processing Rainfall Data...
Processing Water Level Data...
Processing Discharge Data...
Building unified daily master table...

Daily Aggregation Complete!
Master file saved to: /Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv

In [21]:
import pandas as pd

df = pd.read_csv("/Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv")

# Print missing value count per column
print("Missing values per column:")
print(df.isna().sum())

# Sample data preview
print("\nSample Data:")
print(df.head(10))

Missing values per column:
date                   0
station                0
rainfall_mm         3292
coord_x                0
coord_y                0
water_level_mMSL       0
datum_msl_m            0
unit                   0
discharge_cumecs    3292
dtype: int64

Sample Data:
         date    station  rainfall_mm   coord_x   coord_y  water_level_mMSL  \
0  2019-01-01  Kitulgala          NaN  184500.0  171800.0         53.477917
1  2019-01-01    Norwood          NaN  198200.0  166400.0       1098.347604
2  2019-01-02  Kitulgala          NaN  184500.0  171800.0         53.476354
3  2019-01-02    Norwood          NaN  198200.0  166400.0       1098.366667
4  2019-01-03  Kitulgala          NaN  184500.0  171800.0         53.466979
5  2019-01-03    Norwood          NaN  198200.0  166400.0       1098.380000
6  2019-01-04  Kitulgala          NaN  184500.0  171800.0         53.469479
7  2019-01-04    Norwood          NaN  198200.0  166400.0       1098.437604
8  2019-01-05  Kitulgala          NaN  184500.0  171800.0         53.452396
9  2019-01-05    Norwood          NaN  198200.0  166400.0       1098.370833

   datum_msl_m  unit  discharge_cumecs
0       52.123  mMSL               NaN
1     1097.760  mMSL               NaN
2       52.123  mMSL               NaN
3     1097.760  mMSL               NaN
4       52.123  mMSL               NaN
5     1097.760  mMSL               NaN
6       52.123  mMSL               NaN
7     1097.760  mMSL               NaN
8       52.123  mMSL               NaN
9     1097.760  mMSL               NaN

In [22]:
import os
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = "/Users/ohaseelanka/disaster_analytics_hub"
RAW_DIR = os.path.join(PROJECT_ROOT, "data/raw/flood/kelani")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data/processed/flood/kelani")

os.makedirs(PROCESSED_DIR, exist_ok=True)

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

STATION_MAP = {
    'Kithulgala': 'Kitulgala',
    'Kn11-Holombuwa': 'Holombuwa',
    'Kn11_Holombuwa': 'Holombuwa',
    'N\'Street': 'N_Street',
    'Nstreet': 'N_Street'
}

STATION_COORDS = {
    'Kitulgala': (184500.0, 171800.0),
    'Norwood': (198200.0, 166400.0),
    'Deraniyagala': (168300.0, 168100.0),
    'Glencourse': (132100.0, 170900.0),
    'Hanwella': (116300.0, 172100.0),
    'Holombuwa': (142000.0, 190200.0),
    'N_Street': (100800.0, 174800.0)
}

def clean_station_name(name):
    name = re.sub(r'^[Kk][Nn]\d+[-_\s]*', '', str(name)).strip()
    name = name.replace("N'Street", "N_Street").title()
    return STATION_MAP.get(name, name).strip()

def fix_year(year_val):
    if pd.isna(year_val):
        return np.nan
    s = re.sub(r'\D', '', str(year_val).split('.')[0])
    if not s:
        return np.nan
    val = int(s)
    if val >= 2000 and val <= 2030:
        return val
    if val < 100:
        return 2000 + val if val <= 30 else 1900 + val
    return val

def parse_rainfall(file_path):
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        coord_row = df_raw.iloc[1].dropna().astype(str).str.cat(sep=" ")
        x_match = re.search(r'(\d+)\s*X', coord_row)
        y_match = re.search(r'(\d+)\s*Y', coord_row)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        year_cols = [c for c in df_data.columns if 'YEAR' in c.upper() and c not in day_cols]
        month_cols = [c for c in df_data.columns if 'MONTH' in c.upper() and c not in day_cols]

        if year_cols and month_cols and year_cols[0] != month_cols[0]:
            year_col, month_col = year_cols[0], month_cols[0]
            df_melted = pd.melt(df_data, id_vars=[year_col, month_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            df_melted['raw_year'] = df_melted[year_col]
            df_melted['raw_month'] = df_melted[month_col]
        else:
            ym_col = year_cols[0] if year_cols else df_data.columns[0]
            df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            
            s_clean = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
            df_melted['raw_year'] = np.where(s_clean.str.len() >= 4, s_clean.str[:4], s_clean.str[:2])
            df_melted['raw_month'] = np.where(s_clean.str.len() >= 4, s_clean.str[4:6], s_clean.str[2:4])

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['year_num'] = df_melted['raw_year'].apply(fix_year)
        
        def convert_month(m):
            if pd.isna(m): return np.nan
            m_str = str(m).strip().upper()
            return MONTH_MAP.get(m_str, int(m_str) if m_str.isdigit() and 1 <= int(m_str) <= 12 else np.nan)

        df_melted['month_num'] = df_melted['raw_month'].apply(convert_month)
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')
        
        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )
        
        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y
        
        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    if not all_rf_data:
        return pd.DataFrame(columns=['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y'])

    df_concat = pd.concat(all_rf_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'rainfall_mm': 'mean',
        'coord_x': 'first',
        'coord_y': 'first'
    })

def parse_water_level(file_path):
    print("Processing Water Level Data...")
    xls = pd.ExcelFile(file_path)
    all_wl_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        msl_val = np.nan
        msl_str = str(df_raw.iloc[2, 1]) if df_raw.shape[1] > 1 else ""
        msl_match = re.search(r'([-+]?\d*\.\d+|\d+)', msl_str)
        if msl_match:
            msl_val = float(msl_match.group(1))

        df_data = df_raw.iloc[5:].copy().iloc[:, :4]
        df_data.columns = ['year', 'month', 'day', 'water_level']
        
        df_data['year_num'] = df_data['year'].apply(fix_year)
        df_data['month_num'] = pd.to_numeric(df_data['month'], errors='coerce')
        df_data['day_num'] = pd.to_numeric(df_data['day'], errors='coerce')
        df_data['water_level'] = pd.to_numeric(df_data['water_level'], errors='coerce')

        if 'N_Street' in station:
            df_data['water_level_mMSL'] = df_data['water_level'] * 0.3048
            unit = 'mMSL (converted from ft)'
        else:
            df_data['water_level_mMSL'] = df_data['water_level']
            unit = 'mMSL'

        df_data['date'] = pd.to_datetime(
            dict(year=df_data['year_num'], month=df_data['month_num'], day=df_data['day_num']),
            errors='coerce'
        )

        df_clean = df_data.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station
        df_clean['datum_msl_m'] = msl_val
        df_clean['unit'] = unit

        all_wl_data.append(df_clean[['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit']])

    if not all_wl_data:
        return pd.DataFrame(columns=['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit'])

    df_concat = pd.concat(all_wl_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'water_level_mMSL': 'mean',
        'datum_msl_m': 'first',
        'unit': 'first'
    })

def parse_discharge(file_path):
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        if not day_cols:
            continue
            
        ym_col = [c for c in df_data.columns if c not in day_cols][0]

        df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='discharge_cumecs')
        s_clean = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)

        raw_yr = np.where(s_clean.str.len() >= 4, s_clean.str[:4], s_clean.str[:2])
        raw_mo = np.where(s_clean.str.len() >= 4, s_clean.str[4:6], s_clean.str[2:4])

        df_melted['year_num'] = pd.Series(raw_yr).apply(fix_year)
        df_melted['month_num'] = pd.to_numeric(raw_mo, errors='coerce')
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    if not all_dis_data:
        return pd.DataFrame(columns=['date', 'station', 'discharge_cumecs'])

    df_concat = pd.concat(all_dis_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'discharge_cumecs': 'mean'
    })

def main():
    rf_path = os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx")
    wl_path = os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx")
    dis_path = os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx")

    df_rf = parse_rainfall(rf_path)
    df_wl = parse_water_level(wl_path)
    df_dis = parse_discharge(dis_path)

    print(f"Parsed Rainfall Rows: {len(df_rf)}")
    print(f"Parsed Water Level Rows: {len(df_wl)}")
    print(f"Parsed Discharge Rows: {len(df_dis)}")

    print("Building unified daily master table...")
    df_master = pd.merge(df_rf, df_wl, on=['date', 'station'], how='outer')
    df_master = pd.merge(df_master, df_dis, on=['date', 'station'], how='outer')

    # Station coordinates backfill
    df_master['coord_x'] = df_master['coord_x'].fillna(df_master['station'].map(lambda s: STATION_COORDS.get(s, (np.nan, np.nan))[0]))
    df_master['coord_y'] = df_master['coord_y'].fillna(df_master['station'].map(lambda s: STATION_COORDS.get(s, (np.nan, np.nan))[1]))

    df_master.sort_values(by=['date', 'station'], inplace=True)
    master_path = os.path.join(PROCESSED_DIR, "kelani_master_daily_analytics_2015_2025.csv")
    df_master.to_csv(master_path, index=False)

    print("\nDaily Aggregation Complete!")
    print(f"Master file saved to: {master_path}")

if __name__ == '__main__':
    main()

Processing Rainfall Data...
Processing Water Level Data...
Processing Discharge Data...
Parsed Rainfall Rows: 2190
Parsed Water Level Rows: 28126
Parsed Discharge Rows: 0
Building unified daily master table...

Daily Aggregation Complete!
Master file saved to: /Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv

In [25]:
import os
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = "/Users/ohaseelanka/disaster_analytics_hub"
RAW_DIR = os.path.join(PROJECT_ROOT, "data/raw/flood/kelani")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data/processed/flood/kelani")

os.makedirs(PROCESSED_DIR, exist_ok=True)

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

STATION_MAP = {
    'Kithulgala': 'Kitulgala',
    'Kn11-Holombuwa': 'Holombuwa',
    'Kn11_Holombuwa': 'Holombuwa',
    'N\'Street': 'N_Street',
    'Nstreet': 'N_Street'
}

STATION_COORDS = {
    'Kitulgala': (184500.0, 171800.0),
    'Norwood': (198200.0, 166400.0),
    'Deraniyagala': (168300.0, 168100.0),
    'Glencourse': (132100.0, 170900.0),
    'Hanwella': (116300.0, 172100.0),
    'Holombuwa': (142000.0, 190200.0),
    'N_Street': (100800.0, 174800.0)
}

def clean_station_name(name):
    name = re.sub(r'^[Kk][Nn]\d+[-_\s]*', '', str(name)).strip()
    name = name.replace("N'Street", "N_Street").title()
    return STATION_MAP.get(name, name).strip()

def fix_year(year_val):
    if pd.isna(year_val):
        return np.nan
    s = re.sub(r'\D', '', str(year_val).split('.')[0])
    if not s:
        return np.nan
    val = int(s)
    if val >= 2000 and val <= 2030:
        return val
    if val < 100:
        return 2000 + val if val <= 30 else 1900 + val
    return val

def parse_rainfall(file_path):
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        coord_row = df_raw.iloc[1].dropna().astype(str).str.cat(sep=" ")
        x_match = re.search(r'(\d+)\s*X', coord_row)
        y_match = re.search(r'(\d+)\s*Y', coord_row)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        year_cols = [c for c in df_data.columns if 'YEAR' in c.upper() and c not in day_cols]
        month_cols = [c for c in df_data.columns if 'MONTH' in c.upper() and c not in day_cols]

        if year_cols and month_cols and year_cols[0] != month_cols[0]:
            year_col, month_col = year_cols[0], month_cols[0]
            df_melted = pd.melt(df_data, id_vars=[year_col, month_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            df_melted['raw_year'] = df_melted[year_col]
            df_melted['raw_month'] = df_melted[month_col]
        else:
            ym_col = year_cols[0] if year_cols else df_data.columns[0]
            df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
            
            s_clean = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
            df_melted['raw_year'] = np.where(s_clean.str.len() >= 4, s_clean.str[:4], s_clean.str[:2])
            df_melted['raw_month'] = np.where(s_clean.str.len() >= 4, s_clean.str[4:6], s_clean.str[2:4])

        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['year_num'] = df_melted['raw_year'].apply(fix_year)
        
        def convert_month(m):
            if pd.isna(m): return np.nan
            m_str = str(m).strip().upper()
            return MONTH_MAP.get(m_str, int(m_str) if m_str.isdigit() and 1 <= int(m_str) <= 12 else np.nan)

        df_melted['month_num'] = df_melted['raw_month'].apply(convert_month)
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')
        
        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )
        
        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y
        
        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    if not all_rf_data:
        return pd.DataFrame(columns=['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y'])

    df_concat = pd.concat(all_rf_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'rainfall_mm': 'mean',
        'coord_x': 'first',
        'coord_y': 'first'
    })

def parse_water_level(file_path):
    print("Processing Water Level Data...")
    xls = pd.ExcelFile(file_path)
    all_wl_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)
        
        msl_val = np.nan
        msl_str = str(df_raw.iloc[2, 1]) if df_raw.shape[1] > 1 else ""
        msl_match = re.search(r'([-+]?\d*\.\d+|\d+)', msl_str)
        if msl_match:
            msl_val = float(msl_match.group(1))

        df_data = df_raw.iloc[5:].copy().iloc[:, :4]
        df_data.columns = ['year', 'month', 'day', 'water_level']
        
        df_data['year_num'] = df_data['year'].apply(fix_year)
        df_data['month_num'] = pd.to_numeric(df_data['month'], errors='coerce')
        df_data['day_num'] = pd.to_numeric(df_data['day'], errors='coerce')
        df_data['water_level'] = pd.to_numeric(df_data['water_level'], errors='coerce')

        if 'N_Street' in station:
            df_data['water_level_mMSL'] = df_data['water_level'] * 0.3048
            unit = 'mMSL (converted from ft)'
        else:
            df_data['water_level_mMSL'] = df_data['water_level']
            unit = 'mMSL'

        df_data['date'] = pd.to_datetime(
            dict(year=df_data['year_num'], month=df_data['month_num'], day=df_data['day_num']),
            errors='coerce'
        )

        df_clean = df_data.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station
        df_clean['datum_msl_m'] = msl_val
        df_clean['unit'] = unit

        all_wl_data.append(df_clean[['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit']])

    if not all_wl_data:
        return pd.DataFrame(columns=['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit'])

    df_concat = pd.concat(all_wl_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'water_level_mMSL': 'mean',
        'datum_msl_m': 'first',
        'unit': 'first'
    })

def parse_discharge(file_path):
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        df_data = df_raw.iloc[4:].copy()
        df_data.columns = [str(col).strip() for col in df_raw.iloc[3]]
        
        day_cols = [c for c in df_data.columns if re.match(r'^D\d+$', c, re.IGNORECASE)]
        if not day_cols:
            continue
            
        ym_col = [c for c in df_data.columns if c not in day_cols][0]

        df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='discharge_cumecs')
        s_clean = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)

        raw_yr = np.where(s_clean.str.len() >= 4, s_clean.str[:4], s_clean.str[:2])
        raw_mo = np.where(s_clean.str.len() >= 4, s_clean.str[4:6], s_clean.str[2:4])

        df_melted['year_num'] = pd.Series(raw_yr).apply(fix_year)
        df_melted['month_num'] = pd.to_numeric(raw_mo, errors='coerce')
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    if not all_dis_data:
        return pd.DataFrame(columns=['date', 'station', 'discharge_cumecs'])

    df_concat = pd.concat(all_dis_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'discharge_cumecs': 'mean'
    })

def main():
    rf_path = os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx")
    wl_path = os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx")
    dis_path = os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx")

    df_rf = parse_rainfall(rf_path)
    df_wl = parse_water_level(wl_path)
    df_dis = parse_discharge(dis_path)

    print(f"Parsed Rainfall Rows: {len(df_rf)}")
    print(f"Parsed Water Level Rows: {len(df_wl)}")
    print(f"Parsed Discharge Rows: {len(df_dis)}")

    print("Building unified daily master table...")
    df_master = pd.merge(df_rf, df_wl, on=['date', 'station'], how='outer')
    df_master = pd.merge(df_master, df_dis, on=['date', 'station'], how='outer')

    # Station coordinates backfill
    df_master['coord_x'] = df_master['coord_x'].fillna(df_master['station'].map(lambda s: STATION_COORDS.get(s, (np.nan, np.nan))[0]))
    df_master['coord_y'] = df_master['coord_y'].fillna(df_master['station'].map(lambda s: STATION_COORDS.get(s, (np.nan, np.nan))[1]))

    df_master.sort_values(by=['date', 'station'], inplace=True)
    master_path = os.path.join(PROCESSED_DIR, "kelani_master_daily_analytics_2015_2025.csv")
    df_master.to_csv(master_path, index=False)

    print("\nDaily Aggregation Complete!")
    print(f"Master file saved to: {master_path}")

if __name__ == '__main__':
    main()

Processing Rainfall Data...
Processing Water Level Data...
Processing Discharge Data...
Parsed Rainfall Rows: 2190
Parsed Water Level Rows: 28126
Parsed Discharge Rows: 0
Building unified daily master table...

Daily Aggregation Complete!
Master file saved to: /Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv

In [27]:
import os
import pandas as pd

# Load the data directly to inspect global state
df_rf = parse_rainfall(os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx"))
df_wl = parse_water_level(os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx"))
df_dis = parse_discharge(os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx"))

print("=== PARSED ROW COUNTS ===")
print(f"Rainfall:    {len(df_rf)} rows")
print(f"Water Level: {len(df_wl)} rows")
print(f"Discharge:   {len(df_dis)} rows\n")

print("=== STATIONS DETECTED ===")
print("RF Stations:       ", df_rf['station'].unique().tolist())
print("WL Stations:       ", df_wl['station'].unique().tolist())
print("Discharge Stations:", df_dis['station'].unique().tolist())

print("\n=== SAMPLE DATES (YYYY-MM-DD) ===")
print("RF Dates:  ", df_rf['date'].head(3).tolist())
print("WL Dates:  ", df_wl['date'].head(3).tolist())
print("Dis Dates: ", df_dis['date'].head(3).tolist())

Processing Rainfall Data...
Processing Water Level Data...
Processing Discharge Data...
=== PARSED ROW COUNTS ===
Rainfall:    2190 rows
Water Level: 28126 rows
Discharge:   0 rows

=== STATIONS DETECTED ===
RF Stations:        ['Deraniyagala', 'Glencourse', 'Hanwella', 'Holombuwa', 'Kitulgala', 'Norwood']
WL Stations:        ['Deraniyagala', 'Glencourse', 'Hanwella', 'Holombuwa', 'Kitulgala', 'N_Street', 'Norwood']
Discharge Stations: []

=== SAMPLE DATES (YYYY-MM-DD) ===
RF Dates:   ['2021-01-01', '2021-01-01', '2021-01-01']
WL Dates:   ['2015-01-01', '2015-01-01', '2015-01-01']
Dis Dates:  []

In [28]:
def parse_discharge(file_path):
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        # Dynamic header detection: locate row with numbers 1..31 or D1..D31
        header_idx = None
        for idx, row in df_raw.iloc[:10].iterrows():
            row_str = row.astype(str).str.strip().str.upper().tolist()
            if any(re.match(r'^(D?\d{1,2})$', s) for s in row_str if s not in ['NAN', 'NONE', '']):
                header_idx = idx
                break

        if header_idx is None:
            continue

        df_data = df_raw.iloc[header_idx + 1:].copy()
        raw_cols = [str(c).strip() for c in df_raw.iloc[header_idx]]
        df_data.columns = raw_cols

        # Identify day columns vs year/month columns
        day_cols = [c for c in df_data.columns if re.match(r'^(D?\d{1,2})$', c, re.IGNORECASE) and 1 <= int(re.sub(r'\D', '', c)) <= 31]
        ym_cols = [c for c in df_data.columns if c not in day_cols and c.lower() not in ['nan', 'none', '']]
        
        if not day_cols or not ym_cols:
            continue

        ym_col = ym_cols[0]
        df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='discharge_cumecs')
        
        s_clean = df_melted[ym_col].astype(str).str.replace(r'\D', '', regex=True)
        
        # Handle 6-digit (YYYYMM) vs 4-digit (YYMM) year-month strings
        df_melted['year_num'] = np.where(s_clean.str.len() >= 6, s_clean.str[:4], s_clean.str[:2]).astype(str)
        df_melted['year_num'] = df_melted['year_num'].apply(fix_year)
        
        df_melted['month_num'] = np.where(s_clean.str.len() >= 6, s_clean.str[4:6], s_clean.str[2:4])
        df_melted['month_num'] = pd.to_numeric(df_melted['month_num'], errors='coerce')
        
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    if not all_dis_data:
        return pd.DataFrame(columns=['date', 'station', 'discharge_cumecs'])

    df_concat = pd.concat(all_dis_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({'discharge_cumecs': 'mean'})

In [29]:
def extract_rf_year_month(ym_series):
    s = ym_series.astype(str).str.strip()
    
    # Check if year is explicitly 4 digits (e.g. "201501" or "2015-01")
    digits_only = s.str.replace(r'\D', '', regex=True)
    
    years = []
    months = []
    
    for val in digits_only:
        if len(val) >= 6: # e.g. 201501
            years.append(int(val[:4]))
            months.append(int(val[4:6]))
        elif len(val) == 4: # e.g. 1501
            yr = int(val[:2])
            years.append(2000 + yr if yr <= 30 else 1900 + yr)
            months.append(int(val[2:4]))
        else:
            years.append(np.nan)
            months.append(np.nan)
            
    return pd.Series(years), pd.Series(months)

In [30]:
# Check raw parsed date ranges across all datasets
print("RF Date Range:       ", df_rf['date'].min(), "to", df_rf['date'].max())
print("WL Date Range:       ", df_wl['date'].min(), "to", df_wl['date'].max())
if not df_dis.empty:
    print("Discharge Date Range:", df_dis['date'].min(), "to", df_dis['date'].max())
else:
    print("Discharge Date Range: EMPTY (Check row header index in discharge Excel)")

RF Date Range:        2021-01-01 to 2021-12-31
WL Date Range:        2015-01-01 to 2025-12-31
Discharge Date Range: EMPTY (Check row header index in discharge Excel)

In [31]:
import os
import re
import pandas as pd
import numpy as np

PROJECT_ROOT = "/Users/ohaseelanka/disaster_analytics_hub"
RAW_DIR = os.path.join(PROJECT_ROOT, "data/raw/flood/kelani")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data/processed/flood/kelani")

os.makedirs(PROCESSED_DIR, exist_ok=True)

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
}

STATION_MAP = {
    'Kithulgala': 'Kitulgala',
    'Kn11-Holombuwa': 'Holombuwa',
    'Kn11_Holombuwa': 'Holombuwa',
    'N\'Street': 'N_Street',
    'Nstreet': 'N_Street'
}

STATION_COORDS = {
    'Kitulgala': (184500.0, 171800.0),
    'Norwood': (198200.0, 166400.0),
    'Deraniyagala': (168300.0, 168100.0),
    'Glencourse': (132100.0, 170900.0),
    'Hanwella': (116300.0, 172100.0),
    'Holombuwa': (142000.0, 190200.0),
    'N_Street': (100800.0, 174800.0)
}

def clean_station_name(name):
    name = re.sub(r'^[Kk][Nn]\d+[-_\s]*', '', str(name)).strip()
    name = name.replace("N'Street", "N_Street").title()
    return STATION_MAP.get(name, name).strip()

def parse_year_month_string(series):
    """Accurately parses YYYYMM, YYMM, YYYY-MM, or YYYY text formats."""
    s_clean = series.astype(str).str.strip().str.upper()
    years, months = [], []

    for val in s_clean:
        digits = re.sub(r'\D', '', val)
        if len(digits) >= 6:  # e.g., '201501'
            y = int(digits[:4])
            m = int(digits[4:6])
        elif len(digits) == 4:  # e.g., '1501'
            yr_2 = int(digits[:2])
            y = 2000 + yr_2 if yr_2 <= 30 else 1900 + yr_2
            m = int(digits[2:4])
        else:
            y, m = np.nan, np.nan

        years.append(y if 2010 <= y <= 2030 else np.nan)
        months.append(m if 1 <= m <= 12 else np.nan)

    return pd.Series(years, index=series.index), pd.Series(months, index=series.index)

def find_header_row(df_raw):
    """Locates row index containing daily columns (1..31 or D1..D31)."""
    for idx, row in df_raw.iloc[:10].iterrows():
        row_vals = [str(v).strip().upper() for v in row.dropna()]
        day_matches = [v for v in row_vals if re.match(r'^(D?\d{1,2})$', v) and 1 <= int(re.sub(r'\D', '', v)) <= 31]
        if len(day_matches) >= 15:  # Valid row contains most days of a month
            return idx
    return None

def parse_rainfall(file_path):
    print("Processing Rainfall Data...")
    xls = pd.ExcelFile(file_path)
    all_rf_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        header_idx = find_header_row(df_raw)
        if header_idx is None:
            continue

        # Extract coordinates if present
        coord_row = df_raw.iloc[:header_idx].fillna('').astype(str).values.flatten()
        coord_text = " ".join(coord_row)
        x_match = re.search(r'(\d+)\s*X', coord_text)
        y_match = re.search(r'(\d+)\s*Y', coord_text)
        coord_x = float(x_match.group(1)) if x_match else np.nan
        coord_y = float(y_match.group(1)) if y_match else np.nan

        df_data = df_raw.iloc[header_idx + 1:].copy()
        df_data.columns = [str(c).strip() for c in df_raw.iloc[header_idx]]

        day_cols = [c for c in df_data.columns if re.match(r'^(D?\d{1,2})$', c, re.IGNORECASE) and 1 <= int(re.sub(r'\D', '', c)) <= 31]
        ym_cols = [c for c in df_data.columns if c not in day_cols and str(c).lower() not in ['nan', 'none', '']]

        if not day_cols or not ym_cols:
            continue

        ym_col = ym_cols[0]
        df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='rainfall_mm')
        
        years, months = parse_year_month_string(df_melted[ym_col])
        df_melted['year_num'] = years
        df_melted['month_num'] = months
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['rainfall_mm'] = pd.to_numeric(df_melted['rainfall_mm'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station
        df_clean['coord_x'] = coord_x
        df_clean['coord_y'] = coord_y

        all_rf_data.append(df_clean[['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y']])

    if not all_rf_data:
        return pd.DataFrame(columns=['date', 'station', 'rainfall_mm', 'coord_x', 'coord_y'])

    df_concat = pd.concat(all_rf_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'rainfall_mm': 'mean',
        'coord_x': 'first',
        'coord_y': 'first'
    })

def parse_water_level(file_path):
    print("Processing Water Level Data...")
    xls = pd.ExcelFile(file_path)
    all_wl_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        msl_val = np.nan
        msl_str = str(df_raw.iloc[2, 1]) if df_raw.shape[1] > 1 else ""
        msl_match = re.search(r'([-+]?\d*\.\d+|\d+)', msl_str)
        if msl_match:
            msl_val = float(msl_match.group(1))

        df_data = df_raw.iloc[5:].copy().iloc[:, :4]
        df_data.columns = ['year', 'month', 'day', 'water_level']

        # Flexible year handling
        years_s = df_data['year'].astype(str).str.replace(r'\D', '', regex=True)
        df_data['year_num'] = pd.to_numeric(years_s, errors='coerce').apply(
            lambda y: y if y >= 2000 else (2000 + y if y <= 30 else 1900 + y) if pd.notna(y) else np.nan
        )
        df_data['month_num'] = pd.to_numeric(df_data['month'], errors='coerce')
        df_data['day_num'] = pd.to_numeric(df_data['day'], errors='coerce')
        df_data['water_level'] = pd.to_numeric(df_data['water_level'], errors='coerce')

        if 'N_Street' in station:
            df_data['water_level_mMSL'] = df_data['water_level'] * 0.3048
            unit = 'mMSL (converted from ft)'
        else:
            df_data['water_level_mMSL'] = df_data['water_level']
            unit = 'mMSL'

        df_data['date'] = pd.to_datetime(
            dict(year=df_data['year_num'], month=df_data['month_num'], day=df_data['day_num']),
            errors='coerce'
        )

        df_clean = df_data.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station
        df_clean['datum_msl_m'] = msl_val
        df_clean['unit'] = unit

        all_wl_data.append(df_clean[['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit']])

    if not all_wl_data:
        return pd.DataFrame(columns=['date', 'station', 'water_level_mMSL', 'datum_msl_m', 'unit'])

    df_concat = pd.concat(all_wl_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({
        'water_level_mMSL': 'mean',
        'datum_msl_m': 'first',
        'unit': 'first'
    })

def parse_discharge(file_path):
    print("Processing Discharge Data...")
    xls = pd.ExcelFile(file_path)
    all_dis_data = []

    for sheet in xls.sheet_names:
        df_raw = pd.read_excel(xls, sheet_name=sheet, header=None)
        station = clean_station_name(sheet)

        header_idx = find_header_row(df_raw)
        if header_idx is None:
            continue

        df_data = df_raw.iloc[header_idx + 1:].copy()
        df_data.columns = [str(c).strip() for c in df_raw.iloc[header_idx]]

        day_cols = [c for c in df_data.columns if re.match(r'^(D?\d{1,2})$', c, re.IGNORECASE) and 1 <= int(re.sub(r'\D', '', c)) <= 31]
        ym_cols = [c for c in df_data.columns if c not in day_cols and str(c).lower() not in ['nan', 'none', '']]

        if not day_cols or not ym_cols:
            continue

        ym_col = ym_cols[0]
        df_melted = pd.melt(df_data, id_vars=[ym_col], value_vars=day_cols, var_name='day', value_name='discharge_cumecs')

        years, months = parse_year_month_string(df_melted[ym_col])
        df_melted['year_num'] = years
        df_melted['month_num'] = months
        df_melted['day'] = df_melted['day'].str.extract(r'(\d+)').astype(int)
        df_melted['discharge_cumecs'] = pd.to_numeric(df_melted['discharge_cumecs'], errors='coerce')

        df_melted['date'] = pd.to_datetime(
            dict(year=df_melted['year_num'], month=df_melted['month_num'], day=df_melted['day']),
            errors='coerce'
        )

        df_clean = df_melted.dropna(subset=['date']).copy()
        df_clean['date'] = df_clean['date'].dt.strftime('%Y-%m-%d')
        df_clean = df_clean[(df_clean['date'] >= '2015-01-01') & (df_clean['date'] <= '2025-12-31')]
        df_clean['station'] = station

        all_dis_data.append(df_clean[['date', 'station', 'discharge_cumecs']])

    if not all_dis_data:
        return pd.DataFrame(columns=['date', 'station', 'discharge_cumecs'])

    df_concat = pd.concat(all_dis_data, ignore_index=True)
    return df_concat.groupby(['date', 'station'], as_index=False).agg({'discharge_cumecs': 'mean'})

def main():
    rf_path = os.path.join(RAW_DIR, "2015 - 2025 RF.xlsx")
    wl_path = os.path.join(RAW_DIR, "2015 - 2025 WL.xlsx")
    dis_path = os.path.join(RAW_DIR, "2015 - 2025 Discharge.xlsx")

    df_rf = parse_rainfall(rf_path)
    df_wl = parse_water_level(wl_path)
    df_dis = parse_discharge(dis_path)

    print("\n=== PARSED ROW COUNTS ===")
    print(f"Rainfall:    {len(df_rf)} rows")
    print(f"Water Level: {len(df_wl)} rows")
    print(f"Discharge:   {len(df_dis)} rows\n")

    print("Building unified daily master table...")
    df_master = pd.merge(df_rf, df_wl, on=['date', 'station'], how='outer')
    df_master = pd.merge(df_master, df_dis, on=['date', 'station'], how='outer')

    # Fill coordinates
    df_master['coord_x'] = df_master['coord_x'].fillna(df_master['station'].map(lambda s: STATION_COORDS.get(s, (np.nan, np.nan))[0]))
    df_master['coord_y'] = df_master['coord_y'].fillna(df_master['station'].map(lambda s: STATION_COORDS.get(s, (np.nan, np.nan))[1]))

    df_master.sort_values(by=['date', 'station'], inplace=True)
    master_path = os.path.join(PROCESSED_DIR, "kelani_master_daily_analytics_2015_2025.csv")
    df_master.to_csv(master_path, index=False)

    print(f"Master file saved to: {master_path}")
    return df_rf, df_wl, df_dis, df_master

if __name__ == '__main__':
    df_rf, df_wl, df_dis, df_master = main()

Processing Rainfall Data...
Processing Water Level Data...
Processing Discharge Data...

=== PARSED ROW COUNTS ===
Rainfall:    2190 rows
Water Level: 28126 rows
Discharge:   0 rows

Building unified daily master table...
Master file saved to: /Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_master_daily_analytics_2015_2025.csv

In [32]:
# Verify outputs in notebook
print("=== DATE RANGES ===")
print("RF:       ", df_rf['date'].min(), "to", df_rf['date'].max())
print("WL:       ", df_wl['date'].min(), "to", df_wl['date'].max())
print("Discharge:", df_dis['date'].min(), "to", df_dis['date'].max())

print("\n=== MASTER TABLE MISSING VALUES ===")
print(df_master.isna().sum())

=== DATE RANGES ===
RF:        2021-01-01 to 2021-12-31
WL:        2015-01-01 to 2025-12-31
Discharge: nan to nan

=== MASTER TABLE MISSING VALUES ===
date                    0
station                 0
rainfall_mm         25959
coord_x                 0
coord_y                 0
water_level_mMSL        0
datum_msl_m             0
unit                    0
discharge_cumecs    28126
dtype: int64

In [34]:
import pandas as pd

file_path = "data/raw/flood/kelani/2015 - 2025 RF.xlsx"

excel = pd.ExcelFile(file_path)

print("SHEETS:")
print(excel.sheet_names)

for sheet in excel.sheet_names:
    print("\n" + "=" * 100)
    print("SHEET:", sheet)
    print("=" * 100)

    df = pd.read_excel(
        file_path,
        sheet_name=sheet,
        header=None,
        nrows=10
    )

    print(df.to_string(index=True, header=False))

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/flood/kelani/2015 - 2025 RF.xlsx'

In [35]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

Current working directory:
/Users/ohaseelanka/disaster_analytics_hub/notebooks

Files/folders here:
['01_data_inventory.ipynb']

In [36]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

print("Project root:", PROJECT_ROOT)
print("Data folder exists:", (PROJECT_ROOT / "data").exists())

Project root: /Users/ohaseelanka/disaster_analytics_hub
Data folder exists: True

In [37]:
kelani_folder = PROJECT_ROOT / "data" / "raw" / "flood" / "kelani"

print("Kelani folder:", kelani_folder)
print("Exists:", kelani_folder.exists())

if kelani_folder.exists():
    print("Files:")
    for file in kelani_folder.iterdir():
        print(" -", file.name)

Kelani folder: /Users/ohaseelanka/disaster_analytics_hub/data/raw/flood/kelani
Exists: True
Files:
 - 2015 - 2025 WL.xlsx
 - 2015 - 2025 RF.xlsx
 - 2015 - 2025 Discharge.xlsx

In [38]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

rf_file = PROJECT_ROOT / "data" / "raw" / "flood" / "kelani" / "2015 - 2025 RF.xlsx"

print("File exists:", rf_file.exists())
print("File:", rf_file)

File exists: True
File: /Users/ohaseelanka/disaster_analytics_hub/data/raw/flood/kelani/2015 - 2025 RF.xlsx

In [39]:
excel = pd.ExcelFile(rf_file)

print("Sheets:")
print(excel.sheet_names)

Sheets:
['KN02-NORWOOD', 'KN07-KITULGALA', ' KN11-HOLOMBUWA', 'KN16-DERANIYAGALA', 'KN18-GLENCOURSE', 'KN21-HANWELLA']

In [40]:
for sheet in excel.sheet_names:
    print("\n" + "=" * 60)
    print("SHEET:", sheet)
    print("=" * 60)

    df_preview = pd.read_excel(
        rf_file,
        sheet_name=sheet,
        header=None,
        nrows=10
    )

    print(df_preview.to_string())

============================================================
SHEET: KN02-NORWOOD
============================================================
                             0     1      2    3     4     5     6     7     8    9    10    11    12    13                                 14    15   16    17    18    19    20    21   22   23   24    25            26    27        28    29        30    31   32   33     34
0                           NaN   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN                                NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN  NaN  NaN    NaN
1  Norwood Daily Rainfall in mm   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN  Cordinate :-   NaN  182051 X   NaN  182230 Y   NaN  NaN  NaN    NaN
2                           NaN   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN                                NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN  NaN  NaN    NaN
3                    Year/Month  YEAR  MONTH   D1    D2    D3    D4    D5    D6   D7   D8    D9   D10   D11                                D12   D13  D14   D15   D16   D17   D18   D19  D20  D21  D22   D23           D24   D25       D26   D27       D28   D29  D30  D31  TOTAL
4                      14/15/04  2015    JAN    0     0     0     0     0   1.7    0    0     0     0     0                                  0     0    0     0     0     0     0     0    0    0    0     0             0     0         0     0      11.7  23.4  4.6  0.5   41.9
5                      14/15/05  2015    FEB    0     0  10.4     0  25.9  23.9    0    0     0  13.2  12.3                               15.1   1.2    0     0     0     0     0     0    0    0  3.8     5           7.2     0      12.5    20      31.7   NaN  NaN  NaN  182.2
6                      14/15/06  2015    MAR  3.7     0     0  20.3   2.5     0    0    0     0     0     0                                  4   4.2  0.6     0   4.8     0     0     0    0    0    0     0             0     0      25.4   1.3       1.8   4.6    7  5.5   85.7
7                      14/15/07  2015    APR   39  26.8   0.7  13.1     0   0.3  9.4  1.3  31.3   7.4     0                                  0  13.9    3    48   7.9     0     0   4.8  8.3    0    0  12.5          39.3  21.4       1.2  38.8       1.2   3.1  8.7  NaN  341.4
8                      14/15/08  2015    MAY  1.9     0     0   3.6  29.9   9.7  1.2    0   3.7  43.3     0                                  0   1.1    0  14.1   1.8   2.1   1.2   3.1    0  1.7    0   1.7             0     0         0     0         0     0    0  5.1  125.2
9                      14/15/09  2015    JUN    0     0   1.3   4.2  16.5     0    0    0     0     0   1.5                                  0     0    0  11.3  48.5  28.9  38.5  12.4  0.9    0    0     0           1.6     0       7.6  16.7       8.1   7.8  1.3  NaN  207.1

============================================================
SHEET: KN07-KITULGALA
============================================================
                                0     1      2     3     4     5     6     7     8     9     10    11    12    13                                 14    15    16    17    18    19    20    21    22    23   24    25            26    27        28    29        30    31    32    33     34
0                              NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN                                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN   NaN    NaN
1  Kithulgala Daily Rainfall in mm   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  Cordinate :-   NaN  160270 X   NaN  198922 Y   NaN   NaN   NaN    NaN
2                              NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN                                NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN   NaN    NaN
3                       Year/Month  YEAR  MONTH    D1    D2    D3    D4    D5    D6    D7    D8    D9   D10   D11                                D12   D13   D14   D15   D16   D17   D18   D19   D20   D21  D22   D23           D24   D25       D26   D27       D28   D29   D30   D31  TOTAL
4                         14/15/04  2015    JAN     0     0     0     0     0   5.3     0     0     0     0     0                                  0     0     0     0     0     0     0     0     0     0    0  33.1             0     0         0     0       2.8  26.9   1.5     0   69.6
5                         14/15/05  2015    FEB     0     0    21     0   0.4   1.7     0     0     8   7.9  16.5                                6.6   0.7     0     0     0     0     0     0     0     0    0   0.3           0.5  11.2      31.3  37.4       8.1   NaN   NaN   NaN  151.6
6                         14/15/06  2015    MAR  55.8     0     0   2.9     0     0     0     0     0     0     0                                0.6  18.7  13.6  52.9   1.9     2     0     0     0     0    0     0             0     0         9     0      53.1  20.5   2.4   2.8  236.2
7                         14/15/07  2015    APR   6.9  14.5     0     0     0     0   5.6     0  13.8  17.4     0                               11.4  10.3     6  36.2  14.2   6.4   1.4   3.7  24.9   0.7    0  25.2           7.4  23.4      17.2   1.1      24.8    19   4.4   NaN  295.9
8                         14/15/08  2015    MAY  18.6   9.6  13.2  12.4  46.5  35.7  47.9  14.6    15  92.8     0                                  0     0    17   6.6   9.8   7.7    20  11.6   6.8  11.8  1.1  44.3             1     0       3.6   2.8         0   8.6    22  43.2  524.2
9                         14/15/09  2015    JUN   7.7     3  16.8  13.2  68.8     0     0   0.5   2.2   0.5  16.6                                1.7   0.7   0.8    73    41  34.1  44.5   9.1     0     4  1.4     0           2.8     0      20.1    20        52  36.6  21.3   NaN  492.4

============================================================
SHEET:  KN11-HOLOMBUWA
============================================================
                               0     1      2     3     4     5     6     7    8     9    10   11    12   13                                 14    15    16    17    18    19   20    21    22   23   24   25    26            27    28        29    30        31    32    33     34
0                             NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN  NaN   NaN  NaN                                NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
1  Holombuwa Daily Rainfall in mm   NaN    NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN  NaN   NaN  NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN  Cordinate :-   NaN  143948 X   NaN  220765 Y   NaN   NaN    NaN
2                             NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN  NaN   NaN  NaN                                NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
3                       YEARMONTH  YEAR  MONTH    D1    D2    D3    D4    D5   D6    D7   D8   D9   D10  D11                                D12   D13   D14   D15   D16   D17  D18   D19   D20  D21  D22  D23   D24           D25   D26       D27   D28       D29   D30   D31  TOTAL
4                        14/15/04  2015    JAN     0     0     0     0     0    0     0    0    0     0    0                                  0     0     0     0     0     0    0     0     0    0    0    0     0             0     0         0   3.6         0   2.5     0    6.1
5                        14/15/05  2015    FEB     0     0  13.5     0   0.3    0     0    0  1.7   7.7    0                                  7     0     0     0     0     0    0     0     0    0    0   12  18.5             0     2       2.3     0       NaN   NaN   NaN     65
6                        14/15/06  2015    MAR  13.4   2.6     0  38.7     0    0     0    0    0     0    0                                  0  28.6     0  69.7  18.1     0    0     0     0    0    0    0     0             0   4.2         0  12.8      19.4  13.1  23.1  243.7
7                        14/15/07  2015    APR  11.7  50.4     0     0     0    7   7.3    0  2.5    31    0                                9.8  50.5  25.7   9.5   2.9     0    0  25.7  45.2  6.1    0  1.2  14.5          17.8  12.6      22.9     0      13.8  13.7   NaN  381.8
8                        14/15/08  2015    MAY     0  16.8   6.4     0     0    0  39.2  2.6  5.3  17.1  0.2                                  0   0.3   3.9   0.8   7.3  19.1   26  17.4   1.9  9.5  1.7  0.5     0             0     0         0     0         0   0.6  32.6  209.2
9                        14/15/09  2015    JUN   8.7     0    16  13.7  19.8    0     0    5    2     0  7.2                                  0   2.8     0  33.2   7.5   8.9  7.5     5     0    0  3.9    0   0.6             0    14      28.3   6.6      14.5  16.5   NaN  221.7

============================================================
SHEET: KN16-DERANIYAGALA
============================================================
                                  0     1      2     3     4     5      6     7     8     9     10    11    12    13                                 14   15    16    17    18    19    20    21   22    23   24    25    26            27    28        29    30        31    32    33     34
0                                NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN                                NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
1  Deraniyagala Daily Rainfall in mm   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN   NaN   NaN  Cordinate :-   NaN  152036 X   NaN  191688 Y   NaN   NaN    NaN
2                                NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN                                NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
3                          YEARMONTH  YEAR  MONTH    D1    D2    D3     D4    D5    D6    D7    D8    D9   D10   D11                                D12  D13   D14   D15   D16   D17   D18   D19  D20   D21  D22   D23   D24           D25   D26       D27   D28       D29   D30   D31  TOTAL
4                           14/15/04  2015    JAN     0     0     0      0     0     0     0     0     0     0     0                                  0    0     0     0     0     0     0     0    0     0    0    30     0             0     0         0   4.1      41.5  50.5     0  126.1
5                           14/15/05  2015    FEB     0     0     9      0   0.7   2.3     0     0  45.1  59.7  64.3                               65.1    0     0     0     0     0     0     0    0     0    0   3.8  41.2             0   1.7      10.3  30.7       NaN   NaN   NaN  333.9
6                           14/15/06  2015    MAR  30.7  53.8  20.5    1.8     4     0     0     0   0.6     0     0                               12.8    0   3.6  57.8     0     0     0     0    0     0    0     0     0             0   6.5      14.5  15.6      24.8     0  55.7  302.7
7                           14/15/07  2015    APR   4.5  81.8     0    2.1     0  68.3  34.7     0     0  35.7     0                               87.3    2   1.3   6.8     0     0   4.2  70.6  7.2    96    0  70.9  27.9            37     0     150.4     0      32.6  33.3   NaN  854.6
8                           14/15/08  2015    MAY   6.7   1.4  35.3  113.7   6.3   6.3  58.5  10.6   1.8  13.7     0                                  0    0  18.5   3.7     3  16.3  20.3  13.5  5.4  14.4    2   4.8     0             0   9.2         0     0         0     0  74.9  440.3
9                           14/15/09  2015    JUN  14.5   4.6  44.1   29.2  80.8     0     0     0   7.2   6.1     9                                0.6  2.7   1.6  45.9  28.7  12.7  25.5  11.3    0     0  0.9     0   7.3             0  21.8      27.9  17.6      38.3   4.8   NaN  443.1

============================================================
SHEET: KN18-GLENCOURSE
============================================================
                                0     1      2     3     4     5      6     7     8      9    10    11    12    13                                 14   15    16    17    18    19    20    21    22    23   24    25    26            27    28        29    30        31    32    33      34
0                              NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN  NaN   NaN   NaN   NaN                                NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN     NaN
1  Glencourse Daily Rainfall in mm   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN  NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  Cordinate :-   NaN  135963 X   NaN  197396 Y   NaN   NaN     NaN
2                              NaN   NaN    NaN   NaN   NaN   NaN    NaN   NaN   NaN    NaN  NaN   NaN   NaN   NaN                                NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN     NaN
3                        YEARMONTH  YEAR  MONTH    D1    D2    D3     D4    D5    D6     D7   D8    D9   D10   D11                                D12  D13   D14   D15   D16   D17   D18   D19   D20   D21  D22   D23   D24           D25   D26       D27   D28       D29   D30   D31   TOTAL
4                         14/15/04  2015    JAN     0     0     0      0     0     0      0    0     0     0     0                                  0    0     0     0     0     0     0     0     0     0    0  38.9     0             0     0         0   0.3      36.8   6.7     0    82.7
5                         14/15/05  2015    FEB     0     0   2.6      0   0.8   3.6      0    0  14.9  10.2   3.6                               29.7  7.9     0     0     0     0     0     0     0     0    0     0  13.7             0  11.5        32   1.1       NaN   NaN   NaN   131.6
6                         14/15/06  2015    MAR     0  14.8     0   22.4   0.8     0      0    0   7.3     0     0                               14.6  4.2   1.4  48.7   6.1     0     0     0     0     0    0     0     0             0  59.7         7  87.2        16  15.1  18.2   323.5
7                         14/15/07  2015    APR  15.4   7.3     0      0     0  80.6  19.39    0     0   3.1    10                               37.9  8.2   3.4     0     0   0.9  35.5  61.1  48.5  95.5    0   1.7  24.8           3.3  48.8       2.3  11.5      62.2   0.3   NaN  581.69
8                         14/15/08  2015    MAY  36.1  10.1  53.5      9   0.3    10    4.3   23   1.8  29.1     0                                  0  1.1  10.9   1.4   0.6   7.9  14.9  13.5  14.5   9.3  0.9   3.6   0.3             0     0         0     0       0.5   0.9  19.4   276.9
9                         14/15/09  2015    JUN  22.2   0.6  10.7  104.8  16.5     0      0    0   2.5     0  86.6                                0.3  6.5   1.4  36.1  20.8  12.3  22.7  12.9     0     0  2.8     0   0.9           1.4  30.2        11  14.3       5.1   0.9   NaN   423.5

============================================================
SHEET: KN21-HANWELLA
============================================================
                              0     1      2     3    4     5     6    7     8     9    10    11   12    13                                 14    15    16    17    18   19    20    21   22   23   24    25    26            27    28        29    30        31    32    33     34
0                            NaN   NaN    NaN   NaN  NaN   NaN   NaN  NaN   NaN   NaN  NaN   NaN  NaN   NaN                                NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
1  Hanwella Daily Rainfall in mm   NaN    NaN   NaN  NaN   NaN   NaN  NaN   NaN   NaN  NaN   NaN  NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN  Cordinate :-   NaN  123689 X   NaN  189980 Y   NaN   NaN    NaN
2                            NaN   NaN    NaN   NaN  NaN   NaN   NaN  NaN   NaN   NaN  NaN   NaN  NaN   NaN                                NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN   NaN    NaN
3                      YEARMONTH  YEAR  MONTH    D1   D2    D3    D4   D5    D6    D7   D8    D9  D10   D11                                D12   D13   D14   D15   D16  D17   D18   D19  D20  D21  D22   D23   D24           D25   D26       D27   D28       D29   D30   D31  TOTAL
4                       14/15/04  2015    JAN     0    0     0     0    0     0     0    0     0    0     0                                  0     0     0     0     0    0     0     0    0    0    0  16.4  16.6             0     0       0.6   8.4      39.9  10.5     0   92.4
5                       14/15/05  2015    FEB     0    0   7.8     0  2.2  48.6     0    0  78.5   63  16.5                                2.7   1.3     0     0     0    0     0     0    0    0    0     0   2.3             0   3.3       4.6   0.3       NaN   NaN   NaN  231.1
6                       14/15/06  2015    MAR     0    0   1.3  19.6    0     0     0    0  38.3    0     0                                  0  14.4  20.9  38.3   3.3   18     0     0    0    0    0     0     0             0   2.3       2.5  68.5       1.2  15.1    29  272.7
7                       14/15/07  2015    APR  56.8  2.2     0     0    0     0  17.7    0     0    1  30.5                               29.2  23.5   6.2     0     0    0     0  12.1   13  2.6    0     0   7.3           1.5     0      34.2     0       6.7  12.8   NaN  257.3
8                       14/15/08  2015    MAY   3.8  9.5     0   3.2   15   3.5   9.1  5.6   3.3  7.4   2.5                                  0   4.5  22.2     0   1.3  5.1  16.7  20.9  7.8  6.8  0.3   6.6     0             0     0         0     0         0   0.4  25.1  180.6
9                       14/15/09  2015    JUN   7.9  0.8  22.8    98  5.5   1.4   1.3    0     0    0  54.4                                1.8     2     0  38.4  31.6  3.2  27.9     6  0.7    0  2.5     0   0.8             0  23.5      15.8  23.5       6.1     0   NaN  375.9

In [42]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

rf_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "flood"
    / "kelani"
    / "2015 - 2025 RF.xlsx"
)

output_file = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "flood"
    / "rainfall_daily_long.parquet"
)

output_file.parent.mkdir(parents=True, exist_ok=True)

print("Input:", rf_file)
print("Output:", output_file)

Input: /Users/ohaseelanka/disaster_analytics_hub/data/raw/flood/kelani/2015 - 2025 RF.xlsx
Output: /Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/rainfall_daily_long.parquet

In [43]:
# Station information
station_info = {
    "KN02-NORWOOD": {
        "station_id": "KN02",
        "station_name": "Norwood"
    },
    "KN07-KITULGALA": {
        "station_id": "KN07",
        "station_name": "Kitulgala"
    },
    " KN11-HOLOMBUWA": {
        "station_id": "KN11",
        "station_name": "Holombuwa"
    },
    "KN16-DERANIYAGALA": {
        "station_id": "KN16",
        "station_name": "Deraniyagala"
    },
    "KN18-GLENCOURSE": {
        "station_id": "KN18",
        "station_name": "Glencourse"
    },
    "KN21-HANWELLA": {
        "station_id": "KN21",
        "station_name": "Hanwella"
    }
}

all_station_data = []

for sheet_name in pd.ExcelFile(rf_file).sheet_names:

    print(f"Processing: {sheet_name}")

    # Read the actual table beginning at row 3
    df = pd.read_excel(
        rf_file,
        sheet_name=sheet_name,
        header=3
    )

    # Remove accidental whitespace from column names
    df.columns = df.columns.astype(str).str.strip()

    info = station_info[sheet_name]

    # Keep only the daily rainfall columns
    day_columns = [f"D{i}" for i in range(1, 32)]

    # Convert N.A. and other non-numeric values to NaN
    for col in day_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Convert month names to month numbers
    month_numbers = {
        "JAN": 1,
        "FEB": 2,
        "MAR": 3,
        "APR": 4,
        "MAY": 5,
        "JUN": 6,
        "JUL": 7,
        "AUG": 8,
        "SEP": 9,
        "OCT": 10,
        "NOV": 11,
        "DEC": 12
    }

    df["month_number"] = (
        df["MONTH"]
        .astype(str)
        .str.strip()
        .str.upper()
        .map(month_numbers)
    )

    # Convert wide format into daily long format
    long_df = df.melt(
        id_vars=["YEAR", "MONTH", "month_number"],
        value_vars=day_columns,
        var_name="day_column",
        value_name="rainfall_mm"
    )

    # Extract day number from D1, D2, ... D31
    long_df["day"] = (
        long_df["day_column"]
        .str.replace("D", "", regex=False)
        .astype(int)
    )

    # Construct actual date
    long_df["date"] = pd.to_datetime(
        dict(
            year=long_df["YEAR"],
            month=long_df["month_number"],
            day=long_df["day"]
        ),
        errors="coerce"
    )

    # Add station information
    long_df["station_id"] = info["station_id"]
    long_df["station_name"] = info["station_name"]

    # Keep only required columns
    long_df = long_df[
        [
            "station_id",
            "station_name",
            "date",
            "rainfall_mm"
        ]
    ]

    # Remove invalid calendar dates
    long_df = long_df.dropna(subset=["date"])

    all_station_data.append(long_df)

# Combine all stations
rainfall_daily = pd.concat(
    all_station_data,
    ignore_index=True
)

# Sort
rainfall_daily = rainfall_daily.sort_values(
    ["station_id", "date"]
).reset_index(drop=True)

print("\nFinal shape:", rainfall_daily.shape)
print("\nStations:")
print(rainfall_daily["station_id"].unique())

print("\nDate range:")
print(rainfall_daily["date"].min())
print(rainfall_daily["date"].max())

print("\nPreview:")
print(rainfall_daily.head(20))

Processing: KN02-NORWOOD
Processing: KN07-KITULGALA
Processing:  KN11-HOLOMBUWA
Processing: KN16-DERANIYAGALA
Processing: KN18-GLENCOURSE
Processing: KN21-HANWELLA

Final shape: (24108, 4)

Stations:
['KN02' 'KN07' 'KN11' 'KN16' 'KN18' 'KN21']

Date range:
2015-01-01 00:00:00
2025-12-31 00:00:00

Preview:
   station_id station_name       date  rainfall_mm
0        KN02      Norwood 2015-01-01          0.0
1        KN02      Norwood 2015-01-02          0.0
2        KN02      Norwood 2015-01-03          0.0
3        KN02      Norwood 2015-01-04          0.0
4        KN02      Norwood 2015-01-05          0.0
5        KN02      Norwood 2015-01-06          1.7
6        KN02      Norwood 2015-01-07          0.0
7        KN02      Norwood 2015-01-08          0.0
8        KN02      Norwood 2015-01-09          0.0
9        KN02      Norwood 2015-01-10          0.0
10       KN02      Norwood 2015-01-11          0.0
11       KN02      Norwood 2015-01-12          0.0
12       KN02      Norwood 2015-01-13          0.0
13       KN02      Norwood 2015-01-14          0.0
14       KN02      Norwood 2015-01-15          0.0
15       KN02      Norwood 2015-01-16          0.0
16       KN02      Norwood 2015-01-17          0.0
17       KN02      Norwood 2015-01-18          0.0
18       KN02      Norwood 2015-01-19          0.0
19       KN02      Norwood 2015-01-20          0.0

In [44]:
print(rainfall_daily.info())

print("\nMissing rainfall:")
print(rainfall_daily["rainfall_mm"].isna().sum())

print("\nMissing percentage:")
print(
    rainfall_daily["rainfall_mm"].isna().mean() * 100
)

print("\nRows per station:")
print(
    rainfall_daily.groupby("station_id").size()
)

print("\nRainfall statistics:")
print(
    rainfall_daily["rainfall_mm"].describe()
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24108 entries, 0 to 24107
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   station_id    24108 non-null  object
 1   station_name  24108 non-null  object
 2   date          24108 non-null  datetime64[ns]
 3   rainfall_mm   24103 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 753.5+ KB
None

Missing rainfall:
5

Missing percentage:
0.02074000331840053

Rows per station:
station_id
KN02    4018
KN07    4018
KN11    4018
KN16    4018
KN18    4018
KN21    4018
dtype: int64

Rainfall statistics:
count    24103.000000
mean        10.652118
std         21.368306
min          0.000000
25%          0.000000
50%          1.100000
75%         11.900000
max        355.600000
Name: rainfall_mm, dtype: float64

In [45]:
print(
    rainfall_daily[
        rainfall_daily["rainfall_mm"].isna()
    ].head(20)
)

      station_id  station_name       date  rainfall_mm
395         KN02       Norwood 2016-01-31          NaN
1126        KN02       Norwood 2018-01-31          NaN
1185        KN02       Norwood 2018-03-31          NaN
3683        KN02       Norwood 2025-01-31          NaN
15870       KN16  Deraniyagala 2025-06-13          NaN

In [46]:
print(
    rainfall_daily[
        rainfall_daily["date"].dt.month == 2
    ].tail(20)
)

      station_id station_name       date  rainfall_mm
23782       KN21     Hanwella 2025-02-09          0.0
23783       KN21     Hanwella 2025-02-10          0.0
23784       KN21     Hanwella 2025-02-11          0.0
23785       KN21     Hanwella 2025-02-12          0.0
23786       KN21     Hanwella 2025-02-13          0.0
23787       KN21     Hanwella 2025-02-14          0.0
23788       KN21     Hanwella 2025-02-15          0.0
23789       KN21     Hanwella 2025-02-16          0.0
23790       KN21     Hanwella 2025-02-17          0.0
23791       KN21     Hanwella 2025-02-18          0.0
23792       KN21     Hanwella 2025-02-19          0.0
23793       KN21     Hanwella 2025-02-20          0.0
23794       KN21     Hanwella 2025-02-21          0.0
23795       KN21     Hanwella 2025-02-22          0.0
23796       KN21     Hanwella 2025-02-23          0.0
23797       KN21     Hanwella 2025-02-24          0.0
23798       KN21     Hanwella 2025-02-25         24.4
23799       KN21     Hanwella 2025-02-26          0.0
23800       KN21     Hanwella 2025-02-27          0.7
23801       KN21     Hanwella 2025-02-28         19.3

In [47]:
rainfall_daily.to_parquet(
    output_file,
    index=False
)

print("Saved successfully:")
print(output_file)

Saved successfully:
/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/rainfall_daily_long.parquet

In [48]:
wl_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "flood"
    / "kelani"
    / "2015 - 2025 WL.xlsx"
)

print("File exists:", wl_file.exists())

excel_wl = pd.ExcelFile(wl_file)

print("\nSheets:")
print(excel_wl.sheet_names)

File exists: True

Sheets:
['Norwood', 'Kithulgala', 'Deraniyagala', 'Holombuwa', 'Glencourse', 'Hanwella', "N'Street"]

In [49]:
for sheet_name in excel_wl.sheet_names:
    print("\n" + "=" * 70)
    print("SHEET:", repr(sheet_name))
    print("=" * 70)

    df_preview = pd.read_excel(
        wl_file,
        sheet_name=sheet_name,
        header=None,
        nrows=12
    )

    print(df_preview.to_string())

======================================================================
SHEET: 'Norwood'
======================================================================
                             0         1     2            3
0     Kehelgamu Oya at Norwood       NaN   NaN          NaN
1   Hourly Water Level in mMSL       NaN   NaN          NaN
2                          MSL  1097.76m   NaN          NaN
3                          NaN       NaN   NaN          NaN
4                         Year     Month  Date      Avg. WL
5                         1996         1     1  1098.211667
6                         1996         1     2  1098.253333
7                         1996         1     3  1098.202917
8                         1996         1     4  1098.143333
9                         1996         1     5    1098.1125
10                        1996         1     6    1098.0975
11                        1996         1     7   1098.08375

======================================================================
SHEET: 'Kithulgala'
======================================================================
                             0        1     2          3
0   Kelani Ganga at Kithulgala      NaN   NaN        NaN
1   Hourly Water Level in mMSL      NaN   NaN        NaN
2                          MSL  52.123m   NaN        NaN
3                          NaN      NaN   NaN        NaN
4                         Year    Month  Date    Avg. WL
5                         1996        1     1  53.476667
6                         1996        1     2     53.465
7                         1996        1     3  53.516667
8                         1996        1     4  53.475417
9                         1996        1     5  53.434167
10                        1996        1     6   53.40625
11                        1996        1     7  53.363333

======================================================================
SHEET: 'Deraniyagala'
======================================================================
                                   0       1     2          3
0   Seethawaka Ganga at Deraniyagala     NaN   NaN        NaN
1         Hourly Water Level in mMSL     NaN   NaN        NaN
2                                MSL  73.21m   NaN        NaN
3                                NaN     NaN   NaN        NaN
4                               Year   Month  Date    Avg. WL
5                               2015       1     1  73.733872
6                               2015       1     2  73.689424
7                               2015       1     3  73.651326
8                               2015       1     4  73.636722
9                               2015       1     5  73.622117
10                              2015       1     6  73.622117
11                              2015       1     7  73.617037

======================================================================
SHEET: 'Holombuwa'
======================================================================
                             0       1     2          3
0    Gurugoda Oya at Holombuwa     NaN   NaN        NaN
1   Hourly Water Level in mMSL     NaN   NaN        NaN
2                          MSL  44.55m   NaN        NaN
3                          NaN     NaN   NaN        NaN
4                         Year   Month  Date    Avg. WL
5                         2015       1     1  45.622168
6                         2015       1     2  45.496444
7                         2015       1     3  45.427233
8                         2015       1     4  45.394214
9                         2015       1     5  45.345957
10                        2015       1     6  45.318018
11                        2015       1     7  45.302144

======================================================================
SHEET: 'Glencourse'
======================================================================
                             0          1     2         3
0   Kelani Ganga at Glencourse        NaN   NaN       NaN
1   Hourly Water Level in mMSL        NaN   NaN       NaN
2                          MSL  (-0.118)m   NaN       NaN
3                          NaN        NaN   NaN       NaN
4                         Year      Month  Date   Avg. WL
5                         2015          1     1  9.896627
6                         2015          1     2  9.694707
7                         2015          1     3  9.605811
8                         2015          1     4  9.381667
9                         2015          1     5   9.33087
10                        2015          1     6   9.33341
11                        2015          1     7   9.22229

======================================================================
SHEET: 'Hanwella'
======================================================================
                             0      1     2         3
0     Kelani Ganga at Hanwella    NaN   NaN       NaN
1   Hourly Water Level in mMSL    NaN   NaN       NaN
2                          MSL  0.56m   NaN       NaN
3                          NaN    NaN   NaN       NaN
4                         Year  Month  Date   Avg. WL
5                         2015      1     1   2.51375
6                         2015      1     2  2.194167
7                         2015      1     3  2.063333
8                         2015      1     4     1.865
9                         2015      1     5  1.740833
10                        2015      1     6  1.760833
11                        2015      1     7      1.67

======================================================================
SHEET: "N'Street"
======================================================================
                              0      1     2             3
0      Kelani Ganga at N'Street    NaN   NaN           NaN
1   Hourly Water Level in ftMSL    NaN   NaN           NaN
2                           MSL  0.0ft   NaN           NaN
3                           NaN    NaN   NaN           NaN
4                          Year  Month  Date  Avg. WL (ft)
5                          2015      1     1      1.508333
6                          2015      1     2      1.516667
7                          2015      1     3      1.458333
8                          2015      1     4      1.585417
9                          2015      1     5       1.44375
10                         2015      1     6      1.370833
11                         2015      1     7      1.383333

In [50]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

wl_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "flood"
    / "kelani"
    / "2015 - 2025 WL.xlsx"
)

output_file = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "flood"
    / "water_level_daily.parquet"
)

output_file.parent.mkdir(parents=True, exist_ok=True)

station_info = {
    "Norwood": {
        "station_id": "KN02",
        "station_name": "Norwood",
        "unit": "mMSL"
    },
    "Kithulgala": {
        "station_id": "KN07",
        "station_name": "Kitulgala",
        "unit": "mMSL"
    },
    "Deraniyagala": {
        "station_id": "KN16",
        "station_name": "Deraniyagala",
        "unit": "mMSL"
    },
    "Holombuwa": {
        "station_id": "KN11",
        "station_name": "Holombuwa",
        "unit": "mMSL"
    },
    "Glencourse": {
        "station_id": "KN18",
        "station_name": "Glencourse",
        "unit": "mMSL"
    },
    "Hanwella": {
        "station_id": "KN21",
        "station_name": "Hanwella",
        "unit": "mMSL"
    },
    "N'Street": {
        "station_id": "NSTR",
        "station_name": "N'Street",
        "unit": "ftMSL"
    }
}

all_wl = []

for sheet_name, info in station_info.items():

    df = pd.read_excel(
        wl_file,
        sheet_name=sheet_name,
        header=4
    )

    # Clean column names
    df.columns = df.columns.astype(str).str.strip()

    print("\nProcessing:", sheet_name)
    print("Columns:", df.columns.tolist())

    # Rename columns according to the confirmed structure
    if sheet_name == "N'Street":
        df = df.rename(columns={
            "Year": "year",
            "Month": "month",
            "Date": "day",
            "Avg. WL (ft)": "water_level"
        })
    else:
        df = df.rename(columns={
            "Year": "year",
            "Month": "month",
            "Date": "day",
            "Avg. WL": "water_level"
        })

    # Convert numeric columns
    for col in ["year", "month", "day", "water_level"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Construct date
    df["date"] = pd.to_datetime(
        dict(
            year=df["year"],
            month=df["month"],
            day=df["day"]
        ),
        errors="coerce"
    )

    # Add station information
    df["station_id"] = info["station_id"]
    df["station_name"] = info["station_name"]
    df["unit"] = info["unit"]

    # Keep only required fields
    df = df[
        [
            "station_id",
            "station_name",
            "date",
            "water_level",
            "unit"
        ]
    ]

    # Remove rows where date itself is invalid
    df = df.dropna(subset=["date"])

    all_wl.append(df)

water_level_daily = pd.concat(
    all_wl,
    ignore_index=True
)

water_level_daily = water_level_daily.sort_values(
    ["station_id", "date"]
).reset_index(drop=True)

print("\nFinal shape:", water_level_daily.shape)

print("\nStations:")
print(water_level_daily["station_id"].unique())

print("\nDate ranges:")
print(
    water_level_daily
    .groupby(["station_id", "station_name"])["date"]
    .agg(["min", "max", "count"])
)

print("\nMissing water-level values:")
print(
    water_level_daily["water_level"].isna().sum()
)

print("\nUnits:")
print(
    water_level_daily.groupby("station_id")["unit"].unique()
)

Processing: Norwood
Columns: ['Year', 'Month', 'Date', 'Avg. WL', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28']

Processing: Kithulgala
Columns: ['Year', 'Month', 'Date', 'Avg. WL']

Processing: Deraniyagala
Columns: ['Year', 'Month', 'Date', 'Avg. WL']

Processing: Holombuwa
Columns: ['Year', 'Month', 'Date', 'Avg. WL']

Processing: Glencourse
Columns: ['Year', 'Month', 'Date', 'Avg. WL']

Processing: Hanwella
Columns: ['Year', 'Month', 'Date', 'Avg. WL']

Processing: N'Street
Columns: ['Year', 'Month', 'Date', 'Avg. WL (ft)']

Final shape: (42006, 5)

Stations:
['KN02' 'KN07' 'KN11' 'KN16' 'KN18' 'KN21' 'NSTR']

Date ranges:
                               min        max  count
station_id station_name
KN02       Norwood      1996-01-01 2025-12-31  10958
KN07       Kitulgala    1996-01-01 2025-12-31  10958
KN11       Holombuwa    2015-01-01 2025-12-31   4018
KN16       Deraniyagala 2015-01-01 2025-12-31   4018
KN18       Glencourse   2015-01-01 2025-12-31   4018
KN21       Hanwella     2015-01-01 2025-12-31   4018
NSTR       N'Street     2015-01-01 2025-12-31   4018

Missing water-level values:
10

Units:
station_id
KN02     [mMSL]
KN07     [mMSL]
KN11     [mMSL]
KN16     [mMSL]
KN18     [mMSL]
KN21     [mMSL]
NSTR    [ftMSL]
Name: unit, dtype: object

In [51]:
water_level_daily.to_parquet(output_file, index=False)

print("Saved successfully:", output_file)
print("File exists:", output_file.exists())

Saved successfully: /Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/water_level_daily.parquet
File exists: True

In [52]:
discharge_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "flood"
    / "kelani"
    / "2015 - 2025 Discharge.xlsx"
)

print("File exists:", discharge_file.exists())

excel_discharge = pd.ExcelFile(discharge_file)

print("\nSheets:")
print(excel_discharge.sheet_names)

File exists: True

Sheets:
['Norwood', 'Kithulgala', 'Deraniyagala', 'Holombuwa', 'Glencourse', 'Hanwella']

In [53]:
for sheet_name in excel_discharge.sheet_names:
    print("\n" + "=" * 70)
    print("SHEET:", repr(sheet_name))
    print("=" * 70)

    df_preview = pd.read_excel(
        discharge_file,
        sheet_name=sheet_name,
        header=None,
        nrows=12
    )

    print(df_preview.to_string())

======================================================================
SHEET: 'Norwood'
======================================================================
                                   0         1         2          3          4          5          6         7          8          9          10         11         12        13        14        15         16        17        18        19        20        21        22        23        24        25        26        27         28        29        30        31
0            Kehelgamu Oya at Norwood       NaN       NaN        NaN        NaN        NaN        NaN       NaN        NaN        NaN        NaN        NaN        NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN
1   Daily Average Discharge in cumecs       NaN       NaN        NaN        NaN        NaN        NaN       NaN        NaN        NaN        NaN        NaN        NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN
2                                 NaN       NaN       NaN        NaN        NaN        NaN        NaN       NaN        NaN        NaN        NaN        NaN        NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN
3                           YEARMONTH        D1        D2         D3         D4         D5         D6        D7         D8         D9        D10        D11        D12       D13       D14       D15        D16       D17       D18       D19       D20       D21       D22       D23       D24       D25       D26       D27        D28       D29       D30       D31
4                            2015 Jan  8.509801  6.902546   7.394394   7.121124   6.819315   6.630659  6.175714   5.626016   5.263352   4.959773   4.756467   4.583691  4.251836  3.996093  3.913382   3.700951  3.560417  3.404478  3.269798  3.120182  2.905066    2.5619  2.938179  3.111569  2.798339  2.654672  2.464305   3.122195  4.424972  4.206189  5.132493
5                            2015 Feb  4.350544  3.197624   3.001585   3.894239   3.472079   8.408243  5.368316   3.551123   3.002054    7.58552  24.428389  15.177951  8.269731  5.735947  4.539982   3.961773  3.542437  3.346655  3.047423  2.837598   2.67031  3.869216  5.119445  4.119249  3.284945  5.917738   7.29056   8.389487       NaN       NaN       NaN
6                            2015 Mar  6.080805  4.634424   4.306572   5.754567   5.735837   4.027676  3.430792   3.007579   3.002522   2.783755   3.317919   2.957365  3.241552  3.119319  2.698988   2.513348  2.299081  1.996448  1.881979  1.762314  1.697005  1.629215  1.525284  1.448998  1.307125  2.214185  2.203536   1.730293  2.110178  2.516743  2.259918
7                            2015 Apr  7.685325  7.972914  10.797781    8.58574   4.642481   3.549675  3.029773   2.955375    7.88754  11.710355  12.814668   7.710963  7.892419  7.337134  9.304138  11.030155  6.591071  4.474175  6.963389  6.183106  4.957409  4.131198  3.044563  7.368608  7.811522  5.636141  7.037713  10.915688  9.736352  8.637378       NaN
8                            2015 May  8.130887  6.201165   5.996689  10.105778  14.866291  13.069665   11.5183  12.472654  10.835416  10.885052   9.514675   7.570691  6.712485   6.61516  5.755726   5.759941  5.506436  6.249338  6.467666  5.667746  4.698314  4.362735  4.007962  3.799534  3.422926  3.199754  3.143335   2.991004  2.934703  2.951511  2.643623
9                            2015 Jun  2.648679  2.540738   2.316731   2.905864   7.260131   5.203408  2.987587   2.514636   2.331549   2.272277   2.151134   2.042446  2.056562  2.051856  2.144724   2.749882  6.857069  6.534191  7.143655  4.892656  3.338042  2.616797  2.346836  2.347187  2.199357  2.160779  2.409855   2.947274  2.991355  2.552958       NaN
10                           2015 Jul  2.294025  2.113844   1.816318    1.75796   1.804193   1.915032  1.721116   1.537877   1.508804   3.030939   7.051175   4.216171  2.637959   2.17548  2.147131   2.322256  3.867472  3.444045  3.192451  3.476374   3.32397  3.223726  3.206918  3.281901  2.985128  2.698051  2.411633   2.292034  2.161364  1.754873  1.440407
11                           2015 Aug  1.396729  1.389191   1.265671   1.308179   5.035499   2.860964  1.532448   1.445112   1.338327   1.530223   1.506207   1.369295  1.460421   1.40038  4.999631  10.761813  5.278467  3.570156  2.831019  2.599871   2.27909  1.923272  1.714889  1.582961  1.420979  1.421447  1.472429   3.114833  2.468389  1.570228     1.374

======================================================================
SHEET: 'Kithulgala'
======================================================================
                                   0          1          2          3          4          5          6          7          8          9          10         11         12         13         14         15         16         17         18         19         20         21         22         23         24         25         26         27         28         29         30         31
0          Kelani Ganga at Kithulgala        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
1   Daily Average Discharge in cumecs        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2                                 NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
3                           YEARMONTH         D1         D2         D3         D4         D5         D6         D7         D8         D9        D10        D11        D12        D13        D14        D15        D16        D17        D18        D19        D20        D21        D22        D23        D24        D25        D26        D27        D28        D29        D30        D31
4                            2015 Jan  36.915004  35.903387  35.270563  26.456657   33.90992  35.765173  32.843959  29.231109  28.261365  33.275582  31.838667  32.706955  31.145549  32.299847  33.366278  31.608379  30.784311   19.85873  25.581584  30.054874  30.123308  29.403086  30.597639  29.785542  27.496922  29.607783  28.828948  28.547677  28.195352   26.73917  27.736927
5                            2015 Feb  27.823521  25.856458  24.936821  19.432898  27.685379  26.086474  25.260664  25.876027  23.831283  30.446546  30.657066  29.002168  31.652537  32.831685  32.074841  29.498458  28.895232  30.306046  29.319049   26.92938  28.453422  29.372955  27.959616  29.146467  30.091966  28.353782  29.603045  26.380155        NaN        NaN        NaN
6                            2015 Mar  27.516397  31.804204   32.36395  28.653715  30.362884  27.253422  25.489908  24.114673  25.936967  26.602406  27.267845  28.083908  22.727635  23.928168  24.181928  28.059632  25.425878  26.425388  26.811173  26.539994  24.960898  21.743404  25.325601   23.73252  25.267698  25.798012  23.056456   22.56551  20.678487  22.011651  19.872819
7                            2015 Apr  19.930827  18.678705  18.773502  26.160325  25.827506  27.392408  19.582885  29.339464  25.572264  28.380386  27.446523  26.534713  27.278105  25.999244  28.110407  30.368604   26.81276  26.619658   25.68781  27.671185  22.118722  22.609866  23.024436   24.01974  23.714694  23.638161  23.345493  26.169843  27.407103  23.886744        NaN
8                            2015 May  26.286506  24.729306   20.77988  23.991561  33.240828  34.303251  42.179548  35.436028  40.282182  27.731029  32.802295  31.988821  33.039544  29.034991  29.578028  27.911868  17.038846  31.797441  32.868109  28.547447  31.028355  29.860875  31.532754  29.572778  29.683387  33.301006  34.638313  33.382017  35.006346  29.447276  31.890224
9                            2015 Jun  35.280489  28.263483  35.211919  37.388229  37.980993  37.833838  31.065353  37.627659  34.084318  33.048154  25.242378  26.639666  21.842773  21.885825  26.241648  30.880758  33.120961  33.249355  43.907639  34.031487  26.874274   31.70493  30.343044  24.522793  26.302881   26.62161  23.391999  25.174237   37.48431  39.269783        NaN
10                           2015 Jul  30.745038  33.118039  33.433272  29.183601  24.596508  25.726823  27.287623  26.115134   25.74468  36.774472  65.723556  45.005954  35.488045  29.950162  28.276571  27.311732  32.982288  33.474904  29.233614  30.477157  28.753052  29.914176  35.158451  29.503238  25.457366  24.401424  32.285601  33.170703  27.223426   26.71288  25.410891
11                           2015 Aug  23.202102  22.063615  24.779476  24.064911  33.815863  26.313944  27.885035  25.827204  26.904729  29.144452  30.318392  31.915648  33.384876  34.553535   40.66325  33.090705  25.291149  29.784133  32.112204  31.376651  30.628344  28.253433  28.652702  27.235731  27.187378  26.456928  27.893405  35.414633  35.569828  35.866671  37.774557

======================================================================
SHEET: 'Deraniyagala'
======================================================================
                                   0          1          2          3          4          5          6          7          8          9          10         11         12         13         14         15         16         17         18         19         20         21         22         23         24         25         26         27         28         29         30         31     32
0    Seethawaka Ganga at Deraniyagala        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN    NaN
1   Daily Average Discharge in cumecs        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN    NaN
2                                 NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN    NaN
3                           YEARMONTH         D1         D2         D3         D4         D5         D6         D7         D8         D9        D10        D11        D12        D13        D14        D15        D16        D17        D18        D19        D20        D21        D22        D23        D24        D25        D26        D27        D28        D29        D30        D31  UNITS
4                            2015 Jan      9.625      8.625   7.833333   7.458333   7.333333   7.458333   7.208333          7   7.083333          7   6.458333   6.416667   6.208333          6   5.791667   5.458333   5.208333       5.25      5.375   5.416667   5.166667      5.375   5.208333      5.125          5   4.958333   5.291667   4.958333   5.916667      7.875   5.833333    NaN
5                            2015 Feb   5.041667      5.125        5.5   5.416667   4.958333   6.958333       6.25   4.916667   6.541667   6.916667  10.083333  14.416667       11.5      7.875   6.833333   6.208333        5.5      5.125   5.083333          5   5.083333   4.833333   4.958333   5.958333       5.75   6.333333  17.416667      14.25        NaN        NaN        NaN    NaN
6                            2015 Mar   7.291667   9.333333   8.833333   7.833333        7.5       6.75   5.291667   5.041667   5.166667        5.5   5.041667   5.041667   5.208333      5.875  12.166667  12.041667   6.958333   5.666667      5.375   5.208333      4.875   4.333333   4.666667   4.666667   4.666667   4.333333      4.625      4.875       6.25   6.083333   5.541667    NaN
7                            2015 Apr   5.416667   9.833333   9.333333      6.125   5.416667          6   7.541667   8.208333      5.875      7.375      9.625  23.583333         29         12      17.25     17.375   7.916667   7.166667  14.166667  13.583333  19.916667  12.708333     13.875      17.75  19.958333     14.375  16.583333       17.5  20.791667     19.875        NaN    NaN
8                            2015 May  13.833333  11.916667  13.708333  18.958333  25.333333  17.291667  33.083333  33.666667  20.416667  25.583333  24.333333  15.583333  12.541667  11.791667  10.541667  12.208333  11.958333  13.666667     16.625  18.166667  14.541667  14.458333  13.208333  14.416667  12.291667      10.75   8.958333          9   9.041667   8.666667  15.666667    NaN
9                            2015 Jun     24.625  15.833333  13.166667  19.208333  63.666667  29.583333     18.125      14.75  13.291667  11.916667  11.833333         13     10.375       9.25      11.75  23.041667  25.791667      24.75      27.75     23.375  15.916667     13.875  11.916667  10.708333  10.166667   9.458333      12.25  14.708333  29.583333     17.375        NaN    NaN
10                           2015 Jul  16.333333  14.458333  12.666667     14.875  16.958333      14.25  10.916667      10.75  10.208333  22.541667      54.75  21.833333     17.125  14.916667         15  13.333333  18.291667  13.708333  11.958333  11.583333      12.25  15.833333  19.541667  12.791667  10.708333  10.916667       9.75   8.541667      8.375      7.875   7.166667    NaN
11                           2015 Aug   7.083333          7   7.041667  12.541667      23.75  10.333333   8.333333          8      7.875   7.791667   8.916667       11.5       10.5   8.041667  11.916667  11.791667   9.333333      9.375      8.125   7.416667   7.083333   7.791667   9.333333     11.625  23.291667  17.083333  17.333333  35.166667  19.791667  18.458333     19.375    NaN

======================================================================
SHEET: 'Holombuwa'
======================================================================
                                   0          1          2         3         4         5          6         7          8         9         10        11        12        13        14         15         16        17        18        19         20        21        22        23        24         25        26         27         28         29        30        31
0           Gurugoda Oya at Holombuwa        NaN        NaN       NaN       NaN       NaN        NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN        NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN        NaN       NaN        NaN        NaN        NaN       NaN       NaN
1   Daily Average Discharge in cumecs        NaN        NaN       NaN       NaN       NaN        NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN        NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN        NaN       NaN        NaN        NaN        NaN       NaN       NaN
2                                 NaN        NaN        NaN       NaN       NaN       NaN        NaN       NaN        NaN       NaN       NaN       NaN       NaN       NaN       NaN        NaN        NaN       NaN       NaN       NaN        NaN       NaN       NaN       NaN       NaN        NaN       NaN        NaN        NaN        NaN       NaN       NaN
3                           YEARMONTH         D1         D2        D3        D4        D5         D6        D7         D8        D9       D10       D11       D12       D13       D14        D15        D16       D17       D18       D19        D20       D21       D22       D23       D24        D25       D26        D27        D28        D29       D30       D31
4                            2015 Jan  14.560833  11.508333  9.912917     9.195  8.194167   7.633333  7.325417        6.7   5.97375   5.43125  5.030833   4.55125  4.207083  4.092083    3.84875   3.892083  4.064167  3.343333  3.371667   3.023333  2.762917   2.75625  2.589583   2.56375   2.600417  2.531667   2.030417     1.9575   2.366667  2.310417     2.435
5                            2015 Feb   2.033333   1.817083   2.48125   4.29375  1.805833   1.765833    1.7725   1.310417  1.064583  1.363333    1.4375    2.4775  3.018333   2.78125     1.6375   1.482917  0.950417    1.0025   0.96125   0.867083   0.55375  0.662083      0.74  0.981667  12.894167  4.005417      2.515     1.8475        NaN       NaN       NaN
6                            2015 Mar   1.577917      5.395   2.22125  3.475417  3.453333   1.419167   1.39625    0.95125    0.7225   0.99125  0.779167   0.31125   1.24375  2.234583   4.214167   7.739583  8.012917   1.65875  1.444583   0.702083  0.679583  0.796667   0.74875  0.737083   0.925833  0.304583    1.01875    0.74625   3.139167  3.199167  5.148333
7                            2015 Apr     7.6025  11.515833  6.219583  3.412083    2.3425   1.518333  1.535417   2.065417     2.365   2.20125      4.12  14.04875  17.34625  7.970833  10.446667   7.930417    7.3525    4.7725  9.232917  10.586667  9.966667  6.285833       4.2   6.63125  12.362083   13.5075  40.045417  16.607917  18.969583    14.215       NaN
8                            2015 May   8.663333   5.549583  5.957917   9.29875  7.118333   5.182917  9.537917  10.977917   7.43875  13.89625   14.0325  6.736667  5.151667    4.9025   4.342083    3.68875  6.418333  8.424167   9.70625   6.961667  5.085833  3.944583  3.677083  3.446667   2.503333     2.255   2.508333     1.7725    1.47375   2.06125  2.049167
9                            2015 Jun   6.423333   4.404167  1.799167      7.25  20.37875  16.152917  5.155833   3.644167    2.9625   2.58625  2.354583  2.790833  2.250417  1.820417   3.284167  10.954167  5.102917  4.137917  4.739583   3.584583  2.787917  2.626667  2.217917  2.100417     1.5425  1.968333      3.845   5.106667   8.139167      7.05       NaN
10                           2015 Jul    5.29375    4.95375  4.003333  3.168333  3.269583   2.652917  2.332917       2.19  1.527917  1.557083  2.930417   2.65875  1.779167  1.334583   1.354583   0.948333  1.500417  1.384167   1.16375   1.112917  1.259583    0.9925   1.34625     1.275     0.9675  1.695417    2.04375      1.335   0.919167  0.725833  0.825417
11                           2015 Aug   0.480417    0.40875   0.93875  3.353333  5.095833      2.015     0.965   1.095417  0.702917  0.887917   0.80375  1.302083  1.233333      0.98    0.44875   1.420833  2.688333      3.19  1.761667     0.5825    1.3175  1.215417  0.872083  0.890833   1.272083  1.516667   4.649167   7.218333    4.06375  1.914583   1.69875

======================================================================

In [55]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

discharge_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "flood"
    / "kelani"
    / "2015 - 2025 Discharge.xlsx"
)

output_file = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "flood"
    / "discharge_daily.parquet"
)

output_file.parent.mkdir(parents=True, exist_ok=True)

station_info = {
    "Norwood": {
        "station_id": "KN02",
        "station_name": "Norwood"
    },
    "Kithulgala": {
        "station_id": "KN07",
        "station_name": "Kitulgala"
    },
    "Deraniyagala": {
        "station_id": "KN16",
        "station_name": "Deraniyagala"
    },
    "Holombuwa": {
        "station_id": "KN11",
        "station_name": "Holombuwa"
    },
    "Glencourse": {
        "station_id": "KN18",
        "station_name": "Glencourse"
    },
    "Hanwella": {
        "station_id": "KN21",
        "station_name": "Hanwella"
    }
}

all_discharge = []

for sheet_name, info in station_info.items():

    df = pd.read_excel(
        discharge_file,
        sheet_name=sheet_name,
        header=3
    )

    df.columns = df.columns.astype(str).str.strip()

    # First column is YEARMONTH
    df = df.rename(columns={
        df.columns[0]: "year_month"
    })

    # Identify daily columns
    day_columns = [
        col for col in df.columns
        if str(col).upper().startswith("D")
        and str(col)[1:].isdigit()
    ]

    # Convert discharge values to numeric
    for col in day_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Convert wide format to long format
    long_df = df.melt(
        id_vars=["year_month"],
        value_vars=day_columns,
        var_name="day",
        value_name="discharge_m3s"
    )

    # Extract year and month
    long_df["year_month"] = long_df["year_month"].astype(str).str.strip()

    long_df["year"] = pd.to_numeric(
        long_df["year_month"].str.extract(r"^(\d{4})")[0],
        errors="coerce"
    )

    long_df["month_name"] = (
        long_df["year_month"]
        .str.extract(r"^\d{4}\s+([A-Za-z]+)")[0]
    )

    month_map = {
        "Jan": 1,
        "Feb": 2,
        "Mar": 3,
        "Apr": 4,
        "May": 5,
        "Jun": 6,
        "Jul": 7,
        "Aug": 8,
        "Sep": 9,
        "Oct": 10,
        "Nov": 11,
        "Dec": 12
    }

    long_df["month"] = long_df["month_name"].map(month_map)

    long_df["day_number"] = (
        long_df["day"]
        .str.extract(r"(\d+)")[0]
        .astype(float)
    )

    # Construct date
    long_df["date"] = pd.to_datetime(
        dict(
            year=long_df["year"],
            month=long_df["month"],
            day=long_df["day_number"]
        ),
        errors="coerce"
    )

    # Add station information
    long_df["station_id"] = info["station_id"]
    long_df["station_name"] = info["station_name"]

    # Keep required columns
    long_df = long_df[
        [
            "station_id",
            "station_name",
            "date",
            "discharge_m3s"
        ]
    ]

    # Remove invalid calendar dates
    long_df = long_df.dropna(subset=["date"])

    all_discharge.append(long_df)


discharge_daily = pd.concat(
    all_discharge,
    ignore_index=True
)

discharge_daily = discharge_daily.sort_values(
    ["station_id", "date"]
).reset_index(drop=True)


print("Final shape:", discharge_daily.shape)

print("\nStations:")
print(discharge_daily["station_id"].unique())

print("\nDate ranges:")
print(
    discharge_daily
    .groupby(["station_id", "station_name"])["date"]
    .agg(["min", "max", "count"])
)

print("\nMissing discharge values:")
print(
    discharge_daily["discharge_m3s"].isna().sum()
)

print("\nDischarge statistics:")
print(
    discharge_daily["discharge_m3s"].describe()
)

Final shape: (24108, 4)

Stations:
['KN02' 'KN07' 'KN11' 'KN16' 'KN18' 'KN21']

Date ranges:
                               min        max  count
station_id station_name
KN02       Norwood      2015-01-01 2025-12-31   4018
KN07       Kitulgala    2015-01-01 2025-12-31   4018
KN11       Holombuwa    2015-01-01 2025-12-31   4018
KN16       Deraniyagala 2015-01-01 2025-12-31   4018
KN18       Glencourse   2015-01-01 2025-12-31   4018
KN21       Hanwella     2015-01-01 2025-12-31   4018

Missing discharge values:
3

Discharge statistics:
count    24105.000000
mean        52.781480
std        104.356574
min          0.005500
25%          5.007089
50%         23.431859
75%         53.042654
max       3104.164253
Name: discharge_m3s, dtype: float64

In [56]:
discharge_daily.to_parquet(output_file, index=False)

print("Saved successfully:", output_file)
print("File exists:", output_file.exists())

Saved successfully: /Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/discharge_daily.parquet
File exists: True

In [57]:
disaster_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "disaster_records"
    / "DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx"
)

print("File exists:", disaster_file.exists())

excel_disaster = pd.ExcelFile(disaster_file)

print("\nSheets:")
print(excel_disaster.sheet_names)

File exists: True

Sheets:
['Ratnapura-Kegalle Floods', 'Notes']

In [58]:
for sheet_name in excel_disaster.sheet_names:
    
    print("\n" + "=" * 80)
    print("SHEET:", repr(sheet_name))
    print("=" * 80)

    df_preview = pd.read_excel(
        disaster_file,
        sheet_name=sheet_name,
        header=None,
        nrows=15
    )

    print(df_preview.to_string())

================================================================================
SHEET: 'Ratnapura-Kegalle Floods'
================================================================================
        0      1             2          3                 4           5         6       7        8        9                 10              11                 12                   13         14         15           16
0   Serial  Event      Province   District          Division        Date  Location  Deaths  Injured  Missing  Houses Destroyed  Houses Damaged  Directly affected  Indirectly Affected  Relocated  Evacuated  Losses $USD
1   143803  FLOOD  Sabaragamuwa  Ratnapura        Pelmadulla  2019/12/05       NaN     NaN      NaN      NaN               NaN             NaN                NaN                   40        NaN        NaN            0
2   143303  FLOOD  Sabaragamuwa    Kegalle         Dehiovita  2019/10/21       NaN     NaN      NaN      NaN               NaN             NaN                NaN                   48        NaN        NaN            0
3   143183  FLOOD  Sabaragamuwa    Kegalle         Aranayaka  2019/10/15       NaN     NaN      NaN      NaN               NaN               1                NaN                    4        NaN        NaN            0
4   142912  FLOOD  Sabaragamuwa    Kegalle  Bulathkohupitiya  2019/08/31       NaN     NaN      NaN      NaN                 4             NaN                NaN                   26        NaN        NaN            0
5   142894  FLOOD  Sabaragamuwa  Ratnapura         Ratnapura  2019/08/30       NaN     NaN      NaN      NaN                 1             NaN                NaN                  114        NaN        NaN            0
6   142787  FLOOD  Sabaragamuwa  Ratnapura          Kiriella  2019/08/13       NaN     NaN      NaN      NaN               NaN             NaN                NaN                  312        NaN        NaN            0
7   142784  FLOOD  Sabaragamuwa  Ratnapura          Elapatha  2019/08/13       NaN     NaN      NaN      NaN               NaN             NaN                NaN                  381        NaN        NaN            0
8   142777  FLOOD  Sabaragamuwa  Ratnapura         Ratnapura  2019/08/13       NaN     NaN      NaN      NaN               NaN              13                NaN                 1788        NaN        NaN            0
9   142444  FLOOD  Sabaragamuwa  Ratnapura         Ratnapura  2019/07/18       NaN     NaN      NaN      NaN               NaN              13                NaN                  724        NaN        NaN            0
10  142435  FLOOD  Sabaragamuwa  Ratnapura        Pelmadulla  2019/07/18       NaN     NaN      NaN      NaN               NaN              25                NaN                  115        NaN        NaN            0
11  140466  FLOOD  Sabaragamuwa  Ratnapura           Ayagama  2018/05/21       NaN     NaN      NaN      NaN                 1              16                NaN                  515        NaN        NaN            0
12  140463  FLOOD  Sabaragamuwa  Ratnapura        Pelmadulla  2018/05/21       NaN     NaN      NaN      NaN                 2              29                NaN                 1016        NaN        NaN            0
13  140460  FLOOD  Sabaragamuwa  Ratnapura          Kiriella  2018/05/20       NaN     NaN        1        1               NaN             NaN                NaN                 5850        NaN        NaN            0
14  140453  FLOOD  Sabaragamuwa  Ratnapura          Kalawana  2018/05/21       NaN     NaN      NaN      NaN               NaN               8                NaN                  216        NaN        NaN            0

================================================================================
SHEET: 'Notes'
================================================================================
                                                                                                                                                                                                                                                           0
0                                                                                                                                                                                                                                                      Notes
1                                                                                                                                                                                                                                                        NaN
2                                                                                                                                                         Source: DesInventar Sri Lanka query results, disaster type FLOOD, districts Ratnapura and Kegalle.
3                                                                   Result set has 977 hits across 10 pages. Only pages 1 and 2 are captured here (from the screenshots provided) -- approximately 183 of 977 rows. Pages 3-10 (~794 rows) are NOT included.
4                                                                                                                 Columns to the right of 'Losses $USD' (e.g. 'Losses $Local', 'Education' and beyond) were cut off in the screenshots and are NOT included.
5                                                                                                                     Rows are in the same order as on the website. Blank cells on the website are blank here. No values were edited, rounded, or filled in.
6                                                                                                                                                                               Serial numbers and dates are stored as text so Excel does not reformat them.
7  Values were read from screenshot images (not an export), so please spot-check rows against the live website before final use -- in particular the row for Ratnapura, 2017/05/26, 'Batugedara, Damme Ela' (long numbers are the easiest to mistranscribe).
8                                                                     To get the remaining 8 pages, either screenshot pages 3-10 the same way, or use the site's Download page (desinventar.net/DesInventar/download.jsp) for the full database in one file.

In [60]:
flood_impact = pd.read_excel(
    disaster_file,
    sheet_name="Ratnapura-Kegalle Floods"
)

flood_impact.columns = flood_impact.columns.astype(str).str.strip()

print("Shape:", flood_impact.shape)

print("\nColumns:")
for i, col in enumerate(flood_impact.columns):
    print(i, repr(col))

print("\nDate range:")
print(
    pd.to_datetime(
        flood_impact["Date"],
        errors="coerce"
    ).agg(["min", "max"])
)

print("\nDistrict counts:")
print(
    flood_impact["District"].value_counts(dropna=False)
)

print("\nDS Division count:")
print(
    flood_impact["Division"].nunique()
)

print("\nRecords per DS Division:")
print(
    flood_impact["Division"].value_counts()
)

Shape: (200, 17)

Columns:
0 'Serial'
1 'Event'
2 'Province'
3 'District'
4 'Division'
5 'Date'
6 'Location'
7 'Deaths'
8 'Injured'
9 'Missing'
10 'Houses Destroyed'
11 'Houses Damaged'
12 'Directly affected'
13 'Indirectly Affected'
14 'Relocated'
15 'Evacuated'
16 'Losses $USD'

Date range:
min   2003-05-17
max   2019-12-05
Name: Date, dtype: datetime64[ns]

District counts:
District
Ratnapura    138
Kegalle       62
Name: count, dtype: int64

DS Division count:
28

Records per DS Division:
Division
Pelmadulla          27
Ratnapura           20
Elapatha            17
Kiriella            16
Kuruvita            13
Mawanella           11
Ayagama              9
Kegalle              8
Eheliyagoda          7
Rambukkana           7
Dehiovita            6
Kahawatta            6
Yatiyanthota         6
Galigamuwa           5
Ruwanwella           5
Nivithigala          5
Bulathkohupitiya     5
Kalawana             4
Aranayaka            4
Embilipitiya         4
Warakapola           3
Balangoda            3
Deraniyagala         2
Opanayaka            2
Godakawela           2
Kolonna              1
Weligepola           1
Imbulpe              1
Name: count, dtype: int64

In [61]:
impact_columns = [
    "Deaths",
    "Injured",
    "Missing",
    "Houses Destroyed",
    "Houses Damaged",
    "Directly affected",
    "Indirectly Affected",
    "Relocated",
    "Evacuated",
    "Losses $USD"
]

coverage = pd.DataFrame({
    "non_missing": flood_impact[impact_columns].notna().sum(),
    "missing": flood_impact[impact_columns].isna().sum(),
    "coverage_percent": (
        flood_impact[impact_columns].notna().mean() * 100
    ).round(2)
})

print(coverage)

                     non_missing  missing  coverage_percent
Deaths                         7      193               3.5
Injured                       19      181               9.5
Missing                        3      197               1.5
Houses Destroyed              54      146              27.0
Houses Damaged               116       84              58.0
Directly affected              0      200               0.0
Indirectly Affected          193        7              96.5
Relocated                      0      200               0.0
Evacuated                      0      200               0.0
Losses $USD                  200        0             100.0

In [62]:
print("\nImpact statistics:")
print(
    flood_impact[impact_columns]
    .describe()
    .T
)

Impact statistics:
                     count        mean          std  min    25%   50%     75%  \
Deaths                 7.0    1.428571     0.534522  1.0   1.00   1.0    2.00
Injured               19.0    2.210526     2.615742  1.0   1.00   1.0    2.50
Missing                3.0    1.333333     0.577350  1.0   1.00   1.0    1.50
Houses Destroyed      54.0    8.833333    16.873279  1.0   1.25   3.5   10.00
Houses Damaged       116.0   26.474138    73.429228  1.0   2.00   6.0   22.75
Directly affected      0.0         NaN          NaN  NaN    NaN   NaN     NaN
Indirectly Affected  193.0  705.735751  2423.625033  1.0  14.00  50.0  389.00
Relocated              0.0         NaN          NaN  NaN    NaN   NaN     NaN
Evacuated              0.0         NaN          NaN  NaN    NaN   NaN     NaN
Losses $USD          200.0    0.000000     0.000000  0.0   0.00   0.0    0.00

                         max
Deaths                   2.0
Injured                 12.0
Missing                  2.0
Houses Destroyed        81.0
Houses Damaged         619.0
Directly affected        NaN
Indirectly Affected  25363.0
Relocated                NaN
Evacuated                NaN
Losses $USD              0.0

In [63]:
print("\nRows with at least one human-impact value:")

has_impact = flood_impact[impact_columns].notna().any(axis=1)

print(has_impact.value_counts())

print(
    "\nRows with no recorded impact values:",
    (~has_impact).sum()
)

Rows with at least one human-impact value:
True    200
Name: count, dtype: int64

Rows with no recorded impact values: 0

In [64]:
flood_impact["Date"] = pd.to_datetime(
    flood_impact["Date"],
    errors="coerce"
)

overlap = flood_impact[
    flood_impact["Date"].dt.year.between(2015, 2019)
].copy()

print("2015–2019 records:", len(overlap))

print("\nRecords by year:")
print(
    overlap["Date"]
    .dt.year
    .value_counts()
    .sort_index()
)

print("\nRecords by district:")
print(
    overlap["District"]
    .value_counts()
)

print("\nRecords by DS Division:")
print(
    overlap["Division"]
    .value_counts()
)

2015–2019 records: 84

Records by year:
Date
2015    23
2016    16
2017    17
2018    18
2019    10
Name: count, dtype: int64

Records by district:
District
Ratnapura    42
Kegalle      42
Name: count, dtype: int64

Records by DS Division:
Division
Mawanella           10
Kegalle              7
Ratnapura            6
Elapatha             6
Pelmadulla           5
Rambukkana           5
Bulathkohupitiya     4
Dehiovita            4
Ruwanwella           3
Eheliyagoda          3
Ayagama              3
Kiriella             3
Aranayaka            3
Kuruvita             2
Nivithigala          2
Kalawana             2
Galigamuwa           2
Yatiyanthota         2
Kahawatta            2
Embilipitiya         2
Opanayaka            2
Balangoda            1
Weligepola           1
Deraniyagala         1
Kolonna              1
Warakapola           1
Godakawela           1
Name: count, dtype: int64

In [65]:
print("2015–2019 Indirectly Affected statistics:")
print(
    overlap["Indirectly Affected"].describe()
)

print(
    "\nMissing Indirectly Affected:",
    overlap["Indirectly Affected"].isna().sum()
)

print(
    "\nZero Indirectly Affected:",
    (overlap["Indirectly Affected"] == 0).sum()
)

2015–2019 Indirectly Affected statistics:
count       84.000000
mean       906.154762
std       3121.110300
min          1.000000
25%         10.750000
50%         42.000000
75%        456.500000
max      25363.000000
Name: Indirectly Affected, dtype: float64

Missing Indirectly Affected: 0

Zero Indirectly Affected: 0

In [66]:
print("\nSorted 2015–2019 impact values:")

print(
    overlap[
        [
            "Date",
            "District",
            "Division",
            "Indirectly Affected",
            "Houses Destroyed",
            "Houses Damaged",
            "Deaths",
            "Injured"
        ]
    ]
    .sort_values("Indirectly Affected", ascending=False)
    .to_string(index=False)
)

Sorted 2015–2019 impact values:
      Date  District         Division  Indirectly Affected  Houses Destroyed  Houses Damaged  Deaths  Injured
2017-05-26 Ratnapura        Ratnapura              25363.0              11.0           619.0     2.0     12.0
2018-05-20 Ratnapura         Elapatha               8624.0               5.0             NaN     NaN      NaN
2018-05-20 Ratnapura        Ratnapura               7348.0               NaN            85.0     NaN      NaN
2018-05-20 Ratnapura         Kuruvita               6100.0               NaN            48.0     NaN      NaN
2018-05-20 Ratnapura         Kiriella               5850.0               NaN             NaN     NaN      1.0
2016-05-16 Ratnapura         Kiriella               3875.0               NaN             NaN     1.0      NaN
2018-05-20   Kegalle        Dehiovita               2140.0               NaN           457.0     NaN      NaN
2019-08-13 Ratnapura        Ratnapura               1788.0               NaN            13.0     NaN      NaN
2017-05-24 Ratnapura        Kahawatta               1750.0              13.0           143.0     1.0      1.0
2016-05-16 Ratnapura     Embilipitiya               1112.0               NaN            29.0     NaN      1.0
2016-05-15 Ratnapura          Ayagama               1097.0               1.0            16.0     NaN      NaN
2018-05-21 Ratnapura       Pelmadulla               1016.0               2.0            29.0     NaN      NaN
2017-09-07 Ratnapura          Ayagama                879.0               NaN             2.0     NaN      NaN
2018-05-20   Kegalle       Ruwanwella                832.0               NaN            15.0     NaN      1.0
2019-07-18 Ratnapura        Ratnapura                724.0               NaN            13.0     NaN      NaN
2016-05-16 Ratnapura         Elapatha                704.0               4.0            13.0     NaN      NaN
2016-05-16 Ratnapura       Godakawela                629.0               1.0            19.0     NaN      NaN
2017-05-24 Ratnapura        Opanayaka                624.0               NaN            43.0     NaN      1.0
2018-05-20 Ratnapura      Nivithigala                574.0               NaN            17.0     NaN      NaN
2017-09-07 Ratnapura         Elapatha                555.0               NaN             1.0     NaN      NaN
2018-05-21 Ratnapura          Ayagama                515.0               1.0            16.0     NaN      NaN
2017-05-24 Ratnapura          Kolonna                437.0               6.0            26.0     NaN      2.0
2019-08-13 Ratnapura         Elapatha                381.0               NaN             NaN     NaN      NaN
2018-05-20   Kegalle     Deraniyagala                372.0               NaN           102.0     NaN      NaN
2019-08-13 Ratnapura         Kiriella                312.0               NaN             NaN     NaN      NaN
2016-05-16 Ratnapura      Nivithigala                304.0               1.0             6.0     NaN      NaN
2017-10-14 Ratnapura      Eheliyagoda                280.0               NaN            10.0     NaN      NaN
2018-05-21 Ratnapura         Kalawana                216.0               NaN             8.0     NaN      NaN
2017-04-13 Ratnapura       Pelmadulla                198.0               NaN             NaN     NaN      NaN
2017-05-24 Ratnapura        Ratnapura                128.0               NaN             1.0     NaN      NaN
2019-07-18 Ratnapura       Pelmadulla                115.0               NaN            25.0     NaN      NaN
2019-08-30 Ratnapura        Ratnapura                114.0               1.0             NaN     NaN      NaN
2017-04-05 Ratnapura         Kuruvita                 94.0               NaN            21.0     NaN      NaN
2017-10-15 Ratnapura         Elapatha                 85.0               NaN             1.0     NaN      NaN
2016-05-15 Ratnapura        Kahawatta                 72.0               4.0            12.0     NaN      NaN
2016-05-16 Ratnapura        Opanayaka                 67.0               2.0             2.0     NaN      3.0
2015-11-05   Kegalle          Kegalle                 67.0               NaN             2.0     NaN      NaN
2016-05-15 Ratnapura       Weligepola                 54.0               8.0             6.0     NaN      NaN
2016-05-16 Ratnapura         Kalawana                 52.0               2.0            13.0     NaN      NaN
2019-10-21   Kegalle        Dehiovita                 48.0               NaN             NaN     NaN      NaN
2016-05-09 Ratnapura     Embilipitiya                 45.0              11.0             NaN     NaN      NaN
2017-05-24 Ratnapura       Pelmadulla                 44.0               NaN             NaN     NaN      NaN
2019-12-05 Ratnapura       Pelmadulla                 40.0               NaN             NaN     NaN      NaN
2018-05-20   Kegalle       Warakapola                 37.0               NaN             9.0     NaN      NaN
2018-05-20   Kegalle       Galigamuwa                 28.0               NaN             5.0     NaN      NaN
2017-05-24 Ratnapura        Balangoda                 27.0               NaN             3.0     NaN      NaN
2018-05-20 Ratnapura      Eheliyagoda                 27.0               NaN             NaN     NaN      NaN
2019-08-31   Kegalle Bulathkohupitiya                 26.0               4.0             NaN     NaN      NaN
2018-02-26   Kegalle     Yatiyanthota                 25.0               NaN             NaN     NaN      NaN
2016-05-09   Kegalle        Dehiovita                 25.0               NaN             6.0     NaN      NaN
2018-05-22   Kegalle       Galigamuwa                 22.0               NaN             NaN     NaN      NaN
2018-05-20   Kegalle       Rambukkana                 22.0               NaN             1.0     NaN      NaN
2015-11-12   Kegalle       Rambukkana                 16.0               NaN             NaN     NaN      NaN
2015-11-12   Kegalle Bulathkohupitiya                 16.0               NaN             3.0     NaN      NaN
2015-11-12   Kegalle Bulathkohupitiya                 15.0               NaN             4.0     NaN      NaN
2015-11-05   Kegalle Bulathkohupitiya                 14.0               NaN             NaN     NaN      NaN
2015-11-07   Kegalle        Mawanella                 14.0               NaN             3.0     NaN      NaN
2015-11-05   Kegalle        Mawanella                 14.0               NaN             3.0     NaN      NaN
2018-05-20   Kegalle          Kegalle                 13.0               NaN             2.0     NaN      NaN
2016-04-19 Ratnapura      Eheliyagoda                 13.0               2.0             2.0     NaN      NaN
2015-04-01   Kegalle        Aranayaka                 12.0               NaN             3.0     NaN      NaN
2015-12-13   Kegalle       Rambukkana                 11.0               NaN             1.0     NaN      NaN
2015-12-13   Kegalle       Rambukkana                 11.0               NaN             1.0     NaN      NaN
2017-10-29   Kegalle        Mawanella                 10.0               NaN             NaN     NaN      NaN
2017-05-24 Ratnapura         Elapatha                 10.0               NaN             NaN     NaN      NaN
2015-12-12   Kegalle          Kegalle                  9.0               NaN             1.0     NaN      NaN
2015-12-14   Kegalle        Dehiovita                  9.0               NaN             1.0     NaN      NaN
2015-10-13   Kegalle          Kegalle                  8.0               NaN             2.0     NaN      NaN
2015-10-18   Kegalle     Yatiyanthota                  8.0               NaN             2.0     NaN      NaN
2015-11-02   Kegalle        Aranayaka                  7.0               1.0             1.0     NaN      NaN
2015-10-22   Kegalle          Kegalle                  5.0               NaN             1.0     NaN      NaN
2016-03-10   Kegalle        Mawanella                  5.0               NaN             1.0     NaN      NaN
2017-04-04   Kegalle          Kegalle                  4.0               NaN             NaN     NaN      NaN
2017-06-27   Kegalle        Mawanella                  4.0               NaN             NaN     NaN      NaN
2016-05-11   Kegalle       Ruwanwella                  4.0               NaN             1.0     NaN      NaN
2019-10-15   Kegalle        Aranayaka                  4.0               NaN             1.0     NaN      NaN
2015-10-14   Kegalle          Kegalle                  4.0               NaN             1.0     NaN      NaN
2015-12-10   Kegalle        Mawanella                  3.0               NaN             1.0     NaN      NaN
2015-10-25   Kegalle       Ruwanwella                  3.0               NaN             1.0     NaN      NaN
2016-05-09   Kegalle       Rambukkana                  3.0               NaN             1.0     NaN      NaN
2015-10-31   Kegalle        Mawanella                  2.0               1.0             NaN     NaN      NaN
2015-05-07   Kegalle        Mawanella                  1.0               NaN             NaN     NaN      NaN
2015-04-19   Kegalle        Mawanella                  1.0               1.0             NaN     NaN      NaN
2015-12-20   Kegalle        Mawanella                  1.0               NaN             NaN     NaN      NaN

In [67]:
census_population_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "census"
    / "GN_population_excel.xlsx"
)

print("File exists:", census_population_file.exists())

excel_population = pd.ExcelFile(census_population_file)

print("\nSheets:")
print(excel_population.sheet_names)

File exists: True

Sheets:
['Population']

In [68]:
for sheet_name in excel_population.sheet_names:
    
    print("\n" + "=" * 80)
    print("SHEET:", repr(sheet_name))
    print("=" * 80)

    df_preview = pd.read_excel(
        census_population_file,
        sheet_name=sheet_name,
        header=None,
        nrows=15
    )

    print(df_preview.to_string())

================================================================================
SHEET: 'Population'
================================================================================
                                                                                                                       0               1               2               3                  4                  5                  6                  7                    8      9      10      11         12      13       14       15             16
0                                                                                                                     NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN    NaN    NaN     NaN        NaN     NaN      NaN      NaN            NaN
1   Census of Population and Housing - 2024\nGrama Niladhari Division Level Population by Sex and Age Group (Provisional)             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN    NaN    NaN     NaN        NaN     NaN      NaN      NaN            NaN
2                                                                                                                     NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN    NaN    NaN     NaN        NaN     NaN      NaN      NaN            NaN
3                                                                                                          Province\nCode  Province\nName  District\nCode  District\nName  DS_Division\nCode  DS_Division\nName  GN_Division\nCode  GN_Division\nName  GN_Division\nNumber    Sex    NaN     NaN  Age_Group     NaN      NaN      NaN            NaN
4                                                                                                                     NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN  Total   Male  Female      Total  0 - 14  15 - 59  60 - 64   65 and above
5                                                                                                                       1         Western              11         Colombo                  3            Colombo                  5   Sammanthranapura                        7640   3864    3776       7640    1695     4891      393            661
6                                                                                                                       1         Western              11         Colombo                  3            Colombo                 10       Mattakkuliya                       28135  13749   14386      28135    5653    18163     1499           2820
7                                                                                                                       1         Western              11         Colombo                  3            Colombo                 15             Modara                       31728  15579   16149      31728    6930    20400     1554           2844
8                                                                                                                       1         Western              11         Colombo                  3            Colombo                 20        Madampitiya                        7699   3890    3809       7699    1831     5024      353            491
9                                                                                                                       1         Western              11         Colombo                  3            Colombo                 25          Mahawatta                        7108   3611    3497       7108    1504     4582      354            668
10                                                                                                                      1         Western              11         Colombo                  3            Colombo                 30       Aluthmawatha                       13714   6796    6918      13714    2649     8785      754           1526
11                                                                                                                      1         Western              11         Colombo                  3            Colombo                 35         Lunupokuna                       11925   5784    6141      11925    2273     7602      672           1378
12                                                                                                                      1         Western              11         Colombo                  3            Colombo                 40        Bloemendhal                        7771   3678    4093       7771    1426     5018      452            875
13                                                                                                                      1         Western              11         Colombo                  3            Colombo                 45      Kotahena East                        6090   2775    3315       6090    1008     3723      388            971
14                                                                                                                      1         Western              11         Colombo                  3            Colombo                 50      Kotahena West                        9186   4371    4815       9186    1723     5735      558           1170

In [69]:
import pandas as pd

population_raw = pd.read_excel(
    census_population_file,
    sheet_name="Population",
    header=None
)

print("Shape:", population_raw.shape)
print("\nFirst 8 rows:")
display(population_raw.head(8))

Shape: (14013, 17)

First 8 rows:

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Census of Population and Housing - 2024\nGrama...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Province\nCode,Province\nName,District\nCode,District\nName,DS_Division\nCode,DS_Division\nName,GN_Division\nCode,GN_Division\nName,GN_Division\nNumber,Sex,NaN,NaN,Age_Group,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Male,Female,Total,0 - 14,15 - 59,60 - 64,65 and above
5,1,Western,11,Colombo,3,Colombo,5,Sammanthranapura,,7640,3864,3776,7640,1695,4891,393,661
6,1,Western,11,Colombo,3,Colombo,10,Mattakkuliya,,28135,13749,14386,28135,5653,18163,1499,2820
7,1,Western,11,Colombo,3,Colombo,15,Modara,,31728,15579,16149,31728,6930,20400,1554,2844

In [70]:
population = population_raw.iloc[5:].copy()

population.columns = [
    "province_code",
    "province_name",
    "district_code",
    "district_name",
    "ds_code",
    "ds_name",
    "gn_code",
    "gn_name",
    "gn_number",
    "total_population",
    "male",
    "female",
    "age_total",
    "age_0_14",
    "age_15_59",
    "age_60_64",
    "age_65_plus"
]

population = population.reset_index(drop=True)

print("Shape:", population.shape)
display(population.head())

Shape: (14008, 17)

,province_code,province_name,district_code,district_name,ds_code,ds_name,gn_code,gn_name,gn_number,total_population,male,female,age_total,age_0_14,age_15_59,age_60_64,age_65_plus
0,1,Western,11,Colombo,3,Colombo,5,Sammanthranapura,,7640,3864,3776,7640,1695,4891,393,661
1,1,Western,11,Colombo,3,Colombo,10,Mattakkuliya,,28135,13749,14386,28135,5653,18163,1499,2820
2,1,Western,11,Colombo,3,Colombo,15,Modara,,31728,15579,16149,31728,6930,20400,1554,2844
3,1,Western,11,Colombo,3,Colombo,20,Madampitiya,,7699,3890,3809,7699,1831,5024,353,491
4,1,Western,11,Colombo,3,Colombo,25,Mahawatta,,7108,3611,3497,7108,1504,4582,354,668

In [71]:
print("Data types:")
print(population.dtypes)

print("\nMissing values:")
print(population.isna().sum())

Data types:
province_code       object
province_name       object
district_code       object
district_name       object
ds_code             object
ds_name             object
gn_code             object
gn_name             object
gn_number           object
total_population    object
male                object
female              object
age_total           object
age_0_14            object
age_15_59           object
age_60_64           object
age_65_plus         object
dtype: object

Missing values:
province_code       0
province_name       0
district_code       0
district_name       0
ds_code             0
ds_name             0
gn_code             0
gn_name             0
gn_number           0
total_population    0
male                0
female              0
age_total           0
age_0_14            0
age_15_59           0
age_60_64           0
age_65_plus         0
dtype: int64

In [72]:
population["age_sum"] = (
    pd.to_numeric(population["age_0_14"], errors="coerce")
    + pd.to_numeric(population["age_15_59"], errors="coerce")
    + pd.to_numeric(population["age_60_64"], errors="coerce")
    + pd.to_numeric(population["age_65_plus"], errors="coerce")
)

population["age_difference"] = (
    pd.to_numeric(population["total_population"], errors="coerce")
    - population["age_sum"]
)

print("Records where age total does not equal population:")
print((population["age_difference"] != 0).sum())

print("\nAge difference distribution:")
print(population["age_difference"].value_counts().head(10))

Records where age total does not equal population:
0

Age difference distribution:
age_difference
0    14008
Name: count, dtype: int64

In [73]:
population["sex_sum"] = (
    pd.to_numeric(population["male"], errors="coerce")
    + pd.to_numeric(population["female"], errors="coerce")
)

population["sex_difference"] = (
    pd.to_numeric(population["total_population"], errors="coerce")
    - population["sex_sum"]
)

print("Records where male + female != total:")
print((population["sex_difference"] != 0).sum())

Records where male + female != total:
0

In [74]:
flood_population = population[
    population["district_name"].isin(["Ratnapura", "Kegalle"])
].copy()

print("Flood study-area GN records:", len(flood_population))

print("\nDistrict counts:")
print(flood_population["district_name"].value_counts())

print("\nDS divisions:")
print(
    flood_population[
        ["district_name", "ds_code", "ds_name"]
    ].drop_duplicates()
    .sort_values(["district_name", "ds_name"])
    .to_string(index=False)
)

Flood study-area GN records: 1148

District counts:
district_name
Ratnapura    575
Kegalle      573
Name: count, dtype: int64

DS divisions:
district_name ds_code          ds_name
      Kegalle       9        Aranayaka
      Kegalle      24 Bulathkohupitiya
      Kegalle      30        Dehiovita
      Kegalle      33     Deraniyagala
      Kegalle      15       Galigamuwa
      Kegalle      12          Kegalle
      Kegalle       6        Mawanella
      Kegalle       3       Rambukkana
      Kegalle      21       Ruwanwella
      Kegalle      18       Warakapola
      Kegalle      27     Yatiyanthota
    Ratnapura      30          Ayagama
    Ratnapura      18        Balangoda
    Ratnapura       3      Eheliyagoda
    Ratnapura      27         Elapatha
    Ratnapura      48     Embilipitiya
    Ratnapura      42       Godakawela
    Ratnapura      15          Imbulpe
    Ratnapura      39        Kahawatta
    Ratnapura      33         Kalawana
    Ratnapura      19          Kaltota
    Ratnapura       9         Kiriella
    Ratnapura      51          Kolonna
    Ratnapura       6         Kuruvita
    Ratnapura      36      Nivithigala
    Ratnapura      21        Opanayake
    Ratnapura      24       Pelmadulla
    Ratnapura      12        Ratnapura
    Ratnapura      45       Weligepola

In [75]:
landslide_population = population[
    (population["district_name"] == "Nuwara Eliya") &
    (population["ds_name"].isin([
        "Ambagamuwa",
        "Kothmale",
        "Nuwara Eliya",
        "Walapane"
    ]))
].copy()

print("Landslide study-area GN records:", len(landslide_population))

print("\nDS counts:")
print(
    landslide_population["ds_name"]
    .value_counts()
    .sort_index()
)

Landslide study-area GN records: 100

DS counts:
ds_name
Nuwara Eliya    38
Walapane        62
Name: count, dtype: int64

In [76]:
# Show every DS division available in Nuwara Eliya
nuwara_ds = (
    population[
        population["district_name"].str.strip().str.lower() == "nuwara eliya"
    ][["ds_code", "ds_name"]]
    .drop_duplicates()
    .sort_values("ds_name")
)

print(nuwara_ds.to_string(index=False))

ds_code             ds_name
     15 Ambagamuwa Koralaya
      6       Hanguranketha
      3       Kothmale East
      2       Kothmale West
      7           Mathurata
     10       Nildandahinna
     14             Norwood
     12        Nuwara Eliya
     13        Thalawakelle
      9            Walapane

In [77]:
nuwara_names = population[
    population["district_name"].str.strip().str.lower() == "nuwara eliya"
]["ds_name"].drop_duplicates()

print("Names containing Amb:")
print(nuwara_names[nuwara_names.str.contains("amb", case=False, na=False)].to_list())

print("\nNames containing Koth:")
print(nuwara_names[nuwara_names.str.contains("koth", case=False, na=False)].to_list())

Names containing Amb:
['Ambagamuwa Koralaya']

Names containing Koth:
['Kothmale West', 'Kothmale East']

In [78]:
landslide_population = population[
    (population["district_name"].str.strip().str.lower() == "nuwara eliya") &
    (
        population["ds_name"].isin([
            "Ambagamuwa Koralaya",
            "Kothmale East",
            "Kothmale West",
            "Nuwara Eliya",
            "Walapane"
        ])
    )
].copy()

print("Landslide study-area GN records:", len(landslide_population))

print("\nCensus DS coverage:")
print(
    landslide_population["ds_name"]
    .value_counts()
    .sort_index()
)

Landslide study-area GN records: 228

Census DS coverage:
ds_name
Ambagamuwa Koralaya    32
Kothmale East          47
Kothmale West          49
Nuwara Eliya           38
Walapane               62
Name: count, dtype: int64

In [79]:
from pathlib import Path
import pandas as pd

# ---------------------------------------------------------
# 1. Work on a copy
# ---------------------------------------------------------
population_clean = population.copy()

# ---------------------------------------------------------
# 2. Convert numeric columns
# ---------------------------------------------------------
numeric_columns = [
    "province_code",
    "district_code",
    "ds_code",
    "gn_code",
    "total_population",
    "male",
    "female",
    "age_total",
    "age_0_14",
    "age_15_59",
    "age_60_64",
    "age_65_plus"
]

for col in numeric_columns:
    population_clean[col] = pd.to_numeric(
        population_clean[col],
        errors="coerce"
    )

# ---------------------------------------------------------
# 3. Create elderly population (60+)
# ---------------------------------------------------------
population_clean["elderly_60_plus"] = (
    population_clean["age_60_64"]
    + population_clean["age_65_plus"]
)

# ---------------------------------------------------------
# 4. Create population ratios
# ---------------------------------------------------------
population_clean["children_ratio"] = (
    population_clean["age_0_14"]
    / population_clean["total_population"]
)

population_clean["elderly_ratio"] = (
    population_clean["elderly_60_plus"]
    / population_clean["total_population"]
)

population_clean["female_ratio"] = (
    population_clean["female"]
    / population_clean["total_population"]
)

# ---------------------------------------------------------
# 5. Final validation
# ---------------------------------------------------------
print("Shape:", population_clean.shape)

print("\nMissing values:")
print(population_clean.isna().sum())

print("\nDuplicate GN codes:")
print(population_clean["gn_code"].duplicated().sum())

# Age consistency
age_check = (
    population_clean["age_0_14"]
    + population_clean["age_15_59"]
    + population_clean["age_60_64"]
    + population_clean["age_65_plus"]
)

print("\nAge consistency errors:")
print((age_check != population_clean["total_population"]).sum())

# Sex consistency
sex_check = (
    population_clean["male"]
    + population_clean["female"]
)

print("\nSex consistency errors:")
print((sex_check != population_clean["total_population"]).sum())

# ---------------------------------------------------------
# 6. Display final structure
# ---------------------------------------------------------
print("\nFinal columns:")
print(population_clean.columns.tolist())

display(population_clean.head())

# ---------------------------------------------------------
# 7. Save cleaned Census population dataset
# ---------------------------------------------------------
output_dir = PROJECT_ROOT / "data" / "interim" / "census"
output_dir.mkdir(parents=True, exist_ok=True)

output_file = output_dir / "population_gn_clean.parquet"

population_clean.to_parquet(
    output_file,
    index=False
)

print("\nSaved successfully:", output_file)
print("File exists:", output_file.exists())

Shape: (14008, 25)

Missing values:
province_code       0
province_name       0
district_code       0
district_name       0
ds_code             0
ds_name             0
gn_code             0
gn_name             0
gn_number           0
total_population    0
male                0
female              0
age_total           0
age_0_14            0
age_15_59           0
age_60_64           0
age_65_plus         0
age_sum             0
age_difference      0
sex_sum             0
sex_difference      0
elderly_60_plus     0
children_ratio      5
elderly_ratio       5
female_ratio        5
dtype: int64

Duplicate GN codes:
13854

Age consistency errors:
0

Sex consistency errors:
0

Final columns:
['province_code', 'province_name', 'district_code', 'district_name', 'ds_code', 'ds_name', 'gn_code', 'gn_name', 'gn_number', 'total_population', 'male', 'female', 'age_total', 'age_0_14', 'age_15_59', 'age_60_64', 'age_65_plus', 'age_sum', 'age_difference', 'sex_sum', 'sex_difference', 'elderly_60_plus', 'children_ratio', 'elderly_ratio', 'female_ratio']

,province_code,province_name,district_code,district_name,ds_code,ds_name,gn_code,gn_name,gn_number,total_population,...,age_60_64,age_65_plus,age_sum,age_difference,sex_sum,sex_difference,elderly_60_plus,children_ratio,elderly_ratio,female_ratio
0,1,Western,11,Colombo,3,Colombo,5,Sammanthranapura,,7640,...,393,661,7640,0,7640,0,1054,0.221859,0.137958,0.494241
1,1,Western,11,Colombo,3,Colombo,10,Mattakkuliya,,28135,...,1499,2820,28135,0,28135,0,4319,0.200924,0.153510,0.511320
2,1,Western,11,Colombo,3,Colombo,15,Modara,,31728,...,1554,2844,31728,0,31728,0,4398,0.218419,0.138616,0.508983
3,1,Western,11,Colombo,3,Colombo,20,Madampitiya,,7699,...,353,491,7699,0,7699,0,844,0.237823,0.109625,0.494740
4,1,Western,11,Colombo,3,Colombo,25,Mahawatta,,7108,...,354,668,7108,0,7108,0,1022,0.211593,0.143782,0.491981

ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column gn_number with type object')

In [80]:
# ---------------------------------------------------------
# Fix mixed-type GN number issue
# ---------------------------------------------------------

# Remove GN Number because GN Code is the proper identifier
population_clean = population_clean.drop(columns=["gn_number"])

# Convert all identifier columns to consistent numeric types
numeric_columns = [
    "province_code",
    "district_code",
    "ds_code",
    "gn_code",
    "total_population",
    "male",
    "female",
    "age_total",
    "age_0_14",
    "age_15_59",
    "age_60_64",
    "age_65_plus",
    "elderly_60_plus",
    "children_ratio",
    "elderly_ratio",
    "female_ratio"
]

for col in numeric_columns:
    population_clean[col] = pd.to_numeric(
        population_clean[col],
        errors="coerce"
    )

# Convert text columns consistently
text_columns = [
    "province_name",
    "district_name",
    "ds_name",
    "gn_code"
]

for col in text_columns:
    if col in population_clean.columns:
        population_clean[col] = population_clean[col].astype("string")

# ---------------------------------------------------------
# Check
# ---------------------------------------------------------
print("Final shape:", population_clean.shape)

print("\nColumns:")
print(population_clean.columns.tolist())

print("\nMissing values:")
print(population_clean.isna().sum())

print("\nData types:")
print(population_clean.dtypes)

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------
output_dir = PROJECT_ROOT / "data" / "interim" / "census"
output_dir.mkdir(parents=True, exist_ok=True)

output_file = output_dir / "population_gn_clean.parquet"

population_clean.to_parquet(
    output_file,
    index=False
)

print("\nSaved successfully:", output_file)
print("File exists:", output_file.exists())

Final shape: (14008, 24)

Columns:
['province_code', 'province_name', 'district_code', 'district_name', 'ds_code', 'ds_name', 'gn_code', 'gn_name', 'total_population', 'male', 'female', 'age_total', 'age_0_14', 'age_15_59', 'age_60_64', 'age_65_plus', 'age_sum', 'age_difference', 'sex_sum', 'sex_difference', 'elderly_60_plus', 'children_ratio', 'elderly_ratio', 'female_ratio']

Missing values:
province_code       0
province_name       0
district_code       0
district_name       0
ds_code             0
ds_name             0
gn_code             0
gn_name             0
total_population    0
male                0
female              0
age_total           0
age_0_14            0
age_15_59           0
age_60_64           0
age_65_plus         0
age_sum             0
age_difference      0
sex_sum             0
sex_difference      0
elderly_60_plus     0
children_ratio      5
elderly_ratio       5
female_ratio        5
dtype: int64

Data types:
province_code                int64
province_name       string[python]
district_code                int64
district_name       string[python]
ds_code                      int64
ds_name             string[python]
gn_code             string[python]
gn_name                     object
total_population             int64
male                         int64
female                       int64
age_total                    int64
age_0_14                     int64
age_15_59                    int64
age_60_64                    int64
age_65_plus                  int64
age_sum                      int64
age_difference               int64
sex_sum                      int64
sex_difference               int64
elderly_60_plus              int64
children_ratio             float64
elderly_ratio              float64
female_ratio               float64
dtype: object

Saved successfully: /Users/ohaseelanka/disaster_analytics_hub/data/interim/census/population_gn_clean.parquet
File exists: True

In [81]:
census_housing_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "census"
    / "GN_housing_excel.xlsx"
)

print("File exists:", census_housing_file.exists())

excel_housing = pd.ExcelFile(census_housing_file)

print("\nSheets:")
print(excel_housing.sheet_names)

for sheet_name in excel_housing.sheet_names:
    print("\n" + "=" * 80)
    print("SHEET:", repr(sheet_name))
    print("=" * 80)

    df_preview = pd.read_excel(
        census_housing_file,
        sheet_name=sheet_name,
        header=None,
        nrows=15
    )

    print(df_preview.to_string())

File exists: True

Sheets:
['Housing Units']

================================================================================
SHEET: 'Housing Units'
================================================================================
                                                                                                            0               1               2               3                  4                  5                  6                  7                    8                       9
0                                                                                                         NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                     NaN
1   Census of Population and Housing - 2024\nOccupied Housing Units by Grama Niladhari Division (Provisional)             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                     NaN
2                                                                                                         NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                     NaN
3                                                                                              Province\nCode  Province\nName  District\nCode  District\nName  DS_Division\nCode  DS_Division\nName  GN_Division\nCode  GN_Division\nName  GN_Division\nNumber  Occupied Housing Units
4                                                                                                         NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                     NaN
5                                                                                                           1         Western              11         Colombo                  3            Colombo                  5   Sammanthranapura                                         1834
6                                                                                                           1         Western              11         Colombo                  3            Colombo                 10       Mattakkuliya                                         6838
7                                                                                                           1         Western              11         Colombo                  3            Colombo                 15             Modara                                         7725
8                                                                                                           1         Western              11         Colombo                  3            Colombo                 20        Madampitiya                                         1893
9                                                                                                           1         Western              11         Colombo                  3            Colombo                 25          Mahawatta                                         1746
10                                                                                                          1         Western              11         Colombo                  3            Colombo                 30       Aluthmawatha                                         3648
11                                                                                                          1         Western              11         Colombo                  3            Colombo                 35         Lunupokuna                                         3355
12                                                                                                          1         Western              11         Colombo                  3            Colombo                 40        Bloemendhal                                         2111
13                                                                                                          1         Western              11         Colombo                  3            Colombo                 45      Kotahena East                                         1676
14                                                                                                          1         Western              11         Colombo                  3            Colombo                 50      Kotahena West                                         2497

In [82]:
# ---------------------------------------------------------
# CLEAN 2024 GN-LEVEL HOUSING DATA
# ---------------------------------------------------------

census_housing_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "census"
    / "GN_housing_excel.xlsx"
)

# Read the actual data
housing_raw = pd.read_excel(
    census_housing_file,
    sheet_name="Housing Units",
    header=None
)

# Row 3 contains the column headers
housing = housing_raw.iloc[5:].copy()

# Assign clean column names
housing.columns = [
    "province_code",
    "province_name",
    "district_code",
    "district_name",
    "ds_code",
    "ds_name",
    "gn_code",
    "gn_name",
    "gn_number",
    "occupied_housing_units"
]

housing = housing.reset_index(drop=True)

print("Initial shape:", housing.shape)

print("\nColumns:")
print(housing.columns.tolist())

print("\nFirst 5 rows:")
print(housing.head().to_string())

Initial shape: (14008, 10)

Columns:
['province_code', 'province_name', 'district_code', 'district_name', 'ds_code', 'ds_name', 'gn_code', 'gn_name', 'gn_number', 'occupied_housing_units']

First 5 rows:
  province_code province_name district_code district_name ds_code  ds_name gn_code           gn_name gn_number occupied_housing_units
0             1       Western            11       Colombo       3  Colombo       5  Sammanthranapura                             1834
1             1       Western            11       Colombo       3  Colombo      10      Mattakkuliya                             6838
2             1       Western            11       Colombo       3  Colombo      15            Modara                             7725
3             1       Western            11       Colombo       3  Colombo      20       Madampitiya                             1893
4             1       Western            11       Colombo       3  Colombo      25         Mahawatta                             1746

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [83]:
print("\nData types:")
print(housing.dtypes)

print("\nMissing values:")
print(housing.isna().sum())

print("\nDuplicate rows:")
print(housing.duplicated().sum())

Data types:
province_code             object
province_name             object
district_code             object
district_name             object
ds_code                   object
ds_name                   object
gn_code                   object
gn_name                   object
gn_number                 object
occupied_housing_units    object
dtype: object

Missing values:
province_code             0
province_name             0
district_code             0
district_name             0
ds_code                   0
ds_name                   0
gn_code                   0
gn_name                   0
gn_number                 0
occupied_housing_units    0
dtype: int64

Duplicate rows:
0

In [85]:
# ---------------------------------------------------------
# CONVERT HOUSING DATA TYPES
# ---------------------------------------------------------

numeric_columns = [
    "province_code",
    "district_code",
    "ds_code",
    "gn_code",
    "occupied_housing_units"
]

for col in numeric_columns:
    housing[col] = pd.to_numeric(
        housing[col],
        errors="coerce"
    )

# Keep GN number as text because it may contain mixed formats
housing["gn_number"] = housing["gn_number"].astype("string")

# Convert geographic names to consistent text type
text_columns = [
    "province_name",
    "district_name",
    "ds_name",
    "gn_name"
]

for col in text_columns:
    housing[col] = housing[col].astype("string")

# ---------------------------------------------------------
# VALIDATION
# ---------------------------------------------------------

print("Shape:", housing.shape)

print("\nData types:")
print(housing.dtypes)

print("\nMissing values:")
print(housing.isna().sum())

print("\nHousing units statistics:")
print(housing["occupied_housing_units"].describe())

# Check for invalid zero/negative housing counts
print("\nZero housing units:", (housing["occupied_housing_units"] == 0).sum())
print(
    "Negative housing units:",
    (housing["occupied_housing_units"] < 0).sum()
)

Shape: (14008, 10)

Data types:
province_code                      int64
province_name             string[python]
district_code                      int64
district_name             string[python]
ds_code                            int64
ds_name                   string[python]
gn_code                            int64
gn_name                   string[python]
gn_number                 string[python]
occupied_housing_units             int64
dtype: object

Missing values:
province_code             0
province_name             0
district_code             0
district_name             0
ds_code                   0
ds_name                   0
gn_code                   0
gn_name                   0
gn_number                 0
occupied_housing_units    0
dtype: int64

Housing units statistics:
count    14008.000000
mean       430.506925
std        347.106701
min          0.000000
25%        233.000000
50%        339.000000
75%        511.000000
max       7725.000000
Name: occupied_housing_units, dtype: float64

Zero housing units: 5
Negative housing units: 0

In [86]:
# ---------------------------------------------------------
# VALIDATE POPULATION AND HOUSING GN MATCHING
# ---------------------------------------------------------

# Make sure both GN codes use the same type
population_gn_codes = set(
    population_clean["gn_code"]
    .astype("string")
    .str.strip()
)

housing_gn_codes = set(
    housing["gn_code"]
    .astype("string")
    .str.strip()
)

# Compare GN codes
population_only = population_gn_codes - housing_gn_codes
housing_only = housing_gn_codes - population_gn_codes
common_gn_codes = population_gn_codes & housing_gn_codes

print("Population GN codes:", len(population_gn_codes))
print("Housing GN codes:", len(housing_gn_codes))
print("Common GN codes:", len(common_gn_codes))

print("\nGN codes only in population:")
print(len(population_only))

if population_only:
    print(sorted(population_only)[:20])

print("\nGN codes only in housing:")
print(len(housing_only))

if housing_only:
    print(sorted(housing_only)[:20])

# ---------------------------------------------------------
# Check duplicate GN codes
# ---------------------------------------------------------

print("\nDuplicate GN codes in population:")
print(population_clean["gn_code"].duplicated().sum())

print("\nDuplicate GN codes in housing:")
print(housing["gn_code"].duplicated().sum())

Population GN codes: 154
Housing GN codes: 154
Common GN codes: 154

GN codes only in population:
0

GN codes only in housing:
0

Duplicate GN codes in population:
13854

Duplicate GN codes in housing:
13854

In [87]:
# ---------------------------------------------------------
# CREATE COMPLETE GN IDENTIFIER
# ---------------------------------------------------------

population_key = (
    population_clean["district_code"].astype("string").str.strip()
    + "_"
    + population_clean["ds_code"].astype("string").str.strip()
    + "_"
    + population_clean["gn_code"].astype("string").str.strip()
)

housing_key = (
    housing["district_code"].astype("string").str.strip()
    + "_"
    + housing["ds_code"].astype("string").str.strip()
    + "_"
    + housing["gn_code"].astype("string").str.strip()
)

# ---------------------------------------------------------
# Compare keys
# ---------------------------------------------------------

population_keys = set(population_key)
housing_keys = set(housing_key)

population_only = population_keys - housing_keys
housing_only = housing_keys - population_keys
common_keys = population_keys & housing_keys

print("Population unique GN keys:", len(population_keys))
print("Housing unique GN keys:", len(housing_keys))
print("Common GN keys:", len(common_keys))

print("\nKeys only in population:", len(population_only))
print("Keys only in housing:", len(housing_only))

# ---------------------------------------------------------
# Duplicate check
# ---------------------------------------------------------

print("\nDuplicate complete GN keys in population:")
print(population_key.duplicated().sum())

print("\nDuplicate complete GN keys in housing:")
print(housing_key.duplicated().sum())

Population unique GN keys: 14008
Housing unique GN keys: 14008
Common GN keys: 14008

Keys only in population: 0
Keys only in housing: 0

Duplicate complete GN keys in population:
0

Duplicate complete GN keys in housing:
0

In [88]:
# ---------------------------------------------------------
# CREATE UNIQUE GN KEY
# ---------------------------------------------------------

housing["gn_key"] = (
    housing["district_code"].astype("string").str.strip()
    + "_"
    + housing["ds_code"].astype("string").str.strip()
    + "_"
    + housing["gn_code"].astype("string").str.strip()
)

# ---------------------------------------------------------
# Validate the new key
# ---------------------------------------------------------

print("Unique GN keys:", housing["gn_key"].nunique())
print("Total records:", len(housing))
print("Duplicate GN keys:", housing["gn_key"].duplicated().sum())

# ---------------------------------------------------------
# Save cleaned housing dataset
# ---------------------------------------------------------

output_dir = PROJECT_ROOT / "data" / "interim" / "census"
output_dir.mkdir(parents=True, exist_ok=True)

output_file = output_dir / "housing_gn_clean.parquet"

housing.to_parquet(
    output_file,
    index=False
)

print("\nSaved successfully:", output_file)
print("File exists:", output_file.exists())

Unique GN keys: 14008
Total records: 14008
Duplicate GN keys: 0

Saved successfully: /Users/ohaseelanka/disaster_analytics_hub/data/interim/census/housing_gn_clean.parquet
File exists: True

In [89]:
# ---------------------------------------------------------
# INSPECT HOUSEHOLD / GN CENSUS DATA
# ---------------------------------------------------------

hh_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "census"
    / "HH_GND_excel.xlsx"
)

print("File exists:", hh_file.exists())

excel_hh = pd.ExcelFile(hh_file)

print("\nSheets:")
print(excel_hh.sheet_names)

for sheet_name in excel_hh.sheet_names:
    print("\n" + "=" * 80)
    print("SHEET:", repr(sheet_name))
    print("=" * 80)

    df_preview = pd.read_excel(
        hh_file,
        sheet_name=sheet_name,
        header=None,
        nrows=20
    )

    print(df_preview.to_string())

File exists: True

Sheets:
['Households']

================================================================================
SHEET: 'Households'
================================================================================
                                                                                                          0               1               2               3                  4                  5                  6                  7                    8                     9                                  10                   11                12         13                 14                                                         15                                  16                                               17                                               18                   19          20             21                         22      23               24                                           25        26    27           28                   29       30                       31            32                                                          33             34                            35                         36       37         38                       39                                                       40                                                        41                                               42                                                43                                                     44                     45                                                      46
0                                                                                                        NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                                NaN                  NaN               NaN        NaN                NaN                                                        NaN                                 NaN                                              NaN                                              NaN                  NaN         NaN            NaN                        NaN     NaN              NaN                                          NaN       NaN   NaN          NaN                  NaN      NaN                      NaN           NaN                                                         NaN            NaN                           NaN                        NaN      NaN        NaN                      NaN                                                      NaN                                                       NaN                                              NaN                                               NaN                                                    NaN                    NaN                                                     NaN
1   Census of Population and Housing - 2024\nHousehold Information by Grama Niladhari Division (Provisional)             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                                NaN                  NaN               NaN        NaN                NaN                                                        NaN                                 NaN                                              NaN                                              NaN                  NaN         NaN            NaN                        NaN     NaN              NaN                                          NaN       NaN   NaN          NaN                  NaN      NaN                      NaN           NaN                                                         NaN            NaN                           NaN                        NaN      NaN        NaN                      NaN                                                      NaN                                                       NaN                                              NaN                                               NaN                                                    NaN                    NaN                                                     NaN
2                                                                                                        NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                                NaN                  NaN               NaN        NaN                NaN                                                        NaN                                 NaN                                              NaN                                              NaN                  NaN         NaN            NaN                        NaN     NaN              NaN                                          NaN       NaN   NaN          NaN                  NaN      NaN                      NaN           NaN                                                         NaN            NaN                           NaN                        NaN      NaN        NaN                      NaN                                                      NaN                                                       NaN                                              NaN                                               NaN                                                    NaN                    NaN                                                     NaN
3                                                                                             Province\nCode  Province\nName  District\nCode  District\nName  DS_Division\nCode  DS_Division\nName  GN_Division\nCode  GN_Division\nName  GN_Division\nNumber  Number of Households  Main Source/way of drinking water                  NaN               NaN        NaN                NaN                                                        NaN                                 NaN                                              NaN                                              NaN                  NaN         NaN            NaN                        NaN     NaN              NaN  Main Source of Energy/Fuel Used for Cooking       NaN   NaN          NaN                  NaN      NaN                      NaN           NaN                                     Main source of Lighting            NaN                           NaN                        NaN      NaN        NaN                      NaN                                        Toilet facilities                                                       NaN                                              NaN                                               NaN                                                    NaN                    NaN                                                     NaN
4                                                                                                        NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                       Ground Water                  NaN               NaN        NaN                NaN                                           Pipe Borne water                                 NaN                                              NaN                                              NaN                Other         NaN            NaN                        NaN     NaN              NaN                                          NaN       NaN   NaN          NaN                  NaN      NaN                      NaN           NaN                                                         NaN            NaN                           NaN                        NaN      NaN        NaN                      NaN                                          Within the unit                                                       NaN                                 Outside the unit                                               NaN                                                  Other                    NaN                                                     NaN
5                                                                                                        NaN             NaN             NaN             NaN                NaN                NaN                NaN                NaN                  NaN                   NaN                     Protected well  Semi protected well  Unprotected well  Tube well  Spring/\nFountain  Pipe borne water - National water supply & drainage board  Pipe borne water - Local Authority  Pipe borne water - Community base organiziation  Pipe borne water - Private water supply project  Tank/ River/Streams  Rain water  Bottled water  Filter water (R.O. Plant)  Bowser  Other (specify)                                    Fire wood  Kerosene   Gas  Electricity  Saw dust/Paddy husk  Bio gas  Other (Specify bellow )  Not relavent  Electricity - from National grid/rural hydro power project  Kerosene lamp  Solar power (grid connected)  Solar power (stand alone)  Bio gas  Generator  Other (Specify bellow )  Within the housing unit - Exclusively for the household  Within the housing unit - Sharing with another household  Within Premises - Exclusively for the household  Within Premises - Sharing with another household  No toilet but sharing with another housing unit/units  Common/ Public toilet  Not using a toilet (use jungle, beach and open ground)
6                                                                                                          1         Western              11         Colombo                  3            Colombo                  5   Sammanthranapura                                       1859                                  4                    3                 0          1                  0                                                       1846                                   5                                                0                                                0                    0           0              0                          0       0                0                                           91       248  1436            4                    0        0                        0            80                                                        1817             24                             0                          0        0          0                       18                                                     1645                                                        40                                                5                                                10                                                     31                    127                                                       1
7                                                                                                          1         Western              11         Colombo                  3            Colombo                 10       Mattakkuliya                                       6957                                 21                    8                 1         55                  0                                                       6811                                  22                                               14                                                0                    1           0             17                          3       0                4                                          221       308  6243           39                    0       11                        1           134                                                        6859             62                            22                          2        0          1                       11                                                     6593                                                        76                                               89                                                19                                                     13                    163                                                       4
8                                                                                                          1         Western              11         Colombo                  3            Colombo                 15             Modara                                       7809                                 19                    2                 1        676                  2                                                       6958                                 143                                                2                                                3                    1           0              0                          1       1                0                                           59       355  7225           41                    0        2                        4           123                                                        7752             36                             0                          0        0         10                       11                                                     7572                                                        61                                               89                                                30                                                     17                     30                                                      10
9                                                                                                          1         Western              11         Colombo                  3            Colombo                 20        Madampitiya                                       1904                                 16                   38                 0          2                  0                                                       1830                                  11                                                4                                                1                    0           0              0                          0       2                0                                           90       176  1591           10                    0        0                        2            35                                                        1803             61                             0                          0        0          0                       40                                                     1742                                                        54                                               23                                                 7                                                     18                     60                                                       0
10                                                                                                         1         Western              11         Colombo                  3            Colombo                 25          Mahawatta                                       1833                                 30                    4                 0          0                  0                                                       1768                                  26                                                3                                                0                    0           0              2                          0       0                0                                           73       223  1451            7                    0        0                        0            79                                                        1796             29                             0                          1        0          0                        7                                                     1729                                                        26                                               20                                                 5                                                     18                     34                                                       1
11                                                                                                         1         Western              11         Colombo                  3            Colombo                 30       Aluthmawatha                                       3685                                403                   15                 0          4                  1                                                       3210                                  11                                                0                                                1                    0           2              0                          0       0               38                                          155       150  3216           17                    0        0                        1           146                                                        3581             60                             8                          0        2          0                       34                                                     3412                                                        61                                               64                                                29                                                     22                     95                                                       2
12                                                                                                         1         Western              11         Colombo                  3            Colombo                 35         Lunupokuna                                       3371                                  3                    7                 1          7                  3                                                       3327                                  11                                               11                                                0                    0           0              1                          0       0                0                                           26       242  2996           30                    0        0                        0            77                                                        3207            125                             1                          0        0          0                       38                                                     3175                                                        28                                               10                                                10                                                     30                    117                                                       1

In [90]:
# ---------------------------------------------------------
# CLEAN 2024 GN-LEVEL HOUSEHOLD DATA
# ---------------------------------------------------------

hh_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "census"
    / "HH_GND_excel.xlsx"
)

household_raw = pd.read_excel(
    hh_file,
    sheet_name="Households",
    header=None
)

# Actual data starts at row 6
households = household_raw.iloc[6:].copy()

# Assign clean column names
households.columns = [
    "province_code",
    "province_name",
    "district_code",
    "district_name",
    "ds_code",
    "ds_name",
    "gn_code",
    "gn_name",
    "gn_number",
    "number_of_households",

    # Drinking water
    "water_protected_well",
    "water_semi_protected_well",
    "water_unprotected_well",
    "water_tube_well",
    "water_spring_fountain",
    "water_national_water_supply",
    "water_local_authority",
    "water_community_organization",
    "water_private_supply",
    "water_tank_river_stream",
    "water_rain_water",
    "water_bottled",
    "water_filter_ro_plant",
    "water_bowser",
    "water_other",

    # Cooking energy
    "cooking_firewood",
    "cooking_kerosene",
    "cooking_gas",
    "cooking_electricity",
    "cooking_sawdust_paddy_husk",
    "cooking_biogas",
    "cooking_other",
    "cooking_not_relevant",

    # Lighting
    "lighting_n

SyntaxError: unterminated string literal (detected at line 63) (2078158664.py, line 63)

In [91]:
# ---------------------------------------------------------
# CLEAN 2024 GN-LEVEL HOUSEHOLD DATA
# ---------------------------------------------------------

hh_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "census"
    / "HH_GND_excel.xlsx"
)

household_raw = pd.read_excel(
    hh_file,
    sheet_name="Households",
    header=None
)

# Actual household data starts at row 6
households = household_raw.iloc[6:].copy()

# Assign clean column names
households.columns = [
    "province_code",
    "province_name",
    "district_code",
    "district_name",
    "ds_code",
    "ds_name",
    "gn_code",
    "gn_name",
    "gn_number",
    "number_of_households",

    # Drinking water
    "water_protected_well",
    "water_semi_protected_well",
    "water_unprotected_well",
    "water_tube_well",
    "water_spring_fountain",
    "water_national_water_supply",
    "water_local_authority",
    "water_community_organization",
    "water_private_supply",
    "water_tank_river_stream",
    "water_rain_water",
    "water_bottled",
    "water_filter_ro_plant",
    "water_bowser",
    "water_other",

    # Cooking energy
    "cooking_firewood",
    "cooking_kerosene",
    "cooking_gas",
    "cooking_electricity",
    "cooking_sawdust_paddy_husk",
    "cooking_biogas",
    "cooking_other",
    "cooking_not_relevant",

    # Lighting
    "lighting_national_grid_hydro",
    "lighting_kerosene_lamp",
    "lighting_solar_grid",
    "lighting_solar_standalone",
    "lighting_biogas",
    "lighting_generator",
    "lighting_other",

    # Toilet facilities
    "toilet_within_unit_exclusive",
    "toilet_within_unit_shared",
    "toilet_within_premises_exclusive",
    "toilet_within_premises_shared",
    "toilet_no_toilet_shared_elsewhere",
    "toilet_common_public",
    "toilet_no_toilet"
]

households = households.reset_index(drop=True)

print("Shape:", households.shape)

print("\nNumber of columns:", len(households.columns))

print("\nColumns:")
for i, col in enumerate(households.columns, start=1):
    print(i, col)

print("\nFirst 3 records:")
print(households.head(3).to_string())

Shape: (14008, 47)

Number of columns: 47

Columns:
1 province_code
2 province_name
3 district_code
4 district_name
5 ds_code
6 ds_name
7 gn_code
8 gn_name
9 gn_number
10 number_of_households
11 water_protected_well
12 water_semi_protected_well
13 water_unprotected_well
14 water_tube_well
15 water_spring_fountain
16 water_national_water_supply
17 water_local_authority
18 water_community_organization
19 water_private_supply
20 water_tank_river_stream
21 water_rain_water
22 water_bottled
23 water_filter_ro_plant
24 water_bowser
25 water_other
26 cooking_firewood
27 cooking_kerosene
28 cooking_gas
29 cooking_electricity
30 cooking_sawdust_paddy_husk
31 cooking_biogas
32 cooking_other
33 cooking_not_relevant
34 lighting_national_grid_hydro
35 lighting_kerosene_lamp
36 lighting_solar_grid
37 lighting_solar_standalone
38 lighting_biogas
39 lighting_generator
40 lighting_other
41 toilet_within_unit_exclusive
42 toilet_within_unit_shared
43 toilet_within_premises_exclusive
44 toilet_within_premises_shared
45 toilet_no_toilet_shared_elsewhere
46 toilet_common_public
47 toilet_no_toilet

First 3 records:
  province_code province_name district_code district_name ds_code  ds_name gn_code           gn_name gn_number number_of_households water_protected_well water_semi_protected_well water_unprotected_well water_tube_well water_spring_fountain water_national_water_supply water_local_authority water_community_organization water_private_supply water_tank_river_stream water_rain_water water_bottled water_filter_ro_plant water_bowser water_other cooking_firewood cooking_kerosene cooking_gas cooking_electricity cooking_sawdust_paddy_husk cooking_biogas cooking_other cooking_not_relevant lighting_national_grid_hydro lighting_kerosene_lamp lighting_solar_grid lighting_solar_standalone lighting_biogas lighting_generator lighting_other toilet_within_unit_exclusive toilet_within_unit_shared toilet_within_premises_exclusive toilet_within_premises_shared toilet_no_toilet_shared_elsewhere toilet_common_public toilet_no_toilet
0             1       Western            11       Colombo       3  Colombo       5  Sammanthranapura                           1859                    4                         3                      0               1                     0                        1846                     5                            0                    0                       0                0             0                     0            0           0               91              248        1436                   4                          0              0             0                   80                         1817                     24                   0                         0               0                  0             18                         1645                        40                                5                            10                                31                  127                1
1             1       Western            11       Colombo       3  Colombo      10      Mattakkuliya                           6957                   21                         8                      1              55                     0                        6811                    22                           14                    0                       1                0            17                     3            0           4              221              308        6243                  39                          0             11             1                  134                         6859                     62                  22                         2               0                  1             11                         6593                        76                               89                            19                                13                  163                4
2             1       Western            11       Colombo       3  Colombo      15            Modara                           7809                   19                         2                      1             676                     2                        6958                   143                            2                    3                       1                0             0                     1            1           0               59              355        7225                  41                          0              2             4                  123                         7752                     36                   0                         0               0                 10             11                         7572                        61                               89                            30                                17                   30               10

In [92]:
# ---------------------------------------------------------
# VALIDATE HOUSEHOLD CATEGORY TOTALS
# ---------------------------------------------------------

# Convert all household count columns to numeric temporarily
household_count_columns = households.columns[9:]

for col in household_count_columns:
    households[col] = pd.to_numeric(
        households[col],
        errors="coerce"
    )

# ---------------------------------------------------------
# Calculate category totals
# ---------------------------------------------------------

water_columns = [
    "water_protected_well",
    "water_semi_protected_well",
    "water_unprotected_well",
    "water_tube_well",
    "water_spring_fountain",
    "water_national_water_supply",
    "water_local_authority",
    "water_community_organization",
    "water_private_supply",
    "water_tank_river_stream",
    "water_rain_water",
    "water_bottled",
    "water_filter_ro_plant",
    "water_bowser",
    "water_other"
]

cooking_columns = [
    "cooking_firewood",
    "cooking_kerosene",
    "cooking_gas",
    "cooking_electricity",
    "cooking_sawdust_paddy_husk",
    "cooking_biogas",
    "cooking_other",
    "cooking_not_relevant"
]

lighting_columns = [
    "lighting_national_grid_hydro",
    "lighting_kerosene_lamp",
    "lighting_solar_grid",
    "lighting_solar_standalone",
    "lighting_biogas",
    "lighting_generator",
    "lighting_other"
]

toilet_columns = [
    "toilet_within_unit_exclusive",
    "toilet_within_unit_shared",

_IncompleteInputError: incomplete input (301317212.py, line 59)

In [93]:
# ---------------------------------------------------------
# VALIDATE HOUSEHOLD CATEGORY TOTALS
# ---------------------------------------------------------

# Convert household count columns to numeric
for col in households.columns[9:]:
    households[col] = pd.to_numeric(
        households[col],
        errors="coerce"
    )

# Define category groups
water_columns = [
    "water_protected_well",
    "water_semi_protected_well",
    "water_unprotected_well",
    "water_tube_well",
    "water_spring_fountain",
    "water_national_water_supply",
    "water_local_authority",
    "water_community_organization",
    "water_private_supply",
    "water_tank_river_stream",
    "water_rain_water",
    "water_bottled",
    "water_filter_ro_plant",
    "water_bowser",
    "water_other"
]

cooking_columns = [
    "cooking_firewood",
    "cooking_kerosene",
    "cooking_gas",
    "cooking_electricity",
    "cooking_sawdust_paddy_husk",
    "cooking_biogas",
    "cooking_other",
    "cooking_not_relevant"
]

lighting_columns = [
    "lighting_national_grid_hydro",
    "lighting_kerosene_lamp",
    "lighting_solar_grid",
    "lighting_solar_standalone",
    "lighting_biogas",
    "lighting_generator",
    "lighting_other"
]

toilet_columns = [
    "toilet_within_unit_exclusive",
    "toilet_within_unit_shared",
    "toilet_within_premises_exclusive",
    "toilet_within_premises_shared",
    "toilet_no_toilet_shared_elsewhere",
    "toilet_common_public",
    "toilet_no_toilet"
]

# Calculate category totals
households["water_sum"] = households[water_columns].sum(axis=1)
households["cooking_sum"] = households[cooking_columns].sum(axis=1)
households["lighting_sum"] = households[lighting_columns].sum(axis=1)
households["toilet_sum"] = households[toilet_columns].sum(axis=1)

# Compare against total households
households["water_difference"] = (
    households["water_sum"] - households["number_of_households"]
)

households["cooking_difference"] = (
    households["cooking_sum"] - households["number_of_households"]
)

households["lighting_difference"] = (
    households["lighting_sum"] - households["number_of_households"]
)

households["toilet_difference"] = (
    households["toilet_sum"] - households["number_of_households"]
)

# Results
print("Water mismatches:",
      (households["water_difference"] != 0).sum())

print("Cooking mismatches:",
      (households["cooking_difference"] != 0).sum())

print("Lighting mismatches:",
      (households["lighting_difference"] != 0).sum())

print("Toilet mismatches:",
      (households["toilet_difference"] != 0).sum())

print("\nDifference statistics:")

print("\nWater:")
print(households["water_difference"].describe())

print("\nCooking:")
print(households["cooking_difference"].describe())

print("\nLighting:")
print(households["lighting_difference"].describe())

print("\nToilet:")
print(households["toilet_difference"].describe())

Water mismatches: 0
Cooking mismatches: 0
Lighting mismatches: 0
Toilet mismatches: 0

Difference statistics:

Water:
count    14008.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: water_difference, dtype: float64

Cooking:
count    14008.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: cooking_difference, dtype: float64

Lighting:
count    14008.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: lighting_difference, dtype: float64

Toilet:
count    14008.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: toilet_difference, dtype: float64

In [95]:
# ---------------------------------------------------------
# FINALIZE GN-LEVEL HOUSEHOLD DATA
# ---------------------------------------------------------

# Remove temporary validation columns
validation_columns = [
    "water_sum",
    "cooking_sum",
    "lighting_sum",
    "toilet_sum",
    "water_difference",
    "cooking_difference",
    "lighting_difference",
    "toilet_difference"
]

households_clean = households.drop(
    columns=validation_columns
).copy()

# ---------------------------------------------------------
# Convert administrative identifiers
# ---------------------------------------------------------

numeric_columns = [
    "province_code",
    "district_code",
    "ds_code",
    "gn_code",
    "number_of_households"
]

for col in numeric_columns:
    households_clean[col] = pd.to_numeric(
        households_clean[col],
        errors="coerce"
    )

# GN number remains text
households_clean["gn_number"] = (
    households_clean["gn_number"].astype("string")
)

# Administrative names
text_columns = [
    "province_name",
    "district_name",
    "ds_name",
    "gn_name"
]

for col in text_columns:
    households_clean[col] = (
        households_clean[col].astype("string")
    )

# ---------------------------------------------------------
# Household condition variables
# ---------------------------------------------------------

condition_columns = [
    col for col in households_clean.columns
    if col not in [
        "province_code",
        "province_name",
        "district_code",
        "district_name",
        "ds_code",
        "ds_name",
        "gn_code",
        "gn_name",
        "gn_number"
    ]
]

for col in condition_columns:
    households_clean[col] = pd.to_numeric(
        households_clean[col],
        errors="coerce"
    )

# ---------------------------------------------------------
# Create unique GN key
# ---------------------------------------------------------

households_clean["gn_key"] = (
    households_clean["district_code"].astype("string").str.strip()
    + "_"
    + households_clean["ds_code"].astype("string").str.strip()
    + "_"
    + households_clean["gn_code"].astype("string").str.strip()
)

# ---------------------------------------------------------
# Final validation
# ---------------------------------------------------------

print("Shape:", households_clean.shape)

print("\nUnique GN keys:",
      households_clean["gn_key"].nunique())

print("Duplicate GN keys:",
      households_clean["gn_key"].duplicated().sum())

print("\nMissing values:")
print(households_clean.isna().sum().sum())

print("\nData types:")
print(households_clean.dtypes)

# ---------------------------------------------------------
# Save
# ---------------------------------------------------------

output_dir = PROJECT_ROOT / "data" / "interim" / "census"
output_dir.mkdir(parents=True, exist_ok=True)

output_file = output_dir / "households_gn_clean.parquet"

households_clean.to_parquet(
    output_file,
    index=False
)

print("\nSaved successfully:", output_file)
print("File exists:", output_file.exists())

Shape: (14008, 48)

Unique GN keys: 14008
Duplicate GN keys: 0

Missing values:
0

Data types:
province_code                                 int64
province_name                        string[python]
district_code                                 int64
district_name                        string[python]
ds_code                                       int64
ds_name                              string[python]
gn_code                                       int64
gn_name                              string[python]
gn_number                            string[python]
number_of_households                          int64
water_protected_well                          int64
water_semi_protected_well                     int64
water_unprotected_well                        int64
water_tube_well                               int64
water_spring_fountain                         int64
water_national_water_supply                   int64
water_local_authority                         int64
water_community_organization                  int64
water_private_supply                          int64
water_tank_river_stream                       int64
water_rain_water                              int64
water_bottled                                 int64
water_filter_ro_plant                         int64
water_bowser                                  int64
water_other                                   int64
cooking_firewood                              int64
cooking_kerosene                              int64
cooking_gas                                   int64
cooking_electricity                           int64
cooking_sawdust_paddy_husk                    int64
cooking_biogas                                int64
cooking_other                                 int64
cooking_not_relevant                          int64
lighting_national_grid_hydro                  int64
lighting_kerosene_lamp                        int64
lighting_solar_grid                           int64
lighting_solar_standalone                     int64
lighting_biogas                               int64
lighting_generator                            int64
lighting_other                                int64
toilet_within_unit_exclusive                  int64
toilet_within_unit_shared                     int64
toilet_within_premises_exclusive              int64
toilet_within_premises_shared                 int64
toilet_no_toilet_shared_elsewhere             int64
toilet_common_public                          int64
toilet_no_toilet                              int64
gn_key                               string[python]
dtype: object

Saved successfully: /Users/ohaseelanka/disaster_analytics_hub/data/interim/census/households_gn_clean.parquet
File exists: True

In [96]:
# ---------------------------------------------------------
# MERGE THE 3 CLEAN CENSUS DATASETS
# ---------------------------------------------------------

population_clean = pd.read_parquet(
    PROJECT_ROOT / "data/interim/census/population_gn_clean.parquet"
)

housing_clean = pd.read_parquet(
    PROJECT_ROOT / "data/interim/census/housing_gn_clean.parquet"
)

households_clean = pd.read_parquet(
    PROJECT_ROOT / "data/interim/census/households_gn_clean.parquet"
)

print("Population:", population_clean.shape)
print("Housing:", housing_clean.shape)
print("Households:", households_clean.shape)

Population: (14008, 24)
Housing: (14008, 11)
Households: (14008, 48)

In [97]:
# ---------------------------------------------------------
# VERIFY GN KEYS BEFORE MERGING
# ---------------------------------------------------------

population_keys = set(population_clean["gn_key"])
housing_keys = set(housing_clean["gn_key"])
household_keys = set(households_clean["gn_key"])

print("Population unique keys:", len(population_keys))
print("Housing unique keys:", len(housing_keys))
print("Household unique keys:", len(household_keys))

print("\nPopulation ↔ Housing")
print("Common:", len(population_keys & housing_keys))
print("Population only:", len(population_keys - housing_keys))
print("Housing only:", len(housing_keys - population_keys))

print("\nPopulation ↔ Households")
print("Common:", len(population_keys & household_keys))
print("Population only:", len(population_keys - household_keys))
print("Households only:", len(household_keys - population_keys))

print("\nHousing ↔ Households")
print("Common:", len(housing_keys & household_keys))
print("Housing only:", len(housing_keys - household_keys))
print("Households only:", len(household_keys - housing_keys))

KeyError: 'gn_key'

In [98]:
# ---------------------------------------------------------
# CREATE / STANDARDIZE GN KEY FOR ALL 3 CENSUS DATASETS
# ---------------------------------------------------------

def create_gn_key(df):
    df = df.copy()

    df["gn_key"] = (
        df["district_code"].astype("string").str.strip()
        + "_"
        + df["ds_code"].astype("string").str.strip()
        + "_"
        + df["gn_code"].astype("string").str.strip()
    )

    return df


# Create GN keys
population_clean = create_gn_key(population_clean)
housing_clean = create_gn_key(housing_clean)
households_clean = create_gn_key(households_clean)


# ---------------------------------------------------------
# Check
# ---------------------------------------------------------

print("Population:", population_clean.shape)
print("Housing:", housing_clean.shape)
print("Households:", households_clean.shape)

print("\nGN key columns:")
print("Population:", "gn_key" in population_clean.columns)
print("Housing:", "gn_key" in housing_clean.columns)
print("Households:", "gn_key" in households_clean.columns)

print("\nUnique GN keys:")
print("Population:", population_clean["gn_key"].nunique())
print("Housing:", housing_clean["gn_key"].nunique())
print("Households:", households_clean["gn_key"].nunique())

print("\nDuplicate GN keys:")
print("Population:", population_clean["gn_key"].duplicated().sum())
print("Housing:", housing_clean["gn_key"].duplicated().sum())
print("Households:", households_clean["gn_key"].duplicated().sum())

Population: (14008, 25)
Housing: (14008, 11)
Households: (14008, 48)

GN key columns:
Population: True
Housing: True
Households: True

Unique GN keys:
Population: 14008
Housing: 14008
Households: 14008

Duplicate GN keys:
Population: 0
Housing: 0
Households: 0

In [99]:
# ---------------------------------------------------------
# FINAL GN KEY MATCHING CHECK
# ---------------------------------------------------------

population_keys = set(population_clean["gn_key"])
housing_keys = set(housing_clean["gn_key"])
household_keys = set(households_clean["gn_key"])

print("Population ↔ Housing")
print("Common:", len(population_keys & housing_keys))
print("Population only:", len(population_keys - housing_keys))
print("Housing only:", len(housing_keys - population_keys))

print("\nPopulation ↔ Households")
print("Common:", len(population_keys & household_keys))
print("Population only:", len(population_keys - household_keys))
print("Households only:", len(household_keys - population_keys))

print("\nHousing ↔ Households")
print("Common:", len(housing_keys & household_keys))
print("Housing only:", len(housing_keys - household_keys))
print("Households only:", len(household_keys - housing_keys))

# Overall check
all_match = (
    population_keys == housing_keys == household_keys
)

print("\nAll three datasets match:", all_match)

Population ↔ Housing
Common: 14008
Population only: 0
Housing only: 0

Population ↔ Households
Common: 14008
Population only: 0
Households only: 0

Housing ↔ Households
Common: 14008
Housing only: 0
Households only: 0

All three datasets match: True

In [100]:
# ---------------------------------------------------------
# MERGE POPULATION + HOUSING + HOUSEHOLDS
# ---------------------------------------------------------

# Start with population data
census_gn = population_clean.copy()

# Remove duplicate administrative columns from housing
housing_merge = housing_clean.drop(
    columns=[
        "province_code",
        "province_name",
        "district_code",
        "district_name",
        "ds_code",
        "ds_name",
        "gn_code",
        "gn_name",
        "gn_number"
    ]
)

# Merge housing
census_gn = census_gn.merge(
    housing_merge,
    on="gn_key",
    how="inner",
    validate="one_to_one"
)

# Remove duplicate administrative columns from households
households_merge = households_clean.drop(
    columns=[
        "province_code",
        "province_name",
        "district_code",
        "district_name",
        "ds_code",
        "ds_name",
        "gn_code",
        "gn_name",
        "gn_number"
    ]
)

# Merge households
census_gn = census_gn.merge(
    households_merge,
    on="gn_key",
    how="inner",
    validate="one_to_one"
)

# ---------------------------------------------------------
# CHECK RESULT
# ---------------------------------------------------------

print("Final Census GN shape:", census_gn.shape)

print("\nUnique GN keys:",
      census_gn["gn_key"].nunique())

print("Duplicate GN keys:",
      census_gn["gn_key"].duplicated().sum())

print("\nMissing values:")
print("Total missing values:", census_gn.isna().sum().sum())

print("\nFirst 5 rows:")
display(census_gn.head())

Final Census GN shape: (14008, 64)

Unique GN keys: 14008
Duplicate GN keys: 0

Missing values:
Total missing values: 15

First 5 rows:

,province_code,province_name,district_code,district_name,ds_code,ds_name,gn_code,gn_name,total_population,male,...,lighting_biogas,lighting_generator,lighting_other,toilet_within_unit_exclusive,toilet_within_unit_shared,toilet_within_premises_exclusive,toilet_within_premises_shared,toilet_no_toilet_shared_elsewhere,toilet_common_public,toilet_no_toilet
0,1,Western,11,Colombo,3,Colombo,5,Sammanthranapura,7640,3864,...,0,0,18,1645,40,5,10,31,127,1
1,1,Western,11,Colombo,3,Colombo,10,Mattakkuliya,28135,13749,...,0,1,11,6593,76,89,19,13,163,4
2,1,Western,11,Colombo,3,Colombo,15,Modara,31728,15579,...,0,10,11,7572,61,89,30,17,30,10
3,1,Western,11,Colombo,3,Colombo,20,Madampitiya,7699,3890,...,0,0,40,1742,54,23,7,18,60,0
4,1,Western,11,Colombo,3,Colombo,25,Mahawatta,7108,3611,...,0,0,7,1729,26,20,5,18,34,1

In [101]:
# ---------------------------------------------------------
# INSPECT ALL MISSING VALUES IN THE MERGED CENSUS DATA
# ---------------------------------------------------------

missing_summary = (
    census_gn.isna()
    .sum()
    .sort_values(ascending=False)
)

print("Columns containing missing values:")
display(
    missing_summary[missing_summary > 0]
)

# Show the actual affected GN records
missing_columns = missing_summary[
    missing_summary > 0
].index.tolist()

print("\nAffected records:")
display(
    census_gn[
        census_gn[missing_columns].isna().any(axis=1)
    ][[
        "gn_key",
        "district_name",
        "ds_name",
        "gn_name",
        "total_population",
        "children_ratio",
        "elderly_ratio",
        "female_ratio"
    ]]
)

Columns containing missing values:

female_ratio      5
elderly_ratio     5
children_ratio    5
dtype: int64

Affected records:

,gn_key,district_name,ds_name,gn_name,total_population,children_ratio,elderly_ratio,female_ratio
6940,41_12_185,Jaffna,Valikamam North (Tellipallai),Myliddyththurai South,0,NaN,NaN,NaN
6947,41_12_220,Jaffna,Valikamam North (Tellipallai),Palaly North West,0,NaN,NaN,NaN
6948,41_12_225,Jaffna,Valikamam North (Tellipallai),Palaly West,0,NaN,NaN,NaN
7797,51_10_25,Batticaloa,Koralai Pattu South (Kiran),Kallichchai,0,NaN,NaN,NaN
11817,72_10_65,Polonnaruwa,Welikanda,Alinchipothana,0,NaN,NaN,NaN

In [102]:
# ---------------------------------------------------------
# FINALIZE CENSUS GN MASTER DATASET
# ---------------------------------------------------------

# Copy merged dataset
census_gn_final = census_gn.copy()

# Remove population validation columns
validation_columns = [
    "age_sum",
    "age_difference",
    "sex_sum",
    "sex_difference"
]

census_gn_final = census_gn_final.drop(
    columns=validation_columns,
    errors="ignore"
)

# ---------------------------------------------------------
# Final structure check
# ---------------------------------------------------------

print("Final Census shape:", census_gn_final.shape)

print("\nUnique GN keys:",
      census_gn_final["gn_key"].nunique())

print("Duplicate GN keys:",
      census_gn_final["gn_key"].duplicated().sum())

print("\nMissing values:")
missing_final = (
    census_gn_final.isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    missing_final[missing_final > 0]
)

# ---------------------------------------------------------
# Save final Census GN dataset
# ---------------------------------------------------------

output_file = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "census_gn_master.parquet"
)

output_file.parent.mkdir(
    parents=True,
    exist_ok=True
)

census_gn_final.to_parquet(
    output_file,
    index=False
)

print("\nSaved successfully:", output_file)
print("File exists:", output_file.exists())

Final Census shape: (14008, 60)

Unique GN keys: 14008
Duplicate GN keys: 0

Missing values:

female_ratio      5
elderly_ratio     5
children_ratio    5
dtype: int64

Saved successfully: /Users/ohaseelanka/disaster_analytics_hub/data/processed/census_gn_master.parquet
File exists: True

In [103]:
# ---------------------------------------------------------
# INSPECT KALU GANGA RAW DATA
# ---------------------------------------------------------

kalu_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "flood"
    / "kalu"
    / "Rathnapura.xlsx"
)

print("File exists:", kalu_file.exists())

# List all sheets
kalu_excel = pd.ExcelFile(kalu_file)

print("\nSheets:")
for sheet in kalu_excel.sheet_names:
    print("-", sheet)

File exists: True

Sheets:
- General Information
- WL Summery MSL
- Q

In [104]:
# ---------------------------------------------------------
# PREVIEW KALU GANGA SHEETS
# ---------------------------------------------------------

for sheet in kalu_excel.sheet_names:

    print("\n" + "=" * 80)
    print("SHEET:", sheet)
    print("=" * 80)

    preview = pd.read_excel(
        kalu_file,
        sheet_name=sheet,
        header=None,
        nrows=20
    )

    display(preview)

================================================================================
SHEET: General Information
================================================================================

,0,1,2,3
0,General Information,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,River Basin,03 - Kalu Ganga,NaN,NaN
3,NaN,NaN,NaN,NaN
4,Station Name,Rathnapura,NaN,NaN
5,NaN,NaN,NaN,NaN
6,Coordinates,60 40' 43.2'' 800 23' 49.8'',NaN,NaN
7,NaN,"158588 , 164427",NaN,NaN
8,NaN,NaN,NaN,NaN
9,Catchment Area,603.0 km2,NaN,NaN
10,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN
12,Classified Flood Levels,Alert,NaN,17.14 m MSL
13,NaN,Minor Flood,NaN,19.44 m MSL
14,NaN,Major Flood,NaN,21.44 m MSL

================================================================================
SHEET: WL Summery MSL
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,RATHNAPURA WATER LEVELS in m (MSL),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Year,Month,Day,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,...,6.000000,7.000000,8.000000,9.000000,10.000000,11.000000,12.000000,AVG,Max,Min
3,2015,1,1,13.492533,13.542533,13.572533,13.592533,13.582533,13.572533,13.562533,...,13.402533,13.392533,13.382533,13.372533,13.352533,13.312533,13.232533,13.458366,13.592533,13.232533
4,2015,1,2,13.202533,13.162533,13.132533,13.122533,13.112533,13.102533,13.102533,...,13.042533,13.042533,13.052533,13.052533,13.062533,13.072533,13.072533,13.080033,13.202533,13.042533
5,2015,1,3,13.062533,13.022533,13.002533,12.992533,12.982533,12.972533,12.962533,...,12.912533,12.912533,12.912533,12.912533,12.922533,12.932533,12.942533,12.946699,13.062533,12.912533
6,2015,1,4,12.962533,12.942533,12.922533,12.912533,12.892533,12.882533,12.872533,...,12.852533,12.852533,12.852533,12.852533,12.852533,12.842533,12.832533,12.864616,12.962533,12.822533
7,2015,1,5,12.832533,12.822533,12.822533,12.822533,12.812533,12.812533,12.812533,...,12.762533,12.762533,12.792533,12.842533,12.892533,12.922533,12.962533,12.818783,12.962533,12.762533
8,2015,1,6,12.962533,12.942533,12.932533,12.922533,12.912533,12.902533,12.902533,...,12.822533,12.822533,12.862533,12.892533,12.912533,12.922533,12.932533,12.886699,12.962533,12.822533
9,2015,1,7,13.042533,13.192533,13.392533,13.492533,13.542533,13.592533,13.572533,...,13.192533,13.172533,13.142533,13.112533,13.072533,13.042533,13.032533,13.307533,13.592533,13.032533
10,2015,1,8,13.012533,12.992533,12.982533,12.962533,12.942533,12.932533,12.912533,...,12.762533,12.752533,12.742533,12.732533,12.722533,12.722533,12.712533,12.836283,13.012533,12.712533
11,2015,1,9,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,...,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533
12,2015,1,10,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,...,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533,13.492533
13,2015,1,11,12.582533,12.582533,12.582533,12.572533,12.572533,12.572533,12.572533,...,12.562533,12.562533,12.562533,12.562533,12.562533,12.562533,12.562533,12.567949,12.582533,12.562533
14,2015,1,12,12.572533,12.582533,12.592533,12.582533,12.572533,12.562533,12.562533,...,12.552533,12.552533,12.552533,12.552533,12.552533,12.562533,12.562533,12.563366,12.592533,12.552533
15,2015,1,13,12.562533,12.562533,12.562533,12.562533,12.562533,12.562533,12.562533,...,12.532533,12.532533,12.532533,12.532533,12.532533,12.542533,12.542533,12.547533,12.562533,12.532533
16,2015,1,14,12.542533,12.542533,12.532533,12.532533,12.532533,12.532533,12.532533,...,12.522533,12.522533,12.522533,12.522533,12.522533,12.522533,12.532533,12.527533,12.542533,12.522533
17,2015,1,15,12.542533,12.552533,12.542533,12.532533,12.532533,12.532533,12.532533,...,12.522533,12.522533,12.522533,12.522533,12.522533,12.522533,12.522533,12.528366,12.552533,12.522533
18,2015,1,16,12.512533,12.512533,12.512533,12.512533,12.512533,12.512533,12.512533,...,12.512533,12.512533,12.512533,12.512533,12.512533,12.512533,12.512533,12.515033,12.522533,12.512533
19,2015,1,17,12.512533,12.512533,12.512533,12.512533,12.512533,12.512533,12.512533,...,12.502533,12.502533,12.502533,12.502533,12.512533,12.512533,12.522533,12.507533,12.522533,12.502533

================================================================================
SHEET: Q
================================================================================

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.492533
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,frm 2007
2,Year,Month,Day,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,...,6.000000,7.000000,8.000000,9.000000,10.000000,11.000000,12.000000,AVG,Max,Min
3,2015,1,1,24.971082,26.172749,26.909476,27.407213,27.157685,26.909476,26.662586,...,22.889956,22.665169,22.441664,22.219440,21.778826,20.912876,19.241632,24.224286,27.407213,19.241632
4,2015,1,2,18.635596,17.844951,17.264945,17.074070,16.884421,16.695997,16.695997,...,15.591049,15.591049,15.772171,15.772171,15.954505,16.138052,16.138052,16.286905,18.635596,15.591049
5,2015,1,3,15.954505,15.232431,14.878632,14.703534,14.529635,14.356931,14.185421,...,13.345699,13.345699,13.345699,13.345699,13.511274,13.678032,13.845974,13.925681,15.954505,13.345699
6,2015,1,4,14.185421,13.845974,13.511274,13.345699,13.018087,12.856045,12.695177,...,12.376950,12.376950,12.376950,12.376950,12.376950,12.219587,12.063388,12.576275,14.185421,11.908351
7,2015,1,5,12.063388,11.908351,11.908351,11.908351,11.754472,11.754472,11.754472,...,11.002384,11.002384,11.450183,12.219587,13.018087,13.511274,14.185421,11.863112,14.185421,11.002384
8,2015,1,6,14.185421,13.845974,13.678032,13.511274,13.345699,13.181304,13.181304,...,11.908351,11.908351,12.535479,13.018087,13.345699,13.511274,13.678032,12.932562,14.185421,11.908351
9,2015,1,7,15.591049,18.436075,22.665169,24.971082,26.172749,27.407213,26.909476,...,18.436075,18.040754,17.457048,16.884421,16.138052,15.591049,15.411136,21.009752,27.407213,15.411136
10,2015,1,8,15.054930,14.703534,14.529635,14.185421,13.845974,13.678032,13.345699,...,11.002384,10.855411,10.709580,10.564889,10.421335,10.421335,10.278917,12.17155,15.05493,10.278917
11,2015,1,9,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,...,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082
12,2015,1,10,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,...,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082,24.971082
13,2015,1,11,8.529642,8.529642,8.529642,8.402854,8.402854,8.402854,8.402854,...,8.277162,8.277162,8.277162,8.277162,8.277162,8.277162,8.277162,8.345382,8.529642,8.277162
14,2015,1,12,8.402854,8.529642,8.657531,8.529642,8.402854,8.277162,8.277162,...,8.152565,8.152565,8.152565,8.152565,8.152565,8.277162,8.277162,8.288185,8.657531,8.152565
15,2015,1,13,8.277162,8.277162,8.277162,8.277162,8.277162,8.277162,8.277162,...,7.906646,7.906646,7.906646,7.906646,7.906646,8.029061,8.029061,8.09145,8.277162,7.906646
16,2015,1,14,8.029061,8.029061,7.906646,7.906646,7.906646,7.906646,7.906646,...,7.785318,7.785318,7.785318,7.785318,7.785318,7.785318,7.906646,7.846072,8.029061,7.785318
17,2015,1,15,8.029061,8.152565,8.029061,7.906646,7.906646,7.906646,7.906646,...,7.785318,7.785318,7.785318,7.785318,7.785318,7.785318,7.785318,7.856319,8.152565,7.785318
18,2015,1,16,7.665074,7.665074,7.665074,7.665074,7.665074,7.665074,7.665074,...,7.665074,7.665074,7.665074,7.665074,7.665074,7.665074,7.665074,7.695135,7.785318,7.665074
19,2015,1,17,7.665074,7.665074,7.665074,7.665074,7.665074,7.665074,7.665074,...,7.545911,7.545911,7.545911,7.545911,7.665074,7.665074,7.785318,7.605538,7.785318,7.545911

In [105]:
# ---------------------------------------------------------
# KALU GANGA - DATE COVERAGE
# ---------------------------------------------------------

for sheet_name, df in [
    ("Water Level", kalu_wl_raw),
    ("Discharge", kalu_q_raw)
]:

    dates = pd.to_datetime(
        df.iloc[3:, 0].astype(str) + "-" +
        df.iloc[3:, 1].astype(str) + "-" +
        df.iloc[3:, 2].astype(str),
        errors="coerce"
    )

    dates = dates.dropna()

    print("=" * 60)
    print(sheet_name)
    print("=" * 60)
    print("Number of valid dates :", len(dates))
    print("Start date             :", dates.min())
    print("End date               :", dates.max())
    print("Unique dates           :", dates.nunique())

    # Check duplicate dates
    duplicates = dates.duplicated().sum()
    print("Duplicate dates        :", duplicates)

NameError: name 'kalu_wl_raw' is not defined

In [106]:
# ---------------------------------------------------------
# KALU GANGA - LOAD DATA AND CHECK DATE COVERAGE
# ---------------------------------------------------------

# Load the two measurement sheets
kalu_wl_raw = pd.read_excel(
    kalu_file,
    sheet_name="WL Summery MSL",
    header=None
)

kalu_q_raw = pd.read_excel(
    kalu_file,
    sheet_name="Q",
    header=None
)

# ---------------------------------------------------------
# Function to check date coverage
# ---------------------------------------------------------

def check_date_coverage(df, name):

    dates = pd.to_datetime(
        df.iloc[3:, 0].astype(str) + "-" +
        df.iloc[3:, 1].astype(str) + "-" +
        df.iloc[3:, 2].astype(str),
        errors="coerce"
    )

    dates = dates.dropna()

    print("=" * 60)
    print(name)
    print("=" * 60)

    print("Rows in workbook       :", len(df))
    print("Valid dates            :", len(dates))
    print("Unique dates           :", dates.nunique())
    print("Start date             :", dates.min())
    print("End date               :", dates.max())
    print("Duplicate dates        :", dates.duplicated().sum())


# ---------------------------------------------------------
# Run checks
# ---------------------------------------------------------

check_date_coverage(
    kalu_wl_raw,
    "KALU GANGA - WATER LEVEL"
)

print()

check_date_coverage(
    kalu_q_raw,
    "KALU GANGA - DISCHARGE"
)

============================================================
KALU GANGA - WATER LEVEL
============================================================
Rows in workbook       : 4153
Valid dates            : 4017
Unique dates           : 4016
Start date             : 2015-01-01 00:00:00
End date               : 2025-12-31 00:00:00
Duplicate dates        : 1

============================================================
KALU GANGA - DISCHARGE
============================================================
Rows in workbook       : 4153
Valid dates            : 4017
Unique dates           : 4016
Start date             : 2015-01-01 00:00:00
End date               : 2025-12-31 00:00:00
Duplicate dates        : 1

In [108]:
# ---------------------------------------------------------
# KALU GANGA - FIND DUPLICATE AND MISSING DATES
# ---------------------------------------------------------

def get_dates(df):
    return pd.to_datetime(
        df.iloc[3:, 0].astype(str) + "-" +
        df.iloc[3:, 1].astype(str) + "-" +
        df.iloc[3:, 2].astype(str),
        errors="coerce"
    )


# =========================
# WATER LEVEL
# =========================

wl_dates = get_dates(kalu_wl_raw)

print("=" * 60)
print("WATER LEVEL")
print("=" * 60)

duplicate_wl = wl_dates[wl_dates.duplicated(keep=False)].dropna()

print("Duplicate date:")
print(duplicate_wl.unique())

expected_wl = pd.date_range(
    wl_dates.min(),
    wl_dates.max(),
    freq="D"
)

missing_wl = expected_wl.difference(
    pd.DatetimeIndex(wl_dates.dropna().unique())
)

print("\nMissing date:")
print(missing_wl)


# =========================
# DISCHARGE
# =========================

q_dates = get_dates(kalu_q_raw)

print("\n" + "=" * 60)
print("DISCHARGE")
print("=" * 60)

duplicate_q = q_dates[q_dates.duplicated(keep=False)].dropna()

print("Duplicate date:")
print(duplicate_q.unique())

expected_q = pd.date_range(
    q_dates.min(),
    q_dates.max(),
    freq="D"
)

missing_q = expected_q.difference(
    pd.DatetimeIndex(q_dates.dropna().unique())
)

print("\nMissing date:")
print(missing_q)

============================================================
WATER LEVEL
============================================================
Duplicate date:
<DatetimeArray>
['2020-02-28 00:00:00']
Length: 1, dtype: datetime64[ns]

Missing date:
DatetimeIndex(['2017-01-01', '2020-02-29'], dtype='datetime64[ns]', freq=None)

============================================================
DISCHARGE
============================================================
Duplicate date:
<DatetimeArray>
['2020-02-28 00:00:00']
Length: 1, dtype: datetime64[ns]

Missing date:
DatetimeIndex(['2017-01-01', '2020-02-29'], dtype='datetime64[ns]', freq=None)

In [110]:
# ---------------------------------------------------------
# KALU GANGA - INSPECT DUPLICATE 2020-02-28
# ---------------------------------------------------------

duplicate_date = pd.Timestamp("2020-02-28")


# =========================
# WATER LEVEL
# =========================

wl_data = kalu_wl_raw.iloc[3:].copy()

wl_data["date"] = pd.to_datetime(
    wl_data.iloc[:, 0].astype(str) + "-" +
    wl_data.iloc[:, 1].astype(str) + "-" +
    wl_data.iloc[:, 2].astype(str),
    errors="coerce"
)

print("=" * 70)
print("WATER LEVEL - DUPLICATE 2020-02-28")
print("=" * 70)

display(
    wl_data[
        wl_data["date"] == duplicate_date
    ]
)


# =========================
# DISCHARGE
# =========================

q_data = kalu_q_raw.iloc[3:].copy()

q_data["date"] = pd.to_datetime(
    q_data.iloc[:, 0].astype(str) + "-" +
    q_data.iloc[:, 1].astype(str) + "-" +
    q_data.iloc[:, 2].astype(str),
    errors="coerce"
)

print("=" * 70)
print("DISCHARGE - DUPLICATE 2020-02-28")
print("=" * 70)

display(
    q_data[
        q_data["date"] == duplicate_date
    ]
)

======================================================================
WATER LEVEL - DUPLICATE 2020-02-28
======================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,date
1948,2020,2,28,12.23,12.22,12.22,12.21,12.22,12.23,12.24,...,12.26,12.24,12.23,12.23,12.21,12.20,12.24125,12.27,12.2,2020-02-28
1949,2020,2,28,12.20,12.19,12.19,12.18,12.18,12.18,12.18,...,12.26,12.24,12.23,12.23,12.21,12.21,12.19375,12.26,12.12,2020-02-28

======================================================================
DISCHARGE - DUPLICATE 2020-02-28
======================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,date
1948,2020,2,28,6.617459,6.510364,6.510364,6.404143,6.510364,6.617459,6.725427,...,6.943981,6.725427,6.617459,6.617459,6.404143,6.298795,6.740814,7.054568,6.298795,2020-02-28
1949,2020,2,28,6.298795,6.194320,6.194320,6.090718,6.090718,6.090718,6.090718,...,6.943981,6.725427,6.617459,6.617459,6.404143,6.404143,6.239319,6.943981,5.487442,2020-02-28

In [112]:
# ---------------------------------------------------------
# KALU GANGA - CLEAN WATER LEVEL AND DISCHARGE
# ---------------------------------------------------------

# =========================================================
# WATER LEVEL
# =========================================================

wl = kalu_wl_raw.iloc[3:].copy()

wl["date"] = pd.to_datetime(
    wl.iloc[:, 0].astype(str) + "-" +
    wl.iloc[:, 1].astype(str) + "-" +
    wl.iloc[:, 2].astype(str),
    errors="coerce"
)

# Keep only valid dates
wl = wl[wl["date"].notna()].copy()

# Rename hourly columns
wl_columns = (
    ["year", "month", "day"]
    + [f"hour_{i:02d}" for i in range(1, 25)]
    + ["avg", "max", "min", "date"]
)

wl.columns = wl_columns

# Convert measurements to numeric
measurement_columns = [
    f"hour_{i:02d}" for i in range(1, 25)
] + ["avg", "max", "min"]

for col in measurement_columns:
    wl[col] = pd.to_numeric(wl[col], errors="coerce")

# Remove duplicate date - keep first authentic record
wl = wl.drop_duplicates(
    subset="date",
    keep="first"
).copy()

# Sort chronologically
wl = wl.sort_values("date").reset_index(drop=True)


# =========================================================
# DISCHARGE
# =========================================================

q = kalu_q_raw.iloc[3:].copy()

q["date"] = pd.to_datetime(
    q.iloc[:, 0].astype(str) + "-" +
    q.iloc[:, 1].astype(str) + "-" +
    q.iloc[:, 2].astype(str),
    errors="coerce"
)

# Keep only valid dates
q = q[q["date"].notna()].copy()

# Rename columns
q_columns = (
    ["year", "month", "day"]
    + [f"hour_{i:02d}" for i in range(1, 25)]
    + ["avg", "max", "min", "date"]
)

q.columns = q_columns

# Convert measurements to numeric
for col in measurement_columns:
    q[col] = pd.to_numeric(q[col], errors="coerce")

# Remove duplicate date - keep first authentic record
q = q.drop_duplicates(
    subset="date",
    keep="first"
).copy()

# Sort chronologically
q = q.sort_values("date").reset_index(drop=True)


# =========================================================
# VALIDATION
# =========================================================

print("=" * 70)
print("KALU GANGA CLEANING VALIDATION")
print("=" * 70)

print("\nWATER LEVEL")
print("Rows:", len(wl))
print("Unique dates:", wl["date"].nunique())
print("Start:", wl["date"].min())
print("End:", wl["date"].max())
print("Duplicate dates:", wl["date"].duplicated().sum())

print("\nDISCHARGE")
print("Rows:", len(q))
print("Unique dates:", q["date"].nunique())
print("Start:", q["date"].min())
print("End:", q["date"].max())
print("Duplicate dates:", q["date"].duplicated().sum())

print("\nExpected observations:")
print("2015-01-01 to 2025-12-31 = 4018 calendar days")

print("\nMissing dates remain:")
expected_dates = pd.date_range(
    "2015-01-01",
    "2025-12-31",
    freq="D"
)

wl_missing = expected_dates.difference(
    pd.DatetimeIndex(wl["date"])
)

q_missing = expected_dates.difference(
    pd.DatetimeIndex(q["date"])
)

print("Water Level:", list(wl_missing))
print("Discharge:", list(q_missing))

======================================================================
KALU GANGA CLEANING VALIDATION
======================================================================

WATER LEVEL
Rows: 4016
Unique dates: 4016
Start: 2015-01-01 00:00:00
End: 2025-12-31 00:00:00
Duplicate dates: 0

DISCHARGE
Rows: 4016
Unique dates: 4016
Start: 2015-01-01 00:00:00
End: 2025-12-31 00:00:00
Duplicate dates: 0

Expected observations:
2015-01-01 to 2025-12-31 = 4018 calendar days

Missing dates remain:
Water Level: [Timestamp('2017-01-01 00:00:00'), Timestamp('2020-02-29 00:00:00')]
Discharge: [Timestamp('2017-01-01 00:00:00'), Timestamp('2020-02-29 00:00:00')]

In [113]:
# ---------------------------------------------------------
# SAVE CLEAN KALU GANGA DATA
# ---------------------------------------------------------

from pathlib import Path

output_dir = Path(
    "data/interim/flood/kalu"
)

output_dir.mkdir(
    parents=True,
    exist_ok=True
)

# Save cleaned water level
wl.to_parquet(
    output_dir / "water_level_daily.parquet",
    index=False
)

# Save cleaned discharge
q.to_parquet(
    output_dir / "discharge_daily.parquet",
    index=False
)

print("=" * 70)
print("KALU GANGA DATA SAVED")
print("=" * 70)

print(
    "Water Level:",
    output_dir / "water_level_daily.parquet"
)

print(
    "Discharge:",
    output_dir / "discharge_daily.parquet"
)

print("\nWater Level shape:", wl.shape)
print("Discharge shape:", q.shape)

======================================================================
KALU GANGA DATA SAVED
======================================================================
Water Level: data/interim/flood/kalu/water_level_daily.parquet
Discharge: data/interim/flood/kalu/discharge_daily.parquet

Water Level shape: (4016, 31)
Discharge shape: (4016, 31)

In [114]:
# ---------------------------------------------------------
# KALU GANGA - EXTRACT OFFICIAL FLOOD THRESHOLDS
# ---------------------------------------------------------

general_info = pd.read_excel(
    kalu_file,
    sheet_name="General Information",
    header=None
)

print("=" * 70)
print("KALU GANGA - GENERAL INFORMATION")
print("=" * 70)

display(general_info)

======================================================================
KALU GANGA - GENERAL INFORMATION
======================================================================

,0,1,2,3
0,General Information,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,River Basin,03 - Kalu Ganga,NaN,NaN
3,NaN,NaN,NaN,NaN
4,Station Name,Rathnapura,NaN,NaN
5,NaN,NaN,NaN,NaN
6,Coordinates,60 40' 43.2'' 800 23' 49.8'',NaN,NaN
7,NaN,"158588 , 164427",NaN,NaN
8,NaN,NaN,NaN,NaN
9,Catchment Area,603.0 km2,NaN,NaN
10,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN
12,Classified Flood Levels,Alert,NaN,17.14 m MSL
13,NaN,Minor Flood,NaN,19.44 m MSL
14,NaN,Major Flood,NaN,21.44 m MSL

In [115]:
# ---------------------------------------------------------
# KALU GANGA - CREATE DAILY HYDROLOGICAL FEATURES
# ---------------------------------------------------------

# =========================================================
# SELECT WATER LEVEL FEATURES
# =========================================================

wl_features = wl[
    [
        "date",
        "avg",
        "max",
        "min"
    ]
].copy()

wl_features = wl_features.rename(
    columns={
        "avg": "wl_avg",
        "max": "wl_max",
        "min": "wl_min"
    }
)


# =========================================================
# SELECT DISCHARGE FEATURES
# =========================================================

q_features = q[
    [
        "date",
        "avg",
        "max",
        "min"
    ]
].copy()

q_features = q_features.rename(
    columns={
        "avg": "discharge_avg",
        "max": "discharge_max",
        "min": "discharge_min"
    }
)


# =========================================================
# MERGE WATER LEVEL + DISCHARGE
# =========================================================

kalu_daily = wl_features.merge(
    q_features,
    on="date",
    how="outer",
    validate="one_to_one"
)

kalu_daily = kalu_daily.sort_values(
    "date"
).reset_index(drop=True)


# =========================================================
# OFFICIAL RATHNAPURA FLOOD THRESHOLDS
# =========================================================

ALERT_LEVEL = 17.14
MINOR_FLOOD_LEVEL = 19.44
MAJOR_FLOOD_LEVEL = 21.44


# =========================================================
# THRESHOLD FEATURES
# =========================================================

kalu_daily["alert_exceeded"] = (
    kalu_daily["wl_max"] >= ALERT_LEVEL
)

kalu_daily["minor_flood_exceeded"] = (
    kalu_daily["wl_max"] >= MINOR_FLOOD_LEVEL
)

kalu_daily["major_flood_exceeded"] = (
    kalu_daily["wl_max"] >= MAJOR_FLOOD_LEVEL
)


# =========================================================
# VALIDATION
# =========================================================

print("=" * 70)
print("KALU GANGA DAILY HYDROLOGICAL DATASET")
print("=" * 70)

print("\nShape:", kalu_daily.shape)

print("\nDate range:")
print("Start:", kalu_daily["date"].min())
print("End  :", kalu_daily["date"].max())

print("\nColumns:")
print(kalu_daily.columns.tolist())

print("\nMissing values:")
print(kalu_daily.isna().sum())

print("\nThreshold exceedances:")
print(
    "Alert days        :",
    kalu_daily["alert_exceeded"].sum()
)

print(
    "Minor flood days  :",
    kalu_daily["minor_flood_exceeded"].sum()
)

print(
    "Major flood days  :",
    kalu_daily["major_flood_exceeded"].sum()
)

print("\nFirst 5 rows:")
display(kalu_daily.head())

print("\nHighest water levels:")
display(
    kalu_daily.nlargest(
        10,
        "wl_max"
    )[
        [
            "date",
            "wl_avg",
            "wl_max",
            "wl_min",
            "discharge_avg",
            "discharge_max",
            "alert_exceeded",
            "minor_flood_exceeded",
            "major_flood_exceeded"
        ]
    ]
)

======================================================================
KALU GANGA DAILY HYDROLOGICAL DATASET
======================================================================

Shape: (4016, 10)

Date range:
Start: 2015-01-01 00:00:00
End  : 2025-12-31 00:00:00

Columns:
['date', 'wl_avg', 'wl_max', 'wl_min', 'discharge_avg', 'discharge_max', 'discharge_min', 'alert_exceeded', 'minor_flood_exceeded', 'major_flood_exceeded']

Missing values:
date                    0
wl_avg                  1
wl_max                  1
wl_min                  1
discharge_avg           1
discharge_max           1
discharge_min           1
alert_exceeded          0
minor_flood_exceeded    0
major_flood_exceeded    0
dtype: int64

Threshold exceedances:
Alert days        : 227
Minor flood days  : 30
Major flood days  : 4

First 5 rows:

,date,wl_avg,wl_max,wl_min,discharge_avg,discharge_max,discharge_min,alert_exceeded,minor_flood_exceeded,major_flood_exceeded
0,2015-01-01,13.458366,13.592533,13.232533,24.224286,27.407213,19.241632,False,False,False
1,2015-01-02,13.080033,13.202533,13.042533,16.286905,18.635596,15.591049,False,False,False
2,2015-01-03,12.946699,13.062533,12.912533,13.925681,15.954505,13.345699,False,False,False
3,2015-01-04,12.864616,12.962533,12.822533,12.576275,14.185421,11.908351,False,False,False
4,2015-01-05,12.818783,12.962533,12.762533,11.863112,14.185421,11.002384,False,False,False

Highest water levels:

,date,wl_avg,wl_max,wl_min,discharge_avg,discharge_max,alert_exceeded,minor_flood_exceeded,major_flood_exceeded
875,2017-05-26,22.105000,23.57,19.61,546.924377,689.031902,True,True,True
876,2017-05-27,22.211250,23.25,21.21,549.995451,654.418414,True,True,True
3982,2025-11-28,21.113750,22.15,18.92,451.452983,542.233303,True,True,True
3983,2025-11-29,20.696667,21.79,19.79,411.643879,507.806051,True,True,True
877,2017-05-28,20.355833,21.14,19.56,382.817262,448.503639,True,True,False
3438,2024-06-02,20.463750,21.08,19.04,392.069113,443.215026,True,True,False
1235,2018-05-21,20.277500,20.93,19.49,376.657499,430.130633,True,True,False
2380,2021-07-10,20.283333,20.86,18.84,377.086354,424.091629,True,True,False
1236,2018-05-22,19.835417,20.79,18.89,342.018027,418.095291,True,True,False
2767,2022-08-01,17.922083,20.78,13.95,238.612127,417.242155,True,True,False

In [116]:
# ---------------------------------------------------------
# KALU GANGA - CORRECT THRESHOLD FLAGS FOR MISSING DATA
# ---------------------------------------------------------

measurement_missing = (
    kalu_daily[
        [
            "wl_max",
            "discharge_max"
        ]
    ].isna().any(axis=1)
)

threshold_columns = [
    "alert_exceeded",
    "minor_flood_exceeded",
    "major_flood_exceeded"
]

# Set threshold indicators to missing where
# the required hydrological observation is missing
for col in threshold_columns:
    kalu_daily.loc[
        measurement_missing,
        col
    ] = pd.NA


# ---------------------------------------------------------
# VALIDATION
# ---------------------------------------------------------

print("=" * 70)
print("KALU GANGA - THRESHOLD FLAG VALIDATION")
print("=" * 70)

print("\nRows with missing hydrological measurements:")
display(
    kalu_daily[
        measurement_missing
    ]
)

print("\nThreshold missing counts:")
print(
    kalu_daily[
        threshold_columns
    ].isna().sum()
)

print("\nThreshold counts excluding missing observations:")

for col in threshold_columns:
    print(
        col,
        ":",
        kalu_daily[col].eq(True).sum()
    )

======================================================================
KALU GANGA - THRESHOLD FLAG VALIDATION
======================================================================

Rows with missing hydrological measurements:

/var/folders/7f/t00z49jj07x0fn7tv5p2rhyh0000gn/T/ipykernel_9564/2785119058.py:23: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  kalu_daily.loc[
/var/folders/7f/t00z49jj07x0fn7tv5p2rhyh0000gn/T/ipykernel_9564/2785119058.py:23: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  kalu_daily.loc[
/var/folders/7f/t00z49jj07x0fn7tv5p2rhyh0000gn/T/ipykernel_9564/2785119058.py:23: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  kalu_daily.loc[

,date,wl_avg,wl_max,wl_min,discharge_avg,discharge_max,discharge_min,alert_exceeded,minor_flood_exceeded,major_flood_exceeded
1338,2018-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Threshold missing counts:
alert_exceeded          1
minor_flood_exceeded    1
major_flood_exceeded    1
dtype: int64

Threshold counts excluding missing observations:
alert_exceeded : 227
minor_flood_exceeded : 30
major_flood_exceeded : 4

In [117]:
# ---------------------------------------------------------
# KALU GANGA - INSPECT 2018-09-01
# ---------------------------------------------------------

check_date = pd.Timestamp("2018-09-01")


# =========================
# WATER LEVEL
# =========================

wl_check = wl_data[
    wl_data["date"] == check_date
].copy()

print("=" * 70)
print("WATER LEVEL - 2018-09-01")
print("=" * 70)

display(wl_check)


# =========================
# DISCHARGE
# =========================

q_check = q_data[
    q_data["date"] == check_date
].copy()

print("=" * 70)
print("DISCHARGE - 2018-09-01")
print("=" * 70)

display(q_check)

======================================================================
WATER LEVEL - 2018-09-01
======================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,date
1386,2018,9,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-09-01

======================================================================
DISCHARGE - 2018-09-01
======================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,date
1386,2018,9,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-09-01

In [118]:
# ---------------------------------------------------------
# KALU GANGA - CHECK DISCHARGE 2018-09-01
# ---------------------------------------------------------

check_date = pd.Timestamp("2018-09-01")

q_check = q_data[
    q_data["date"] == check_date
].copy()

print("=" * 70)
print("DISCHARGE - 2018-09-01")
print("=" * 70)

display(q_check)

======================================================================
DISCHARGE - 2018-09-01
======================================================================

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,date
1386,2018,9,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-09-01

In [119]:
# Kalu Ganga - Data Quality Summary

kalu_quality_summary = pd.DataFrame({
    "issue": [
        "Missing date",
        "Missing measurements",
        "Missing date",
        "Duplicate date"
    ],
    "date": [
        "2017-01-01",
        "2018-09-01",
        "2020-02-29",
        "2020-02-28"
    ],
    "description": [
        "No source row exists for this date.",
        "Source row exists, but all hourly water-level and discharge measurements are missing.",
        "No source row exists for this date.",
        "Two different source rows exist for the same date; first authentic row retained."
    ],
    "treatment": [
        "Kept as missing; no value imputed.",
        "Kept as NaN; threshold flags set to <NA>.",
        "Kept as missing; no value imputed.",
        "First source row retained; duplicate documented."
    ]
})

display(kalu_quality_summary)

,issue,date,description,treatment
0,Missing date,2017-01-01,No source row exists for this date.,Kept as missing; no value imputed.
1,Missing measurements,2018-09-01,"Source row exists, but all hourly water-level ...",Kept as NaN; threshold flags set to <NA>.
2,Missing date,2020-02-29,No source row exists for this date.,Kept as missing; no value imputed.
3,Duplicate date,2020-02-28,Two different source rows exist for the same d...,First source row retained; duplicate documented.

In [120]:
print("Kalu daily dataset shape:", kalu_daily.shape)

print("\nMissing values:")
display(kalu_daily.isna().sum())

print("\nThreshold flag counts:")
for col in [
    "alert_exceeded",
    "minor_flood_exceeded",
    "major_flood_exceeded"
]:
    print(f"\n{col}")
    print(kalu_daily[col].value_counts(dropna=False))

Kalu daily dataset shape: (4016, 10)

Missing values:

date                    0
wl_avg                  1
wl_max                  1
wl_min                  1
discharge_avg           1
discharge_max           1
discharge_min           1
alert_exceeded          1
minor_flood_exceeded    1
major_flood_exceeded    1
dtype: int64

Threshold flag counts:

alert_exceeded
alert_exceeded
False    3788
True      227
NaN         1
Name: count, dtype: int64

minor_flood_exceeded
minor_flood_exceeded
False    3985
True       30
NaN         1
Name: count, dtype: int64

major_flood_exceeded
major_flood_exceeded
False    4011
True        4
NaN         1
Name: count, dtype: int64

In [121]:
kalu_daily[kalu_daily["date"] == "2018-09-01"]

,date,wl_avg,wl_max,wl_min,discharge_avg,discharge_max,discharge_min,alert_exceeded,minor_flood_exceeded,major_flood_exceeded
1338,2018-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [122]:
kalu_daily.to_parquet(
    "data/interim/flood/kalu/kalu_daily_hydrology.parquet",
    index=False
)

print("Saved successfully.")
print("Shape:", kalu_daily.shape)

Saved successfully.
Shape: (4016, 10)

In [124]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

Current working directory:
/Users/ohaseelanka/disaster_analytics_hub/notebooks

Files/folders here:
['01_data_inventory.ipynb', 'data']

In [125]:
import os

print("notebooks/data:")
print(os.listdir("data"))

print("\nnotebooks/data/interim:")
print(os.listdir("data/interim"))

print("\nnotebooks/data/interim/flood:")
print(os.listdir("data/interim/flood"))

notebooks/data:
['interim']

notebooks/data/interim:
['flood']

notebooks/data/interim/flood:
['kalu']

In [126]:
import os

base = "/Users/ohaseelanka/disaster_analytics_hub"

for root, dirs, files in os.walk(base):
    for file in files:
        if file in [
            "rainfall_daily_long.parquet",
            "water_level_daily.parquet",
            "discharge_daily.parquet"
        ]:
            print(os.path.join(root, file))

/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/rainfall_daily_long.parquet
/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/discharge_daily.parquet
/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/water_level_daily.parquet
/Users/ohaseelanka/disaster_analytics_hub/notebooks/data/interim/flood/kalu/discharge_daily.parquet
/Users/ohaseelanka/disaster_analytics_hub/notebooks/data/interim/flood/kalu/water_level_daily.parquet

In [127]:
import pandas as pd
import numpy as np

# Correct project-level paths
rainfall = pd.read_parquet(
    "/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/rainfall_daily_long.parquet"
)

water_level = pd.read_parquet(
    "/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/water_level_daily.parquet"
)

discharge = pd.read_parquet(
    "/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/discharge_daily.parquet"
)

print("RAINFALL")
print("Shape:", rainfall.shape)
print("Columns:", rainfall.columns.tolist())

print("\nWATER LEVEL")
print("Shape:", water_level.shape)
print("Columns:", water_level.columns.tolist())

print("\nDISCHARGE")
print("Shape:", discharge.shape)
print("Columns:", discharge.columns.tolist())

RAINFALL
Shape: (24108, 4)
Columns: ['station_id', 'station_name', 'date', 'rainfall_mm']

WATER LEVEL
Shape: (42006, 5)
Columns: ['station_id', 'station_name', 'date', 'water_level', 'unit']

DISCHARGE
Shape: (24108, 4)
Columns: ['station_id', 'station_name', 'date', 'discharge_m3s']

In [128]:
print("Rainfall sample:")
display(rainfall.head())

print("\nWater level sample:")
display(water_level.head())

print("\nDischarge sample:")
display(discharge.head())

Rainfall sample:

  station_id station_name       date  rainfall_mm
0       KN02      Norwood 2015-01-01          0.0
1       KN02      Norwood 2015-01-02          0.0
2       KN02      Norwood 2015-01-03          0.0
3       KN02      Norwood 2015-01-04          0.0
4       KN02      Norwood 2015-01-05          0.0

Water level sample:

  station_id station_name       date  water_level  unit
0       KN02      Norwood 1996-01-01  1098.211667  mMSL
1       KN02      Norwood 1996-01-02  1098.253333  mMSL
2       KN02      Norwood 1996-01-03  1098.202917  mMSL
3       KN02      Norwood 1996-01-04  1098.143333  mMSL
4       KN02      Norwood 1996-01-05  1098.112500  mMSL

Discharge sample:

  station_id station_name       date  discharge_m3s
0       KN02      Norwood 2015-01-01       8.509801
1       KN02      Norwood 2015-01-02       6.902546
2       KN02      Norwood 2015-01-03       7.394394
3       KN02      Norwood 2015-01-04       7.121124
4       KN02      Norwood 2015-01-05       6.819315

In [129]:
print("=" * 70)
print("KELANI RAINFALL SUMMARY")
print("=" * 70)

rainfall_summary = (
    rainfall.groupby(["station_id", "station_name"])["rainfall_mm"]
    .describe()
)

display(rainfall_summary)

======================================================================
KELANI RAINFALL SUMMARY
======================================================================

,,count,mean,std,min,25%,50%,75%,max
station_id,station_name,,,,,,,,
KN02,Norwood,4014.0,7.564895,14.322079,0.0,0.0,1.0,8.700,169.8
KN07,Kitulgala,4018.0,13.065729,22.551353,0.0,0.0,2.8,17.275,336.4
KN11,Holombuwa,4018.0,8.743977,18.832506,0.0,0.0,0.3,8.700,201.6
KN16,Deraniyagala,4017.0,13.681449,26.228713,0.0,0.0,1.9,16.200,355.6
KN18,Glencourse,4018.0,11.504652,22.502319,0.0,0.0,1.2,12.775,245.9
KN21,Hanwella,4018.0,9.349689,21.136717,0.0,0.0,0.6,9.300,350.4

In [130]:
wl_2015_2025 = water_level[
    (water_level["date"] >= "2015-01-01") &
    (water_level["date"] <= "2025-12-31")
].copy()

print("=" * 70)
print("KELANI WATER LEVEL SUMMARY — 2015-2025")
print("=" * 70)

water_level_summary = (
    wl_2015_2025.groupby(["station_id", "station_name"])["water_level"]
    .describe()
)

display(water_level_summary)

======================================================================
KELANI WATER LEVEL SUMMARY — 2015-2025
======================================================================

,,count,mean,std,min,25%,50%,75%,max
station_id,station_name,,,,,,,,
KN02,Norwood,4018.0,1098.437258,0.259843,1097.970000,1098.262500,1098.398333,1098.564167,1100.896250
KN07,Kitulgala,4018.0,53.743471,0.257045,53.166250,53.578833,53.713417,53.891646,57.437167
KN11,Holombuwa,4018.0,45.115553,0.455468,44.666214,44.824012,44.970055,45.260172,51.182464
KN16,Deraniyagala,4018.0,73.880592,0.488969,73.236054,73.529387,73.785622,74.095846,79.884804
KN18,Glencourse,4018.0,9.572291,1.284304,7.796167,8.648667,9.260333,10.151271,20.792417
KN21,Hanwella,4018.0,2.167168,1.396514,0.570000,1.166667,1.698542,2.710000,11.230000
NSTR,N'Street,4018.0,1.582450,0.590276,0.575000,1.279167,1.479167,1.706250,8.322917

In [131]:
print("=" * 70)
print("KELANI DISCHARGE SUMMARY")
print("=" * 70)

discharge_summary = (
    discharge.groupby(["station_id", "station_name"])["discharge_m3s"]
    .describe()
)

display(discharge_summary)

======================================================================
KELANI DISCHARGE SUMMARY
======================================================================

,,count,mean,std,min,25%,50%,75%,max
station_id,station_name,,,,,,,,
KN02,Norwood,4018.0,5.691646,5.904176,1.134287,2.969908,4.413551,6.650268,150.771043
KN07,Kitulgala,4017.0,39.091024,25.833777,4.546293,25.595143,34.204919,47.930439,741.184650
KN11,Holombuwa,4018.0,6.796949,16.744667,0.005500,0.683567,1.970721,6.404850,454.045039
KN16,Deraniyagala,4018.0,18.914069,20.849913,0.440939,6.051554,13.293134,24.583231,401.547991
KN18,Glencourse,4017.0,127.394395,154.851988,5.500703,44.885998,82.650444,158.050006,3104.164253
KN21,Hanwella,4017.0,118.832398,156.093791,10.700274,32.792959,62.645127,140.475123,1813.297333

In [132]:
print("=" * 70)
print("TOP KELANI RAINFALL DAYS")
print("=" * 70)

display(
    rainfall.nlargest(20, "rainfall_mm")[
        ["station_id", "station_name", "date", "rainfall_mm"]
    ]
)

======================================================================
TOP KELANI RAINFALL DAYS
======================================================================

      station_id  station_name       date  rainfall_mm
12554       KN16  Deraniyagala 2016-05-15        355.6
20965       KN21      Hanwella 2017-05-25        350.4
13289       KN16  Deraniyagala 2018-05-20        349.9
4518        KN07     Kitulgala 2016-05-15        336.4
12929       KN16  Deraniyagala 2017-05-25        303.5
23660       KN21      Hanwella 2024-10-10        275.7
16037       KN16  Deraniyagala 2025-11-27        251.5
16947       KN18    Glencourse 2017-05-25        245.9
21069       KN21      Hanwella 2017-09-06        244.5
22932       KN21      Hanwella 2022-10-13        235.7
14024       KN16  Deraniyagala 2020-05-24        231.9
8001        KN07     Kitulgala 2025-11-27        231.3
14378       KN16  Deraniyagala 2021-05-13        227.3
6399        KN07     Kitulgala 2021-07-09        226.0
16572       KN18    Glencourse 2016-05-15        225.8
19642       KN18    Glencourse 2024-10-10        218.4
15493       KN16  Deraniyagala 2024-06-01        215.4
20055       KN18    Glencourse 2025-11-27        215.1
14897       KN16  Deraniyagala 2022-10-14        214.6
5253        KN07     Kitulgala 2018-05-20        206.7

In [133]:
print("=" * 70)
print("TOP KELANI WATER-LEVEL DAYS")
print("=" * 70)

display(
    wl_2015_2025.nlargest(20, "water_level")[
        ["station_id", "station_name", "date", "water_level", "unit"]
    ]
)

======================================================================
TOP KELANI WATER-LEVEL DAYS
======================================================================

      station_id station_name       date  water_level  unit
9265        KN02      Norwood 2021-05-14  1100.896250  mMSL
10924       KN02      Norwood 2025-11-28  1100.466667  mMSL
9277        KN02      Norwood 2021-05-26  1100.325000  mMSL
10923       KN02      Norwood 2025-11-27  1100.291250  mMSL
9276        KN02      Norwood 2021-05-25  1100.237083  mMSL
8176        KN02      Norwood 2018-05-21  1100.072500  mMSL
9278        KN02      Norwood 2021-05-27  1100.015000  mMSL
9254        KN02      Norwood 2021-05-03  1099.940833  mMSL
8004        KN02      Norwood 2017-11-30  1099.785417  mMSL
8905        KN02      Norwood 2020-05-19  1099.690833  mMSL
9322        KN02      Norwood 2021-07-10  1099.593750  mMSL
10925       KN02      Norwood 2025-11-29  1099.517083  mMSL
7441        KN02      Norwood 2016-05-16  1099.491667  mMSL
10187       KN02      Norwood 2023-11-22  1099.484583  mMSL
7442        KN02      Norwood 2016-05-17  1099.453333  mMSL
7249        KN02      Norwood 2015-11-06  1099.421250  mMSL
9266        KN02      Norwood 2021-05-15  1099.421250  mMSL
10558       KN02      Norwood 2024-11-27  1099.389583  mMSL
10184       KN02      Norwood 2023-11-19  1099.378750  mMSL
8685        KN02      Norwood 2019-10-12  1099.370000  mMSL

In [134]:
print("=" * 70)
print("TOP KELANI DISCHARGE DAYS")
print("=" * 70)

display(
    discharge.nlargest(20, "discharge_m3s")[
        ["station_id", "station_name", "date", "discharge_m3s"]
    ]
)

======================================================================
TOP KELANI DISCHARGE DAYS
======================================================================

      station_id station_name       date  discharge_m3s
18016       KN18   Glencourse 2020-04-28    3104.164253
17578       KN18   Glencourse 2019-02-15    2919.566344
20057       KN18   Glencourse 2025-11-29    2291.171833
20056       KN18   Glencourse 2025-11-28    2022.696079
16573       KN18   Glencourse 2016-05-16    1847.867850
24075       KN21     Hanwella 2025-11-29    1813.297333
24076       KN21     Hanwella 2025-11-30    1810.329815
16574       KN18   Glencourse 2016-05-17    1720.078508
20593       KN21     Hanwella 2016-05-18    1604.195771
20592       KN21     Hanwella 2016-05-17    1563.507249
16575       KN18   Glencourse 2016-05-18    1423.368263
20594       KN21     Hanwella 2016-05-19    1365.210946
24077       KN21     Hanwella 2025-12-01    1364.221528
20595       KN21     Hanwella 2016-05-20    1348.840775
24074       KN21     Hanwella 2025-11-28    1330.931258
20058       KN18   Glencourse 2025-11-30    1328.267198
20591       KN21     Hanwella 2016-05-16    1311.701499
23530       KN21     Hanwella 2024-06-02    1308.914937
17308       KN18   Glencourse 2018-05-21    1283.117375
20967       KN21     Hanwella 2017-05-27    1270.151950

In [135]:
# Make copies so the original cleaned datasets remain unchanged

rf = rainfall.copy()
wl = wl_2015_2025.copy()
q = discharge.copy()

# Make sure dates are datetime
rf["date"] = pd.to_datetime(rf["date"])
wl["date"] = pd.to_datetime(wl["date"])
q["date"] = pd.to_datetime(q["date"])

# Sort correctly
rf = rf.sort_values(["station_id", "date"])
wl = wl.sort_values(["station_id", "date"])
q = q.sort_values(["station_id", "date"])

# ---------------------------------------------------------
# 1. Rainfall rolling features
# ---------------------------------------------------------

rf["rainfall_3d"] = (
    rf.groupby("station_id")["rainfall_mm"]
      .transform(lambda x: x.rolling(3, min_periods=3).sum())
)

rf["rainfall_7d"] = (
    rf.groupby("station_id")["rainfall_mm"]
      .transform(lambda x: x.rolling(7, min_periods=7).sum())
)

# ---------------------------------------------------------
# 2. Station-normalized water-level anomaly
# ---------------------------------------------------------

wl["wl_mean"] = (
    wl.groupby("station_id")["water_level"]
      .transform("mean")
)

wl["wl_std"] = (
    wl.groupby("station_id")["water_level"]
      .transform("std")
)

wl["wl_zscore"] = (
    (wl["water_level"] - wl["wl_mean"]) /
    wl["wl_std"]
)

# ---------------------------------------------------------
# 3. Station-normalized discharge anomaly
# ---------------------------------------------------------

q["q_mean"] = (
    q.groupby("station_id")["discharge_m3s"]
      .transform("mean")
)

q["q_std"] = (
    q.groupby("station_id")["discharge_m3s"]
      .transform("std")
)

q["q_zscore"] = (
    (q["discharge_m3s"] - q["q_mean"]) /
    q["q_std"]
)

print("Rainfall features:", rf.shape)
print("Water-level features:", wl.shape)
print("Discharge features:", q.shape)

Rainfall features: (24108, 6)
Water-level features: (28126, 8)
Discharge features: (24108, 7)

In [136]:
print("=" * 70)
print("RAINFALL FEATURES")
print("=" * 70)

display(
    rf[
        [
            "station_id",
            "date",
            "rainfall_mm",
            "rainfall_3d",
            "rainfall_7d"
        ]
    ].head(15)
)

print("=" * 70)
print("WATER-LEVEL FEATURES")
print("=" * 70)

display(
    wl[
        [
            "station_id",
            "date",
            "water_level",
            "wl_mean",
            "wl_std",
            "wl_zscore"
        ]
    ].head(15)
)

print("=" * 70)
print("DISCHARGE FEATURES")
print("=" * 70)

display(
    q[
        [
            "station_id",
            "date",
            "discharge_m3s",
            "q_mean",
            "q_std",
            "q_zscore"
        ]
    ].head(15)
)

======================================================================
RAINFALL FEATURES
======================================================================

   station_id       date  rainfall_mm  rainfall_3d  rainfall_7d
0        KN02 2015-01-01          0.0          NaN          NaN
1        KN02 2015-01-02          0.0          NaN          NaN
2        KN02 2015-01-03          0.0          0.0          NaN
3        KN02 2015-01-04          0.0          0.0          NaN
4        KN02 2015-01-05          0.0          0.0          NaN
5        KN02 2015-01-06          1.7          1.7          NaN
6        KN02 2015-01-07          0.0          1.7          1.7
7        KN02 2015-01-08          0.0          1.7          1.7
8        KN02 2015-01-09          0.0          0.0          1.7
9        KN02 2015-01-10          0.0          0.0          1.7
10       KN02 2015-01-11          0.0          0.0          1.7
11       KN02 2015-01-12          0.0          0.0          1.7
12       KN02 2015-01-13          0.0          0.0          0.0
13       KN02 2015-01-14          0.0          0.0          0.0
14       KN02 2015-01-15          0.0          0.0          0.0

======================================================================
WATER-LEVEL FEATURES
======================================================================

     station_id       date  water_level      wl_mean    wl_std  wl_zscore
6940       KN02 2015-01-01  1098.668333  1098.437258  0.259843   0.889288
6941       KN02 2015-01-02  1098.593750  1098.437258  0.259843   0.602255
6942       KN02 2015-01-03  1098.617917  1098.437258  0.259843   0.695260
6943       KN02 2015-01-04  1098.604583  1098.437258  0.259843   0.643947
6944       KN02 2015-01-05  1098.589583  1098.437258  0.259843   0.586220
6945       KN02 2015-01-06  1098.580000  1098.437258  0.259843   0.549339
6946       KN02 2015-01-07  1098.556250  1098.437258  0.259843   0.457937
6947       KN02 2015-01-08  1098.526667  1098.437258  0.259843   0.344086
6948       KN02 2015-01-09  1098.506250  1098.437258  0.259843   0.265513
6949       KN02 2015-01-10  1098.488750  1098.437258  0.259843   0.198165
6950       KN02 2015-01-11  1098.476667  1098.437258  0.259843   0.151662
6951       KN02 2015-01-12  1098.466250  1098.437258  0.259843   0.111574
6952       KN02 2015-01-13  1098.445417  1098.437258  0.259843   0.031397
6953       KN02 2015-01-14  1098.429167  1098.437258  0.259843  -0.031141
6954       KN02 2015-01-15  1098.423750  1098.437258  0.259843  -0.051987

======================================================================
DISCHARGE FEATURES
======================================================================

   station_id       date  discharge_m3s    q_mean     q_std  q_zscore
0        KN02 2015-01-01       8.509801  5.691646  5.904176  0.477316
1        KN02 2015-01-02       6.902546  5.691646  5.904176  0.205092
2        KN02 2015-01-03       7.394394  5.691646  5.904176  0.288397
3        KN02 2015-01-04       7.121124  5.691646  5.904176  0.242113
4        KN02 2015-01-05       6.819315  5.691646  5.904176  0.190995
5        KN02 2015-01-06       6.630659  5.691646  5.904176  0.159042
6        KN02 2015-01-07       6.175714  5.691646  5.904176  0.081988
7        KN02 2015-01-08       5.626016  5.691646  5.904176 -0.011116
8        KN02 2015-01-09       5.263352  5.691646  5.904176 -0.072541
9        KN02 2015-01-10       4.959773  5.691646  5.904176 -0.123959
10       KN02 2015-01-11       4.756467  5.691646  5.904176 -0.158393
11       KN02 2015-01-12       4.583691  5.691646  5.904176 -0.187656
12       KN02 2015-01-13       4.251836  5.691646  5.904176 -0.243863
13       KN02 2015-01-14       3.996093  5.691646  5.904176 -0.287179
14       KN02 2015-01-15       3.913382  5.691646  5.904176 -0.301187

In [137]:
# ============================================================
# INSPECT STATION-NORMALIZED HYDROLOGICAL FEATURES
# ============================================================

print("=" * 70)
print("RAINFALL EXTREMES")
print("=" * 70)

display(
    rf[
        ["station_id", "station_name", "date",
         "rainfall_mm", "rainfall_3d", "rainfall_7d"]
    ]
    .sort_values("rainfall_3d", ascending=False)
    .head(20)
)

print("=" * 70)
print("WATER-LEVEL ANOMALIES")
print("=" * 70)

display(
    wl[
        ["station_id", "station_name", "date",
         "water_level", "wl_zscore"]
    ]
    .sort_values("wl_zscore", ascending=False)
    .head(20)
)

print("=" * 70)
print("DISCHARGE ANOMALIES")
print("=" * 70)

display(
    q[
        ["station_id", "station_name", "date",
         "discharge_m3s", "q_zscore"]
    ]
    .sort_values("q_zscore", ascending=False)
    .head(20)
)

======================================================================
RAINFALL EXTREMES
======================================================================

,station_id,station_name,date,rainfall_mm,rainfall_3d,rainfall_7d
13290,KN16,Deraniyagala,2018-05-21,119.8,529.7,709.2
12556,KN16,Deraniyagala,2016-05-17,70.4,523.9,785.8
12554,KN16,Deraniyagala,2016-05-15,355.6,521.0,727.9
13291,KN16,Deraniyagala,2018-05-22,18.5,488.2,669.1
22436,KN21,Hanwella,2021-06-04,102.7,486.8,508.5
8002,KN07,Kitulgala,2025-11-28,160.3,484.9,538.2
12555,KN16,Deraniyagala,2016-05-16,97.9,476.3,788.0
4520,KN07,Kitulgala,2016-05-17,66.9,473.3,623.8
16038,KN16,Deraniyagala,2025-11-28,92.9,460.9,566.2
12930,KN16,Deraniyagala,2017-05-26,13.2,450.7,480.3
22933,KN21,Hanwella,2022-10-14,144.1,449.0,462.9
12929,KN16,Deraniyagala,2017-05-25,303.5,445.8,467.7
12020,KN11,Holombuwa,2025-11-28,152.6,434.9,535.9
4519,KN07,Kitulgala,2016-05-16,70.0,429.3,589.4
20966,KN21,Hanwella,2017-05-26,15.3,428.5,445.3
13289,KN16,Deraniyagala,2018-05-20,349.9,413.7,700.6
20965,KN21,Hanwella,2017-05-25,350.4,413.2,430.0
23661,KN21,Hanwella,2024-10-11,125.0,412.8,552.2
23662,KN21,Hanwella,2024-10-12,9.7,410.4,560.7
22435,KN21,Hanwella,2021-06-03,205.8,401.9,411.7

======================================================================
WATER-LEVEL ANOMALIES
======================================================================

      station_id  station_name       date  water_level  wl_zscore
21882       KN07     Kitulgala 2025-11-28    57.437167  14.369815
25900       KN11     Holombuwa 2025-11-28    51.182464  13.320162
29918       KN16  Deraniyagala 2025-11-28    79.884804  12.279337
41975       NSTR      N'Street 2025-12-01     8.322917  11.419187
22417       KN11     Holombuwa 2016-05-16    49.782485  10.246449
38492       NSTR      N'Street 2016-05-19     7.435417   9.915652
41974       NSTR      N'Street 2025-11-30     7.414583   9.880357
38493       NSTR      N'Street 2016-05-20     7.281250   9.654474
9265        KN02       Norwood 2021-05-14  1100.896250   9.463385
22418       KN11     Holombuwa 2016-05-17    49.346261   9.288702
41976       NSTR      N'Street 2025-12-02     6.983333   9.149766
25899       KN11     Holombuwa 2025-11-27    49.182464   8.929077
38491       NSTR      N'Street 2016-05-18     6.787500   8.818000
26435       KN16  Deraniyagala 2016-05-16    78.163416   8.758891
33937       KN18    Glencourse 2025-11-29    20.792417   8.736349
27170       KN16  Deraniyagala 2018-05-21    77.851054   8.120074
41973       NSTR      N'Street 2025-11-29     6.372917   8.115645
33936       KN18    Glencourse 2025-11-28    19.799917   7.963557
23152       KN11     Holombuwa 2018-05-21    48.710657   7.893206
10924       KN02       Norwood 2025-11-28  1100.466667   7.810141

======================================================================
DISCHARGE ANOMALIES
======================================================================

      station_id  station_name       date  discharge_m3s   q_zscore
8002        KN07     Kitulgala 2025-11-28     741.184650  27.177352
12020       KN11     Holombuwa 2025-11-28     454.045039  26.709882
2325        KN02       Norwood 2021-05-14     150.771043  24.572335
3984        KN02       Norwood 2025-11-28     127.347109  20.604985
18016       KN18    Glencourse 2020-04-28    3104.164253  19.223323
8537        KN11     Holombuwa 2016-05-16     319.223174  18.658252
16038       KN16  Deraniyagala 2025-11-28     401.547991  18.351824
17578       KN18    Glencourse 2019-02-15    2919.566344  18.031231
3983        KN02       Norwood 2025-11-27     108.975937  17.493429
8538        KN11     Holombuwa 2016-05-17     259.416706  15.086580
20057       KN18    Glencourse 2025-11-29    2291.171833  13.973198
12019       KN11     Holombuwa 2025-11-27     235.847927  13.679040
2314        KN02       Norwood 2021-05-03      84.674161  13.377398
2337        KN02       Norwood 2021-05-26      82.795419  13.059192
1236        KN02       Norwood 2018-05-21      81.760949  12.883982
20056       KN18    Glencourse 2025-11-28    2022.696079  12.239440
12555       KN16  Deraniyagala 2016-05-16     264.647879  11.785844
9272        KN11     Holombuwa 2018-05-21     201.047583  11.600746
4520        KN07     Kitulgala 2016-05-17     337.461213  11.549616
16573       KN18    Glencourse 2016-05-16    1847.867850  11.110438

In [138]:
# ============================================================
# COMBINE RAINFALL + WATER LEVEL + DISCHARGE
# SIX KELANI STATIONS ONLY
# ============================================================

# Keep only stations that have rainfall + water level + discharge
six_stations = sorted(
    set(rf["station_id"])
    & set(wl["station_id"])
    & set(q["station_id"])
)

print("Stations with all three datasets:")
print(six_stations)

# Select useful columns
rf_features = rf[
    [
        "station_id",
        "station_name",
        "date",
        "rainfall_mm",
        "rainfall_3d",
        "rainfall_7d"
    ]
].copy()

wl_features = wl[
    [
        "station_id",
        "date",
        "water_level",
        "wl_zscore"
    ]
].copy()

q_features = q[
    [
        "station_id",
        "date",
        "discharge_m3s",
        "q_zscore"
    ]
].copy()

# Merge rainfall + water level
hydro = rf_features.merge(
    wl_features,
    on=["station_id", "date"],
    how="left",
    validate="one_to_one"
)

# Merge discharge
hydro = hydro.merge(
    q_features,
    on=["station_id", "date"],
    how="left",
    validate="one_to_one"
)

# Keep only the six complete stations
hydro = hydro[
    hydro["station_id"].isin(six_stations)
].copy()

# Sort
hydro = hydro.sort_values(
    ["station_id", "date"]
).reset_index(drop=True)

print()
print("Combined hydrological dataset shape:", hydro.shape)
print()
print("Columns:")
print(hydro.columns.tolist())
print()
print("Missing values:")
print(hydro.isna().sum())

Stations with all three datasets:
['KN02', 'KN07', 'KN11', 'KN16', 'KN18', 'KN21']

Combined hydrological dataset shape: (24108, 10)

Columns:
['station_id', 'station_name', 'date', 'rainfall_mm', 'rainfall_3d', 'rainfall_7d', 'water_level', 'wl_zscore', 'discharge_m3s', 'q_zscore']

Missing values:
station_id        0
station_name      0
date              0
rainfall_mm       5
rainfall_3d      27
rainfall_7d      71
water_level       0
wl_zscore         0
discharge_m3s     3
q_zscore          3
dtype: int64

In [139]:
# ============================================================
# STATION-SPECIFIC EXTREME THRESHOLD INSPECTION
# ============================================================

print("=" * 70)
print("RAINFALL 3-DAY / 7-DAY EXTREMES")
print("=" * 70)

rainfall_percentiles = (
    hydro.groupby("station_id")
    .agg(
        rainfall_3d_p90=("rainfall_3d", lambda x: x.quantile(0.90)),
        rainfall_3d_p95=("rainfall_3d", lambda x: x.quantile(0.95)),
        rainfall_3d_p99=("rainfall_3d", lambda x: x.quantile(0.99)),
        rainfall_7d_p90=("rainfall_7d", lambda x: x.quantile(0.90)),
        rainfall_7d_p95=("rainfall_7d", lambda x: x.quantile(0.95)),
        rainfall_7d_p99=("rainfall_7d", lambda x: x.quantile(0.99))
    )
)

display(rainfall_percentiles)

print("=" * 70)
print("WATER-LEVEL Z-SCORE DISTRIBUTION")
print("=" * 70)

wl_percentiles = (
    hydro.groupby("station_id")["wl_zscore"]
    .quantile([0.90, 0.95, 0.99])
    .unstack()
)

wl_percentiles.columns = [
    "wl_z_p90",
    "wl_z_p95",
    "wl_z_p99"
]

display(wl_percentiles)

print("=" * 70)
print("DISCHARGE Z-SCORE DISTRIBUTION")
print("=" * 70)

q_percentiles = (
    hydro.groupby("station_id")["q_zscore"]
    .quantile([0.90, 0.95, 0.99])
    .unstack()
)

q_percentiles.columns = [
    "q_z_p90",
    "q_z_p95",
    "q_z_p99"
]

display(q_percentiles)

======================================================================
RAINFALL 3-DAY / 7-DAY EXTREMES
======================================================================

,rainfall_3d_p90,rainfall_3d_p95,rainfall_3d_p99,rainfall_7d_p90,rainfall_7d_p95,rainfall_7d_p99
station_id,,,,,,
KN02,62.87,84.700,144.258,125.77,173.070,250.770
KN07,101.65,132.050,203.270,207.20,258.570,376.991
KN11,77.40,106.150,174.150,156.50,207.045,315.879
KN16,108.08,143.740,230.392,220.22,279.400,422.028
KN18,96.05,129.125,205.100,192.58,252.945,394.000
KN21,76.70,104.975,199.925,158.89,217.325,357.590

======================================================================
WATER-LEVEL Z-SCORE DISTRIBUTION
======================================================================

            wl_z_p90  wl_z_p95  wl_z_p99
station_id
KN02        1.248480  1.867283  3.121648
KN07        1.084974  1.626610  2.865901
KN11        1.189765  1.887941  3.385139
KN16        1.186690  1.795709  3.435598
KN18        1.301472  1.877185  3.251639
KN21        1.352175  2.011167  3.523855

======================================================================
DISCHARGE Z-SCORE DISTRIBUTION
======================================================================

             q_z_p90   q_z_p95   q_z_p99
station_id
KN02        0.737314  1.337900  3.029945
KN07        0.865337  1.452971  3.210498
KN11        0.627612  1.282244  3.494840
KN16        1.010227  1.676963  3.681965
KN18        0.946594  1.524554  3.180159
KN21        1.000811  1.753850  4.077869

In [140]:
# ============================================================
# CREATE STATION-SPECIFIC P95 THRESHOLDS
# ============================================================

thresholds = (
    hydro.groupby("station_id")
    .agg(
        rainfall_3d_p95=("rainfall_3d", lambda x: x.quantile(0.95)),
        rainfall_7d_p95=("rainfall_7d", lambda x: x.quantile(0.95)),
        wl_z_p95=("wl_zscore", lambda x: x.quantile(0.95)),
        q_z_p95=("q_zscore", lambda x: x.quantile(0.95))
    )
    .reset_index()
)

print("Station-specific P95 thresholds:")
display(thresholds)

Station-specific P95 thresholds:

  station_id  rainfall_3d_p95  rainfall_7d_p95  wl_z_p95   q_z_p95
0       KN02           84.700          173.070  1.867283  1.337900
1       KN07          132.050          258.570  1.626610  1.452971
2       KN11          106.150          207.045  1.887941  1.282244
3       KN16          143.740          279.400  1.795709  1.676963
4       KN18          129.125          252.945  1.877185  1.524554
5       KN21          104.975          217.325  2.011167  1.753850

In [141]:
# ============================================================
# ATTACH STATION-SPECIFIC THRESHOLDS
# ============================================================

hydro_thresholded = hydro.merge(
    thresholds,
    on="station_id",
    how="left",
    validate="many_to_one"
)

print("Shape:", hydro_thresholded.shape)

display(
    hydro_thresholded[
        [
            "station_id",
            "date",
            "rainfall_3d",
            "rainfall_3d_p95",
            "rainfall_7d",
            "rainfall_7d_p95",
            "wl_zscore",
            "wl_z_p95",
            "q_zscore",
            "q_z_p95"
        ]
    ].head(15)
)

Shape: (24108, 14)

,station_id,date,rainfall_3d,rainfall_3d_p95,rainfall_7d,rainfall_7d_p95,wl_zscore,wl_z_p95,q_zscore,q_z_p95
0,KN02,2015-01-01,NaN,84.7,NaN,173.07,0.889288,1.867283,0.477316,1.3379
1,KN02,2015-01-02,NaN,84.7,NaN,173.07,0.602255,1.867283,0.205092,1.3379
2,KN02,2015-01-03,0.0,84.7,NaN,173.07,0.695260,1.867283,0.288397,1.3379
3,KN02,2015-01-04,0.0,84.7,NaN,173.07,0.643947,1.867283,0.242113,1.3379
4,KN02,2015-01-05,0.0,84.7,NaN,173.07,0.586220,1.867283,0.190995,1.3379
5,KN02,2015-01-06,1.7,84.7,NaN,173.07,0.549339,1.867283,0.159042,1.3379
6,KN02,2015-01-07,1.7,84.7,1.7,173.07,0.457937,1.867283,0.081988,1.3379
7,KN02,2015-01-08,1.7,84.7,1.7,173.07,0.344086,1.867283,-0.011116,1.3379
8,KN02,2015-01-09,0.0,84.7,1.7,173.07,0.265513,1.867283,-0.072541,1.3379
9,KN02,2015-01-10,0.0,84.7,1.7,173.07,0.198165,1.867283,-0.123959,1.3379
10,KN02,2015-01-11,0.0,84.7,1.7,173.07,0.151662,1.867283,-0.158393,1.3379
11,KN02,2015-01-12,0.0,84.7,1.7,173.07,0.111574,1.867283,-0.187656,1.3379
12,KN02,2015-01-13,0.0,84.7,0.0,173.07,0.031397,1.867283,-0.243863,1.3379
13,KN02,2015-01-14,0.0,84.7,0.0,173.07,-0.031141,1.867283,-0.287179,1.3379
14,KN02,2015-01-15,0.0,84.7,0.0,173.07,-0.051987,1.867283,-0.301187,1.3379

In [142]:
# ============================================================
# IDENTIFY CANDIDATE FLOOD DAYS
# ============================================================

# High accumulated rainfall
hydro_thresholded["rainfall_extreme"] = (
    (hydro_thresholded["rainfall_3d"] >= hydro_thresholded["rainfall_3d_p95"])
    |
    (hydro_thresholded["rainfall_7d"] >= hydro_thresholded["rainfall_7d_p95"])
)

# Strong river response
hydro_thresholded["river_response_extreme"] = (
    (hydro_thresholded["wl_zscore"] >= hydro_thresholded["wl_z_p95"])
    |
    (hydro_thresholded["q_zscore"] >= hydro_thresholded["q_z_p95"])
)

# Candidate flood condition
hydro_thresholded["candidate_flood_day"] = (
    hydro_thresholded["rainfall_extreme"]
    &
    hydro_thresholded["river_response_extreme"]
)

print("Candidate flood days:")
print(
    hydro_thresholded["candidate_flood_day"]
    .value_counts(dropna=False)
)

print()
print("Candidate days by station:")
display(
    hydro_thresholded
    .groupby("station_id")["candidate_flood_day"]
    .agg(["count", "sum"])
)

Candidate flood days:
candidate_flood_day
False    23325
True       783
Name: count, dtype: int64

Candidate days by station:

            count  sum
station_id
KN02         4018  119
KN07         4018  115
KN11         4018  150
KN16         4018  132
KN18         4018  129
KN21         4018  138

In [143]:
# ============================================================
# INSPECT CANDIDATE FLOOD DAYS
# ============================================================

candidate_days = (
    hydro_thresholded[
        hydro_thresholded["candidate_flood_day"] == True
    ]
    .sort_values(["date", "station_id"])
)

display(
    candidate_days[
        [
            "station_id",
            "station_name",
            "date",
            "rainfall_mm",
            "rainfall_3d",
            "rainfall_7d",
            "wl_zscore",
            "q_zscore"
        ]
    ].head(100)
)

,station_id,station_name,date,rainfall_mm,rainfall_3d,rainfall_7d,wl_zscore,q_zscore
12209,KN16,Deraniyagala,2015-06-05,80.8,154.1,248.1,1.836118,2.146417
4303,KN07,Kitulgala,2015-10-13,130.1,174.1,232.9,1.083904,2.532219
16363,KN18,Glencourse,2015-10-19,22.4,200.7,286.1,2.426447,2.218084
20381,KN21,Hanwella,2015-10-19,41.5,144.7,197.8,2.755908,2.848592
292,KN02,Norwood,2015-10-20,40.2,83.4,223.0,2.308416,1.933270
...,...,...,...,...,...,...,...,...
4900,KN07,Kitulgala,2017-06-01,58.7,148.2,269.7,1.682372,1.699354
12937,KN16,Deraniyagala,2017-06-02,69.8,151.5,324.1,2.556494,2.622397
12938,KN16,Deraniyagala,2017-06-03,4.7,129.1,324.7,2.184964,2.171267
13034,KN16,Deraniyagala,2017-09-07,43.5,209.5,280.7,3.707726,4.368024
17052,KN18,Glencourse,2017-09-07,30.6,156.5,228.1,2.848269,2.881243

In [144]:
import pandas as pd

candidate = (
    hydro_thresholded[
        hydro_thresholded["candidate_flood_day"] == True
    ]
    .copy()
)

candidate["date"] = pd.to_datetime(candidate["date"])

candidate = candidate.sort_values(
    ["station_id", "date"]
).reset_index(drop=True)

# Calculate the gap between consecutive candidate days
candidate["gap_days"] = (
    candidate.groupby("station_id")["date"]
    .diff()
    .dt.days
)

# Start a new episode if the gap is greater than 2 days.
# This allows a 1-day non-candidate gap inside an episode.
candidate["new_event"] = (
    candidate["gap_days"].isna()
    | (candidate["gap_days"] > 2)
)

# Create station-specific event IDs
candidate["event_number"] = (
    candidate.groupby("station_id")["new_event"]
    .cumsum()
)

candidate["event_id"] = (
    candidate["station_id"]
    + "_E"
    + candidate["event_number"].astype(str).str.zfill(3)
)

candidate.head(20)

,station_id,station_name,date,rainfall_mm,rainfall_3d,rainfall_7d,water_level,wl_zscore,discharge_m3s,q_zscore,...,rainfall_7d_p95,wl_z_p95,q_z_p95,rainfall_extreme,river_response_extreme,candidate_flood_day,gap_days,new_event,event_number,event_id
0,KN02,Norwood,2015-10-20,40.2,83.4,223.0,1099.037083,2.308416,17.106015,1.933270,...,173.07,1.867283,1.3379,True,True,True,NaN,True,1,KN02_E001
1,KN02,Norwood,2015-10-21,13.7,59.5,202.3,1099.060417,2.398214,17.252831,1.958137,...,173.07,1.867283,1.3379,True,True,True,1.0,False,1,KN02_E001
2,KN02,Norwood,2015-10-22,6.3,60.2,173.7,1099.013750,2.218618,15.693000,1.693946,...,173.07,1.867283,1.3379,True,True,True,1.0,False,1,KN02_E001
3,KN02,Norwood,2016-05-15,97.1,146.6,205.5,1099.340833,3.477392,28.743669,3.904359,...,173.07,1.867283,1.3379,True,True,True,206.0,True,2,KN02_E002
4,KN02,Norwood,2016-05-16,35.4,170.2,210.9,1099.491667,4.057871,31.349275,4.345675,...,173.07,1.867283,1.3379,True,True,True,1.0,False,2,KN02_E002
5,KN02,Norwood,2016-05-17,68.6,201.1,269.4,1099.453333,3.910346,31.704943,4.405915,...,173.07,1.867283,1.3379,True,True,True,1.0,False,2,KN02_E002
6,KN02,Norwood,2016-05-18,17.1,121.1,269.9,1099.350417,3.514273,26.291303,3.488998,...,173.07,1.867283,1.3379,True,True,True,1.0,False,2,KN02_E002
7,KN02,Norwood,2016-05-19,45.0,130.7,312.7,1099.087083,2.500840,17.424065,1.987139,...,173.07,1.867283,1.3379,True,True,True,1.0,False,2,KN02_E002
8,KN02,Norwood,2016-05-20,2.7,64.8,303.6,1099.140000,2.704489,19.061903,2.264542,...,173.07,1.867283,1.3379,True,True,True,1.0,False,2,KN02_E002
9,KN02,Norwood,2017-05-26,22.9,170.4,170.4,1099.248750,3.123011,24.646256,3.210373,...,173.07,1.867283,1.3379,True,True,True,371.0,True,3,KN02_E003
10,KN02,Norwood,2017-05-30,42.3,107.5,281.3,1098.953333,1.986105,14.477822,1.488129,...,173.07,1.867283,1.3379,True,True,True,4.0,True,4,KN02_E004
11,KN02,Norwood,2017-05-31,13.2,114.7,226.7,1098.926250,1.881876,13.451150,1.314240,...,173.07,1.867283,1.3379,True,True,True,1.0,False,4,KN02_E004
12,KN02,Norwood,2017-10-14,85.8,149.1,153.1,1099.021667,2.249085,17.402109,1.983420,...,173.07,1.867283,1.3379,True,True,True,136.0,True,5,KN02_E005
13,KN02,Norwood,2017-10-15,18.6,159.1,169.1,1098.943333,1.947620,13.848128,1.381477,...,173.07,1.867283,1.3379,True,True,True,1.0,False,5,KN02_E005
14,KN02,Norwood,2017-11-30,24.1,86.5,109.4,1099.785417,5.188363,58.178560,8.889795,...,173.07,1.867283,1.3379,True,True,True,46.0,True,6,KN02_E006
15,KN02,Norwood,2017-12-01,13.9,94.6,122.1,1099.260417,3.167910,22.796988,2.897160,...,173.07,1.867283,1.3379,True,True,True,1.0,False,6,KN02_E006
16,KN02,Norwood,2018-05-21,43.4,169.5,234.6,1100.072500,6.293198,81.760949,12.883982,...,173.07,1.867283,1.3379,True,True,True,171.0,True,7,KN02_E007
17,KN02,Norwood,2018-05-22,2.6,171.3,236.6,1099.269583,3.203188,23.699246,3.049977,...,173.07,1.867283,1.3379,True,True,True,1.0,False,7,KN02_E007
18,KN02,Norwood,2018-05-23,44.1,90.1,225.3,1099.176667,2.845600,20.420665,2.494678,...,173.07,1.867283,1.3379,True,True,True,1.0,False,7,KN02_E007
19,KN02,Norwood,2018-05-24,24.5,71.2,249.8,1099.023750,2.257103,15.925685,1.733356,...,173.07,1.867283,1.3379,True,True,True,1.0,False,7,KN02_E007

In [145]:
print("Candidate station-days:", len(candidate))

print(
    "Candidate flood episodes:",
    candidate["event_id"].nunique()
)

print("\nEvents by station:")
print(
    candidate.groupby("station_id")["event_id"]
    .nunique()
)

Candidate station-days: 783
Candidate flood episodes: 270

Events by station:
station_id
KN02    40
KN07    42
KN11    56
KN16    51
KN18    43
KN21    38
Name: event_id, dtype: int64

In [146]:
# Create a compact event table
station_events = (
    candidate
    .groupby(["station_id", "event_id"])
    .agg(
        start_date=("date", "min"),
        end_date=("date", "max"),
        candidate_days=("date", "count"),
        max_rainfall_3d=("rainfall_3d", "max"),
        max_rainfall_7d=("rainfall_7d", "max"),
        max_wl_zscore=("wl_zscore", "max"),
        max_q_zscore=("q_zscore", "max")
    )
    .reset_index()
)

station_events["duration_days"] = (
    station_events["end_date"]
    - station_events["start_date"]
).dt.days + 1

station_events.sort_values("start_date").head(30)

,station_id,event_id,start_date,end_date,candidate_days,max_rainfall_3d,max_rainfall_7d,max_wl_zscore,max_q_zscore,duration_days
138,KN16,KN16_E001,2015-06-05,2015-06-05,1,154.1,248.1,1.836118,2.146417,1
40,KN07,KN07_E001,2015-10-13,2015-10-13,1,174.1,232.9,1.083904,2.532219,1
232,KN21,KN21_E001,2015-10-19,2015-10-21,2,144.7,240.7,2.755908,2.848592,3
189,KN18,KN18_E001,2015-10-19,2015-10-21,2,200.7,332.9,2.426447,2.218084,3
0,KN02,KN02_E001,2015-10-20,2015-10-22,3,83.4,223.0,2.398214,1.958137,3
233,KN21,KN21_E002,2015-10-24,2015-10-24,1,76.0,256.8,2.233775,2.066336,1
190,KN18,KN18_E002,2015-10-24,2015-10-24,1,81.1,284.9,2.290485,2.000723,1
82,KN11,KN11_E001,2015-11-02,2015-11-03,2,130.1,188.8,2.796370,3.501046,2
41,KN07,KN07_E002,2015-11-06,2015-11-07,2,182.8,227.2,0.876419,2.030471,2
83,KN11,KN11_E002,2015-11-13,2015-11-14,2,119.6,154.1,3.052885,2.744790,2
84,KN11,KN11_E003,2015-12-01,2015-12-01,1,117.2,117.2,2.698783,2.245964,1
85,KN11,KN11_E004,2015-12-14,2015-12-14,1,119.5,173.3,4.664466,5.546578,1
191,KN18,KN18_E003,2016-05-12,2016-05-22,11,376.5,600.0,7.542572,11.110438,11
234,KN21,KN21_E003,2016-05-12,2016-05-12,1,160.5,190.7,2.255555,2.085656,1
86,KN11,KN11_E005,2016-05-15,2016-05-21,7,391.6,496.6,10.246449,18.658252,7
139,KN16,KN16_E002,2016-05-15,2016-05-21,7,523.9,884.8,8.758891,11.785844,7
1,KN02,KN02_E002,2016-05-15,2016-05-20,6,201.1,312.7,4.057871,4.405915,6
235,KN21,KN21_E004,2016-05-16,2016-05-24,9,227.3,392.6,5.992836,9.515839,9
42,KN07,KN07_E003,2016-05-16,2016-05-20,4,473.3,708.4,7.109103,11.549616,5
140,KN16,KN16_E003,2016-05-25,2016-05-28,3,178.4,279.4,3.048999,3.140951,4
236,KN21,KN21_E005,2016-05-28,2016-05-31,3,199.5,293.7,3.168542,3.472260,4
141,KN16,KN16_E004,2017-05-24,2017-06-03,9,450.7,623.3,6.921974,9.254390,11
192,KN18,KN18_E004,2017-05-25,2017-05-27,3,325.3,400.0,5.441438,7.027346,3
43,KN07,KN07_E004,2017-05-26,2017-05-26,1,204.4,256.0,2.745737,3.424846,1
2,KN02,KN02_E003,2017-05-26,2017-05-26,1,170.4,170.4,3.123011,3.210373,1
237,KN21,KN21_E006,2017-05-26,2017-05-31,6,428.5,489.4,5.112668,7.375819,6
44,KN07,KN07_E005,2017-05-30,2017-06-01,3,148.2,369.3,2.194603,2.438800,3
87,KN11,KN11_E006,2017-05-30,2017-05-30,1,86.7,240.2,2.827040,2.238489,1
3,KN02,KN02_E004,2017-05-30,2017-05-31,2,114.7,281.3,1.986105,1.488129,2
193,KN18,KN18_E005,2017-05-30,2017-05-31,2,104.9,422.6,2.766188,2.476004,2

In [147]:
# For each date, count how many different stations
# have candidate flood conditions
daily_station_overlap = (
    candidate.groupby("date")["station_id"]
    .nunique()
    .reset_index(name="candidate_station_count")
)

daily_station_overlap.sort_values(
    "candidate_station_count",
    ascending=False
).head(30)

          date  candidate_station_count
39  2017-05-30                        6
334 2025-11-27                        6
20  2016-05-17                        6
19  2016-05-16                        6
132 2021-05-26                        6
131 2021-05-25                        6
310 2024-11-27                        6
162 2021-11-08                        6
62  2018-05-25                        6
23  2016-05-20                        6
21  2016-05-18                        6
335 2025-11-28                        6
336 2025-11-29                        6
337 2025-11-30                        6
59  2018-05-22                        6
58  2018-05-21                        6
163 2021-11-09                        6
141 2021-06-09                        5
140 2021-06-08                        5
164 2021-11-10                        5
40  2017-05-31                        5
60  2018-05-23                        5
280 2024-05-23                        5
137 2021-06-05                        5
189 2022-05-31                        5
128 2021-05-15                        5
299 2024-10-11                        5
127 2021-05-14                        5
281 2024-05-24                        5
282 2024-05-25                        5

In [148]:
candidate[
    candidate["date"].between(
        "2017-05-20",
        "2017-06-05"
    )
][
    [
        "station_id",
        "station_name",
        "date",
        "rainfall_mm",
        "rainfall_3d",
        "rainfall_7d",
        "wl_zscore",
        "q_zscore"
    ]
].sort_values(
    ["date", "station_id"]
)

,station_id,station_name,date,rainfall_mm,rainfall_3d,rainfall_7d,wl_zscore,q_zscore
395,KN16,Deraniyagala,2017-05-24,134.0,152.6,183.8,2.245465,2.590216
396,KN16,Deraniyagala,2017-05-25,303.5,445.8,467.7,2.088673,2.078180
530,KN18,Glencourse,2017-05-25,245.9,325.3,384.1,1.958033,1.598222
9,KN02,Norwood,2017-05-26,22.9,170.4,170.4,3.123011,3.210373
126,KN07,Kitulgala,2017-05-26,9.5,204.4,256.0,2.745737,3.424846
397,KN16,Deraniyagala,2017-05-26,13.2,450.7,480.3,6.921974,9.254390
531,KN18,Glencourse,2017-05-26,14.0,315.5,397.8,5.441438,7.027346
661,KN21,Hanwella,2017-05-26,15.3,428.5,445.3,4.629024,6.522164
398,KN16,Deraniyagala,2017-05-27,4.1,320.8,474.0,2.562459,2.614815
532,KN18,Glencourse,2017-05-27,2.2,262.1,400.0,3.800146,4.170556
662,KN21,Hanwella,2017-05-27,1.0,366.7,438.8,5.112668,7.375819
663,KN21,Hanwella,2017-05-28,19.2,35.5,456.9,3.525681,4.122253
399,KN16,Deraniyagala,2017-05-29,65.5,111.1,570.1,1.788722,1.733938
664,KN21,Hanwella,2017-05-29,19.3,39.5,468.0,2.465303,2.375072
10,KN02,Norwood,2017-05-30,42.3,107.5,281.3,1.986105,1.488129
127,KN07,Kitulgala,2017-05-30,42.9,141.0,359.3,2.194603,2.438800
247,KN11,Holombuwa,2017-05-30,18.5,86.7,240.2,2.827040,2.238489
400,KN16,Deraniyagala,2017-05-30,61.5,168.5,623.3,3.131684,3.335923
533,KN18,Glencourse,2017-05-30,26.6,104.9,422.6,2.766188,2.476004
665,KN21,Hanwella,2017-05-30,21.4,59.9,489.4,2.898823,3.039911
11,KN02,Norwood,2017-05-31,13.2,114.7,226.7,1.881876,1.314240
128,KN07,Kitulgala,2017-05-31,46.6,146.3,369.3,1.513789,1.456104
401,KN16,Deraniyagala,2017-05-31,27.1,154.1,516.4,2.622961,2.695934
534,KN18,Glencourse,2017-05-31,10.6,77.9,377.6,2.322043,1.970292
666,KN21,Hanwella,2017-05-31,22.2,62.9,448.8,2.760085,2.821088
129,KN07,Kitulgala,2017-06-01,58.7,148.2,269.7,1.682372,1.699354
402,KN16,Deraniyagala,2017-06-02,69.8,151.5,324.1,2.556494,2.622397
403,KN16,Deraniyagala,2017-06-03,4.7,129.1,324.7,2.184964,2.171267

In [149]:
candidate[
    candidate["date"].between(
        "2018-05-15",
        "2018-05-30"
    )
][
    [
        "station_id",
        "station_name",
        "date",
        "rainfall_mm",
        "rainfall_3d",
        "rainfall_7d",
        "wl_zscore",
        "q_zscore"
    ]
].sort_values(
    ["date", "station_id"]
)

,station_id,station_name,date,rainfall_mm,rainfall_3d,rainfall_7d,wl_zscore,q_zscore
412,KN16,Deraniyagala,2018-05-16,111.7,281.5,431.7,1.782757,1.754869
132,KN07,Kitulgala,2018-05-20,206.7,265.8,323.7,1.769905,2.070255
250,KN11,Holombuwa,2018-05-20,151.4,172.8,236.9,3.207630,3.892324
413,KN16,Deraniyagala,2018-05-20,349.9,413.7,700.6,4.593945,6.192023
540,KN18,Glencourse,2018-05-20,95.5,151.5,221.3,1.774730,1.553972
16,KN02,Norwood,2018-05-21,43.4,169.5,234.6,6.293198,12.883982
133,KN07,Kitulgala,2018-05-21,79.6,331.3,389.8,5.271231,7.635273
251,KN11,Holombuwa,2018-05-21,68.6,238.8,285.9,7.893206,11.600746
414,KN16,Deraniyagala,2018-05-21,119.8,529.7,709.2,8.120074,10.686408
541,KN18,Glencourse,2018-05-21,46.0,172.3,246.0,5.805124,7.463404
672,KN21,Hanwella,2018-05-21,19.7,157.0,196.6,4.364078,5.734040
17,KN02,Norwood,2018-05-22,2.6,171.3,236.6,3.203188,3.049977
134,KN07,Kitulgala,2018-05-22,16.8,303.1,387.8,1.722896,1.738030
252,KN11,Holombuwa,2018-05-22,30.9,250.9,313.2,3.154654,2.604904
415,KN16,Deraniyagala,2018-05-22,18.5,488.2,669.1,3.358352,3.492717
542,KN18,Glencourse,2018-05-22,22.2,163.7,236.8,5.222772,6.465551
673,KN21,Hanwella,2018-05-22,29.7,136.8,226.3,4.898743,6.864322
18,KN02,Norwood,2018-05-23,44.1,90.1,225.3,2.845600,2.494678
253,KN11,Holombuwa,2018-05-23,14.7,114.2,287.0,2.500820,1.720407
416,KN16,Deraniyagala,2018-05-23,62.5,200.8,619.9,2.994491,3.063864
543,KN18,Glencourse,2018-05-23,77.8,146.0,297.5,3.048442,2.929046
674,KN21,Hanwella,2018-05-23,34.0,83.4,250.9,4.020365,5.022058
19,KN02,Norwood,2018-05-24,24.5,71.2,249.8,2.257103,1.733356
417,KN16,Deraniyagala,2018-05-24,147.5,228.5,762.0,2.188372,2.052744
544,KN18,Glencourse,2018-05-24,120.8,220.8,418.3,2.522217,2.213592
675,KN21,Hanwella,2018-05-24,26.0,89.7,276.5,3.449002,3.978882
20,KN02,Norwood,2018-05-25,2.1,70.7,242.8,1.883479,1.308297
135,KN07,Kitulgala,2018-05-25,5.7,118.4,466.5,1.636984,1.637378
254,KN11,Holombuwa,2018-05-25,26.9,149.1,418.8,5.664037,6.823423
418,KN16,Deraniyagala,2018-05-25,26.2,236.2,784.4,3.055844,3.123310
545,KN18,Glencourse,2018-05-25,14.9,213.5,408.0,3.774841,4.007755
676,KN21,Hanwella,2018-05-25,16.8,76.8,263.5,3.638164,4.323558
255,KN11,Holombuwa,2018-05-26,43.2,177.6,443.2,3.146289,2.579591
546,KN18,Glencourse,2018-05-26,44.8,180.5,422.0,2.895635,2.739375
677,KN21,Hanwella,2018-05-26,25.0,67.8,238.6,3.621754,4.282264
256,KN11,Holombuwa,2018-05-27,10.4,80.5,302.2,2.432509,1.623576
547,KN18,Glencourse,2018-05-27,8.7,68.4,335.2,2.038816,1.663807

In [150]:
candidate[
    candidate["date"].between(
        "2025-11-25",
        "2025-12-05"
    )
][
    [
        "station_id",
        "station_name",
        "date",
        "rainfall_mm",
        "rainfall_3d",
        "rainfall_7d",
        "wl_zscore",
        "q_zscore"
    ]
].sort_values(
    ["date", "station_id"]
)

,station_id,station_name,date,rainfall_mm,rainfall_3d,rainfall_7d,wl_zscore,q_zscore
113,KN02,Norwood,2025-11-26,92.0,126.6,212.5,2.045436,1.510172
379,KN11,Holombuwa,2025-11-26,121.9,150.8,234.3,2.240904,1.571075
114,KN02,Norwood,2025-11-27,150.6,258.6,358.4,7.135054,17.493429
228,KN07,Kitulgala,2025-11-27,231.3,347.0,417.2,5.407393,8.177135
380,KN11,Holombuwa,2025-11-27,160.4,302.9,394.7,8.929077,13.679040
512,KN16,Deraniyagala,2025-11-27,251.5,383.1,511.7,4.876854,5.855320
640,KN18,Glencourse,2025-11-27,215.1,291.4,349.5,3.580507,3.792658
776,KN21,Hanwella,2025-11-27,193.8,246.2,342.9,2.511251,2.604188
115,KN02,Norwood,2025-11-28,73.5,316.1,425.4,7.810141,20.604985
229,KN07,Kitulgala,2025-11-28,160.3,484.9,538.2,14.369815,27.177352
381,KN11,Holombuwa,2025-11-28,152.6,434.9,535.9,13.320162,26.709882
513,KN16,Deraniyagala,2025-11-28,92.9,460.9,566.2,12.279337,18.351824
641,KN18,Glencourse,2025-11-28,102.6,379.6,429.9,7.963557,12.239440
777,KN21,Hanwella,2025-11-28,41.6,283.6,358.3,5.257970,7.765196
116,KN02,Norwood,2025-11-29,2.3,226.4,402.9,4.155687,4.494550
230,KN07,Kitulgala,2025-11-29,2.0,393.6,534.0,5.918003,6.833368
382,KN11,Holombuwa,2025-11-29,0.3,313.3,508.1,6.663093,9.363782
514,KN16,Deraniyagala,2025-11-29,0.7,345.1,562.2,3.868780,4.172229
642,KN18,Glencourse,2025-11-29,0.0,317.7,419.7,8.736349,13.973198
778,KN21,Hanwella,2025-11-29,0.0,235.4,345.3,6.489608,10.855428
117,KN02,Norwood,2025-11-30,0.0,75.8,353.0,2.949829,2.568109
231,KN07,Kitulgala,2025-11-30,0.0,162.3,524.7,3.676182,3.558107
383,KN11,Holombuwa,2025-11-30,0.0,152.9,464.1,2.927011,2.230747
515,KN16,Deraniyagala,2025-11-30,0.0,93.6,554.4,2.086969,1.940192
643,KN18,Glencourse,2025-11-30,0.0,102.6,403.6,5.906021,7.754972
779,KN21,Hanwella,2025-11-30,0.0,41.6,315.4,6.482746,10.836417
118,KN02,Norwood,2025-12-01,0.0,2.3,334.4,2.247481,1.687955
232,KN07,Kitulgala,2025-12-01,0.0,2.0,509.3,2.478275,2.178574
644,KN18,Glencourse,2025-12-01,0.0,0.0,394.0,2.485231,2.213478
780,KN21,Hanwella,2025-12-01,0.0,0.0,287.8,5.366276,7.978467
233,KN07,Kitulgala,2025-12-02,0.0,0.0,486.9,1.833123,1.490838
781,KN21,Hanwella,2025-12-02,0.0,0.0,283.6,4.021857,5.042583
782,KN21,Hanwella,2025-12-03,0.0,0.0,235.4,2.613888,2.613218

In [152]:
from pathlib import Path

project_root = Path("/Users/ohaseelanka/disaster_analytics_hub")

# Search for files related to flood events
matches = list(project_root.rglob("*event*"))

for path in matches:
    print(path)

In [153]:
import pandas as pd
from pathlib import Path

project_root = Path("/Users/ohaseelanka/disaster_analytics_hub")

rf_path = project_root / "data/interim/flood/rainfall_daily_long.parquet"
wl_path = project_root / "data/interim/flood/water_level_daily.parquet"
q_path = project_root / "data/interim/flood/discharge_daily.parquet"

rf = pd.read_parquet(rf_path)
wl = pd.read_parquet(wl_path)
q = pd.read_parquet(q_path)

print("Rainfall:", rf.shape)
print("Water level:", wl.shape)
print("Discharge:", q.shape)

print("\nRainfall columns:")
print(rf.columns.tolist())

print("\nWater level columns:")
print(wl.columns.tolist())

print("\nDischarge columns:")
print(q.columns.tolist())

Rainfall: (24108, 4)
Water level: (42006, 5)
Discharge: (24108, 4)

Rainfall columns:
['station_id', 'station_name', 'date', 'rainfall_mm']

Water level columns:
['station_id', 'station_name', 'date', 'water_level', 'unit']

Discharge columns:
['station_id', 'station_name', 'date', 'discharge_m3s']

In [154]:
# Make copies so the original cleaned datasets remain unchanged

rf = rf.copy()
wl = wl.copy()
q = q.copy()

# Make sure dates are datetime
rf["date"] = pd.to_datetime(rf["date"])
wl["date"] = pd.to_datetime(wl["date"])
q["date"] = pd.to_datetime(q["date"])

# Sort chronologically within each station
rf = rf.sort_values(["station_id", "date"]).reset_index(drop=True)
wl = wl.sort_values(["station_id", "date"]).reset_index(drop=True)
q = q.sort_values(["station_id", "date"]).reset_index(drop=True)

# --------------------------------------------------
# RAINFALL: 3-day and 7-day accumulated rainfall
# --------------------------------------------------

rf["rainfall_3d"] = (
    rf.groupby("station_id")["rainfall_mm"]
      .transform(lambda x: x.rolling(3, min_periods=3).sum())
)

rf["rainfall_7d"] = (
    rf.groupby("station_id")["rainfall_mm"]
      .transform(lambda x: x.rolling(7, min_periods=7).sum())
)

# --------------------------------------------------
# WATER LEVEL: station-relative z-score
# --------------------------------------------------

wl["wl_mean"] = (
    wl.groupby("station_id")["water_level"]
      .transform("mean")
)

wl["wl_std"] = (
    wl.groupby("station_id")["water_level"]
      .transform("std")
)

wl["wl_zscore"] = (
    (wl["water_level"] - wl["wl_mean"]) / wl["wl_std"]
)

# --------------------------------------------------
# DISCHARGE: station-relative z-score
# --------------------------------------------------

q["q_mean"] = (
    q.groupby("station_id")["discharge_m3s"]
      .transform("mean")
)

q["q_std"] = (
    q.groupby("station_id")["discharge_m3s"]
      .transform("std")
)

q["q_zscore"] = (
    (q["discharge_m3s"] - q["q_mean"]) / q["q_std"]
)

# --------------------------------------------------
# Display results
# --------------------------------------------------

print("Rainfall features:", rf.shape)
print("Water-level features:", wl.shape)
print("Discharge features:", q.shape)

print("\nRainfall columns:")
print(rf.columns.tolist())

print("\nWater-level columns:")
print(wl.columns.tolist())

print("\nDischarge columns:")
print(q.columns.tolist())

Rainfall features: (24108, 6)
Water-level features: (42006, 8)
Discharge features: (24108, 7)

Rainfall columns:
['station_id', 'station_name', 'date', 'rainfall_mm', 'rainfall_3d', 'rainfall_7d']

Water-level columns:
['station_id', 'station_name', 'date', 'water_level', 'unit', 'wl_mean', 'wl_std', 'wl_zscore']

Discharge columns:
['station_id', 'station_name', 'date', 'discharge_m3s', 'q_mean', 'q_std', 'q_zscore']

In [156]:
# Calculate station-specific P95 thresholds

rainfall_thresholds = (
    rf.groupby("station_id")[["rainfall_3d", "rainfall_7d"]]
      .quantile(0.95)
      .reset_index()
      .rename(columns={
          "rainfall_3d": "rainfall_3d_p95",
          "rainfall_7d": "rainfall_7d_p95"
      })
)

wl_thresholds = (
    wl[wl["station_id"].isin(
        ["KN02", "KN07", "KN11", "KN16", "KN18", "KN21"]
    )]
    .groupby("station_id")["wl_zscore"]
    .quantile(0.95)
    .reset_index()
    .rename(columns={"wl_zscore": "wl_zscore_p95"})
)

q_thresholds = (
    q.groupby("station_id")["q_zscore"]
     .quantile(0.95)
     .reset_index()
     .rename(columns={"q_zscore": "q_zscore_p95"})
)

# Display the thresholds

print("RAINFALL P95 THRESHOLDS")
display(rainfall_thresholds)

print("\nWATER LEVEL P95 THRESHOLDS")
display(wl_thresholds)

print("\nDISCHARGE P95 THRESHOLDS")
display(q_thresholds)

RAINFALL P95 THRESHOLDS

  station_id  rainfall_3d_p95  rainfall_7d_p95
0       KN02           84.700          173.070
1       KN07          132.050          258.570
2       KN11          106.150          207.045
3       KN16          143.740          279.400
4       KN18          129.125          252.945
5       KN21          104.975          217.325

WATER LEVEL P95 THRESHOLDS

  station_id  wl_zscore_p95
0       KN02       1.942522
1       KN07       1.737503
2       KN11       1.887941
3       KN16       1.795709
4       KN18       1.877185
5       KN21       2.011167

DISCHARGE P95 THRESHOLDS

  station_id  q_zscore_p95
0       KN02      1.337900
1       KN07      1.452971
2       KN11      1.282244
3       KN16      1.676963
4       KN18      1.524554
5       KN21      1.753850

In [157]:
# Use only the six Kelani stations that have
# rainfall + water level + discharge data

six_stations = sorted(
    set(rf["station_id"])
    & set(wl["station_id"])
    & set(q["station_id"])
)

print("Six common stations:")
print(six_stations)

# Keep only the six common stations
rf_six = rf[rf["station_id"].isin(six_stations)].copy()
wl_six = wl[wl["station_id"].isin(six_stations)].copy()
q_six = q[q["station_id"].isin(six_stations)].copy()

# Select only the required columns
rf_six = rf_six[
    [
        "station_id",
        "station_name",
        "date",
        "rainfall_mm",
        "rainfall_3d",
        "rainfall_7d"
    ]
]

wl_six = wl_six[
    [
        "station_id",
        "date",
        "water_level",
        "wl_zscore"
    ]
]

q_six = q_six[
    [
        "station_id",
        "date",
        "discharge_m3s",
        "q_zscore"
    ]
]

# Merge rainfall + water level
hydro = rf_six.merge(
    wl_six,
    on=["station_id", "date"],
    how="inner",
    validate="one_to_one"
)

# Add discharge
hydro = hydro.merge(
    q_six,
    on=["station_id", "date"],
    how="inner",
    validate="one_to_one"
)

hydro = hydro.sort_values(
    ["station_id", "date"]
).reset_index(drop=True)

print("\nCombined hydrology shape:", hydro.shape)

print("\nColumns:")
print(hydro.columns.tolist())

print("\nMissing values:")
display(hydro.isna().sum())

print("\nFirst 10 rows:")
display(hydro.head(10))

Six common stations:
['KN02', 'KN07', 'KN11', 'KN16', 'KN18', 'KN21']

Combined hydrology shape: (24108, 10)

Columns:
['station_id', 'station_name', 'date', 'rainfall_mm', 'rainfall_3d', 'rainfall_7d', 'water_level', 'wl_zscore', 'discharge_m3s', 'q_zscore']

Missing values:

station_id        0
station_name      0
date              0
rainfall_mm       5
rainfall_3d      27
rainfall_7d      71
water_level       0
wl_zscore         0
discharge_m3s     3
q_zscore          3
dtype: int64

First 10 rows:

,station_id,station_name,date,rainfall_mm,rainfall_3d,rainfall_7d,water_level,wl_zscore,discharge_m3s,q_zscore
0,KN02,Norwood,2015-01-01,0.0,NaN,NaN,1098.668333,1.009706,8.509801,0.477316
1,KN02,Norwood,2015-01-02,0.0,NaN,NaN,1098.593750,0.737229,6.902546,0.205092
2,KN02,Norwood,2015-01-03,0.0,0.0,NaN,1098.617917,0.825518,7.394394,0.288397
3,KN02,Norwood,2015-01-04,0.0,0.0,NaN,1098.604583,0.776807,7.121124,0.242113
4,KN02,Norwood,2015-01-05,0.0,0.0,NaN,1098.589583,0.722007,6.819315,0.190995
5,KN02,Norwood,2015-01-06,1.7,1.7,NaN,1098.580000,0.686996,6.630659,0.159042
6,KN02,Norwood,2015-01-07,0.0,1.7,1.7,1098.556250,0.600229,6.175714,0.081988
7,KN02,Norwood,2015-01-08,0.0,1.7,1.7,1098.526667,0.492152,5.626016,-0.011116
8,KN02,Norwood,2015-01-09,0.0,0.0,1.7,1098.506250,0.417563,5.263352,-0.072541
9,KN02,Norwood,2015-01-10,0.0,0.0,1.7,1098.488750,0.353630,4.959773,-0.123959

In [158]:
# --------------------------------------------------
# STEP 7: DETECT CANDIDATE FLOOD DAYS
# --------------------------------------------------

# Merge station-specific thresholds into the hydrology dataset

hydro = hydro.merge(
    rainfall_thresholds,
    on="station_id",
    how="left",
    validate="many_to_one"
)

hydro = hydro.merge(
    wl_thresholds,
    on="station_id",
    how="left",
    validate="many_to_one"
)

hydro = hydro.merge(
    q_thresholds,
    on="station_id",
    how="left",
    validate="many_to_one"
)

# --------------------------------------------------
# Rainfall extreme
# --------------------------------------------------

hydro["rainfall_extreme"] = (
    (hydro["rainfall_3d"] >= hydro["rainfall_3d_p95"]) |
    (hydro["rainfall_7d"] >= hydro["rainfall_7d_p95"])
)

# --------------------------------------------------
# River-response extreme
# --------------------------------------------------

hydro["river_response_extreme"] = (
    (hydro["wl_zscore"] >= hydro["wl_zscore_p95"]) |
    (hydro["q_zscore"] >= hydro["q_zscore_p95"])
)

# --------------------------------------------------
# Candidate flood day
# --------------------------------------------------

hydro["candidate_flood_day"] = (
    hydro["rainfall_extreme"] &
    hydro["river_response_extreme"]
)

# --------------------------------------------------
# Basic results
# --------------------------------------------------

print("Hydrology shape:", hydro.shape)

print("\nCandidate flood-day counts:")
print(
    hydro["candidate_flood_day"]
    .value_counts(dropna=False)
)

print("\nNumber of candidate station-days:")
print(
    hydro["candidate_flood_day"].sum()
)

print("\nCandidate station-days by station:")
display(
    hydro[hydro["candidate_flood_day"]]
    .groupby("station_id")
    .size()
    .reset_index(name="candidate_days")
)

print("\nSample candidate days:")
display(
    hydro[hydro["candidate_flood_day"]]
    [
        [
            "station_id",
            "station_name",
            "date",
            "rainfall_3d",
            "rainfall_7d",
            "wl_zscore",
            "q_zscore"
        ]
    ]
    .head(20)
)

Hydrology shape: (24108, 17)

Candidate flood-day counts:
candidate_flood_day
False    23275
True       833
Name: count, dtype: int64

Number of candidate station-days:
833

Candidate station-days by station:

  station_id  candidate_days
0       KN02             119
1       KN07             165
2       KN11             150
3       KN16             132
4       KN18             129
5       KN21             138

Sample candidate days:

,station_id,station_name,date,rainfall_3d,rainfall_7d,wl_zscore,q_zscore
292,KN02,Norwood,2015-10-20,83.4,223.0,2.356870,1.933270
293,KN02,Norwood,2015-10-21,59.5,202.3,2.442114,1.958137
294,KN02,Norwood,2015-10-22,60.2,173.7,2.271625,1.693946
500,KN02,Norwood,2016-05-15,146.6,205.5,3.466567,3.904359
501,KN02,Norwood,2016-05-16,170.2,210.9,4.017610,4.345675
502,KN02,Norwood,2016-05-17,201.1,269.4,3.877566,4.405915
503,KN02,Norwood,2016-05-18,121.1,269.9,3.501578,3.488998
504,KN02,Norwood,2016-05-19,130.7,312.7,2.539536,1.987139
505,KN02,Norwood,2016-05-20,64.8,303.6,2.732858,2.264542
876,KN02,Norwood,2017-05-26,170.4,170.4,3.130157,3.210373
880,KN02,Norwood,2017-05-30,107.5,281.3,2.050904,1.488129
881,KN02,Norwood,2017-05-31,114.7,226.7,1.951959,1.314240
1017,KN02,Norwood,2017-10-14,149.1,153.1,2.300547,1.983420
1018,KN02,Norwood,2017-10-15,159.1,169.1,2.014370,1.381477
1064,KN02,Norwood,2017-11-30,86.5,109.4,5.090774,8.889795
1065,KN02,Norwood,2017-12-01,94.6,122.1,3.172779,2.897160
1236,KN02,Norwood,2018-05-21,169.5,234.6,6.139583,12.883982
1237,KN02,Norwood,2018-05-22,171.3,236.6,3.206268,3.049977
1238,KN02,Norwood,2018-05-23,90.1,225.3,2.866813,2.494678
1239,KN02,Norwood,2018-05-24,71.2,249.8,2.308159,1.733356

In [160]:
# Create the Kelani interim output folder
kelani_output_dir = project_root / "data/interim/flood/kelani"
kelani_output_dir.mkdir(parents=True, exist_ok=True)

# Save the candidate station-level events
output_path = kelani_output_dir / "flood_candidate_events_station.parquet"

candidate_events.to_parquet(
    output_path,
    index=False
)

print("Saved successfully!")
print(output_path)
print("\nNumber of station-level candidate events:", len(candidate_events))

Saved successfully!
/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/kelani/flood_candidate_events_station.parquet

Number of station-level candidate events: 305

In [161]:
# Verify that the file exists and can be loaded

print("File exists:", output_path.exists())

saved_events = pd.read_parquet(output_path)

print("Saved shape:", saved_events.shape)
print("\nColumns:")
print(saved_events.columns.tolist())

display(saved_events.head(20))

File exists: True
Saved shape: (305, 10)

Columns:
['station_id', 'event_id', 'start_date', 'end_date', 'candidate_days', 'max_rainfall_3d', 'max_rainfall_7d', 'max_wl_zscore', 'max_q_zscore', 'duration_days']

,station_id,event_id,start_date,end_date,candidate_days,max_rainfall_3d,max_rainfall_7d,max_wl_zscore,max_q_zscore,duration_days
0,KN16,KN16_E001,2015-06-05,2015-06-05,1,154.1,248.1,1.836118,2.146417,1
1,KN07,KN07_E001,2015-10-13,2015-10-13,1,174.1,232.9,1.714657,2.532219,1
2,KN18,KN18_E001,2015-10-19,2015-10-19,1,200.7,286.1,2.426447,2.218084,1
3,KN21,KN21_E001,2015-10-19,2015-10-19,1,144.7,197.8,2.755908,2.848592,1
4,KN02,KN02_E001,2015-10-20,2015-10-22,3,83.4,223.0,2.442114,1.958137,3
5,KN18,KN18_E002,2015-10-21,2015-10-21,1,113.4,332.9,2.112498,1.769306,1
6,KN21,KN21_E002,2015-10-21,2015-10-21,1,99.1,240.7,2.160974,1.967025,1
7,KN18,KN18_E003,2015-10-24,2015-10-24,1,81.1,284.9,2.290485,2.000723,1
8,KN21,KN21_E003,2015-10-24,2015-10-24,1,76.0,256.8,2.233775,2.066336,1
9,KN11,KN11_E001,2015-11-02,2015-11-03,2,130.1,188.8,2.796370,3.501046,2
10,KN07,KN07_E002,2015-11-06,2015-11-07,2,182.8,227.2,1.509299,2.030471,2
11,KN11,KN11_E002,2015-11-13,2015-11-14,2,119.6,154.1,3.052885,2.744790,2
12,KN11,KN11_E003,2015-12-01,2015-12-01,1,117.2,117.2,2.698783,2.245964,1
13,KN11,KN11_E004,2015-12-14,2015-12-14,1,119.5,173.3,4.664466,5.546578,1
14,KN18,KN18_E004,2016-05-12,2016-05-22,11,376.5,600.0,7.542572,11.110438,11
15,KN21,KN21_E004,2016-05-12,2016-05-12,1,160.5,190.7,2.255555,2.085656,1
16,KN02,KN02_E002,2016-05-15,2016-05-20,6,201.1,312.7,4.017610,4.405915,6
17,KN11,KN11_E005,2016-05-15,2016-05-21,7,391.6,496.6,10.246449,18.658252,7
18,KN16,KN16_E002,2016-05-15,2016-05-21,7,523.9,884.8,8.758891,11.785844,7
19,KN07,KN07_E003,2016-05-16,2016-05-18,3,473.3,623.8,7.678067,11.549616,3

In [162]:
# --------------------------------------------------
# STEP 9: LOAD AUTHENTIC DESINVENTAR FLOOD RECORDS
# --------------------------------------------------

desinventar_path = (
    project_root
    / "data/raw/disaster_records/"
    / "DesInventar_Ratnapura_Kegalle_Floods_pages1-2.xlsx"
)

print("File exists:", desinventar_path.exists())

xls = pd.ExcelFile(desinventar_path)

print("\nSheets:")
print(xls.sheet_names)

# Load the main flood sheet
desinventar_flood = pd.read_excel(
    desinventar_path,
    sheet_name="Ratnapura-Kegalle Floods"
)

print("\nShape:", desinventar_flood.shape)

print("\nColumns:")
print(desinventar_flood.columns.tolist())

display(desinventar_flood.head(10))

File exists: True

Sheets:
['Ratnapura-Kegalle Floods', 'Notes']

Shape: (200, 17)

Columns:
['Serial', 'Event', 'Province', 'District', 'Division', 'Date', 'Location', 'Deaths', 'Injured', 'Missing', 'Houses Destroyed', 'Houses Damaged', 'Directly affected', 'Indirectly Affected', 'Relocated', 'Evacuated', 'Losses $USD']

,Serial,Event,Province,District,Division,Date,Location,Deaths,Injured,Missing,Houses Destroyed,Houses Damaged,Directly affected,Indirectly Affected,Relocated,Evacuated,Losses $USD
0,143803,FLOOD,Sabaragamuwa,Ratnapura,Pelmadulla,2019/12/05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,NaN,NaN,0
1,143303,FLOOD,Sabaragamuwa,Kegalle,Dehiovita,2019/10/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,0
2,143183,FLOOD,Sabaragamuwa,Kegalle,Aranayaka,2019/10/15,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,0
3,142912,FLOOD,Sabaragamuwa,Kegalle,Bulathkohupitiya,2019/08/31,NaN,NaN,NaN,NaN,4.0,NaN,NaN,26.0,NaN,NaN,0
4,142894,FLOOD,Sabaragamuwa,Ratnapura,Ratnapura,2019/08/30,NaN,NaN,NaN,NaN,1.0,NaN,NaN,114.0,NaN,NaN,0
5,142787,FLOOD,Sabaragamuwa,Ratnapura,Kiriella,2019/08/13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,312.0,NaN,NaN,0
6,142784,FLOOD,Sabaragamuwa,Ratnapura,Elapatha,2019/08/13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.0,NaN,NaN,0
7,142777,FLOOD,Sabaragamuwa,Ratnapura,Ratnapura,2019/08/13,NaN,NaN,NaN,NaN,NaN,13.0,NaN,1788.0,NaN,NaN,0
8,142444,FLOOD,Sabaragamuwa,Ratnapura,Ratnapura,2019/07/18,NaN,NaN,NaN,NaN,NaN,13.0,NaN,724.0,NaN,NaN,0
9,142435,FLOOD,Sabaragamuwa,Ratnapura,Pelmadulla,2019/07/18,NaN,NaN,NaN,NaN,NaN,25.0,NaN,115.0,NaN,NaN,0

In [163]:
# --------------------------------------------------
# STEP 9A: STANDARDIZE DESINVENTAR FLOOD RECORDS
# --------------------------------------------------

des = desinventar_flood.copy()

# Convert date to proper datetime
des["date"] = pd.to_datetime(
    des["Date"],
    format="%Y/%m/%d",
    errors="coerce"
)

# Clean district and DS division names
des["district"] = (
    des["District"]
    .astype("string")
    .str.strip()
)

des["ds_division"] = (
    des["Division"]
    .astype("string")
    .str.strip()
)

# Keep only records overlapping our hydrological observation period
des_overlap = des[
    (des["date"] >= "2015-01-01") &
    (des["date"] <= "2019-12-31")
].copy()

# --------------------------------------------------
# Basic validation
# --------------------------------------------------

print("Total DesInventar records:", len(des))
print("2015–2019 overlapping records:", len(des_overlap))

print("\nRecords by year:")
display(
    des_overlap
    .assign(year=des_overlap["date"].dt.year)
    .groupby("year")
    .size()
    .reset_index(name="record_count")
)

print("\nRecords by district:")
display(
    des_overlap
    .groupby("district")
    .size()
    .reset_index(name="record_count")
)

print("\nDS divisions represented:")
display(
    des_overlap
    .groupby(["district", "ds_division"])
    .size()
    .reset_index(name="record_count")
    .sort_values(["district", "ds_division"])
)

print("\nDate range:")
print(des_overlap["date"].min(), "to", des_overlap["date"].max())

Total DesInventar records: 200
2015–2019 overlapping records: 84

Records by year:

   year  record_count
0  2015            23
1  2016            16
2  2017            17
3  2018            18
4  2019            10

Records by district:

    district  record_count
0    Kegalle            42
1  Ratnapura            42

DS divisions represented:

     district       ds_division  record_count
0     Kegalle         Aranayaka             3
1     Kegalle  Bulathkohupitiya             4
2     Kegalle         Dehiovita             4
3     Kegalle      Deraniyagala             1
4     Kegalle        Galigamuwa             2
5     Kegalle           Kegalle             7
6     Kegalle         Mawanella            10
7     Kegalle        Rambukkana             5
8     Kegalle        Ruwanwella             3
9     Kegalle        Warakapola             1
10    Kegalle      Yatiyanthota             2
11  Ratnapura           Ayagama             3
12  Ratnapura         Balangoda             1
13  Ratnapura       Eheliyagoda             3
14  Ratnapura          Elapatha             6
15  Ratnapura      Embilipitiya             2
16  Ratnapura        Godakawela             1
17  Ratnapura         Kahawatta             2
18  Ratnapura          Kalawana             2
19  Ratnapura          Kiriella             3
20  Ratnapura           Kolonna             1
21  Ratnapura          Kuruvita             2
22  Ratnapura       Nivithigala             2
23  Ratnapura         Opanayaka             2
24  Ratnapura        Pelmadulla             5
25  Ratnapura         Ratnapura             6
26  Ratnapura        Weligepola             1

Date range:
2015-04-01 00:00:00 to 2019-12-05 00:00:00

In [164]:
# --------------------------------------------------
# STEP 9B: TEMPORAL MATCHING
# DesInventar records ↔ Hydrological candidate events
# --------------------------------------------------

# Make sure dates are datetime
candidate_events["start_date"] = pd.to_datetime(
    candidate_events["start_date"]
)

candidate_events["end_date"] = pd.to_datetime(
    candidate_events["end_date"]
)

des_overlap["date"] = pd.to_datetime(
    des_overlap["date"]
)

# --------------------------------------------------
# Find candidate station events occurring within
# ±2 days of each DesInventar flood record
# --------------------------------------------------

matches = []

for _, record in des_overlap.iterrows():

    disaster_date = record["date"]

    # Candidate event overlaps the ±2 day window
    matched = candidate_events[
        (candidate_events["start_date"] <= disaster_date + pd.Timedelta(days=2)) &
        (candidate_events["end_date"] >= disaster_date - pd.Timedelta(days=2))
    ].copy()

    if len(matched) > 0:

        for _, event in matched.iterrows():

            # Calculate distance from the DesInventar date
            if disaster_date < event["start_date"]:
                date_distance = (
                    event["start_date"] - disaster_date
                ).days

            elif disaster_date > event["end_date"]:
                date_distance = (
                    disaster_date - event["end_date"]
                ).days

            else:
                date_distance = 0

            matches.append({
                "desinventar_serial": record["Serial"],
                "disaster_date": disaster_date,
                "district": record["district"],
                "ds_division": record["ds_division"],
                "deaths": record["Deaths"],
                "injured": record["Injured"],
                "missing": record["Missing"],
                "houses_destroyed": record["Houses Destroyed"],
                "houses_damaged": record["Houses Damaged"],
                "directly_affected": record["Directly affected"],
                "indirectly_affected": record["Indirectly Affected"],
                "relocated": record["Relocated"],
                "evacuated": record["Evacuated"],
                "station_id": event["station_id"],
                "event_id": event["event_id"],
                "event_start": event["start_date"],
                "event_end": event["end_date"],
                "candidate_days": event["candidate_days"],
                "max_rainfall_3d": event["max_rainfall_3d"],
                "max_rainfall_7d": event["max_rainfall_7d"],
                "max_wl_zscore": event["max_wl_zscore"],
                "max_q_zscore": event["max_q_zscore"],
                "date_distance_days": date_distance
            })

matched_events = pd.DataFrame(matches)

print("Total DesInventar records:", len(des_overlap))
print("Matched DesInventar records:", 
      matched_events["desinventar_serial"].nunique()
      if len(matched_events) > 0 else 0)

print("Total station-event matches:", len(matched_events))

print("\nUnique DesInventar records WITHOUT a match:")

matched_serials = (
    set(matched_events["desinventar_serial"])
    if len(matched_events) > 0
    else set()
)

unmatched = des_overlap[
    ~des_overlap["Serial"].isin(matched_serials)
].copy()

print(len(unmatched))

print("\nUnmatched records:")
display(
    unmatched[
        ["Serial", "date", "district", "ds_division",
         "Deaths", "Houses Destroyed",
         "Houses Damaged", "Indirectly Affected"]
    ].sort_values("date")
)

print("\nSample matches:")
display(
    matched_events.sort_values(
        ["disaster_date", "station_id"]
    ).head(30)
)

Total DesInventar records: 84
Matched DesInventar records: 65
Total station-event matches: 269

Unique DesInventar records WITHOUT a match:
19

Unmatched records:

,Serial,date,district,ds_division,Deaths,Houses Destroyed,Houses Damaged,Indirectly Affected
83,137729,2015-04-01,Kegalle,Aranayaka,NaN,NaN,3.0,12.0
82,137756,2015-04-19,Kegalle,Mawanella,NaN,1.0,NaN,1.0
81,137854,2015-05-07,Kegalle,Mawanella,NaN,NaN,NaN,1.0
66,138378,2015-12-10,Kegalle,Mawanella,NaN,NaN,1.0,3.0
61,138400,2015-12-20,Kegalle,Mawanella,NaN,NaN,NaN,1.0
60,138469,2016-03-10,Kegalle,Mawanella,NaN,NaN,1.0,5.0
59,138509,2016-04-19,Ratnapura,Eheliyagoda,NaN,2.0,2.0,13.0
58,138586,2016-05-09,Ratnapura,Embilipitiya,NaN,11.0,NaN,45.0
57,138588,2016-05-09,Kegalle,Dehiovita,NaN,NaN,6.0,25.0
56,138590,2016-05-09,Kegalle,Rambukkana,NaN,NaN,1.0,3.0
41,138965,2017-04-04,Kegalle,Kegalle,NaN,NaN,NaN,4.0
40,138968,2017-04-05,Ratnapura,Kuruvita,NaN,NaN,21.0,94.0
39,138990,2017-04-13,Ratnapura,Pelmadulla,NaN,NaN,NaN,198.0
33,139174,2017-06-27,Kegalle,Mawanella,NaN,NaN,NaN,4.0
28,139446,2017-10-29,Kegalle,Mawanella,NaN,NaN,NaN,10.0
27,139838,2018-02-26,Kegalle,Yatiyanthota,NaN,NaN,NaN,25.0
4,142894,2019-08-30,Ratnapura,Ratnapura,NaN,1.0,NaN,114.0
3,142912,2019-08-31,Kegalle,Bulathkohupitiya,NaN,4.0,NaN,26.0
0,143803,2019-12-05,Ratnapura,Pelmadulla,NaN,NaN,NaN,40.0

Sample matches:

,desinventar_serial,disaster_date,district,ds_division,deaths,injured,missing,houses_destroyed,houses_damaged,directly_affected,...,station_id,event_id,event_start,event_end,candidate_days,max_rainfall_3d,max_rainfall_7d,max_wl_zscore,max_q_zscore,date_distance_days
267,138102,2015-10-13,Kegalle,Kegalle,NaN,NaN,NaN,NaN,2.0,NaN,...,KN07,KN07_E001,2015-10-13,2015-10-13,1,174.1,232.9,1.714657,2.532219,0
268,138098,2015-10-14,Kegalle,Kegalle,NaN,NaN,NaN,NaN,1.0,NaN,...,KN07,KN07_E001,2015-10-13,2015-10-13,1,174.1,232.9,1.714657,2.532219,1
266,138119,2015-10-18,Kegalle,Yatiyanthota,NaN,NaN,NaN,NaN,2.0,NaN,...,KN02,KN02_E001,2015-10-20,2015-10-22,3,83.4,223.0,2.442114,1.958137,2
264,138119,2015-10-18,Kegalle,Yatiyanthota,NaN,NaN,NaN,NaN,2.0,NaN,...,KN18,KN18_E001,2015-10-19,2015-10-19,1,200.7,286.1,2.426447,2.218084,1
265,138119,2015-10-18,Kegalle,Yatiyanthota,NaN,NaN,NaN,NaN,2.0,NaN,...,KN21,KN21_E001,2015-10-19,2015-10-19,1,144.7,197.8,2.755908,2.848592,1
259,138143,2015-10-22,Kegalle,Kegalle,NaN,NaN,NaN,NaN,1.0,NaN,...,KN02,KN02_E001,2015-10-20,2015-10-22,3,83.4,223.0,2.442114,1.958137,0
260,138143,2015-10-22,Kegalle,Kegalle,NaN,NaN,NaN,NaN,1.0,NaN,...,KN18,KN18_E002,2015-10-21,2015-10-21,1,113.4,332.9,2.112498,1.769306,1
262,138143,2015-10-22,Kegalle,Kegalle,NaN,NaN,NaN,NaN,1.0,NaN,...,KN18,KN18_E003,2015-10-24,2015-10-24,1,81.1,284.9,2.290485,2.000723,2
261,138143,2015-10-22,Kegalle,Kegalle,NaN,NaN,NaN,NaN,1.0,NaN,...,KN21,KN21_E002,2015-10-21,2015-10-21,1,99.1,240.7,2.160974,1.967025,1
263,138143,2015-10-22,Kegalle,Kegalle,NaN,NaN,NaN,NaN,1.0,NaN,...,KN21,KN21_E003,2015-10-24,2015-10-24,1,76.0,256.8,2.233775,2.066336,2
257,138156,2015-10-25,Kegalle,Ruwanwella,NaN,NaN,NaN,NaN,1.0,NaN,...,KN18,KN18_E003,2015-10-24,2015-10-24,1,81.1,284.9,2.290485,2.000723,1
258,138156,2015-10-25,Kegalle,Ruwanwella,NaN,NaN,NaN,NaN,1.0,NaN,...,KN21,KN21_E003,2015-10-24,2015-10-24,1,76.0,256.8,2.233775,2.066336,1
256,138169,2015-10-31,Kegalle,Mawanella,NaN,NaN,NaN,1.0,NaN,NaN,...,KN11,KN11_E001,2015-11-02,2015-11-03,2,130.1,188.8,2.796370,3.501046,2
255,138185,2015-11-02,Kegalle,Aranayaka,NaN,NaN,NaN,1.0,1.0,NaN,...,KN11,KN11_E001,2015-11-02,2015-11-03,2,130.1,188.8,2.796370,3.501046,0
250,138201,2015-11-05,Kegalle,Kegalle,NaN,NaN,NaN,NaN,2.0,NaN,...,KN07,KN07_E002,2015-11-06,2015-11-07,2,182.8,227.2,1.509299,2.030471,1
252,138200,2015-11-05,Kegalle,Mawanella,NaN,NaN,NaN,NaN,3.0,NaN,...,KN07,KN07_E002,2015-11-06,2015-11-07,2,182.8,227.2,1.509299,2.030471,1
254,138197,2015-11-05,Kegalle,Bulathkohupitiya,NaN,NaN,NaN,NaN,NaN,NaN,...,KN07,KN07_E002,2015-11-06,2015-11-07,2,182.8,227.2,1.509299,2.030471,1
249,138201,2015-11-05,Kegalle,Kegalle,NaN,NaN,NaN,NaN,2.0,NaN,...,KN11,KN11_E001,2015-11-02,2015-11-03,2,130.1,188.8,2.796370,3.501046,2
251,138200,2015-11-05,Kegalle,Mawanella,NaN,NaN,NaN,NaN,3.0,NaN,...,KN11,KN11_E001,2015-11-02,2015-11-03,2,130.1,188.8,2.796370,3.501046,2
253,138197,2015-11-05,Kegalle,Bulathkohupitiya,NaN,NaN,NaN,NaN,NaN,NaN,...,KN11,KN11_E001,2015-11-02,2015-11-03,2,130.1,188.8,2.796370,3.501046,2
248,138210,2015-11-07,Kegalle,Mawanella,NaN,NaN,NaN,NaN,3.0,NaN,...,KN07,KN07_E002,2015-11-06,2015-11-07,2,182.8,227.2,1.509299,2.030471,0
245,138223,2015-11-12,Kegalle,Rambukkana,NaN,NaN,NaN,NaN,NaN,NaN,...,KN11,KN11_E002,2015-11-13,2015-11-14,2,119.6,154.1,3.052885,2.744790,1
246,138221,2015-11-12,Kegalle,Bulathkohupitiya,NaN,NaN,NaN,NaN,4.0,NaN,...,KN11,KN11_E002,2015-11-13,2015-11-14,2,119.6,154.1,3.052885,2.744790,1
247,138219,2015-11-12,Kegalle,Bulathkohupitiya,NaN,NaN,NaN,NaN,3.0,NaN,...,KN11,KN11_E002,2015-11-13,2015-11-14,2,119.6,154.1,3.052885,2.744790,1
244,138385,2015-12-12,Kegalle,Kegalle,NaN,NaN,NaN,NaN,1.0,NaN,...,KN11,KN11_E004,2015-12-14,2015-12-14,1,119.5,173.3,4.664466,5.546578,2
242,138388,2015-12-13,Kegalle,Rambukkana,NaN,NaN,NaN,NaN,1.0,NaN,...,KN11,KN11_E004,2015-12-14,2015-12-14,1,119.5,173.3,4.664466,5.546578,1
243,138386,2015-12-13,Kegalle,Rambukkana,NaN,NaN,NaN,NaN,1.0,NaN,...,KN11,KN11_E004,2015-12-14,2015-12-14,1,119.5,173.3,4.664466,5.546578,1
241,138391,2015-12-14,Kegalle,Dehiovita,NaN,NaN,NaN,NaN,1.0,NaN,...,KN11,KN11_E004,2015-12-14,2015-12-14,1,119.5,173.3,4.664466,5.546578,0
239,138612,2016-05-11,Kegalle,Ruwanwella,NaN,NaN,NaN,NaN,1.0,NaN,...,KN18,KN18_E004,2016-05-12,2016-05-22,11,376.5,600.0,7.542572,11.110438,1
240,138612,2016-05-11,Kegalle,Ruwanwella,NaN,NaN,NaN,NaN,1.0,NaN,...,KN21,KN21_E004,2016-05-12,2016-05-12,1,160.5,190.7,2.255555,2.085656,1

In [165]:
# --------------------------------------------------
# STEP 9C: INSPECT REGIONAL CLUSTERING OF
# HYDROLOGICAL CANDIDATE EVENTS
# --------------------------------------------------

historical_events = candidate_events[
    (candidate_events["start_date"] >= "2015-01-01") &
    (candidate_events["end_date"] <= "2019-12-31")
].copy()

print("Station-level candidate events, 2015–2019:",
      len(historical_events))

print("\nEvents by year:")
display(
    historical_events
    .assign(year=historical_events["start_date"].dt.year)
    .groupby("year")
    .size()
    .reset_index(name="station_event_count")
)

print("\nHistorical station events:")
display(
    historical_events[
        [
            "station_id",
            "event_id",
            "start_date",
            "end_date",
            "candidate_days",
            "max_rainfall_3d",
            "max_rainfall_7d",
            "max_wl_zscore",
            "max_q_zscore"
        ]
    ].sort_values(["start_date", "station_id"])
)

Station-level candidate events, 2015–2019: 93

Events by year:

   year  station_event_count
0  2015                   14
1  2016                   12
2  2017                   26
3  2018                   19
4  2019                   22

Historical station events:

,station_id,event_id,start_date,end_date,candidate_days,max_rainfall_3d,max_rainfall_7d,max_wl_zscore,max_q_zscore
0,KN16,KN16_E001,2015-06-05,2015-06-05,1,154.1,248.1,1.836118,2.146417
1,KN07,KN07_E001,2015-10-13,2015-10-13,1,174.1,232.9,1.714657,2.532219
2,KN18,KN18_E001,2015-10-19,2015-10-19,1,200.7,286.1,2.426447,2.218084
3,KN21,KN21_E001,2015-10-19,2015-10-19,1,144.7,197.8,2.755908,2.848592
4,KN02,KN02_E001,2015-10-20,2015-10-22,3,83.4,223.0,2.442114,1.958137
...,...,...,...,...,...,...,...,...,...
88,KN11,KN11_E015,2019-10-21,2019-10-22,2,108.7,249.5,3.167606,3.117633
89,KN16,KN16_E018,2019-10-21,2019-10-21,1,160.3,251.9,2.673236,3.000878
90,KN18,KN18_E016,2019-10-21,2019-10-22,2,154.3,294.2,3.651233,3.847054
91,KN11,KN11_E016,2019-11-30,2019-12-01,2,168.0,208.7,2.961774,3.398996
92,KN18,KN18_E017,2019-12-01,2019-12-01,1,172.4,273.9,2.126412,1.812818

In [166]:
# --------------------------------------------------
# STEP 10: BUILD REGIONAL FLOOD EPISODES
# --------------------------------------------------

events = historical_events.copy()

events = events.sort_values(
    ["start_date", "end_date", "station_id"]
).reset_index(drop=True)

# --------------------------------------------------
# Determine whether each event starts a new regional
# episode.
#
# If the next event starts more than 2 days after the
# latest end date of the current episode, start a new
# episode.
# --------------------------------------------------

regional_episode_numbers = []

current_episode = 0
current_episode_end = None

for _, row in events.iterrows():

    start = row["start_date"]
    end = row["end_date"]

    if current_episode_end is None:
        current_episode = 1
        current_episode_end = end

    elif start > current_episode_end + pd.Timedelta(days=2):
        current_episode += 1
        current_episode_end = end

    else:
        current_episode_end = max(current_episode_end, end)

    regional_episode_numbers.append(current_episode)

events["regional_episode_number"] = regional_episode_numbers

# Create readable episode IDs
events["regional_episode_id"] = (
    "KELANI_EP"
    + events["regional_episode_number"]
      .astype(str)
      .str.zfill(3)
)

# --------------------------------------------------
# Summarise each regional episode
# --------------------------------------------------

regional_episodes = (
    events
    .groupby("regional_episode_id", as_index=False)
    .agg(
        start_date=("start_date", "min"),
        end_date=("end_date", "max"),
        station_count=("station_id", "nunique"),
        station_event_count=("event_id", "count"),
        stations=("station_id", lambda x: ", ".join(sorted(set(x)))),
        max_rainfall_3d=("max_rainfall_3d", "max"),
        max_rainfall_7d=("max_rainfall_7d", "max"),
        max_wl_zscore=("max_wl_zscore", "max"),
        max_q_zscore=("max_q_zscore", "max")
    )
)

regional_episodes["duration_days"] = (
    regional_episodes["end_date"]
    - regional_episodes["start_date"]
).dt.days + 1

regional_episodes = regional_episodes.sort_values(
    "start_date"
).reset_index(drop=True)

# --------------------------------------------------
# Save
# --------------------------------------------------

regional_output_path = (
    project_root
    / "data/interim/flood/kelani/"
    / "flood_regional_episodes.parquet"
)

regional_episodes.to_parquet(
    regional_output_path,
    index=False
)

print("Regional flood episodes:", len(regional_episodes))
print("Saved to:")
print(regional_output_path)

print("\nRegional episodes:")
display(regional_episodes)

Regional flood episodes: 30
Saved to:
/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/kelani/flood_regional_episodes.parquet

Regional episodes:

,regional_episode_id,start_date,end_date,station_count,station_event_count,stations,max_rainfall_3d,max_rainfall_7d,max_wl_zscore,max_q_zscore,duration_days
0,KELANI_EP001,2015-06-05,2015-06-05,1,1,KN16,154.1,248.1,1.836118,2.146417,1
1,KELANI_EP002,2015-10-13,2015-10-13,1,1,KN07,174.1,232.9,1.714657,2.532219,1
2,KELANI_EP003,2015-10-19,2015-10-24,3,7,"KN02, KN18, KN21",200.7,332.9,2.755908,2.848592,6
3,KELANI_EP004,2015-11-02,2015-11-03,1,1,KN11,130.1,188.8,2.796370,3.501046,2
4,KELANI_EP005,2015-11-06,2015-11-07,1,1,KN07,182.8,227.2,1.509299,2.030471,2
5,KELANI_EP006,2015-11-13,2015-11-14,1,1,KN11,119.6,154.1,3.052885,2.744790,2
6,KELANI_EP007,2015-12-01,2015-12-01,1,1,KN11,117.2,117.2,2.698783,2.245964,1
7,KELANI_EP008,2015-12-14,2015-12-14,1,1,KN11,119.5,173.3,4.664466,5.546578,1
8,KELANI_EP009,2016-05-12,2016-05-31,6,12,"KN02, KN07, KN11, KN16, KN18, KN21",523.9,884.8,10.246449,18.658252,20
9,KELANI_EP010,2017-05-24,2017-06-03,6,11,"KN02, KN07, KN11, KN16, KN18, KN21",450.7,623.3,6.921974,9.254390,11
10,KELANI_EP011,2017-09-07,2017-09-10,4,4,"KN07, KN16, KN18, KN21",294.0,382.7,3.707726,4.368024,4
11,KELANI_EP012,2017-09-13,2017-09-14,3,3,"KN11, KN18, KN21",188.4,277.0,2.943577,3.125998,2
12,KELANI_EP013,2017-09-27,2017-09-27,2,2,"KN07, KN16",216.1,246.9,2.497697,2.560111,1
13,KELANI_EP014,2017-10-14,2017-10-16,4,4,"KN02, KN07, KN16, KN18",246.7,302.3,3.849181,4.263227,3
14,KELANI_EP015,2017-10-19,2017-10-19,1,1,KN07,104.9,310.0,1.804822,1.007463,1
15,KELANI_EP016,2017-11-30,2017-12-01,1,1,KN02,94.6,122.1,5.090774,8.889795,2
16,KELANI_EP017,2018-05-16,2018-05-16,1,1,KN16,281.5,431.7,1.782757,1.754869,1
17,KELANI_EP018,2018-05-20,2018-05-27,6,8,"KN02, KN07, KN11, KN16, KN18, KN21",529.7,784.4,8.120074,12.883982,8
18,KELANI_EP019,2018-06-02,2018-06-10,3,4,"KN02, KN07, KN16",325.9,536.9,5.052393,5.939432,9
19,KELANI_EP020,2018-08-15,2018-08-20,1,1,KN02,191.3,349.5,3.545722,3.471095,6
20,KELANI_EP021,2018-10-05,2018-10-07,3,3,"KN11, KN16, KN18",198.4,366.7,2.622790,2.517843,3
21,KELANI_EP022,2018-10-22,2018-10-22,1,1,KN02,90.4,139.0,1.945871,1.302015,1
22,KELANI_EP023,2018-11-24,2018-11-24,1,1,KN18,206.4,303.4,2.115706,1.790975,1
23,KELANI_EP024,2019-07-18,2019-07-20,2,2,"KN02, KN07",203.3,266.1,3.207034,3.385474,3
24,KELANI_EP025,2019-08-12,2019-08-14,3,3,"KN02, KN07, KN11",248.8,332.1,3.924183,4.247715,3
25,KELANI_EP026,2019-09-16,2019-09-16,4,4,"KN02, KN11, KN16, KN18",161.3,267.7,3.084490,2.906143,1
26,KELANI_EP027,2019-09-24,2019-09-25,2,2,"KN18, KN21",194.9,254.9,2.685793,2.701870,2
27,KELANI_EP028,2019-10-08,2019-10-08,1,1,KN16,157.3,269.5,1.815138,1.741773,1
28,KELANI_EP029,2019-10-13,2019-10-24,4,8,"KN07, KN11, KN16, KN18",194.5,320.5,3.651233,3.847054,12
29,KELANI_EP030,2019-11-30,2019-12-01,2,2,"KN11, KN18",172.4,273.9,2.961774,3.398996,2

In [167]:
# --------------------------------------------------
# STEP 9: VALIDATE REGIONAL EPISODES AGAINST DESINVENTAR
# --------------------------------------------------

# Load regional episodes
regional_episodes = pd.read_parquet(
    project_root
    / "data/interim/flood/kelani/"
    / "flood_regional_episodes.parquet"
)

print("Regional episodes:", len(regional_episodes))

# --------------------------------------------------
# Prepare DesInventar data
# --------------------------------------------------

desi = desinventar.copy()

desi["date"] = pd.to_datetime(desi["date"])

# Create a unique record identifier
desi["desinventar_id"] = desi["Serial"].astype(str)

# Keep the main impact fields
impact_columns = [
    "Deaths",
    "Injured",
    "Missing",
    "Houses Destroyed",
    "Houses Damaged",
    "Directly Affected",
    "Indirectly Affected",
    "Relocated",
    "Evacuated"
]

# Make sure numeric fields are numeric
for col in impact_columns:
    if col in desi.columns:
        desi[col] = pd.to_numeric(
            desi[col],
            errors="coerce"
        )

# --------------------------------------------------
# Match each DesInventar record to regional episodes
# --------------------------------------------------

validation_rows = []

for _, d in desi.iterrows():

    # Only consider regional episodes within ±7 days
    candidates = regional_episodes[
        (
            regional_episodes["start_date"]
            .between(
                d["date"] - pd.Timedelta(days=7),
                d["date"] + pd.Timedelta(days=7)
            )
        )
        |
        (
            regional_episodes["end_date"]
            .between(
                d["date"] - pd.Timedelta(days=7),
                d["date"] + pd.Timedelta(days=7)
            )
        )
        |
        (
            (regional_episodes["start_date"] <= d["date"])
            &
            (regional_episodes["end_date"] >= d["date"])
        )
    ].copy()

    if len(candidates) == 0:
        validation_rows.append({
            "desinventar_id": d["desinventar_id"],
            "disaster_date": d["date"],
            "district": d["district"],
            "ds_division": d["ds_division"],
            "deaths": d["Deaths"],
            "houses_destroyed": d["Houses Destroyed"],
            "houses_damaged": d["Houses Damaged"],
            "indirectly_affected": d["Indirectly Affected"],
            "regional_episode_id": pd.NA,
            "episode_start": pd.NaT,
            "episode_end": pd.NaT,
            "station_count": pd.NA,
            "station_event_count": pd.NA,
            "date_distance_days": pd.NA
        })

    else:

        # Calculate distance from DesInventar date
        candidates["date_distance_days"] = candidates.apply(
            lambda row: min(
                abs((d["date"] - row["start_date"]).days),
                abs((d["date"] - row["end_date"]).days)
            ),
            axis=1
        )

        # Choose closest regional episode
        best = candidates.sort_values(
            ["date_distance_days", "station_count"],
            ascending=[True, False]
        ).iloc[0]

        validation_rows.append({
            "desinventar_id": d["desinventar_id"],
            "disaster_date": d["date"],
            "district": d["district"],
            "ds_division": d["ds_division"],
            "deaths": d["Deaths"],
            "houses_destroyed": d["Houses Destroyed"],
            "houses_damaged": d["Houses Damaged"],
            "indirectly_affected": d["Indirectly Affected"],
            "regional_episode_id": best["regional_episode_id"],
            "episode_start": best["start_date"],
            "episode_end": best["end_date"],
            "station_count": best["station_count"],
            "station_event_count": best["station_event_count"],
            "date_distance_days": best["date_distance_days"]
        })

regional_validation = pd.DataFrame(validation_rows)

# --------------------------------------------------
# Validation summary
# --------------------------------------------------

regional_validation["matched"] = (
    regional_validation["regional_episode_id"].notna()
)

print("Total DesInventar records:", len(regional_validation))
print(
    "Matched to regional episode:",
    regional_validation["matched"].sum()
)
print(
    "Unmatched:",
    (~regional_validation["matched"]).sum()
)

print("\nMatch percentage:")
print(
    round(
        regional_validation["matched"].mean() * 100,
        2
    ),
    "%"
)

# --------------------------------------------------
# Display
# --------------------------------------------------

display(
    regional_validation[
        [
            "desinventar_id",
            "disaster_date",
            "district",
            "ds_division",
            "indirectly_affected",
            "regional_episode_id",
            "episode_start",
            "episode_end",
            "station_count",
            "date_distance_days",
            "matched"
        ]
    ].sort_values("disaster_date")
)

Regional episodes: 30

NameError: name 'desinventar' is not defined

In [168]:
# --------------------------------------------------
# VALIDATE REGIONAL EPISODES AGAINST DESINVENTAR
# --------------------------------------------------

# Load regional episodes
regional_episodes = pd.read_parquet(
    project_root
    / "data/interim/flood/kelani/"
    / "flood_regional_episodes.parquet"
)

print("Regional episodes:", len(regional_episodes))


# --------------------------------------------------
# Load DesInventar
# --------------------------------------------------

desi = desinventar_flood.copy()

# Convert date
desi["date"] = pd.to_datetime(
    desi["Date"],
    format="%Y/%m/%d",
    errors="coerce"
)

# Clean location fields
desi["district"] = (
    desi["District"]
    .astype("string")
    .str.strip()
)

desi["ds_division"] = (
    desi["Division"]
    .astype("string")
    .str.strip()
)

# Unique DesInventar record
desi["desinventar_id"] = (
    desi["Serial"].astype(str)
)


# --------------------------------------------------
# Convert impact columns to numeric
# --------------------------------------------------

impact_columns = [
    "Deaths",
    "Injured",
    "Missing",
    "Houses Destroyed",
    "Houses Damaged",
    "Directly affected",
    "Indirectly Affected",
    "Relocated",
    "Evacuated"
]

for col in impact_columns:
    desi[col] = pd.to_numeric(
        desi[col],
        errors="coerce"
    )


# --------------------------------------------------
# Keep 2015–2019 overlap
# --------------------------------------------------

desi_overlap = desi[
    (desi["date"] >= "2015-01-01") &
    (desi["date"] <= "2019-12-31")
].copy()

print(
    "DesInventar records in 2015–2019:",
    len(desi_overlap)
)


# --------------------------------------------------
# Match each DesInventar record to a regional episode
# --------------------------------------------------

validation_rows = []

for _, d in desi_overlap.iterrows():

    candidates = regional_episodes[
        (
            regional_episodes["start_date"]
            <= d["date"] + pd.Timedelta(days=7)
        )
        &
        (
            regional_episodes["end_date"]
            >= d["date"] - pd.Timedelta(days=7)
        )
    ].copy()

    # ----------------------------------------------
    # No regional episode found
    # ----------------------------------------------

    if len(candidates) == 0:

        validation_rows.append({
            "desinventar_id": d["desinventar_id"],
            "disaster_date": d["date"],
            "district": d["district"],
            "ds_division": d["ds_division"],
            "deaths": d["Deaths"],
            "houses_destroyed": d["Houses Destroyed"],
            "houses_damaged": d["Houses Damaged"],
            "indirectly_affected": d["Indirectly Affected"],
            "regional_episode_id": pd.NA,
            "episode_start": pd.NaT,
            "episode_end": pd.NaT,
            "station_count": pd.NA,
            "station_event_count": pd.NA,
            "date_distance_days": pd.NA
        })

    # ----------------------------------------------
    # Regional episode found
    # ----------------------------------------------

    else:

        # Distance from DesInventar event date
        candidates["date_distance_days"] = candidates.apply(
            lambda row: min(
                abs(
                    (d["date"] - row["start_date"]).days
                ),
                abs(
                    (d["date"] - row["end_date"]).days
                )
            ),
            axis=1
        )

        # Select closest episode.
        # If tied, prefer the episode involving
        # more stations.
        best = candidates.sort_values(
            [
                "date_distance_days",
                "station_count"
            ],
            ascending=[
                True,
                False
            ]
        ).iloc[0]

        validation_rows.append({
            "desinventar_id": d["desinventar_id"],
            "disaster_date": d["date"],
            "district": d["district"],
            "ds_division": d["ds_division"],
            "deaths": d["Deaths"],
            "houses_destroyed": d["Houses Destroyed"],
            "houses_damaged": d["Houses Damaged"],
            "indirectly_affected": d["Indirectly Affected"],
            "regional_episode_id": best["regional_episode_id"],
            "episode_start": best["start_date"],
            "episode_end": best["end_date"],
            "station_count": best["station_count"],
            "station_event_count": best["station_event_count"],
            "date_distance_days": best["date_distance_days"]
        })


# --------------------------------------------------
# Create validation dataframe
# --------------------------------------------------

regional_validation = pd.DataFrame(
    validation_rows
)

regional_validation["matched"] = (
    regional_validation["regional_episode_id"]
    .notna()
)


# --------------------------------------------------
# Summary
# --------------------------------------------------

total_records = len(regional_validation)

matched_records = (
    regional_validation["matched"].sum()
)

unmatched_records = (
    (~regional_validation["matched"]).sum()
)

match_percentage = (
    matched_records / total_records * 100
)


print("\n-----------------------------")
print("REGIONAL EPISODE VALIDATION")
print("-----------------------------")

print(
    "Total DesInventar records:",
    total_records
)

print(
    "Matched to regional episode:",
    matched_records
)

print(
    "Unmatched:",
    unmatched_records
)

print(
    "Match percentage:",
    round(match_percentage, 2),
    "%"
)


# --------------------------------------------------
# Display results
# --------------------------------------------------

display(
    regional_validation[
        [
            "desinventar_id",
            "disaster_date",
            "district",
            "ds_division",
            "indirectly_affected",
            "regional_episode_id",
            "episode_start",
            "episode_end",
            "station_count",
            "date_distance_days",
            "matched"
        ]
    ]
    .sort_values("disaster_date")
    .reset_index(drop=True)
)

Regional episodes: 30
DesInventar records in 2015–2019: 84

-----------------------------
REGIONAL EPISODE VALIDATION
-----------------------------
Total DesInventar records: 84
Matched to regional episode: 71
Unmatched: 13
Match percentage: 84.52 %

,desinventar_id,disaster_date,district,ds_division,indirectly_affected,regional_episode_id,episode_start,episode_end,station_count,date_distance_days,matched
0,137729,2015-04-01,Kegalle,Aranayaka,12.0,<NA>,NaT,NaT,<NA>,<NA>,False
1,137756,2015-04-19,Kegalle,Mawanella,1.0,<NA>,NaT,NaT,<NA>,<NA>,False
2,137854,2015-05-07,Kegalle,Mawanella,1.0,<NA>,NaT,NaT,<NA>,<NA>,False
3,138102,2015-10-13,Kegalle,Kegalle,8.0,KELANI_EP002,2015-10-13,2015-10-13,1,0,True
4,138098,2015-10-14,Kegalle,Kegalle,4.0,KELANI_EP002,2015-10-13,2015-10-13,1,1,True
...,...,...,...,...,...,...,...,...,...,...,...
79,142894,2019-08-30,Ratnapura,Ratnapura,114.0,<NA>,NaT,NaT,<NA>,<NA>,False
80,142912,2019-08-31,Kegalle,Bulathkohupitiya,26.0,<NA>,NaT,NaT,<NA>,<NA>,False
81,143183,2019-10-15,Kegalle,Aranayaka,4.0,KELANI_EP029,2019-10-13,2019-10-24,4,2,True
82,143303,2019-10-21,Kegalle,Dehiovita,48.0,KELANI_EP029,2019-10-13,2019-10-24,4,3,True
83,143803,2019-12-05,Ratnapura,Pelmadulla,40.0,KELANI_EP030,2019-11-30,2019-12-01,2,4,True

In [169]:
# --------------------------------------------------
# INSPECT UNMATCHED DESINVENTAR RECORDS
# --------------------------------------------------

unmatched = regional_validation[
    ~regional_validation["matched"]
].copy()

print("Unmatched records:", len(unmatched))

display(
    unmatched[
        [
            "desinventar_id",
            "disaster_date",
            "district",
            "ds_division",
            "deaths",
            "houses_destroyed",
            "houses_damaged",
            "indirectly_affected"
        ]
    ].sort_values("disaster_date")
)

Unmatched records: 13

,desinventar_id,disaster_date,district,ds_division,deaths,houses_destroyed,houses_damaged,indirectly_affected
83,137729,2015-04-01,Kegalle,Aranayaka,NaN,NaN,3.0,12.0
82,137756,2015-04-19,Kegalle,Mawanella,NaN,1.0,NaN,1.0
81,137854,2015-05-07,Kegalle,Mawanella,NaN,NaN,NaN,1.0
60,138469,2016-03-10,Kegalle,Mawanella,NaN,NaN,1.0,5.0
59,138509,2016-04-19,Ratnapura,Eheliyagoda,NaN,2.0,2.0,13.0
41,138965,2017-04-04,Kegalle,Kegalle,NaN,NaN,NaN,4.0
40,138968,2017-04-05,Ratnapura,Kuruvita,NaN,NaN,21.0,94.0
39,138990,2017-04-13,Ratnapura,Pelmadulla,NaN,NaN,NaN,198.0
33,139174,2017-06-27,Kegalle,Mawanella,NaN,NaN,NaN,4.0
28,139446,2017-10-29,Kegalle,Mawanella,NaN,NaN,NaN,10.0
27,139838,2018-02-26,Kegalle,Yatiyanthota,NaN,NaN,NaN,25.0
4,142894,2019-08-30,Ratnapura,Ratnapura,NaN,1.0,NaN,114.0
3,142912,2019-08-31,Kegalle,Bulathkohupitiya,NaN,4.0,NaN,26.0

In [170]:
# --------------------------------------------------
# REGIONAL EPISODE MATCH SUMMARY
# --------------------------------------------------

episode_match_summary = (
    regional_validation[
        regional_validation["matched"]
    ]
    .groupby("regional_episode_id", as_index=False)
    .agg(
        desinventar_records=("desinventar_id", "count"),
        total_indirectly_affected=("indirectly_affected", "sum"),
        max_indirectly_affected=("indirectly_affected", "max"),
        ds_divisions=("ds_division", "nunique"),
        station_count=("station_count", "first"),
        episode_start=("episode_start", "first"),
        episode_end=("episode_end", "first")
    )
    .sort_values(
        ["desinventar_records", "max_indirectly_affected"],
        ascending=False
    )
)

display(episode_match_summary)

,regional_episode_id,desinventar_records,total_indirectly_affected,max_indirectly_affected,ds_divisions,station_count,episode_start,episode_end
10,KELANI_EP018,17,33736.0,8624.0,16,6,2018-05-20,2018-05-27
6,KELANI_EP009,14,8043.0,3875.0,13,6,2016-05-12,2016-05-31
7,KELANI_EP010,8,28383.0,25363.0,7,6,2017-05-24,2017-06-03
5,KELANI_EP008,6,44.0,11.0,4,1,2015-12-14,2015-12-14
3,KELANI_EP005,4,109.0,67.0,3,1,2015-11-06,2015-11-07
12,KELANI_EP025,3,2481.0,1788.0,3,3,2019-08-12,2019-08-14
4,KELANI_EP006,3,47.0,16.0,2,1,2015-11-13,2015-11-14
1,KELANI_EP003,3,16.0,8.0,3,3,2015-10-19,2015-10-24
8,KELANI_EP011,2,1434.0,879.0,2,4,2017-09-07,2017-09-10
11,KELANI_EP024,2,839.0,724.0,2,2,2019-07-18,2019-07-20
9,KELANI_EP014,2,365.0,280.0,2,4,2017-10-14,2017-10-16
13,KELANI_EP029,2,52.0,48.0,2,4,2019-10-13,2019-10-24
0,KELANI_EP002,2,12.0,8.0,1,1,2015-10-13,2015-10-13
2,KELANI_EP004,2,9.0,7.0,2,1,2015-11-02,2015-11-03
14,KELANI_EP030,1,40.0,40.0,1,2,2019-11-30,2019-12-01

In [171]:
# --------------------------------------------------
# INSPECT LONG REGIONAL EPISODES
# --------------------------------------------------

long_episode_ids = regional_episodes[
    regional_episodes["duration_days"] >= 7
]["regional_episode_id"].tolist()

print("Long episodes:")
print(long_episode_ids)

long_episode_details = (
    events[
        events["regional_episode_id"].isin(long_episode_ids)
    ]
    [
        [
            "regional_episode_id",
            "station_id",
            "event_id",
            "start_date",
            "end_date",
            "candidate_days",
            "max_rainfall_3d",
            "max_rainfall_7d",
            "max_wl_zscore",
            "max_q_zscore"
        ]
    ]
    .sort_values(
        [
            "regional_episode_id",
            "start_date",
            "station_id"
        ]
    )
    .reset_index(drop=True)
)

display(long_episode_details)

Long episodes:
['KELANI_EP009', 'KELANI_EP010', 'KELANI_EP018', 'KELANI_EP019', 'KELANI_EP029']

,regional_episode_id,station_id,event_id,start_date,end_date,candidate_days,max_rainfall_3d,max_rainfall_7d,max_wl_zscore,max_q_zscore
0,KELANI_EP009,KN18,KN18_E004,2016-05-12,2016-05-22,11,376.5,600.0,7.542572,11.110438
1,KELANI_EP009,KN21,KN21_E004,2016-05-12,2016-05-12,1,160.5,190.7,2.255555,2.085656
2,KELANI_EP009,KN02,KN02_E002,2016-05-15,2016-05-20,6,201.1,312.7,4.017610,4.405915
3,KELANI_EP009,KN11,KN11_E005,2016-05-15,2016-05-21,7,391.6,496.6,10.246449,18.658252
4,KELANI_EP009,KN16,KN16_E002,2016-05-15,2016-05-21,7,523.9,884.8,8.758891,11.785844
5,KELANI_EP009,KN07,KN07_E003,2016-05-16,2016-05-18,3,473.3,623.8,7.678067,11.549616
6,KELANI_EP009,KN21,KN21_E005,2016-05-16,2016-05-24,9,227.3,392.6,5.992836,9.515839
7,KELANI_EP009,KN07,KN07_E004,2016-05-20,2016-05-20,1,212.2,708.4,1.299128,1.743205
8,KELANI_EP009,KN16,KN16_E003,2016-05-25,2016-05-25,1,76.5,279.4,1.910137,1.741911
9,KELANI_EP009,KN16,KN16_E004,2016-05-27,2016-05-28,2,178.4,277.7,3.048999,3.140951
10,KELANI_EP009,KN21,KN21_E006,2016-05-28,2016-05-29,2,199.5,293.7,3.168542,3.472260
11,KELANI_EP009,KN21,KN21_E007,2016-05-31,2016-05-31,1,42.2,247.8,2.041033,1.789505
12,KELANI_EP010,KN16,KN16_E005,2017-05-24,2017-05-27,4,450.7,480.3,6.921974,9.254390
13,KELANI_EP010,KN18,KN18_E005,2017-05-25,2017-05-27,3,325.3,400.0,5.441438,7.027346
14,KELANI_EP010,KN02,KN02_E003,2017-05-26,2017-05-26,1,170.4,170.4,3.130157,3.210373
15,KELANI_EP010,KN07,KN07_E005,2017-05-26,2017-05-26,1,204.4,256.0,3.359448,3.424846
16,KELANI_EP010,KN21,KN21_E008,2017-05-26,2017-05-31,6,428.5,489.4,5.112668,7.375819
17,KELANI_EP010,KN16,KN16_E006,2017-05-29,2017-05-31,3,168.5,623.3,3.131684,3.335923
18,KELANI_EP010,KN02,KN02_E004,2017-05-30,2017-05-31,2,114.7,281.3,2.050904,1.488129
19,KELANI_EP010,KN07,KN07_E006,2017-05-30,2017-06-02,4,148.2,369.3,2.813965,2.438800
20,KELANI_EP010,KN11,KN11_E006,2017-05-30,2017-05-30,1,86.7,240.2,2.827040,2.238489
21,KELANI_EP010,KN18,KN18_E006,2017-05-30,2017-05-31,2,104.9,422.6,2.766188,2.476004
22,KELANI_EP010,KN16,KN16_E007,2017-06-02,2017-06-03,2,151.5,324.7,2.556494,2.622397
23,KELANI_EP018,KN07,KN07_E011,2018-05-20,2018-05-23,4,331.3,411.6,5.859042,7.635273
24,KELANI_EP018,KN11,KN11_E008,2018-05-20,2018-05-23,4,250.9,313.2,7.893206,11.600746
25,KELANI_EP018,KN16,KN16_E012,2018-05-20,2018-05-25,6,529.7,784.4,8.120074,10.686408
26,KELANI_EP018,KN18,KN18_E010,2018-05-20,2018-05-27,8,220.8,422.0,5.805124,7.463404
27,KELANI_EP018,KN02,KN02_E007,2018-05-21,2018-05-25,5,171.3,249.8,6.139583,12.883982
28,KELANI_EP018,KN21,KN21_E011,2018-05-21,2018-05-26,6,157.0,276.5,4.898743,6.864322
29,KELANI_EP018,KN07,KN07_E012,2018-05-25,2018-05-26,2,118.4,466.5,2.262065,1.637378
30,KELANI_EP018,KN11,KN11_E009,2018-05-25,2018-05-27,3,177.6,443.2,5.664037,6.823423
31,KELANI_EP019,KN07,KN07_E013,2018-06-02,2018-06-10,9,219.4,388.9,4.917283,5.939432
32,KELANI_EP019,KN16,KN16_E013,2018-06-02,2018-06-04,3,325.9,377.8,2.804465,2.963720
33,KELANI_EP019,KN02,KN02_E008,2018-06-07,2018-06-07,1,89.4,143.6,2.189426,1.786291
34,KELANI_EP019,KN16,KN16_E014,2018-06-07,2018-06-09,3,196.1,536.9,5.052393,5.929685
35,KELANI_EP029,KN11,KN11_E013,2019-10-13,2019-10-13,1,155.8,198.9,2.748623,2.235740
36,KELANI_EP029,KN18,KN18_E015,2019-10-13,2019-10-14,2,194.5,244.6,2.086831,1.747695
37,KELANI_EP029,KN11,KN11_E014,2019-10-15,2019-10-17,3,134.8,296.2,3.096251,2.597438
38,KELANI_EP029,KN07,KN07_E016,2019-10-19,2019-10-19,1,150.8,236.0,2.440149,1.865944
39,KELANI_EP029,KN07,KN07_E017,2019-10-21,2019-10-24,4,161.1,320.5,3.197407,3.154738
40,KELANI_EP029,KN11,KN11_E015,2019-10-21,2019-10-22,2,108.7,249.5,3.167606,3.117633
41,KELANI_EP029,KN16,KN16_E018,2019-10-21,2019-10-21,1,160.3,251.9,2.673236,3.000878
42,KELANI_EP029,KN18,KN18_E016,2019-10-21,2019-10-22,2,154.3,294.2,3.651233,3.847054

In [172]:
# --------------------------------------------------
# STEP 11: CREATE CANDIDATE EPISODE-IMPACT TABLE
# --------------------------------------------------

# Merge regional episode information into
# the validated DesInventar records.

episode_impact = regional_validation[
    regional_validation["matched"]
].copy()

# Select useful regional episode features
episode_features = regional_episodes[
    [
        "regional_episode_id",
        "start_date",
        "end_date",
        "station_count",
        "station_event_count",
        "stations",
        "max_rainfall_3d",
        "max_rainfall_7d",
        "max_wl_zscore",
        "max_q_zscore",
        "duration_days"
    ]
].copy()

# Rename episode dates to avoid confusion
episode_features = episode_features.rename(
    columns={
        "start_date": "episode_start",
        "end_date": "episode_end"
    }
)

# Merge
episode_impact = episode_impact.merge(
    episode_features,
    on="regional_episode_id",
    how="left"
)

# --------------------------------------------------
# Historical impact fields
# --------------------------------------------------

episode_impact["human_impact_count"] = (
    episode_impact["indirectly_affected"]
)

# Binary indicators for historical impact
episode_impact["death_recorded"] = (
    episode_impact["deaths"].fillna(0) > 0
)

episode_impact["houses_destroyed_recorded"] = (
    episode_impact["houses_destroyed"].fillna(0) > 0
)

episode_impact["houses_damaged_recorded"] = (
    episode_impact["houses_damaged"].fillna(0) > 0
)

# --------------------------------------------------
# Sort
# --------------------------------------------------

episode_impact = episode_impact.sort_values(
    [
        "disaster_date",
        "district",
        "ds_division"
    ]
).reset_index(drop=True)

# --------------------------------------------------
# Summary
# --------------------------------------------------

print(
    "Candidate episode-impact records:",
    len(episode_impact)
)

print(
    "Unique regional episodes:",
    episode_impact["regional_episode_id"].nunique()
)

print(
    "Unique DS divisions:",
    episode_impact["ds_division"].nunique()
)

print("\nColumns:")
print(episode_impact.columns.tolist())

# --------------------------------------------------
# Display
# --------------------------------------------------

display(
    episode_impact[
        [
            "desinventar_id",
            "disaster_date",
            "district",
            "ds_division",
            "regional_episode_id",
            "episode_start",
            "episode_end",
            "station_count",
            "max_rainfall_3d",
            "max_rainfall_7d",
            "max_wl_zscore",
            "max_q_zscore",
            "human_impact_count",
            "death_recorded",
            "houses_destroyed_recorded",
            "houses_damaged_recorded"
        ]
    ]
)

Candidate episode-impact records: 71
Unique regional episodes: 15
Unique DS divisions: 27

Columns:
['desinventar_id', 'disaster_date', 'district', 'ds_division', 'deaths', 'houses_destroyed', 'houses_damaged', 'indirectly_affected', 'regional_episode_id', 'episode_start_x', 'episode_end_x', 'station_count_x', 'station_event_count_x', 'date_distance_days', 'matched', 'episode_start_y', 'episode_end_y', 'station_count_y', 'station_event_count_y', 'stations', 'max_rainfall_3d', 'max_rainfall_7d', 'max_wl_zscore', 'max_q_zscore', 'duration_days', 'human_impact_count', 'death_recorded', 'houses_destroyed_recorded', 'houses_damaged_recorded']

KeyError: "['episode_start', 'episode_end', 'station_count'] not in index"

In [173]:
# --------------------------------------------------
# FIX DISPLAY OF CANDIDATE EPISODE-IMPACT TABLE
# --------------------------------------------------

display_columns = [
    "desinventar_id",
    "disaster_date",
    "district",
    "ds_division",
    "regional_episode_id",
    "episode_start_y",
    "episode_end_y",
    "station_count_y",
    "max_rainfall_3d",
    "max_rainfall_7d",
    "max_wl_zscore",
    "max_q_zscore",
    "human_impact_count",
    "death_recorded",
    "houses_destroyed_recorded",
    "houses_damaged_recorded"
]

display(
    episode_impact[display_columns]
)

,desinventar_id,disaster_date,district,ds_division,regional_episode_id,episode_start_y,episode_end_y,station_count_y,max_rainfall_3d,max_rainfall_7d,max_wl_zscore,max_q_zscore,human_impact_count,death_recorded,houses_destroyed_recorded,houses_damaged_recorded
0,138102,2015-10-13,Kegalle,Kegalle,KELANI_EP002,2015-10-13,2015-10-13,1,174.1,232.9,1.714657,2.532219,8.0,False,False,True
1,138098,2015-10-14,Kegalle,Kegalle,KELANI_EP002,2015-10-13,2015-10-13,1,174.1,232.9,1.714657,2.532219,4.0,False,False,True
2,138119,2015-10-18,Kegalle,Yatiyanthota,KELANI_EP003,2015-10-19,2015-10-24,3,200.7,332.9,2.755908,2.848592,8.0,False,False,True
3,138143,2015-10-22,Kegalle,Kegalle,KELANI_EP003,2015-10-19,2015-10-24,3,200.7,332.9,2.755908,2.848592,5.0,False,False,True
4,138156,2015-10-25,Kegalle,Ruwanwella,KELANI_EP003,2015-10-19,2015-10-24,3,200.7,332.9,2.755908,2.848592,3.0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,142787,2019-08-13,Ratnapura,Kiriella,KELANI_EP025,2019-08-12,2019-08-14,3,248.8,332.1,3.924183,4.247715,312.0,False,False,False
67,142777,2019-08-13,Ratnapura,Ratnapura,KELANI_EP025,2019-08-12,2019-08-14,3,248.8,332.1,3.924183,4.247715,1788.0,False,False,True
68,143183,2019-10-15,Kegalle,Aranayaka,KELANI_EP029,2019-10-13,2019-10-24,4,194.5,320.5,3.651233,3.847054,4.0,False,False,True
69,143303,2019-10-21,Kegalle,Dehiovita,KELANI_EP029,2019-10-13,2019-10-24,4,194.5,320.5,3.651233,3.847054,48.0,False,False,False
70,143803,2019-12-05,Ratnapura,Pelmadulla,KELANI_EP030,2019-11-30,2019-12-01,2,172.4,273.9,2.961774,3.398996,40.0,False,False,False

In [174]:
print("Candidate episode-impact records:", len(episode_impact))
print("Unique regional episodes:", episode_impact["regional_episode_id"].nunique())
print("Unique DS divisions:", episode_impact["ds_division"].nunique())

display(
    episode_impact[
        [
            "desinventar_id",
            "disaster_date",
            "district",
            "ds_division",
            "regional_episode_id",
            "episode_start",
            "episode_end",
            "station_count",
            "station_event_count",
            "max_rainfall_3d",
            "max_rainfall_7d",
            "max_wl_zscore",
            "max_q_zscore",
            "human_impact_count",
            "death_recorded",
            "houses_destroyed_recorded",
            "houses_damaged_recorded"
        ]
    ]
)

Candidate episode-impact records: 71
Unique regional episodes: 15
Unique DS divisions: 27

KeyError: "['episode_start', 'episode_end', 'station_count', 'station_event_count'] not in index"

In [175]:
# --------------------------------------------------
# STEP 12: CREATE CLEAN EPISODE-IMPACT TABLE
# --------------------------------------------------

episode_impact_clean = episode_impact[
    [
        "desinventar_id",
        "disaster_date",
        "district",
        "ds_division",
        "regional_episode_id",
        "episode_start_y",
        "episode_end_y",
        "station_count_y",
        "station_event_count_y",
        "max_rainfall_3d",
        "max_rainfall_7d",
        "max_wl_zscore",
        "max_q_zscore",
        "human_impact_count",
        "death_recorded",
        "houses_destroyed_recorded",
        "houses_damaged_recorded"
    ]
].copy()

# Rename only the columns we need
episode_impact_clean = episode_impact_clean.rename(
    columns={
        "episode_start_y": "episode_start",
        "episode_end_y": "episode_end",
        "station_count_y": "station_count",
        "station_event_count_y": "station_event_count"
    }
)

print("Candidate episode-impact records:", len(episode_impact_clean))
print(
    "Unique regional episodes:",
    episode_impact_clean["regional_episode_id"].nunique()
)
print(
    "Unique DS divisions:",
    episode_impact_clean["ds_division"].nunique()
)

print("\nFinal columns:")
print(episode_impact_clean.columns.tolist())

display(episode_impact_clean)

Candidate episode-impact records: 71
Unique regional episodes: 15
Unique DS divisions: 27

Final columns:
['desinventar_id', 'disaster_date', 'district', 'ds_division', 'regional_episode_id', 'episode_start', 'episode_end', 'station_count', 'station_event_count', 'max_rainfall_3d', 'max_rainfall_7d', 'max_wl_zscore', 'max_q_zscore', 'human_impact_count', 'death_recorded', 'houses_destroyed_recorded', 'houses_damaged_recorded']

,desinventar_id,disaster_date,district,ds_division,regional_episode_id,episode_start,episode_end,station_count,station_event_count,max_rainfall_3d,max_rainfall_7d,max_wl_zscore,max_q_zscore,human_impact_count,death_recorded,houses_destroyed_recorded,houses_damaged_recorded
0,138102,2015-10-13,Kegalle,Kegalle,KELANI_EP002,2015-10-13,2015-10-13,1,1,174.1,232.9,1.714657,2.532219,8.0,False,False,True
1,138098,2015-10-14,Kegalle,Kegalle,KELANI_EP002,2015-10-13,2015-10-13,1,1,174.1,232.9,1.714657,2.532219,4.0,False,False,True
2,138119,2015-10-18,Kegalle,Yatiyanthota,KELANI_EP003,2015-10-19,2015-10-24,3,7,200.7,332.9,2.755908,2.848592,8.0,False,False,True
3,138143,2015-10-22,Kegalle,Kegalle,KELANI_EP003,2015-10-19,2015-10-24,3,7,200.7,332.9,2.755908,2.848592,5.0,False,False,True
4,138156,2015-10-25,Kegalle,Ruwanwella,KELANI_EP003,2015-10-19,2015-10-24,3,7,200.7,332.9,2.755908,2.848592,3.0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,142787,2019-08-13,Ratnapura,Kiriella,KELANI_EP025,2019-08-12,2019-08-14,3,3,248.8,332.1,3.924183,4.247715,312.0,False,False,False
67,142777,2019-08-13,Ratnapura,Ratnapura,KELANI_EP025,2019-08-12,2019-08-14,3,3,248.8,332.1,3.924183,4.247715,1788.0,False,False,True
68,143183,2019-10-15,Kegalle,Aranayaka,KELANI_EP029,2019-10-13,2019-10-24,4,8,194.5,320.5,3.651233,3.847054,4.0,False,False,True
69,143303,2019-10-21,Kegalle,Dehiovita,KELANI_EP029,2019-10-13,2019-10-24,4,8,194.5,320.5,3.651233,3.847054,48.0,False,False,False
70,143803,2019-12-05,Ratnapura,Pelmadulla,KELANI_EP030,2019-11-30,2019-12-01,2,2,172.4,273.9,2.961774,3.398996,40.0,False,False,False

In [176]:
from pathlib import Path

gis_root = project_root / "gis"

print("GIS folder:")
print(gis_root)

for path in sorted(gis_root.rglob("*")):
    if path.is_file():
        print(path.relative_to(project_root))

GIS folder:
/Users/ohaseelanka/disaster_analytics_hub/gis

In [177]:
import pandas as pd
from pathlib import Path

qgis_file = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/ds79_feature_matrix.csv"
)

qgis_features = pd.read_csv(qgis_file)

print("Shape:", qgis_features.shape)

print("\nColumns:")
print(qgis_features.columns.tolist())

print("\nFirst 5 rows:")
display(qgis_features.head())

Shape: (79, 38)

Columns:
['fid', 'adm3_name', 'adm3_name1', 'adm3_name2', 'adm3_name3', 'adm3_pcode', 'adm2_name', 'adm2_name1', 'adm2_name2', 'adm2_name3', 'adm2_pcode', 'adm1_name', 'adm1_name1', 'adm1_name2', 'adm1_name3', 'adm1_pcode', 'adm0_name', 'adm0_name1', 'adm0_name2', 'adm0_name3', 'adm0_pcode', 'valid_on', 'valid_to', 'area_sqkm', 'version', 'lang', 'lang1', 'lang2', 'lang3', 'center_lat', 'center_lon', 'total_road_m', 'COUNT', 'road_density', 'facility_count', 'Hub distance_HubName', 'Hub distance_HubDist', 'facility_density']

First 5 rows:

,fid,adm3_name,adm3_name1,adm3_name2,adm3_name3,adm3_pcode,adm2_name,adm2_name1,adm2_name2,adm2_name3,...,lang3,center_lat,center_lon,total_road_m,COUNT,road_density,facility_count,Hub distance_HubName,Hub distance_HubDist,facility_density
0,1,Colombo,කොළඹ,கொழும்பு,NaN,LK1103,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,...,NaN,6.946987,79.865263,4.004475e+05,3133,16.320050,213,Old Town Hall,0.480685,8.680714
1,2,Kolonnawa,කොලොන්නාව,கொலன்னாவை,NaN,LK1106,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,...,NaN,6.934943,79.914709,3.693511e+05,2359,14.245240,56,Dharmapala Vidalaya,0.411989,2.159824
2,3,Kaduwela,කඩුවෙල,கடுவெலை,NaN,LK1109,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,...,NaN,6.901985,79.972773,1.016346e+06,6650,11.717451,219,Supreme City Children's Playground,0.345704,2.524850
3,4,Homagama,හෝමාගම,கோமகமை,NaN,LK1112,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,...,NaN,6.836353,80.024442,9.303959e+05,3892,7.732922,96,Pitipana Kiriberiyakele Crematorium and cemetery,0.648292,0.797897
4,5,Seethawaka,සීතාවක,சீதவாக்கை,NaN,LK1115,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,...,NaN,6.919902,80.152703,5.695109e+05,1602,3.901375,41,NaN,1.989135,0.280866

In [178]:
# --------------------------------------------------
# STEP 13: CHECK DS DIVISION NAME MATCHING
# --------------------------------------------------

qgis_ds = (
    qgis_features[
        [
            "adm3_name",
            "adm3_pcode",
            "adm2_name",
            "adm2_pcode",
            "area_sqkm",
            "center_lat",
            "center_lon",
            "total_road_m",
            "road_density",
            "facility_count",
            "Hub distance_HubName",
            "Hub distance_HubDist",
            "facility_density"
        ]
    ]
    .copy()
)

print("QGIS DS divisions:", len(qgis_ds))
print(
    "Unique QGIS DS names:",
    qgis_ds["adm3_name"].nunique()
)

print("\nQGIS DS divisions:")
display(
    qgis_ds[
        ["adm3_name", "adm3_pcode", "adm2_name"]
    ].sort_values(
        ["adm2_name", "adm3_name"]
    ).reset_index(drop=True)
)

QGIS DS divisions: 79
Unique QGIS DS names: 79

QGIS DS divisions:

      adm3_name adm3_pcode  adm2_name
0       Colombo     LK1103    Colombo
1      Dehiwala     LK1130    Colombo
2      Homagama     LK1112    Colombo
3      Kaduwela     LK1109    Colombo
4       Kesbewa     LK1136    Colombo
..          ...        ...        ...
74  Nivithigala     LK9136  Ratnapura
75    Opanayake     LK9121  Ratnapura
76   Pelmadulla     LK9124  Ratnapura
77    Ratnapura     LK9112  Ratnapura
78   Weligepola     LK9145  Ratnapura

[79 rows x 3 columns]

In [179]:
# --------------------------------------------------
# STEP 14: FLOOD DS DIVISIONS
# --------------------------------------------------

flood_ds = (
    episode_impact_clean[
        ["district", "ds_division"]
    ]
    .drop_duplicates()
    .sort_values(
        ["district", "ds_division"]
    )
    .reset_index(drop=True)
)

print("Unique DS divisions in flood records:", len(flood_ds))

display(flood_ds)

Unique DS divisions in flood records: 27

     district       ds_division
0     Kegalle         Aranayaka
1     Kegalle  Bulathkohupitiya
2     Kegalle         Dehiovita
3     Kegalle      Deraniyagala
4     Kegalle        Galigamuwa
5     Kegalle           Kegalle
6     Kegalle         Mawanella
7     Kegalle        Rambukkana
8     Kegalle        Ruwanwella
9     Kegalle        Warakapola
10    Kegalle      Yatiyanthota
11  Ratnapura           Ayagama
12  Ratnapura         Balangoda
13  Ratnapura       Eheliyagoda
14  Ratnapura          Elapatha
15  Ratnapura      Embilipitiya
16  Ratnapura        Godakawela
17  Ratnapura         Kahawatta
18  Ratnapura          Kalawana
19  Ratnapura          Kiriella
20  Ratnapura           Kolonna
21  Ratnapura          Kuruvita
22  Ratnapura       Nivithigala
23  Ratnapura         Opanayaka
24  Ratnapura        Pelmadulla
25  Ratnapura         Ratnapura
26  Ratnapura        Weligepola

In [180]:
# --------------------------------------------------
# STEP 15: CHECK FLOOD DS NAMES AGAINST QGIS
# --------------------------------------------------

qgis_names = set(
    qgis_features["adm3_name"]
    .dropna()
    .astype(str)
    .str.strip()
)

flood_ds["qgis_name_match"] = (
    flood_ds["ds_division"]
    .astype(str)
    .str.strip()
    .isin(qgis_names)
)

print(
    "Flood DS divisions:",
    len(flood_ds)
)

print(
    "Direct QGIS name matches:",
    flood_ds["qgis_name_match"].sum()
)

print(
    "No direct QGIS name match:",
    (~flood_ds["qgis_name_match"]).sum()
)

print("\nPotential unmatched names:")

display(
    flood_ds[
        ~flood_ds["qgis_name_match"]
    ]
)

Flood DS divisions: 27
Direct QGIS name matches: 21
No direct QGIS name match: 6

Potential unmatched names:

     district       ds_division  qgis_name_match
0     Kegalle         Aranayaka            False
1     Kegalle  Bulathkohupitiya            False
2     Kegalle         Dehiovita            False
10    Kegalle      Yatiyanthota            False
17  Ratnapura         Kahawatta            False
23  Ratnapura         Opanayaka            False

In [181]:
# STEP 16 — Check QGIS names for the 6 unmatched DS divisions

unmatched_names = [
    "Aranayaka",
    "Bulathkohupitiya",
    "Dehiovita",
    "Yatiyanthota",
    "Kahawatta",
    "Opanayaka"
]

qgis_unmatched_candidates = (
    qgis_features[
        qgis_features["adm3_name"].astype(str).str.contains(
            "|".join(unmatched_names),
            case=False,
            na=False
        )
    ][
        [
            "adm3_name",
            "adm3_pcode",
            "adm2_name",
            "adm2_pcode",
            "area_sqkm",
            "center_lat",
            "center_lon"
        ]
    ]
    .sort_values(["adm2_name", "adm3_name"])
    .reset_index(drop=True)
)

display(qgis_unmatched_candidates)

Empty DataFrame
Columns: [adm3_name, adm3_pcode, adm2_name, adm2_pcode, area_sqkm, center_lat, center_lon]
Index: []

In [182]:
# STEP 17 — Display all Kegalle and Ratnapura DS divisions from QGIS

qgis_kegalle_ratnapura = (
    qgis_features[
        qgis_features["adm2_name"].astype(str).str.strip().isin(
            ["Kegalle", "Ratnapura"]
        )
    ][
        [
            "adm3_name",
            "adm3_pcode",
            "adm2_name",
            "adm2_pcode",
            "area_sqkm",
            "center_lat",
            "center_lon"
        ]
    ]
    .sort_values(["adm2_name", "adm3_name"])
    .reset_index(drop=True)
)

display(qgis_kegalle_ratnapura)

,adm3_name,adm3_pcode,adm2_name,adm2_pcode,area_sqkm,center_lat,center_lon
0,Aranayake,LK9209,Kegalle,LK92,120.094898,7.158896,80.450421
1,Bulathkohipitiya,LK9224,Kegalle,LK92,125.266065,7.107101,80.347375
2,Dehiowita,LK9230,Kegalle,LK92,193.948087,6.937338,80.264818
3,Deraniyagala,LK9233,Kegalle,LK92,222.157864,6.914293,80.375294
4,Galigamuwa,LK9215,Kegalle,LK92,124.589823,7.213872,80.313400
5,Kegalle,LK9212,Kegalle,LK92,106.253692,7.201406,80.364440
6,Mawanella,LK9206,Kegalle,LK92,120.094023,7.225226,80.494171
7,Rambukkana,LK9203,Kegalle,LK92,127.792892,7.321908,80.388898
8,Ruwanwella,LK9221,Kegalle,LK92,140.637891,7.067041,80.222522
9,Warakapola,LK9218,Kegalle,LK92,196.982135,7.205965,80.235193
10,Yatiyantota,LK9227,Kegalle,LK92,179.914723,7.018502,80.370140
11,Ayagama,LK9130,Ratnapura,LK91,163.354507,6.642544,80.291477
12,Balangoda,LK9118,Ratnapura,LK91,183.451426,6.659204,80.659184
13,Eheliyagoda,LK9103,Ratnapura,LK91,140.971448,6.841765,80.239442
14,Elapatha,LK9127,Ratnapura,LK91,85.606743,6.661977,80.356103
15,Embilipitiya,LK9148,Ratnapura,LK91,388.816920,6.359565,80.802696
16,Godakawela,LK9142,Ratnapura,LK91,152.121084,6.509197,80.641462
17,Imbulpe,LK9115,Ratnapura,LK91,255.010385,6.711979,80.736470
18,Kahawattha,LK9139,Ratnapura,LK91,104.248827,6.522633,80.549305
19,Kalawana,LK9133,Ratnapura,LK91,382.398966,6.474673,80.448525
20,Kalthota,LK9154,Ratnapura,LK91,97.635369,6.601114,80.845239
21,Kiriella,LK9109,Ratnapura,LK91,79.425895,6.759960,80.266635
22,Kolonna,LK9151,Ratnapura,LK91,177.845851,6.383262,80.686866
23,Kuruvita,LK9106,Ratnapura,LK91,171.016346,6.789412,80.342543
24,Nivithigala,LK9136,Ratnapura,LK91,153.456250,6.556131,80.458402
25,Opanayake,LK9121,Ratnapura,LK91,79.287949,6.606780,80.620244
26,Pelmadulla,LK9124,Ratnapura,LK91,146.678668,6.639002,80.493516
27,Ratnapura,LK9112,Ratnapura,LK91,327.733666,6.742331,80.484428
28,Weligepola,LK9145,Ratnapura,LK91,198.015452,6.541747,80.725760

In [183]:
# STEP 18 — Standardize flood DS names for joining with QGIS features

ds_name_mapping = {
    "Aranayaka": "Aranayake",
    "Bulathkohupitiya": "Bulathkohipitiya",
    "Dehiovita": "Dehiowita",
    "Yatiyanthota": "Yatiyantota",
    "Kahawatta": "Kahawattha",
    "Opanayaka": "Opanayake"
}

flood_ds["qgis_ds_name"] = (
    flood_ds["ds_division"]
    .astype(str)
    .str.strip()
    .replace(ds_name_mapping)
)

display(flood_ds)

     district       ds_division  qgis_name_match      qgis_ds_name
0     Kegalle         Aranayaka            False         Aranayake
1     Kegalle  Bulathkohupitiya            False  Bulathkohipitiya
2     Kegalle         Dehiovita            False         Dehiowita
3     Kegalle      Deraniyagala             True      Deraniyagala
4     Kegalle        Galigamuwa             True        Galigamuwa
5     Kegalle           Kegalle             True           Kegalle
6     Kegalle         Mawanella             True         Mawanella
7     Kegalle        Rambukkana             True        Rambukkana
8     Kegalle        Ruwanwella             True        Ruwanwella
9     Kegalle        Warakapola             True        Warakapola
10    Kegalle      Yatiyanthota            False       Yatiyantota
11  Ratnapura           Ayagama             True           Ayagama
12  Ratnapura         Balangoda             True         Balangoda
13  Ratnapura       Eheliyagoda             True       Eheliyagoda
14  Ratnapura          Elapatha             True          Elapatha
15  Ratnapura      Embilipitiya             True      Embilipitiya
16  Ratnapura        Godakawela             True        Godakawela
17  Ratnapura         Kahawatta            False        Kahawattha
18  Ratnapura          Kalawana             True          Kalawana
19  Ratnapura          Kiriella             True          Kiriella
20  Ratnapura           Kolonna             True           Kolonna
21  Ratnapura          Kuruvita             True          Kuruvita
22  Ratnapura       Nivithigala             True       Nivithigala
23  Ratnapura         Opanayaka            False         Opanayake
24  Ratnapura        Pelmadulla             True        Pelmadulla
25  Ratnapura         Ratnapura             True         Ratnapura
26  Ratnapura        Weligepola             True        Weligepola

In [184]:
# STEP 19 — Verify that all 27 flood DS divisions now match QGIS

qgis_name_set = set(
    qgis_features["adm3_name"]
    .dropna()
    .astype(str)
    .str.strip()
)

flood_ds["qgis_match_after_mapping"] = (
    flood_ds["qgis_ds_name"].isin(qgis_name_set)
)

print(
    "Flood DS divisions:",
    len(flood_ds)
)

print(
    "Matched to QGIS:",
    flood_ds["qgis_match_after_mapping"].sum()
)

print(
    "Still unmatched:",
    (~flood_ds["qgis_match_after_mapping"]).sum()
)

display(
    flood_ds[
        ~flood_ds["qgis_match_after_mapping"]
    ]
)

Flood DS divisions: 27
Matched to QGIS: 27
Still unmatched: 0

Empty DataFrame
Columns: [district, ds_division, qgis_name_match, qgis_ds_name, qgis_match_after_mapping]
Index: []

In [185]:
# STEP 20 — Attach QGIS DS P-codes to flood DS divisions

qgis_ds_lookup = (
    qgis_features[
        [
            "adm3_name",
            "adm3_pcode",
            "adm2_name",
            "adm2_pcode",
            "area_sqkm",
            "center_lat",
            "center_lon",
            "total_road_m",
            "road_density",
            "facility_count",
            "Hub distance_HubName",
            "Hub distance_HubDist",
            "facility_density"
        ]
    ]
    .drop_duplicates(subset=["adm3_pcode"])
    .copy()
)

flood_ds_qgis = flood_ds.merge(
    qgis_ds_lookup,
    left_on="qgis_ds_name",
    right_on="adm3_name",
    how="left",
    validate="one_to_one"
)

print("Flood DS rows:", len(flood_ds_qgis))
print("Rows with QGIS P-code:", flood_ds_qgis["adm3_pcode"].notna().sum())
print("Rows without QGIS P-code:", flood_ds_qgis["adm3_pcode"].isna().sum())

display(
    flood_ds_qgis[
        [
            "district",
            "ds_division",
            "qgis_ds_name",
            "adm3_pcode",
            "adm2_name",
            "area_sqkm",
            "road_density",
            "facility_count",
            "facility_density",
            "Hub distance_HubDist"
        ]
    ]
)

Flood DS rows: 27
Rows with QGIS P-code: 27
Rows without QGIS P-code: 0

,district,ds_division,qgis_ds_name,adm3_pcode,adm2_name,area_sqkm,road_density,facility_count,facility_density,Hub distance_HubDist
0,Kegalle,Aranayaka,Aranayake,LK9209,Kegalle,120.094898,1.758800,3,0.024980,1.802790
1,Kegalle,Bulathkohupitiya,Bulathkohipitiya,LK9224,Kegalle,125.266065,1.951012,9,0.071847,1.991905
2,Kegalle,Dehiovita,Dehiowita,LK9230,Kegalle,193.948087,1.805159,16,0.082496,3.292820
3,Kegalle,Deraniyagala,Deraniyagala,LK9233,Kegalle,222.157864,1.293385,11,0.049514,1.903905
4,Kegalle,Galigamuwa,Galigamuwa,LK9215,Kegalle,124.589823,2.240352,32,0.256843,2.067029
5,Kegalle,Kegalle,Kegalle,LK9212,Kegalle,106.253692,2.680448,38,0.357635,0.675170
6,Kegalle,Mawanella,Mawanella,LK9206,Kegalle,120.094023,2.295291,47,0.391360,0.727012
7,Kegalle,Rambukkana,Rambukkana,LK9203,Kegalle,127.792892,2.175840,22,0.172154,0.423939
8,Kegalle,Ruwanwella,Ruwanwella,LK9221,Kegalle,140.637891,2.074469,17,0.120878,4.308172
9,Kegalle,Warakapola,Warakapola,LK9218,Kegalle,196.982135,1.932134,22,0.111685,2.662864
10,Kegalle,Yatiyanthota,Yatiyantota,LK9227,Kegalle,179.914723,1.656417,23,0.127838,2.939705
11,Ratnapura,Ayagama,Ayagama,LK9130,Ratnapura,163.354507,3.096403,9,0.055095,0.446427
12,Ratnapura,Balangoda,Balangoda,LK9118,Ratnapura,183.451426,1.900564,16,0.087217,1.352196
13,Ratnapura,Eheliyagoda,Eheliyagoda,LK9103,Ratnapura,140.971448,2.726110,60,0.425618,2.670559
14,Ratnapura,Elapatha,Elapatha,LK9127,Ratnapura,85.606743,4.117022,6,0.070088,1.796260
15,Ratnapura,Embilipitiya,Embilipitiya,LK9148,Ratnapura,388.816920,2.313747,40,0.102876,1.106703
16,Ratnapura,Godakawela,Godakawela,LK9142,Ratnapura,152.121084,2.213563,23,0.151195,0.841767
17,Ratnapura,Kahawatta,Kahawattha,LK9139,Ratnapura,104.248827,1.672069,5,0.047962,1.507506
18,Ratnapura,Kalawana,Kalawana,LK9133,Ratnapura,382.398966,1.316577,11,0.028766,4.257788
19,Ratnapura,Kiriella,Kiriella,LK9109,Ratnapura,79.425895,3.511879,13,0.163675,0.530507
20,Ratnapura,Kolonna,Kolonna,LK9151,Ratnapura,177.845851,1.697153,16,0.089966,0.941208
21,Ratnapura,Kuruvita,Kuruvita,LK9106,Ratnapura,171.016346,2.557806,24,0.140337,1.491240
22,Ratnapura,Nivithigala,Nivithigala,LK9136,Ratnapura,153.456250,2.442601,25,0.162913,1.593851
23,Ratnapura,Opanayaka,Opanayake,LK9121,Ratnapura,79.287949,2.012129,17,0.214408,0.582954
24,Ratnapura,Pelmadulla,Pelmadulla,LK9124,Ratnapura,146.678668,2.859830,15,0.102264,0.296161
25,Ratnapura,Ratnapura,Ratnapura,LK9112,Ratnapura,327.733666,2.225119,83,0.253254,2.215960
26,Ratnapura,Weligepola,Weligepola,LK9145,Ratnapura,198.015452,0.990470,4,0.020200,1.872019

In [186]:
# STEP 21 — Check Census coverage for the 27 flood DS divisions

census_ds = (
    census_master[
        [
            "district_name",
            "ds_name",
            "ds_code",
            "gn_key",
            "total_population",
            "male",
            "female",
            "age_0_14",
            "age_15_59",
            "age_60_64",
            "age_65_plus",
            "occupied_housing_units"
        ]
    ]
    .copy()
)

# Get unique DS divisions from Census
census_ds_summary = (
    census_ds[
        ["district_name", "ds_name", "ds_code"]
    ]
    .drop_duplicates()
)

# Match our flood DS list to Census
flood_census_check = flood_ds_qgis[
    [
        "district",
        "ds_division",
        "adm3_pcode"
    ]
].copy()

flood_census_check = flood_census_check.merge(
    census_ds_summary,
    left_on=["district", "ds_division"],
    right_on=["district_name", "ds_name"],
    how="left"
)

flood_census_check["census_match"] = (
    flood_census_check["ds_code"].notna()
)

print("Flood DS divisions:", len(flood_census_check))
print("Census matches:", flood_census_check["census_match"].sum())
print("Census unmatched:", (~flood_census_check["census_match"]).sum())

display(
    flood_census_check[
        ~flood_census_check["census_match"]
    ]
)

NameError: name 'census_master' is not defined

In [187]:
from pathlib import Path
import pandas as pd

census_master_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/processed/census_gn_master.parquet"
)

census_master = pd.read_parquet(census_master_path)

print("Census master shape:", census_master.shape)
print("Columns:")
print(census_master.columns.tolist())

Census master shape: (14008, 60)
Columns:
['province_code', 'province_name', 'district_code', 'district_name', 'ds_code', 'ds_name', 'gn_code', 'gn_name', 'total_population', 'male', 'female', 'age_total', 'age_0_14', 'age_15_59', 'age_60_64', 'age_65_plus', 'elderly_60_plus', 'children_ratio', 'elderly_ratio', 'female_ratio', 'gn_key', 'occupied_housing_units', 'number_of_households', 'water_protected_well', 'water_semi_protected_well', 'water_unprotected_well', 'water_tube_well', 'water_spring_fountain', 'water_national_water_supply', 'water_local_authority', 'water_community_organization', 'water_private_supply', 'water_tank_river_stream', 'water_rain_water', 'water_bottled', 'water_filter_ro_plant', 'water_bowser', 'water_other', 'cooking_firewood', 'cooking_kerosene', 'cooking_gas', 'cooking_electricity', 'cooking_sawdust_paddy_husk', 'cooking_biogas', 'cooking_other', 'cooking_not_relevant', 'lighting_national_grid_hydro', 'lighting_kerosene_lamp', 'lighting_solar_grid', 'lighting_solar_standalone', 'lighting_biogas', 'lighting_generator', 'lighting_other', 'toilet_within_unit_exclusive', 'toilet_within_unit_shared', 'toilet_within_premises_exclusive', 'toilet_within_premises_shared', 'toilet_no_toilet_shared_elsewhere', 'toilet_common_public', 'toilet_no_toilet']

In [188]:
# STEP 21B — Check Census coverage for the 27 flood DS divisions

census_ds_summary = (
    census_master[
        ["district_name", "ds_name", "ds_code"]
    ]
    .drop_duplicates()
    .copy()
)

flood_census_check = flood_ds_qgis[
    [
        "district",
        "ds_division",
        "adm3_pcode"
    ]
].copy()

flood_census_check = flood_census_check.merge(
    census_ds_summary,
    left_on=["district", "ds_division"],
    right_on=["district_name", "ds_name"],
    how="left"
)

flood_census_check["census_match"] = (
    flood_census_check["ds_code"].notna()
)

print("Flood DS divisions:", len(flood_census_check))
print("Census matches:", flood_census_check["census_match"].sum())
print("Census unmatched:", (~flood_census_check["census_match"]).sum())

print("\nUnmatched DS divisions:")
display(
    flood_census_check[
        ~flood_census_check["census_match"]
    ][
        ["district", "ds_division"]
    ]
)

Flood DS divisions: 27
Census matches: 26
Census unmatched: 1

Unmatched DS divisions:

     district ds_division
23  Ratnapura   Opanayaka

In [189]:
# STEP 21C — Find the Census name used for Opanayaka DS

opanayaka_census = (
    census_master[
        census_master["district_name"].astype(str).str.strip().eq("Ratnapura")
    ][
        ["district_name", "ds_name", "ds_code"]
    ]
    .drop_duplicates()
    .sort_values("ds_name")
    .reset_index(drop=True)
)

display(
    opanayaka_census[
        opanayaka_census["ds_name"]
        .astype(str)
        .str.contains("Opan", case=False, na=False)
    ]
)

   district_name    ds_name  ds_code
14     Ratnapura  Opanayake       21

In [190]:
# STEP 21D — Standardize the Census DS name to match our flood DS naming

census_master["ds_name_join"] = (
    census_master["ds_name"]
    .astype("string")
    .str.strip()
)

census_master["ds_name_join"] = (
    census_master["ds_name_join"]
    .replace({
        "Opanayake": "Opanayaka"
    })
)

print(
    "Unique Census DS divisions after standardization:",
    census_master["ds_name_join"].nunique()
)

print("\nOpanayaka Census records:")
display(
    census_master[
        census_master["ds_name_join"] == "Opanayaka"
    ][
        [
            "district_name",
            "ds_name",
            "ds_name_join",
            "ds_code",
            "gn_code",
            "gn_name",
            "total_population"
        ]
    ].head(10)
)

Unique Census DS divisions after standardization: 340

Opanayaka Census records:

,district_name,ds_name,ds_name_join,ds_code,gn_code,gn_name,total_population
13116,Ratnapura,Opanayake,Opanayaka,21,5,Polwattahena,1000
13117,Ratnapura,Opanayake,Opanayaka,21,10,Metihakwala,1104
13118,Ratnapura,Opanayake,Opanayaka,21,15,Malmeekanda,1250
13119,Ratnapura,Opanayake,Opanayaka,21,20,Meegahawela,1828
13120,Ratnapura,Opanayake,Opanayaka,21,25,Kendaketiya,614
13121,Ratnapura,Opanayake,Opanayaka,21,30,Pelendakanda,1425
13122,Ratnapura,Opanayake,Opanayaka,21,35,Madola,1021
13123,Ratnapura,Opanayake,Opanayaka,21,40,Udawela,979
13124,Ratnapura,Opanayake,Opanayaka,21,45,Opanayaka,2657
13125,Ratnapura,Opanayake,Opanayaka,21,50,Hunuwala North,2328

In [191]:
# STEP 21E — Verify all 27 flood DS divisions match Census

census_ds_lookup = (
    census_master[
        ["district_name", "ds_name_join", "ds_code"]
    ]
    .drop_duplicates()
    .copy()
)

flood_census_final_check = flood_ds_qgis[
    [
        "district",
        "ds_division",
        "adm3_pcode"
    ]
].copy()

flood_census_final_check = flood_census_final_check.merge(
    census_ds_lookup,
    left_on=["district", "ds_division"],
    right_on=["district_name", "ds_name_join"],
    how="left"
)

flood_census_final_check["census_match"] = (
    flood_census_final_check["ds_code"].notna()
)

print("Flood DS divisions:", len(flood_census_final_check))
print("Census matches:", flood_census_final_check["census_match"].sum())
print("Census unmatched:", (~flood_census_final_check["census_match"]).sum())

print("\nUnmatched:")
display(
    flood_census_final_check[
        ~flood_census_final_check["census_match"]
    ][
        ["district", "ds_division"]
    ]
)

Flood DS divisions: 27
Census matches: 27
Census unmatched: 0

Unmatched:

Empty DataFrame
Columns: [district, ds_division]
Index: []

In [192]:
# STEP 22 — Aggregate GN-level Census data to DS level

# Count variables that should be summed from GN → DS
sum_columns = [
    "total_population",
    "male",
    "female",
    "age_total",
    "age_0_14",
    "age_15_59",
    "age_60_64",
    "age_65_plus",
    "elderly_60_plus",
    "occupied_housing_units",
    "number_of_households",

    # Water
    "water_protected_well",
    "water_semi_protected_well",
    "water_unprotected_well",
    "water_tube_well",
    "water_spring_fountain",
    "water_national_water_supply",
    "water_local_authority",
    "water_community_organization",
    "water_private_supply",
    "water_tank_river_stream",
    "water_rain_water",
    "water_bottled",
    "water_filter_ro_plant",
    "water_bowser",
    "water_other",

    # Cooking
    "cooking_firewood",
    "cooking_kerosene",
    "cooking_gas",
    "cooking_electricity",
    "cooking_sawdust_paddy_husk",
    "cooking_biogas",
    "cooking_other",
    "cooking_not_relevant",

    # Lighting
    "lighting_national_grid_hydro",
    "lighting_kerosene_lamp",
    "lighting_solar_grid",
    "lighting_solar_standalone",
    "lighting_biogas",
    "lighting_generator",
    "lighting_other",

    # Toilet
    "toilet_within_unit_exclusive",
    "toilet_within_unit_shared",
    "toilet_within_premises_exclusive",
    "toilet_within_premises_shared",
    "toilet_no_toilet_shared_elsewhere",
    "toilet_common_public",
    "toilet_no_toilet"
]

census_ds = (
    census_master
    .groupby(
        ["district_name", "ds_name_join", "ds_code"],
        as_index=False
    )[sum_columns]
    .sum(min_count=1)
)

print("DS-level Census rows:", len(census_ds))
print("DS-level Census columns:", len(census_ds.columns))

display(
    census_ds[
        [
            "district_name",
            "ds_name_join",
            "ds_code",
            "total_population",
            "male",
            "female",
            "age_0_14",
            "age_15_59",
            "age_60_64",
            "age_65_plus",
            "occupied_housing_units",
            "number_of_households"
        ]
    ].head(10)
)

DS-level Census rows: 340
DS-level Census columns: 51

,district_name,ds_name_join,ds_code,total_population,male,female,age_0_14,age_15_59,age_60_64,age_65_plus,occupied_housing_units,number_of_households
0,Ampara,Addalachchenai,33,53214,24354,28860,14612,33424,2042,3136,13178,13503
1,Ampara,Akkaraipattu,36,44979,21075,23904,12307,26735,2148,3789,12052,12300
2,Ampara,Alayadiwembu,39,24838,11868,12970,5786,15795,1154,2103,7017,7104
3,Ampara,Ampara,15,47868,23103,24765,10082,30524,2397,4865,13172,13241
4,Ampara,Damana,42,40325,19809,20516,8523,25141,2142,4519,11478,11501
5,Ampara,Dehiattakandiya,3,67274,33196,34078,15835,41573,3456,6410,18437,18627
6,Ampara,Irakkamam,34,17671,8435,9236,5632,10407,596,1036,4649,4674
7,Ampara,Kalmunai,24,52798,24929,27869,14465,31740,2562,4031,13481,14065
8,Ampara,Kalmunai North Sub,21,31556,14355,17201,7504,19153,1655,3244,8675,8960
9,Ampara,Karaitheevu,27,19493,9211,10282,5291,11671,924,1607,5241,5347

In [193]:
# STEP 23 — Create DS-level demographic H-E-S-C features

census_ds = census_ds.copy()

# --------------------------------------------------
# 1. Age-based sensitivity
# --------------------------------------------------

census_ds["children_0_14_ratio"] = (
    census_ds["age_0_14"] /
    census_ds["total_population"].replace(0, pd.NA)
)

census_ds["elderly_60_plus_ratio"] = (
    census_ds["elderly_60_plus"] /
    census_ds["total_population"].replace(0, pd.NA)
)

# --------------------------------------------------
# 2. Female population ratio
# --------------------------------------------------

census_ds["female_ratio"] = (
    census_ds["female"] /
    census_ds["total_population"].replace(0, pd.NA)
)

# --------------------------------------------------
# 3. Household / housing exposure
# --------------------------------------------------

census_ds["households_per_1000_population"] = (
    census_ds["number_of_households"] /
    census_ds["total_population"].replace(0, pd.NA)
) * 1000

census_ds["housing_units_per_1000_population"] = (
    census_ds["occupied_housing_units"] /
    census_ds["total_population"].replace(0, pd.NA)
) * 1000

# --------------------------------------------------
# 4. Basic household service indicators
# --------------------------------------------------

# Water sources that can indicate less reliable / more vulnerable access
census_ds["unprotected_well_households"] = (
    census_ds["water_unprotected_well"]
)

census_ds["river_stream_water_households"] = (
    census_ds["water_tank_river_stream"]
)

# Toilet access
census_ds["no_toilet_households"] = (
    census_ds["toilet_no_toilet"]
)

census_ds["public_toilet_households"] = (
    census_ds["toilet_common_public"]
)

# --------------------------------------------------
# 5. Convert service counts into proportions
# --------------------------------------------------

census_ds["unprotected_well_ratio"] = (
    census_ds["water_unprotected_well"] /
    census_ds["number_of_households"].replace(0, pd.NA)
)

census_ds["river_stream_water_ratio"] = (
    census_ds["water_tank_river_stream"] /
    census_ds["number_of_households"].replace(0, pd.NA)
)

census_ds["no_toilet_ratio"] = (
    census_ds["toilet_no_toilet"] /
    census_ds["number_of_households"].replace(0, pd.NA)
)

census_ds["public_toilet_ratio"] = (
    census_ds["toilet_common_public"] /
    census_ds["number_of_households"].replace(0, pd.NA)
)

# --------------------------------------------------
# Check
# --------------------------------------------------

feature_columns = [
    "total_population",
    "number_of_households",
    "occupied_housing_units",
    "children_0_14_ratio",
    "elderly_60_plus_ratio",
    "female_ratio",
    "households_per_1000_population",
    "housing_units_per_1000_population",
    "unprotected_well_ratio",
    "river_stream_water_ratio",
    "no_toilet_ratio",
    "public_toilet_ratio"
]

print("DS-level Census shape:", census_ds.shape)

display(
    census_ds[
        [
            "district_name",
            "ds_name_join",
            "ds_code"
        ] + feature_columns
    ].head(10)
)

DS-level Census shape: (340, 64)

,district_name,ds_name_join,ds_code,total_population,number_of_households,occupied_housing_units,children_0_14_ratio,elderly_60_plus_ratio,female_ratio,households_per_1000_population,housing_units_per_1000_population,unprotected_well_ratio,river_stream_water_ratio,no_toilet_ratio,public_toilet_ratio
0,Ampara,Addalachchenai,33,53214,13503,13178,0.274589,0.097305,0.542338,253.749013,247.641598,0.005480,0.000222,0.003999,0.000741
1,Ampara,Akkaraipattu,36,44979,12300,12052,0.273617,0.131995,0.531448,273.460948,267.947264,0.000732,0.000163,0.000569,0.000000
2,Ampara,Alayadiwembu,39,24838,7104,7017,0.232950,0.131130,0.522184,286.013367,282.510669,0.039274,0.000985,0.002956,0.000000
3,Ampara,Ampara,15,47868,13241,13172,0.210621,0.151709,0.517360,276.614858,275.173393,0.002492,0.000680,0.001813,0.000982
4,Ampara,Damana,42,40325,11501,11478,0.211358,0.165183,0.508766,285.207688,284.637322,0.006869,0.000522,0.003826,0.000435
5,Ampara,Dehiattakandiya,3,67274,18627,18437,0.235381,0.146654,0.506555,276.882600,274.058329,0.002255,0.001127,0.000913,0.000215
6,Ampara,Irakkamam,34,17671,4674,4649,0.318714,0.092355,0.522664,264.501160,263.086413,0.002567,0.000642,0.006632,0.000642
7,Ampara,Kalmunai,24,52798,14065,13481,0.273969,0.124872,0.527842,266.392666,255.331641,0.001138,0.000071,0.000569,0.000000
8,Ampara,Kalmunai North Sub,21,31556,8960,8675,0.237799,0.155248,0.545094,283.939663,274.908100,0.001674,0.000112,0.000335,0.000335
9,Ampara,Karaitheevu,27,19493,5347,5241,0.271431,0.129841,0.527471,274.303596,268.865747,0.000187,0.000748,0.000374,0.000561

In [194]:
# STEP 24 — Save DS-level Census features

census_ds_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/processed/census_ds_features.parquet"
)

census_ds.to_parquet(
    census_ds_path,
    index=False
)

print("Saved DS-level Census features to:")
print(census_ds_path)

print("\nShape:", census_ds.shape)
print("\nFile exists:", census_ds_path.exists())

Saved DS-level Census features to:
/Users/ohaseelanka/disaster_analytics_hub/data/processed/census_ds_features.parquet

Shape: (340, 64)

File exists: True

In [195]:
# STEP 25 — Combine Census + QGIS features for the 27 flood-study DS divisions

# Start from the QGIS-matched flood DS table
flood_ds_features = flood_ds_qgis.copy()

# Select the Census features we need
census_features = census_ds[
    [
        "district_name",
        "ds_name_join",
        "ds_code",
        "total_population",
        "male",
        "female",
        "age_0_14",
        "age_15_59",
        "age_60_64",
        "age_65_plus",
        "elderly_60_plus",
        "occupied_housing_units",
        "number_of_households",
        "children_0_14_ratio",
        "elderly_60_plus_ratio",
        "female_ratio",
        "households_per_1000_population",
        "housing_units_per_1000_population",
        "unprotected_well_ratio",
        "river_stream_water_ratio",
        "no_toilet_ratio",
        "public_toilet_ratio"
    ]
].copy()

# Merge using the validated standardized DS names
flood_ds_features = flood_ds_features.merge(
    census_features,
    left_on=["district", "ds_division"],
    right_on=["district_name", "ds_name_join"],
    how="left",
    validate="one_to_one"
)

# Check results
print("Flood DS feature table shape:", flood_ds_features.shape)

print(
    "Census population matched:",
    flood_ds_features["total_population"].notna().sum(),
    "/",
    len(flood_ds_features)
)

print(
    "Missing Census matches:",
    flood_ds_features["total_population"].isna().sum()
)

print("\nColumns:")
print(flood_ds_features.columns.tolist())

display(
    flood_ds_features[
        [
            "district",
            "ds_division",
            "adm3_pcode",
            "area_sqkm",
            "total_population",
            "number_of_households",
            "children_0_14_ratio",
            "elderly_60_plus_ratio",
            "female_ratio",
            "road_density",
            "facility_count",
            "facility_density",
            "Hub distance_HubDist"
        ]
    ].sort_values(
        ["district", "ds_division"]
    ).reset_index(drop=True)
)

Flood DS feature table shape: (27, 40)
Census population matched: 27 / 27
Missing Census matches: 0

Columns:
['district', 'ds_division', 'qgis_name_match', 'qgis_ds_name', 'qgis_match_after_mapping', 'adm3_name', 'adm3_pcode', 'adm2_name', 'adm2_pcode', 'area_sqkm', 'center_lat', 'center_lon', 'total_road_m', 'road_density', 'facility_count', 'Hub distance_HubName', 'Hub distance_HubDist', 'facility_density', 'district_name', 'ds_name_join', 'ds_code', 'total_population', 'male', 'female', 'age_0_14', 'age_15_59', 'age_60_64', 'age_65_plus', 'elderly_60_plus', 'occupied_housing_units', 'number_of_households', 'children_0_14_ratio', 'elderly_60_plus_ratio', 'female_ratio', 'households_per_1000_population', 'housing_units_per_1000_population', 'unprotected_well_ratio', 'river_stream_water_ratio', 'no_toilet_ratio', 'public_toilet_ratio']

,district,ds_division,adm3_pcode,area_sqkm,total_population,number_of_households,children_0_14_ratio,elderly_60_plus_ratio,female_ratio,road_density,facility_count,facility_density,Hub distance_HubDist
0,Kegalle,Aranayaka,LK9209,120.094898,69075,20062,0.204792,0.224249,0.527919,1.758800,3,0.024980,1.802790
1,Kegalle,Bulathkohupitiya,LK9224,125.266065,45237,12978,0.187678,0.221522,0.520393,1.951012,9,0.071847,1.991905
2,Kegalle,Dehiovita,LK9230,193.948087,84967,23403,0.192322,0.188803,0.511304,1.805159,16,0.082496,3.292820
3,Kegalle,Deraniyagala,LK9233,222.157864,44005,13080,0.198955,0.208045,0.514123,1.293385,11,0.049514,1.903905
4,Kegalle,Galigamuwa,LK9215,124.589823,73778,21224,0.183008,0.228849,0.524953,2.240352,32,0.256843,2.067029
5,Kegalle,Kegalle,LK9212,106.253692,94314,26825,0.185561,0.220773,0.527027,2.680448,38,0.357635,0.675170
6,Kegalle,Mawanella,LK9206,120.094023,126026,33333,0.223700,0.191572,0.525868,2.295291,47,0.391360,0.727012
7,Kegalle,Rambukkana,LK9203,127.792892,87055,24842,0.192706,0.220723,0.525484,2.175840,22,0.172154,0.423939
8,Kegalle,Ruwanwella,LK9221,140.637891,65797,18370,0.191893,0.209508,0.518656,2.074469,17,0.120878,4.308172
9,Kegalle,Warakapola,LK9218,196.982135,117967,32379,0.190469,0.214348,0.524206,1.932134,22,0.111685,2.662864
10,Kegalle,Yatiyanthota,LK9227,179.914723,62255,17541,0.200578,0.201044,0.512457,1.656417,23,0.127838,2.939705
11,Ratnapura,Ayagama,LK9130,163.354507,29944,8897,0.189387,0.197502,0.503139,3.096403,9,0.055095,0.446427
12,Ratnapura,Balangoda,LK9118,183.451426,74893,21276,0.214760,0.183956,0.513933,1.900564,16,0.087217,1.352196
13,Ratnapura,Eheliyagoda,LK9103,140.971448,74071,20443,0.193801,0.192383,0.507338,2.726110,60,0.425618,2.670559
14,Ratnapura,Elapatha,LK9127,85.606743,38429,10904,0.181452,0.197559,0.501991,4.117022,6,0.070088,1.796260
15,Ratnapura,Embilipitiya,LK9148,388.816920,160008,45965,0.230732,0.162086,0.509518,2.313747,40,0.102876,1.106703
16,Ratnapura,Godakawela,LK9142,152.121084,78541,22908,0.212500,0.191365,0.516800,2.213563,23,0.151195,0.841767
17,Ratnapura,Kahawatta,LK9139,104.248827,43708,12482,0.210122,0.184657,0.507367,1.672069,5,0.047962,1.507506
18,Ratnapura,Kalawana,LK9133,382.398966,50753,15180,0.204914,0.182965,0.505271,1.316577,11,0.028766,4.257788
19,Ratnapura,Kiriella,LK9109,79.425895,33631,9658,0.180905,0.210193,0.507270,3.511879,13,0.163675,0.530507
20,Ratnapura,Kolonna,LK9151,177.845851,50068,14854,0.221039,0.183890,0.501937,1.697153,16,0.089966,0.941208
21,Ratnapura,Kuruvita,LK9106,171.016346,97966,27041,0.188463,0.186718,0.504767,2.557806,24,0.140337,1.491240
22,Ratnapura,Nivithigala,LK9136,153.456250,59442,16782,0.199758,0.187342,0.504610,2.442601,25,0.162913,1.593851
23,Ratnapura,Opanayaka,LK9121,79.287949,27244,8139,0.202430,0.192189,0.514939,2.012129,17,0.214408,0.582954
24,Ratnapura,Pelmadulla,LK9124,146.678668,93818,26300,0.193119,0.188205,0.505351,2.859830,15,0.102264,0.296161
25,Ratnapura,Ratnapura,LK9112,327.733666,121166,33423,0.192405,0.181619,0.508468,2.225119,83,0.253254,2.215960
26,Ratnapura,Weligepola,LK9145,198.015452,34168,10677,0.204665,0.199807,0.502839,0.990470,4,0.020200,1.872019

In [196]:
# STEP 26 — Quality check for DS-level Census features

census_feature_check = flood_ds_features[
    [
        "district",
        "ds_division",
        "adm3_pcode",

        "total_population",
        "number_of_households",
        "occupied_housing_units",

        "children_0_14_ratio",
        "elderly_60_plus_ratio",
        "female_ratio",

        "households_per_1000_population",
        "housing_units_per_1000_population",

        "unprotected_well_ratio",
        "river_stream_water_ratio",
        "no_toilet_ratio",
        "public_toilet_ratio",

        "area_sqkm",
        "road_density",
        "facility_count",
        "facility_density"
    ]
].copy()

print("Feature-check shape:", census_feature_check.shape)

print("\nMissing values:")
print(
    census_feature_check.isna().sum()
)

print("\nSummary statistics:")
display(
    census_feature_check.describe().T
)

Feature-check shape: (27, 19)

Missing values:
district                             0
ds_division                          0
adm3_pcode                           0
total_population                     0
number_of_households                 0
occupied_housing_units               0
children_0_14_ratio                  0
elderly_60_plus_ratio                0
female_ratio                         0
households_per_1000_population       0
housing_units_per_1000_population    0
unprotected_well_ratio               0
river_stream_water_ratio             0
no_toilet_ratio                      0
public_toilet_ratio                  0
area_sqkm                            0
road_density                         0
facility_count                       0
facility_density                     0
dtype: int64

Summary statistics:

,count,mean,std,min,25%,50%,75%,max
total_population,27.0,71789.851852,33183.453860,27244.000000,44621.000000,69075.000000,90436.500000,160008.000000
number_of_households,27.0,20332.074074,9047.108258,8139.000000,13029.000000,20062.000000,25571.000000,45965.000000
occupied_housing_units,27.0,20173.407407,8989.630998,8102.000000,12933.500000,19811.000000,25334.500000,45752.000000
children_0_14_ratio,27.0,0.198967,0.013139,0.180905,0.189928,0.193801,0.204853,0.230732
elderly_60_plus_ratio,27.0,0.198217,0.016197,0.162086,0.187030,0.192383,0.209851,0.228849
female_ratio,27.0,0.512886,0.008658,0.501937,0.505311,0.511304,0.519524,0.527919
households_per_1000_population,27.0,285.982853,9.979524,264.493041,279.761031,285.359830,291.053624,312.485366
housing_units_per_1000_population,27.0,283.755867,9.990763,261.922143,277.916664,282.591465,287.186874,310.173262
unprotected_well_ratio,27.0,0.020787,0.010789,0.002915,0.013839,0.020451,0.025796,0.052824
river_stream_water_ratio,27.0,0.029414,0.025554,0.001528,0.008104,0.024945,0.035542,0.094251
no_toilet_ratio,27.0,0.001131,0.000624,0.000510,0.000772,0.001006,0.001257,0.003044
public_toilet_ratio,27.0,0.000837,0.001169,0.000000,0.000230,0.000399,0.001003,0.005845
area_sqkm,27.0,170.080077,80.545240,79.287949,122.342361,152.121084,188.699756,388.816920
road_density,27.0,2.204309,0.675716,0.990470,1.781979,2.175840,2.500204,4.117022
facility_count,27.0,22.481481,18.162451,3.000000,11.000000,17.000000,24.500000,83.000000
facility_density,27.0,0.143817,0.109555,0.020200,0.070968,0.111685,0.167914,0.425618

In [197]:
display(
    census_feature_check.describe().T
)

,count,mean,std,min,25%,50%,75%,max
total_population,27.0,71789.851852,33183.453860,27244.000000,44621.000000,69075.000000,90436.500000,160008.000000
number_of_households,27.0,20332.074074,9047.108258,8139.000000,13029.000000,20062.000000,25571.000000,45965.000000
occupied_housing_units,27.0,20173.407407,8989.630998,8102.000000,12933.500000,19811.000000,25334.500000,45752.000000
children_0_14_ratio,27.0,0.198967,0.013139,0.180905,0.189928,0.193801,0.204853,0.230732
elderly_60_plus_ratio,27.0,0.198217,0.016197,0.162086,0.187030,0.192383,0.209851,0.228849
female_ratio,27.0,0.512886,0.008658,0.501937,0.505311,0.511304,0.519524,0.527919
households_per_1000_population,27.0,285.982853,9.979524,264.493041,279.761031,285.359830,291.053624,312.485366
housing_units_per_1000_population,27.0,283.755867,9.990763,261.922143,277.916664,282.591465,287.186874,310.173262
unprotected_well_ratio,27.0,0.020787,0.010789,0.002915,0.013839,0.020451,0.025796,0.052824
river_stream_water_ratio,27.0,0.029414,0.025554,0.001528,0.008104,0.024945,0.035542,0.094251
no_toilet_ratio,27.0,0.001131,0.000624,0.000510,0.000772,0.001006,0.001257,0.003044
public_toilet_ratio,27.0,0.000837,0.001169,0.000000,0.000230,0.000399,0.001003,0.005845
area_sqkm,27.0,170.080077,80.545240,79.287949,122.342361,152.121084,188.699756,388.816920
road_density,27.0,2.204309,0.675716,0.990470,1.781979,2.175840,2.500204,4.117022
facility_count,27.0,22.481481,18.162451,3.000000,11.000000,17.000000,24.500000,83.000000
facility_density,27.0,0.143817,0.109555,0.020200,0.070968,0.111685,0.167914,0.425618

In [198]:
from pathlib import Path
import pandas as pd

landslide_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/raw/landslide/DesInventar_NuwaraEliya_Landslides_page1.xlsx"
)

landslide_raw = pd.read_excel(landslide_path)

print("Shape:", landslide_raw.shape)
print("\nColumns:")
print(landslide_raw.columns.tolist())

print("\nFirst 10 rows:")
display(landslide_raw.head(10))

Shape: (100, 17)

Columns:
['Serial', 'Event', 'Province', 'District', 'Division', 'Date', 'Location', 'Deaths', 'Injured', 'Missing', 'Houses Destroyed', 'Houses Damaged', 'Directly affected', 'Indirectly Affected', 'Relocated', 'Evacuated', 'Losses $USD']

First 10 rows:

,Serial,Event,Province,District,Division,Date,Location,Deaths,Injured,Missing,Houses Destroyed,Houses Damaged,Directly affected,Indirectly Affected,Relocated,Evacuated,Losses $USD
0,143772,LANDSLIDE,Central,Nuwara Eliya,Nuwara Eliya,2019/12/19,NaN,NaN,NaN,NaN,1.0,NaN,NaN,5.0,NaN,NaN,0
1,143771,LANDSLIDE,Central,Nuwara Eliya,Nuwara Eliya,2019/12/04,NaN,NaN,NaN,NaN,NaN,1.0,NaN,102.0,NaN,NaN,0
2,143757,LANDSLIDE,Central,Nuwara Eliya,Walapane,2019/11/30,NaN,3.0,NaN,1.0,1.0,NaN,NaN,75.0,NaN,NaN,0
3,143755,LANDSLIDE,Central,Nuwara Eliya,Nuwara Eliya,2019/11/30,NaN,NaN,NaN,NaN,NaN,5.0,NaN,59.0,NaN,NaN,0
4,143157,LANDSLIDE,Central,Nuwara Eliya,Nuwara Eliya,2019/10/08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,0
5,143156,LANDSLIDE,Central,Nuwara Eliya,Nuwara Eliya,2019/10/09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN,0
6,142965,LANDSLIDE,Central,Nuwara Eliya,Ambagamuwakorale,2019/09/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0,NaN,NaN,0
7,142763,LANDSLIDE,Central,Nuwara Eliya,Kothmale,2019/08/13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.0,NaN,NaN,0
8,142756,LANDSLIDE,Central,Nuwara Eliya,Nuwara Eliya,2019/08/13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,NaN,NaN,0
9,142478,LANDSLIDE,Central,Nuwara Eliya,Nuwara Eliya,2019/07/19,NaN,NaN,NaN,NaN,NaN,2.0,NaN,14.0,NaN,NaN,0

In [199]:
# Step 2 — Clean landslide DesInventar data

landslide = landslide_raw.copy()

# Standardize column names
landslide.columns = (
    landslide.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# Convert date
landslide["date"] = pd.to_datetime(
    landslide["date"],
    format="%Y/%m/%d",
    errors="coerce"
)

# Clean text fields
for col in ["event", "province", "district", "division"]:
    landslide[col] = (
        landslide[col]
        .astype("string")
        .str.strip()
    )

# Convert impact fields to numeric
impact_columns = [
    "deaths",
    "injured",
    "missing",
    "houses_destroyed",
    "houses_damaged",
    "directly_affected",
    "indirectly_affected",
    "relocated",
    "evacuated",
    "losses_$usd"
]

for col in impact_columns:
    landslide[col] = pd.to_numeric(
        landslide[col],
        errors="coerce"
    )

print("Cleaned shape:", landslide.shape)

print("\nDate range:")
print(landslide["date"].min(), "to", landslide["date"].max())

print("\nDistricts:")
print(landslide["district"].value_counts())

print("\nDS Divisions:")
print(landslide["division"].value_counts())

print("\nMissing values:")
display(landslide.isna().sum())

Cleaned shape: (100, 17)

Date range:
2003-05-17 00:00:00 to 2019-12-19 00:00:00

Districts:
district
Nuwara Eliya    100
Name: count, dtype: Int64

DS Divisions:
division
Nuwara Eliya        55
Ambagamuwakorale    15
Kothmale            14
Walapane            13
Hanguranketha        3
Name: count, dtype: Int64

Missing values:

serial                   0
event                    0
province                 0
district                 0
division                 0
date                     0
location                53
deaths                  94
injured                 97
missing                 99
houses_destroyed        81
houses_damaged          39
directly_affected      100
indirectly_affected      5
relocated              100
evacuated               99
losses_$usd              0
dtype: int64

In [200]:
# Step 3 — Landslide impact summary

impact_summary = pd.DataFrame({
    "records_with_value": [
        landslide["deaths"].notna().sum(),
        landslide["injured"].notna().sum(),
        landslide["missing"].notna().sum(),
        landslide["houses_destroyed"].notna().sum(),
        landslide["houses_damaged"].notna().sum(),
        landslide["indirectly_affected"].notna().sum(),
        landslide["directly_affected"].notna().sum(),
        landslide["relocated"].notna().sum(),
        landslide["evacuated"].notna().sum()
    ],
    "total_records": 100
}, index=[
    "Deaths",
    "Injured",
    "Missing",
    "Houses destroyed",
    "Houses damaged",
    "Indirectly affected",
    "Directly affected",
    "Relocated",
    "Evacuated"
])

impact_summary["missing_records"] = (
    impact_summary["total_records"]
    - impact_summary["records_with_value"]
)

display(impact_summary)

print("\nNumeric impact statistics:")
display(
    landslide[
        [
            "deaths",
            "injured",
            "missing",
            "houses_destroyed",
            "houses_damaged",
            "indirectly_affected",
            "relocated",
            "evacuated"
        ]
    ].describe()
)

print("\nRecords by year:")
display(
    landslide["date"]
    .dt.year
    .value_counts()
    .sort_index()
)

print("\nRecords by DS division:")
display(
    landslide["division"]
    .value_counts()
)

                     records_with_value  total_records  missing_records
Deaths                                6            100               94
Injured                               3            100               97
Missing                               1            100               99
Houses destroyed                     19            100               81
Houses damaged                       61            100               39
Indirectly affected                  95            100                5
Directly affected                     0            100              100
Relocated                             0            100              100
Evacuated                             1            100               99

Numeric impact statistics:

,deaths,injured,missing,houses_destroyed,houses_damaged,indirectly_affected,relocated,evacuated
count,6.000000,3.0,1.0,19.000000,61.000000,95.000000,0.0,1.0
mean,3.000000,1.0,1.0,2.052632,6.442623,191.505263,NaN,5.0
std,2.529822,0.0,NaN,1.840099,10.952206,1073.691186,NaN,NaN
min,1.000000,1.0,1.0,1.000000,1.000000,2.000000,NaN,5.0
25%,1.000000,1.0,1.0,1.000000,1.000000,5.000000,NaN,5.0
50%,2.000000,1.0,1.0,1.000000,2.000000,15.000000,NaN,5.0
75%,4.500000,1.0,1.0,2.500000,5.000000,71.500000,NaN,5.0
max,7.000000,1.0,1.0,7.000000,45.000000,10365.000000,NaN,5.0

Records by year:

date
2003     3
2006     3
2007    11
2008     7
2009    18
2010     8
2012     1
2013     8
2014    11
2015    10
2016     1
2017     2
2018     4
2019    13
Name: count, dtype: int64

Records by DS division:

division
Nuwara Eliya        55
Ambagamuwakorale    15
Kothmale            14
Walapane            13
Hanguranketha        3
Name: count, dtype: Int64

In [201]:
# Step 4 — Inspect temporal clustering of landslide records

landslide_dates = (
    landslide
    .groupby("date")
    .agg(
        record_count=("serial", "count"),
        ds_count=("division", "nunique"),
        ds_divisions=("division", lambda x: ", ".join(sorted(x.unique())))
    )
    .reset_index()
    .sort_values("date")
)

print("Unique landslide dates:", len(landslide_dates))
print("Total landslide records:", len(landslide))

print("\nDates with multiple landslide records:")
display(
    landslide_dates[
        landslide_dates["record_count"] > 1
    ]
)

print("\nMaximum records on one date:")
print(landslide_dates["record_count"].max())

Unique landslide dates: 80
Total landslide records: 100

Dates with multiple landslide records:

         date  record_count  ds_count                    ds_divisions
1  2003-05-18             2         1                    Nuwara Eliya
6  2007-01-13             4         1                        Walapane
7  2007-01-15             3         1                        Walapane
12 2008-06-01             2         1                Ambagamuwakorale
14 2008-11-25             2         1                    Nuwara Eliya
16 2009-05-20             2         2  Ambagamuwakorale, Nuwara Eliya
18 2009-05-24             3         1                        Kothmale
21 2009-06-11             2         2     Hanguranketha, Nuwara Eliya
22 2009-07-02             2         1                    Nuwara Eliya
41 2013-06-24             2         2         Hanguranketha, Kothmale
50 2014-09-26             2         2          Kothmale, Nuwara Eliya
58 2015-05-11             2         1                    Nuwara Eliya
65 2017-05-28             2         2          Kothmale, Nuwara Eliya
72 2019-07-19             2         2  Ambagamuwakorale, Nuwara Eliya
73 2019-08-13             2         2          Kothmale, Nuwara Eliya
77 2019-11-30             2         2          Nuwara Eliya, Walapane

Maximum records on one date:
4

In [203]:
# Step 5 — Examine gaps between unique landslide dates

landslide_dates = landslide_dates.sort_values("date").reset_index(drop=True)

landslide_dates["gap_days"] = (
    landslide_dates["date"].diff().dt.days
)

print("Gap statistics:")
display(
    landslide_dates["gap_days"]
    .describe()
)

print("\nSmallest gaps:")
display(
    landslide_dates[
        ["date", "record_count", "ds_count", "ds_divisions", "gap_days"]
    ].head(25)
)

print("\nLargest gaps:")
display(
    landslide_dates[
        ["date", "record_count", "ds_count", "ds_divisions", "gap_days"]
    ]
    .sort_values("gap_days", ascending=False)
    .head(20)
)

print("\nGap distribution:")
display(
    landslide_dates["gap_days"]
    .value_counts()
    .sort_index()
)

Gap statistics:

count     79.000000
mean      76.708861
std      145.048104
min        1.000000
25%        4.000000
50%       24.000000
75%       80.500000
max      972.000000
Name: gap_days, dtype: float64

Smallest gaps:

,date,record_count,ds_count,ds_divisions,gap_days
0,2003-05-17,1,1,Nuwara Eliya,NaN
1,2003-05-18,2,1,Nuwara Eliya,1.0
2,2006-01-14,1,1,Walapane,972.0
3,2006-04-01,1,1,Ambagamuwakorale,77.0
4,2006-11-15,1,1,Ambagamuwakorale,228.0
5,2007-01-11,1,1,Nuwara Eliya,57.0
6,2007-01-13,4,1,Walapane,2.0
7,2007-01-15,3,1,Walapane,2.0
8,2007-02-01,1,1,Walapane,17.0
9,2007-05-09,1,1,Walapane,97.0
10,2007-10-12,1,1,Walapane,156.0
11,2008-03-13,1,1,Nuwara Eliya,153.0
12,2008-06-01,2,1,Ambagamuwakorale,80.0
13,2008-06-02,1,1,Nuwara Eliya,1.0
14,2008-11-25,2,1,Nuwara Eliya,176.0
15,2008-12-08,1,1,Nuwara Eliya,13.0
16,2009-05-20,2,2,"Ambagamuwakorale, Nuwara Eliya",163.0
17,2009-05-23,1,1,Ambagamuwakorale,3.0
18,2009-05-24,3,1,Kothmale,1.0
19,2009-05-25,1,1,Nuwara Eliya,1.0
20,2009-05-26,1,1,Nuwara Eliya,1.0
21,2009-06-11,2,2,"Hanguranketha, Nuwara Eliya",16.0
22,2009-07-02,2,1,Nuwara Eliya,21.0
23,2009-07-03,1,1,Nuwara Eliya,1.0
24,2009-07-22,1,1,Nuwara Eliya,19.0

Largest gaps:

,date,record_count,ds_count,ds_divisions,gap_days
2,2006-01-14,1,1,Walapane,972.0
37,2012-07-09,1,1,Ambagamuwakorale,582.0
65,2017-05-28,2,2,"Kothmale, Nuwara Eliya",460.0
66,2018-04-25,1,1,Ambagamuwakorale,332.0
38,2013-05-24,1,1,Nuwara Eliya,319.0
4,2006-11-15,1,1,Ambagamuwakorale,228.0
70,2019-06-22,1,1,Nuwara Eliya,226.0
14,2008-11-25,2,1,Nuwara Eliya,176.0
67,2018-10-15,1,1,Ambagamuwakorale,173.0
16,2009-05-20,2,2,"Ambagamuwakorale, Nuwara Eliya",163.0
10,2007-10-12,1,1,Walapane,156.0
29,2010-04-20,1,1,Nuwara Eliya,155.0
11,2008-03-13,1,1,Nuwara Eliya,153.0
45,2014-04-30,1,1,Kothmale,140.0
33,2010-10-06,1,1,Nuwara Eliya,132.0
64,2016-02-23,1,1,Ambagamuwakorale,110.0
9,2007-05-09,1,1,Walapane,97.0
44,2013-12-11,1,1,Nuwara Eliya,93.0
25,2009-10-14,1,1,Nuwara Eliya,84.0
52,2014-12-18,1,1,Hanguranketha,81.0

Gap distribution:

gap_days
1.0      10
2.0       5
3.0       3
4.0       5
5.0       1
7.0       2
10.0      2
12.0      1
13.0      1
15.0      1
16.0      1
17.0      3
18.0      1
19.0      1
20.0      1
21.0      1
24.0      1
25.0      1
26.0      1
27.0      1
29.0      1
31.0      1
34.0      1
36.0      1
43.0      1
50.0      1
51.0      1
52.0      1
53.0      1
55.0      1
57.0      1
60.0      1
70.0      1
75.0      1
77.0      1
80.0      1
81.0      1
84.0      1
93.0      1
97.0      1
110.0     1
132.0     1
140.0     1
153.0     1
155.0     1
156.0     1
163.0     1
173.0     1
176.0     1
226.0     1
228.0     1
319.0     1
332.0     1
460.0     1
582.0     1
972.0     1
Name: count, dtype: int64

In [204]:
# Step 6 — Construct candidate landslide episodes
# Rule: a gap > 3 days starts a new episode

landslide_events = landslide.copy()

landslide_events = (
    landslide_events
    .sort_values(["date", "division", "serial"])
    .reset_index(drop=True)
)

# Gap between consecutive reported landslide dates
landslide_events["date_gap"] = (
    landslide_events["date"].diff().dt.days
)

# New episode when gap is greater than 3 days
landslide_events["new_episode"] = (
    landslide_events["date_gap"].isna() |
    (landslide_events["date_gap"] > 3)
)

# Assign episode number
landslide_events["episode_number"] = (
    landslide_events["new_episode"]
    .cumsum()
)

# Create readable episode ID
landslide_events["episode_id"] = (
    "NE_LS_EP"
    + landslide_events["episode_number"]
      .astype(int)
      .astype(str)
      .str.zfill(3)
)

print("Total incident records:", len(landslide_events))
print(
    "Candidate landslide episodes:",
    landslide_events["episode_id"].nunique()
)

print("\nRecords per episode:")
display(
    landslide_events
    .groupby("episode_id")
    .size()
    .describe()
)

Total incident records: 100
Candidate landslide episodes: 62

Records per episode:

count    62.000000
mean      1.612903
std       1.371308
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       8.000000
dtype: float64

In [205]:
# Step 7 — Inspect candidate landslide episodes

landslide_episode_summary = (
    landslide_events
    .groupby("episode_id", as_index=False)
    .agg(
        start_date=("date", "min"),
        end_date=("date", "max"),
        incident_count=("serial", "count"),
        ds_count=("division", "nunique"),
        ds_divisions=("division", lambda x: ", ".join(sorted(x.unique()))),
        total_deaths=("deaths", "sum", min_count=1),
        total_houses_destroyed=("houses_destroyed", "sum", min_count=1),
        total_houses_damaged=("houses_damaged", "sum", min_count=1),
        total_indirectly_affected=("indirectly_affected", "sum", min_count=1),
    )
)

landslide_episode_summary["duration_days"] = (
    landslide_episode_summary["end_date"]
    - landslide_episode_summary["start_date"]
).dt.days + 1

print("Candidate episodes:", len(landslide_episode_summary))

print("\nEpisodes with multiple incident records:")
display(
    landslide_episode_summary[
        landslide_episode_summary["incident_count"] > 1
    ].sort_values("start_date")
)

print("\nEpisodes involving multiple DS divisions:")
display(
    landslide_episode_summary[
        landslide_episode_summary["ds_count"] > 1
    ].sort_values("start_date")
)

print("\nEpisode duration statistics:")
display(
    landslide_episode_summary["duration_days"].describe()
)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3437172454.py, line 12)

In [206]:
# Step 7 — Inspect candidate landslide episodes

landslide_episode_summary = (
    landslide_events
    .groupby("episode_id", as_index=False)
    .agg(
        start_date=("date", "min"),
        end_date=("date", "max"),
        incident_count=("serial", "count"),
        ds_count=("division", "nunique"),
        ds_divisions=("division", lambda x: ", ".join(sorted(x.unique()))),
        total_deaths=("deaths", "sum", min_count=1),
        total_houses_destroyed=("houses_destroyed", "sum", min_count=1),
        total_houses_damaged=("houses_damaged", "sum", min_count=1),
        total_indirectly_affected=("indirectly_affected", "sum", min_count=1),
    )
)

landslide_episode_summary["duration_days"] = (
    landslide_episode_summary["end_date"]
    - landslide_episode_summary["start_date"]
).dt.days + 1

print("Candidate episodes:", len(landslide_episode_summary))

print("\nEpisodes with multiple incident records:")
display(
    landslide_episode_summary[
        landslide_episode_summary["incident_count"] > 1
    ].sort_values("start_date")
)

print("\nEpisodes involving multiple DS divisions:")
display(
    landslide_episode_summary[
        landslide_episode_summary["ds_count"] > 1
    ].sort_values("start_date")
)

print("\nEpisode duration statistics:")
display(
    landslide_episode_summary["duration_days"].describe()
)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3437172454.py, line 12)

In [207]:
# Step 7 — Inspect candidate landslide episodes

landslide_episode_summary = (
    landslide_events
    .groupby("episode_id", as_index=False)
    .agg(
        start_date=("date", "min"),
        end_date=("date", "max"),
        incident_count=("serial", "count"),
        ds_count=("division", "nunique"),
        ds_divisions=("division", lambda x: ", ".join(sorted(x.unique()))),
        total_deaths=("deaths", "sum"),
        total_houses_destroyed=("houses_destroyed", "sum"),
        total_houses_damaged=("houses_damaged", "sum"),
        total_indirectly_affected=("indirectly_affected", "sum")
    )
)

landslide_episode_summary["duration_days"] = (
    landslide_episode_summary["end_date"]
    - landslide_episode_summary["start_date"]
).dt.days + 1

print("Candidate episodes:", len(landslide_episode_summary))

print("\nEpisodes with multiple incident records:")
display(
    landslide_episode_summary[
        landslide_episode_summary["incident_count"] > 1
    ].sort_values("start_date")
)

print("\nEpisodes involving multiple DS divisions:")
display(
    landslide_episode_summary[
        landslide_episode_summary["ds_count"] > 1
    ].sort_values("start_date")
)

print("\nEpisode duration statistics:")
display(
    landslide_episode_summary["duration_days"].describe()
)

Candidate episodes: 62

Episodes with multiple incident records:

,episode_id,start_date,end_date,incident_count,ds_count,ds_divisions,total_deaths,total_houses_destroyed,total_houses_damaged,total_indirectly_affected,duration_days
0,NE_LS_EP001,2003-05-17,2003-05-18,3,1,Nuwara Eliya,0.0,0.0,0.0,505.0,2
4,NE_LS_EP005,2007-01-11,2007-01-15,8,2,"Nuwara Eliya, Walapane",0.0,8.0,43.0,1200.0,5
9,NE_LS_EP010,2008-06-01,2008-06-02,3,2,"Ambagamuwakorale, Nuwara Eliya",1.0,2.0,6.0,83.0,2
10,NE_LS_EP011,2008-11-25,2008-11-25,2,1,Nuwara Eliya,0.0,0.0,2.0,18.0,1
12,NE_LS_EP013,2009-05-20,2009-05-26,8,3,"Ambagamuwakorale, Kothmale, Nuwara Eliya",5.0,6.0,8.0,63.0,7
13,NE_LS_EP014,2009-06-11,2009-06-11,2,2,"Hanguranketha, Nuwara Eliya",0.0,0.0,2.0,5.0,1
14,NE_LS_EP015,2009-07-02,2009-07-03,3,1,Nuwara Eliya,0.0,0.0,4.0,27.0,2
18,NE_LS_EP019,2009-11-14,2009-11-16,2,2,"Ambagamuwakorale, Nuwara Eliya",0.0,1.0,2.0,10.0,3
20,NE_LS_EP021,2010-05-19,2010-05-22,2,2,"Kothmale, Nuwara Eliya",0.0,0.0,1.0,11.0,4
22,NE_LS_EP023,2010-10-06,2010-10-09,2,1,Nuwara Eliya,0.0,0.0,0.0,10.0,4
28,NE_LS_EP029,2013-06-23,2013-06-26,4,3,"Hanguranketha, Kothmale, Nuwara Eliya",0.0,3.0,49.0,236.0,4
36,NE_LS_EP037,2014-09-26,2014-09-28,3,2,"Kothmale, Nuwara Eliya",0.0,0.0,9.0,34.0,3
38,NE_LS_EP039,2014-12-22,2014-12-23,2,2,"Nuwara Eliya, Walapane",0.0,0.0,6.0,447.0,2
42,NE_LS_EP043,2015-05-11,2015-05-11,2,1,Nuwara Eliya,0.0,0.0,3.0,13.0,1
49,NE_LS_EP050,2017-05-28,2017-05-28,2,2,"Kothmale, Nuwara Eliya",0.0,0.0,16.0,308.0,1
55,NE_LS_EP056,2019-07-18,2019-07-19,3,2,"Ambagamuwakorale, Nuwara Eliya",0.0,0.0,6.0,37.0,2
56,NE_LS_EP057,2019-08-13,2019-08-13,2,2,"Kothmale, Nuwara Eliya",0.0,0.0,0.0,184.0,1
58,NE_LS_EP059,2019-10-08,2019-10-09,2,1,Nuwara Eliya,0.0,0.0,0.0,21.0,2
59,NE_LS_EP060,2019-11-30,2019-11-30,2,2,"Nuwara Eliya, Walapane",3.0,1.0,5.0,134.0,1

Episodes involving multiple DS divisions:

,episode_id,start_date,end_date,incident_count,ds_count,ds_divisions,total_deaths,total_houses_destroyed,total_houses_damaged,total_indirectly_affected,duration_days
4,NE_LS_EP005,2007-01-11,2007-01-15,8,2,"Nuwara Eliya, Walapane",0.0,8.0,43.0,1200.0,5
9,NE_LS_EP010,2008-06-01,2008-06-02,3,2,"Ambagamuwakorale, Nuwara Eliya",1.0,2.0,6.0,83.0,2
12,NE_LS_EP013,2009-05-20,2009-05-26,8,3,"Ambagamuwakorale, Kothmale, Nuwara Eliya",5.0,6.0,8.0,63.0,7
13,NE_LS_EP014,2009-06-11,2009-06-11,2,2,"Hanguranketha, Nuwara Eliya",0.0,0.0,2.0,5.0,1
18,NE_LS_EP019,2009-11-14,2009-11-16,2,2,"Ambagamuwakorale, Nuwara Eliya",0.0,1.0,2.0,10.0,3
20,NE_LS_EP021,2010-05-19,2010-05-22,2,2,"Kothmale, Nuwara Eliya",0.0,0.0,1.0,11.0,4
28,NE_LS_EP029,2013-06-23,2013-06-26,4,3,"Hanguranketha, Kothmale, Nuwara Eliya",0.0,3.0,49.0,236.0,4
36,NE_LS_EP037,2014-09-26,2014-09-28,3,2,"Kothmale, Nuwara Eliya",0.0,0.0,9.0,34.0,3
38,NE_LS_EP039,2014-12-22,2014-12-23,2,2,"Nuwara Eliya, Walapane",0.0,0.0,6.0,447.0,2
49,NE_LS_EP050,2017-05-28,2017-05-28,2,2,"Kothmale, Nuwara Eliya",0.0,0.0,16.0,308.0,1
55,NE_LS_EP056,2019-07-18,2019-07-19,3,2,"Ambagamuwakorale, Nuwara Eliya",0.0,0.0,6.0,37.0,2
56,NE_LS_EP057,2019-08-13,2019-08-13,2,2,"Kothmale, Nuwara Eliya",0.0,0.0,0.0,184.0,1
59,NE_LS_EP060,2019-11-30,2019-11-30,2,2,"Nuwara Eliya, Walapane",3.0,1.0,5.0,134.0,1

Episode duration statistics:

count    62.000000
mean      1.467742
std       1.141149
min       1.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       7.000000
Name: duration_days, dtype: float64

In [208]:
from pathlib import Path

landslide_rainfall_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/raw/landslide"
)

print("Files in landslide raw-data folder:\n")

for file in sorted(landslide_rainfall_path.iterdir()):
    print(file.name)

Files in landslide raw-data folder:

DesInventar_NuwaraEliya_Landslides_page1.xlsx

In [209]:
from pathlib import Path

landslide_folder = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/raw/landslide"
)

print("Contents of landslide raw-data folder:\n")

for item in sorted(landslide_folder.iterdir()):
    if item.is_file():
        print("FILE:", item.name)
    elif item.is_dir():
        print("FOLDER:", item.name)

Contents of landslide raw-data folder:

FILE: DesInventar_NuwaraEliya_Landslides_page1.xlsx
FILE: rain_gauge_shortlist.xlsx

In [210]:
import pandas as pd

rain_gauge_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/raw/landslide/rain_gauge_shortlist.xlsx"
)

rain_gauge_raw = pd.read_excel(rain_gauge_path)

print("Shape:", rain_gauge_raw.shape)

print("\nColumns:")
print(rain_gauge_raw.columns.tolist())

print("\nFirst 10 rows:")
display(rain_gauge_raw.head(10))

Shape: (14, 8)

Columns:
['priority', 'station', 'type', 'district', 'lon', 'lat', 'new_target_incidents_within_5km', 'target_incidents_within_5km_by_division']

First 10 rows:

,priority,station,type,district,lon,lat,new_target_incidents_within_5km,target_incidents_within_5km_by_division
0,1,HELBODDE ESTATE,Rain gauge (daily/monthly),NUWARA ELIA,80.6700,7.0800,128.0,Kothmale 128
1,2,SAMANALA POWER STATION,Rain gauge (daily/monthly),NUWARA ELIA,80.4700,6.9800,103.0,Ambagamuwa 103
2,3,CASTLEREIGH,Rain gauge (daily/monthly),NUWARA ELIA,80.5700,6.8700,62.0,Ambagamuwa 62
3,4,KURUNDU OYA,Rain gauge (daily/monthly),NUWARA ELIA,80.8300,7.0700,48.0,"Walapane 47, Kothmale 1"
4,5,KOTHMALE RESERVOIR,Rain gauge (daily/monthly),KANDY,80.5830,7.0167,45.0,"Kothmale 44, Walapane 1"
5,6,NORTON,Rain gauge (daily/monthly),NUWARA ELIA,80.5167,6.9167,42.0,Ambagamuwa 51
6,7,LABUKELLE,Rain gauge (daily/monthly),NUWARA ELIA,80.7200,7.0200,23.0,"Kothmale 28, Walapane 1"
7,8,LIDDESDALE ESTATE,Rain gauge (daily/monthly),NUWARA ELIA,80.8500,7.0300,22.0,Walapane 30
8,9,KOTHMALE,Agromet,KANDY,80.5800,7.0800,22.0,Kothmale 37
9,10,QUEENSBERRY ESTATE,Rain gauge (daily/monthly),NUWARA ELIA,80.5984,6.9888,17.0,"Kothmale 37, Walapane 1"

In [211]:
# Check all sheets in the rainfall gauge workbook

excel_file = pd.ExcelFile(rain_gauge_path)

print("Sheets found:")
print(excel_file.sheet_names)

Sheets found:
['Request_shortlist', 'All_gauges_near_incidents']

In [212]:
# Read both sheets separately

request_shortlist = pd.read_excel(
    rain_gauge_path,
    sheet_name="Request_shortlist"
)

all_gauges = pd.read_excel(
    rain_gauge_path,
    sheet_name="All_gauges_near_incidents"
)

print("Request_shortlist")
print("Shape:", request_shortlist.shape)
print("Columns:", request_shortlist.columns.tolist())

print("\nAll_gauges_near_incidents")
print("Shape:", all_gauges.shape)
print("Columns:", all_gauges.columns.tolist())

print("\nFirst 10 rows of All_gauges_near_incidents:")
display(all_gauges.head(10))

Request_shortlist
Shape: (14, 8)
Columns: ['priority', 'station', 'type', 'district', 'lon', 'lat', 'new_target_incidents_within_5km', 'target_incidents_within_5km_by_division']

All_gauges_near_incidents
Shape: (101, 6)
Columns: ['name', 'type', 'lon', 'lat', 'incidents_within_5km', 'incidents_within_10km']

First 10 rows of All_gauges_near_incidents:

,name,type,lon,lat,incidents_within_5km,incidents_within_10km
0,LABUKELLE,Rain gauge (daily/monthly),80.720,7.020,49,318
1,KURUNDU OYA,Rain gauge (daily/monthly),80.830,7.070,72,279
2,HOLLY ROOD ESTATE,Rain gauge (daily/monthly),80.670,6.950,62,272
3,MARIGOLD FACTORY,Rain gauge (daily/monthly),80.820,7.070,71,271
4,HIGH FOREST ESTATE,Rain gauge (daily/monthly),80.833,7.067,64,270
5,HELBODDE NORTH,Rain gauge (daily/monthly),80.680,7.080,119,267
6,HELBODDE ESTATE,Rain gauge (daily/monthly),80.670,7.080,128,264
7,SUMMERSET,Rain gauge (daily/monthly),80.700,6.930,71,264
8,HOPE ESTATE,Rain gauge (daily/monthly),80.750,7.100,49,253
9,QUEENSBERRY ESTATE,Rain gauge (daily/monthly),80.598,6.989,53,249

In [214]:
from pathlib import Path
import pandas as pd

met_station_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/raw/landslide/Met_Stations.xlsx"
)

met_excel = pd.ExcelFile(met_station_path)

print("Sheet names:")
for sheet in met_excel.sheet_names:
    print("-", sheet)

Sheet names:
- All Stations
- AWS Locations
- Met Stations & Parameters
- Agromet Stations & Parameters
- RF_Online(10 mts)
- Rainfall Stations & Parameters
- ARG Stations
- 3.2 & 2.1

In [216]:
rainfall_stations = pd.read_excel(
    met_station_path,
    sheet_name="Rainfall Stations & Parameters "
)

print("Shape:", rainfall_stations.shape)
print("\nColumns:")
print(rainfall_stations.columns.tolist())

print("\nFirst 10 rows:")
display(rainfall_stations.head(10))

Shape: (464, 9)

Columns:
['Source Layer', 'Name', 'id', 'District', 'longitude', 'latitude', 'Parameter Daily/Monthly', 'Coord_Longitude', 'Coord_Latitude']

First 10 rows:

,Source Layer,Name,id,District,longitude,latitude,Parameter Daily/Monthly,Coord_Longitude,Coord_Latitude
0,Rainfall Stations & Parameters 2023-2025,AMPARAI TANK,01AM0012,AMPARAI,81.666781,7.283278,Rainfall,81.666781,7.283278
1,Rainfall Stations & Parameters 2023-2025,ADDALACHENAI,01AM001E,AMPARAI,81.852060,7.245667,Rainfall,81.852060,7.245667
2,Rainfall Stations & Parameters 2023-2025,AKKARAIPATTU IRRIGATION,01AM001F,AMPARAI,81.825879,7.224130,Rainfall,81.825879,7.224130
3,Rainfall Stations & Parameters 2023-2025,IRAKKAMAN,01AM0182,AMPARAI,81.726095,7.254938,Rainfall,81.726095,7.254938
4,Rainfall Stations & Parameters 2023-2025,LAHUGALA TANK,01AM0269,AMPARAI,81.700000,6.880000,Rainfall,81.700000,6.880000
5,Rainfall Stations & Parameters 2023-2025,MAHA OYA,01AM0293,AMPARAI,81.370000,7.530000,Rainfall,81.370000,7.530000
6,Rainfall Stations & Parameters 2023-2025,PANAWA TANK,01AM0404,AMPARAI,81.770000,6.750000,Rainfall,81.770000,6.750000
7,Rainfall Stations & Parameters 2023-2025,RUFUSKULAM TANK,01AM0456,AMPARAI,81.780000,7.080000,Rainfall,81.780000,7.080000
8,Rainfall Stations & Parameters 2023-2025,SAGAMAM TANK,01AM0459,AMPARAI,81.800000,7.130000,Rainfall,81.800000,7.130000
9,Rainfall Stations & Parameters 2023-2025,DEEGAVAPI,01AM080A,AMPARAI,81.757805,7.256173,Rainfall,81.757805,7.256173

In [217]:
nuwara_rainfall_stations = rainfall_stations[
    rainfall_stations["District"]
    .astype("string")
    .str.strip()
    .str.upper()
    .eq("NUWARA ELIYA")
].copy()

print("Nuwara Eliya rainfall stations:", len(nuwara_rainfall_stations))

display(
    nuwara_rainfall_stations[
        [
            "Source Layer",
            "Name",
            "id",
            "District",
            "longitude",
            "latitude",
            "Parameter Daily/Monthly"
        ]
    ].sort_values("Name")
)

Nuwara Eliya rainfall stations: 0

Empty DataFrame
Columns: [Source Layer, Name, id, District, longitude, latitude, Parameter Daily/Monthly]
Index: []

In [218]:
districts = (
    rainfall_stations["District"]
    .dropna()
    .astype("string")
    .str.strip()
    .sort_values()
    .unique()
)

print("Number of unique districts:", len(districts))
print("\nDistrict names:")
for district in districts:
    print(repr(district))

Number of unique districts: 25

District names:
'AMPARAI'
'ANURADHAPURA'
'BADULLA'
'BATTICOALA'
'COLOMBO'
'GALLE'
'GAMPAHA'
'HAMBANTOTA'
'JAFFNA'
'KALUTARA'
'KANDY'
'KEGALLE'
'KILINOCHCHI'
'KURUNRGALA'
'MANNAR'
'MATARA'
'MATHALE'
'MONARAGALA'
'MULLATIVE'
'NUWARA ELIA'
'POLONNARUWA'
'PUTTALAM'
'RATNAPURA'
'TRINCOMALEE'
'VAUNIYA'

In [219]:
nuwara_rainfall_stations = rainfall_stations[
    rainfall_stations["District"]
    .astype("string")
    .str.strip()
    .str.upper()
    .eq("NUWARA ELIA")
].copy()

print("Nuwara Elia rainfall stations:", len(nuwara_rainfall_stations))

display(
    nuwara_rainfall_stations[
        [
            "Source Layer",
            "Name",
            "id",
            "District",
            "longitude",
            "latitude",
            "Parameter Daily/Monthly"
        ]
    ].sort_values("Name")
)

Nuwara Elia rainfall stations: 45

,Source Layer,Name,id,District,longitude,latitude,Parameter Daily/Monthly
334,Rainfall Stations & Parameters 2023-2025,AMBEWELA,01NE0010,NUWARA ELIA,80.795837,6.869434,Rainfall
335,Rainfall Stations & Parameters 2023-2025,ANNFIELD ESTATE,01NE0017,NUWARA ELIA,80.630000,6.870000,Rainfall
348,Rainfall Stations & Parameters 2023-2025,BAMBRAKELLY - LINDULA,01NE033A,NUWARA ELIA,80.650000,6.880000,Rainfall
336,Rainfall Stations & Parameters 2023-2025,BOPATTHALAWA,01NE0049,NUWARA ELIA,80.720000,6.830000,Rainfall
337,Rainfall Stations & Parameters 2023-2025,CAMPION ESTATE,01NE0058,NUWARA ELIA,80.700000,6.780000,Rainfall
358,Rainfall Stations & Parameters 2023-2025,CANYON,01NE317A,NUWARA ELIA,80.527854,6.869434,Rainfall
359,Rainfall Stations & Parameters 2023-2025,CASTLEREIGH,01NE317B,NUWARA ELIA,80.570000,6.870000,Rainfall
353,Rainfall Stations & Parameters 2023-2025,COOLDOWNGINIGATHHENA,01NE133A,NUWARA ELIA,80.470000,7.020000,Rainfall
351,Rainfall Stations & Parameters 2023-2025,DICKOYA,01NE088A,NUWARA ELIA,80.580000,6.880000,Rainfall
352,Rainfall Stations & Parameters 2023-2025,DRAYTON,01NE098A,NUWARA ELIA,80.620000,6.920000,Rainfall
338,Rainfall Stations & Parameters 2023-2025,HAKGALA BOTANICAL GDNS,01NE0142,NUWARA ELIA,80.822897,6.926241,Rainfall
339,Rainfall Stations & Parameters 2023-2025,HATTON KOTAGALA ROSITA,01NE0153,NUWARA ELIA,80.605017,6.929986,Rainfall
340,Rainfall Stations & Parameters 2023-2025,HELBODDE ESTATE,01NE0156,NUWARA ELIA,80.670000,7.080000,Rainfall
341,Rainfall Stations & Parameters 2023-2025,HELBODDE NORTH,01NE0157,NUWARA ELIA,80.680000,7.080000,Rainfall
355,Rainfall Stations & Parameters 2023-2025,HIGH FOREST ESTATE,01NE159A,NUWARA ELIA,80.833300,7.066700,Rainfall
354,Rainfall Stations & Parameters 2023-2025,HOLLY ROOD ESTATE,01NE157B,NUWARA ELIA,80.670000,6.950000,Rainfall
342,Rainfall Stations & Parameters 2023-2025,HOLMWOOD ESTATE,01NE0166,NUWARA ELIA,80.720000,6.850000,Rainfall
343,Rainfall Stations & Parameters 2023-2025,HOPE ESTATE,01NE0167,NUWARA ELIA,80.750000,7.100000,Rainfall
344,Rainfall Stations & Parameters 2023-2025,KENILWORTH (STRATHELLIE),01NE0236,NUWARA ELIA,80.480343,7.001022,Rainfall
345,Rainfall Stations & Parameters 2023-2025,KURUNDU OYA,01NE0264,NUWARA ELIA,80.830000,7.070000,Rainfall
346,Rainfall Stations & Parameters 2023-2025,LABUKELLE,01NE0266,NUWARA ELIA,80.720000,7.020000,Rainfall
360,Rainfall Stations & Parameters 2023-2025,LAXAPANA,01NE317D,NUWARA ELIA,80.492019,6.918234,Rainfall
347,Rainfall Stations & Parameters 2023-2025,LIDDESDALE ESTATE,01NE0274,NUWARA ELIA,80.850000,7.030000,Rainfall
356,Rainfall Stations & Parameters 2023-2025,Loolecondera Estate,01NE277C,NUWARA ELIA,80.714559,7.128442,Rainfall
357,Rainfall Stations & Parameters 2023-2025,MARIGOLD FACTORY,01NE315A,NUWARA ELIA,80.820000,7.070000,Rainfall
362,Rainfall Stations & Parameters 2023-2025,MAUSSAKELLE,01NE317F,NUWARA ELIA,80.550000,6.850000,Rainfall
367,Rainfall Stations & Parameters 2023-2025,NEW ZEALAND FARM,01NE376B,NUWARA ELIA,80.799603,6.871694,Rainfall
361,Rainfall Stations & Parameters 2023-2025,NORTON,01NE317E,NUWARA ELIA,80.516700,6.916700,Rainfall
369,Rainfall Stations & Parameters 2023-2025,PEDRO ESTATE,01NE415A,NUWARA ELIA,80.792145,6.970596,Rainfall
370,Rainfall Stations & Parameters 2023-2025,PIDURUTALAGALA FARM,01NE424D,NUWARA ELIA,80.793318,7.002100,Rainfall
371,Rainfall Stations & Parameters 2023-2025,PIDURUTHALAGALA AIR FORCE CAMP,01NE424E,NUWARA ELIA,80.773430,7.000707,Rainfall
368,Rainfall Stations & Parameters 2023-2025,PRESIDENTS HOUSE N-ELIYA,01NE382A,NUWARA ELIA,80.770000,6.980000,Rainfall
366,Rainfall Stations & Parameters 2023-2025,QUEENSBERRY ESTATE,01NE370A,NUWARA ELIA,80.598427,6.988788,Rainfall
363,Rainfall Stations & Parameters 2023-2025,SAMANALA POWER STATION,01NE317G,NUWARA ELIA,80.470000,6.980000,Rainfall
349,Rainfall Stations & Parameters 2023-2025,SANDRINGHAM ESTATE,01NE0460,NUWARA ELIA,80.750000,6.850000,Rainfall
372,Rainfall Stations & Parameters 2023-2025,SHANNON ESTATE,01NE464A,NUWARA ELIA,80.570000,6.900000,Rainfall
373,Rainfall Stations & Parameters 2023-2025,SITA ELIYA,01NE467B,NUWARA ELIA,80.798981,6.951684,Rainfall
374,Rainfall Stations & Parameters 2023-2025,SITAELIYA GOVT FARM,01NE467C,NUWARA ELIA,80.780000,6.950000,Rainfall
375,Rainfall Stations & Parameters 2023-2025,ST. CLAIR,01NE485D,NUWARA ELIA,80.650000,6.930000,Rainfall
365,Rainfall Stations & Parameters 2023-2025,SUMMERSET,01NE362A,NUWARA ELIA,80.700000,6.930000,Rainfall
376,Rainfall Stations & Parameters 2023-2025,UDARADELLA,01NE506B,NUWARA ELIA,80.820000,6.970000,Rainfall
350,Rainfall Stations & Parameters 2023-2025,WATAWALA,01NE0534,NUWARA ELIA,80.520000,6.970000,Rainfall
378,Rainfall Stations & Parameters 2023-2025,WATAWALA MOUNT JEAN,01NE534B,NUWARA ELIA,80.520000,6.950000,Rainfall
377,Rainfall Stations & Parameters 2023-2025,"WATAWALA,RAILWAY STATION",01NE534A,NUWARA ELIA,80.526485,6.961759,Rainfall
364,Rainfall Stations & Parameters 2023-2025,WIMALASURENDRA POWER STN,01NE317H,NUWARA ELIA,80.525708,6.908010,Rainfall

In [220]:
for sheet in [
    "All Stations",
    "Met Stations & Parameters",
    "Agromet Stations & Parameters"
]:
    df = pd.read_excel(met_station_path, sheet_name=sheet)
    
    print("\n" + "=" * 70)
    print("SHEET:", sheet)
    print("Shape:", df.shape)
    print("Columns:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df.head())

======================================================================
SHEET: All Stations
Shape: (1961, 29)
Columns:
['Name', 'Station ID', 'unnamed (1)', 'unnamed (2)', 'Latitude', 'Longitude', 'Coord_Longitude', 'Coord_Latitude', 'id', 'longitude', 'latitude', 'elevation', 'Parameters Daily & Monthly', 'Parameters 3 hourly', 'Obsevation times( UTC )', 'Station_id', 'District', 'Elevation', 'Obsevation Times (UTC)', 'Main Station', 'LON', 'LAT', 'Rf', 'Parameter Daily/Monthly', 'Station Type', 'Lat', 'Lon', 'code', 'unnamed (3)']

First 5 rows:

,Name,Station ID,unnamed (1),unnamed (2),Latitude,Longitude,Coord_Longitude,Coord_Latitude,id,longitude,...,Main Station,LON,LAT,Rf,Parameter Daily/Monthly,Station Type,Lat,Lon,code,unnamed (3)
0,wagolla,C1,"7°17'32.6""N","80°23'15.9""E",7.292400,80.387750,80.387750,7.292400,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Polonnaruwa,C2,7.866666667,81.05,7.866667,81.050000,81.050000,7.866667,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Monaragala,C3,6.5,81.3,6.500000,81.300000,81.300000,6.500000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mathale,C4,"7°27'13.5""N","80°38'31.9""E",7.453800,80.642194,80.642194,7.453800,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sewanagala,C5,"6°23'47.1""N","80°54'45.6""E",6.396400,80.912667,80.912667,6.396400,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
SHEET: Met Stations & Parameters
Shape: (24, 11)
Columns:
['Source Layer', 'Name', 'id', 'longitude', 'latitude', 'elevation', 'Parameters Daily & Monthly', 'Parameters 3 hourly', 'Obsevation times( UTC )', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

,Source Layer,Name,id,longitude,latitude,elevation,Parameters Daily & Monthly,Parameters 3 hourly,Obsevation times( UTC ),Coord_Longitude,Coord_Latitude
0,Met Stations & Parameters,BANDARAWELA,43476,80.986260,6.830904,1225.0,"Temp Max,Temp min,Rainfall,RH Day","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure...","0000,0300,0600,0900,1200,1500,",80.986260,6.830904
1,Met Stations & Parameters,JAFFNA,43404,80.032947,9.693824,3.0,"Temp Max,Temp min,Rainfall,RH Day","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure...","0000,0300,0600,0900,1200,1500,",80.032947,9.693824
2,Met Stations & Parameters,MULLATIVE,43410,80.819239,9.270556,3.0,"Temp Max,Temp min,Rainfall,RH Day","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure...","0000,0300,0600,0900,1200,1500,",80.819239,9.270556
3,Met Stations & Parameters,MANNAR,43413,79.907610,8.987058,4.0,"Temp Max,Temp min,Rainfall,RH Day,RH Night","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure...","0000,0300,0600,0900,1200,1500,1800,2100,",79.907610,8.987058
4,Met Stations & Parameters,VAVUNIYA,43415,80.496591,8.759978,98.0,"Temp Max,Temp min,Rainfall,RH Day","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure...","0000,0300,0600,0900,1200,1500,",80.496591,8.759978

======================================================================
SHEET: Agromet Stations & Parameters
Shape: (41, 11)
Columns:
['Source Layer', 'Name', 'Station_id', 'District', 'Longitude', 'Latitude', 'Elevation', 'Parameters Daily & Monthly', 'Obsevation Times (UTC)', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

,Source Layer,Name,Station_id,District,Longitude,Latitude,Elevation,Parameters Daily & Monthly,Obsevation Times (UTC),Coord_Longitude,Coord_Latitude
0,Agromet Stations & Parameters,AGALAWATTA,01AG1,KALUTARA,80.150000,6.530000,65.0,"Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,R...",0300 & 1000,80.150000,6.530000
1,Agromet Stations & Parameters,ELUWANKULAMA,01AG10,PUTTALAM,79.850000,8.270000,100.0,"Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,R...",0300 & 1000,79.850000,8.270000
2,Agromet Stations & Parameters,GIRADURUKOTTE,01AG11,BADULLA,81.022322,7.458215,292.0,"Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,R...",0300 & 1000,81.022322,7.458215
3,Agromet Stations & Parameters,KOTHMALE,01AG12,KANDY,80.580000,7.080000,716.0,"Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,R...",0300 & 1000,80.580000,7.080000
4,Agromet Stations & Parameters,KOTTAWA,01AG13,GALLE,80.320000,6.090000,18.0,"Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,R...",0300 & 1000,80.320000,6.090000

In [221]:
all_stations = pd.read_excel(
    met_station_path,
    sheet_name="All Stations"
)

# Search every text-containing column for Nuwara Elia / Nuwara Eliya
text_columns = all_stations.select_dtypes(include=["object", "string"]).columns

mask = pd.Series(False, index=all_stations.index)

for col in text_columns:
    mask = mask | (
        all_stations[col]
        .astype("string")
        .str.contains(
            "NUWARA|ELIA|ELIYA",
            case=False,
            na=False
        )
    )

nuwara_all = all_stations[mask].copy()

print("Matching All Stations records:", len(nuwara_all))

display(nuwara_all)

Matching All Stations records: 153

,Name,Station ID,unnamed (1),unnamed (2),Latitude,Longitude,Coord_Longitude,Coord_Latitude,id,longitude,...,Main Station,LON,LAT,Rf,Parameter Daily/Monthly,Station Type,Lat,Lon,code,unnamed (3)
31,NUWARA ELIYA,43473,6.966666667,80.76666667,6.966667,80.766667,80.766667,6.966667,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NUWARA ELIYA,NaN,NaN,NaN,NaN,NaN,80.779152,6.969531,43473,80.779152,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,SEETHAELIYA,NaN,NaN,NaN,6.951726,80.798970,80.798970,6.951726,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,THALAWAKELLE,NaN,NaN,NaN,6.930000,80.660000,80.660000,6.930000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,Kanneliya Forest Office,NaN,NaN,NaN,NaN,NaN,80.338330,6.251110,NaN,NaN,...,AWS,80.33833,6.25111,-9999.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1741,UDARADELLA,NaN,NUWARA ELIYA,Rainfall,NaN,NaN,80.726044,6.963933,01NE506B,80.726044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
1742,"WATAWALA,RAILWAY STATION",NaN,NUWARA ELIYA,Rainfall,NaN,NaN,80.522246,6.969417,01NE534A,80.522246,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1743,WATAWALA MOUNT JEAN,NaN,NUWARA ELIYA,Rainfall,NaN,NaN,80.527519,6.962990,01NE534B,80.527519,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
1744,YARRAVALE ESTATE,NaN,NUWARA ELIYA,Rainfall,NaN,NaN,80.770000,6.820000,01NE551A,80.770000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
1827,EHELIYAGODA S.P.,NaN,RATNAPURA,Rainfall,NaN,NaN,80.270000,6.850000,01RT0104,80.270000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN

In [222]:
# Keep records where the station is associated with Nuwara Elia
# AND the record indicates rainfall.

nuwara_rain_all = nuwara_all[
    (
        nuwara_all.astype("string")
        .apply(
            lambda col: col.str.contains(
                "NUWARA ELIA",
                case=False,
                na=False
            )
        )
        .any(axis=1)
    )
    &
    (
        nuwara_all.astype("string")
        .apply(
            lambda col: col.str.contains(
                "Rainfall",
                case=False,
                na=False
            )
        )
        .any(axis=1)
    )
].copy()

print("Nuwara Elia + rainfall records:", len(nuwara_rain_all))

display(
    nuwara_rain_all[
        [
            "Name",
            "Station ID",
            "id",
            "Coord_Longitude",
            "Coord_Latitude",
            "District",
            "Rf",
            "Parameter Daily/Monthly",
            "Station Type",
            "code"
        ]
    ].drop_duplicates()
)

Nuwara Elia + rainfall records: 45

,Name,Station ID,id,Coord_Longitude,Coord_Latitude,District,Rf,Parameter Daily/Monthly,Station Type,code
560,AMBEWELA,NaN,01NE0010,80.795837,6.869434,NUWARA ELIA,NaN,Rainfall,NaN,NaN
561,ANNFIELD ESTATE,NaN,01NE0017,80.630000,6.870000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
562,BOPATTHALAWA,NaN,01NE0049,80.720000,6.830000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
563,CAMPION ESTATE,NaN,01NE0058,80.700000,6.780000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
564,HAKGALA BOTANICAL GDNS,NaN,01NE0142,80.822897,6.926241,NUWARA ELIA,NaN,Rainfall,NaN,NaN
565,HATTON KOTAGALA ROSITA,NaN,01NE0153,80.605017,6.929986,NUWARA ELIA,NaN,Rainfall,NaN,NaN
566,HELBODDE ESTATE,NaN,01NE0156,80.670000,7.080000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
567,HELBODDE NORTH,NaN,01NE0157,80.680000,7.080000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
568,HOLMWOOD ESTATE,NaN,01NE0166,80.720000,6.850000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
569,HOPE ESTATE,NaN,01NE0167,80.750000,7.100000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
570,KENILWORTH (STRATHELLIE),NaN,01NE0236,80.480343,7.001022,NUWARA ELIA,NaN,Rainfall,NaN,NaN
571,KURUNDU OYA,NaN,01NE0264,80.830000,7.070000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
572,LABUKELLE,NaN,01NE0266,80.720000,7.020000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
573,LIDDESDALE ESTATE,NaN,01NE0274,80.850000,7.030000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
574,BAMBRAKELLY - LINDULA,NaN,01NE033A,80.650000,6.880000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
575,SANDRINGHAM ESTATE,NaN,01NE0460,80.750000,6.850000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
576,WATAWALA,NaN,01NE0534,80.520000,6.970000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
577,DICKOYA,NaN,01NE088A,80.580000,6.880000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
578,DRAYTON,NaN,01NE098A,80.620000,6.920000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
579,COOLDOWNGINIGATHHENA,NaN,01NE133A,80.470000,7.020000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
580,HOLLY ROOD ESTATE,NaN,01NE157B,80.670000,6.950000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
581,HIGH FOREST ESTATE,NaN,01NE159A,80.833300,7.066700,NUWARA ELIA,NaN,Rainfall,NaN,NaN
582,Loolecondera Estate,NaN,01NE277C,80.714559,7.128442,NUWARA ELIA,NaN,Rainfall,NaN,NaN
583,MARIGOLD FACTORY,NaN,01NE315A,80.820000,7.070000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
584,CANYON,NaN,01NE317A,80.527854,6.869434,NUWARA ELIA,NaN,Rainfall,NaN,NaN
585,CASTLEREIGH,NaN,01NE317B,80.570000,6.870000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
586,LAXAPANA,NaN,01NE317D,80.492019,6.918234,NUWARA ELIA,NaN,Rainfall,NaN,NaN
587,NORTON,NaN,01NE317E,80.516700,6.916700,NUWARA ELIA,NaN,Rainfall,NaN,NaN
588,MAUSSAKELLE,NaN,01NE317F,80.550000,6.850000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
589,SAMANALA POWER STATION,NaN,01NE317G,80.470000,6.980000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
590,WIMALASURENDRA POWER STN,NaN,01NE317H,80.525708,6.908010,NUWARA ELIA,NaN,Rainfall,NaN,NaN
591,SUMMERSET,NaN,01NE362A,80.700000,6.930000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
592,QUEENSBERRY ESTATE,NaN,01NE370A,80.598427,6.988788,NUWARA ELIA,NaN,Rainfall,NaN,NaN
593,NEW ZEALAND FARM,NaN,01NE376B,80.799603,6.871694,NUWARA ELIA,NaN,Rainfall,NaN,NaN
594,PRESIDENTS HOUSE N-ELIYA,NaN,01NE382A,80.770000,6.980000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
595,PEDRO ESTATE,NaN,01NE415A,80.792145,6.970596,NUWARA ELIA,NaN,Rainfall,NaN,NaN
596,PIDURUTALAGALA FARM,NaN,01NE424D,80.793318,7.002100,NUWARA ELIA,NaN,Rainfall,NaN,NaN
597,PIDURUTHALAGALA AIR FORCE CAMP,NaN,01NE424E,80.773430,7.000707,NUWARA ELIA,NaN,Rainfall,NaN,NaN
598,SHANNON ESTATE,NaN,01NE464A,80.570000,6.900000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
599,SITA ELIYA,NaN,01NE467B,80.798981,6.951684,NUWARA ELIA,NaN,Rainfall,NaN,NaN
600,SITAELIYA GOVT FARM,NaN,01NE467C,80.780000,6.950000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
601,ST. CLAIR,NaN,01NE485D,80.650000,6.930000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
602,UDARADELLA,NaN,01NE506B,80.820000,6.970000,NUWARA ELIA,NaN,Rainfall,NaN,NaN
603,"WATAWALA,RAILWAY STATION",NaN,01NE534A,80.526485,6.961759,NUWARA ELIA,NaN,Rainfall,NaN,NaN
604,WATAWALA MOUNT JEAN,NaN,01NE534B,80.520000,6.950000,NUWARA ELIA,NaN,Rainfall,NaN,NaN

In [223]:
# Check how the Nuwara Elia rainfall station IDs appear
# across the entire All Stations workbook.

station_ids = (
    nuwara_rain_all["id"]
    .dropna()
    .astype("string")
    .str.strip()
    .unique()
)

station_history = all_stations[
    all_stations["id"]
    .astype("string")
    .str.strip()
    .isin(station_ids)
].copy()

print("Matching station-ID records:", len(station_history))
print("Unique station IDs:", station_history["id"].nunique())

display(
    station_history[
        [
            "Name",
            "id",
            "Coord_Longitude",
            "Coord_Latitude",
            "unnamed (1)",
            "unnamed (2)",
            "Rf",
            "Parameter Daily/Monthly",
            "Station Type",
            "Main Station",
            "code"
        ]
    ].drop_duplicates()
)

Matching station-ID records: 90
Unique station IDs: 45

,Name,id,Coord_Longitude,Coord_Latitude,unnamed (1),unnamed (2),Rf,Parameter Daily/Monthly,Station Type,Main Station,code
560,AMBEWELA,01NE0010,80.795837,6.869434,NaN,NaN,NaN,Rainfall,NaN,NaN,NaN
561,ANNFIELD ESTATE,01NE0017,80.630000,6.870000,NaN,NaN,NaN,Rainfall,NaN,NaN,NaN
562,BOPATTHALAWA,01NE0049,80.720000,6.830000,NaN,NaN,NaN,Rainfall,NaN,NaN,NaN
563,CAMPION ESTATE,01NE0058,80.700000,6.780000,NaN,NaN,NaN,Rainfall,NaN,NaN,NaN
564,HAKGALA BOTANICAL GDNS,01NE0142,80.822897,6.926241,NaN,NaN,NaN,Rainfall,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1736,SITAELIYA GOVT FARM,01NE467C,80.798947,6.951670,NUWARA ELIYA,Rainfall,NaN,NaN,NaN,NaN,5.0
1738,ST. CLAIR,01NE485D,80.649466,6.946561,NUWARA ELIYA,Rainfall,NaN,NaN,NaN,NaN,5.0
1741,UDARADELLA,01NE506B,80.726044,6.963933,NUWARA ELIYA,Rainfall,NaN,NaN,NaN,NaN,5.0
1742,"WATAWALA,RAILWAY STATION",01NE534A,80.522246,6.969417,NUWARA ELIYA,Rainfall,NaN,NaN,NaN,NaN,NaN
1743,WATAWALA MOUNT JEAN,01NE534B,80.527519,6.962990,NUWARA ELIYA,Rainfall,NaN,NaN,NaN,NaN,5.0

In [224]:
rf_online = pd.read_excel(
    met_station_path,
    sheet_name="RF_Online(10 mts)"
)

print("Shape:", rf_online.shape)

print("\nColumns:")
print(rf_online.columns.tolist())

print("\nFirst 10 rows:")
display(rf_online.head(10))

Shape: (122, 8)

Columns:
['Source Layer', 'Name', 'Main Station', 'LON', 'LAT', 'Rf', 'Coord_Longitude', 'Coord_Latitude']

First 10 rows:

,Source Layer,Name,Main Station,LON,LAT,Rf,Coord_Longitude,Coord_Latitude
0,RF_Online(10 mts),Wathupitiwala Base Hospital,AWS,80.110830,7.122500,0.0,80.110830,7.122500
1,RF_Online(10 mts),Madolthenna Estate,AWS,80.182220,7.082220,-9999.0,80.182220,7.082220
2,RF_Online(10 mts),Dunumale Estate,AWS,80.208890,7.136110,-9999.0,80.208890,7.136110
3,RF_Online(10 mts),"Etana Estate, Warakapola",AWS,80.190550,7.215280,0.0,80.190550,7.215280
4,RF_Online(10 mts),"Mahayaya Area Estate,Dansalwaththa",AWS,80.117220,7.180550,0.0,80.117220,7.180550
5,RF_Online(10 mts),Algama Central College,AWS,80.164440,7.155280,-9999.0,80.164440,7.155280
6,RF_Online(10 mts),Gampaha Technical College,AWS,80.025280,7.082500,0.0,80.025280,7.082500
7,RF_Online(10 mts),Divulapitiya Divisional Secretariate,AWS,80.024170,7.225550,0.0,80.024170,7.225550
8,RF_Online(10 mts),Siyane National College of Education,AWS,80.070000,7.139170,-9999.0,80.070000,7.139170
9,RF_Online(10 mts),Melkopiwatta,AWS,79.933644,7.183365,0.0,79.933644,7.183365

In [225]:
# Inspect all sheets in the rain gauge shortlist workbook

rain_gauge_excel = pd.ExcelFile(rain_gauge_path)

print("Sheets in rain_gauge_shortlist.xlsx:")
for i, sheet in enumerate(rain_gauge_excel.sheet_names, start=1):
    print(f"{i}. {sheet}")

Sheets in rain_gauge_shortlist.xlsx:
1. Request_shortlist
2. All_gauges_near_incidents

In [228]:
from pathlib import Path

kelani_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/raw/flood/kelani"
)

print("Files in Kelani folder:")
print()

for file in sorted(kelani_path.iterdir()):
    print(file.name)

Files in Kelani folder:

2015 - 2025 Discharge.xlsx
2015 - 2025 RF.xlsx
2015 - 2025 WL.xlsx

In [229]:
rf_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/raw/flood/kelani/2015 - 2025 RF.xlsx"
)

rf_excel = pd.ExcelFile(rf_path)

print("Rainfall workbook sheets:")
for i, sheet in enumerate(rf_excel.sheet_names, start=1):
    print(f"{i}. {sheet}")

Rainfall workbook sheets:
1. KN02-NORWOOD
2. KN07-KITULGALA
3.  KN11-HOLOMBUWA
4. KN16-DERANIYAGALA
5. KN18-GLENCOURSE
6. KN21-HANWELLA

In [230]:
norwood_rf = pd.read_excel(
    rf_path,
    sheet_name="KN02-NORWOOD",
    header=None
)

print("Shape:", norwood_rf.shape)
print()
print(norwood_rf.head(10).to_string())

Shape: (136, 35)

                             0     1      2    3     4     5     6     7     8    9    10    11    12    13                                 14    15   16    17    18    19    20    21   22   23   24    25            26    27        28    29        30    31   32   33     34
0                           NaN   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN                                NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN  NaN  NaN    NaN
1  Norwood Daily Rainfall in mm   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN  N.A. - DENOTED DATA NOT AVAILABLE   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN  Cordinate :-   NaN  182051 X   NaN  182230 Y   NaN  NaN  NaN    NaN
2                           NaN   NaN    NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN   NaN   NaN   NaN                                NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN           NaN   NaN       NaN   NaN       NaN   NaN  NaN  NaN    NaN
3                    Year/Month  YEAR  MONTH   D1    D2    D3    D4    D5    D6   D7   D8    D9   D10   D11                                D12   D13  D14   D15   D16   D17   D18   D19  D20  D21  D22   D23           D24   D25       D26   D27       D28   D29  D30  D31  TOTAL
4                      14/15/04  2015    JAN    0     0     0     0     0   1.7    0    0     0     0     0                                  0     0    0     0     0     0     0     0    0    0    0     0             0     0         0     0      11.7  23.4  4.6  0.5   41.9
5                      14/15/05  2015    FEB    0     0  10.4     0  25.9  23.9    0    0     0  13.2  12.3                               15.1   1.2    0     0     0     0     0     0    0    0  3.8     5           7.2     0      12.5    20      31.7   NaN  NaN  NaN  182.2
6                      14/15/06  2015    MAR  3.7     0     0  20.3   2.5     0    0    0     0     0     0                                  4   4.2  0.6     0   4.8     0     0     0    0    0    0     0             0     0      25.4   1.3       1.8   4.6    7  5.5   85.7
7                      14/15/07  2015    APR   39  26.8   0.7  13.1     0   0.3  9.4  1.3  31.3   7.4     0                                  0  13.9    3    48   7.9     0     0   4.8  8.3    0    0  12.5          39.3  21.4       1.2  38.8       1.2   3.1  8.7  NaN  341.4
8                      14/15/08  2015    MAY  1.9     0     0   3.6  29.9   9.7  1.2    0   3.7  43.3     0                                  0   1.1    0  14.1   1.8   2.1   1.2   3.1    0  1.7    0   1.7             0     0         0     0         0     0    0  5.1  125.2
9                      14/15/09  2015    JUN    0     0   1.3   4.2  16.5     0    0    0     0     0   1.5                                  0     0    0  11.3  48.5  28.9  38.5  12.4  0.9    0    0     0           1.6     0       7.6  16.7       8.1   7.8  1.3  NaN  207.1

In [231]:
print("Year range in Norwood rainfall data:")
print(norwood_rf.iloc[4:, 1].dropna().unique())

print()
print("Number of monthly rows:", len(norwood_rf) - 4)

print()
print("Last 10 data rows:")
print(norwood_rf.iloc[-10:, :4].to_string(index=False))

Year range in Norwood rainfall data:
[2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025]

Number of monthly rows: 132

Last 10 data rows:
       0    1   2    3
24/25/06 2025 MAR  1.3
24/25/07 2025 APR  3.1
24/25/08 2025 MAY    0
24/25/09 2025 JUN  3.6
24/25/10 2025 JUL  1.5
24/25/11 2025 AUG  4.3
24/25/12 2025 SEP  1.5
25/26/01 2025 OCT    0
25/26/02 2025 NOV    0
25/26/03 2025 DEC    0

In [232]:
for sheet in rf_excel.sheet_names:
    df = pd.read_excel(
        rf_path,
        sheet_name=sheet,
        header=None
    )
    
    print("=" * 60)
    print("Station:", sheet)
    print("Shape:", df.shape)
    print("First data row:", df.iloc[4, 0])
    print("Last data row:", df.iloc[-1, 0])
    print("Years:", sorted(df.iloc[4:, 1].dropna().unique().tolist()))

============================================================
Station: KN02-NORWOOD
Shape: (136, 35)
First data row: 14/15/04
Last data row: 25/26/03
Years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
============================================================
Station: KN07-KITULGALA
Shape: (136, 35)
First data row: 14/15/04
Last data row: 25/26/03
Years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
============================================================
Station:  KN11-HOLOMBUWA
Shape: (136, 35)
First data row: 14/15/04
Last data row: 25/26/03
Years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
============================================================
Station: KN16-DERANIYAGALA
Shape: (136, 35)
First data row: 14/15/04
Last data row: 25/26/03
Years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
============================================================
Station: KN18-GLENCOURSE
Shape: (136, 35)
First data row: 14/15/04
Last data row: 25/26/03
Years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
============================================================
Station: KN21-HANWELLA
Shape: (136, 35)
First data row: 14/15/04
Last data row: 25/26/03
Years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

In [233]:
station_sheets = rf_excel.sheet_names

for sheet in station_sheets:
    df = pd.read_excel(
        rf_path,
        sheet_name=sheet,
        header=None
    )

    print("=" * 60)
    print(sheet)

    # Display rows containing coordinate information
    for i in range(min(4, len(df))):
        print(i, df.iloc[i].dropna().tolist())

============================================================
KN02-NORWOOD
0 []
1 ['Norwood Daily Rainfall in mm', 'N.A. - DENOTED DATA NOT AVAILABLE', 'Cordinate :-', '182051 X', '182230 Y']
2 []
3 ['Year/Month', 'YEAR', 'MONTH', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'TOTAL']
============================================================
KN07-KITULGALA
0 []
1 ['Kithulgala Daily Rainfall in mm', 'N.A. - DENOTED DATA NOT AVAILABLE', 'Cordinate :-', '160270 X', '198922 Y']
2 []
3 ['Year/Month', 'YEAR', 'MONTH', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'TOTAL']
============================================================
 KN11-HOLOMBUWA
0 []
1 ['Holombuwa Daily Rainfall in mm', 'N.A. - DENOTED DATA NOT AVAILABLE', 'Cordinate :-', '143948 X', '220765 Y']
2 []
3 ['YEARMONTH', 'YEAR', 'MONTH', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'TOTAL']
============================================================
KN16-DERANIYAGALA
0 []
1 ['Deraniyagala Daily Rainfall in mm', 'N.A. - DENOTED DATA NOT AVAILABLE', 'Cordinate :-', '152036 X', '191688 Y']
2 []
3 ['YEARMONTH', 'YEAR', 'MONTH', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'TOTAL']
============================================================
KN18-GLENCOURSE
0 []
1 ['Glencourse Daily Rainfall in mm', 'N.A. - DENOTED DATA NOT AVAILABLE', 'Cordinate :-', '135963 X', '197396 Y']
2 []
3 ['YEARMONTH', 'YEAR', 'MONTH', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'TOTAL']
============================================================
KN21-HANWELLA
0 []
1 ['Hanwella Daily Rainfall in mm', 'N.A. - DENOTED DATA NOT AVAILABLE', 'Cordinate :-', '123689 X', '189980 Y']
2 []
3 ['YEARMONTH', 'YEAR', 'MONTH', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'TOTAL']

In [234]:
# Check whether the Kelani rainfall station names appear
# in the Nuwara Eliya rainfall-station metadata.

station_names_to_check = [
    "NORWOOD",
    "KITULGALA",
    "HOLOMBUWA",
    "DERANIYAGALA",
    "GLENCOURSE",
    "HANWELLA"
]

for name in station_names_to_check:
    matches = met_station_raw[
        met_station_raw["Name"]
        .astype("string")
        .str.upper()
        .str.contains(name, na=False)
    ]

    print("=" * 60)
    print("Search:", name)
    print("Matches:", len(matches))

    if len(matches) > 0:
        print(
            matches[
                ["Name", "Station ID", "District",
                 "Coord_Longitude", "Coord_Latitude",
                 "Parameter Daily/Monthly"]
            ].drop_duplicates().to_string(index=False)
        )

NameError: name 'met_station_raw' is not defined

In [235]:
from pathlib import Path
import pandas as pd

# Search for Met_Stations.xlsx inside your project
project_path = Path("/Users/ohaseelanka/disaster_analytics_hub")

met_files = list(project_path.rglob("Met_Stations.xlsx"))

print("Files found:", len(met_files))
for file in met_files:
    print(file)

Files found: 1
/Users/ohaseelanka/disaster_analytics_hub/data/raw/landslide/Met_Stations.xlsx

In [236]:
met_station_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub/data/raw/landslide/Met_Stations.xlsx"
)

met_station_raw = pd.read_excel(
    met_station_path,
    sheet_name="All Stations"
)

print("Shape:", met_station_raw.shape)
print()
print("Columns:")
print(met_station_raw.columns.tolist())

Shape: (1961, 29)

Columns:
['Name', 'Station ID', 'unnamed (1)', 'unnamed (2)', 'Latitude', 'Longitude', 'Coord_Longitude', 'Coord_Latitude', 'id', 'longitude', 'latitude', 'elevation', 'Parameters Daily & Monthly', 'Parameters 3 hourly', 'Obsevation times( UTC )', 'Station_id', 'District', 'Elevation', 'Obsevation Times (UTC)', 'Main Station', 'LON', 'LAT', 'Rf', 'Parameter Daily/Monthly', 'Station Type', 'Lat', 'Lon', 'code', 'unnamed (3)']

In [237]:
station_names_to_check = [
    "NORWOOD",
    "KITULGALA",
    "HOLOMBUWA",
    "DERANIYAGALA",
    "GLENCOURSE",
    "HANWELLA"
]

for name in station_names_to_check:
    matches = met_station_raw[
        met_station_raw["Name"]
        .astype("string")
        .str.upper()
        .str.contains(name, na=False)
    ]

    print("=" * 60)
    print("Search:", name)
    print("Matches:", len(matches))

    if len(matches) > 0:
        print(
            matches[
                [
                    "Name",
                    "Station ID",
                    "District",
                    "Coord_Longitude",
                    "Coord_Latitude",
                    "Parameter Daily/Monthly"
                ]
            ].drop_duplicates().to_string(index=False)
        )

============================================================
Search: NORWOOD
Matches: 1
                Name Station ID District  Coord_Longitude  Coord_Latitude Parameter Daily/Monthly
NORWOOD (NEW VALLEY)        NaN      NaN             80.6            6.83                     NaN
============================================================
Search: KITULGALA
Matches: 1
                Name Station ID District  Coord_Longitude  Coord_Latitude Parameter Daily/Monthly
KITULGALA REST HOUSE        NaN      NaN        80.405908        6.995807                     NaN
============================================================
Search: HOLOMBUWA
Matches: 0
============================================================
Search: DERANIYAGALA
Matches: 2
                                Name Station ID District  Coord_Longitude  Coord_Latitude Parameter Daily/Monthly
Deraniyagala Divisional Secretariate        NaN      NaN         80.33639         6.93444                     NaN
============================================================
Search: GLENCOURSE
Matches: 0
============================================================
Search: HANWELLA
Matches: 4
                        Name Station ID District  Coord_Longitude  Coord_Latitude Parameter Daily/Monthly
W.K.K. Engineering, Hanwella        NaN      NaN        80.098294        6.874275                     NaN
              HANWELLA GROUP        NaN  COLOMBO        80.120000        6.880000                Rainfall
              HANWELLA GROUP        NaN      NaN        80.120000        6.880000                     NaN

In [238]:
project_path = Path(
    "/Users/ohaseelanka/disaster_analytics_hub"
)

rain_files = []

for file in project_path.rglob("*"):
    if file.is_file():
        name = file.name.lower()

        if (
            file.suffix.lower() in [".xlsx", ".xls", ".csv", ".parquet"]
            and any(word in name for word in [
                "rain",
                "rf",
                "precip"
            ])
        ):
            rain_files.append(file)

print("Possible rainfall files found:", len(rain_files))
print()

for file in sorted(rain_files):
    print(file)

Possible rainfall files found: 4

/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/rainfall_daily_long.parquet
/Users/ohaseelanka/disaster_analytics_hub/data/processed/flood/kelani/kelani_daily_rainfall_2015_2025.csv
/Users/ohaseelanka/disaster_analytics_hub/data/raw/flood/kelani/2015 - 2025 RF.xlsx
/Users/ohaseelanka/disaster_analytics_hub/data/raw/landslide/rain_gauge_shortlist.xlsx

In [239]:
qgis_path = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/ds79_feature_matrix.csv"
)

ds_gis = pd.read_csv(qgis_path)

landslide_ds = [
    "Ambagamuwa",
    "Kothmale",
    "Nuwara Eliya",
    "Walapane",
    "Hanguranketha"
]

ds_matches = ds_gis[
    ds_gis["adm3_name"]
    .astype("string")
    .str.strip()
    .isin(landslide_ds)
].copy()

print("Matching DS divisions:", len(ds_matches))
print()

print(
    ds_matches[
        ["adm3_name", "adm3_pcode", "center_lat", "center_lon"]
    ].sort_values("adm3_name").to_string(index=False)
)

Matching DS divisions: 2

   adm3_name adm3_pcode  center_lat  center_lon
Nuwara Eliya     LK2312    6.897998   80.778032
    Walapane     LK2324    7.088056   80.834132

In [240]:
all_nuwara_ds = ds_gis[
    ds_gis["adm2_name"]
    .astype("string")
    .str.contains("Nuwara", case=False, na=False)
].copy()

print(
    all_nuwara_ds[
        ["adm3_name", "adm3_pcode", "center_lat", "center_lon"]
    ]
    .drop_duplicates()
    .sort_values("adm3_name")
    .to_string(index=False)
)

        adm3_name adm3_pcode  center_lat  center_lon
Ambagamuwa Korale     LK2315    6.951382   80.474234
     Hanguranketa     LK2306    7.174685   80.791419
    Kothmale East     LK2303    7.037375   80.698200
    Kothmale West     LK2321    7.028795   80.612003
        Mathurata     LK2318    7.088705   80.788718
    Nildandahinna     LK2309    7.088632   80.913975
          Norwood     LK2330    6.856014   80.578133
     Nuwara Eliya     LK2312    6.897998   80.778032
      Thalawakele     LK2327    6.889229   80.705843
         Walapane     LK2324    7.088056   80.834132

In [241]:
from math import radians, sin, cos, sqrt, atan2

# Norwood coordinate from Met_Stations.xlsx
norwood_lat = 6.8300
norwood_lon = 80.6000

ds_coords = ds_gis[
    ds_gis["adm2_name"]
    .astype("string")
    .str.contains("Nuwara", case=False, na=False)
][
    ["adm3_name", "adm3_pcode", "center_lat", "center_lon"]
].drop_duplicates().copy()

def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371.0

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        sin(dlat / 2) ** 2
        + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    )

    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c

ds_coords["distance_from_norwood_km"] = ds_coords.apply(
    lambda row: haversine_km(
        norwood_lat,
        norwood_lon,
        row["center_lat"],
        row["center_lon"]
    ),
    axis=1
)

print(
    ds_coords
    .sort_values("distance_from_norwood_km")
    .to_string(index=False)
)

        adm3_name adm3_pcode  center_lat  center_lon  distance_from_norwood_km
          Norwood     LK2330    6.856014   80.578133                  3.767652
      Thalawakele     LK2327    6.889229   80.705843                 13.413145
Ambagamuwa Korale     LK2315    6.951382   80.474234                 19.362905
     Nuwara Eliya     LK2312    6.897998   80.778032                 21.058616
    Kothmale West     LK2321    7.028795   80.612003                 22.144625
    Kothmale East     LK2303    7.037375   80.698200                 25.479710
        Mathurata     LK2318    7.088705   80.788718                 35.516238
         Walapane     LK2324    7.088056   80.834132                 38.616178
     Hanguranketa     LK2306    7.174685   80.791419                 43.764012
    Nildandahinna     LK2309    7.088632   80.913975                 45.033717

In [242]:
shortlist = pd.read_excel(
    rain_gauge_path,
    sheet_name="Request_shortlist"
)

print(
    shortlist[
        [
            "priority",
            "station",
            "type",
            "district",
            "lon",
            "lat",
            "new_target_incidents_within_5km",
            "target_incidents_within_5km_by_division"
        ]
    ].to_string(index=False)
)

                                                                                                                                                   priority                station                       type    district     lon    lat  new_target_incidents_within_5km target_incidents_within_5km_by_division
                                                                                                                                                          1        HELBODDE ESTATE Rain gauge (daily/monthly) NUWARA ELIA 80.6700 7.0800                            128.0                            Kothmale 128
                                                                                                                                                          2 SAMANALA POWER STATION Rain gauge (daily/monthly) NUWARA ELIA 80.4700 6.9800                            103.0                          Ambagamuwa 103
                                                                                                                                                          3            CASTLEREIGH Rain gauge (daily/monthly) NUWARA ELIA 80.5700 6.8700                             62.0                           Ambagamuwa 62
                                                                                                                                                          4            KURUNDU OYA Rain gauge (daily/monthly) NUWARA ELIA 80.8300 7.0700                             48.0                 Walapane 47, Kothmale 1
                                                                                                                                                          5     KOTHMALE RESERVOIR Rain gauge (daily/monthly)       KANDY 80.5830 7.0167                             45.0                 Kothmale 44, Walapane 1
                                                                                                                                                          6                 NORTON Rain gauge (daily/monthly) NUWARA ELIA 80.5167 6.9167                             42.0                           Ambagamuwa 51
                                                                                                                                                          7              LABUKELLE Rain gauge (daily/monthly) NUWARA ELIA 80.7200 7.0200                             23.0                 Kothmale 28, Walapane 1
                                                                                                                                                          8      LIDDESDALE ESTATE Rain gauge (daily/monthly) NUWARA ELIA 80.8500 7.0300                             22.0                             Walapane 30
                                                                                                                                                          9               KOTHMALE                    Agromet       KANDY 80.5800 7.0800                             22.0                             Kothmale 37
                                                                                                                                                         10     QUEENSBERRY ESTATE Rain gauge (daily/monthly) NUWARA ELIA 80.5984 6.9888                             17.0                 Kothmale 37, Walapane 1
                                                                                                                                                         11          BOGAHAMADITTA Rain gauge (daily/monthly)     BADULLA 80.9000 6.9700                             11.0                             Walapane 11
                                                                                                                                                         12        ANNFIELD ESTATE Rain gauge (daily/monthly) NUWARA ELIA 80.6300 6.8700                              7.0                           Ambagamuwa 43
                                                                                                                                                        NaN                    NaN                        NaN         NaN     NaN    NaN                              NaN                                     NaN
Source: station locations from Met_Stations.xlsx (Dept. of Meteorology list). Distances are from NBRI incident points. Locations only - no rainfall values.                    NaN                        NaN         NaN     NaN    NaN                              NaN                                     NaN

In [243]:
shortlist_stations = shortlist[
    shortlist["station"].notna()
]["station"].astype("string").str.strip().tolist()

for station in shortlist_stations:
    matches = met_station_raw[
        met_station_raw["Name"]
        .astype("string")
        .str.upper()
        .str.strip()
        .eq(station.upper())
    ]

    print("=" * 70)
    print("Station:", station)
    print("Matches:", len(matches))

    if len(matches) > 0:
        print(
            matches[
                [
                    "Name",
                    "Station ID",
                    "id",
                    "Station_id",
                    "District",
                    "Coord_Longitude",
                    "Coord_Latitude",
                    "Parameters Daily & Monthly",
                    "Parameter Daily/Monthly"
                ]
            ]
            .drop_duplicates()
            .to_string(index=False)
        )

======================================================================
Station: HELBODDE ESTATE
Matches: 2
           Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
HELBODDE ESTATE        NaN 01NE0156        NaN NUWARA ELIA        80.670000        7.080000                        NaN                Rainfall
HELBODDE ESTATE        NaN 01NE0156        NaN         NaN        80.663244        7.084725                        NaN                     NaN
======================================================================
Station: SAMANALA POWER STATION
Matches: 2
                  Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
SAMANALA POWER STATION        NaN 01NE317G        NaN NUWARA ELIA        80.470000        6.980000                        NaN                Rainfall
SAMANALA POWER STATION        NaN 01NE317G        NaN         NaN        80.456436        6.977543                        NaN                     NaN
======================================================================
Station: CASTLEREIGH
Matches: 2
       Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
CASTLEREIGH        NaN 01NE317B        NaN NUWARA ELIA            80.57            6.87                        NaN                Rainfall
CASTLEREIGH        NaN 01NE317B        NaN         NaN            80.57            6.87                        NaN                     NaN
======================================================================
Station: KURUNDU OYA
Matches: 2
       Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
KURUNDU OYA        NaN 01NE0264        NaN NUWARA ELIA            80.83            7.07                        NaN                Rainfall
KURUNDU OYA        NaN 01NE0264        NaN         NaN            80.83            7.07                        NaN                     NaN
======================================================================
Station: KOTHMALE RESERVOIR
Matches: 2
              Name Station ID       id Station_id District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
KOTHMALE RESERVOIR        NaN 01KY317N        NaN    KANDY          80.5830          7.0167                        NaN                Rainfall
KOTHMALE RESERVOIR        NaN 01KY317N        NaN      NaN          80.5833          7.0167                        NaN                     NaN
======================================================================
Station: NORTON
Matches: 2
  Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
NORTON        NaN 01NE317E        NaN NUWARA ELIA          80.5167          6.9167                        NaN                Rainfall
NORTON        NaN 01NE317E        NaN         NaN          80.5167          6.9167                        NaN                     NaN
======================================================================
Station: LABUKELLE
Matches: 2
     Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
LABUKELLE        NaN 01NE0266        NaN NUWARA ELIA        80.720000        7.020000                        NaN                Rainfall
LABUKELLE        NaN 01NE0266        NaN         NaN        80.719328        7.024501                        NaN                     NaN
======================================================================
Station: LIDDESDALE ESTATE
Matches: 2
             Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
LIDDESDALE ESTATE        NaN 01NE0274        NaN NUWARA ELIA        80.850000        7.030000                        NaN                Rainfall
LIDDESDALE ESTATE        NaN 01NE0274        NaN         NaN        80.855651        7.017976                        NaN                     NaN
======================================================================
Station: KOTHMALE
Matches: 1
    Name Station ID  id Station_id District  Coord_Longitude  Coord_Latitude                                                                                                      Parameters Daily & Monthly Parameter Daily/Monthly
KOTHMALE        NaN NaN     01AG12    KANDY            80.58            7.08 Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,RH Morning,RH Evening,Evoporation,Sunshine Hours,Soil Temperatures,Wind (Sp & Dir)                     NaN
======================================================================
Station: QUEENSBERRY ESTATE
Matches: 2
              Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
QUEENSBERRY ESTATE        NaN 01NE370A        NaN NUWARA ELIA        80.598427        6.988788                        NaN                Rainfall
QUEENSBERRY ESTATE        NaN 01NE370A        NaN         NaN        80.598459        6.988860                        NaN                     NaN
======================================================================
Station: BOGAHAMADITTA
Matches: 2
         Name Station ID       id Station_id District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
BOGAHAMADITTA        NaN 01BD048B        NaN  BADULLA             80.9            6.97                        NaN                Rainfall
BOGAHAMADITTA        NaN 01BD048B        NaN      NaN             80.9            6.97                        NaN                     NaN
======================================================================
Station: ANNFIELD ESTATE
Matches: 2
           Name Station ID       id Station_id    District  Coord_Longitude  Coord_Latitude Parameters Daily & Monthly Parameter Daily/Monthly
ANNFIELD ESTATE        NaN 01NE0017        NaN NUWARA ELIA            80.63            6.87                        NaN                Rainfall
ANNFIELD ESTATE        NaN 01NE0017        NaN         NaN            80.63            6.87                        NaN                     NaN

In [244]:
from pathlib import Path
import pandas as pd

rain_path = Path(
    "/Users/ohaseelanka/Downloads/lka-rainfall-subnat-full.csv"
)

print("File exists:", rain_path.exists())
print("File size (MB):", round(rain_path.stat().st_size / (1024**2), 2))

rain_raw = pd.read_csv(rain_path)

print("\nShape:", rain_raw.shape)
print("\nColumns:")
print(rain_raw.columns.tolist())

print("\nFirst 5 rows:")
display(rain_raw.head())

File exists: True
File size (MB): 6.46

Shape: (55998, 15)

Columns:
['date', 'adm_level', 'adm_id', 'PCODE', 'n_pixels', 'rfh', 'rfh_avg', 'r1h', 'r1h_avg', 'r3h', 'r3h_avg', 'rfq', 'r1q', 'r3q', 'version']

First 5 rows:

,date,adm_level,adm_id,PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version
0,1981-01-01,2,25830,LK22,67.0,105.970146,71.977610,NaN,NaN,NaN,NaN,144.159000,NaN,NaN,final
1,1981-01-11,2,25830,LK22,67.0,7.716418,56.896020,NaN,NaN,NaN,NaN,20.544806,NaN,NaN,final
2,1981-01-21,2,25830,LK22,67.0,4.328358,54.214924,118.014920,183.08856,NaN,NaN,15.753390,65.402664,NaN,final
3,1981-02-01,2,25830,LK22,67.0,54.358208,44.043285,66.402985,155.15424,NaN,NaN,121.032290,44.583885,NaN,final
4,1981-02-11,2,25830,LK22,67.0,3.731343,30.813930,62.417908,129.07214,NaN,NaN,24.379740,50.284798,NaN,final

In [245]:
print("Administrative levels:")
print(
    rain_raw["adm_level"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nUnique PCODE count:", rain_raw["PCODE"].nunique())

print("\nDate range:")
print("Start:", rain_raw["date"].min())
print("End:", rain_raw["date"].max())

print("\nNumber of unique dates:", rain_raw["date"].nunique())

print("\nSample PCODEs:")
print(
    rain_raw["PCODE"]
    .dropna()
    .drop_duplicates()
    .head(30)
    .tolist()
)

Administrative levels:
adm_level
1    14823
2    41175
Name: count, dtype: int64

Unique PCODE count: 34

Date range:
Start: 1981-01-01
End: 2026-09-21

Number of unique dates: 1647

Sample PCODEs:
['LK22', 'LK52', 'LK51', 'LK53', 'LK71', 'LK72', 'LK61', 'LK62', 'LK2', 'LK41', 'LK5', 'LK45', 'LK42', 'LK7', 'LK6', 'LK44', 'LK4', 'LK21', 'LK23', 'LK9', 'LK43', 'LK3', 'LK92', 'LK8', 'LK1', 'LK91', 'LK31', 'LK33', 'LK32', 'LK81']

In [247]:
nuwara_rain = rain_raw[
    rain_raw["PCODE"].astype("string").str.strip() == "LK23"
].copy()

print("Shape:", nuwara_rain.shape)

print("\nDate range:")
print("Start:", nuwara_rain["date"].min())
print("End:", nuwara_rain["date"].max())

print("\nAdministrative levels:")
print(nuwara_rain["adm_level"].value_counts())

print("\nFirst 10 rows:")
display(nuwara_rain.head(10))

print("\nLast 10 rows:")
display(nuwara_rain.tail(10))

print("\nMissing values:")
display(nuwara_rain.isna().sum())

Shape: (1647, 15)

Date range:
Start: 1981-01-01
End: 2026-09-21

Administrative levels:
adm_level
2    1647
Name: count, dtype: int64

First 10 rows:

,date,adm_level,adm_id,PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version
27606,1981-01-01,2,41749,LK23,58.0,96.706894,48.627586,NaN,NaN,NaN,NaN,189.654070,NaN,NaN,final
27607,1981-01-11,2,41749,LK23,58.0,7.724138,45.348274,NaN,NaN,NaN,NaN,25.272243,NaN,NaN,final
27608,1981-01-21,2,41749,LK23,58.0,3.586207,43.304596,108.017235,137.280460,NaN,NaN,17.775133,79.432720,NaN,final
27609,1981-02-01,2,41749,LK23,58.0,52.293102,42.146553,63.603447,130.799420,NaN,NaN,121.521290,50.518215,NaN,final
27610,1981-02-11,2,41749,LK23,58.0,3.620690,35.041954,59.500000,120.493100,NaN,NaN,21.529142,51.397247,NaN,final
27611,1981-02-21,2,41749,LK23,58.0,9.879311,30.390230,65.793106,107.578735,NaN,NaN,42.043556,62.883198,NaN,final
27612,1981-03-01,2,41749,LK23,58.0,23.551723,38.354023,37.051723,103.786210,NaN,NaN,65.857150,38.655380,NaN,final
27613,1981-03-11,2,41749,LK23,58.0,19.034483,47.558044,52.465515,116.302300,NaN,NaN,45.729410,47.373806,NaN,final
27614,1981-03-21,2,41749,LK23,58.0,62.586210,55.414944,105.172410,141.327010,278.98276,386.18622,111.870026,75.291916,72.595280,final
27615,1981-04-01,2,41749,LK23,58.0,62.224136,72.696550,143.844820,175.669540,244.50000,410.25516,86.521390,82.385124,60.083538,final

Last 10 rows:

,date,adm_level,adm_id,PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version
29243,2026-06-21,2,41749,LK23,58.0,129.327590,67.698850,284.60345,226.02873,921.17240,679.18274,184.772640,125.353874,135.369160,final
29244,2026-07-01,2,41749,LK23,58.0,20.362068,55.169540,256.15518,200.74483,872.37933,661.65576,42.151010,126.931595,131.609050,final
29245,2026-07-11,2,41749,LK23,58.0,28.241379,58.766666,177.93105,181.63506,805.75860,643.68164,52.129710,98.015370,124.985596,final
29246,2026-07-21,2,41749,LK23,58.0,51.517242,59.444828,100.12069,173.38103,722.51720,626.32587,87.698654,58.930420,115.236404,final
29247,2026-08-01,2,41749,LK23,58.0,51.189655,41.375862,130.94827,159.58736,592.44830,584.61554,121.161420,82.599464,101.328450,final
29248,2026-08-11,2,41749,LK23,58.0,16.551723,60.892530,119.25862,161.71321,492.39658,574.35920,32.707386,74.534355,85.852880,final
29249,2026-08-21,2,41749,LK23,58.0,33.068966,63.867240,100.81035,166.13564,485.53452,565.54540,55.278770,61.828358,85.976425,final
29250,2026-09-01,2,41749,LK23,58.0,49.017242,74.064370,98.63793,198.82414,485.74140,559.15630,68.320590,50.846737,86.986780,prelim
29251,2026-09-11,2,41749,LK23,58.0,152.672410,71.706320,234.75862,209.63792,531.94830,552.98620,205.553340,111.703750,96.229675,prelim
29252,2026-09-21,2,41749,LK23,58.0,65.879310,91.155750,267.56897,236.92644,468.50000,576.44310,73.713030,112.666060,81.435310,prelim

Missing values:

date         0
adm_level    0
adm_id       0
PCODE        0
n_pixels     0
rfh          0
rfh_avg      0
r1h          2
r1h_avg      2
r3h          8
r3h_avg      8
rfq          0
r1q          2
r3q          8
version      0
dtype: int64

In [248]:
rain_vars = [
    "rfh", "rfh_avg",
    "r1h", "r1h_avg",
    "r3h", "r3h_avg",
    "rfq", "r1q", "r3q"
]

print("Rainfall variable summary for Nuwara Eliya (LK23):")

display(
    nuwara_rain[rain_vars].describe().T
)

print("\nCorrelation between rainfall variables:")
display(
    nuwara_rain[rain_vars].corr().round(3)
)

Rainfall variable summary for Nuwara Eliya (LK23):

,count,mean,std,min,25%,50%,75%,max
rfh,1647.0,69.193110,52.249832,2.051724,29.396552,56.758620,97.465515,318.72415
rfh_avg,1647.0,69.824593,22.675139,30.390230,48.627586,71.706320,81.749430,124.78966
r1h,1645.0,207.536526,112.223066,10.500000,126.603455,194.793120,273.068970,617.20690
r1h_avg,1645.0,209.527379,63.537785,103.786210,161.713210,207.601150,236.926440,339.17758
r3h,1639.0,623.564528,233.541280,50.620690,464.853435,603.000000,757.655150,1411.17250
r3h_avg,1639.0,628.864982,141.432578,386.186220,552.190250,603.112700,700.314400,895.27124
rfq,1647.0,99.349615,68.831029,7.441805,50.361263,84.381195,130.038200,709.04080
r1q,1645.0,99.068009,49.029138,10.592712,67.375430,92.669365,123.897960,468.59158
r3q,1639.0,99.091567,32.037713,14.170763,77.865082,95.866745,117.332490,288.34930

Correlation between rainfall variables:

           rfh  rfh_avg    r1h  r1h_avg    r3h  r3h_avg    rfq    r1q    r3q
rfh      1.000    0.425  0.688    0.399  0.399    0.164  0.855  0.531  0.357
rfh_avg  0.425    1.000  0.512    0.918  0.225    0.375 -0.009 -0.005 -0.001
r1h      0.688    0.512  1.000    0.563  0.654    0.355  0.506  0.783  0.528
r1h_avg  0.399    0.918  0.563    1.000  0.380    0.629  0.002  0.000  0.002
r3h      0.399    0.225  0.654    0.380  1.000    0.606  0.333  0.520  0.776
r3h_avg  0.164    0.375  0.355    0.629  0.606    1.000  0.002  0.003  0.010
rfq      0.855   -0.009  0.506    0.002  0.333    0.002  1.000  0.638  0.407
r1q      0.531   -0.005  0.783    0.000  0.520    0.003  0.638  1.000  0.656
r3q      0.357   -0.001  0.528    0.002  0.776    0.010  0.407  0.656  1.000

In [249]:
import pandas as pd
from pathlib import Path

# Original rainfall file
rain_path = Path(
    "/Users/ohaseelanka/Downloads/lka-rainfall-subnat-full.csv"
)

# Load the dataset
rain_raw = pd.read_csv(rain_path)

# Keep only Nuwara Eliya District (LK23)
nuwara_rain = rain_raw[
    rain_raw["PCODE"].astype("string").str.strip() == "LK23"
].copy()

# Convert date
nuwara_rain["date"] = pd.to_datetime(
    nuwara_rain["date"],
    errors="coerce"
)

# Sort chronologically
nuwara_rain = (
    nuwara_rain
    .sort_values("date")
    .reset_index(drop=True)
)

print("Nuwara Eliya rainfall shape:", nuwara_rain.shape)
print("Date range:", nuwara_rain["date"].min(), "to", nuwara_rain["date"].max())

print("\nAdministrative level:")
print(nuwara_rain["adm_level"].value_counts(dropna=False))

print("\nPCODE:")
print(nuwara_rain["PCODE"].unique())

print("\nUnique administrative units:")
print(nuwara_rain["adm_id"].unique())

print("\nFirst 5 rows:")
display(nuwara_rain.head())

Nuwara Eliya rainfall shape: (1647, 15)
Date range: 1981-01-01 00:00:00 to 2026-09-21 00:00:00

Administrative level:
adm_level
2    1647
Name: count, dtype: int64

PCODE:
['LK23']

Unique administrative units:
[41749]

First 5 rows:

,date,adm_level,adm_id,PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version
0,1981-01-01,2,41749,LK23,58.0,96.706894,48.627586,NaN,NaN,NaN,NaN,189.654070,NaN,NaN,final
1,1981-01-11,2,41749,LK23,58.0,7.724138,45.348274,NaN,NaN,NaN,NaN,25.272243,NaN,NaN,final
2,1981-01-21,2,41749,LK23,58.0,3.586207,43.304596,108.017235,137.28046,NaN,NaN,17.775133,79.432720,NaN,final
3,1981-02-01,2,41749,LK23,58.0,52.293102,42.146553,63.603447,130.79942,NaN,NaN,121.521290,50.518215,NaN,final
4,1981-02-11,2,41749,LK23,58.0,3.620690,35.041954,59.500000,120.49310,NaN,NaN,21.529142,51.397247,NaN,final

In [250]:
# Check the time gaps between rainfall observations

rain_dates = (
    nuwara_rain["date"]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

date_gaps = rain_dates.diff().dt.days

print("Number of unique rainfall dates:", len(rain_dates))

print("\nDate-gap distribution:")
print(date_gaps.value_counts(dropna=False).sort_index())

print("\nFirst 20 rainfall dates:")
print(rain_dates.head(20).to_string(index=False))

print("\nLast 20 rainfall dates:")
print(rain_dates.tail(20).to_string(index=False))

Number of unique rainfall dates: 1647

Date-gap distribution:
date
8.0       35
9.0       11
10.0    1280
11.0     320
NaN        1
Name: count, dtype: int64

First 20 rainfall dates:
1981-01-01
1981-01-11
1981-01-21
1981-02-01
1981-02-11
1981-02-21
1981-03-01
1981-03-11
1981-03-21
1981-04-01
1981-04-11
1981-04-21
1981-05-01
1981-05-11
1981-05-21
1981-06-01
1981-06-11
1981-06-21
1981-07-01
1981-07-11

Last 20 rainfall dates:
2026-03-11
2026-03-21
2026-04-01
2026-04-11
2026-04-21
2026-05-01
2026-05-11
2026-05-21
2026-06-01
2026-06-11
2026-06-21
2026-07-01
2026-07-11
2026-07-21
2026-08-01
2026-08-11
2026-08-21
2026-09-01
2026-09-11
2026-09-21

In [251]:
print("Checking landslide episode dataframe...")

print("Variable exists:", "landslide_episode_summary" in globals())

if "landslide_episode_summary" in globals():
    print("\nShape:", landslide_episode_summary.shape)
    
    print("\nColumns:")
    print(landslide_episode_summary.columns.tolist())
    
    print("\nDate range:")
    print(
        landslide_episode_summary["start_date"].min(),
        "to",
        landslide_episode_summary["end_date"].max()
    )
    
    print("\nFirst 10 episodes:")
    display(
        landslide_episode_summary[
            [
                "episode_id",
                "start_date",
                "end_date",
                "incident_count",
                "ds_count",
                "total_indirectly_affected"
            ]
        ].head(10)
    )
else:
    print(
        "\nlandslide_episode_summary is not currently available."
        "\nDo not recreate anything yet."
    )

Checking landslide episode dataframe...
Variable exists: True

Shape: (62, 11)

Columns:
['episode_id', 'start_date', 'end_date', 'incident_count', 'ds_count', 'ds_divisions', 'total_deaths', 'total_houses_destroyed', 'total_houses_damaged', 'total_indirectly_affected', 'duration_days']

Date range:
2003-05-17 00:00:00 to 2019-12-19 00:00:00

First 10 episodes:

,episode_id,start_date,end_date,incident_count,ds_count,total_indirectly_affected
0,NE_LS_EP001,2003-05-17,2003-05-18,3,1,505.0
1,NE_LS_EP002,2006-01-14,2006-01-14,1,1,10365.0
2,NE_LS_EP003,2006-04-01,2006-04-01,1,1,0.0
3,NE_LS_EP004,2006-11-15,2006-11-15,1,1,0.0
4,NE_LS_EP005,2007-01-11,2007-01-15,8,2,1200.0
5,NE_LS_EP006,2007-02-01,2007-02-01,1,1,360.0
6,NE_LS_EP007,2007-05-09,2007-05-09,1,1,1343.0
7,NE_LS_EP008,2007-10-12,2007-10-12,1,1,1180.0
8,NE_LS_EP009,2008-03-13,2008-03-13,1,1,6.0
9,NE_LS_EP010,2008-06-01,2008-06-02,3,2,83.0

In [252]:
# Inspect rainfall around the first landslide episode

first_episode = landslide_episode_summary.iloc[0]

episode_start = first_episode["start_date"]
episode_end = first_episode["end_date"]

print("Episode:", first_episode["episode_id"])
print("Landslide period:", episode_start.date(), "to", episode_end.date())

# Show rainfall observations around the episode
rain_check = nuwara_rain[
    (nuwara_rain["date"] >= episode_start - pd.Timedelta(days=40)) &
    (nuwara_rain["date"] <= episode_end + pd.Timedelta(days=20))
].copy()

display(
    rain_check[
        [
            "date",
            "rfh",
            "rfh_avg",
            "r1h",
            "r1h_avg",
            "r3h",
            "r3h_avg",
            "rfq",
            "r1q",
            "r3q",
            "version"
        ]
    ]
)

Episode: NE_LS_EP001
Landslide period: 2003-05-17 to 2003-05-18

,date,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version
802,2003-04-11,57.637930,76.740810,152.94827,204.85230,481.58624,441.64767,76.629944,75.26640,108.941860,final
803,2003-04-21,121.120690,76.800575,208.25862,226.23793,569.84485,475.14368,154.180680,92.22476,119.723510,final
804,2003-05-01,101.017240,83.086205,279.77588,236.62758,621.81030,516.08330,120.356240,117.85736,120.289840,final
805,2003-05-11,109.586205,71.148850,331.72415,231.03563,680.10345,552.19025,150.476610,142.65819,122.956825,final
806,2003-05-21,18.206896,72.681040,228.81035,226.91609,693.60345,594.48100,29.874596,100.81679,116.534710,final
807,2003-06-01,48.706898,80.453445,176.50000,224.28334,706.89660,636.58044,62.849308,79.15970,110.959840,final

In [253]:
# Create explicit dekad start and end dates
# for the Nuwara Eliya rainfall observations.

rain_dekad = nuwara_rain.copy()

rain_dekad["dekad_start"] = rain_dekad["date"]

rain_dekad["dekad_end"] = (
    rain_dekad["date"].shift(-1) - pd.Timedelta(days=1)
)

# The final observation has no following rainfall observation,
# so its end date is set to the end of that calendar month.
last_idx = rain_dekad.index[-1]

rain_dekad.loc[last_idx, "dekad_end"] = (
    rain_dekad.loc[last_idx, "date"]
    + pd.offsets.MonthEnd(0)
)

print("Rainfall dekad table shape:", rain_dekad.shape)

print("\nFirst 6 dekads:")
display(
    rain_dekad[
        [
            "date",
            "dekad_start",
            "dekad_end",
            "rfh",
            "r1h",
            "r3h",
            "rfq",
            "r1q",
            "r3q"
        ]
    ].head(6)
)

Rainfall dekad table shape: (1647, 17)

First 6 dekads:

,date,dekad_start,dekad_end,rfh,r1h,r3h,rfq,r1q,r3q
0,1981-01-01,1981-01-01,1981-01-10,96.706894,NaN,NaN,189.654070,NaN,NaN
1,1981-01-11,1981-01-11,1981-01-20,7.724138,NaN,NaN,25.272243,NaN,NaN
2,1981-01-21,1981-01-21,1981-01-31,3.586207,108.017235,NaN,17.775133,79.432720,NaN
3,1981-02-01,1981-02-01,1981-02-10,52.293102,63.603447,NaN,121.521290,50.518215,NaN
4,1981-02-11,1981-02-11,1981-02-20,3.620690,59.500000,NaN,21.529142,51.397247,NaN
5,1981-02-21,1981-02-21,1981-02-28,9.879311,65.793106,NaN,42.043556,62.883198,NaN

In [254]:
# Match all 62 landslide episodes to overlapping rainfall dekads

rainfall_features = [
    "rfh",
    "r1h",
    "r3h",
    "rfq",
    "r1q",
    "r3q"
]

matched_rows = []

for _, episode in landslide_episode_summary.iterrows():

    episode_start = episode["start_date"]
    episode_end = episode["end_date"]

    # Find rainfall dekads that overlap the landslide episode
    matching_rain = rain_dekad[
        (rain_dekad["dekad_start"] <= episode_end) &
        (rain_dekad["dekad_end"] >= episode_start)
    ].copy()

    row = {
        "episode_id": episode["episode_id"],
        "start_date": episode_start,
        "end_date": episode_end,
        "incident_count": episode["incident_count"],
        "ds_count": episode["ds_count"],
        "ds_divisions": episode["ds_divisions"],
        "total_deaths": episode["total_deaths"],
        "total_houses_destroyed": episode["total_houses_destroyed"],
        "total_houses_damaged": episode["total_houses_damaged"],
        "total_indirectly_affected": episode["total_indirectly_affected"],
        "duration_days": episode["duration_days"],
        "rainfall_dekads_matched": len(matching_rain)
    }

    # Store rainfall features
    for feature in rainfall_features:
        row[f"event_{feature}_max"] = matching_rain[feature].max()

    # Keep the rainfall dates that were matched
    row["matched_rainfall_dates"] = ", ".join(
        matching_rain["date"].dt.strftime("%Y-%m-%d")
    )

    matched_rows.append(row)


landslide_rainfall_matched = pd.DataFrame(matched_rows)

print("Matched dataset shape:", landslide_rainfall_matched.shape)

print("\nEpisodes with rainfall matches:")
print(
    landslide_rainfall_matched["rainfall_dekads_matched"]
    .value_counts()
    .sort_index()
)

print("\nEpisodes without rainfall matches:")
print(
    landslide_rainfall_matched[
        landslide_rainfall_matched["rainfall_dekads_matched"] == 0
    ]["episode_id"].tolist()
)

print("\nFirst 10 matched episodes:")
display(
    landslide_rainfall_matched[
        [
            "episode_id",
            "start_date",
            "end_date",
            "rainfall_dekads_matched",
            "event_rfh_max",
            "event_r1h_max",
            "event_r3h_max",
            "event_rfq_max",
            "event_r1q_max",
            "event_r3q_max",
            "total_indirectly_affected"
        ]
    ].head(10)
)

Matched dataset shape: (62, 19)

Episodes with rainfall matches:
rainfall_dekads_matched
1    60
2     2
Name: count, dtype: int64

Episodes without rainfall matches:
[]

First 10 matched episodes:

,episode_id,start_date,end_date,rainfall_dekads_matched,event_rfh_max,event_r1h_max,event_r3h_max,event_rfq_max,event_r1q_max,event_r3q_max,total_indirectly_affected
0,NE_LS_EP001,2003-05-17,2003-05-18,1,109.586205,331.72415,680.10345,150.476610,142.658190,122.956825,505.0
1,NE_LS_EP002,2006-01-14,2006-01-14,1,107.137930,228.39655,1093.79310,222.724490,135.019400,140.433640,10365.0
2,NE_LS_EP003,2006-04-01,2006-04-01,1,16.844828,125.79310,471.06894,28.115570,72.393550,114.644920,0.0
3,NE_LS_EP004,2006-11-15,2006-11-15,1,225.465520,617.20690,1201.41380,208.664840,182.879010,144.956700,0.0
4,NE_LS_EP005,2007-01-11,2007-01-15,1,125.637930,222.82758,1134.77590,259.468570,131.797760,145.671540,1200.0
5,NE_LS_EP006,2007-02-01,2007-02-01,1,4.189655,176.41379,793.81030,19.491680,133.589520,124.580190,360.0
6,NE_LS_EP007,2007-05-09,2007-05-09,1,42.948277,209.24138,574.89660,54.433357,88.665950,111.286736,1343.0
7,NE_LS_EP008,2007-10-12,2007-10-12,1,127.034485,217.67241,760.03455,115.418230,77.480545,116.135580,1180.0
8,NE_LS_EP009,2008-03-13,2008-03-13,1,303.517240,483.08620,729.53455,587.002870,402.371800,179.304810,6.0
9,NE_LS_EP010,2008-06-01,2008-06-02,1,140.017240,230.93103,1011.94824,169.703220,102.899340,158.506740,83.0

In [255]:
# ---------------------------------------------------------
# Step 4: Create PRE-EVENT rainfall features
# ---------------------------------------------------------

# Make sure rainfall is sorted chronologically
rain_dekad = (
    rain_dekad
    .sort_values("dekad_start")
    .reset_index(drop=True)
)

# Use the dekad containing the START of each landslide episode.
# This prevents rainfall after the initial event from being
# used as a predictor.

pre_event_rows = []

for _, episode in landslide_episode_summary.iterrows():

    event_start = episode["start_date"]

    # Find the rainfall dekad containing the episode start
    current_idx = rain_dekad.index[
        (rain_dekad["dekad_start"] <= event_start) &
        (rain_dekad["dekad_end"] >= event_start)
    ]

    if len(current_idx) == 0:
        pre_event_rows.append({
            "episode_id": episode["episode_id"]
        })
        continue

    current_idx = current_idx[0]

    # Previous rainfall dekads
    previous_1 = (
        rain_dekad.iloc[current_idx - 1]
        if current_idx >= 1 else None
    )

    previous_2 = (
        rain_dekad.iloc[max(0, current_idx - 2):current_idx]
    )

    previous_3 = (
        rain_dekad.iloc[max(0, current_idx - 3):current_idx]
    )

    row = {
        "episode_id": episode["episode_id"],
        "event_start": event_start,

        # Rainfall dekad immediately before the event
        "pre_rfh_1dekad": (
            previous_1["rfh"]
            if previous_1 is not None else None
        ),

        # Rainfall accumulated over previous 2 dekads
        "pre_rfh_2dekad_sum": (
            previous_2["rfh"].sum()
            if len(previous_2) > 0 else None
        ),

        # Rainfall accumulated over previous 3 dekads
        "pre_rfh_3dekad_sum": (
            previous_3["rfh"].sum()
            if len(previous_3) > 0 else None
        ),

        # Conditions immediately before the event
        "pre_r1h": (
            previous_1["r1h"]
            if previous_1 is not None else None
        ),

        "pre_r3h": (
            previous_1["r3h"]
            if previous_1 is not None else None
        ),

        "pre_rfq": (
            previous_1["rfq"]
            if previous_1 is not None else None
        ),

        "pre_r1q": (
            previous_1["r1q"]
            if previous_1 is not None else None
        ),

        "pre_r3q": (
            previous_1["r3q"]
            if previous_1 is not None else None
        ),

        # Keep track of which rainfall dekad was used
        "pre_event_rainfall_date": (
            previous_1["date"]
            if previous_1 is not None else None
        )
    }

    pre_event_rows.append(row)


landslide_pre_event_rainfall = pd.DataFrame(pre_event_rows)

print(
    "Pre-event rainfall table shape:",
    landslide_pre_event_rainfall.shape
)

print("\nMissing values:")
display(
    landslide_pre_event_rainfall.isna().sum()
)

print("\nFirst 10 episodes:")
display(
    landslide_pre_event_rainfall.head(10)
)

Pre-event rainfall table shape: (62, 11)

Missing values:

episode_id                 0
event_start                0
pre_rfh_1dekad             0
pre_rfh_2dekad_sum         0
pre_rfh_3dekad_sum         0
pre_r1h                    0
pre_r3h                    0
pre_rfq                    0
pre_r1q                    0
pre_r3q                    0
pre_event_rainfall_date    0
dtype: int64

First 10 episodes:

,episode_id,event_start,pre_rfh_1dekad,pre_rfh_2dekad_sum,pre_rfh_3dekad_sum,pre_r1h,pre_r3h,pre_rfq,pre_r1q,pre_r3q,pre_event_rainfall_date
0,NE_LS_EP001,2003-05-17,101.017240,222.137930,279.775860,279.77588,621.81030,120.35624,117.857360,120.28984,2003-05-01
1,NE_LS_EP002,2006-01-14,86.224140,121.258620,205.568970,205.56897,1114.13800,170.10674,99.044130,132.59575,2006-01-01
2,NE_LS_EP003,2006-04-01,65.189650,108.948270,224.034475,224.03447,540.44824,116.17929,156.522340,139.43442,2006-03-21
3,NE_LS_EP004,2006-11-15,158.120700,391.741400,605.913810,605.91380,1024.67250,148.30316,177.499590,130.71838,2006-11-01
4,NE_LS_EP005,2007-01-11,35.362070,97.189657,270.862067,270.86206,1223.31040,75.26363,129.755680,145.53053,2007-01-01
5,NE_LS_EP006,2007-02-01,46.586210,172.224140,207.586210,207.58621,947.74133,106.79358,149.413500,135.08037,2007-01-21
6,NE_LS_EP007,2007-05-09,99.379310,166.293105,435.293105,435.29310,536.13794,127.60217,190.406950,112.70334,2007-04-21
7,NE_LS_EP008,2007-10-12,58.603447,90.637927,165.448277,165.44827,707.96560,73.24288,68.260910,117.24235,2007-10-01
8,NE_LS_EP009,2008-03-13,144.741380,179.568967,198.775863,198.77586,588.65515,345.39212,187.317730,132.75328,2008-03-01
9,NE_LS_EP010,2008-06-01,71.293106,90.913796,104.724141,104.72414,1016.67240,98.21329,47.311996,170.42615,2008-05-21

In [256]:
# ---------------------------------------------------------
# Step 5: Validate pre-event rainfall features
# ---------------------------------------------------------

rainfall_feature_cols = [
    "pre_rfh_1dekad",
    "pre_rfh_2dekad_sum",
    "pre_rfh_3dekad_sum",
    "pre_r1h",
    "pre_r3h",
    "pre_rfq",
    "pre_r1q",
    "pre_r3q"
]

print("Number of episodes:", len(landslide_pre_event_rainfall))

print("\nMissing values:")
display(
    landslide_pre_event_rainfall[rainfall_feature_cols]
    .isna()
    .sum()
)

print("\nInfinite values:")
print(
    landslide_pre_event_rainfall[rainfall_feature_cols]
    .isin([float("inf"), float("-inf")])
    .sum()
)

print("\nDescriptive statistics:")
display(
    landslide_pre_event_rainfall[rainfall_feature_cols]
    .describe()
    .T
)

print("\nHighest pre-event 10-day rainfall:")
display(
    landslide_pre_event_rainfall[
        [
            "episode_id",
            "event_start",
            "pre_event_rainfall_date",
            "pre_rfh_1dekad",
            "pre_rfh_2dekad_sum",
            "pre_rfh_3dekad_sum",
            "pre_rfq",
            "total_indirectly_affected"
        ]
    ]
    .sort_values("pre_rfh_1dekad", ascending=False)
    .head(10)
)

Number of episodes: 62

Missing values:

pre_rfh_1dekad        0
pre_rfh_2dekad_sum    0
pre_rfh_3dekad_sum    0
pre_r1h               0
pre_r3h               0
pre_rfq               0
pre_r1q               0
pre_r3q               0
dtype: int64

Infinite values:
pre_rfh_1dekad        0
pre_rfh_2dekad_sum    0
pre_rfh_3dekad_sum    0
pre_r1h               0
pre_r3h               0
pre_rfq               0
pre_r1q               0
pre_r3q               0
dtype: int64

Descriptive statistics:

,count,mean,std,min,25%,50%,75%,max
pre_rfh_1dekad,62.0,92.282537,50.971685,10.568966,58.732758,76.353450,117.409482,230.06897
pre_rfh_2dekad_sum,62.0,179.372359,84.631410,41.586206,110.974134,166.948275,230.892245,391.74140
pre_rfh_3dekad_sum,62.0,259.038933,113.222344,58.810344,196.474143,233.879311,316.133619,605.91381
pre_r1h,62.0,259.038932,113.222344,58.810345,196.474147,233.879320,316.133605,605.91380
pre_r3h,62.0,719.711350,226.012360,256.500000,572.375013,663.577570,830.965525,1238.41370
pre_rfq,62.0,118.555257,59.376024,32.501656,77.036396,105.304145,148.254245,345.39212
pre_r1q,62.0,110.961032,38.541873,45.506910,86.259098,109.687487,137.110520,190.40695
pre_r3q,62.0,112.069654,23.867910,58.547264,96.435466,118.892688,130.231850,170.42615

Highest pre-event 10-day rainfall:

KeyError: "['total_indirectly_affected'] not in index"

In [257]:
# Add the impact value temporarily for validation/inspection

rainfall_check = landslide_pre_event_rainfall.merge(
    landslide_episode_summary[
        [
            "episode_id",
            "total_indirectly_affected"
        ]
    ],
    on="episode_id",
    how="left"
)

print("Shape:", rainfall_check.shape)

print("\nHighest pre-event 10-day rainfall:")
display(
    rainfall_check[
        [
            "episode_id",
            "event_start",
            "pre_event_rainfall_date",
            "pre_rfh_1dekad",
            "pre_rfh_2dekad_sum",
            "pre_rfh_3dekad_sum",
            "pre_rfq",
            "total_indirectly_affected"
        ]
    ]
    .sort_values("pre_rfh_1dekad", ascending=False)
    .head(10)
)

Shape: (62, 12)

Highest pre-event 10-day rainfall:

,episode_id,event_start,pre_event_rainfall_date,pre_rfh_1dekad,pre_rfh_2dekad_sum,pre_rfh_3dekad_sum,pre_rfq,total_indirectly_affected
24,NE_LS_EP025,2010-12-05,2010-11-21,230.06897,351.379320,487.137940,202.92316,16.0
53,NE_LS_EP054,2018-11-08,2018-10-21,190.96552,287.931035,475.879305,150.98700,7.0
51,NE_LS_EP052,2018-10-15,2018-10-01,187.94827,293.068960,365.086200,222.19060,35.0
22,NE_LS_EP023,2010-10-06,2010-09-21,186.94827,239.706890,285.362064,199.62227,10.0
47,NE_LS_EP048,2015-11-05,2015-10-21,184.37930,352.000000,437.913795,145.91248,264.0
23,NE_LS_EP024,2010-10-13,2010-10-01,170.60345,357.551720,410.310340,202.21707,128.0
38,NE_LS_EP039,2014-12-22,2014-12-11,168.24138,274.586206,454.482756,192.36145,447.0
58,NE_LS_EP059,2019-10-08,2019-09-21,166.86208,312.637940,368.913804,178.73303,21.0
28,NE_LS_EP029,2013-06-23,2013-06-11,165.75862,272.534480,316.155170,206.04002,236.0
3,NE_LS_EP004,2006-11-15,2006-11-01,158.12070,391.741400,605.913810,148.30316,0.0

In [258]:
# ---------------------------------------------------------
# Step 5C — Check correlation/redundancy among rainfall features
# ---------------------------------------------------------

rainfall_corr = (
    landslide_pre_event_rainfall[rainfall_feature_cols]
    .corr()
    .round(3)
)

print("Rainfall feature correlation matrix:")

display(rainfall_corr)

Rainfall feature correlation matrix:

,pre_rfh_1dekad,pre_rfh_2dekad_sum,pre_rfh_3dekad_sum,pre_r1h,pre_r3h,pre_rfq,pre_r1q,pre_r3q
pre_rfh_1dekad,1.000,0.848,0.762,0.762,0.439,0.786,0.603,0.383
pre_rfh_2dekad_sum,0.848,1.000,0.888,0.888,0.439,0.554,0.670,0.363
pre_rfh_3dekad_sum,0.762,0.888,1.000,1.000,0.513,0.473,0.782,0.410
pre_r1h,0.762,0.888,1.000,1.000,0.513,0.473,0.782,0.410
pre_r3h,0.439,0.439,0.513,0.513,1.000,0.304,0.299,0.728
pre_rfq,0.786,0.554,0.473,0.473,0.304,1.000,0.681,0.429
pre_r1q,0.603,0.670,0.782,0.782,0.299,0.681,1.000,0.502
pre_r3q,0.383,0.363,0.410,0.410,0.728,0.429,0.502,1.000

In [259]:
# ---------------------------------------------------------
# Step 6A — Inspect Census DS names relevant to landslides
# ---------------------------------------------------------

landslide_ds_names = [
    "Ambagamuwa",
    "Kothmale",
    "Nuwara Eliya",
    "Walapane",
    "Hanguranketha"
]

print("Census DS names containing relevant terms:\n")

census_relevant = census_ds[
    census_ds["ds_name"]
    .astype("string")
    .str.contains(
        "Ambag|Koth|Nuwara|Walap|Hangur",
        case=False,
        na=False
    )
].copy()

print(
    census_relevant["ds_name"]
    .value_counts()
    .sort_index()
)

Census DS names containing relevant terms:

KeyError: 'ds_name'

In [260]:
print("census_ds shape:", census_ds.shape)

print("\nCensus DS columns:")
for i, col in enumerate(census_ds.columns):
    print(i, repr(col))

census_ds shape: (340, 64)

Census DS columns:
0 'district_name'
1 'ds_name_join'
2 'ds_code'
3 'total_population'
4 'male'
5 'female'
6 'age_total'
7 'age_0_14'
8 'age_15_59'
9 'age_60_64'
10 'age_65_plus'
11 'elderly_60_plus'
12 'occupied_housing_units'
13 'number_of_households'
14 'water_protected_well'
15 'water_semi_protected_well'
16 'water_unprotected_well'
17 'water_tube_well'
18 'water_spring_fountain'
19 'water_national_water_supply'
20 'water_local_authority'
21 'water_community_organization'
22 'water_private_supply'
23 'water_tank_river_stream'
24 'water_rain_water'
25 'water_bottled'
26 'water_filter_ro_plant'
27 'water_bowser'
28 'water_other'
29 'cooking_firewood'
30 'cooking_kerosene'
31 'cooking_gas'
32 'cooking_electricity'
33 'cooking_sawdust_paddy_husk'
34 'cooking_biogas'
35 'cooking_other'
36 'cooking_not_relevant'
37 'lighting_national_grid_hydro'
38 'lighting_kerosene_lamp'
39 'lighting_solar_grid'
40 'lighting_solar_standalone'
41 'lighting_biogas'
42 'lighting_generator'
43 'lighting_other'
44 'toilet_within_unit_exclusive'
45 'toilet_within_unit_shared'
46 'toilet_within_premises_exclusive'
47 'toilet_within_premises_shared'
48 'toilet_no_toilet_shared_elsewhere'
49 'toilet_common_public'
50 'toilet_no_toilet'
51 'children_0_14_ratio'
52 'elderly_60_plus_ratio'
53 'female_ratio'
54 'households_per_1000_population'
55 'housing_units_per_1000_population'
56 'unprotected_well_households'
57 'river_stream_water_households'
58 'no_toilet_households'
59 'public_toilet_households'
60 'unprotected_well_ratio'
61 'river_stream_water_ratio'
62 'no_toilet_ratio'
63 'public_toilet_ratio'

In [261]:
# ---------------------------------------------------------
# Step 6B — Inspect Census DS names for landslide areas
# ---------------------------------------------------------

census_relevant = census_ds[
    census_ds["ds_name_join"]
    .astype("string")
    .str.contains(
        "Ambag|Koth|Nuwara|Walap|Hangur",
        case=False,
        na=False
    )
].copy()

print("Relevant Census DS names:\n")

display(
    census_relevant[
        [
            "district_name",
            "ds_name_join",
            "ds_code",
            "total_population"
        ]
    ]
    .sort_values(["district_name", "ds_name_join"])
    .reset_index(drop=True)
)

Relevant Census DS names:

   district_name               ds_name_join  ds_code  total_population
0   Anuradhapura  Nuwaragam Palatha Central       15             71529
1   Anuradhapura     Nuwaragam Palatha East       33             76138
2       Kalutara              Palindanuwara       36             51171
3          Kandy                  Udunuwara       39            121018
4          Kandy                 Yatinuwara       36            112642
5     Kurunegala        Panduwasnuwara East       48             31790
6     Kurunegala        Panduwasnuwara West       45             71186
7         Matara                 Devinuwara       45             49274
8   Nuwara Eliya        Ambagamuwa Koralaya       15             42538
9   Nuwara Eliya              Hanguranketha        6             58931
10  Nuwara Eliya              Kothmale East        3             61742
11  Nuwara Eliya              Kothmale West        2             41955
12  Nuwara Eliya               Nuwara Eliya       12             88332
13  Nuwara Eliya                   Walapane        9             65287

In [ ]:
# ---------------------------------------------------------
# Step 6C — Create Census features for the 5 landslide DS
# ---------------------------------------------------------

# Exact mapping from Census DS names
landslide_census_mapping = {
    "Ambagamuwa Koralaya": "Ambagamuwa",
    "Hanguranketha": "Hanguranketha",
    "Kothmale East": "Kothmale",
    "Kothmale West": "Kothmale",
    "Nuwara Eliya": "Nuwara Eliya",
    "Walapane": "Walapane"
}

# Select only Nuwara Eliya Census records relevant to
# the landslide study area
landslide_census = census_ds[
    (census_ds["district_name"] == "Nuwara Eliya") &
    (census_ds["ds_name_join"].isin(landslide_census_mapping.keys()))
].copy()

# Create the harmonized landslide DS name
landslide_census["landslide_ds"] = (
    landslide_census["ds_name_join"]
    .map(landslide_census_mapping)
)

print("Source Census rows:", len(landslide_census))

print("\nMapping:")
display(
    landslide_census[
        [
            "ds_name_join",
            "landslide_ds",
            "ds_code",
            "total_population"
        ]
    ]
    .sort_values("landslide_ds")
    .reset_index(drop=True)
)

In [263]:
# ---------------------------------------------------------
# Step 6D — Aggregate Census data to the 5 landslide DS
# ---------------------------------------------------------

# Columns that represent counts and should be summed
count_columns = [
    "total_population",
    "male",
    "female",
    "age_total",
    "age_0_14",
    "age_15_59",
    "age_60_64",
    "age_65_plus",
    "elderly_60_plus",
    "occupied_housing_units",
    "number_of_households",
    "water_protected_well",
    "water_semi_protected_well",
    "water_unprotected_well",
    "water_tube_well",
    "water_spring_fountain",
    "water_national_water_supply",
    "water_local_authority",
    "water_community_organization",
    "water_private_supply",
    "water_tank_river_stream",
    "water_rain_water",
    "water_bottled",
    "water_filter_ro_plant",
    "water_bowser",
    "water_other",
    "cooking_firewood",
    "cooking_kerosene",
    "cooking_gas",
    "cooking_electricity",
    "cooking_sawdust_paddy_husk",
    "cooking_biogas",
    "cooking_other",
    "cooking_not_relevant",
    "lighting_national_grid_hydro",
    "lighting_kerosene_lamp",
    "lighting_solar_grid",
    "lighting_solar_standalone",
    "lighting_biogas",
    "lighting_generator",
    "lighting_other",
    "toilet_within_unit_exclusive",
    "toilet_within_unit_shared",
    "toilet_within_premises_exclusive",
    "toilet_within_premises_shared",
    "toilet_no_toilet_shared_elsewhere",
    "toilet_common_public",
    "toilet_no_toilet"
]

# Aggregate the count variables
landslide_census_ds = (
    landslide_census
    .groupby("landslide_ds", as_index=False)[count_columns]
    .sum()
)

# ---------------------------------------------------------
# Recalculate ratios from aggregated counts
# ---------------------------------------------------------

landslide_census_ds["children_0_14_ratio"] = (
    landslide_census_ds["age_0_14"]
    / landslide_census_ds["total_population"]
)

landslide_census_ds["elderly_60_plus_ratio"] = (
    landslide_census_ds["elderly_60_plus"]
    / landslide_census_ds["total_population"]
)

landslide_census_ds["female_ratio"] = (
    landslide_census_ds["female"]
    / landslide_census_ds["total_population"]
)

landslide_census_ds["households_per_1000_population"] = (
    landslide_census_ds["number_of_households"]
    / landslide_census_ds["total_population"]
    * 1000
)

landslide_census_ds["housing_units_per_1000_population"] = (
    landslide_census_ds["occupied_housing_units"]
    / landslide_census_ds["total_population"]
    * 1000
)

# ---------------------------------------------------------
# Vulnerability-related household indicators
# ---------------------------------------------------------

landslide_census_ds["unprotected_well_households"] = (
    landslide_census_ds["water_unprotected_well"]
)

landslide_census_ds["river_stream_water_households"] = (
    landslide_census_ds["water_tank_river_stream"]
)

landslide_census_ds["no_toilet_households"] = (
    landslide_census_ds["toilet_no_toilet"]
)

landslide_census_ds["public_toilet_households"] = (
    landslide_census_ds["toilet_common_public"]
)

landslide_census_ds["unprotected_well_ratio"] = (
    landslide_census_ds["unprotected_well_households"]
    / landslide_census_ds["number_of_households"]
)

landslide_census_ds["river_stream_water_ratio"] = (
    landslide_census_ds["river_stream_water_households"]
    / landslide_census_ds["number_of_households"]
)

landslide_census_ds["no_toilet_ratio"] = (
    landslide_census_ds["no_toilet_households"]
    / landslide_census_ds["number_of_households"]
)

landslide_census_ds["public_toilet_ratio"] = (
    landslide_census_ds["public_toilet_households"]
    / landslide_census_ds["number_of_households"]
)

print("Final landslide Census DS shape:")
print(landslide_census_ds.shape)

print("\nDS profiles:")
display(
    landslide_census_ds[
        [
            "landslide_ds",
            "total_population",
            "number_of_households",
            "children_0_14_ratio",
            "elderly_60_plus_ratio",
            "female_ratio",
            "unprotected_well_ratio",
            "river_stream_water_ratio",
            "no_toilet_ratio",
            "public_toilet_ratio"
        ]
    ]
    .sort_values("landslide_ds")
    .reset_index(drop=True)
)

Final landslide Census DS shape:
(5, 62)

DS profiles:

,landslide_ds,total_population,number_of_households,children_0_14_ratio,elderly_60_plus_ratio,female_ratio,unprotected_well_ratio,river_stream_water_ratio,no_toilet_ratio,public_toilet_ratio
0,Ambagamuwa,42538,12791,0.206404,0.203982,0.530255,0.017043,0.014229,0.002111,0.000704
1,Hanguranketha,58931,16950,0.221208,0.196060,0.523392,0.019646,0.007198,0.000944,0.006431
2,Kothmale,103697,29105,0.238242,0.182252,0.521847,0.010445,0.081258,0.003539,0.001718
3,Nuwara Eliya,88332,23014,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561
4,Walapane,65287,18241,0.226998,0.177631,0.514666,0.019188,0.034812,0.003673,0.002577

In [264]:
# ---------------------------------------------------------
# Step 6E — Load QGIS DS spatial features
# ---------------------------------------------------------

from pathlib import Path
import pandas as pd

qgis_path = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/ds79_feature_matrix.csv"
)

qgis_ds = pd.read_csv(qgis_path)

print("QGIS feature matrix shape:", qgis_ds.shape)

print("\nNuwara Eliya DS records:")

nuwara_qgis = qgis_ds[
    qgis_ds["adm2_name"].astype("string").str.strip() == "Nuwara Eliya"
].copy()

display(
    nuwara_qgis[
        [
            "adm3_name",
            "adm3_pcode",
            "area_sqkm",
            "center_lat",
            "center_lon",
            "total_road_m",
            "road_density",
            "facility_count",
            "facility_density",
            "Hub distance_HubDist"
        ]
    ]
    .sort_values("adm3_name")
    .reset_index(drop=True)
)

QGIS feature matrix shape: (79, 38)

Nuwara Eliya DS records:

,adm3_name,adm3_pcode,area_sqkm,center_lat,center_lon,total_road_m,road_density,facility_count,facility_density,Hub distance_HubDist
0,Ambagamuwa Korale,LK2315,135.588779,6.951382,80.474234,2.306588e+05,1.701164,13,0.095878,2.676577
1,Hanguranketa,LK2306,132.879199,7.174685,80.791419,3.349047e+05,2.520369,20,0.150513,1.144401
2,Kothmale East,LK2303,140.002626,7.037375,80.698200,3.402754e+05,2.430493,20,0.142854,1.168827
3,Kothmale West,LK2321,86.792177,7.028795,80.612003,2.915136e+05,3.358754,22,0.253479,0.608556
4,Mathurata,LK2318,92.839830,7.088705,80.788718,1.708429e+05,1.840190,19,0.204654,1.584085
5,Nildandahinna,LK2309,171.235573,7.088632,80.913975,3.244131e+05,1.894543,34,0.198557,2.003037
6,Norwood,LK2330,351.246024,6.856014,80.578133,1.027532e+06,2.925391,103,0.293242,1.502653
7,Nuwara Eliya,LK2312,222.063358,6.897998,80.778032,6.488606e+05,2.921962,69,0.310722,0.298231
8,Thalawakele,LK2327,260.521170,6.889229,80.705843,8.251515e+05,3.167311,45,0.172731,0.632770
9,Walapane,LK2324,151.646099,7.088056,80.834132,3.427857e+05,2.260432,28,0.184640,0.944611

In [265]:
# ---------------------------------------------------------
# Step 6F — Aggregate QGIS spatial features
# ---------------------------------------------------------

# Exact QGIS → harmonized landslide DS mapping
qgis_landslide_mapping = {
    "Ambagamuwa Korale": "Ambagamuwa",
    "Hanguranketa": "Hanguranketha",
    "Kothmale East": "Kothmale",
    "Kothmale West": "Kothmale",
    "Nuwara Eliya": "Nuwara Eliya",
    "Walapane": "Walapane"
}

# Select only the QGIS records relevant to the landslide study
landslide_qgis = nuwara_qgis[
    nuwara_qgis["adm3_name"].isin(qgis_landslide_mapping.keys())
].copy()

# Create harmonized DS name
landslide_qgis["landslide_ds"] = (
    landslide_qgis["adm3_name"]
    .map(qgis_landslide_mapping)
)

# ---------------------------------------------------------
# Aggregate spatial count/extent variables
# ---------------------------------------------------------

landslide_qgis_ds = (
    landslide_qgis
    .groupby("landslide_ds", as_index=False)
    .agg(
        area_sqkm=("area_sqkm", "sum"),
        total_road_m=("total_road_m", "sum"),
        facility_count=("facility_count", "sum")
    )
)

# ---------------------------------------------------------
# Recalculate densities
# ---------------------------------------------------------

landslide_qgis_ds["road_density"] = (
    landslide_qgis_ds["total_road_m"]
    / landslide_qgis_ds["area_sqkm"]
)

landslide_qgis_ds["facility_density"] = (
    landslide_qgis_ds["facility_count"]
    / landslide_qgis_ds["area_sqkm"]
)

# ---------------------------------------------------------
# Calculate area-weighted geographic centre
# ---------------------------------------------------------

landslide_qgis["area_weight"] = landslide_qgis["area_sqkm"]

centres = []

for ds_name, group in landslide_qgis.groupby("landslide_ds"):

    total_area = group["area_sqkm"].sum()

    weighted_lat = (
        (group["center_lat"] * group["area_sqkm"]).sum()
        / total_area
    )

    weighted_lon = (
        (group["center_lon"] * group["area_sqkm"]).sum()
        / total_area
    )

    centres.append({
        "landslide_ds": ds_name,
        "center_lat": weighted_lat,
        "center_lon": weighted_lon
    })

landslide_centres = pd.DataFrame(centres)

# Combine spatial features with weighted centres
landslide_qgis_ds = landslide_qgis_ds.merge(
    landslide_centres,
    on="landslide_ds",
    how="left"
)

# ---------------------------------------------------------
# Validation
# ---------------------------------------------------------

print("Final spatial DS shape:", landslide_qgis_ds.shape)

print("\nSpatial DS profiles:")

display(
    landslide_qgis_ds
    .sort_values("landslide_ds")
    .reset_index(drop=True)
)

Final spatial DS shape: (5, 8)

Spatial DS profiles:

,landslide_ds,area_sqkm,total_road_m,facility_count,road_density,facility_density,center_lat,center_lon
0,Ambagamuwa,135.588779,230658.795399,13,1701.164339,0.095878,6.951382,80.474234
1,Hanguranketha,132.879199,334904.676391,20,2520.369462,0.150513,7.174685,80.791419
2,Kothmale,226.794803,631789.029090,42,2785.729746,0.185189,7.034091,80.665214
3,Nuwara Eliya,222.063358,648860.608251,69,2921.961615,0.310722,6.897998,80.778032
4,Walapane,151.646099,342785.713095,28,2260.432114,0.184640,7.088056,80.834132

In [266]:
# ---------------------------------------------------------
# Step 6G — Combine Census + QGIS DS features
# ---------------------------------------------------------

landslide_ds_features = landslide_census_ds.merge(
    landslide_qgis_ds,
    on="landslide_ds",
    how="inner",
    validate="one_to_one"
)

print("Combined DS feature table shape:")
print(landslide_ds_features.shape)

print("\nDS names:")
print(
    landslide_ds_features["landslide_ds"]
    .sort_values()
    .tolist()
)

print("\nMissing values:")
display(
    landslide_ds_features.isna().sum()
    .sort_values(ascending=False)
    .head(20)
)

print("\nSelected exposure/vulnerability/spatial features:")
display(
    landslide_ds_features[
        [
            "landslide_ds",
            "total_population",
            "number_of_households",
            "children_0_14_ratio",
            "elderly_60_plus_ratio",
            "female_ratio",
            "unprotected_well_ratio",
            "river_stream_water_ratio",
            "no_toilet_ratio",
            "public_toilet_ratio",
            "area_sqkm",
            "total_road_m",
            "road_density",
            "facility_count",
            "facility_density",
            "center_lat",
            "center_lon"
        ]
    ]
    .sort_values("landslide_ds")
    .reset_index(drop=True)
)

Combined DS feature table shape:
(5, 69)

DS names:
['Ambagamuwa', 'Hanguranketha', 'Kothmale', 'Nuwara Eliya', 'Walapane']

Missing values:

landslide_ds                         0
toilet_within_premises_exclusive     0
elderly_60_plus_ratio                0
children_0_14_ratio                  0
toilet_no_toilet                     0
toilet_common_public                 0
toilet_no_toilet_shared_elsewhere    0
toilet_within_premises_shared        0
toilet_within_unit_shared            0
lighting_national_grid_hydro         0
toilet_within_unit_exclusive         0
lighting_other                       0
lighting_generator                   0
lighting_biogas                      0
lighting_solar_standalone            0
lighting_solar_grid                  0
female_ratio                         0
households_per_1000_population       0
housing_units_per_1000_population    0
unprotected_well_households          0
dtype: int64

Selected exposure/vulnerability/spatial features:

,landslide_ds,total_population,number_of_households,children_0_14_ratio,elderly_60_plus_ratio,female_ratio,unprotected_well_ratio,river_stream_water_ratio,no_toilet_ratio,public_toilet_ratio,area_sqkm,total_road_m,road_density,facility_count,facility_density,center_lat,center_lon
0,Ambagamuwa,42538,12791,0.206404,0.203982,0.530255,0.017043,0.014229,0.002111,0.000704,135.588779,230658.795399,1701.164339,13,0.095878,6.951382,80.474234
1,Hanguranketha,58931,16950,0.221208,0.196060,0.523392,0.019646,0.007198,0.000944,0.006431,132.879199,334904.676391,2520.369462,20,0.150513,7.174685,80.791419
2,Kothmale,103697,29105,0.238242,0.182252,0.521847,0.010445,0.081258,0.003539,0.001718,226.794803,631789.029090,2785.729746,42,0.185189,7.034091,80.665214
3,Nuwara Eliya,88332,23014,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,648860.608251,2921.961615,69,0.310722,6.897998,80.778032
4,Walapane,65287,18241,0.226998,0.177631,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,342785.713095,2260.432114,28,0.184640,7.088056,80.834132

In [267]:
# ---------------------------------------------------------
# Step 7A — Inspect raw landslide DS names
# ---------------------------------------------------------

print("Raw DS names in landslide event data:\n")

display(
    landslide_events["division"]
    .value_counts(dropna=False)
    .rename_axis("raw_division")
    .reset_index(name="record_count")
)

Raw DS names in landslide event data:

       raw_division  record_count
0      Nuwara Eliya            55
1  Ambagamuwakorale            15
2          Kothmale            14
3          Walapane            13
4     Hanguranketha             3

In [268]:
# ---------------------------------------------------------
# Step 7B — Create Event × DS observations
# ---------------------------------------------------------

landslide_event_ds = landslide_events.copy()

# Harmonize historical DS names
landslide_event_ds["landslide_ds"] = (
    landslide_event_ds["division"]
    .replace({
        "Ambagamuwakorale": "Ambagamuwa",
        "Kothmale": "Kothmale",
        "Nuwara Eliya": "Nuwara Eliya",
        "Walapane": "Walapane",
        "Hanguranketha": "Hanguranketha"
    })
)

# Check that every historical record mapped correctly
print("Unmapped DS records:")
print(
    landslide_event_ds[
        ~landslide_event_ds["landslide_ds"].isin(
            landslide_ds_features["landslide_ds"]
        )
    ]["division"]
    .value_counts()
)

# Create event × DS observations
landslide_event_ds_summary = (
    landslide_event_ds
    .groupby(
        ["episode_id", "landslide_ds"],
        as_index=False
    )
    .agg(
        start_date=("date", "min"),
        end_date=("date", "max"),
        incident_count=("serial", "count"),

        deaths=("deaths", "sum"),
        injured=("injured", "sum"),
        missing=("missing", "sum"),
        houses_destroyed=("houses_destroyed", "sum"),
        houses_damaged=("houses_damaged", "sum"),
        indirectly_affected=("indirectly_affected", "sum"),
        evacuated=("evacuated", "sum"),

        target_records=("indirectly_affected", "count")
    )
)

landslide_event_ds_summary["duration_days"] = (
    landslide_event_ds_summary["end_date"]
    - landslide_event_ds_summary["start_date"]
).dt.days + 1

print("\nEvent × DS shape:")
print(landslide_event_ds_summary.shape)

print("\nNumber of unique episodes:")
print(landslide_event_ds_summary["episode_id"].nunique())

print("\nNumber of unique DS divisions:")
print(landslide_event_ds_summary["landslide_ds"].nunique())

print("\nEvent × DS records by DS:")
display(
    landslide_event_ds_summary["landslide_ds"]
    .value_counts()
    .rename_axis("landslide_ds")
    .reset_index(name="event_ds_count")
)

print("\nFirst records:")
display(
    landslide_event_ds_summary
    .sort_values(["start_date", "landslide_ds"])
    .head(15)
)

Unmapped DS records:
Series([], Name: count, dtype: Int64)

Event × DS shape:
(77, 14)

Number of unique episodes:
62

Number of unique DS divisions:
5

Event × DS records by DS:

    landslide_ds  event_ds_count
0   Nuwara Eliya              42
1     Ambagamuwa              13
2       Kothmale              12
3       Walapane               7
4  Hanguranketha               3

First records:

,episode_id,landslide_ds,start_date,end_date,incident_count,deaths,injured,missing,houses_destroyed,houses_damaged,indirectly_affected,evacuated,target_records,duration_days
0,NE_LS_EP001,Nuwara Eliya,2003-05-17,2003-05-18,3,0.0,0.0,0.0,0.0,0.0,505.0,0.0,3,2
1,NE_LS_EP002,Walapane,2006-01-14,2006-01-14,1,0.0,0.0,0.0,0.0,0.0,10365.0,0.0,1,1
2,NE_LS_EP003,Ambagamuwa,2006-04-01,2006-04-01,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
3,NE_LS_EP004,Ambagamuwa,2006-11-15,2006-11-15,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
4,NE_LS_EP005,Nuwara Eliya,2007-01-11,2007-01-11,1,0.0,0.0,0.0,0.0,1.0,5.0,0.0,1,1
5,NE_LS_EP005,Walapane,2007-01-13,2007-01-15,7,0.0,0.0,0.0,8.0,42.0,1195.0,0.0,7,3
6,NE_LS_EP006,Walapane,2007-02-01,2007-02-01,1,0.0,0.0,0.0,0.0,15.0,360.0,0.0,1,1
7,NE_LS_EP007,Walapane,2007-05-09,2007-05-09,1,0.0,0.0,0.0,0.0,0.0,1343.0,0.0,1,1
8,NE_LS_EP008,Walapane,2007-10-12,2007-10-12,1,0.0,0.0,0.0,0.0,0.0,1180.0,0.0,1,1
9,NE_LS_EP009,Nuwara Eliya,2008-03-13,2008-03-13,1,0.0,0.0,0.0,0.0,1.0,6.0,0.0,1,1
10,NE_LS_EP010,Ambagamuwa,2008-06-01,2008-06-01,2,0.0,0.0,0.0,1.0,6.0,83.0,0.0,2,1
11,NE_LS_EP010,Nuwara Eliya,2008-06-02,2008-06-02,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0,1
12,NE_LS_EP011,Nuwara Eliya,2008-11-25,2008-11-25,2,0.0,0.0,0.0,0.0,2.0,18.0,0.0,2,1
13,NE_LS_EP012,Nuwara Eliya,2008-12-08,2008-12-08,1,0.0,0.0,0.0,0.0,3.0,15.0,0.0,1,1
14,NE_LS_EP013,Ambagamuwa,2009-05-20,2009-05-23,2,5.0,0.0,0.0,1.0,4.0,20.0,0.0,1,4

In [269]:
# ---------------------------------------------------------
# Step 7C — Audit human-impact target completeness
# ---------------------------------------------------------

target_audit = (
    landslide_event_ds_summary
    .assign(
        target_missing=lambda df:
            df["target_records"] == 0
    )
)

print("Total event × DS observations:")
print(len(target_audit))

print("\nTarget recorded:")
print(
    (~target_audit["target_missing"]).sum()
)

print("\nTarget missing:")
print(
    target_audit["target_missing"].sum()
)

print("\nTarget completeness percentage:")
print(
    round(
        (~target_audit["target_missing"]).mean() * 100,
        2
    ),
    "%"
)

print("\nTarget status by DS:")
display(
    target_audit
    .groupby("landslide_ds")
    .agg(
        event_ds_count=("episode_id", "count"),
        target_recorded=("target_missing", lambda x: (~x).sum()),
        target_missing=("target_missing", "sum")
    )
    .reset_index()
)

print("\nObservations with missing target:")
display(
    target_audit[
        target_audit["target_missing"]
    ][
        [
            "episode_id",
            "landslide_ds",
            "start_date",
            "end_date",
            "incident_count",
            "deaths",
            "houses_destroyed",
            "houses_damaged",
            "indirectly_affected",
            "target_records"
        ]
    ]
    .sort_values(["start_date", "landslide_ds"])
    .reset_index(drop=True)
)

Total event × DS observations:
77

Target recorded:
73

Target missing:
4

Target completeness percentage:
94.81 %

Target status by DS:

    landslide_ds  event_ds_count  target_recorded  target_missing
0     Ambagamuwa              13               11               2
1  Hanguranketha               3                2               1
2       Kothmale              12               12               0
3   Nuwara Eliya              42               41               1
4       Walapane               7                7               0

Observations with missing target:

,episode_id,landslide_ds,start_date,end_date,incident_count,deaths,houses_destroyed,houses_damaged,indirectly_affected,target_records
0,NE_LS_EP003,Ambagamuwa,2006-04-01,2006-04-01,1,1.0,0.0,0.0,0.0,0
1,NE_LS_EP004,Ambagamuwa,2006-11-15,2006-11-15,1,1.0,0.0,0.0,0.0,0
2,NE_LS_EP010,Nuwara Eliya,2008-06-02,2008-06-02,1,1.0,1.0,0.0,0.0,0
3,NE_LS_EP014,Hanguranketha,2009-06-11,2009-06-11,1,0.0,0.0,1.0,0.0,0

In [270]:
# ---------------------------------------------------------
# Step 7D — Prepare clean landslide target
# ---------------------------------------------------------

landslide_target = landslide_event_ds_summary.copy()

# Target completeness flag
landslide_target["target_complete"] = (
    landslide_target["target_records"] > 0
)

# Keep the original target untouched
landslide_target["human_impact_count"] = (
    landslide_target["indirectly_affected"]
)

# Separate model-usable observations
landslide_target_model = landslide_target[
    landslide_target["target_complete"]
].copy()

print("Full event × DS dataset:")
print(landslide_target.shape)

print("\nTarget-complete observations:")
print(landslide_target_model.shape)

print("\nTarget-incomplete observations:")
print(
    (~landslide_target["target_complete"]).sum()
)

print("\nHuman-impact target statistics:")
display(
    landslide_target_model[
        "human_impact_count"
    ].describe()
)

print("\nSorted human-impact values:")
display(
    landslide_target_model[
        [
            "episode_id",
            "landslide_ds",
            "start_date",
            "incident_count",
            "human_impact_count"
        ]
    ]
    .sort_values(
        "human_impact_count",
        ascending=False
    )
    .reset_index(drop=True)
)

Full event × DS dataset:
(77, 16)

Target-complete observations:
(73, 16)

Target-incomplete observations:
4

Human-impact target statistics:

count       73.000000
mean       249.219178
std       1227.561192
min          3.000000
25%          6.000000
50%         18.000000
75%         75.000000
max      10365.000000
Name: human_impact_count, dtype: float64

Sorted human-impact values:

     episode_id   landslide_ds start_date  incident_count  human_impact_count
0   NE_LS_EP002       Walapane 2006-01-14               1             10365.0
1   NE_LS_EP007       Walapane 2007-05-09               1              1343.0
2   NE_LS_EP005       Walapane 2007-01-13               7              1195.0
3   NE_LS_EP008       Walapane 2007-10-12               1              1180.0
4   NE_LS_EP001   Nuwara Eliya 2003-05-17               3               505.0
..          ...            ...        ...             ...                 ...
68  NE_LS_EP035       Kothmale 2014-07-02               1                 4.0
69  NE_LS_EP029  Hanguranketha 2013-06-24               1                 4.0
70  NE_LS_EP028   Nuwara Eliya 2013-06-05               1                 4.0
71  NE_LS_EP044   Nuwara Eliya 2015-07-20               1                 3.0
72  NE_LS_EP032       Kothmale 2014-04-30               1                 3.0

[73 rows x 5 columns]

In [271]:
# ---------------------------------------------------------
# Step 7E — Inspect human-impact target distribution
# ---------------------------------------------------------

target_values = (
    landslide_target_model["human_impact_count"]
    .sort_values()
    .reset_index(drop=True)
)

# Calculate useful empirical percentiles
target_percentiles = (
    landslide_target_model["human_impact_count"]
    .quantile(
        [0, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 1.00]
    )
    .rename("human_impact_count")
    .reset_index()
    .rename(columns={"index": "percentile"})
)

print("Empirical target percentiles:")
display(target_percentiles)

print("\nTarget value frequency groups:")

target_frequency = (
    landslide_target_model
    .groupby("human_impact_count")
    .size()
    .reset_index(name="observation_count")
    .sort_values(
        "human_impact_count",
        ascending=False
    )
)

display(target_frequency.head(20))

print("\nNumber of observations by broad impact range:")

impact_ranges = pd.cut(
    landslide_target_model["human_impact_count"],
    bins=[-1, 10, 50, 100, 500, 1000, float("inf")],
    labels=[
        "0–10",
        "11–50",
        "51–100",
        "101–500",
        "501–1000",
        "1001+"
    ]
)

display(
    impact_ranges
    .value_counts(sort=False)
    .rename_axis("impact_range")
    .reset_index(name="observation_count")
)

Empirical target percentiles:

   percentile  human_impact_count
0        0.00                 3.0
1        0.10                 5.0
2        0.25                 6.0
3        0.50                18.0
4        0.75                75.0
5        0.90               298.4
6        0.95               775.0
7        1.00             10365.0

Target value frequency groups:

    human_impact_count  observation_count
46             10365.0                  1
45              1343.0                  1
44              1195.0                  1
43              1180.0                  1
42               505.0                  1
41               438.0                  1
40               360.0                  1
39               307.0                  1
38               264.0                  1
37               245.0                  1
36               202.0                  1
35               154.0                  1
34               142.0                  1
33               130.0                  1
32               128.0                  1
31               102.0                  1
30                83.0                  1
29                78.0                  1
28                75.0                  1
27                63.0                  1

Number of observations by broad impact range:

  impact_range  observation_count
0         0–10                 27
1        11–50                 25
2       51–100                  5
3      101–500                 11
4     501–1000                  1
5        1001+                  4

In [273]:
# ---------------------------------------------------------
# Step 7F — Provisional 3-class human-impact target
# ---------------------------------------------------------

landslide_target_model = landslide_target_model.copy()

landslide_target_model["impact_class"] = pd.cut(
    landslide_target_model["human_impact_count"],
    bins=[
        -float("inf"),
        18,
        75,
        float("inf")
    ],
    labels=[
        "LOW",
        "MODERATE",
        "HIGH"
    ],
    include_lowest=True
)

print("Provisional class distribution:")
display(
    landslide_target_model["impact_class"]
    .value_counts()
    .sort_index()
    .rename_axis("impact_class")
    .reset_index(name="observation_count")
)

print("\nClass percentages:")
display(
    (
        landslide_target_model["impact_class"]
        .value_counts(normalize=True)
        .sort_index()
        .mul(100)
        .round(2)
        .rename_axis("impact_class")
        .reset_index(name="percentage")
    )
)

print("\nImpact range within each class:")
display(
    landslide_target_model
    .groupby("impact_class", observed=False)["human_impact_count"]
    .agg(
        count="count",
        minimum="min",
        median="median",
        maximum="max"
    )
    .reset_index()
)

Provisional class distribution:

  impact_class  observation_count
0          LOW                 37
1     MODERATE                 18
2         HIGH                 18

Class percentages:

  impact_class  percentage
0          LOW       50.68
1     MODERATE       24.66
2         HIGH       24.66

Impact range within each class:

  impact_class  count  minimum  median  maximum
0          LOW     37      3.0     6.0     18.0
1     MODERATE     18     20.0    34.0     75.0
2         HIGH     18     78.0   254.5  10365.0

In [274]:
# ---------------------------------------------------------
# Step 7G — Check impact classes within historical episodes
# ---------------------------------------------------------

episode_class_check = (
    landslide_target_model
    .groupby("episode_id")
    .agg(
        ds_count=("landslide_ds", "count"),
        ds_list=("landslide_ds", lambda x: ", ".join(sorted(x.unique()))),
        class_count=("impact_class", "nunique"),
        classes=("impact_class", lambda x: ", ".join(sorted(x.astype(str).unique()))),
        min_impact=("human_impact_count", "min"),
        max_impact=("human_impact_count", "max")
    )
    .reset_index()
)

print("Total target-complete episodes:")
print(len(episode_class_check))

print("\nEpisodes involving multiple DS divisions:")
print(
    (episode_class_check["ds_count"] > 1).sum()
)

print("\nEpisodes containing more than one impact class:")
print(
    (episode_class_check["class_count"] > 1).sum()
)

print("\nEpisodes with multiple DS divisions:")
display(
    episode_class_check[
        episode_class_check["ds_count"] > 1
    ]
    .sort_values("episode_id")
)

print("\nEpisodes containing multiple impact classes:")
display(
    episode_class_check[
        episode_class_check["class_count"] > 1
    ]
    .sort_values("episode_id")
)

Total target-complete episodes:
60

Episodes involving multiple DS divisions:
11

Episodes containing more than one impact class:
8

Episodes with multiple DS divisions:

,episode_id,ds_count,ds_list,class_count,classes,min_impact,max_impact
2,NE_LS_EP005,2,"Nuwara Eliya, Walapane",2,"HIGH, LOW",5.0,1195.0
10,NE_LS_EP013,3,"Ambagamuwa, Kothmale, Nuwara Eliya",2,"LOW, MODERATE",10.0,33.0
16,NE_LS_EP019,2,"Ambagamuwa, Nuwara Eliya",1,LOW,5.0,5.0
18,NE_LS_EP021,2,"Kothmale, Nuwara Eliya",1,LOW,5.0,6.0
26,NE_LS_EP029,3,"Hanguranketha, Kothmale, Nuwara Eliya",3,"HIGH, LOW, MODERATE",4.0,202.0
34,NE_LS_EP037,2,"Kothmale, Nuwara Eliya",2,"LOW, MODERATE",5.0,29.0
36,NE_LS_EP039,2,"Nuwara Eliya, Walapane",2,"HIGH, LOW",9.0,438.0
47,NE_LS_EP050,2,"Kothmale, Nuwara Eliya",2,"HIGH, MODERATE",63.0,245.0
53,NE_LS_EP056,2,"Ambagamuwa, Nuwara Eliya",2,"LOW, MODERATE",14.0,23.0
54,NE_LS_EP057,2,"Kothmale, Nuwara Eliya",2,"HIGH, MODERATE",42.0,142.0
57,NE_LS_EP060,2,"Nuwara Eliya, Walapane",1,MODERATE,59.0,75.0

Episodes containing multiple impact classes:

,episode_id,ds_count,ds_list,class_count,classes,min_impact,max_impact
2,NE_LS_EP005,2,"Nuwara Eliya, Walapane",2,"HIGH, LOW",5.0,1195.0
10,NE_LS_EP013,3,"Ambagamuwa, Kothmale, Nuwara Eliya",2,"LOW, MODERATE",10.0,33.0
26,NE_LS_EP029,3,"Hanguranketha, Kothmale, Nuwara Eliya",3,"HIGH, LOW, MODERATE",4.0,202.0
34,NE_LS_EP037,2,"Kothmale, Nuwara Eliya",2,"LOW, MODERATE",5.0,29.0
36,NE_LS_EP039,2,"Nuwara Eliya, Walapane",2,"HIGH, LOW",9.0,438.0
47,NE_LS_EP050,2,"Kothmale, Nuwara Eliya",2,"HIGH, MODERATE",63.0,245.0
53,NE_LS_EP056,2,"Ambagamuwa, Nuwara Eliya",2,"LOW, MODERATE",14.0,23.0
54,NE_LS_EP057,2,"Kothmale, Nuwara Eliya",2,"HIGH, MODERATE",42.0,142.0

In [275]:
# ---------------------------------------------------------
# Step 7H — Merge pre-event rainfall features
# ---------------------------------------------------------

rainfall_features = landslide_pre_event_rainfall[
    [
        "episode_id",
        "pre_rfh_1dekad",
        "pre_rfh_2dekad_sum",
        "pre_r1h",
        "pre_r3h",
        "pre_rfq",
        "pre_r1q",
        "pre_r3q",
        "pre_event_rainfall_date"
    ]
].copy()

landslide_model_base = landslide_target_model.merge(
    rainfall_features,
    on="episode_id",
    how="left",
    validate="many_to_one"
)

print("Dataset shape after rainfall merge:")
print(landslide_model_base.shape)

print("\nMissing rainfall features:")
display(
    landslide_model_base[
        [
            "pre_rfh_1dekad",
            "pre_rfh_2dekad_sum",
            "pre_r1h",
            "pre_r3h",
            "pre_rfq",
            "pre_r1q",
            "pre_r3q"
        ]
    ]
    .isna()
    .sum()
)

print("\nRainfall + target preview:")
display(
    landslide_model_base[
        [
            "episode_id",
            "landslide_ds",
            "start_date",
            "human_impact_count",
            "impact_class",
            "pre_rfh_1dekad",
            "pre_rfh_2dekad_sum",
            "pre_r1h",
            "pre_r3h",
            "pre_rfq",
            "pre_r1q",
            "pre_r3q"
        ]
    ]
    .sort_values(["start_date", "landslide_ds"])
    .head(15)
)

Dataset shape after rainfall merge:
(73, 25)

Missing rainfall features:

pre_rfh_1dekad        0
pre_rfh_2dekad_sum    0
pre_r1h               0
pre_r3h               0
pre_rfq               0
pre_r1q               0
pre_r3q               0
dtype: int64

Rainfall + target preview:

,episode_id,landslide_ds,start_date,human_impact_count,impact_class,pre_rfh_1dekad,pre_rfh_2dekad_sum,pre_r1h,pre_r3h,pre_rfq,pre_r1q,pre_r3q
0,NE_LS_EP001,Nuwara Eliya,2003-05-17,505.0,HIGH,101.017240,222.137930,279.775880,621.81030,120.356240,117.857360,120.289840
1,NE_LS_EP002,Walapane,2006-01-14,10365.0,HIGH,86.224140,121.258620,205.568970,1114.13800,170.106740,99.044130,132.595750
2,NE_LS_EP005,Nuwara Eliya,2007-01-11,5.0,LOW,35.362070,97.189657,270.862060,1223.31040,75.263630,129.755680,145.530530
3,NE_LS_EP005,Walapane,2007-01-13,1195.0,HIGH,35.362070,97.189657,270.862060,1223.31040,75.263630,129.755680,145.530530
4,NE_LS_EP006,Walapane,2007-02-01,360.0,HIGH,46.586210,172.224140,207.586210,947.74133,106.793580,149.413500,135.080370
5,NE_LS_EP007,Walapane,2007-05-09,1343.0,HIGH,99.379310,166.293105,435.293100,536.13794,127.602170,190.406950,112.703340
6,NE_LS_EP008,Walapane,2007-10-12,1180.0,HIGH,58.603447,90.637927,165.448270,707.96560,73.242880,68.260910,117.242350
7,NE_LS_EP009,Nuwara Eliya,2008-03-13,6.0,LOW,144.741380,179.568967,198.775860,588.65515,345.392120,187.317730,132.753280
8,NE_LS_EP010,Ambagamuwa,2008-06-01,83.0,HIGH,71.293106,90.913796,104.724140,1016.67240,98.213290,47.311996,170.426150
9,NE_LS_EP011,Nuwara Eliya,2008-11-25,18.0,LOW,59.120690,95.500000,149.827580,634.01720,58.055252,45.506910,76.781136
10,NE_LS_EP012,Nuwara Eliya,2008-12-08,15.0,LOW,110.913795,170.034485,206.413790,594.15515,100.062515,64.795110,68.145270
11,NE_LS_EP013,Ambagamuwa,2009-05-20,20.0,MODERATE,28.879310,70.810344,110.913795,635.31036,38.461540,47.972088,122.880615
13,NE_LS_EP013,Nuwara Eliya,2009-05-20,33.0,MODERATE,28.879310,70.810344,110.913795,635.31036,38.461540,47.972088,122.880615
12,NE_LS_EP013,Kothmale,2009-05-24,10.0,LOW,28.879310,70.810344,110.913795,635.31036,38.461540,47.972088,122.880615
14,NE_LS_EP014,Nuwara Eliya,2009-06-11,5.0,LOW,42.948277,167.293103,254.086210,804.77594,56.110405,112.998270,126.215805

In [276]:
# ---------------------------------------------------------
# Step 7I — Merge Census + QGIS DS features
# ---------------------------------------------------------

landslide_model_dataset = landslide_model_base.merge(
    landslide_ds_features,
    on="landslide_ds",
    how="left",
    validate="many_to_one"
)

print("Final merged dataset shape:")
print(landslide_model_dataset.shape)

print("\nMissing values after DS feature merge:")

display(
    landslide_model_dataset
    .isna()
    .sum()
    .sort_values(ascending=False)
    .head(25)
)

print("\nDS coverage:")
display(
    landslide_model_dataset[
        "landslide_ds"
    ]
    .value_counts()
    .rename_axis("landslide_ds")
    .reset_index(name="observation_count")
)

print("\nFinal dataset preview:")

display(
    landslide_model_dataset[
        [
            "episode_id",
            "landslide_ds",
            "start_date",
            "human_impact_count",
            "impact_class",

            # Hazard
            "pre_rfh_1dekad",
            "pre_rfh_2dekad_sum",
            "pre_r1h",
            "pre_r3h",
            "pre_rfq",
            "pre_r1q",
            "pre_r3q",

            # Exposure
            "total_population",
            "number_of_households",

            # Demographic sensitivity
            "children_0_14_ratio",
            "elderly_60_plus_ratio",
            "female_ratio",

            # Household sensitivity
            "unprotected_well_ratio",
            "river_stream_water_ratio",
            "no_toilet_ratio",
            "public_toilet_ratio",

            # Spatial / infrastructure
            "area_sqkm",
            "road_density",
            "facility_density"
        ]
    ]
    .sort_values(["start_date", "landslide_ds"])
    .head(15)
)

Final merged dataset shape:
(73, 93)

Missing values after DS feature merge:

episode_id                           0
lighting_national_grid_hydro         0
toilet_within_premises_exclusive     0
toilet_within_unit_shared            0
toilet_within_unit_exclusive         0
lighting_other                       0
lighting_generator                   0
lighting_biogas                      0
lighting_solar_standalone            0
lighting_solar_grid                  0
lighting_kerosene_lamp               0
cooking_not_relevant                 0
water_bottled                        0
cooking_other                        0
cooking_biogas                       0
cooking_sawdust_paddy_husk           0
cooking_electricity                  0
cooking_gas                          0
cooking_kerosene                     0
cooking_firewood                     0
water_other                          0
water_bowser                         0
toilet_within_premises_shared        0
toilet_no_toilet_shared_elsewhere    0
toilet_common_public                 0
dtype: int64

DS coverage:

    landslide_ds  observation_count
0   Nuwara Eliya                 41
1       Kothmale                 12
2     Ambagamuwa                 11
3       Walapane                  7
4  Hanguranketha                  2

Final dataset preview:

,episode_id,landslide_ds,start_date,human_impact_count,impact_class,pre_rfh_1dekad,pre_rfh_2dekad_sum,pre_r1h,pre_r3h,pre_rfq,...,children_0_14_ratio,elderly_60_plus_ratio,female_ratio,unprotected_well_ratio,river_stream_water_ratio,no_toilet_ratio,public_toilet_ratio,area_sqkm,road_density,facility_density
0,NE_LS_EP001,Nuwara Eliya,2003-05-17,505.0,HIGH,101.017240,222.137930,279.775880,621.81030,120.356240,...,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722
1,NE_LS_EP002,Walapane,2006-01-14,10365.0,HIGH,86.224140,121.258620,205.568970,1114.13800,170.106740,...,0.226998,0.177631,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640
2,NE_LS_EP005,Nuwara Eliya,2007-01-11,5.0,LOW,35.362070,97.189657,270.862060,1223.31040,75.263630,...,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722
3,NE_LS_EP005,Walapane,2007-01-13,1195.0,HIGH,35.362070,97.189657,270.862060,1223.31040,75.263630,...,0.226998,0.177631,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640
4,NE_LS_EP006,Walapane,2007-02-01,360.0,HIGH,46.586210,172.224140,207.586210,947.74133,106.793580,...,0.226998,0.177631,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640
5,NE_LS_EP007,Walapane,2007-05-09,1343.0,HIGH,99.379310,166.293105,435.293100,536.13794,127.602170,...,0.226998,0.177631,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640
6,NE_LS_EP008,Walapane,2007-10-12,1180.0,HIGH,58.603447,90.637927,165.448270,707.96560,73.242880,...,0.226998,0.177631,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640
7,NE_LS_EP009,Nuwara Eliya,2008-03-13,6.0,LOW,144.741380,179.568967,198.775860,588.65515,345.392120,...,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722
8,NE_LS_EP010,Ambagamuwa,2008-06-01,83.0,HIGH,71.293106,90.913796,104.724140,1016.67240,98.213290,...,0.206404,0.203982,0.530255,0.017043,0.014229,0.002111,0.000704,135.588779,1701.164339,0.095878
9,NE_LS_EP011,Nuwara Eliya,2008-11-25,18.0,LOW,59.120690,95.500000,149.827580,634.01720,58.055252,...,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722
10,NE_LS_EP012,Nuwara Eliya,2008-12-08,15.0,LOW,110.913795,170.034485,206.413790,594.15515,100.062515,...,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722
11,NE_LS_EP013,Ambagamuwa,2009-05-20,20.0,MODERATE,28.879310,70.810344,110.913795,635.31036,38.461540,...,0.206404,0.203982,0.530255,0.017043,0.014229,0.002111,0.000704,135.588779,1701.164339,0.095878
13,NE_LS_EP013,Nuwara Eliya,2009-05-20,33.0,MODERATE,28.879310,70.810344,110.913795,635.31036,38.461540,...,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722
12,NE_LS_EP013,Kothmale,2009-05-24,10.0,LOW,28.879310,70.810344,110.913795,635.31036,38.461540,...,0.238242,0.182252,0.521847,0.010445,0.081258,0.003539,0.001718,226.794803,2785.729746,0.185189
14,NE_LS_EP014,Nuwara Eliya,2009-06-11,5.0,LOW,42.948277,167.293103,254.086210,804.77594,56.110405,...,0.208022,0.163169,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722

In [277]:
# ---------------------------------------------------------
# Step 7J — Select initial modelling features
# ---------------------------------------------------------

initial_features = [
    # Hazard / rainfall
    "pre_rfh_1dekad",
    "pre_rfh_2dekad_sum",
    "pre_r1h",
    "pre_r3h",
    "pre_rfq",
    "pre_r1q",
    "pre_r3q",

    # Exposure
    "total_population",
    "number_of_households",

    # Demographic sensitivity
    "children_0_14_ratio",
    "elderly_60_plus_ratio",
    "female_ratio",

    # Household sensitivity
    "unprotected_well_ratio",
    "river_stream_water_ratio",
    "no_toilet_ratio",
    "public_toilet_ratio",

    # Spatial / infrastructure
    "area_sqkm",
    "road_density",
    "facility_density"
]

target_columns = [
    "human_impact_count",
    "impact_class"
]

identifier_columns = [
    "episode_id",
    "landslide_ds",
    "start_date",
    "end_date",
    "incident_count",
    "target_complete"
]

landslide_model_features = landslide_model_dataset[
    identifier_columns
    + initial_features
    + target_columns
].copy()

print("Initial modelling dataset shape:")
print(landslide_model_features.shape)

print("\nNumber of predictors:")
print(len(initial_features))

print("\nPredictors:")
for i, feature in enumerate(initial_features, start=1):
    print(f"{i:02d}. {feature}")

print("\nMissing values:")
display(
    landslide_model_features[
        initial_features + target_columns
    ]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print("\nDataset preview:")
display(
    landslide_model_features
    .sort_values(["start_date", "landslide_ds"])
    .head(10)
)

Initial modelling dataset shape:
(73, 27)

Number of predictors:
19

Predictors:
01. pre_rfh_1dekad
02. pre_rfh_2dekad_sum
03. pre_r1h
04. pre_r3h
05. pre_rfq
06. pre_r1q
07. pre_r3q
08. total_population
09. number_of_households
10. children_0_14_ratio
11. elderly_60_plus_ratio
12. female_ratio
13. unprotected_well_ratio
14. river_stream_water_ratio
15. no_toilet_ratio
16. public_toilet_ratio
17. area_sqkm
18. road_density
19. facility_density

Missing values:

pre_rfh_1dekad              0
female_ratio                0
human_impact_count          0
facility_density            0
road_density                0
area_sqkm                   0
public_toilet_ratio         0
no_toilet_ratio             0
river_stream_water_ratio    0
unprotected_well_ratio      0
elderly_60_plus_ratio       0
pre_rfh_2dekad_sum          0
children_0_14_ratio         0
number_of_households        0
total_population            0
pre_r3q                     0
pre_r1q                     0
pre_rfq                     0
pre_r3h                     0
pre_r1h                     0
impact_class                0
dtype: int64

Dataset preview:

,episode_id,landslide_ds,start_date,end_date,incident_count,target_complete,pre_rfh_1dekad,pre_rfh_2dekad_sum,pre_r1h,pre_r3h,...,female_ratio,unprotected_well_ratio,river_stream_water_ratio,no_toilet_ratio,public_toilet_ratio,area_sqkm,road_density,facility_density,human_impact_count,impact_class
0,NE_LS_EP001,Nuwara Eliya,2003-05-17,2003-05-18,3,True,101.017240,222.137930,279.77588,621.81030,...,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722,505.0,HIGH
1,NE_LS_EP002,Walapane,2006-01-14,2006-01-14,1,True,86.224140,121.258620,205.56897,1114.13800,...,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640,10365.0,HIGH
2,NE_LS_EP005,Nuwara Eliya,2007-01-11,2007-01-11,1,True,35.362070,97.189657,270.86206,1223.31040,...,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722,5.0,LOW
3,NE_LS_EP005,Walapane,2007-01-13,2007-01-15,7,True,35.362070,97.189657,270.86206,1223.31040,...,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640,1195.0,HIGH
4,NE_LS_EP006,Walapane,2007-02-01,2007-02-01,1,True,46.586210,172.224140,207.58621,947.74133,...,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640,360.0,HIGH
5,NE_LS_EP007,Walapane,2007-05-09,2007-05-09,1,True,99.379310,166.293105,435.29310,536.13794,...,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640,1343.0,HIGH
6,NE_LS_EP008,Walapane,2007-10-12,2007-10-12,1,True,58.603447,90.637927,165.44827,707.96560,...,0.514666,0.019188,0.034812,0.003673,0.002577,151.646099,2260.432114,0.184640,1180.0,HIGH
7,NE_LS_EP009,Nuwara Eliya,2008-03-13,2008-03-13,1,True,144.741380,179.568967,198.77586,588.65515,...,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722,6.0,LOW
8,NE_LS_EP010,Ambagamuwa,2008-06-01,2008-06-01,2,True,71.293106,90.913796,104.72414,1016.67240,...,0.530255,0.017043,0.014229,0.002111,0.000704,135.588779,1701.164339,0.095878,83.0,HIGH
9,NE_LS_EP011,Nuwara Eliya,2008-11-25,2008-11-25,2,True,59.120690,95.500000,149.82758,634.01720,...,0.510438,0.016338,0.036326,0.001695,0.006561,222.063358,2921.961615,0.310722,18.0,LOW

In [278]:
# ---------------------------------------------------------
# Step 7K — Feature variation and correlation audit
# ---------------------------------------------------------

import numpy as np
import pandas as pd

X_audit = landslide_model_features[initial_features].copy()

# ---------------------------------------------------------
# 1. Number of unique values
# ---------------------------------------------------------

feature_variation = pd.DataFrame({
    "feature": X_audit.columns,
    "unique_values": [
        X_audit[col].nunique()
        for col in X_audit.columns
    ],
    "missing_values": [
        X_audit[col].isna().sum()
        for col in X_audit.columns
    ]
})

feature_variation["variation_type"] = np.where(
    feature_variation["unique_values"] <= 5,
    "Very limited",
    "Variable"
)

print("Feature variation:")
display(
    feature_variation
    .sort_values(["unique_values", "feature"])
    .reset_index(drop=True)
)

# ---------------------------------------------------------
# 2. Correlation matrix
# ---------------------------------------------------------

correlation_matrix = X_audit.corr(method="spearman")

print("\nSpearman correlation matrix:")

display(
    correlation_matrix.round(3)
)

# ---------------------------------------------------------
# 3. Strongly correlated feature pairs
# ---------------------------------------------------------

correlation_pairs = []

for i in range(len(correlation_matrix.columns)):
    for j in range(i + 1, len(correlation_matrix.columns)):

        feature_1 = correlation_matrix.columns[i]
        feature_2 = correlation_matrix.columns[j]

        correlation_value = correlation_matrix.iloc[i, j]

        if abs(correlation_value) >= 0.80:

            correlation_pairs.append({
                "feature_1": feature_1,
                "feature_2": feature_2,
                "spearman_correlation": correlation_value
            })

strong_correlations = (
    pd.DataFrame(correlation_pairs)
    .sort_values(
        "spearman_correlation",
        key=lambda x: x.abs(),
        ascending=False
    )
    if correlation_pairs
    else pd.DataFrame(
        columns=[
            "feature_1",
            "feature_2",
            "spearman_correlation"
        ]
    )
)

print("\nStrong correlation pairs (|ρ| >= 0.80):")

display(strong_correlations)

# ---------------------------------------------------------
# 4. Class distribution
# ---------------------------------------------------------

print("\nImpact-class distribution:")

display(
    landslide_model_features["impact_class"]
    .value_counts()
    .rename_axis("impact_class")
    .reset_index(name="count")
)

Feature variation:

                     feature  unique_values  missing_values variation_type
0                  area_sqkm              5               0   Very limited
1        children_0_14_ratio              5               0   Very limited
2      elderly_60_plus_ratio              5               0   Very limited
3           facility_density              5               0   Very limited
4               female_ratio              5               0   Very limited
5            no_toilet_ratio              5               0   Very limited
6       number_of_households              5               0   Very limited
7        public_toilet_ratio              5               0   Very limited
8   river_stream_water_ratio              5               0   Very limited
9               road_density              5               0   Very limited
10          total_population              5               0   Very limited
11    unprotected_well_ratio              5               0   Very limited
12                   pre_r1h             60               0       Variable
13                   pre_r1q             60               0       Variable
14                   pre_r3h             60               0       Variable
15                   pre_r3q             60               0       Variable
16            pre_rfh_1dekad             60               0       Variable
17        pre_rfh_2dekad_sum             60               0       Variable
18                   pre_rfq             60               0       Variable

Spearman correlation matrix:

,pre_rfh_1dekad,pre_rfh_2dekad_sum,pre_r1h,pre_r3h,pre_rfq,pre_r1q,pre_r3q,total_population,number_of_households,children_0_14_ratio,elderly_60_plus_ratio,female_ratio,unprotected_well_ratio,river_stream_water_ratio,no_toilet_ratio,public_toilet_ratio,area_sqkm,road_density,facility_density
pre_rfh_1dekad,1.000,0.866,0.758,0.407,0.892,0.635,0.363,0.161,0.161,0.167,-0.102,-0.102,-0.119,0.139,-0.109,0.125,0.139,0.132,0.121
pre_rfh_2dekad_sum,0.866,1.000,0.865,0.394,0.725,0.739,0.351,0.175,0.175,0.166,-0.097,-0.097,-0.137,0.149,-0.143,0.128,0.149,0.142,0.127
pre_r1h,0.758,0.865,1.000,0.541,0.611,0.826,0.445,0.123,0.123,0.241,-0.068,-0.068,-0.051,0.098,-0.022,0.089,0.098,0.068,0.061
pre_r3h,0.407,0.394,0.541,1.000,0.357,0.376,0.793,-0.130,-0.130,0.139,0.048,0.048,0.209,-0.150,0.077,-0.024,-0.150,-0.107,-0.109
pre_rfq,0.892,0.725,0.611,0.357,1.000,0.701,0.423,0.151,0.151,0.211,-0.054,-0.054,-0.099,0.127,-0.050,0.076,0.127,0.077,0.067
pre_r1q,0.635,0.739,0.826,0.376,0.701,1.000,0.515,0.143,0.143,0.278,-0.039,-0.039,-0.069,0.123,0.048,0.049,0.123,0.035,0.031
pre_r3q,0.363,0.351,0.445,0.793,0.423,0.515,1.000,-0.105,-0.105,0.130,0.087,0.087,0.164,-0.115,0.146,-0.080,-0.115,-0.141,-0.139
total_population,0.161,0.175,0.123,-0.130,0.151,0.143,-0.105,1.000,1.000,0.650,-0.345,-0.345,-0.962,0.995,-0.025,0.293,0.995,0.504,0.506
number_of_households,0.161,0.175,0.123,-0.130,0.151,0.143,-0.105,1.000,1.000,0.650,-0.345,-0.345,-0.962,0.995,-0.025,0.293,0.995,0.504,0.506
children_0_14_ratio,0.167,0.166,0.241,0.139,0.211,0.278,0.130,0.650,0.650,1.000,0.042,0.042,-0.459,0.611,0.419,-0.057,0.611,-0.014,-0.011
elderly_60_plus_ratio,-0.102,-0.097,-0.068,0.048,-0.054,-0.039,0.087,-0.345,-0.345,0.042,1.000,1.000,0.273,-0.340,0.694,-0.985,-0.340,-0.961,-0.970
female_ratio,-0.102,-0.097,-0.068,0.048,-0.054,-0.039,0.087,-0.345,-0.345,0.042,1.000,1.000,0.273,-0.340,0.694,-0.985,-0.340,-0.961,-0.970
unprotected_well_ratio,-0.119,-0.137,-0.051,0.209,-0.099,-0.069,0.164,-0.962,-0.962,-0.459,0.273,0.273,1.000,-0.974,0.047,-0.210,-0.974,-0.466,-0.468
river_stream_water_ratio,0.139,0.149,0.098,-0.150,0.127,0.123,-0.115,0.995,0.995,0.611,-0.340,-0.340,-0.974,1.000,0.014,0.272,1.000,0.492,0.501
no_toilet_ratio,-0.109,-0.143,-0.022,0.077,-0.050,0.048,0.146,-0.025,-0.025,0.419,0.694,0.694,0.047,0.014,1.000,-0.784,0.014,-0.761,-0.724
public_toilet_ratio,0.125,0.128,0.089,-0.024,0.076,0.049,-0.080,0.293,0.293,-0.057,-0.985,-0.985,-0.210,0.272,-0.784,1.000,0.272,0.957,0.955
area_sqkm,0.139,0.149,0.098,-0.150,0.127,0.123,-0.115,0.995,0.995,0.611,-0.340,-0.340,-0.974,1.000,0.014,0.272,1.000,0.492,0.501
road_density,0.132,0.142,0.068,-0.107,0.077,0.035,-0.141,0.504,0.504,-0.014,-0.961,-0.961,-0.466,0.492,-0.761,0.957,0.492,1.000,0.998
facility_density,0.121,0.127,0.061,-0.109,0.067,0.031,-0.139,0.506,0.506,-0.011,-0.970,-0.970,-0.468,0.501,-0.724,0.955,0.501,0.998,1.000

Strong correlation pairs (|ρ| >= 0.80):

                   feature_1                 feature_2  spearman_correlation
20  river_stream_water_ratio                 area_sqkm              1.000000
4           total_population      number_of_households              1.000000
11     elderly_60_plus_ratio              female_ratio              1.000000
23              road_density          facility_density              0.997613
9       number_of_households  river_stream_water_ratio              0.994581
6           total_population  river_stream_water_ratio              0.994581
7           total_population                 area_sqkm              0.994581
10      number_of_households                 area_sqkm              0.994581
15              female_ratio       public_toilet_ratio             -0.984881
12     elderly_60_plus_ratio       public_toilet_ratio             -0.984881
18    unprotected_well_ratio  river_stream_water_ratio             -0.973741
19    unprotected_well_ratio                 area_sqkm             -0.973741
14     elderly_60_plus_ratio          facility_density             -0.969762
17              female_ratio          facility_density             -0.969762
8       number_of_households    unprotected_well_ratio             -0.962487
5           total_population    unprotected_well_ratio             -0.962487
13     elderly_60_plus_ratio              road_density             -0.961009
16              female_ratio              road_density             -0.961009
21       public_toilet_ratio              road_density              0.957030
22       public_toilet_ratio          facility_density              0.954643
1             pre_rfh_1dekad                   pre_rfq              0.892296
0             pre_rfh_1dekad        pre_rfh_2dekad_sum              0.865632
2         pre_rfh_2dekad_sum                   pre_r1h              0.865107
3                    pre_r1h                   pre_r1q              0.826469

Impact-class distribution:

  impact_class  count
0          LOW     37
1     MODERATE     18
2         HIGH     18

In [279]:
# ---------------------------------------------------------
# Step 7L — Create compact modelling feature set
# ---------------------------------------------------------

core_features = [
    # Hazard
    "pre_rfh_1dekad",
    "pre_r1h",
    "pre_r3h",
    "pre_r1q",

    # Exposure
    "total_population",

    # Demographic sensitivity
    "children_0_14_ratio",
    "elderly_60_plus_ratio",

    # Household sensitivity
    "no_toilet_ratio",

    # Infrastructure
    "road_density",
    "facility_density"
]

landslide_core_dataset = landslide_model_features[
    [
        "episode_id",
        "landslide_ds",
        "start_date",
        "end_date",
        "human_impact_count",
        "impact_class"
    ]
    + core_features
].copy()

print("Core modelling dataset shape:")
print(landslide_core_dataset.shape)

print("\nNumber of predictors:")
print(len(core_features))

print("\nCore predictors:")
for i, feature in enumerate(core_features, start=1):
    print(f"{i:02d}. {feature}")

print("\nMissing values:")
display(
    landslide_core_dataset[
        core_features + ["human_impact_count", "impact_class"]
    ]
    .isna()
    .sum()
)

print("\nCorrelation among core predictors:")

display(
    landslide_core_dataset[
        core_features
    ]
    .corr(method="spearman")
    .round(3)
)

print("\nImpact-class distribution:")

display(
    landslide_core_dataset["impact_class"]
    .value_counts()
    .rename_axis("impact_class")
    .reset_index(name="count")
)

print("\nCore dataset preview:")

display(
    landslide_core_dataset
    .sort_values(["start_date", "landslide_ds"])
    .head(10)
)

Core modelling dataset shape:
(73, 16)

Number of predictors:
10

Core predictors:
01. pre_rfh_1dekad
02. pre_r1h
03. pre_r3h
04. pre_r1q
05. total_population
06. children_0_14_ratio
07. elderly_60_plus_ratio
08. no_toilet_ratio
09. road_density
10. facility_density

Missing values:

pre_rfh_1dekad           0
pre_r1h                  0
pre_r3h                  0
pre_r1q                  0
total_population         0
children_0_14_ratio      0
elderly_60_plus_ratio    0
no_toilet_ratio          0
road_density             0
facility_density         0
human_impact_count       0
impact_class             0
dtype: int64

Correlation among core predictors:

,pre_rfh_1dekad,pre_r1h,pre_r3h,pre_r1q,total_population,children_0_14_ratio,elderly_60_plus_ratio,no_toilet_ratio,road_density,facility_density
pre_rfh_1dekad,1.000,0.758,0.407,0.635,0.161,0.167,-0.102,-0.109,0.132,0.121
pre_r1h,0.758,1.000,0.541,0.826,0.123,0.241,-0.068,-0.022,0.068,0.061
pre_r3h,0.407,0.541,1.000,0.376,-0.130,0.139,0.048,0.077,-0.107,-0.109
pre_r1q,0.635,0.826,0.376,1.000,0.143,0.278,-0.039,0.048,0.035,0.031
total_population,0.161,0.123,-0.130,0.143,1.000,0.650,-0.345,-0.025,0.504,0.506
children_0_14_ratio,0.167,0.241,0.139,0.278,0.650,1.000,0.042,0.419,-0.014,-0.011
elderly_60_plus_ratio,-0.102,-0.068,0.048,-0.039,-0.345,0.042,1.000,0.694,-0.961,-0.970
no_toilet_ratio,-0.109,-0.022,0.077,0.048,-0.025,0.419,0.694,1.000,-0.761,-0.724
road_density,0.132,0.068,-0.107,0.035,0.504,-0.014,-0.961,-0.761,1.000,0.998
facility_density,0.121,0.061,-0.109,0.031,0.506,-0.011,-0.970,-0.724,0.998,1.000

Impact-class distribution:

  impact_class  count
0          LOW     37
1     MODERATE     18
2         HIGH     18

Core dataset preview:

,episode_id,landslide_ds,start_date,end_date,human_impact_count,impact_class,pre_rfh_1dekad,pre_r1h,pre_r3h,pre_r1q,total_population,children_0_14_ratio,elderly_60_plus_ratio,no_toilet_ratio,road_density,facility_density
0,NE_LS_EP001,Nuwara Eliya,2003-05-17,2003-05-18,505.0,HIGH,101.017240,279.77588,621.81030,117.857360,88332,0.208022,0.163169,0.001695,2921.961615,0.310722
1,NE_LS_EP002,Walapane,2006-01-14,2006-01-14,10365.0,HIGH,86.224140,205.56897,1114.13800,99.044130,65287,0.226998,0.177631,0.003673,2260.432114,0.184640
2,NE_LS_EP005,Nuwara Eliya,2007-01-11,2007-01-11,5.0,LOW,35.362070,270.86206,1223.31040,129.755680,88332,0.208022,0.163169,0.001695,2921.961615,0.310722
3,NE_LS_EP005,Walapane,2007-01-13,2007-01-15,1195.0,HIGH,35.362070,270.86206,1223.31040,129.755680,65287,0.226998,0.177631,0.003673,2260.432114,0.184640
4,NE_LS_EP006,Walapane,2007-02-01,2007-02-01,360.0,HIGH,46.586210,207.58621,947.74133,149.413500,65287,0.226998,0.177631,0.003673,2260.432114,0.184640
5,NE_LS_EP007,Walapane,2007-05-09,2007-05-09,1343.0,HIGH,99.379310,435.29310,536.13794,190.406950,65287,0.226998,0.177631,0.003673,2260.432114,0.184640
6,NE_LS_EP008,Walapane,2007-10-12,2007-10-12,1180.0,HIGH,58.603447,165.44827,707.96560,68.260910,65287,0.226998,0.177631,0.003673,2260.432114,0.184640
7,NE_LS_EP009,Nuwara Eliya,2008-03-13,2008-03-13,6.0,LOW,144.741380,198.77586,588.65515,187.317730,88332,0.208022,0.163169,0.001695,2921.961615,0.310722
8,NE_LS_EP010,Ambagamuwa,2008-06-01,2008-06-01,83.0,HIGH,71.293106,104.72414,1016.67240,47.311996,42538,0.206404,0.203982,0.002111,1701.164339,0.095878
9,NE_LS_EP011,Nuwara Eliya,2008-11-25,2008-11-25,18.0,LOW,59.120690,149.82758,634.01720,45.506910,88332,0.208022,0.163169,0.001695,2921.961615,0.310722

In [280]:
# ---------------------------------------------------------
# Step 7M — Final primary modelling feature set
# ---------------------------------------------------------

final_features = [
    # Hazard
    "pre_rfh_1dekad",
    "pre_r1h",
    "pre_r3h",

    # Rainfall anomaly
    "pre_r1q",

    # Exposure
    "total_population",

    # Demographic sensitivity
    "children_0_14_ratio",
    "elderly_60_plus_ratio",

    # Household sensitivity
    "no_toilet_ratio",

    # Infrastructure / capacity proxy
    "facility_density"
]

landslide_final_dataset = landslide_core_dataset[
    [
        "episode_id",
        "landslide_ds",
        "start_date",
        "end_date",
        "human_impact_count",
        "impact_class"
    ]
    + final_features
].copy()

print("Final primary dataset shape:")
print(landslide_final_dataset.shape)

print("\nNumber of predictors:")
print(len(final_features))

print("\nFinal predictors:")
for i, feature in enumerate(final_features, start=1):
    print(f"{i:02d}. {feature}")

print("\nMissing values:")
display(
    landslide_final_dataset[
        final_features + [
            "human_impact_count",
            "impact_class"
        ]
    ]
    .isna()
    .sum()
)

print("\nFinal feature correlation:")

display(
    landslide_final_dataset[
        final_features
    ]
    .corr(method="spearman")
    .round(3)
)

print("\nImpact-class distribution:")

display(
    landslide_final_dataset["impact_class"]
    .value_counts()
    .rename_axis("impact_class")
    .reset_index(name="count")
)

print("\nUnique episodes:")
print(
    landslide_final_dataset["episode_id"].nunique()
)

print("\nUnique DS divisions:")
print(
    landslide_final_dataset["landslide_ds"].nunique()
)

Final primary dataset shape:
(73, 15)

Number of predictors:
9

Final predictors:
01. pre_rfh_1dekad
02. pre_r1h
03. pre_r3h
04. pre_r1q
05. total_population
06. children_0_14_ratio
07. elderly_60_plus_ratio
08. no_toilet_ratio
09. facility_density

Missing values:

pre_rfh_1dekad           0
pre_r1h                  0
pre_r3h                  0
pre_r1q                  0
total_population         0
children_0_14_ratio      0
elderly_60_plus_ratio    0
no_toilet_ratio          0
facility_density         0
human_impact_count       0
impact_class             0
dtype: int64

Final feature correlation:

,pre_rfh_1dekad,pre_r1h,pre_r3h,pre_r1q,total_population,children_0_14_ratio,elderly_60_plus_ratio,no_toilet_ratio,facility_density
pre_rfh_1dekad,1.000,0.758,0.407,0.635,0.161,0.167,-0.102,-0.109,0.121
pre_r1h,0.758,1.000,0.541,0.826,0.123,0.241,-0.068,-0.022,0.061
pre_r3h,0.407,0.541,1.000,0.376,-0.130,0.139,0.048,0.077,-0.109
pre_r1q,0.635,0.826,0.376,1.000,0.143,0.278,-0.039,0.048,0.031
total_population,0.161,0.123,-0.130,0.143,1.000,0.650,-0.345,-0.025,0.506
children_0_14_ratio,0.167,0.241,0.139,0.278,0.650,1.000,0.042,0.419,-0.011
elderly_60_plus_ratio,-0.102,-0.068,0.048,-0.039,-0.345,0.042,1.000,0.694,-0.970
no_toilet_ratio,-0.109,-0.022,0.077,0.048,-0.025,0.419,0.694,1.000,-0.724
facility_density,0.121,0.061,-0.109,0.031,0.506,-0.011,-0.970,-0.724,1.000

Impact-class distribution:

  impact_class  count
0          LOW     37
1     MODERATE     18
2         HIGH     18

Unique episodes:
60

Unique DS divisions:
5

In [281]:
# ---------------------------------------------------------
# Step 7N — Check grouped stratified cross-validation
# ---------------------------------------------------------

from sklearn.model_selection import StratifiedGroupKFold

X = landslide_final_dataset[final_features].copy()
y = landslide_final_dataset["impact_class"].copy()
groups = landslide_final_dataset["episode_id"].copy()

print("Total observations:", len(X))
print("Unique episodes:", groups.nunique())

print("\nOverall class distribution:")
print(y.value_counts())

# ---------------------------------------------------------
# Create grouped stratified folds
# ---------------------------------------------------------

sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

fold_summary = []

for fold_number, (train_idx, test_idx) in enumerate(
    sgkf.split(X, y, groups),
    start=1
):

    train_groups = set(groups.iloc[train_idx])
    test_groups = set(groups.iloc[test_idx])

    overlap = train_groups.intersection(test_groups)

    train_classes = y.iloc[train_idx].value_counts()
    test_classes = y.iloc[test_idx].value_counts()

    fold_summary.append({
        "fold": fold_number,
        "train_observations": len(train_idx),
        "test_observations": len(test_idx),
        "train_episodes": len(train_groups),
        "test_episodes": len(test_groups),
        "group_overlap": len(overlap),
        "train_low": train_classes.get("LOW", 0),
        "train_moderate": train_classes.get("MODERATE", 0),
        "train_high": train_classes.get("HIGH", 0),
        "test_low": test_classes.get("LOW", 0),
        "test_moderate": test_classes.get("MODERATE", 0),
        "test_high": test_classes.get("HIGH", 0)
    })

fold_summary = pd.DataFrame(fold_summary)

print("\nGrouped cross-validation summary:")
display(fold_summary)

print("\nMaximum group overlap across folds:")
print(fold_summary["group_overlap"].max())

Total observations: 73
Unique episodes: 60

Overall class distribution:
impact_class
LOW         37
MODERATE    18
HIGH        18
Name: count, dtype: int64

Grouped cross-validation summary:

,fold,train_observations,test_observations,train_episodes,test_episodes,group_overlap,train_low,train_moderate,train_high,test_low,test_moderate,test_high
0,1,58,15,47,13,0,28,15,15,9,3,3
1,2,58,15,47,13,0,29,13,16,8,5,2
2,3,57,16,48,12,0,33,12,12,4,6,6
3,4,60,13,51,9,0,30,15,15,7,3,3
4,5,59,14,47,13,0,28,17,14,9,1,4

Maximum group overlap across folds:
0

In [282]:
from google.colab import files

uploaded = files.upload()

ModuleNotFoundError: No module named 'google.colab'

In [283]:
import pandas as pd

file_path = "/Users/ohaseelanka/situation report.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Worksheets:")
for i, sheet in enumerate(excel_file.sheet_names, start=1):
    print(f"{i}. {sheet}")

Worksheets:
1. Sheet1
2. Sheet3
3. Sheet2

In [284]:
for sheet in excel_file.sheet_names:
    df = pd.read_excel(file_path, sheet_name=sheet)

    print("=" * 70)
    print(f"SHEET: {sheet}")
    print("=" * 70)
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    display(df.head())
    print()

======================================================================
SHEET: Sheet1
======================================================================
Shape: (101, 14)

Columns:
['Serial', 'Event', 'Province ', 'District', 'Division', 'Date', 'Location', 'Deaths', 'Injured', 'Missing', 'House Destroyed', 'Houses Damaged', 'Directly affected ', 'Indirectly affected']

First 5 rows:

,Serial,Event,Province,District,Division,Date,Location,Deaths,Injured,Missing,House Destroyed,Houses Damaged,Directly affected,Indirectly affected
0,143020,FLOOD,Western,Colombo,Kaduwela,2019-09-24 00:00:00,NaN,NaN,NaN,NaN,NaN,350.0,NaN,1151.0
1,143019,FLOOD,Western,Colombo,Colombo,2019-09-24 00:00:00,NaN,NaN,NaN,NaN,NaN,203.0,NaN,7024.0
2,143018,FLOOD,Western,Colombo,Moratuwa,2019-09-24 00:00:00,NaN,NaN,NaN,NaN,NaN,4.0,NaN,1367.0
3,143017,FLOOD,Western,Colombo,Sri Jayawardanapura Kotte,2019-09-24 00:00:00,NaN,NaN,NaN,NaN,NaN,75.0,NaN,3804.0
4,143016,FLOOD,Western,Colombo,Thibirigasyaya,2019-09-24 00:00:00,NaN,NaN,NaN,NaN,NaN,6.0,NaN,4637.0

======================================================================
SHEET: Sheet3
======================================================================
Shape: (179, 17)

Columns:
['Province', 'District', 'DS Division', 'Disaster', 'Date of commenced', 'Affected', 'Unnamed: 6', 'Deaths', 'Injured', 'Missing', 'House Damaged', 'Unnamed: 11', 'Safety Places', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Safety Locations']

First 5 rows:

,Province,District,DS Division,Disaster,Date of commenced,Affected,Unnamed: 6,Deaths,Injured,Missing,House Damaged,Unnamed: 11,Safety Places,Unnamed: 13,Unnamed: 14,Unnamed: 15,Safety Locations
0,NaN,NaN,NaN,NaN,NaN,Families,People,NaN,NaN,NaN,Fully,Partially,No. of safety locations,NaN,Families,Persons,NaN
1,Central,Nuwara Eliya,Walapane,Landslide risk,2019.11.30/12.11,107,272,NaN,NaN,NaN,NaN,NaN,10,NaN,107,272,"01. Munwatte Temple, 02.Naranthalawa Wewakele ..."
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Central,Nuwara Eliya,Walapane,Landslide risk,2019.12.20,38,124,NaN,NaN,NaN,NaN,NaN,1,NaN,38,124,Ilukpelesse Multiwok building

======================================================================
SHEET: Sheet2
======================================================================
Shape: (0, 14)

Columns:
['Serial', 'Event', 'Province ', 'District', 'Division', 'Date', 'Location', 'Deaths', 'Injured', 'Missing', 'House Destroyed', 'Houses Damaged', 'Directly affected ', 'Indirectly affected']

First 5 rows:

Empty DataFrame
Columns: [Serial, Event, Province , District, Division, Date, Location, Deaths, Injured, Missing, House Destroyed, Houses Damaged, Directly affected , Indirectly affected]
Index: []

In [285]:
for sheet in excel_file.sheet_names:
    df = pd.read_excel(file_path, sheet_name=sheet)

    print("\n" + "=" * 80)
    print(f"SHEET: {sheet}")
    print("=" * 80)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    # Date information
    date_col = None
    for col in df.columns:
        if "date" in str(col).lower():
            date_col = col
            break

    if date_col:
        dates = pd.to_datetime(df[date_col], errors="coerce")
        print(f"Date column: {date_col}")
        print("Date range:", dates.min(), "to", dates.max())
        print("Valid dates:", dates.notna().sum())

    # Disaster/Event types
    for col in ["Event", "Disaster"]:
        if col in df.columns:
            print(f"\n{col} values:")
            print(df[col].value_counts(dropna=False).head(20))

    # Districts
    for col in ["District"]:
        if col in df.columns:
            print("\nDistricts:")
            print(df[col].value_counts(dropna=False).head(30))

    # DS divisions
    for col in ["Division", "DS Division"]:
        if col in df.columns:
            print("\nDS Divisions:")
            print(df[col].value_counts(dropna=False).head(30))

================================================================================
SHEET: Sheet1
================================================================================
Rows: 101
Columns: 14
Date column: Date
Date range: 1989-01-01 00:00:00 to 2019-09-24 00:00:00
Valid dates: 100

Event values:
Event
FLOOD    101
Name: count, dtype: int64

Districts:
District
Colombo    101
Name: count, dtype: int64

DS Divisions:
Division
Kaduwela                     15
Hanwella                     14
Sri Jayawardanapura Kotte    13
Moratuwa                     12
Thibirigasyaya                8
Homagama                      7
Kolonnawa                     7
Maharagama                    6
Colombo                       5
Kesbewa                       5
Padukka                       4
Dehiwala                      2
Rathmalana                    2
NaN                           1
Name: count, dtype: int64

================================================================================
SHEET: Sheet3
================================================================================
Rows: 179
Columns: 17
Date column: Date of commenced
Date range: 2019-11-30 00:00:00 to 2026-12-28 00:00:00
Valid dates: 129

Disaster values:
Disaster
Flood                   103
NaN                      49
Flood, Landslide          9
Flash Flood               5
Landslide risk            4
Land Slide                2
Flood and\nLandslide      2
Flash Flood               2
Flash flood               1
Flash flood               1
Flood Risk                1
Name: count, dtype: int64

Districts:
District
NaN             99
Gampaha         15
Colombo         14
Nuwara Eliya    13
Rathnapura      12
Kaluthara       12
Kegalle         11
Nuwaraeliya      3
Name: count, dtype: int64

DS Divisions:
DS Division
NaN               77
Kelaniya           5
Wattala            5
Mahara             4
Ja-Ela             4
kaduwela           3
Gampaha            3
Biyagama           3
Walapane           3
Palmadulla         2
Godakawala         2
Dompe              2
Horana             2
Dodangoda          2
Bulathsinghla      2
Attanagalla        2
Kolonnawa          2
Opanayaka          2
Nuwaraeliya        2
Katana             2
Ingiriya           2
Kuruvita           2
Nivithigala        2
Eheliyagoda        2
Ayagama            2
Embilipitiya       2
Rathnapura         2
Kahawattha         2
Kiriella           2
Elapatha           2
Name: count, dtype: int64

================================================================================
SHEET: Sheet2
================================================================================
Rows: 0
Columns: 14
Date column: Date
Date range: NaT to NaT
Valid dates: 0

Event values:
Series([], Name: count, dtype: int64)

Districts:
Series([], Name: count, dtype: int64)

DS Divisions:
Series([], Name: count, dtype: int64)

/var/folders/7f/t00z49jj07x0fn7tv5p2rhyh0000gn/T/ipykernel_9564/2436764183.py:19: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dates = pd.to_datetime(df[date_col], errors="coerce")

In [286]:
sheet3 = pd.read_excel(
    file_path,
    sheet_name="Sheet3",
    header=None
)

print("Shape:", sheet3.shape)

display(sheet3.head(30))

Shape: (180, 17)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Province,District,DS Division,Disaster,Date of commenced,Affected,NaN,Deaths,Injured,Missing,House Damaged,NaN,Safety Places,NaN,NaN,NaN,Safety Locations
1,NaN,NaN,NaN,NaN,NaN,Families,People,NaN,NaN,NaN,Fully,Partially,No. of safety locations,NaN,Families,Persons,NaN
2,Central,Nuwara Eliya,Walapane,Landslide risk,2019.11.30/12.11,107,272,NaN,NaN,NaN,NaN,NaN,10,NaN,107,272,"01. Munwatte Temple, 02.Naranthalawa Wewakele ..."
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Central,Nuwara Eliya,Walapane,Landslide risk,2019.12.20,38,124,NaN,NaN,NaN,NaN,NaN,1,NaN,38,124,Ilukpelesse Multiwok building
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Central,Nuwara Eliya,Walapane,Landslide risk,2019.11.30,126,320,NaN,NaN,NaN,NaN,NaN,2,NaN,8,20,01. Munwatte Temple 02.\nNaranthalawa Wewakele...
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Central,Nuwaraeliya,Nuwaraeliya,Land Slide,2019.12.05,2,11,NaN,NaN,NaN,NaN,NaN,1,NaN,2,11,Lipakele Day Care Centre
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,2019.12.19,1,5,NaN,NaN,NaN,NaN,NaN,1,NaN,1,5,Headrest Cultural Centre
14,Central,Nuwaraeliya,Nuwaraeliya,Land Slide,2020.04.16,1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Central,Nuwaraeliya,Kothmale,Landslide risk,2020.04.23,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Sabaragamuwa,Kegalle,Mawanella,Flash flood,2020.05.14,12,47,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Sabaragamuwa,Rathnapura,Palmadulla,Flood and\nLandslide,2020.05.19,1078,4171,1,NaN,NaN,2,106,5,NaN,36,140,NaN
24,NaN,NaN,Opanayaka,NaN,NaN,297,1094,NaN,NaN,NaN,2,5,1,NaN,16,50,NaN
25,NaN,NaN,Eheliyagoda,NaN,NaN,3,12,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,Ayagama,NaN,NaN,199,694,NaN,NaN,NaN,1,41,1,NaN,5,16,NaN
27,NaN,NaN,Embilipitiya,NaN,NaN,7,25,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,Rathnapura,NaN,NaN,1658,6738,2,NaN,NaN,NaN,129,6,NaN,48,206,NaN
29,NaN,NaN,Kahawattha,NaN,NaN,41,174,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN

In [287]:
# Show every non-empty row with its original Excel row number
# so we can identify how the situation reports are structured.

for i, row in sheet3.iterrows():
    if row.notna().any():
        print(
            f"Excel row {i + 1}:",
            row.dropna().to_dict()
        )

Excel row 1: {0: 'Province', 1: 'District', 2: 'DS Division', 3: 'Disaster', 4: 'Date of commenced', 5: 'Affected', 7: 'Deaths', 8: 'Injured', 9: 'Missing', 10: 'House Damaged', 12: 'Safety Places', 16: 'Safety Locations'}
Excel row 2: {5: 'Families', 6: 'People', 10: 'Fully', 11: 'Partially', 12: 'No. of safety locations', 14: 'Families', 15: 'Persons'}
Excel row 3: {0: 'Central', 1: 'Nuwara Eliya', 2: 'Walapane', 3: 'Landslide risk', 4: '2019.11.30/12.11', 5: 107, 6: 272, 12: 10, 14: 107, 15: 272, 16: '01. Munwatte Temple, 02.Naranthalawa Wewakele temple, 03. Magrat School, 04.Ekangapura School,         05. Brooksight Childcare centre 06.Liyanwala School, 07. Watambe School, 08. Harasbedda Temple\n09. Kalamulle Temple  10. Rockland State Childcare centre'}
Excel row 6: {0: 'Central', 1: 'Nuwara Eliya', 2: 'Walapane', 3: 'Landslide risk', 4: '2019.12.20 ', 5: 38, 6: 124, 12: 1, 14: 38, 15: 124, 16: 'Ilukpelesse Multiwok building '}
Excel row 9: {0: 'Central', 1: 'Nuwara Eliya', 2: 'Walapane', 3: 'Landslide risk', 4: '2019.11.30', 5: 126, 6: 320, 12: 2, 14: 8, 15: 20, 16: '01. Munwatte Temple 02.\nNaranthalawa Wewakele\ntemple '}
Excel row 12: {0: 'Central', 1: 'Nuwaraeliya', 2: 'Nuwaraeliya', 3: 'Land Slide', 4: '2019.12.05 ', 5: 2, 6: 11, 12: 1, 14: 2, 15: 11, 16: 'Lipakele Day Care Centre'}
Excel row 14: {4: '2019.12.19', 5: 1, 6: 5, 12: 1, 14: 1, 15: 5, 16: 'Headrest Cultural Centre'}
Excel row 15: {0: 'Central', 1: 'Nuwaraeliya', 2: 'Nuwaraeliya', 3: 'Land Slide', 4: '2020.04.16', 5: 1, 6: 5}
Excel row 18: {0: 'Central', 1: 'Nuwaraeliya', 2: 'Kothmale', 3: 'Landslide risk', 4: '2020.04.23', 5: 1, 6: 6}
Excel row 21: {0: 'Sabaragamuwa', 1: 'Kegalle', 2: 'Mawanella', 3: 'Flash flood ', 4: '2020.05.14', 5: 12, 6: 47, 11: 3}
Excel row 24: {0: 'Sabaragamuwa', 1: 'Rathnapura', 2: 'Palmadulla', 3: 'Flood and\nLandslide', 4: '2020.05.19', 5: 1078, 6: 4171, 7: 1, 10: 2, 11: 106, 12: 5, 14: 36, 15: 140}
Excel row 25: {2: 'Opanayaka ', 5: 297, 6: 1094, 10: 2, 11: 5, 12: 1, 14: 16, 15: 50}
Excel row 26: {2: 'Eheliyagoda', 5: 3, 6: 12, 11: 3}
Excel row 27: {2: 'Ayagama ', 5: 199, 6: 694, 10: 1, 11: 41, 12: 1, 14: 5, 15: 16}
Excel row 28: {2: 'Embilipitiya', 5: 7, 6: 25, 11: 7}
Excel row 29: {2: 'Rathnapura', 5: 1658, 6: 6738, 7: 2, 11: 129, 12: 6, 14: 48, 15: 206}
Excel row 30: {2: 'Kahawattha ', 5: 41, 6: 174, 11: 4}
Excel row 31: {2: 'Kiriella', 5: 5, 6: 23, 11: 5}
Excel row 32: {2: 'Kalawana ', 5: 21, 6: 69, 11: 18}
Excel row 33: {2: 'Elapatha', 5: 196, 6: 659, 10: 1, 11: 26}
Excel row 34: {2: 'Nivithigala ', 5: 85, 6: 277, 11: 14}
Excel row 35: {2: 'Ibulpe', 5: 6, 6: 24, 11: 6}
Excel row 36: {2: 'Balangoda ', 5: 251, 6: 886, 10: 1, 11: 93, 12: 3, 14: 125, 15: 437}
Excel row 37: {2: 'Kolonna', 5: 23, 6: 81, 10: 1, 11: 22}
Excel row 38: {2: 'Weligapola ', 5: 5, 6: 17, 11: 5}
Excel row 39: {2: 'Kuruvita', 5: 78, 6: 299, 11: 12}
Excel row 40: {2: 'Godakawala ', 5: 9, 6: 26, 11: 9}
Excel row 42: {0: 'Sabaragamuwa', 1: 'Rathnapura', 2: 'Palmadulla', 3: 'Flood and\nLandslide', 4: '2020.05.19  - 2020.05.22', 5: 1362, 6: 5033, 7: 1, 10: 14, 11: 1088, 12: 2, 14: 7, 15: 31}
Excel row 43: {2: 'Opanayaka ', 5: 336, 6: 1189, 10: 4, 11: 31}
Excel row 44: {2: 'Eheliyagoda', 5: 6, 6: 20, 11: 6}
Excel row 45: {2: 'Ayagama ', 5: 296, 6: 765, 10: 1, 11: 49, 12: 1, 14: 3, 15: 7}
Excel row 46: {2: 'Embilipitiya', 5: 10, 6: 37, 11: 10}
Excel row 47: {2: 'Rathnapura', 5: 1986, 6: 8105, 7: 2, 10: 1, 11: 359, 12: 1, 14: 3, 15: 11}
Excel row 48: {2: 'Kahawattha ', 5: 48, 6: 203, 11: 8}
Excel row 49: {2: 'Kiriella', 5: 147, 6: 647, 11: 2}
Excel row 50: {2: 'Kalawana ', 5: 32, 6: 111, 11: 27}
Excel row 51: {2: 'Elapatha', 5: 268, 6: 952, 10: 2, 11: 49}
Excel row 52: {2: 'Nivithigala ', 5: 85, 6: 277, 11: 14}
Excel row 53: {2: 'Ibulpe', 5: 36, 6: 138, 11: 35}
Excel row 54: {2: 'Balangoda ', 5: 302, 6: 1112, 10: 1, 11: 186, 12: 2, 14: 17, 15: 73}
Excel row 55: {2: 'Kolonna', 5: 33, 6: 133, 10: 1, 11: 35}
Excel row 56: {2: 'Weligapola ', 5: 61, 6: 211, 10: 1, 11: 9}
Excel row 57: {2: 'Kuruvita', 5: 92, 6: 360, 11: 23}
Excel row 58: {2: 'Godakawala ', 5: 24, 6: 84, 11: 23}
Excel row 60: {0: 'Western', 1: 'Gampaha', 2: 'Kelaniya', 3: 'Flood', 4: '2024.05.21', 5: 700, 6: 3214, 11: 1}
Excel row 61: {2: 'Negombo', 3: 'Flash Flood', 4: '2024.05.20', 5: 52, 6: 252, 11: 7}
Excel row 62: {2: '60:65', 3: 'Flash Flood', 4: '2024.05.20', 5: 51, 6: 218, 11: 4}
Excel row 63: {2: 'Wattala', 3: 'Flood', 4: '2024.05.20', 5: 3997, 6: 17117, 11: 7}
Excel row 64: {1: 'Colombo', 2: 'Thimbirigasyaya ', 3: 'Flash Flood', 4: '2024.05.20', 5: 347, 6: 1491, 12: 1, 14: 9, 15: 52, 16: 'Wanathamulla\nCommunity Hall'}
Excel row 65: {0: 'Western', 1: 'Gampaha', 2: 'Kelaniya', 3: 'Flood', 4: '2024.05.21 ', 5: 259, 6: 1179, 11: 1}
Excel row 66: {2: 'Ja-Ela', 3: 'Flood', 4: '2024.05.20/21 ', 5: 47, 6: 187, 11: 1}
Excel row 67: {2: 'Biyagama ', 3: 'Flood', 4: '2024.05.21 ', 5: 26, 6: 100, 11: 4}
Excel row 68: {2: 'Wattala', 3: 'Flood', 4: '2024.05.20 ', 5: 3659, 6: 14743, 12: 1, 14: 11, 15: 43, 16: 'Welikadamulla\nSiddartha College'}
Excel row 69: {2: 'Mahara', 3: 'Flood', 4: '2024.05.21 ', 5: 60, 6: 232, 11: 8}
Excel row 70: {2: 'Negambo', 3: 'Flood', 4: '2024.05.22', 5: 2, 6: 8, 11: 2}
Excel row 71: {2: 'Gampaha', 3: 'Flood', 4: '2024.05.21 ', 5: 137, 6: 547}
Excel row 72: {0: 'Western', 1: 'Gampaha', 2: 'Kelaniya', 3: 'Flood', 4: '2024.05.21 ', 5: 44, 6: 209, 10: 1, 11: 3}
Excel row 73: {2: 'Ja-Ela', 3: 'Flood', 4: '2024.05.20/21', 5: 214, 6: 844, 11: 3, 12: 3, 14: 49, 15: 209}
Excel row 74: {2: 'Biyagama ', 3: 'Flood', 4: '2024.05.21', 5: 83, 6: 295, 11: 3}
Excel row 75: {2: 'Wattala', 3: 'Flood', 4: '2024.05.20', 5: 4998, 6: 19987, 11: 0, 12: 2, 14: 22, 15: 75, 16: '1. Welikadamulla\nSiddartha College 2.\nShantha maria College'}
Excel row 76: {2: 'Mahara', 3: 'Flood', 4: '2024.05.21', 5: 121, 6: 491, 11: 8}
Excel row 77: {2: 'Gampaha', 3: 'Flood', 4: '2024.05.21', 5: 180, 6: 727, 11: 5}
Excel row 78: {0: 'Western', 1: 'Colombo', 2: 'kaduwela', 3: 'Flash flood', 4: '2024.05.26 ', 5: 20, 6: 85, 12: 3, 14: 20, 15: 85}
Excel row 79: {2: 'Kolonnawa', 3: 'Flood Risk', 4: '2024.05.25 ', 5: 2, 6: 6}
Excel row 80: {0: 'Western', 1: 'Kaluthara', 2: 'Walallavita', 3: 'Flood', 4: '2024.06.01/02 ', 5: 172, 6: 590, 8: 1, 10: 8, 11: 44}
Excel row 81: {2: 'Mathugama', 3: 'Flash Flood', 4: '2024.06.01/02 ', 5: 515, 6: 1789, 11: 12}
Excel row 82: {2: 'Palindanuwara', 3: 'Flood', 4: '2024.06.01/02 ', 5: 721, 6: 2593, 10: 1, 11: 16}
Excel row 83: {2: 'Bulathsinghla ', 3: 'Flood', 4: '2024.06.01/02 ', 5: 3517, 6: 12568, 7: 1, 11: 10, 12: 4, 14: 35, 15: 125}
Excel row 84: {2: 'Dodangoda', 3: 'Flood', 4: '2024.06.01/02 ', 5: 736, 6: 2752, 11: 736, 12: 5, 14: 33, 15: 135}
Excel row 85: {2: 'Horana', 3: 'Flash Flood ', 4: '2024.06.01/02 ', 5: 33, 6: 124, 11: 6}
Excel row 86: {2: 'Madurawela ', 3: 'Flood', 4: '2024.06.01/02 ', 5: 501, 6: 1900, 11: 7, 12: 1, 14: 4, 15: 15}
Excel row 87: {2: 'Millaniya', 3: 'Flood', 4: '2024.06.01/02 ', 5: 954, 6: 3930, 7: 2, 10: 3, 12: 3, 14: 7, 15: 27}
Excel row 88: {2: 'Ingiriya', 3: 'Flood', 4: '2024.06.01/02 ', 5: 750, 6: 2814, 8: 1, 10: 1, 11: 20}
Excel row 89: {2: 'Agalawattha', 3: 'Flood', 4: '2024.06.01/02 ', 5: 96, 6: 442, 10: 1, 11: 4}
Excel row 90: {2: 'Kalutara', 3: 'Flood', 4: '2024.06.01/02 ', 5: 411, 6: 1502, 10: 2, 11: 8, 12: 4, 14: 170, 15: 608}
Excel row 91: {1: 'Gampaha', 2: 'Biyagama ', 3: 'Flood', 4: '2024.06.02', 5: 593, 6: 2905}
Excel row 92: {2: 'Kelaniya', 3: 'Flood', 4: '2024.06.02', 5: 526, 6: 2537, 11: 3}
Excel row 93: {2: 'Mahara', 3: 'Flood', 4: '2024.06.02', 5: 25, 6: 93, 11: 1}
Excel row 94: {2: 'Dompe ', 3: 'Flood', 4: '2024.06.02', 5: 177, 6: 765, 7: 2}
Excel row 95: {2: 'Attanagalla', 3: 'Flood', 4: '2024.06.02', 5: 380, 6: 1485, 11: 2, 12: 3, 14: 141, 15: 643}
Excel row 96: {2: 'Gamnpaha', 3: 'Flood', 4: '2024.06.02', 5: 1005, 6: 3318, 9: 1}
Excel row 97: {2: 'Wattala', 3: 'Flood', 4: '2024.06.02', 5: 4201, 6: 17142, 12: 2, 14: 19, 15: 68}
Excel row 98: {2: 'minuwangoda', 3: 'Flood', 4: '2024.06.02', 5: 175, 6: 589, 11: 1, 12: 4, 14: 70, 15: 199}
Excel row 99: {2: 'Ja-Ela', 3: 'Flood', 4: '2024.06.02', 5: 1467, 6: 5469, 12: 3, 14: 26, 15: 118}
Excel row 100: {2: 'Katana', 3: 'Flood', 4: '2024.06.02', 5: 793, 6: 2731, 12: 1, 14: 7, 15: 22}
Excel row 101: {1: 'Colombo', 2: 'Homagama', 3: 'Flood', 4: '2024.06.02', 5: 4, 6: 12, 12: 1, 14: 4, 15: 12}
Excel row 102: {2: 'Kolonnawa', 3: 'Flood', 4: '2024.06.02', 5: 125, 6: 499, 12: 3, 14: 125, 15: 499}
Excel row 103: {2: 'kaduwela', 3: 'Flood', 4: '2024.06.02', 5: 3404, 6: 12492, 12: 23, 14: 319, 15: 1386}
Excel row 104: {2: 'Seethawaka', 3: 'Flood', 4: '2024.06.02', 5: 20, 6: 67, 7: 3, 12: 1, 14: 20, 15: 67}
Excel row 105: {0: 'Western', 1: 'Kaluthara', 2: 'Bulathsinghla ', 3: 'Flood', 4: '2024.10.12 ', 5: 9, 6: 35, 11: 4}
Excel row 106: {2: 'Ingiriya', 3: 'Flash Flood', 4: '2024.10.14', 5: 5, 6: 17, 11: 1}
Excel row 107: {2: 'Horana', 3: 'Flood', 4: '2024.10.14', 5: 30, 6: 97, 11: 2}
Excel row 108: {2: 'Dodangoda', 3: 'Flood', 4: '2024.10.14', 5: 24, 6: 92}
Excel row 109: {2: 'Bandaragama', 3: 'Flood', 4: '2024.10.14', 5: 150, 6: 687, 11: 2}
Excel row 110: {1: 'Gampaha', 2: 'Dompe ', 3: 'Flash Flood ', 4: '2024.10.11', 5: 17, 6: 54, 11: 5, 12: 1, 14: 17, 15: 54}
Excel row 111: {2: 'Attanagalla', 3: 'Flood', 4: '2024.10.11', 11: 13}
Excel row 112: {2: 'Minuwangoda', 3: 'Flood', 4: '2024.10.11', 11: 5}
Excel row 113: {2: 'Divullapitiya', 3: 'Flood', 4: '2024.10.11', 11: 3}
Excel row 114: {2: 'Wattala', 3: 'Flood', 4: '2024.10.11', 5: 202, 6: 835, 11: 1, 12: 4, 14: 32, 15: 134}
Excel row 115: {2: 'Mahara', 3: 'Flood', 4: '2024.10.11', 11: 4}
Excel row 116: {2: 'Kelaniya', 3: 'Flood', 4: '2024.10.11', 11: 1}
Excel row 117: {2: 'Katana', 3: 'Flood', 4: '2024.10.11', 5: 30, 6: 98}
Excel row 118: {2: 'Ja-Ela', 3: 'Flood', 4: '2024.10.11', 5: 178, 6: 697, 11: 8, 12: 2, 14: 22, 15: 72}
Excel row 119: {2: 'Gampaha', 3: 'Flood', 4: '2024.10.11', 11: 7}
Excel row 120: {1: 'Colombo', 2: 'kaduwela', 3: 'Flood', 4: '2024.10.11', 5: 497, 6: 1768, 7: 1, 12: 10, 14: 109, 15: 403}
Excel row 121: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2025.12.13', 5: 86117, 6: 330443, 7: 9, 9: 1, 10: 77, 11: 4167, 12: 4, 14: 43, 15: 141}
Excel row 122: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2025.12.13', 5: 23324, 6: 83482, 7: 32, 9: 39, 10: 317, 11: 12817, 12: 104, 14: 2980, 15: 8658}
Excel row 123: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2025.12.13', 5: 2013, 6: 7093, 10: 1, 11: 953}
Excel row 124: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2025.12.13', 5: 24, 6: 110, 7: 17, 9: 1, 10: 213, 11: 6735, 12: 2, 14: 24, 15: 110}
Excel row 125: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2025.12.13', 5: 19092, 6: 74277, 7: 1, 10: 6, 11: 8508, 12: 5, 14: 33, 15: 126}
Excel row 126: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2025.12.13', 5: 19780, 6: 63121, 7: 89, 9: 37, 10: 767, 11: 3742, 12: 211, 14: 6652, 15: 20825}
Excel row 127: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.12.14', 5: 85946, 6: 3296000, 7: 9, 9: 1, 10: 76, 11: 4027, 12: 5, 14: 73, 15: 242}
Excel row 128: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.12.14', 5: 22254, 6: 79784, 7: 32, 9: 39, 10: 284, 11: 11996, 12: 106, 14: 3001, 15: 8932}
Excel row 129: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.12.14', 5: 2013, 6: 7093, 10: 1, 11: 953}
Excel row 130: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.12.14', 5: 92, 6: 374, 7: 17, 9: 1, 10: 211, 11: 6703, 12: 3, 14: 41, 15: 165}
Excel row 131: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.12.14', 5: 19053, 6: 74143, 7: 1, 10: 6, 11: 8462, 12: 6, 14: 52, 15: 194}
Excel row 132: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood', 4: '2026.12.14', 5: 19780, 6: 63121, 7: 89, 9: 37, 10: 767, 11: 3742, 12: 211, 14: 6652, 15: 20825}
Excel row 133: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.12.04', 5: 79794, 6: 306585, 7: 7, 9: 2, 10: 8, 11: 1562, 12: 95, 14: 3615, 15: 11999}
Excel row 134: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.12.04', 5: 15723, 6: 54997, 7: 30, 9: 41, 10: 517, 11: 10017, 12: 133, 14: 3721, 15: 12096}
Excel row 135: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.12.04', 5: 2013, 6: 7093, 10: 1, 11: 953}
Excel row 136: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.12.04', 5: 78620, 6: 322342, 7: 12, 9: 2, 10: 111, 11: 3939, 12: 107, 14: 3860, 15: 16964}
Excel row 137: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.12.04', 5: 17537, 6: 68670, 7: 1, 10: 4, 11: 6434, 12: 10, 14: 100, 15: 360}
Excel row 138: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2026.12.04', 5: 6959, 6: 24681, 7: 89, 9: 73, 10: 15, 11: 453, 12: 123, 14: 234, 15: 11453}
Excel row 139: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.12.08', 5: 85803, 6: 328847, 7: 9, 10: 75, 11: 3647, 12: 21, 14: 384, 15: 1391}
Excel row 140: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.12.08', 5: 20579, 6: 73002, 7: 32, 9: 39, 10: 300, 11: 11601, 12: 120, 14: 3496, 15: 11082}
Excel row 141: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.12.08', 5: 2013, 6: 7093, 10: 1, 11: 953}
Excel row 142: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.12.08', 5: 3117, 6: 12251, 7: 16, 9: 1, 10: 216, 11: 5830, 12: 6, 14: 223, 15: 706}
Excel row 143: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.12.08', 5: 18467, 6: 71937, 7: 1, 10: 6, 11: 7869, 12: 10, 14: 106, 15: 389}
Excel row 144: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2026.12.08', 5: 19780, 6: 63121, 7: 89, 9: 37, 10: 767, 11: 3742, 12: 211, 14: 6652, 15: 20285}
Excel row 145: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.12.15', 5: 86150, 6: 330464, 7: 9, 9: 1, 10: 88, 11: 5574, 12: 3, 14: 25, 15: 87}
Excel row 146: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.12.15', 5: 25348, 6: 87854, 7: 32, 9: 39, 10: 265, 11: 13681, 12: 91, 14: 2503, 15: 7197}
Excel row 147: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.12.15', 5: 2746, 6: 9660, 7: 2, 10: 1, 11: 1323}
Excel row 148: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.12.15', 5: 16, 6: 46, 7: 17, 9: 1, 10: 256, 11: 8838, 12: 1, 14: 16, 15: 46}
Excel row 149: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.12.15', 5: 192523, 6: 74829, 7: 2}
Excel row 150: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2026.12.15', 5: 19501, 6: 62394, 7: 89, 9: 35, 10: 767, 11: 3748, 12: 192, 14: 6225, 15: 19719}
Excel row 151: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.12.17', 5: 86150, 6: 330464, 7: 9, 9: 1, 10: 88, 11: 5574, 12: 2, 14: 23, 15: 85}
Excel row 152: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.12.17', 5: 25348, 6: 87854, 7: 32, 9: 39, 10: 265, 11: 13681, 12: 91, 14: 2503, 15: 7197}
Excel row 153: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.12.17', 5: 2746, 6: 9660, 7: 2, 10: 1, 11: 1323}
Excel row 154: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.12.17', 5: 16, 6: 46, 7: 17, 9: 1, 10: 256, 11: 8853, 12: 1, 14: 16, 15: 46}
Excel row 155: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.12.17', 5: 19291, 6: 74972, 7: 2, 10: 6, 11: 7537, 12: 3, 14: 8, 15: 23}
Excel row 156: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2026.12.17', 5: 19501, 6: 62394, 7: 89, 9: 35, 10: 767, 11: 3748, 12: 192, 14: 6225, 15: 19719}
Excel row 157: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.12.28', 5: 162, 6: 575, 7: 9, 9: 1, 10: 140, 11: 19118, 12: 2, 14: 22, 15: 85}
Excel row 158: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.12.28', 5: 12183, 6: 39802, 7: 33, 9: 38, 10: 297, 11: 13977, 12: 31, 14: 1323, 15: 3742}
Excel row 159: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.12.28', 5: 0, 6: 0, 7: 2, 9: 0, 10: 1, 11: 1323, 12: 0, 14: 0, 15: 0}
Excel row 160: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.12.28', 5: 272, 6: 998, 7: 17, 9: 1, 11: 8863, 12: 1, 14: 16, 15: 46}
Excel row 161: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.12.28', 5: 75, 6: 241, 7: 1, 9: 0, 10: 8, 11: 7726, 12: 1, 14: 5, 15: 15}
Excel row 162: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2026.12.28', 5: 21109, 6: 69039, 7: 80, 9: 33, 10: 703, 11: 3967, 12: 96, 14: 2630, 15: 9112}
Excel row 163: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.11.29', 5: 25159, 6: 99668, 12: 61, 14: 1217, 15: 6061}
Excel row 164: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.11.29', 5: 2148, 6: 8311, 7: 9, 9: 24, 12: 17, 14: 234, 15: 955}
Excel row 165: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.11.29', 5: 429, 6: 1722, 12: 5, 14: 82, 15: 444}
Excel row 166: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.11.29', 5: 31143, 6: 123504, 12: 29, 14: 2820, 15: 10457}
Excel row 167: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.11.29', 5: 1867, 6: 7764, 12: 5, 14: 105, 15: 454}
Excel row 168: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2026.11.29', 5: 250, 6: 920, 7: 6, 9: 4, 12: 49, 14: 380, 15: 603}
Excel row 169: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.11.28', 5: 1061, 6: 3611, 12: 5, 14: 43, 15: 133}
Excel row 170: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.11.28', 5: 800, 6: 3600, 7: 8, 9: 2, 12: 10, 14: 271, 15: 1267}
Excel row 171: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.11.28', 5: 72, 6: 287, 12: 3, 14: 49, 15: 386}
Excel row 172: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.11.28', 5: 17465, 6: 71443, 12: 7, 14: 208, 15: 803}
Excel row 173: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.11.28', 5: 298, 6: 1124, 12: 6, 14: 49, 15: 154}
Excel row 174: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2026.11.28', 5: 250, 6: 920, 7: 6, 9: 4, 12: 49, 14: 380, 15: 1603}
Excel row 175: {0: 'Western', 1: 'Colombo', 3: 'Flood', 4: '2026.12.10', 5: 85946, 6: 329600, 7: 9, 9: 1, 10: 76, 11: 4027, 12: 6, 14: 75, 15: 252}
Excel row 176: {0: 'Sabaragamuwa', 1: 'Kegalle', 3: 'Flood', 4: '2026.12.10', 5: 22254, 6: 79784, 7: 32, 9: 39, 10: 284, 11: 11996, 12: 113, 14: 3106, 15: 9163}
Excel row 177: {0: 'Western', 1: 'Kaluthara', 3: 'Flood', 4: '2026.12.10', 5: 2013, 6: 7093, 10: 1, 11: 953}
Excel row 178: {0: 'Western', 1: 'Gampaha', 3: 'Flood', 4: '2026.12.10', 5: 256, 6: 888, 7: 17, 9: 1, 10: 211, 11: 6501, 12: 4, 14: 58, 15: 242}
Excel row 179: {0: 'Sabaragamuwa', 1: 'Rathnapura', 3: 'Flood', 4: '2026.12.10', 5: 18677, 6: 72647, 7: 1, 10: 6, 11: 8146, 12: 11, 14: 136, 15: 466}
Excel row 180: {0: 'Central', 1: 'Nuwara Eliya', 3: 'Flood, Landslide', 4: '2026.12.10', 5: 19780, 6: 63121, 7: 89, 9: 37, 10: 767, 11: 3742, 12: 211, 14: 6652, 15: 20825}

In [288]:
import pandas as pd

file_path = "/Users/ohaseelanka/situation report.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Worksheets:")
for i, sheet in enumerate(excel_file.sheet_names, start=1):
    print(f"{i}. {sheet}")

print("\n--- Sheet3 date check ---")

sheet3 = pd.read_excel(file_path, sheet_name="Sheet3", header=None)

# Date column is column 4
dates = pd.to_datetime(
    sheet3.iloc[2:, 4].astype(str).str.strip(),
    format="%Y.%m.%d",
    errors="coerce"
)

print("Earliest date:", dates.min())
print("Latest date:", dates.max())

print("\nNumber of valid dates:", dates.notna().sum())
print("Number of invalid/missing dates:", dates.isna().sum())

print("\nDates after 2026-10-07:")
future_dates = dates[dates > pd.Timestamp("2026-10-07")]

if len(future_dates) == 0:
    print("None")
else:
    print(future_dates.to_string())

Worksheets:
1. Sheet1
2. Sheet3

--- Sheet3 date check ---
Earliest date: 2019-11-30 00:00:00
Latest date: 2025-12-28 00:00:00

Number of valid dates: 116
Number of invalid/missing dates: 62

Dates after 2026-10-07:
None

In [289]:
# Show rows where a new report block starts
# A new block starts when Province or District is provided.

for i in range(2, len(sheet3)):
    province = sheet3.iloc[i, 0]
    district = sheet3.iloc[i, 1]
    ds = sheet3.iloc[i, 2]
    disaster = sheet3.iloc[i, 3]
    date = sheet3.iloc[i, 4]

    if pd.notna(province) or pd.notna(district):
        print(
            f"Excel row {i+1} | "
            f"Province: {province} | "
            f"District: {district} | "
            f"DS: {ds} | "
            f"Disaster: {disaster} | "
            f"Date: {date}"
        )

Excel row 3 | Province: Central | District: Nuwara Eliya | DS: Walapane | Disaster: Landslide risk | Date: 2019.11.30/12.11
Excel row 6 | Province: Central | District: Nuwara Eliya | DS: Walapane | Disaster: Landslide risk | Date: 2019.12.20
Excel row 9 | Province: Central | District: Nuwara Eliya | DS: Walapane | Disaster: Landslide risk | Date: 2019.11.30
Excel row 12 | Province: Central | District: Nuwaraeliya | DS: Nuwaraeliya | Disaster: Land Slide | Date: 2019.12.05
Excel row 15 | Province: Central | District: Nuwaraeliya | DS: Nuwaraeliya | Disaster: Land Slide | Date: 2020.04.16
Excel row 18 | Province: Central | District: Nuwaraeliya | DS: Kothmale | Disaster: Landslide risk | Date: 2020.04.23
Excel row 21 | Province: Sabaragamuwa | District: Kegalle | DS: Mawanella | Disaster: Flash flood  | Date: 2020.05.14
Excel row 24 | Province: Sabaragamuwa | District: Rathnapura | DS: Palmadulla | Disaster: Flood and
Landslide | Date: 2020.05.19
Excel row 42 | Province: Sabaragamuwa | District: Rathnapura | DS: Palmadulla | Disaster: Flood and
Landslide | Date: 2020.05.19  - 2020.05.22
Excel row 60 | Province: Western | District: Gampaha | DS: Kelaniya | Disaster: Flood | Date: 2024.05.21
Excel row 64 | Province: nan | District: Colombo | DS: Thimbirigasyaya  | Disaster: Flash Flood | Date: 2024.05.20
Excel row 65 | Province: Western | District: Gampaha | DS: Kelaniya | Disaster: Flood | Date: 2024.05.21
Excel row 72 | Province: Western | District: Gampaha | DS: Kelaniya | Disaster: Flood | Date: 2024.05.21
Excel row 78 | Province: Western | District: Colombo | DS: kaduwela | Disaster: Flash flood | Date: 2024.05.26
Excel row 80 | Province: Western | District: Kaluthara | DS: Walallavita | Disaster: Flood | Date: 2024.06.01/02
Excel row 91 | Province: nan | District: Gampaha | DS: Biyagama  | Disaster: Flood | Date: 2024.06.02
Excel row 101 | Province: nan | District: Colombo | DS: Homagama | Disaster: Flood | Date: 2024.06.02
Excel row 105 | Province: Western | District: Kaluthara | DS: Bulathsinghla  | Disaster: Flood | Date: 2024.10.12
Excel row 110 | Province: nan | District: Gampaha | DS: Dompe  | Disaster: Flash Flood  | Date: 2024.10.11
Excel row 120 | Province: nan | District: Colombo | DS: kaduwela | Disaster: Flood | Date: 2024.10.11
Excel row 121 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.12.13
Excel row 122 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.12.13
Excel row 123 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.12.13
Excel row 124 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.12.13
Excel row 125 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.12.13
Excel row 126 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.12.13
Excel row 127 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.12.14
Excel row 128 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.12.14
Excel row 129 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.12.14
Excel row 130 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.12.14
Excel row 131 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.12.04
Excel row 132 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood | Date: 2025.12.04
Excel row 133 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.12.04
Excel row 134 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.12.04
Excel row 135 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.12.04
Excel row 136 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.12.04
Excel row 137 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.12.04
Excel row 138 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.12.08
Excel row 139 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.12.08
Excel row 140 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.12.08
Excel row 141 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.12.08
Excel row 142 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.12.08
Excel row 143 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.12.08
Excel row 144 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.12.08
Excel row 145 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.12.15
Excel row 146 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.12.15
Excel row 147 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.12.15
Excel row 148 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.12.15
Excel row 149 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.12.15
Excel row 150 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.12.15
Excel row 151 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.12.17
Excel row 152 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.12.17
Excel row 153 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.12.17
Excel row 154 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.12.17
Excel row 155 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.12.17
Excel row 156 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.12.17
Excel row 157 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.12.28
Excel row 158 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.12.28
Excel row 159 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.12.28
Excel row 160 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.12.28
Excel row 161 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.12.28
Excel row 162 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.12.28
Excel row 163 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.11.29
Excel row 164 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.11.29
Excel row 165 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.11.29
Excel row 166 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.11.29
Excel row 167 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.11.29
Excel row 168 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.11.29
Excel row 169 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.11.28
Excel row 170 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.11.28
Excel row 171 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.11.28
Excel row 172 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.11.28
Excel row 173 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.11.28
Excel row 174 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.11.28
Excel row 175 | Province: Western | District: Colombo | DS: nan | Disaster: Flood | Date: 2025.12.10
Excel row 176 | Province: Sabaragamuwa | District: Kegalle | DS: nan | Disaster: Flood | Date: 2025.12.10
Excel row 177 | Province: Western | District: Kaluthara | DS: nan | Disaster: Flood | Date: 2025.12.10
Excel row 178 | Province: Western | District: Gampaha | DS: nan | Disaster: Flood | Date: 2025.12.10
Excel row 179 | Province: Sabaragamuwa | District: Rathnapura | DS: nan | Disaster: Flood | Date: 2025.12.10
Excel row 180 | Province: Central | District: Nuwara Eliya | DS: nan | Disaster: Flood, Landslide | Date: 2025.12.10

In [290]:
# Count detailed DS-level records by year and disaster type.
# This helps us understand how much usable event × DS information
# Sheet3 actually contains.

data = sheet3.iloc[2:].copy()

# Rename the important columns temporarily
data = data.rename(columns={
    0: "province",
    1: "district",
    2: "ds_division",
    3: "disaster",
    4: "date",
    5: "affected_families",
    6: "affected_people",
    7: "deaths",
    8: "injured",
    9: "missing",
    10: "houses_fully_damaged",
    11: "houses_partially_damaged",
    12: "safety_locations_count",
    14: "safety_families",
    15: "safety_persons",
    16: "safety_locations"
})

# Keep rows that have a DS division
ds_rows = data[data["ds_division"].notna()].copy()

# Clean DS names for counting only
ds_rows["ds_division"] = (
    ds_rows["ds_division"]
    .astype(str)
    .str.strip()
)

# Extract the first date from date strings such as:
# 2020.05.19 - 2020.05.22
ds_rows["start_date"] = pd.to_datetime(
    ds_rows["date"]
    .astype(str)
    .str.extract(r"(\d{4}\.\d{2}\.\d{2})")[0],
    format="%Y.%m.%d",
    errors="coerce"
)

ds_rows["year"] = ds_rows["start_date"].dt.year

print("Total rows with DS division:", len(ds_rows))

print("\nDS-level records by year:")
print(
    ds_rows["year"]
    .value_counts()
    .sort_index()
)

print("\nDS-level records by disaster:")
print(
    ds_rows["disaster"]
    .astype(str)
    .str.strip()
    .value_counts()
)

print("\nDS-level records by year and disaster:")
print(
    pd.crosstab(
        ds_rows["year"],
        ds_rows["disaster"].astype(str).str.strip()
    )
)

Total rows with DS division: 102

DS-level records by year:
year
2019.0     4
2020.0     5
2024.0    61
Name: count, dtype: int64

DS-level records by disaster:
disaster
Flood                   52
nan                     32
Flash Flood              7
Landslide risk           4
Land Slide               2
Flash flood              2
Flood and\nLandslide     2
Flood Risk               1
Name: count, dtype: int64

DS-level records by year and disaster:
disaster  Flash Flood  Flash flood  Flood  Flood Risk  Flood and\nLandslide  \
year
2019.0              0            0      0           0                     0
2020.0              0            1      0           0                     2
2024.0              7            1     52           1                     0

disaster  Land Slide  Landslide risk
year
2019.0             1               3
2020.0             1               1
2024.0             0               0

In [291]:
# Reconstruct the Sheet3 report structure.
# This does NOT modify the original Excel file.
# It only creates a working cleaned dataframe.

import pandas as pd
import numpy as np

# Start from the raw Sheet3 data
data = sheet3.iloc[2:].copy()

# Rename important columns
data = data.rename(columns={
    0: "province",
    1: "district",
    2: "ds_division",
    3: "disaster",
    4: "date",
    5: "affected_families",
    6: "affected_people",
    7: "deaths",
    8: "injured",
    9: "missing",
    10: "houses_fully_damaged",
    11: "houses_partially_damaged",
    12: "safety_locations_count",
    14: "safety_families",
    15: "safety_persons",
    16: "safety_locations"
})

# Replace completely blank cells with NaN
data = data.replace(r"^\s*$", np.nan, regex=True)

# Clean text columns
text_columns = [
    "province",
    "district",
    "ds_division",
    "disaster",
    "date"
]

for col in text_columns:
    data[col] = (
        data[col]
        .astype("string")
        .str.strip()
    )

# A report block starts when at least one of the main
# report-identifying fields is present.
# Blank rows separate blocks.

data["is_blank_row"] = data[
    ["province", "district", "ds_division", "disaster", "date"]
].isna().all(axis=1)

# Create a report-block ID.
# Every completely blank row starts a new separator.
data["report_block"] = data["is_blank_row"].cumsum()

# Within each block, inherit report-level information
# from the first non-empty value.
for col in ["province", "district", "disaster", "date"]:
    data[col] = data.groupby("report_block")[col].transform(
        lambda x: x.ffill().bfill()
    )

# Convert numeric impact columns
numeric_columns = [
    "affected_families",
    "affected_people",
    "deaths",
    "injured",
    "missing",
    "houses_fully_damaged",
    "houses_partially_damaged",
    "safety_locations_count",
    "safety_families",
    "safety_persons"
]

for col in numeric_columns:
    data[col] = pd.to_numeric(
        data[col],
        errors="coerce"
    )

# Extract the START date from values such as:
# 2020.05.19 - 2020.05.22
data["start_date"] = pd.to_datetime(
    data["date"]
    .astype("string")
    .str.extract(r"(\d{4}\.\d{2}\.\d{2})")[0],
    format="%Y.%m.%d",
    errors="coerce"
)

# Standardize disaster names
data["disaster_standardized"] = (
    data["disaster"]
    .astype("string")
    .str.replace("\n", " ", regex=False)
    .str.strip()
    .str.lower()
)

data["disaster_standardized"] = data["disaster_standardized"].replace({
    "flash flood": "flash flood",
    "land slide": "landslide",
    "landslide risk": "landslide risk",
    "flood risk": "flood risk",
    "flood and landslide": "flood and landslide",
    "flood": "flood"
})

print("Cleaned Sheet3 shape:", data.shape)

print("\nReport blocks:")
print("Number of report blocks:", data["report_block"].nunique())

print("\nStandardized disaster types:")
print(
    data["disaster_standardized"]
    .value_counts(dropna=False)
)

print("\nRows with DS division after reconstruction:")
print(
    data["ds_division"]
    .notna()
    .sum()
)

print("\nDS-level rows by year after reconstruction:")
print(
    data.loc[data["ds_division"].notna(), "start_date"]
    .dt.year
    .value_counts()
    .sort_index()
)

Cleaned Sheet3 shape: (178, 21)

Report blocks:
Number of report blocks: 16

Standardized disaster types:
disaster_standardized
flood                  104
flood and landslide     36
flash flood             10
flood, landslide         9
landslide risk           7
<NA>                     6
landslide                5
flood risk               1
Name: count, dtype: Int64

Rows with DS division after reconstruction:
102

DS-level rows by year after reconstruction:
start_date
2019     4
2020    37
2024    61
Name: count, dtype: int64

/var/folders/7f/t00z49jj07x0fn7tv5p2rhyh0000gn/T/ipykernel_9564/969616814.py:32: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data = data.replace(r"^\s*$", np.nan, regex=True)

In [292]:
# Inspect the 16 report blocks in Sheet3.
# This lets us distinguish:
# 1. confirmed disaster reports
# 2. risk/status reports
# 3. repeated/update reports
# 4. combined flood + landslide reports

block_summary = (
    data.groupby("report_block", dropna=False)
    .agg(
        province=("province", "first"),
        district=("district", "first"),
        disaster=("disaster", "first"),
        start_date=("start_date", "first"),
        raw_date=("date", "first"),
        total_rows=("report_block", "size"),
        ds_rows=("ds_division", lambda x: x.notna().sum()),
    )
    .reset_index()
)

print(block_summary.to_string(index=False))

 report_block     province     district            disaster start_date                 raw_date  total_rows  ds_rows
            0      Central Nuwara Eliya      Landslide risk 2019-11-30         2019.11.30/12.11           1        1
            1         <NA>         <NA>                <NA>        NaT                     <NA>           1        0
            2      Central Nuwara Eliya      Landslide risk 2019-12-20               2019.12.20           2        1
            3         <NA>         <NA>                <NA>        NaT                     <NA>           1        0
            4      Central Nuwara Eliya      Landslide risk 2019-11-30               2019.11.30           2        1
            5         <NA>         <NA>                <NA>        NaT                     <NA>           1        0
            6      Central  Nuwaraeliya          Land Slide 2019-12-05               2019.12.05           2        1
            7      Central  Nuwaraeliya          Land Slide 2019-12-19               2019.12.19           3        1
            8         <NA>         <NA>                <NA>        NaT                     <NA>           1        0
            9      Central  Nuwaraeliya      Landslide risk 2020-04-23               2020.04.23           2        1
           10         <NA>         <NA>                <NA>        NaT                     <NA>           1        0
           11 Sabaragamuwa      Kegalle         Flash flood 2020-05-14               2020.05.14           2        1
           12         <NA>         <NA>                <NA>        NaT                     <NA>           1        0
           13 Sabaragamuwa   Rathnapura Flood and
Landslide 2020-05-19               2020.05.19          18       17
           14 Sabaragamuwa   Rathnapura Flood and
Landslide 2020-05-19 2020.05.19  - 2020.05.22          18       17
           15      Western      Gampaha               Flood 2024-05-21               2024.05.21         122       61

In [293]:
# Inspect the detailed DS-level records from the potentially
# usable situation-report blocks.

blocks_to_inspect = [6, 7, 11, 13, 14, 15]

inspection = data[
    data["report_block"].isin(blocks_to_inspect) &
    data["ds_division"].notna()
].copy()

# Select the important fields
inspection = inspection[
    [
        "report_block",
        "province",
        "district",
        "ds_division",
        "disaster",
        "date",
        "start_date",
        "affected_families",
        "affected_people",
        "deaths",
        "injured",
        "missing",
        "houses_fully_damaged",
        "houses_partially_damaged",
        "safety_locations_count"
    ]
]

# Add a simple row number for easier discussion
inspection = inspection.reset_index(drop=True)
inspection.insert(0, "record_no", range(1, len(inspection) + 1))

print(inspection.to_string(index=False))

 record_no  report_block     province    district     ds_division            disaster                     date start_date  affected_families  affected_people  deaths  injured  missing  houses_fully_damaged  houses_partially_damaged  safety_locations_count
         1             6      Central Nuwaraeliya     Nuwaraeliya          Land Slide               2019.12.05 2019-12-05                2.0             11.0     NaN      NaN      NaN                   NaN                       NaN                     1.0
         2             7      Central Nuwaraeliya     Nuwaraeliya          Land Slide               2020.04.16 2020-04-16                1.0              5.0     NaN      NaN      NaN                   NaN                       NaN                     NaN
         3            11 Sabaragamuwa     Kegalle       Mawanella         Flash flood               2020.05.14 2020-05-14               12.0             47.0     NaN      NaN      NaN                   NaN                       3.0                     NaN
         4            13 Sabaragamuwa  Rathnapura      Palmadulla Flood and
Landslide               2020.05.19 2020-05-19             1078.0           4171.0     1.0      NaN      NaN                   2.0                     106.0                     5.0
         5            13 Sabaragamuwa  Rathnapura       Opanayaka Flood and
Landslide               2020.05.19 2020-05-19              297.0           1094.0     NaN      NaN      NaN                   2.0                       5.0                     1.0
         6            13 Sabaragamuwa  Rathnapura     Eheliyagoda Flood and
Landslide               2020.05.19 2020-05-19                3.0             12.0     NaN      NaN      NaN                   NaN                       3.0                     NaN
         7            13 Sabaragamuwa  Rathnapura         Ayagama Flood and
Landslide               2020.05.19 2020-05-19              199.0            694.0     NaN      NaN      NaN                   1.0                      41.0                     1.0
         8            13 Sabaragamuwa  Rathnapura    Embilipitiya Flood and
Landslide               2020.05.19 2020-05-19                7.0             25.0     NaN      NaN      NaN                   NaN                       7.0                     NaN
         9            13 Sabaragamuwa  Rathnapura      Rathnapura Flood and
Landslide               2020.05.19 2020-05-19             1658.0           6738.0     2.0      NaN      NaN                   NaN                     129.0                     6.0
        10            13 Sabaragamuwa  Rathnapura      Kahawattha Flood and
Landslide               2020.05.19 2020-05-19               41.0            174.0     NaN      NaN      NaN                   NaN                       4.0                     NaN
        11            13 Sabaragamuwa  Rathnapura        Kiriella Flood and
Landslide               2020.05.19 2020-05-19                5.0             23.0     NaN      NaN      NaN                   NaN                       5.0                     NaN
        12            13 Sabaragamuwa  Rathnapura        Kalawana Flood and
Landslide               2020.05.19 2020-05-19               21.0             69.0     NaN      NaN      NaN                   NaN                      18.0                     NaN
        13            13 Sabaragamuwa  Rathnapura        Elapatha Flood and
Landslide               2020.05.19 2020-05-19              196.0            659.0     NaN      NaN      NaN                   1.0                      26.0                     NaN
        14            13 Sabaragamuwa  Rathnapura     Nivithigala Flood and
Landslide               2020.05.19 2020-05-19               85.0            277.0     NaN      NaN      NaN                   NaN                      14.0                     NaN
        15            13 Sabaragamuwa  Rathnapura          Ibulpe Flood and
Landslide               2020.05.19 2020-05-19                6.0             24.0     NaN      NaN      NaN                   NaN                       6.0                     NaN
        16            13 Sabaragamuwa  Rathnapura       Balangoda Flood and
Landslide               2020.05.19 2020-05-19              251.0            886.0     NaN      NaN      NaN                   1.0                      93.0                     3.0
        17            13 Sabaragamuwa  Rathnapura         Kolonna Flood and
Landslide               2020.05.19 2020-05-19               23.0             81.0     NaN      NaN      NaN                   1.0                      22.0                     NaN
        18            13 Sabaragamuwa  Rathnapura      Weligapola Flood and
Landslide               2020.05.19 2020-05-19                5.0             17.0     NaN      NaN      NaN                   NaN                       5.0                     NaN
        19            13 Sabaragamuwa  Rathnapura        Kuruvita Flood and
Landslide               2020.05.19 2020-05-19               78.0            299.0     NaN      NaN      NaN                   NaN                      12.0                     NaN
        20            13 Sabaragamuwa  Rathnapura      Godakawala Flood and
Landslide               2020.05.19 2020-05-19                9.0             26.0     NaN      NaN      NaN                   NaN                       9.0                     NaN
        21            14 Sabaragamuwa  Rathnapura      Palmadulla Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19             1362.0           5033.0     1.0      NaN      NaN                  14.0                    1088.0                     2.0
        22            14 Sabaragamuwa  Rathnapura       Opanayaka Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19              336.0           1189.0     NaN      NaN      NaN                   4.0                      31.0                     NaN
        23            14 Sabaragamuwa  Rathnapura     Eheliyagoda Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19                6.0             20.0     NaN      NaN      NaN                   NaN                       6.0                     NaN
        24            14 Sabaragamuwa  Rathnapura         Ayagama Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19              296.0            765.0     NaN      NaN      NaN                   1.0                      49.0                     1.0
        25            14 Sabaragamuwa  Rathnapura    Embilipitiya Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               10.0             37.0     NaN      NaN      NaN                   NaN                      10.0                     NaN
        26            14 Sabaragamuwa  Rathnapura      Rathnapura Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19             1986.0           8105.0     2.0      NaN      NaN                   1.0                     359.0                     1.0
        27            14 Sabaragamuwa  Rathnapura      Kahawattha Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               48.0            203.0     NaN      NaN      NaN                   NaN                       8.0                     NaN
        28            14 Sabaragamuwa  Rathnapura        Kiriella Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19              147.0            647.0     NaN      NaN      NaN                   NaN                       2.0                     NaN
        29            14 Sabaragamuwa  Rathnapura        Kalawana Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               32.0            111.0     NaN      NaN      NaN                   NaN                      27.0                     NaN
        30            14 Sabaragamuwa  Rathnapura        Elapatha Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19              268.0            952.0     NaN      NaN      NaN                   2.0                      49.0                     NaN
        31            14 Sabaragamuwa  Rathnapura     Nivithigala Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               85.0            277.0     NaN      NaN      NaN                   NaN                      14.0                     NaN
        32            14 Sabaragamuwa  Rathnapura          Ibulpe Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               36.0            138.0     NaN      NaN      NaN                   NaN                      35.0                     NaN
        33            14 Sabaragamuwa  Rathnapura       Balangoda Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19              302.0           1112.0     NaN      NaN      NaN                   1.0                     186.0                     2.0
        34            14 Sabaragamuwa  Rathnapura         Kolonna Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               33.0            133.0     NaN      NaN      NaN                   1.0                      35.0                     NaN
        35            14 Sabaragamuwa  Rathnapura      Weligapola Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               61.0            211.0     NaN      NaN      NaN                   1.0                       9.0                     NaN
        36            14 Sabaragamuwa  Rathnapura        Kuruvita Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               92.0            360.0     NaN      NaN      NaN                   NaN                      23.0                     NaN
        37            14 Sabaragamuwa  Rathnapura      Godakawala Flood and
Landslide 2020.05.19  - 2020.05.22 2020-05-19               24.0             84.0     NaN      NaN      NaN                   NaN                      23.0                     NaN
        38            15      Western     Gampaha        Kelaniya               Flood               2024.05.21 2024-05-21              700.0           3214.0     NaN      NaN      NaN                   NaN                       1.0                     NaN
        39            15      Western     Gampaha         Negombo         Flash Flood               2024.05.20 2024-05-20               52.0            252.0     NaN      NaN      NaN                   NaN                       7.0                     NaN
        40            15      Western     Gampaha           60:65         Flash Flood               2024.05.20 2024-05-20               51.0            218.0     NaN      NaN      NaN                   NaN                       4.0                     NaN
        41            15      Western     Gampaha         Wattala               Flood               2024.05.20 2024-05-20             3997.0          17117.0     NaN      NaN      NaN                   NaN                       7.0                     NaN
        42            15      Western     Colombo Thimbirigasyaya         Flash Flood               2024.05.20 2024-05-20              347.0           1491.0     NaN      NaN      NaN                   NaN                       NaN                     1.0
        43            15      Western     Gampaha        Kelaniya               Flood               2024.05.21 2024-05-21              259.0           1179.0     NaN      NaN      NaN                   NaN                       1.0                     NaN
        44            15      Western     Gampaha          Ja-Ela               Flood            2024.05.20/21 2024-05-20               47.0            187.0     NaN      NaN      NaN                   NaN                       1.0                     NaN
        45            15      Western     Gampaha        Biyagama               Flood               2024.05.21 2024-05-21               26.0            100.0     NaN      NaN      NaN                   NaN                       4.0                     NaN
        46            15      Western     Gampaha         Wattala               Flood               2024.05.20 2024-05-20             3659.0          14743.0     NaN      NaN      NaN                   NaN                       NaN                     1.0
        47            15      Western     Gampaha          Mahara               Flood               2024.05.21 2024-05-21               60.0            232.0     NaN      NaN      NaN                   NaN                       8.0                     NaN
        48            15      Western     Gampaha         Negambo               Flood               2024.05.22 2024-05-22                2.0              8.0     NaN      NaN      NaN                   NaN                       2.0                     NaN
        49            15      Western     Gampaha         Gampaha               Flood               2024.05.21 2024-05-21              137.0            547.0     NaN      NaN      NaN                   NaN                       NaN                     NaN
        50            15      Western     Gampaha        Kelaniya               Flood               2024.05.21 2024-05-21               44.0            209.0     NaN      NaN      NaN                   1.0                       3.0                     NaN
        51            15      Western     Gampaha          Ja-Ela               Flood            2024.05.20/21 2024-05-20              214.0            844.0     NaN      NaN      NaN                   NaN                       3.0                     3.0
        52            15      Western     Gampaha        Biyagama               Flood               2024.05.21 2024-05-21               83.0            295.0     NaN      NaN      NaN                   NaN                       3.0                     NaN
        53            15      Western     Gampaha         Wattala               Flood               2024.05.20 2024-05-20             4998.0          19987.0     NaN      NaN      NaN                   NaN                       0.0                     2.0
        54            15      Western     Gampaha          Mahara               Flood               2024.05.21 2024-05-21              121.0            491.0     NaN      NaN      NaN                   NaN                       8.0                     NaN
        55            15      Western     Gampaha         Gampaha               Flood               2024.05.21 2024-05-21              180.0            727.0     NaN      NaN      NaN                   NaN                       5.0                     NaN
        56            15      Western     Colombo        kaduwela         Flash flood               2024.05.26 2024-05-26               20.0             85.0     NaN      NaN      NaN                   NaN                       NaN                     3.0
        57            15      Western     Colombo       Kolonnawa          Flood Risk               2024.05.25 2024-05-25                2.0              6.0     NaN      NaN      NaN                   NaN                       NaN                     NaN
        58            15      Western   Kaluthara     Walallavita               Flood            2024.06.01/02 2024-06-01              172.0            590.0     NaN      1.0      NaN                   8.0                      44.0                     NaN
        59            15      Western   Kaluthara       Mathugama         Flash Flood            2024.06.01/02 2024-06-01              515.0           1789.0     NaN      NaN      NaN                   NaN                      12.0                     NaN
        60            15      Western   Kaluthara   Palindanuwara               Flood            2024.06.01/02 2024-06-01              721.0           2593.0     NaN      NaN      NaN                   1.0                      16.0                     NaN
        61            15      Western   Kaluthara   Bulathsinghla               Flood            2024.06.01/02 2024-06-01             3517.0          12568.0     1.0      NaN      NaN                   NaN                      10.0                     4.0
        62            15      Western   Kaluthara       Dodangoda               Flood            2024.06.01/02 2024-06-01              736.0           2752.0     NaN      NaN      NaN                   NaN                     736.0                     5.0
        63            15      Western   Kaluthara          Horana         Flash Flood            2024.06.01/02 2024-06-01               33.0            124.0     NaN      NaN      NaN                   NaN                       6.0                     NaN
        64            15      Western   Kaluthara      Madurawela               Flood            2024.06.01/02 2024-06-01              501.0           1900.0     NaN      NaN      NaN                   NaN                       7.0                     1.0
        65            15      Western   Kaluthara       Millaniya               Flood            2024.06.01/02 2024-06-01              954.0           3930.0     2.0      NaN      NaN                   3.0                       NaN                     3.0
        66            15      Western   Kaluthara        Ingiriya               Flood            2024.06.01/02 2024-06-01              750.0           2814.0     NaN      1.0      NaN                   1.0                      20.0                     NaN
        67            15      Western   Kaluthara     Agalawattha               Flood            2024.06.01/02 2024-06-01               96.0            442.0     NaN      NaN      NaN                   1.0                       4.0                     NaN
        68            15      Western   Kaluthara        Kalutara               Flood            2024.06.01/02 2024-06-01              411.0           1502.0     NaN      NaN      NaN                   2.0                       8.0                     4.0
        69            15      Western     Gampaha        Biyagama               Flood               2024.06.02 2024-06-02              593.0           2905.0     NaN      NaN      NaN                   NaN                       NaN                     NaN
        70            15      Western     Gampaha        Kelaniya               Flood               2024.06.02 2024-06-02              526.0           2537.0     NaN      NaN      NaN                   NaN                       3.0                     NaN
        71            15      Western     Gampaha          Mahara               Flood               2024.06.02 2024-06-02               25.0             93.0     NaN      NaN      NaN                   NaN                       1.0                     NaN
        72            15      Western     Gampaha           Dompe               Flood               2024.06.02 2024-06-02              177.0            765.0     2.0      NaN      NaN                   NaN                       NaN                     NaN
        73            15      Western     Gampaha     Attanagalla               Flood               2024.06.02 2024-06-02              380.0           1485.0     NaN      NaN      NaN                   NaN                       2.0                     3.0
        74            15      Western     Gampaha        Gamnpaha               Flood               2024.06.02 2024-06-02             1005.0           3318.0     NaN      NaN      1.0                   NaN                       NaN                     NaN
        75            15      Western     Gampaha         Wattala               Flood               2024.06.02 2024-06-02             4201.0          17142.0     NaN      NaN      NaN                   NaN                       NaN                     2.0
        76            15      Western     Gampaha     minuwangoda               Flood               2024.06.02 2024-06-02              175.0            589.0     NaN      NaN      NaN                   NaN                       1.0                     4.0
        77            15      Western     Gampaha          Ja-Ela               Flood               2024.06.02 2024-06-02             1467.0           5469.0     NaN      NaN      NaN                   NaN                       NaN                     3.0

In [294]:
# Find repeated DS-level observations for the same
# district + DS division + date + disaster.
#
# These may represent multiple situation-report updates
# rather than independent disaster events.

ds_data = data[
    data["ds_division"].notna()
].copy()

# Clean text for comparison
for col in ["district", "ds_division", "disaster_standardized"]:
    ds_data[col] = (
        ds_data[col]
        .astype("string")
        .str.replace("\n", " ", regex=False)
        .str.strip()
    )

# Create a date key
ds_data["event_date"] = ds_data["start_date"]

# Count occurrences of the same
# district + DS + date + disaster
duplicate_counts = (
    ds_data
    .groupby(
        [
            "district",
            "ds_division",
            "event_date",
            "disaster_standardized"
        ],
        dropna=False
    )
    .size()
    .reset_index(name="record_count")
)

duplicates = duplicate_counts[
    duplicate_counts["record_count"] > 1
].copy()

print("Total unique DS/date/disaster combinations:",
      len(duplicate_counts))

print("Repeated combinations:",
      len(duplicates))

print("\nRepeated combinations:")
print(
    duplicates
    .sort_values(
        ["event_date", "district", "ds_division"]
    )
    .to_string(index=False)
)

print("\nTotal DS-level records involved in repeated combinations:",
      duplicates["record_count"].sum())

Total unique DS/date/disaster combinations: 76
Repeated combinations: 24

Repeated combinations:
    district  ds_division event_date disaster_standardized  record_count
Nuwara Eliya     Walapane 2019-11-30        landslide risk             2
  Rathnapura      Ayagama 2020-05-19   flood and landslide             2
  Rathnapura    Balangoda 2020-05-19   flood and landslide             2
  Rathnapura  Eheliyagoda 2020-05-19   flood and landslide             2
  Rathnapura     Elapatha 2020-05-19   flood and landslide             2
  Rathnapura Embilipitiya 2020-05-19   flood and landslide             2
  Rathnapura   Godakawala 2020-05-19   flood and landslide             2
  Rathnapura       Ibulpe 2020-05-19   flood and landslide             2
  Rathnapura   Kahawattha 2020-05-19   flood and landslide             2
  Rathnapura     Kalawana 2020-05-19   flood and landslide             2
  Rathnapura     Kiriella 2020-05-19   flood and landslide             2
  Rathnapura      Kolonna 2020-05-19   flood and landslide             2
  Rathnapura     Kuruvita 2020-05-19   flood and landslide             2
  Rathnapura  Nivithigala 2020-05-19   flood and landslide             2
  Rathnapura    Opanayaka 2020-05-19   flood and landslide             2
  Rathnapura   Palmadulla 2020-05-19   flood and landslide             2
  Rathnapura   Rathnapura 2020-05-19   flood and landslide             2
  Rathnapura   Weligapola 2020-05-19   flood and landslide             2
     Gampaha       Ja-Ela 2024-05-20                 flood             2
     Gampaha      Wattala 2024-05-20                 flood             3
     Gampaha     Biyagama 2024-05-21                 flood             2
     Gampaha      Gampaha 2024-05-21                 flood             2
     Gampaha     Kelaniya 2024-05-21                 flood             3
     Gampaha       Mahara 2024-05-21                 flood             2

Total DS-level records involved in repeated combinations: 50

In [295]:
# Inspect the original Sheet3 rows around the 2024 situation-report section.
# We include the Excel-style row number so we can trace the
# records back to the original workbook.

# Original Sheet3 has:
# row 1 = main header
# row 2 = subheader
# pandas index 0 = Excel row 1

start_excel_row = 60
end_excel_row = 125

original_section = sheet3.iloc[
    start_excel_row - 1 : end_excel_row
].copy()

# Add Excel row number
original_section.insert(
    0,
    "excel_row",
    range(
        start_excel_row,
        start_excel_row + len(original_section)
    )
)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 40)

print(original_section.to_string(index=False))

 excel_row            0          1                2            3              4     5      6   7   8   9  10    11  12  13   14   15                                                            16
        60      Western    Gampaha         Kelaniya        Flood     2024.05.21   700   3214 NaN NaN NaN NaN     1 NaN NaN  NaN  NaN                                                           NaN
        61          NaN        NaN          Negombo  Flash Flood     2024.05.20    52    252 NaN NaN NaN NaN     7 NaN NaN  NaN  NaN                                                           NaN
        62          NaN        NaN            60:65  Flash Flood     2024.05.20    51    218 NaN NaN NaN NaN     4 NaN NaN  NaN  NaN                                                           NaN
        63          NaN        NaN          Wattala        Flood     2024.05.20  3997  17117 NaN NaN NaN NaN     7 NaN NaN  NaN  NaN                                                           NaN
        64          NaN    Colombo Thimbirigasyaya   Flash Flood     2024.05.20   347   1491 NaN NaN NaN NaN   NaN   1 NaN    9   52                                  Wanathamulla\nCommunity Hall
        65      Western    Gampaha         Kelaniya        Flood    2024.05.21    259   1179 NaN NaN NaN NaN     1 NaN NaN  NaN  NaN                                                           NaN
        66          NaN        NaN           Ja-Ela        Flood 2024.05.20/21     47    187 NaN NaN NaN NaN     1 NaN NaN  NaN  NaN                                                           NaN
        67          NaN        NaN        Biyagama         Flood    2024.05.21     26    100 NaN NaN NaN NaN     4 NaN NaN  NaN  NaN                                                           NaN
        68          NaN        NaN          Wattala        Flood    2024.05.20   3659  14743 NaN NaN NaN NaN   NaN   1 NaN   11   43                              Welikadamulla\nSiddartha College
        69          NaN        NaN           Mahara        Flood    2024.05.21     60    232 NaN NaN NaN NaN     8 NaN NaN  NaN  NaN                                                           NaN
        70          NaN        NaN          Negambo        Flood     2024.05.22     2      8 NaN NaN NaN NaN     2 NaN NaN  NaN  NaN                                                           NaN
        71          NaN        NaN          Gampaha        Flood    2024.05.21    137    547 NaN NaN NaN NaN   NaN NaN NaN  NaN  NaN                                                           NaN
        72      Western    Gampaha         Kelaniya        Flood    2024.05.21     44    209 NaN NaN NaN   1     3 NaN NaN  NaN  NaN                                                           NaN
        73          NaN        NaN           Ja-Ela        Flood  2024.05.20/21   214    844 NaN NaN NaN NaN     3   3 NaN   49  209                                                           NaN
        74          NaN        NaN        Biyagama         Flood     2024.05.21    83    295 NaN NaN NaN NaN     3 NaN NaN  NaN  NaN                                                           NaN
        75          NaN        NaN          Wattala        Flood     2024.05.20  4998  19987 NaN NaN NaN NaN     0   2 NaN   22   75 1. Welikadamulla\nSiddartha College 2.\nShantha maria College
        76          NaN        NaN           Mahara        Flood     2024.05.21   121    491 NaN NaN NaN NaN     8 NaN NaN  NaN  NaN                                                           NaN
        77          NaN        NaN          Gampaha        Flood     2024.05.21   180    727 NaN NaN NaN NaN     5 NaN NaN  NaN  NaN                                                           NaN
        78      Western    Colombo         kaduwela  Flash flood    2024.05.26     20     85 NaN NaN NaN NaN   NaN   3 NaN   20   85                                                           NaN
        79          NaN        NaN        Kolonnawa   Flood Risk    2024.05.25      2      6 NaN NaN NaN NaN   NaN NaN NaN  NaN  NaN                                                           NaN
        80      Western  Kaluthara      Walallavita        Flood 2024.06.01/02    172    590 NaN   1 NaN   8    44 NaN NaN  NaN  NaN                                                           NaN
        81          NaN        NaN        Mathugama  Flash Flood 2024.06.01/02    515   1789 NaN NaN NaN NaN    12 NaN NaN  NaN  NaN                                                           NaN
        82          NaN        NaN    Palindanuwara        Flood 2024.06.01/02    721   2593 NaN NaN NaN   1    16 NaN NaN  NaN  NaN                                                           NaN
        83          NaN        NaN   Bulathsinghla         Flood 2024.06.01/02   3517  12568   1 NaN NaN NaN    10   4 NaN   35  125                                                           NaN
        84          NaN        NaN        Dodangoda        Flood 2024.06.01/02    736   2752 NaN NaN NaN NaN   736   5 NaN   33  135                                                           NaN
        85          NaN        NaN           Horana Flash Flood  2024.06.01/02     33    124 NaN NaN NaN NaN     6 NaN NaN  NaN  NaN                                                           NaN
        86          NaN        NaN      Madurawela         Flood 2024.06.01/02    501   1900 NaN NaN NaN NaN     7   1 NaN    4   15                                                           NaN
        87          NaN        NaN        Millaniya        Flood 2024.06.01/02    954   3930   2 NaN NaN   3   NaN   3 NaN    7   27                                                           NaN
        88          NaN        NaN         Ingiriya        Flood 2024.06.01/02    750   2814 NaN   1 NaN   1    20 NaN NaN  NaN  NaN                                                           NaN
        89          NaN        NaN      Agalawattha        Flood 2024.06.01/02     96    442 NaN NaN NaN   1     4 NaN NaN  NaN  NaN                                                           NaN
        90          NaN        NaN         Kalutara        Flood 2024.06.01/02    411   1502 NaN NaN NaN   2     8   4 NaN  170  608                                                           NaN
        91          NaN    Gampaha        Biyagama         Flood     2024.06.02   593   2905 NaN NaN NaN NaN   NaN NaN NaN  NaN  NaN                                                           NaN
        92          NaN        NaN         Kelaniya        Flood     2024.06.02   526   2537 NaN NaN NaN NaN     3 NaN NaN  NaN  NaN                                                           NaN
        93          NaN        NaN           Mahara        Flood     2024.06.02    25     93 NaN NaN NaN NaN     1 NaN NaN  NaN  NaN                                                           NaN
        94          NaN        NaN           Dompe         Flood     2024.06.02   177    765   2 NaN NaN NaN   NaN NaN NaN  NaN  NaN                                                           NaN
        95          NaN        NaN      Attanagalla        Flood     2024.06.02   380   1485 NaN NaN NaN NaN     2   3 NaN  141  643                                                           NaN
        96          NaN        NaN         Gamnpaha        Flood     2024.06.02  1005   3318 NaN NaN   1 NaN   NaN NaN NaN  NaN  NaN                                                           NaN
        97          NaN        NaN          Wattala        Flood     2024.06.02  4201  17142 NaN NaN NaN NaN   NaN   2 NaN   19   68                                                           NaN
        98          NaN        NaN      minuwangoda        Flood     2024.06.02   175    589 NaN NaN NaN NaN     1   4 NaN   70  199                                                           NaN
        99          NaN        NaN           Ja-Ela        Flood     2024.06.02  1467   5469 NaN NaN NaN NaN   NaN   3 NaN   26  118                                                           NaN
       100          NaN        NaN           Katana        Flood     2024.06.02   793   2731 NaN NaN NaN NaN   NaN   1 NaN    7   22                                                           NaN
       101          NaN    Colombo         Homagama        Flood     2024.06.02     4     12 NaN NaN NaN NaN   NaN   1 NaN    4   12                                                           NaN
       102          NaN        NaN        Kolonnawa        Flood     2024.06.02   125    499 NaN NaN NaN NaN   NaN   3 NaN  125  499                                                           NaN
       103          NaN        NaN         kaduwela        Flood     2024.06.02  3404  12492 NaN NaN NaN NaN   NaN  23 NaN  319 1386                                                           NaN
       104          NaN        NaN       Seethawaka        Flood     2024.06.02    20     67   3 NaN NaN NaN   NaN   1 NaN   20   67                                                           NaN
       105      Western  Kaluthara   Bulathsinghla         Flood    2024.10.12      9     35 NaN NaN NaN NaN     4 NaN NaN  NaN  NaN                                                           NaN
       106          NaN        NaN         Ingiriya  Flash Flood     2024.10.14     5     17 NaN NaN NaN NaN     1 NaN NaN  NaN  NaN                                                           NaN
       107          NaN        NaN           Horana        Flood     2024.10.14    30     97 NaN NaN NaN NaN     2 NaN NaN  NaN  NaN                                                           NaN
       108          NaN        NaN        Dodangoda        Flood     2024.10.14    24     92 NaN NaN NaN NaN   NaN NaN NaN  NaN  NaN                                                           NaN
       109          NaN        NaN      Bandaragama        Flood     2024.10.14   150    687 NaN NaN NaN NaN     2 NaN NaN  NaN  NaN                                                           NaN
       110          NaN    Gampaha           Dompe  Flash Flood      2024.10.11    17     54 NaN NaN NaN NaN     5   1 NaN   17   54                                                           NaN
       111          NaN        NaN      Attanagalla        Flood     2024.10.11   NaN    NaN NaN NaN NaN NaN    13 NaN NaN  NaN  NaN                                                           NaN
       112          NaN        NaN      Minuwangoda        Flood     2024.10.11   NaN    NaN NaN NaN NaN NaN     5 NaN NaN  NaN  NaN                                                           NaN
       113          NaN        NaN    Divullapitiya        Flood     2024.10.11   NaN    NaN NaN NaN NaN NaN     3 NaN NaN  NaN  NaN                                                           NaN
       114          NaN        NaN          Wattala        Flood     2024.10.11   202    835 NaN NaN NaN NaN     1   4 NaN   32  134                                                           NaN
       115          NaN        NaN           Mahara        Flood     2024.10.11   NaN    NaN NaN NaN NaN NaN     4 NaN NaN  NaN  NaN                                                           NaN
       116          NaN        NaN         Kelaniya        Flood     2024.10.11   NaN    NaN NaN NaN NaN NaN     1 NaN NaN  NaN  NaN                                                           NaN
       117          NaN        NaN           Katana        Flood     2024.10.11    30     98 NaN NaN NaN NaN   NaN NaN NaN  NaN  NaN                                                           NaN
       118          NaN        NaN           Ja-Ela        Flood     2024.10.11   178    697 NaN NaN NaN NaN     8   2 NaN   22   72                                                           NaN
       119          NaN        NaN          Gampaha        Flood     2024.10.11   NaN    NaN NaN NaN NaN NaN     7 NaN NaN  NaN  NaN                                                           NaN
       120          NaN    Colombo         kaduwela        Flood     2024.10.11   497   1768   1 NaN NaN NaN   NaN  10 NaN  109  403                                                           NaN
       121      Western    Colombo              NaN        Flood     2025.12.13 86117 330443   9 NaN   1  77  4167   4 NaN   43  141                                                           NaN
       122 Sabaragamuwa    Kegalle              NaN        Flood     2025.12.13 23324  83482  32 NaN  39 317 12817 104 NaN 2980 8658                                                           NaN
       123      Western  Kaluthara              NaN        Flood     2025.12.13  2013   7093 NaN NaN NaN   1   953 NaN NaN  NaN  NaN                                                           NaN
       124      Western    Gampaha              NaN        Flood     2025.12.13    24    110  17 NaN   1 213  6735   2 NaN   24  110                                                           NaN
       125 Sabaragamuwa Rathnapura              NaN        Flood     2025.12.13 19092  74277   1 NaN NaN   6  8508   5 NaN   33  126                                                           NaN

In [296]:
# Compare repeated DS/date/disaster records side-by-side.
# This helps identify whether later records are cumulative updates.

repeated_keys = duplicates[
    ["district", "ds_division", "event_date", "disaster_standardized"]
].copy()

comparison = ds_data.merge(
    repeated_keys,
    on=[
        "district",
        "ds_division",
        "event_date",
        "disaster_standardized"
    ],
    how="inner"
)

comparison = comparison[
    [
        "report_block",
        "district",
        "ds_division",
        "disaster_standardized",
        "date",
        "affected_families",
        "affected_people",
        "deaths",
        "injured",
        "missing",
        "houses_fully_damaged",
        "houses_partially_damaged"
    ]
].sort_values(
    [
        "district",
        "ds_division",
        "event_date",
        "report_block"
    ]
)

print(comparison.to_string(index=False))

KeyError: 'event_date'

In [297]:
# Compare repeated DS/date/disaster records.
# This version avoids the event_date merge conflict.

repeated_keys = duplicates[
    ["district", "ds_division", "event_date", "disaster_standardized"]
].copy()

comparison = ds_data[
    [
        "report_block",
        "district",
        "ds_division",
        "event_date",
        "disaster_standardized",
        "date",
        "affected_families",
        "affected_people",
        "deaths",
        "injured",
        "missing",
        "houses_fully_damaged",
        "houses_partially_damaged"
    ]
].merge(
    repeated_keys,
    on=[
        "district",
        "ds_division",
        "event_date",
        "disaster_standardized"
    ],
    how="inner"
)

comparison = comparison.sort_values(
    [
        "district",
        "ds_division",
        "event_date",
        "report_block"
    ]
)

print(comparison.to_string(index=False))

 report_block     district  ds_division event_date disaster_standardized                     date  affected_families  affected_people  deaths  injured  missing  houses_fully_damaged  houses_partially_damaged
           15      Gampaha     Biyagama 2024-05-21                 flood               2024.05.21               26.0            100.0     NaN      NaN      NaN                   NaN                       4.0
           15      Gampaha     Biyagama 2024-05-21                 flood               2024.05.21               83.0            295.0     NaN      NaN      NaN                   NaN                       3.0
           15      Gampaha      Gampaha 2024-05-21                 flood               2024.05.21              137.0            547.0     NaN      NaN      NaN                   NaN                       NaN
           15      Gampaha      Gampaha 2024-05-21                 flood               2024.05.21              180.0            727.0     NaN      NaN      NaN                   NaN                       5.0
           15      Gampaha       Ja-Ela 2024-05-20                 flood            2024.05.20/21               47.0            187.0     NaN      NaN      NaN                   NaN                       1.0
           15      Gampaha       Ja-Ela 2024-05-20                 flood            2024.05.20/21              214.0            844.0     NaN      NaN      NaN                   NaN                       3.0
           15      Gampaha     Kelaniya 2024-05-21                 flood               2024.05.21              700.0           3214.0     NaN      NaN      NaN                   NaN                       1.0
           15      Gampaha     Kelaniya 2024-05-21                 flood               2024.05.21              259.0           1179.0     NaN      NaN      NaN                   NaN                       1.0
           15      Gampaha     Kelaniya 2024-05-21                 flood               2024.05.21               44.0            209.0     NaN      NaN      NaN                   1.0                       3.0
           15      Gampaha       Mahara 2024-05-21                 flood               2024.05.21               60.0            232.0     NaN      NaN      NaN                   NaN                       8.0
           15      Gampaha       Mahara 2024-05-21                 flood               2024.05.21              121.0            491.0     NaN      NaN      NaN                   NaN                       8.0
           15      Gampaha      Wattala 2024-05-20                 flood               2024.05.20             3997.0          17117.0     NaN      NaN      NaN                   NaN                       7.0
           15      Gampaha      Wattala 2024-05-20                 flood               2024.05.20             3659.0          14743.0     NaN      NaN      NaN                   NaN                       NaN
           15      Gampaha      Wattala 2024-05-20                 flood               2024.05.20             4998.0          19987.0     NaN      NaN      NaN                   NaN                       0.0
            0 Nuwara Eliya     Walapane 2019-11-30        landslide risk         2019.11.30/12.11              107.0            272.0     NaN      NaN      NaN                   NaN                       NaN
            4 Nuwara Eliya     Walapane 2019-11-30        landslide risk               2019.11.30              126.0            320.0     NaN      NaN      NaN                   NaN                       NaN
           13   Rathnapura      Ayagama 2020-05-19   flood and landslide               2020.05.19              199.0            694.0     NaN      NaN      NaN                   1.0                      41.0
           14   Rathnapura      Ayagama 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22              296.0            765.0     NaN      NaN      NaN                   1.0                      49.0
           13   Rathnapura    Balangoda 2020-05-19   flood and landslide               2020.05.19              251.0            886.0     NaN      NaN      NaN                   1.0                      93.0
           14   Rathnapura    Balangoda 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22              302.0           1112.0     NaN      NaN      NaN                   1.0                     186.0
           13   Rathnapura  Eheliyagoda 2020-05-19   flood and landslide               2020.05.19                3.0             12.0     NaN      NaN      NaN                   NaN                       3.0
           14   Rathnapura  Eheliyagoda 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22                6.0             20.0     NaN      NaN      NaN                   NaN                       6.0
           13   Rathnapura     Elapatha 2020-05-19   flood and landslide               2020.05.19              196.0            659.0     NaN      NaN      NaN                   1.0                      26.0
           14   Rathnapura     Elapatha 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22              268.0            952.0     NaN      NaN      NaN                   2.0                      49.0
           13   Rathnapura Embilipitiya 2020-05-19   flood and landslide               2020.05.19                7.0             25.0     NaN      NaN      NaN                   NaN                       7.0
           14   Rathnapura Embilipitiya 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               10.0             37.0     NaN      NaN      NaN                   NaN                      10.0
           13   Rathnapura   Godakawala 2020-05-19   flood and landslide               2020.05.19                9.0             26.0     NaN      NaN      NaN                   NaN                       9.0
           14   Rathnapura   Godakawala 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               24.0             84.0     NaN      NaN      NaN                   NaN                      23.0
           13   Rathnapura       Ibulpe 2020-05-19   flood and landslide               2020.05.19                6.0             24.0     NaN      NaN      NaN                   NaN                       6.0
           14   Rathnapura       Ibulpe 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               36.0            138.0     NaN      NaN      NaN                   NaN                      35.0
           13   Rathnapura   Kahawattha 2020-05-19   flood and landslide               2020.05.19               41.0            174.0     NaN      NaN      NaN                   NaN                       4.0
           14   Rathnapura   Kahawattha 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               48.0            203.0     NaN      NaN      NaN                   NaN                       8.0
           13   Rathnapura     Kalawana 2020-05-19   flood and landslide               2020.05.19               21.0             69.0     NaN      NaN      NaN                   NaN                      18.0
           14   Rathnapura     Kalawana 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               32.0            111.0     NaN      NaN      NaN                   NaN                      27.0
           13   Rathnapura     Kiriella 2020-05-19   flood and landslide               2020.05.19                5.0             23.0     NaN      NaN      NaN                   NaN                       5.0
           14   Rathnapura     Kiriella 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22              147.0            647.0     NaN      NaN      NaN                   NaN                       2.0
           13   Rathnapura      Kolonna 2020-05-19   flood and landslide               2020.05.19               23.0             81.0     NaN      NaN      NaN                   1.0                      22.0
           14   Rathnapura      Kolonna 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               33.0            133.0     NaN      NaN      NaN                   1.0                      35.0
           13   Rathnapura     Kuruvita 2020-05-19   flood and landslide               2020.05.19               78.0            299.0     NaN      NaN      NaN                   NaN                      12.0
           14   Rathnapura     Kuruvita 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               92.0            360.0     NaN      NaN      NaN                   NaN                      23.0
           13   Rathnapura  Nivithigala 2020-05-19   flood and landslide               2020.05.19               85.0            277.0     NaN      NaN      NaN                   NaN                      14.0
           14   Rathnapura  Nivithigala 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               85.0            277.0     NaN      NaN      NaN                   NaN                      14.0
           13   Rathnapura    Opanayaka 2020-05-19   flood and landslide               2020.05.19              297.0           1094.0     NaN      NaN      NaN                   2.0                       5.0
           14   Rathnapura    Opanayaka 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22              336.0           1189.0     NaN      NaN      NaN                   4.0                      31.0
           13   Rathnapura   Palmadulla 2020-05-19   flood and landslide               2020.05.19             1078.0           4171.0     1.0      NaN      NaN                   2.0                     106.0
           14   Rathnapura   Palmadulla 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22             1362.0           5033.0     1.0      NaN      NaN                  14.0                    1088.0
           13   Rathnapura   Rathnapura 2020-05-19   flood and landslide               2020.05.19             1658.0           6738.0     2.0      NaN      NaN                   NaN                     129.0
           14   Rathnapura   Rathnapura 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22             1986.0           8105.0     2.0      NaN      NaN                   1.0                     359.0
           13   Rathnapura   Weligapola 2020-05-19   flood and landslide               2020.05.19                5.0             17.0     NaN      NaN      NaN                   NaN                       5.0
           14   Rathnapura   Weligapola 2020-05-19   flood and landslide 2020.05.19  - 2020.05.22               61.0            211.0     NaN      NaN      NaN                   1.0                       9.0

In [298]:
# Inspect Sheet3 with Excel row numbers and the original values.
# We are specifically checking where each situation-report
# snapshot starts and ends.

start_excel_row = 1
end_excel_row = 120

inspection = sheet3.iloc[
    start_excel_row - 1 : end_excel_row
].copy()

inspection.insert(
    0,
    "excel_row",
    range(
        start_excel_row,
        start_excel_row + len(inspection)
    )
)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 60)
pd.set_option("display.width", 250)

print(inspection.to_string(index=False))

 excel_row            0            1                2                    3                        4        5      6      7       8       9            10        11                      12  13       14      15                                                                                                                                                                                                                                                               16
         1     Province     District      DS Division             Disaster        Date of commenced Affected    NaN Deaths Injured Missing House Damaged       NaN           Safety Places NaN      NaN     NaN                                                                                                                                                                                                                                                 Safety Locations
         2          NaN          NaN              NaN                  NaN                      NaN Families People    NaN     NaN     NaN         Fully Partially No. of safety locations NaN Families Persons                                                                                                                                                                                                                                                              NaN
         3      Central Nuwara Eliya         Walapane       Landslide risk         2019.11.30/12.11      107    272    NaN     NaN     NaN           NaN       NaN                      10 NaN      107     272 01. Munwatte Temple, 02.Naranthalawa Wewakele temple, 03. Magrat School, 04.Ekangapura School,         05. Brooksight Childcare centre 06.Liyanwala School, 07. Watambe School, 08. Harasbedda Temple\n09. Kalamulle Temple  10. Rockland State Childcare centre
         4          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
         5          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
         6      Central Nuwara Eliya         Walapane       Landslide risk              2019.12.20        38    124    NaN     NaN     NaN           NaN       NaN                       1 NaN       38     124                                                                                                                                                                                                                                   Ilukpelesse Multiwok building
         7          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
         8          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
         9      Central Nuwara Eliya         Walapane       Landslide risk               2019.11.30      126    320    NaN     NaN     NaN           NaN       NaN                       2 NaN        8      20                                                                                                                                                                                                          01. Munwatte Temple 02.\nNaranthalawa Wewakele\ntemple
        10          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        11          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        12      Central  Nuwaraeliya      Nuwaraeliya           Land Slide              2019.12.05         2     11    NaN     NaN     NaN           NaN       NaN                       1 NaN        2      11                                                                                                                                                                                                                                         Lipakele Day Care Centre
        13          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        14          NaN          NaN              NaN                  NaN               2019.12.19        1      5    NaN     NaN     NaN           NaN       NaN                       1 NaN        1       5                                                                                                                                                                                                                                         Headrest Cultural Centre
        15      Central  Nuwaraeliya      Nuwaraeliya           Land Slide               2020.04.16        1      5    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        16          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        17          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        18      Central  Nuwaraeliya         Kothmale       Landslide risk               2020.04.23        1      6    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        19          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        20          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        21 Sabaragamuwa      Kegalle        Mawanella         Flash flood                2020.05.14       12     47    NaN     NaN     NaN           NaN         3                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        22          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        23          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        24 Sabaragamuwa   Rathnapura       Palmadulla Flood and\nLandslide               2020.05.19     1078   4171      1     NaN     NaN             2       106                       5 NaN       36     140                                                                                                                                                                                                                                                              NaN
        25          NaN          NaN       Opanayaka                   NaN                      NaN      297   1094    NaN     NaN     NaN             2         5                       1 NaN       16      50                                                                                                                                                                                                                                                              NaN
        26          NaN          NaN      Eheliyagoda                  NaN                      NaN        3     12    NaN     NaN     NaN           NaN         3                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        27          NaN          NaN         Ayagama                   NaN                      NaN      199    694    NaN     NaN     NaN             1        41                       1 NaN        5      16                                                                                                                                                                                                                                                              NaN
        28          NaN          NaN     Embilipitiya                  NaN                      NaN        7     25    NaN     NaN     NaN           NaN         7                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        29          NaN          NaN       Rathnapura                  NaN                      NaN     1658   6738      2     NaN     NaN           NaN       129                       6 NaN       48     206                                                                                                                                                                                                                                                              NaN
        30          NaN          NaN      Kahawattha                   NaN                      NaN       41    174    NaN     NaN     NaN           NaN         4                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        31          NaN          NaN         Kiriella                  NaN                      NaN        5     23    NaN     NaN     NaN           NaN         5                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        32          NaN          NaN        Kalawana                   NaN                      NaN       21     69    NaN     NaN     NaN           NaN        18                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        33          NaN          NaN         Elapatha                  NaN                      NaN      196    659    NaN     NaN     NaN             1        26                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        34          NaN          NaN     Nivithigala                   NaN                      NaN       85    277    NaN     NaN     NaN           NaN        14                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        35          NaN          NaN           Ibulpe                  NaN                      NaN        6     24    NaN     NaN     NaN           NaN         6                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        36          NaN          NaN       Balangoda                   NaN                      NaN      251    886    NaN     NaN     NaN             1        93                       3 NaN      125     437                                                                                                                                                                                                                                                              NaN
        37          NaN          NaN          Kolonna                  NaN                      NaN       23     81    NaN     NaN     NaN             1        22                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        38          NaN          NaN      Weligapola                   NaN                      NaN        5     17    NaN     NaN     NaN           NaN         5                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        39          NaN          NaN         Kuruvita                  NaN                      NaN       78    299    NaN     NaN     NaN           NaN        12                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        40          NaN          NaN      Godakawala                   NaN                      NaN        9     26    NaN     NaN     NaN           NaN         9                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        41          NaN          NaN              NaN                  NaN                      NaN      NaN    NaN    NaN     NaN     NaN           NaN       NaN                     NaN NaN      NaN     NaN                                                                                                                                                                                                                                                              NaN
        42 Sabaragamuwa   Rathnapura       Palmadulla Flood and\nLandslide 2020.05.19  - 2020.05.22     1362   5033      1     NaN     NaN            14      1088                       2 NaN        7      31                                                                                                                                                                                                                                                              NaN

In [299]:
# Identify rows that appear to start a new situation-report section.
# A new section is indicated when the Province field is populated.

section_starts = sheet3[
    sheet3[0].notna()
].copy()

section_starts.insert(
    0,
    "excel_row",
    section_starts.index + 1
)

print(
    section_starts[
        [
            "excel_row",
            0,
            1,
            2,
            3,
            4
        ]
    ].to_string(index=False)
)

 excel_row            0            1              2                    3                        4
         1     Province     District    DS Division             Disaster        Date of commenced
         3      Central Nuwara Eliya       Walapane       Landslide risk         2019.11.30/12.11
         6      Central Nuwara Eliya       Walapane       Landslide risk              2019.12.20
         9      Central Nuwara Eliya       Walapane       Landslide risk               2019.11.30
        12      Central  Nuwaraeliya    Nuwaraeliya           Land Slide              2019.12.05
        15      Central  Nuwaraeliya    Nuwaraeliya           Land Slide               2020.04.16
        18      Central  Nuwaraeliya       Kothmale       Landslide risk               2020.04.23
        21 Sabaragamuwa      Kegalle      Mawanella         Flash flood                2020.05.14
        24 Sabaragamuwa   Rathnapura     Palmadulla Flood and\nLandslide               2020.05.19
        42 Sabaragamuwa   Rathnapura     Palmadulla Flood and\nLandslide 2020.05.19  - 2020.05.22
        60      Western      Gampaha       Kelaniya                Flood               2024.05.21
        65      Western      Gampaha       Kelaniya                Flood              2024.05.21
        72      Western      Gampaha       Kelaniya                Flood              2024.05.21
        78      Western      Colombo       kaduwela          Flash flood              2024.05.26
        80      Western    Kaluthara    Walallavita                Flood           2024.06.01/02
       105      Western    Kaluthara Bulathsinghla                 Flood              2024.10.12
       121      Western      Colombo            NaN                Flood               2025.12.13
       122 Sabaragamuwa      Kegalle            NaN                Flood               2025.12.13
       123      Western    Kaluthara            NaN                Flood               2025.12.13
       124      Western      Gampaha            NaN                Flood               2025.12.13
       125 Sabaragamuwa   Rathnapura            NaN                Flood               2025.12.13
       126      Central Nuwara Eliya            NaN     Flood, Landslide               2025.12.13
       127      Western      Colombo            NaN                Flood               2025.12.14
       128 Sabaragamuwa      Kegalle            NaN                Flood               2025.12.14
       129      Western    Kaluthara            NaN                Flood               2025.12.14
       130      Western      Gampaha            NaN                Flood               2025.12.14
       131 Sabaragamuwa   Rathnapura            NaN                Flood               2025.12.04
       132      Central Nuwara Eliya            NaN                Flood               2025.12.04
       133      Western      Colombo            NaN                Flood               2025.12.04
       134 Sabaragamuwa      Kegalle            NaN                Flood               2025.12.04
       135      Western    Kaluthara            NaN                Flood               2025.12.04
       136      Western      Gampaha            NaN                Flood               2025.12.04
       137 Sabaragamuwa   Rathnapura            NaN                Flood               2025.12.04
       138      Central Nuwara Eliya            NaN     Flood, Landslide               2025.12.08
       139      Western      Colombo            NaN                Flood               2025.12.08
       140 Sabaragamuwa      Kegalle            NaN                Flood               2025.12.08
       141      Western    Kaluthara            NaN                Flood               2025.12.08
       142      Western      Gampaha            NaN                Flood               2025.12.08
       143 Sabaragamuwa   Rathnapura            NaN                Flood               2025.12.08
       144      Central Nuwara Eliya            NaN     Flood, Landslide               2025.12.08
       145      Western      Colombo            NaN                Flood               2025.12.15
       146 Sabaragamuwa      Kegalle            NaN                Flood               2025.12.15
       147      Western    Kaluthara            NaN                Flood               2025.12.15
       148      Western      Gampaha            NaN                Flood               2025.12.15
       149 Sabaragamuwa   Rathnapura            NaN                Flood               2025.12.15
       150      Central Nuwara Eliya            NaN     Flood, Landslide               2025.12.15
       151      Western      Colombo            NaN                Flood               2025.12.17
       152 Sabaragamuwa      Kegalle            NaN                Flood               2025.12.17
       153      Western    Kaluthara            NaN                Flood               2025.12.17
       154      Western      Gampaha            NaN                Flood               2025.12.17
       155 Sabaragamuwa   Rathnapura            NaN                Flood               2025.12.17
       156      Central Nuwara Eliya            NaN     Flood, Landslide               2025.12.17
       157      Western      Colombo            NaN                Flood               2025.12.28
       158 Sabaragamuwa      Kegalle            NaN                Flood               2025.12.28
       159      Western    Kaluthara            NaN                Flood               2025.12.28
       160      Western      Gampaha            NaN                Flood               2025.12.28
       161 Sabaragamuwa   Rathnapura            NaN                Flood               2025.12.28
       162      Central Nuwara Eliya            NaN     Flood, Landslide               2025.12.28
       163      Western      Colombo            NaN                Flood               2025.11.29
       164 Sabaragamuwa      Kegalle            NaN                Flood               2025.11.29
       165      Western    Kaluthara            NaN                Flood               2025.11.29
       166      Western      Gampaha            NaN                Flood               2025.11.29
       167 Sabaragamuwa   Rathnapura            NaN                Flood               2025.11.29
       168      Central Nuwara Eliya            NaN     Flood, Landslide               2025.11.29
       169      Western      Colombo            NaN                Flood               2025.11.28
       170 Sabaragamuwa      Kegalle            NaN                Flood               2025.11.28
       171      Western    Kaluthara            NaN                Flood               2025.11.28
       172      Western      Gampaha            NaN                Flood               2025.11.28
       173 Sabaragamuwa   Rathnapura            NaN                Flood               2025.11.28
       174      Central Nuwara Eliya            NaN     Flood, Landslide               2025.11.28
       175      Western      Colombo            NaN                Flood               2025.12.10
       176 Sabaragamuwa      Kegalle            NaN                Flood               2025.12.10
       177      Western    Kaluthara            NaN                Flood               2025.12.10
       178      Western      Gampaha            NaN                Flood               2025.12.10
       179 Sabaragamuwa   Rathnapura            NaN                Flood               2025.12.10
       180      Central Nuwara Eliya            NaN     Flood, Landslide               2025.12.10

In [300]:
# Compare the three 2024 Gampaha situation-report snapshots.
# We use the original Excel row numbers to preserve provenance.

snapshot_rows = [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                 72, 73, 74, 75, 76, 77]

snapshot = sheet3.iloc[
    [r - 1 for r in snapshot_rows]
].copy()

snapshot.insert(
    0,
    "excel_row",
    snapshot_rows
)

# Show the fields relevant to identifying the situation-report snapshots.
snapshot_view = snapshot[
    [
        "excel_row",
        0,   # Province
        1,   # District
        2,   # DS Division
        3,   # Disaster
        4,   # Date
        5,   # Families
        6,   # People
        10,  # Houses fully damaged
        11,  # Houses partially damaged
        12,  # Safety locations
        14,  # Safety families
        15   # Safety persons
    ]
].copy()

snapshot_view.columns = [
    "excel_row",
    "province",
    "district",
    "ds_division",
    "disaster",
    "date",
    "affected_families",
    "affected_people",
    "houses_fully_damaged",
    "houses_partially_damaged",
    "safety_locations",
    "safety_families",
    "safety_persons"
]

print(snapshot_view.to_string(index=False))

 excel_row province district      ds_division    disaster           date affected_families affected_people houses_fully_damaged houses_partially_damaged safety_locations safety_families safety_persons
        60  Western  Gampaha         Kelaniya       Flood     2024.05.21               700            3214                  NaN                        1              NaN             NaN            NaN
        61      NaN      NaN          Negombo Flash Flood     2024.05.20                52             252                  NaN                        7              NaN             NaN            NaN
        62      NaN      NaN            60:65 Flash Flood     2024.05.20                51             218                  NaN                        4              NaN             NaN            NaN
        63      NaN      NaN          Wattala       Flood     2024.05.20              3997           17117                  NaN                        7              NaN             NaN            NaN
        64      NaN  Colombo Thimbirigasyaya  Flash Flood     2024.05.20               347            1491                  NaN                      NaN                1               9             52
        65  Western  Gampaha         Kelaniya       Flood    2024.05.21                259            1179                  NaN                        1              NaN             NaN            NaN
        66      NaN      NaN           Ja-Ela       Flood 2024.05.20/21                 47             187                  NaN                        1              NaN             NaN            NaN
        67      NaN      NaN        Biyagama        Flood    2024.05.21                 26             100                  NaN                        4              NaN             NaN            NaN
        68      NaN      NaN          Wattala       Flood    2024.05.20               3659           14743                  NaN                      NaN                1              11             43
        69      NaN      NaN           Mahara       Flood    2024.05.21                 60             232                  NaN                        8              NaN             NaN            NaN
        70      NaN      NaN          Negambo       Flood     2024.05.22                 2               8                  NaN                        2              NaN             NaN            NaN
        71      NaN      NaN          Gampaha       Flood    2024.05.21                137             547                  NaN                      NaN              NaN             NaN            NaN
        72  Western  Gampaha         Kelaniya       Flood    2024.05.21                 44             209                    1                        3              NaN             NaN            NaN
        73      NaN      NaN           Ja-Ela       Flood  2024.05.20/21               214             844                  NaN                        3                3              49            209
        74      NaN      NaN        Biyagama        Flood     2024.05.21                83             295                  NaN                        3              NaN             NaN            NaN
        75      NaN      NaN          Wattala       Flood     2024.05.20              4998           19987                  NaN                        0                2              22             75
        76      NaN      NaN           Mahara       Flood     2024.05.21               121             491                  NaN                        8              NaN             NaN            NaN
        77      NaN      NaN          Gampaha       Flood     2024.05.21               180             727                  NaN                        5              NaN             NaN            NaN

In [301]:
# Inspect workbook metadata and worksheet dimensions.
# This does not modify the original workbook.

import os
from openpyxl import load_workbook

file_path = "/Users/ohaseelanka/situation report.xlsx"

print("File exists:", os.path.exists(file_path))
print("File size (KB):", round(os.path.getsize(file_path) / 1024, 2))

wb = load_workbook(
    file_path,
    read_only=False,
    data_only=False
)

print("\nWorksheets:")
for ws in wb.worksheets:
    print(
        f"- {ws.title}: "
        f"rows={ws.max_row}, "
        f"columns={ws.max_column}"
    )

print("\nWorkbook properties:")
print("Title:", wb.properties.title)
print("Subject:", wb.properties.subject)
print("Creator:", wb.properties.creator)
print("Last modified by:", wb.properties.lastModifiedBy)
print("Created:", wb.properties.created)
print("Modified:", wb.properties.modified)

print("\nDefined names:")
for name in wb.defined_names.values():
    print(name)

File exists: True
File size (KB): 38.09

Worksheets:
- Sheet1: rows=102, columns=15
- Sheet3: rows=180, columns=24

Workbook properties:
Title: None
Subject: None
Creator: PRATHIBHANI Y L O L it23317512
Last modified by: PRATHIBHANI Y L O L it23317512
Created: 2026-09-28 03:36:46
Modified: 2026-10-07 03:43:57

Defined names:

In [302]:
print("DMC Situation Report extraction - starting")

DMC Situation Report extraction - starting

In [303]:
print("DMC Situation Report extraction - starting")

DMC Situation Report extraction - starting

In [304]:
import requests

url = "https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=0&option=com_dmcreports&report_type_id=1&view=reports"

response = requests.get(
    url,
    timeout=30,
    headers={"User-Agent": "Mozilla/5.0"}
)

print("Status code:", response.status_code)
print("Page size:", len(response.text), "characters")
print("Page received:", response.text[:200])

SSLError: HTTPSConnectionPool(host='www.drrweb.dmc.gov.lk', port=443): Max retries exceeded with url: /index.php?Itemid=273&lang=en&limit=30&limitstart=0&option=com_dmcreports&report_type_id=1&view=reports (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.drrweb.dmc.gov.lk'. (_ssl.c:1028)")))

In [305]:
import requests
import urllib3

# Hide the warning caused by the DMC server's SSL certificate
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

url = "https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=0&option=com_dmcreports&report_type_id=1&view=reports"

response = requests.get(
    url,
    timeout=30,
    headers={"User-Agent": "Mozilla/5.0"},
    verify=False
)

print("Status code:", response.status_code)
print("Page size:", len(response.text), "characters")
print("Page received:", response.text[:200])

Status code: 200
Page size: 46555 characters
Page received:
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr">
   <head>
      <meta http-equiv="X-UA-Compatible" content="IE=9" />
      <meta name="viewport" co

In [306]:
from bs4 import BeautifulSoup
from urllib.parse import urljoin

soup = BeautifulSoup(response.text, "html.parser")

base_url = "https://www.drrweb.dmc.gov.lk/"

report_links = []

for a in soup.find_all("a", href=True):
    href = a["href"].strip()
    text = a.get_text(" ", strip=True)

    # Keep links that look like situation-report/PDF links
    if (
        ".pdf" in href.lower()
        or "report" in href.lower()
        or "dmcreport" in href.lower()
    ):
        report_links.append({
            "text": text,
            "url": urljoin(base_url, href)
        })

print("Potential report links found:", len(report_links))

print("\nFirst 50 potential report links:\n")

for i, item in enumerate(report_links[:50], start=1):
    print(f"{i}. TEXT: {item['text']}")
    print(f"   URL : {item['url']}")
    print()

Potential report links found: 47

First 50 potential report links:

1. TEXT: සිංහල
   URL : https://www.drrweb.dmc.gov.lk/index.php?option=com_dmcreports&view=reports&report_type_id=1&Itemid=273&lang=si

2. TEXT: தமிழ்
   URL : https://www.drrweb.dmc.gov.lk/index.php?option=com_dmcreports&view=reports&report_type_id=1&Itemid=273&lang=ta

3. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1791262582.pdf

4. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1791178519.pdf

5. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1791178541.pdf

6. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1791089060.pdf

7. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1791089087.pdf

8. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1791003670.pdf

9. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1791003705.pdf

10. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1790745357.pdf

11. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1790745384.pdf

12. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1790750768.pdf

13. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1790750792.pdf

14. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1790485204.pdf

15. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1790485224.pdf

16. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1790245513.pdf

17. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1790053739.pdf

18. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1790053767.pdf

19. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1789792349.pdf

20. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1789792374.pdf

21. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1789706759.pdf

22. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1789706775.pdf

23. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1789623228.pdf

24. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1789623308.pdf

25. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1789536506.pdf

26. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1789536549.pdf

27. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1789454335.pdf

28. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1789454350.pdf

29. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1789277061.pdf

30. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1789277084.pdf

31. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1788932329.pdf

32. TEXT: Download
   URL : https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_Situation_Report_on_2026__1788932348.pdf

33. TEXT: 2
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=30&option=com_dmcreports&report_type_id=1&view=reports

34. TEXT: 3
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=60&option=com_dmcreports&report_type_id=1&view=reports

35. TEXT: 4
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=90&option=com_dmcreports&report_type_id=1&view=reports

36. TEXT: ...
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=120&option=com_dmcreports&report_type_id=1&view=reports

37. TEXT: 6
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=150&option=com_dmcreports&report_type_id=1&view=reports

38. TEXT: 7
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=180&option=com_dmcreports&report_type_id=1&view=reports

39. TEXT: 8
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=210&option=com_dmcreports&report_type_id=1&view=reports

40. TEXT: 9
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=240&option=com_dmcreports&report_type_id=1&view=reports

41. TEXT: 10
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=270&option=com_dmcreports&report_type_id=1&view=reports

42. TEXT:
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=30&option=com_dmcreports&report_type_id=1&view=reports

43. TEXT:
   URL : https://www.drrweb.dmc.gov.lk/index.php?Itemid=273&lang=en&limit=30&limitstart=4890&option=com_dmcreports&report_type_id=1&view=reports

44. TEXT: Situation Reports
   URL : https://www.drrweb.dmc.gov.lk/index.php?option=com_dmcreports&view=reports&Itemid=273&report_type_id=1&lang=en

45. TEXT: Weather Reports New
   URL : https://www.drrweb.dmc.gov.lk/index.php?option=com_dmcreports&view=reports&Itemid=274&report_type_id=2&lang=en

46. TEXT: Landslide Warning
   URL : https://www.drrweb.dmc.gov.lk/index.php?option=com_dmcreports&view=reports&Itemid=276&report_type_id=5&lang=en

47. TEXT: River Water Level and Flood Warning New
   URL : https://www.drrweb.dmc.gov.lk/index.php?option=com_dmcreports&view=reports&Itemid=277&report_type_id=6&lang=en

In [307]:
from bs4 import BeautifulSoup
from urllib.parse import urljoin

soup = BeautifulSoup(response.text, "html.parser")

# Find the first PDF download link
pdf_link = None

for a in soup.find_all("a", href=True):
    href = a["href"].strip()

    if ".pdf" in href.lower():
        pdf_link = a
        break

if pdf_link is None:
    print("No PDF link found.")
else:
    print("PDF URL:")
    print(urljoin(base_url, pdf_link["href"]))

    print("\n--- Parent HTML ---")
    print(pdf_link.parent.prettify()[:5000])

PDF URL:
https://www.drrweb.dmc.gov.lk/images/dmcreports/Situation_Report_on_2026__1791262582.pdf

--- Parent HTML ---
<td class="sandplustd">
 <a href="/images/dmcreports/Situation_Report_on_2026__1791262582.pdf" onclick="window.open(this.href,'_blank');return false;">
  Download
 </a>
</td>

In [308]:
# Get the complete table row containing the PDF download link

row = pdf_link.find_parent("tr")

if row is None:
    print("Could not find the report table row.")
else:
    print(row.get_text(" | ", strip=True))
    print("\n--- HTML of the complete row ---")
    print(row.prettify()[:10000])

Situation Report | 2026-10-06 | 10:00 | Download

--- HTML of the complete row ---
<tr class="rowdate_0">
 <td>
  Situation Report
 </td>
 <td>
  2026-10-06
 </td>
 <td>
  10:00
 </td>
 <td class="sandplustd">
  <a href="/images/dmcreports/Situation_Report_on_2026__1791262582.pdf" onclick="window.open(this.href,'_blank');return false;">
   Download
  </a>
 </td>
</tr>

In [309]:
import pandas as pd
from urllib.parse import urljoin

reports = []

# Find every report row on the current page
for row in soup.find_all("tr"):

    cells = row.find_all("td")

    # A valid report row has at least 4 cells
    if len(cells) >= 4:

        report_type = cells[0].get_text(" ", strip=True)
        report_date = cells[1].get_text(" ", strip=True)
        report_time = cells[2].get_text(" ", strip=True)

        download_link = cells[3].find("a", href=True)

        if download_link and ".pdf" in download_link["href"].lower():

            pdf_url = urljoin(
                base_url,
                download_link["href"]
            )

            reports.append({
                "report_type": report_type,
                "report_date": report_date,
                "report_time": report_time,
                "pdf_url": pdf_url
            })

reports_df = pd.DataFrame(reports)

print("Reports extracted:", len(reports_df))

print("\nFirst 10 reports:")
display(reports_df.head(10))

Reports extracted: 30

First 10 reports:

                report_type report_date report_time                                                      pdf_url
0          Situation Report  2026-10-06       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...
1          Situation Report  2026-10-05       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...
2  Drought Situation Report  2026-10-05       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_...
3          Situation Report  2026-10-04       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...
4  Drought Situation Report  2026-10-04       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_...
5          Situation Report  2026-10-03       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...
6  Drought Situation Report  2026-10-03       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_...
7          Situation Report  2026-09-30       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...
8  Drought Situation Report  2026-09-30       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Drought_...
9          Situation Report  2026-09-29       10:00  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...

In [310]:
# Convert the report dates to real dates
reports_df["report_date"] = pd.to_datetime(
    reports_df["report_date"],
    errors="coerce"
)

print("Reports on current page:", len(reports_df))

print("Latest report:", reports_df["report_date"].max())
print("Earliest report on current page:", reports_df["report_date"].min())

print("\nReport types:")
print(reports_df["report_type"].value_counts())

print("\nCurrent page:")
display(
    reports_df[
        ["report_type", "report_date", "report_time"]
    ]
)

Reports on current page: 30
Latest report: 2026-10-06 00:00:00
Earliest report on current page: 2026-09-09 00:00:00

Report types:
report_type
Situation Report            16
Drought Situation Report    12
situation report             2
Name: count, dtype: int64

Current page:

                 report_type report_date report_time
0           Situation Report  2026-10-06       10:00
1           Situation Report  2026-10-05       10:00
2   Drought Situation Report  2026-10-05       10:00
3           Situation Report  2026-10-04       10:00
4   Drought Situation Report  2026-10-04       10:00
5           Situation Report  2026-10-03       10:00
6   Drought Situation Report  2026-10-03       10:00
7           Situation Report  2026-09-30       10:00
8   Drought Situation Report  2026-09-30       10:00
9           Situation Report  2026-09-29       10:00
10  Drought Situation Report  2026-09-29       10:00
11          Situation Report  2026-09-27       10:00
12          Situation Report  2026-09-27       10:00
13          Situation Report  2026-09-24       10:00
14          Situation Report  2026-09-22       10:00
15  Drought Situation Report  2026-09-22       10:00
16          Situation Report  2026-09-19       10:00
17  Drought Situation Report  2026-09-19       10:00
18          Situation Report  2026-09-18       10:00
19  Drought Situation Report  2026-09-18       10:00
20          situation report  2026-09-17       10:00
21          situation report  2026-09-17       10:00
22          Situation Report  2026-09-16       10:00
23  Drought Situation Report  2026-09-16       10:00
24          Situation Report  2026-09-15       10:00
25  Drought Situation Report  2026-09-15       10:00
26          Situation Report  2026-09-13       10:00
27  Drought Situation Report  2026-09-13       10:00
28          Situation Report  2026-09-09       10:00
29  Drought Situation Report  2026-09-09       10:00

In [311]:
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

BASE_URL = "https://www.drrweb.dmc.gov.lk/index.php"

all_reports = []

# Start from the first page
limit = 30
start = 0

session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0"
})

while True:

    page_url = (
        f"{BASE_URL}"
        f"?Itemid=273"
        f"&lang=en"
        f"&limit={limit}"
        f"&limitstart={start}"
        f"&option=com_dmcreports"
        f"&report_type_id=1"
        f"&view=reports"
    )

    try:
        page_response = session.get(
            page_url,
            timeout=30,
            verify=False
        )

        print(
            f"Page start={start} | "
            f"Status={page_response.status_code}"
        )

        if page_response.status_code != 200:
            print("Stopping because the page request failed.")
            break

        page_soup = BeautifulSoup(
            page_response.text,
            "html.parser"
        )

        page_count = 0

        for row in page_soup.find_all("tr"):

            cells = row.find_all("td")

            if len(cells) < 4:
                continue

            report_type = cells[0].get_text(
                " ",
                strip=True
            )

            report_date = cells[1].get_text(
                " ",
                strip=True
            )

            report_time = cells[2].get_text(
                " ",
                strip=True
            )

            download_link = cells[3].find(
                "a",
                href=True
            )

            if (
                download_link
                and ".pdf" in download_link["href"].lower()
            ):

                pdf_url = urljoin(
                    BASE_URL,
                    download_link["href"]
                )

                all_reports.append({
                    "report_type": report_type,
                    "report_date": report_date,
                    "report_time": report_time,
                    "pdf_url": pdf_url
                })

                page_count += 1

        print(
            f"  Reports found on page: {page_count}"
        )

        # Stop when no report rows are found
        if page_count == 0:
            print("No more reports found.")
            break

        # Move to next page
        start += limit

        # Small delay to avoid sending requests too quickly
        time.sleep(0.5)

        # Safety limit — prevents accidental endless crawling
        if start > 6000:
            print("Safety limit reached.")
            break

    except Exception as e:
        print("Error:", repr(e))
        break


# Convert to DataFrame
all_reports_df = pd.DataFrame(all_reports)

# Clean dates
all_reports_df["report_date"] = pd.to_datetime(
    all_reports_df["report_date"],
    errors="coerce"
)

# Remove exact duplicate PDF URLs
all_reports_df = (
    all_reports_df
    .drop_duplicates(subset=["pdf_url"])
    .reset_index(drop=True)
)

print("\n" + "=" * 60)
print("CRAWLING COMPLETE")
print("=" * 60)

print("Total unique reports:", len(all_reports_df))

print(
    "Latest report:",
    all_reports_df["report_date"].max()
)

print(
    "Earliest report:",
    all_reports_df["report_date"].min()
)

print("\nReport types:")
print(
    all_reports_df["report_type"]
    .str.strip()
    .str.lower()
    .value_counts()
)

print("\nReports by year:")
print(
    all_reports_df["report_date"]
    .dt.year
    .value_counts()
    .sort_index()
)

Page start=0 | Status=200
  Reports found on page: 30
Page start=30 | Status=200
  Reports found on page: 30
Page start=60 | Status=200
  Reports found on page: 30
Page start=90 | Status=200
  Reports found on page: 30
Page start=120 | Status=200
  Reports found on page: 30
Page start=150 | Status=200
  Reports found on page: 30
Page start=180 | Status=200
  Reports found on page: 30
Page start=210 | Status=200
  Reports found on page: 30
Page start=240 | Status=200
  Reports found on page: 30
Page start=270 | Status=200
  Reports found on page: 30
Page start=300 | Status=200
  Reports found on page: 30
Page start=330 | Status=200
  Reports found on page: 30
Page start=360 | Status=200
  Reports found on page: 30
Page start=390 | Status=200
  Reports found on page: 30
Page start=420 | Status=200
  Reports found on page: 30
Page start=450 | Status=200
  Reports found on page: 30
Page start=480 | Status=200
  Reports found on page: 30
Page start=510 | Status=200
  Reports found on page: 30
Page start=540 | Status=200
  Reports found on page: 30
Page start=570 | Status=200
  Reports found on page: 30
Page start=600 | Status=200
  Reports found on page: 30
Page start=630 | Status=200
  Reports found on page: 30
Page start=660 | Status=200
  Reports found on page: 30
Page start=690 | Status=200
  Reports found on page: 30
Page start=720 | Status=200
  Reports found on page: 30
Page start=750 | Status=200
  Reports found on page: 30
Page start=780 | Status=200
  Reports found on page: 30
Page start=810 | Status=200
  Reports found on page: 30
Page start=840 | Status=200
  Reports found on page: 30
Page start=870 | Status=200
  Reports found on page: 30
Page start=900 | Status=200
  Reports found on page: 30
Page start=930 | Status=200
  Reports found on page: 30
Page start=960 | Status=200
  Reports found on page: 30
Page start=990 | Status=200
  Reports found on page: 30
Page start=1020 | Status=200
  Reports found on page: 30
Page start=1050 | Status=200
  Reports found on page: 30
Page start=1080 | Status=200
  Reports found on page: 30
Page start=1110 | Status=200
  Reports found on page: 30
Page start=1140 | Status=200
  Reports found on page: 30
Page start=1170 | Status=200
  Reports found on page: 30
Page start=1200 | Status=200
  Reports found on page: 30
Page start=1230 | Status=200
  Reports found on page: 30
Page start=1260 | Status=200
  Reports found on page: 30
Page start=1290 | Status=200
  Reports found on page: 30
Page start=1320 | Status=200
  Reports found on page: 30
Page start=1350 | Status=200
  Reports found on page: 30
Page start=1380 | Status=200
  Reports found on page: 30
Page start=1410 | Status=200
  Reports found on page: 30
Page start=1440 | Status=200
  Reports found on page: 30
Page start=1470 | Status=200
  Reports found on page: 30
Page start=1500 | Status=200
  Reports found on page: 30
Page start=1530 | Status=200
  Reports found on page: 30
Page start=1560 | Status=200
  Reports found on page: 30
Page start=1590 | Status=200
  Reports found on page: 29
Page start=1620 | Status=200
  Reports found on page: 30
Page start=1650 | Status=200
  Reports found on page: 30
Page start=1680 | Status=200
  Reports found on page: 30
Page start=1710 | Status=200
  Reports found on page: 30
Page start=1740 | Status=200
  Reports found on page: 30
Page start=1770 | Status=200
  Reports found on page: 30
Page start=1800 | Status=200
  Reports found on page: 30
Page start=1830 | Status=200
  Reports found on page: 30
Page start=1860 | Status=200
  Reports found on page: 30
Page start=1890 | Status=200
  Reports found on page: 30
Page start=1920 | Status=200
  Reports found on page: 30
Page start=1950 | Status=200
  Reports found on page: 30
Page start=1980 | Status=200
  Reports found on page: 30
Page start=2010 | Status=200
  Reports found on page: 30
Page start=2040 | Status=200
  Reports found on page: 30
Page start=2070 | Status=200
  Reports found on page: 29
Page start=2100 | Status=200
  Reports found on page: 30
Page start=2130 | Status=200
  Reports found on page: 30
Page start=2160 | Status=200
  Reports found on page: 30
Page start=2190 | Status=200
  Reports found on page: 29
Page start=2220 | Status=200
  Reports found on page: 30
Page start=2250 | Status=200
  Reports found on page: 30
Page start=2280 | Status=200
  Reports found on page: 30
Page start=2310 | Status=200
  Reports found on page: 30
Page start=2340 | Status=200
  Reports found on page: 30
Page start=2370 | Status=200
  Reports found on page: 30
Page start=2400 | Status=200
  Reports found on page: 30
Page start=2430 | Status=200
  Reports found on page: 30
Page start=2460 | Status=200
  Reports found on page: 30
Page start=2490 | Status=200
  Reports found on page: 30
Page start=2520 | Status=200
  Reports found on page: 30
Page start=2550 | Status=200
  Reports found on page: 30
Page start=2580 | Status=200
  Reports found on page: 30
Page start=2610 | Status=200
  Reports found on page: 29
Page start=2640 | Status=200
  Reports found on page: 30
Page start=2670 | Status=200
  Reports found on page: 30
Page start=2700 | Status=200
  Reports found on page: 30
Page start=2730 | Status=200
  Reports found on page: 30
Page start=2760 | Status=200
  Reports found on page: 30
Page start=2790 | Status=200
  Reports found on page: 30
Page start=2820 | Status=200
  Reports found on page: 30
Page start=2850 | Status=200
  Reports found on page: 30
Page start=2880 | Status=200
  Reports found on page: 30
Page start=2910 | Status=200
  Reports found on page: 30
Page start=2940 | Status=200
  Reports found on page: 30
Page start=2970 | Status=200
  Reports found on page: 30
Page start=3000 | Status=200
  Reports found on page: 30
Page start=3030 | Status=200
  Reports found on page: 30
Page start=3060 | Status=200
  Reports found on page: 30
Page start=3090 | Status=200
  Reports found on page: 30
Page start=3120 | Status=200
  Reports found on page: 29
Page start=3150 | Status=200
  Reports found on page: 30
Page start=3180 | Status=200
  Reports found on page: 30
Page start=3210 | Status=200
  Reports found on page: 30
Page start=3240 | Status=200
  Reports found on page: 30
Page start=3270 | Status=200
  Reports found on page: 30
Page start=3300 | Status=200
  Reports found on page: 30
Page start=3330 | Status=200
  Reports found on page: 30
Page start=3360 | Status=200
  Reports found on page: 30
Page start=3390 | Status=200
  Reports found on page: 30
Page start=3420 | Status=200
  Reports found on page: 30
Page start=3450 | Status=200
  Reports found on page: 30
Page start=3480 | Status=200
  Reports found on page: 30
Page start=3510 | Status=200
  Reports found on page: 30
Page start=3540 | Status=200
  Reports found on page: 30
Page start=3570 | Status=200
  Reports found on page: 30
Page start=3600 | Status=200
  Reports found on page: 30
Page start=3630 | Status=200
  Reports found on page: 30
Page start=3660 | Status=200
  Reports found on page: 30
Page start=3690 | Status=200
  Reports found on page: 30
Page start=3720 | Status=200
  Reports found on page: 30
Page start=3750 | Status=200
  Reports found on page: 29
Page start=3780 | Status=200
  Reports found on page: 29
Page start=3810 | Status=200
  Reports found on page: 30
Page start=3840 | Status=200
  Reports found on page: 30
Page start=3870 | Status=200
  Reports found on page: 30
Page start=3900 | Status=200
  Reports found on page: 30
Page start=3930 | Status=200
  Reports found on page: 30
Page start=3960 | Status=200
  Reports found on page: 29
Page start=3990 | Status=200
  Reports found on page: 30
Page start=4020 | Status=200
  Reports found on page: 30
Page start=4050 | Status=200
  Reports found on page: 30
Page start=4080 | Status=200
  Reports found on page: 30
Page start=4110 | Status=200
  Reports found on page: 30
Page start=4140 | Status=200
  Reports found on page: 30
Page start=4170 | Status=200
  Reports found on page: 30
Page start=4200 | Status=200
  Reports found on page: 30
Page start=4230 | Status=200
  Reports found on page: 30
Page start=4260 | Status=200
  Reports found on page: 30
Page start=4290 | Status=200
  Reports found on page: 29
Page start=4320 | Status=200
  Reports found on page: 30
Page start=4350 | Status=200
  Reports found on page: 30
Page start=4380 | Status=200
  Reports found on page: 30
Page start=4410 | Status=200
  Reports found on page: 30
Page start=4440 | Status=200
  Reports found on page: 30
Page start=4470 | Status=200
  Reports found on page: 30
Page start=4500 | Status=200
  Reports found on page: 30
Page start=4530 | Status=200
  Reports found on page: 29
Page start=4560 | Status=200
  Reports found on page: 29
Page start=4590 | Status=200
  Reports found on page: 26
Page start=4620 | Status=200
  Reports found on page: 20
Page start=4650 | Status=200
  Reports found on page: 20
Page start=4680 | Status=200
  Reports found on page: 20
Page start=4710 | Status=200
  Reports found on page: 20
Page start=4740 | Status=200
  Reports found on page: 20
Page start=4770 | Status=200
  Reports found on page: 20
Page start=4800 | Status=200
  Reports found on page: 20
Page start=4830 | Status=200
  Reports found on page: 19
Page start=4860 | Status=200
  Reports found on page: 20
Page start=4890 | Status=200
  Reports found on page: 11
Page start=4920 | Status=200
  Reports found on page: 0
No more reports found.

============================================================
CRAWLING COMPLETE
============================================================
Total unique reports: 4795
Latest report: 2026-10-06 00:00:00
Earliest report: 2018-01-02 00:00:00

Report types:
report_type
situation report                                   4080
drought situation report                            303
situation report - [pdf]                             98
drought situation report summary - [pdf]             97
situation reports                                    47
situation summary report                             31
situation report (drought)                           20
dry weather situation report                         17
situation report summary                             15
situation report (dry weather)                       13
situation report - ditwah                             7
situation report (ditwah)                             7
drought report                                        5
weather forcast                                       5
weather forecast                                      5
situation report(drought)                             5
situation report (english)                            4
situation summary report (ditwah)                     3
dry weather condition _situation report               2
situation rep[ort summary                             2
daily situation report                                2
south -west monsoon situation summery report          2
south monsoon situation summery report                2
special situation report                              1
flood situation report -23-05-2018                    1
flood situation report -25-05-2018                    1
weekly situation report                               1
summary situation update - 25 september 2019          1
special advisory for strong wind and heavy rain       1
summary situation update - 24 september 2019          1
situation report 01                                   1
weather forecast (tamil language)                     1
summary situation update - 26 september 2019          1
special warning                                       1
heat index advisory                                   1
advisory for strong winds and rough sea               1
situation report on 2025.09.12 at 0900hrs             1
situation report (sinhala)                            1
current situation report                              1
ditwah - situation summary report                     1
situation report - (ditwah)                           1
situation repor                                       1
dry weather condition                                 1
ditwah situation summary report                       1
weather forcast -tamil                                1
situation  report                                     1
Name: count, dtype: int64

Reports by year:
report_date
2018.0     819
2019.0    1227
2020.0     405
2021.0     290
2022.0     482
2023.0     479
2024.0     387
2025.0     414
2026.0     291
Name: count, dtype: int64

In [312]:
# Inspect DMC report types by year
# This cell only analyzes the metadata index.
# It does NOT download any PDFs.

type_by_year = (
    all_reports_df
    .assign(
        year=all_reports_df["report_date"].dt.year,
        report_type_clean=(
            all_reports_df["report_type"]
            .astype("string")
            .str.strip()
            .str.lower()
        )
    )
    .groupby(
        ["year", "report_type_clean"],
        dropna=False
    )
    .size()
    .reset_index(name="count")
    .sort_values(
        ["year", "count"],
        ascending=[True, False]
    )
)

display(type_by_year)

print("\nNumber of distinct report types:", 
      type_by_year["report_type_clean"].nunique())

print("\nReport types containing 'flood':")
display(
    type_by_year[
        type_by_year["report_type_clean"].str.contains(
            "flood",
            na=False
        )
    ]
)

print("\nReport types containing 'landslide':")
display(
    type_by_year[
        type_by_year["report_type_clean"].str.contains(
            "landslide",
            na=False
        )
    ]
)

      year                         report_type_clean  count
7   2018.0                          situation report    552
8   2018.0                  situation report - [pdf]     98
3   2018.0  drought situation report summary - [pdf]     97
11  2018.0                         situation reports     37
10  2018.0                  situation report summary     13
..     ...                                       ...    ...
68  2026.0                         situation reports      1
71  2026.0                           weather forcast      1
72  2026.0                    weather forcast -tamil      1
73  2026.0         weather forecast (tamil language)      1
74     NaN                          situation report      1

[75 rows x 3 columns]

Number of distinct report types: 46

Report types containing 'flood':

     year                   report_type_clean  count
4  2018.0  flood situation report -23-05-2018      1
5  2018.0  flood situation report -25-05-2018      1

Report types containing 'landslide':

Empty DataFrame
Columns: [year, report_type_clean, count]
Index: []

In [313]:
# Identify potentially relevant DMC reports for flood/landslide extraction.
# No PDFs are downloaded in this cell.

dmc = all_reports_df.copy()

# Clean metadata
dmc["report_type_clean"] = (
    dmc["report_type"]
    .astype("string")
    .str.strip()
    .str.lower()
)

dmc["pdf_filename"] = (
    dmc["pdf_url"]
    .astype("string")
    .str.split("/")
    .str[-1]
    .str.lower()
)

dmc["year"] = dmc["report_date"].dt.year

# Restrict to years available for the historical study
dmc_historical = dmc[
    dmc["year"].between(2018, 2025)
].copy()

# Terms that indicate situation reports rather than weather/drought products
situation_terms = [
    "situation report",
    "situation reports",
    "situation summary report",
    "situation summary",
    "daily situation report",
    "summary situation update",
    "special situation report"
]

situation_mask = (
    dmc_historical["report_type_clean"]
    .str.contains(
        "|".join(situation_terms),
        regex=True,
        na=False
    )
)

# Explicit flood/landslide terms in report type or PDF filename
hazard_mask = (
    dmc_historical["report_type_clean"]
    .str.contains(
        "flood|landslide|land slide",
        regex=True,
        na=False
    )
    |
    dmc_historical["pdf_filename"]
    .str.contains(
        "flood|landslide|land_slide|land-slide",
        regex=True,
        na=False
    )
)

# Candidate set:
# - situation-report type, OR
# - explicitly named flood/landslide report
candidate_reports = dmc_historical[
    situation_mask | hazard_mask
].copy()

candidate_reports = (
    candidate_reports
    .drop_duplicates(subset=["pdf_url"])
    .sort_values(
        ["report_date", "report_time"],
        ascending=[False, False]
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("DMC HISTORICAL CANDIDATE REPORTS")
print("=" * 70)

print("\nHistorical reports available:", len(dmc_historical))
print("Potentially relevant reports:", len(candidate_reports))

print("\nCandidate reports by year:")
display(
    candidate_reports["year"]
    .value_counts()
    .sort_index()
)

print("\nCandidate reports by report type:")
display(
    candidate_reports["report_type_clean"]
    .value_counts()
)

print("\nExplicit flood/landslide matches:")
display(
    candidate_reports[
        candidate_reports["report_type_clean"].str.contains(
            "flood|landslide|land slide",
            regex=True,
            na=False
        )
        |
        candidate_reports["pdf_filename"].str.contains(
            "flood|landslide|land_slide|land-slide",
            regex=True,
            na=False
        )
    ][
        [
            "report_date",
            "report_time",
            "report_type",
            "pdf_filename"
        ]
    ].head(50)
)

======================================================================
DMC HISTORICAL CANDIDATE REPORTS
======================================================================

Historical reports available: 4503
Potentially relevant reports: 4479

Candidate reports by year:

year
2018.0     805
2019.0    1226
2020.0     404
2021.0     289
2022.0     482
2023.0     477
2024.0     384
2025.0     412
Name: count, dtype: int64

Candidate reports by report type:

report_type_clean
situation report                                3878
drought situation report                         281
situation report - [pdf]                          98
drought situation report summary - [pdf]          97
situation reports                                 46
situation report (drought)                        20
situation summary report                          19
situation report summary                          15
situation report(drought)                          5
situation report (english)                         4
dry weather condition _situation report            2
situation report (dry weather)                     1
daily situation report                             1
situation report (sinhala)                         1
summary situation update - 26 september 2019       1
summary situation update - 25 september 2019       1
dry weather situation report                       1
current situation report                           1
situation report on 2025.09.12 at 0900hrs          1
flood situation report -25-05-2018                 1
flood situation report -23-05-2018                 1
special situation report                           1
situation report 01                                1
weekly situation report                            1
summary situation update - 24 september 2019       1
Name: count, dtype: Int64

Explicit flood/landslide matches:

     report_date report_time                         report_type                                                 pdf_filename
1351  2022-11-08       19:00                    Situation Report  landslide_early_warning_report_at_1900hrs_on_2022__16679...
4260  2018-05-25       12:00  Flood Situation Report -25-05-2018  20180525_sri_lanka_situation_impact_report1200hours_fina...
4262  2018-05-23       10:00  Flood Situation Report -23-05-2018  20180523_sri_lanka_flood_situation_update1000hours_final...

In [314]:
# Select a small representative sample of DMC PDFs for extraction testing.
# No PDFs are downloaded in this cell.

dmc = all_reports_df.copy()

dmc["report_type_clean"] = (
    dmc["report_type"]
    .astype("string")
    .str.strip()
    .str.lower()
)

dmc["pdf_filename"] = (
    dmc["pdf_url"]
    .astype("string")
    .str.split("/")
    .str[-1]
)

dmc["pdf_filename_clean"] = (
    dmc["pdf_filename"]
    .astype("string")
    .str.lower()
)

dmc["year"] = dmc["report_date"].dt.year

# ---------------------------------------------------------
# 1. Explicit flood report
# ---------------------------------------------------------

flood_reports = dmc[
    dmc["report_type_clean"].str.contains(
        "flood",
        na=False
    )
    |
    dmc["pdf_filename_clean"].str.contains(
        "flood",
        na=False
    )
].copy()

# ---------------------------------------------------------
# 2. Explicit landslide report
# ---------------------------------------------------------

landslide_reports = dmc[
    dmc["report_type_clean"].str.contains(
        "landslide|land slide",
        regex=True,
        na=False
    )
    |
    dmc["pdf_filename_clean"].str.contains(
        "landslide|land_slide|land-slide",
        regex=True,
        na=False
    )
].copy()

# ---------------------------------------------------------
# 3. Generic situation reports
#    Exclude obvious drought/weather reports
# ---------------------------------------------------------

generic_situation = dmc[
    dmc["report_type_clean"].str.contains(
        "situation",
        na=False
    )
    &
    ~dmc["report_type_clean"].str.contains(
        "drought|dry weather|weather forecast|advisory|warning",
        regex=True,
        na=False
    )
].copy()

# ---------------------------------------------------------
# Select representative reports
# ---------------------------------------------------------

samples = []

# One explicit flood report from 2018
if len(flood_reports) > 0:
    samples.append(
        flood_reports
        .sort_values("report_date")
        .iloc[0]
    )

# One explicit landslide report
if len(landslide_reports) > 0:
    samples.append(
        landslide_reports
        .sort_values("report_date")
        .iloc[0]
    )

# One generic report from 2019
generic_2019 = generic_situation[
    generic_situation["year"] == 2019
]

if len(generic_2019) > 0:
    samples.append(
        generic_2019
        .sort_values("report_date")
        .iloc[0]
    )

# One generic report from 2020
generic_2020 = generic_situation[
    generic_situation["year"] == 2020
]

if len(generic_2020) > 0:
    samples.append(
        generic_2020
        .sort_values("report_date")
        .iloc[0]
    )

# One generic report from 2024
generic_2024 = generic_situation[
    generic_situation["year"] == 2024
]

if len(generic_2024) > 0:
    samples.append(
        generic_2024
        .sort_values("report_date")
        .iloc[0]
    )

# One generic report from 2025
generic_2025 = generic_situation[
    generic_situation["year"] == 2025
]

if len(generic_2025) > 0:
    samples.append(
        generic_2025
        .sort_values("report_date")
        .iloc[0]
    )

sample_reports = (
    pd.DataFrame(samples)
    .drop_duplicates(subset=["pdf_url"])
    .reset_index(drop=True)
)

print("=" * 70)
print("REPRESENTATIVE DMC PDFS FOR EXTRACTION TESTING")
print("=" * 70)

print("\nNumber of explicit flood-related reports:", len(flood_reports))
print("Number of explicit landslide-related reports:", len(landslide_reports))
print("Number of generic situation reports after exclusions:", len(generic_situation))

print("\nSelected sample PDFs:", len(sample_reports))

display(
    sample_reports[
        [
            "report_date",
            "report_time",
            "report_type",
            "pdf_filename",
            "pdf_url"
        ]
    ]
)

======================================================================
REPRESENTATIVE DMC PDFS FOR EXTRACTION TESTING
======================================================================

Number of explicit flood-related reports: 2
Number of explicit landslide-related reports: 1
Number of generic situation reports after exclusions: 4316

Selected sample PDFs: 6

  report_date report_time                         report_type                                                 pdf_filename                                                      pdf_url
0  2018-05-23       10:00  Flood Situation Report -23-05-2018  20180523_Sri_Lanka_Flood_Situation_Update1000hours_Final...  https://www.drrweb.dmc.gov.lk/images/dmcreports/20180523...
1  2022-11-08       19:00                    Situation Report  Landslide_Early_Warning_Report_at_1900hrs_on_2022__16679...  https://www.drrweb.dmc.gov.lk/images/dmcreports/Landslid...
2  2019-01-01       09:00                    Situation Report                    Situation_Report__on_2019__1546324706.pdf  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...
3  2020-01-01       18:00                    Situation Report                     Situation_Report_on_2020__1577882809.pdf  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...
4  2024-01-01       09:00                    Situation Report                     Situation_Report_on_2024__1704080044.pdf  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...
5  2025-01-01       09:00                    Situation Report                     Situation_Report_on_2025__1735713870.pdf  https://www.drrweb.dmc.gov.lk/images/dmcreports/Situatio...

In [315]:
# Download only the 6 representative PDFs for extraction testing.
# This is a small test batch — NOT the full DMC dataset.

from pathlib import Path
import requests
import time
import urllib3

urllib3.disable_warnings(
    urllib3.exceptions.InsecureRequestWarning
)

# Create test download directory
test_pdf_dir = (
    Path("../data/interim/disaster_records/dmc_test_pdfs")
    .resolve()
)

test_pdf_dir.mkdir(
    parents=True,
    exist_ok=True
)

session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0"
})

download_results = []

for i, row in sample_reports.iterrows():

    pdf_url = row["pdf_url"]

    filename = str(row["pdf_filename"])

    output_path = test_pdf_dir / filename

    print(f"\n[{i + 1}/{len(sample_reports)}]")
    print("Downloading:", filename)

    try:

        response = session.get(
            pdf_url,
            timeout=60,
            verify=False
        )

        content_type = response.headers.get(
            "Content-Type",
            ""
        )

        file_size = len(response.content)

        if response.status_code == 200 and file_size > 1000:

            output_path.write_bytes(
                response.content
            )

            status = "downloaded"

        else:

            status = "failed"

        download_results.append({
            "report_date": row["report_date"],
            "report_time": row["report_time"],
            "report_type": row["report_type"],
            "filename": filename,
            "status": status,
            "status_code": response.status_code,
            "content_type": content_type,
            "size_bytes": file_size,
            "path": str(output_path)
        })

        print("Status code:", response.status_code)
        print("Content-Type:", content_type)
        print("Size:", file_size, "bytes")
        print("Result:", status)

    except Exception as e:

        download_results.append({
            "report_date": row["report_date"],
            "report_time": row["report_time"],
            "report_type": row["report_type"],
            "filename": filename,
            "status": "error",
            "status_code": None,
            "content_type": None,
            "size_bytes": 0,
            "path": str(output_path),
            "error": repr(e)
        })

        print("ERROR:", repr(e))

    time.sleep(1)

download_results_df = pd.DataFrame(
    download_results
)

print("\n" + "=" * 70)
print("DOWNLOAD TEST COMPLETE")
print("=" * 70)

display(
    download_results_df[
        [
            "report_date",
            "report_type",
            "filename",
            "status",
            "status_code",
            "content_type",
            "size_bytes"
        ]
    ]
)

print("\nFiles saved to:")
print(test_pdf_dir)

[1/6]
Downloading: 20180523_Sri_Lanka_Flood_Situation_Update1000hours_Final-__1527064877.pdf
Status code: 200
Content-Type: application/pdf
Size: 1806579 bytes
Result: downloaded

[2/6]
Downloading: Landslide_Early_Warning_Report_at_1900hrs_on_2022__1667915214.pdf
Status code: 200
Content-Type: application/pdf
Size: 1103030 bytes
Result: downloaded

[3/6]
Downloading: Situation_Report__on_2019__1546324706.pdf
Status code: 200
Content-Type: application/pdf
Size: 464856 bytes
Result: downloaded

[4/6]
Downloading: Situation_Report_on_2020__1577882809.pdf
Status code: 200
Content-Type: application/pdf
Size: 797126 bytes
Result: downloaded

[5/6]
Downloading: Situation_Report_on_2024__1704080044.pdf
Status code: 200
Content-Type: application/pdf
Size: 295500 bytes
Result: downloaded

[6/6]
Downloading: Situation_Report_on_2025__1735713870.pdf
Status code: 200
Content-Type: application/pdf
Size: 281505 bytes
Result: downloaded

======================================================================
DOWNLOAD TEST COMPLETE
======================================================================

  report_date                         report_type                                                     filename      status  status_code     content_type  size_bytes
0  2018-05-23  Flood Situation Report -23-05-2018  20180523_Sri_Lanka_Flood_Situation_Update1000hours_Final...  downloaded          200  application/pdf     1806579
1  2022-11-08                    Situation Report  Landslide_Early_Warning_Report_at_1900hrs_on_2022__16679...  downloaded          200  application/pdf     1103030
2  2019-01-01                    Situation Report                    Situation_Report__on_2019__1546324706.pdf  downloaded          200  application/pdf      464856
3  2020-01-01                    Situation Report                     Situation_Report_on_2020__1577882809.pdf  downloaded          200  application/pdf      797126
4  2024-01-01                    Situation Report                     Situation_Report_on_2024__1704080044.pdf  downloaded          200  application/pdf      295500
5  2025-01-01                    Situation Report                     Situation_Report_on_2025__1735713870.pdf  downloaded          200  application/pdf      281505

Files saved to:
/Users/ohaseelanka/disaster_analytics_hub/data/interim/disaster_records/dmc_test_pdfs

In [316]:
# Test whether the downloaded DMC PDFs contain extractable text.
# This does NOT modify the PDF files.

from pathlib import Path
import fitz
import pandas as pd

pdf_files = sorted(
    test_pdf_dir.glob("*.pdf")
)

pdf_text_test = []

for pdf_path in pdf_files:

    try:

        document = fitz.open(pdf_path)

        page_count = document.page_count

        page_text_lengths = []
        total_text = ""

        for page in document:

            text = page.get_text("text")

            page_text_lengths.append(
                len(text.strip())
            )

            total_text += text

        document.close()

        total_characters = len(
            total_text.strip()
        )

        pages_with_text = sum(
            length > 20
            for length in page_text_lengths
        )

        pdf_text_test.append({
            "filename": pdf_path.name,
            "pages": page_count,
            "pages_with_text": pages_with_text,
            "total_text_characters": total_characters,
            "average_chars_per_page": round(
                total_characters / page_count,
                1
            ) if page_count else 0
        })

    except Exception as e:

        pdf_text_test.append({
            "filename": pdf_path.name,
            "pages": None,
            "pages_with_text": None,
            "total_text_characters": None,
            "average_chars_per_page": None,
            "error": repr(e)
        })

pdf_text_test_df = pd.DataFrame(
    pdf_text_test
)

print("=" * 70)
print("PDF TEXT EXTRACTION TEST")
print("=" * 70)

display(pdf_text_test_df)

ModuleNotFoundError: No module named 'fitz'

In [317]:
%pip install PyMuPDF

Collecting PyMuPDF
  Downloading pymupdf-1.28.2-cp310-abi3-macosx_11_0_arm64.whl.metadata (26 kB)
Downloading pymupdf-1.28.2-cp310-abi3-macosx_11_0_arm64.whl (23.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.9/23.9 MB 109.0 kB/s eta 0:00:000:0400:10m
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.28.2
Note: you may need to restart the kernel to use updated packages.

In [318]:
import fitz

print("PyMuPDF imported successfully.")
print("PyMuPDF version:", fitz.version[0])

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
PyMuPDF imported successfully.
PyMuPDF version: 1.28.2

In [319]:
# Test whether the downloaded DMC PDFs contain a usable text layer.
# This does not modify the PDF files.

import pymupdf
import pandas as pd

pdf_files = sorted(
    test_pdf_dir.glob("*.pdf")
)

pdf_text_test = []

for pdf_path in pdf_files:

    try:
        document = pymupdf.open(pdf_path)

        page_count = document.page_count

        page_text_lengths = []
        total_text = ""

        for page in document:
            text = page.get_text("text")

            page_text_lengths.append(
                len(text.strip())
            )

            total_text += text

        document.close()

        total_characters = len(
            total_text.strip()
        )

        pages_with_text = sum(
            length > 20
            for length in page_text_lengths
        )

        pdf_text_test.append({
            "filename": pdf_path.name,
            "pages": page_count,
            "pages_with_text": pages_with_text,
            "total_text_characters": total_characters,
            "average_chars_per_page": round(
                total_characters / page_count,
                1
            ) if page_count else 0
        })

    except Exception as e:

        pdf_text_test.append({
            "filename": pdf_path.name,
            "pages": None,
            "pages_with_text": None,
            "total_text_characters": None,
            "average_chars_per_page": None,
            "error": repr(e)
        })

pdf_text_test_df = pd.DataFrame(
    pdf_text_test
)

print("=" * 70)
print("DMC PDF TEXT EXTRACTION TEST")
print("=" * 70)

display(pdf_text_test_df)

======================================================================
DMC PDF TEXT EXTRACTION TEST
======================================================================

                                                      filename  pages  pages_with_text  total_text_characters  average_chars_per_page
0  20180523_Sri_Lanka_Flood_Situation_Update1000hours_Final...     16               10                  15116                   944.8
1  Landslide_Early_Warning_Report_at_1900hrs_on_2022__16679...      5                4                   2760                   552.0
2                    Situation_Report__on_2019__1546324706.pdf      2                2                   5686                  2843.0
3                     Situation_Report_on_2020__1577882809.pdf      1                1                   3390                  3390.0
4                     Situation_Report_on_2024__1704080044.pdf      2                2                   5263                  2631.5
5                     Situation_Report_on_2025__1735713870.pdf      1                1                   2752                  2752.0

In [320]:
# Inspect extracted text from the 2018 DMC flood situation report.
# This is only for understanding the PDF structure.

import pymupdf

flood_pdf = test_pdf_dir / (
    "20180523_Sri_Lanka_Flood_Situation_Update1000hours_Final-__1527064877.pdf"
)

document = pymupdf.open(flood_pdf)

print("=" * 80)
print("2018 DMC FLOOD SITUATION REPORT")
print("=" * 80)

print("Number of pages:", document.page_count)

for page_number, page in enumerate(document):

    text = page.get_text("text").strip()

    print("\n")
    print("=" * 80)
    print(f"PAGE {page_number + 1}")
    print("=" * 80)

    if text:
        print(text[:5000])
    else:
        print("[NO TEXT EXTRACTED FROM THIS PAGE]")

document.close()

================================================================================
2018 DMC FLOOD SITUATION REPORT
================================================================================
Number of pages: 16


================================================================================
PAGE 1
================================================================================
[NO TEXT EXTRACTED FROM THIS PAGE]


================================================================================
PAGE 2
================================================================================
2

CURRENT SITUATION
SITUATION SUMMARY
 A heavy rainfall was received across several parts of Sri Lanka between 20 and 21 May
2018, caused heavy rains and flash floods mainly in twelve districts, including Southern,
Western, North-Western and Sabaragamuwa Provinces.
 Early-warning  reached  to the affected people and  evacuations were done covering the
people who are at risk . Search & rescue teams were pre-positioned  and boats were kept
as ready to launch in the affected districts. 557 military and police officials were mobilized
immediately for search and rescue operations while 5,826 military and police personnel
have been organized as stand-by teams for immediate deployment.
 84,943  people (18,542 families) have been affected (the Disaster Situation Report , DMC &
National Disaster Relief Services Centre (NDRSC) at 1000 hours on 23rd of May 2018).
NDRSC has provided 14.7 million cash allocations to the 12 District Secretaries to address
the immediate needs of the affected populations.
 As per the immediate rapid impact analysis estimates, 23,000 people need emergency
flood relief and early recovery assistance.
 River water levels at many stations are  gradually decreasing, as the rainfall recorded in the
catchments during the last 24 hours ending 0830 hours is lower compared to the rainfall
received in 20th and 21st May 2018.

As per the Department of Meteorology, few places in Puttlam district received the highest rainfall received
within the 24 hours ending at 0830 hours on 21 May 2018.  Rainfall stations in Anamaduwa, Adigama and
Kamalsram in Puttalam recorded rains above 300mm while, Anamaduwa received  the highest rainfall of
353.8 mm of rain in 24 hours to early 21 May 2018.  Moreover, many places received  more than 100 mm of
rain in 5 hours during 20 May, including Ratnapura which reported 222.5 mm and Eheliyagoda
(Sabaragamuwa Province) with 201.5 mm.
Department of Meteorology highlighted last 18—24 hours rainfall observed in main stations ended on morn-
ing hours of 23nd May 2018 showing reduction of rainfall in many areas; in Trincomalee 52.6mm, in Battica-
loa 43.5mm, in Badulla 29.5mm, Vavuniya 28.5mm. The highest rainfall recorded was around 72.7mm in
Oddusudan in Mullative District. However, based on received rainfall since 22nd May 2018, rainfall has been
reduced in catchment areas and affected areas and flood waters are receding, allowing response and relief
services to be more effective.
Minister of Disaster Management, Hon Duminda Dissanayake has visited Kalutara area and State Minister of
Disaster Management, Hon Palitha Range Bandara  has visited Puttalam area together with Ministry and Dis-
trict officials to provide effective relief to affected people. Hon Minister, has left his office to Ratnapura to-
day to observe the affected areas and provide immediate needs.
Dam leak was identified in Pulachchikulam tank in Puttalam District and settled with sand bags. Vijaya Katu-
potha tank and Waama-Eliya tank has been damaged due to massive rainfall during 21st May. A stability issue
has been identified in the Kaduwela main bridge and Kaduwela-Biyagama road is temporarily closed.


================================================================================
PAGE 3
================================================================================
3

As a result of  severe rains, 84,943 people (18,542 families)
have been affected (the Disaster Situation Report , National
Disaster Relief Services Centre (NDRSC) at 1000 hours on
23rd  of May 2018). People at flood risk have been evacuat-
ed to safe locations and the total number of welfare cen-
tres. Approximately, 7,526 families have been evacuated
into 194 welfare centres due to flood and landslide risks. As
of now 10 deaths were reported to the Disaster Manage-
ment Centre.
Department of Irrigation has indicated that several major
river levels are decreasing as of 23 May 2018, at 0630 hours
which were at flood levels earlier.
However, the recorded rainfall was minimal in the major
river catchment areas during past 24 hours ending from 8
30 hours of 22 May 2018. Therefore, the flood levels will
fade away gradually.


FIGURE 01: Heavy rainfall received 24
hours ending at 0830 hours on 21 May 2018
FIGURE 02: River water level, 0900 hours 23 May 2018
Source: Department of Irrigation

River gauges in Nilwala, Gin, Kalu, Kelani, Attanagalu-Oya, Ma-Oya, Mahaweli showing normal water levels
Source: Department of Meteorology
0
2
4
6
8
10
12
14
16
18
20
Norwood
Kitulgala
Deraniyagala
Holombuwa
Glencourse
Hanwella
N' Street
Ratnapura
Ellagawa
Millakanda
Putupaula
Dunamale
Kelani
Kalu
Attanagalu
 Oya
Water Level (Feets)
Minor Flood Level
Major Flood Level
Current level


================================================================================
PAGE 4
================================================================================
4


FLOOD STATUS AND FORECASTED IMPACT
FIGURE 03: Affected Districts and proposed prioritization for  response,
22 May 2018 16 00 hours
ESTIMATED PRIORTITY 01 using rapid impact assessment approach
 Estimated 23, 470 People Severely affected and needs
emergency assistance
 Estimated Number of households at high risk— 447 houses


================================================================================
PAGE 5
================================================================================
5

FLOOD RESPONSE  AND RESCUE OPERATIONS
Table 01: Details of Tri Forces allocation to the emergency response
(Colombo, Matara, Galle, Kalutara, Ratnapura and Kegalle)
Deployed Forces:

Stand by Forces:

Resources allocation for the Police
SN
Tri Force
Officers
Others
Total
1
Navy
10
158
168
2
Army
23
366
389
3
Air force



4
Police



Total
33
524
557
SN
Tri Force
Officers
Others
Total
1
Navy
2
171
173
2
Army
179
5204
5383
3
Air force
9
261
270
4
Police
-
-

Total
190
5636
5826
S
N
District
Engine Boat
Angul
Engine
1
Ratnapura
10
08
01
2
Kalutara
11
10
01
3
Galle
06
03

4
Badulla
02
02

5
Gampaha
05
05
02
6
Matara
03
05

7
Colombo
13
06
01
8
Kegalle
01
01

9
Puttlam
02


10
Hambanthota
01


11
Kurunegala
05
07

Total
59
47
05


================================================================================
PAGE 6
================================================================================
[NO TEXT EXTRACTED FROM THIS PAGE]


================================================================================
PAGE 7
================================================================================
7

I.
Summary of the Situation
II. Forecast by Department of Meteorology
III. Water Level in Major Rivers (Dept of Irrigation)
IV. Landslide Warning
List of Annexes


================================================================================
PAGE 8
================================================================================
[NO TEXT EXTRACTED FROM THIS PAGE]


================================================================================
PAGE 9
================================================================================
[NO TEXT EXTRACTED FROM THIS PAGE]


================================================================================
PAGE 10
================================================================================
[NO TEXT EXTRACTED FROM THIS PAGE]


================================================================================
PAGE 11
================================================================================
[NO TEXT EXTRACTED FROM THIS PAGE]


================================================================================
PAGE 12
================================================================================
Page 1 of 5

Landslide Early Warning



From 16:00 hrs on 22.05.2018 to 16.00 hrs on 23.05.2018
නායයෑම් පිළිබඳ පුර්ව අනතුරු ඇඟවීම

22.05.2018 දින.16.00, සිට 23.05.2018 දින 16.00.දක්වා
kz;rhpT Kd;ndr;rhpf;if



22.05.2018 kzp 16.00 ,ypUe;J 23.05.2018 kzp 16.00 tiu

NBRO
NATIONAL BUILDING RESEARCH ORGANISATION
ජාතික ග ාඩනැගිලි පර්ගේෂණ සංවිධානය
Njrpa fl;bl Muha;r;rp epWtdk;
No. 99/1, Jawatta Road, Colombo 05
අංක. 99/1, ජාවත්ත පාර, ගකාළඹ 05
,y.99/1> [htj;ij tPjp> nfhOk;G 05

Tele./දු.ක./njh.Ng-0112588946                                                   Fax/ෆැක්්
/njh.e-0112589943

Warning level 1:                Watch
Color Code:                        Yellow
අදියර 1:                                විමසිලිමත්
වර්ණ ගක්තය:
     කහ
vr;rhpf;if kl;lk; 1:    mtjhdpg;G
th;z FwpaPL:         kQ;rs;
Since the rainfall within the past 24 hours has exceeded 75mm, if the rain continues, be
watchful on the possibility of landslides, slope failures, rock falls, cutting failures and
ground subsidence.

පසු ගිය පැය 24 තුල වර්ෂාපතනය 75mm ඉක්මවා ඇති බැවින්, වර්ෂාව
තවදුරටත් පවතී නම් නායයෑගම්, බෑවුම් කඩා වැටීගම්,  ල් ගපරළිගම්, ප්

කණ්ඩි
 කඩා වැටීගම් සහ  ගපාගළාව ගිලා බැසීගම් අවදානම පිළිබදව
විමසිලිමත් වන්න.

fle;j 24 kzpj;jpahyq;fspy; kiotPo;r;rp 75 kp.kP fis NktpAs;sjdhy;- kio
njhlUkhapd; kz;rhpT> rha;T ,be;J tpOif> ghiw tpOif> epyntl;Lrha;T
,be;J tpOif kw;Wk; jiu cs;spwf;fk; vd;gtw;wpd; rhj;jpaq;fSf;fhd
mtjhdpg;Gld; ,Uf;fTk;.


Warning level 2:
  Alert
Color Code:
               Amber
අදියර 2:                              අවධාන
වර්ණ ගක්තය:                  ඇම්බර්
vr;rhpf;if kl;lk; 2:   vr;rhpf;if
th;z FwpaPL:        nrk;kQ;rs;
Since the rainfall within the past 24 hours has exceeded 100 mm, if the rains continue,
be on alert on the possibility of landslides, slope failures, rock falls, cut failures and
ground subsidence, being ready to evacuate to a safe location if the need arises.

පසුගිය පැය 24 තුළ වර්ෂාපතනය 100 mm ඉක්මවා ඇති බැවින්, වර්ෂාව
තවදුරටත් පවතී නම් නායයෑම්, බෑවුම් කඩා වැටීම්,  ල් ගපරළීම්, ගපාගළාව
ගිලා බැසීගම් සහ ප්
 කණ්ඩි
 කඩා වැටීම් අවධානම පිළිබද අවධානගයන්
සිට අවශ්‍ය වුවගහාත් ආරක්ෂාකාරී තැනකට යාමට සුදානම් වන්න.

fle;j 24 kzpj;jpahyq;fspy; kiotPo;r;rp 100 kp.kP fis NktpAs;sjdhy;- kio
njhlUkhapd; kz;rhpT> rha;T ,be;J-tpOif> ghiw-tpOif> epyntl;Lrha;T
,be;J-tpOif kw;Wk; jiu-cs;spwf;fk; vd;gtw;wpd; rhj;jpaq;fisapl;L
vr;rhpf;ifAld;- NjitNaw;gbd; ghJfhg;ghd ,lq;fSf;F ntspNaWk; jahh;
epiyapy; ,Uf;fTk;.

Warning level 3:
    Evacuation
Color Code:
                 Red
අදියර 3:                                ඉවත්වීම

වර්ණ ගක්තය:                    රතු
vr;rhpf;if kl;lk; 3:    ntspNaWif
th;z FwpaPL:         rptg;G
Since the rainfall within the past 24 hours has exceeded 150 mm, if the rains continue,
evacuate to a safe location to avoid the risk of landslides, slope failures, rock falls,
cutting failures and ground subsidence.

පසුගිය පැය 24 තුළ වර්ෂාපතනය 150mm ඉක්මවා ඇති බැවින්, වර්ෂාව
තවදුරටත් පවතී නම් නායයෑම්, බෑවුම් කඩා වැටීම්,  ල් ගපරළීම්, ගපාගළාව
ගිලා බැසීම් සහ ප්
 කණ්ඩි
 කඩා වැටීගම් අනතුරු වලින් වැලකීමට
ආරක්ි
ත ්
ථානයකට යන්න.

fle;j 24 kzpj;jpahyq;fspy; kiotPo;r;rp 150 kp.kP fis NktpAs;sjdhy;- kio
njhlUkhapd; kz;rhpT> rha;T ,be;J tpOif> ghiw tpOif> epyntl;Lrha;T
,be;J
tpOif
kw;Wk;
jiu
cs;spwf;fk;
vd;gtw;wpd;
mghaq;fis
jtph;g;gjw;fhf ghJfhg;ghd gFjpfSf;F ntspNawTk;.


================================================================================
PAGE 13
================================================================================
Page 2 of 5

Locations of potential risk
නායයෑමේ අවදානම පැවතිය හැකි ප්‍රමේශ                                 fdjpahd mghaKs;s ,lq;fs;

District
Divisional Secretariat Divisions and Locations
Level 1
(Yellow)
Level 2
(Amber)
Level 3
(Red)
Areas and places which
need special attention

Rathnapura




Ratnapura↓
Elapatha↓
Kuruwita↓
Ehaliyagoda↓
Ayaganma
Kahawatta
Kalawana
Kiriella
Kolona
Nivitigala
Pelmadulla
Balangoda
Godakawela
Imbulpe
Opanayaka
Weligepola

Divisional
secretariat divisions
and surrounding
areas.












All mountainous areas,
manmade cut slopes and
roads within the relevant
DS divisions

අදාල ප්‍රාගීය ය ගල්කම්
ගකාට්ඨාශ්‍ තුල පිහිටි
කඳුකර බෑවුම් හා ඒ
ආශ්‍රිත ප්‍රගීශ්‍ තුල පිහිටි
නිර්ි
ත

gpuNjr
nrayf
gphptpDs;shd
rfy
kiyg;ghq;fhd
gFjpfs;
kw;Wk; ntl;lg;gl;l epyr;
rha;Tfs;

Specially: All the landslide
susceptible areas previously
identified by NBRO.

විගේෂ:
ජාතික
ග ාඩනැගිලි පර්ගේෂණ
සංවිධානය
විසින්
නායයෑගම් අවදානමක්
ඇති ගලස පුර්වගයන්
හදුනාග න ඇති ප්‍රගීශ්‍

tpNrlkhf: NBROtpdhy;
Kd;dh;
milahsg;gLj;jg;gl;l
kz;rhpTf;fhd
VJepiyAs;s rfy
gpuNjrq;fs;.
Kegalle
Warakapola

Divisional
secretariat
division and
surrounding
areas.

Bulathkopitiya↓
Dehiovita↓
Deraniyagala↓
Ruwanwella↓
Aranayaka↓
Galigamuwa
Kellgalle
Mawanalle
Yatiyanthota
Rambukana

Divisional
secretariat divisions
and surrounding
areas.



Kandy
Thumpane

Divisional
secretariat
division and
Pasbage Korale
GangaIhala Korale
Udapalatha
Doluwa


================================================================================
PAGE 14
================================================================================
Page 3 of 5

surrounding
areas.

Divisional
secretariat divisions
and surrounding
areas.

Matale
Matale,
Rattota,
Ukkuwela

Divisional
secretariat
division and
surrounding
areas.



Nuwara Eliya

Ambagamuwa↓
Kothmale↓
Nuwara Eliya

Divisional
secretariat divisions
and surrounding
areas.



Badulla

Haldumulla
Divisional
secretariat
division and
surrounding
areas.


Kalutara

Palinda Nuwara↓
Agalawatta
Bulathsinhala
Ingiriya
Walalawita

Divisional
secretariat divisions
and surrounding
areas.




Galle

Elpitiya↓
Galle Four Gravest↓
Nagoda↓
Neluwa↓
Thawalama↓
Divisional
secretariat division
and surrounding
areas.


================================================================================
PAGE 15
================================================================================
Page 4 of 5


Kurunagala
Ibbagamuwa
Malwalapitiya
Mawathegama
Rideegama

Divisional
secretariat
divisions and
surrounding
areas.



Colombo

Seethawaka

Divisional
secretariat
division and
surrounding
areas.


Note:  ↑shifted one level up,  ↑↑shifted two levels up, ↓shifted one level down, ↓↓shifted two levels down.


විමේෂ සටහන: කරුණාකර ගමම නායයෑම් පිළිබඳ පූර්ව අනතුරු හැඟවීම් කාලසීමාව තුළ පහත කරුණු ගවත ඔගේ
අවධානය ගයාමු කරන්න.
1. පහත දැක්ගවන නායයෑම් පූර්ව ලක්ෂණ පිළිබඳ සැලකිලිමත් වන්න.

 ගපාළගේ ඇති වන ඉරි තැලීම්,  ැඹුරට හෑරුණු පැළුම් හා ගපාළගේ ගිලා බැසීම්
 ක්‍රමගයන් ඇලවී යන  ්
, විදුලි කණු, වැටවල් හා දුරකථන කුළුණු ආදිය
 ග ාඩනැගිලිවල ග බිම හා බිත්තිමත ඇතිවන පිපුරුම් හා ඒවාගේ ක්‍රි
ක වර්ධනය වීම්
 එක්වර ජල උල්පත් ඇතිවීම ගහෝ ගපර පැවති ජල උල්පත්ගබාරවීම, අවහිරවීම ගහෝ නැතිවීම

2. එවන් නායයාමක පූර්ව ලක්ෂණ දක්නට ලැගබන ප්‍රගීශ්‍ වලින් හැකි ඉක්මනින් ඉවත් වන්න.

3. ඊට අමතරව අනතුරට භාජනය වියහැකි යැයි අනුමාන කරන ප්‍රගීශ්‍ වල ිව
වත් වන පුී ලයින් වැි
 වශ්‍ගයන්
පරික්ෂාකාරී වියයුතු අතර දැි
 වර්ෂා තත්වය තවදුරටත් පැවතුනගහාත් සුරක්ි
ත ්
ථානයක් කරා ක්ෂණිකව
ඉවත්ව යාමට සූදානම්ව සිටිය යුතුය.
සැ.යු: ජාතික ග ාඩනැගිලි පර්ගේෂණ සංවිධානගයන් සහ ආපදා කළමනාකරණ මධය්
ථානගයන් ලැගබන වැි
දුර
උපගද්
 අනු මනය කරන්න.

Special Note: During this Landslide Early Warning period, please pay attention to the following:
1. Pay your attention to the following pre landslide signs,

 Development of cracks on the ground, deepened cracks and ground subsidence
 Slanting of trees, electrical posts, fences and telephone posts
 Cracks in the floors and walls of buildings which are built at slopes
 Sudden appearance of springs, emerging muddy water, blockage or disappearance of existing
springs
2. People should move immediately away from the areas where they noticed the above pre-landslide signs.


================================================================================
PAGE 16
================================================================================
Page 5 of 5

3. Furthermore, people living in landslide susceptible areas should be extra vigilant and should be ready to
move quickly to safe places if heavy rain continues.
Note: Communities are advised to follow the instructions given by National Building Research Organization and
Disaster Management Center.

tpNrl Fwpg;G: kz;rhpT Kd;ndr;rhpf;if fhyg;gFjpapy; gpd;tUtdtw;wpy; ftdk; vLf;fTk;
1. gpd;tUk; kz;rhpT Kd; mwpFwpfisapl;L ftdj;ij nrYj;jTk;.

 epyj;jpy; ntbg;G cUthFjy;> MokhFk; ntbg;Gfs; kw;Wk; jiu cs;spwf;fq;fs;.
 kuq;fs;>kpd; fk;gq;fs;> Ntypfs;> kw;Wk; njhiyNgrpf; fk;gq;fs; rha;tiljy;.
 rha;Tfspy; mike;Js;s fl;blq;fspd; jiukw;Wk; Rth;fspy; ntbg;Gfs; cUthFjy;.
 epyj;jpypUe;J jpBnud eP&w;Wfs;> Nrw;W ePh Njhd;Wjy; kw;Wk; jw;NghJs;s eP&w;Wfs;
jilg;gLjy; my;yJ ,y;yhJ NghFjy;.

2. kz;rhpTf;F Kd;duhd mwpFwpfis nfhz;l ,lq;fspypUe;J cldbahf kf;fs; mg;ghy; efu
Ntz;Lk;.

3. NkYk;> ghjpg;G VJepiyAs;s gFjpfspy; thOk; kf;fs; Nkyjpf tpopg;Gld; ,Uf;fNtz;Lk;
vd;gJld; fLk; kio njhUkhapd; tpiuthf ghJfhg;ghd ,lq;fSf;F efu Maj;jkhfTk;
,Uf;fNtz;Lk;.
Fwpg;G: jaTnra;J Njrpa fl;bl Muha;r;rp epWtdk; kw;Wk; mdh;j;j Kfhikj;Jt epiyak;
vd;gtw;wpd; mwpTWj;jy;fis gpd;gw;wTk;

    Issued by:                                                      Approved by:




Duty Officer                                                        (for) Director


Date and time issued:
2018/05/22 16.00 hrs.

Landslide Research and Risk Management Division
National Building Research Organisation

In [321]:
# Identify which pages of the 2018 flood report contain the most extractable text.
# This helps us locate the likely impact/data tables.

import pymupdf
import pandas as pd

document = pymupdf.open(flood_pdf)

page_info = []

for page_number, page in enumerate(document):

    text = page.get_text("text").strip()

    page_info.append({
        "page": page_number + 1,
        "characters": len(text),
        "lines": len(text.splitlines()) if text else 0,
        "has_text": len(text) > 20
    })

document.close()

page_info_df = pd.DataFrame(page_info)

print("=" * 70)
print("2018 FLOOD REPORT — PAGE TEXT SUMMARY")
print("=" * 70)

display(
    page_info_df.sort_values(
        "characters",
        ascending=False
    )
)

print("\nPages with substantial text:")
display(
    page_info_df[
        page_info_df["characters"] > 500
    ].sort_values("page")
)

======================================================================
2018 FLOOD REPORT — PAGE TEXT SUMMARY
======================================================================

    page  characters  lines  has_text
11    12        3455    108      True
1      2        3204     41      True
14    15        1830     67      True
12    13        1565    131      True
15    16        1521     38      True
2      3        1414     58      True
4      5         885    133      True
13    14         693     73      True
3      4         341     10      True
6      7         172      8      True
0      1           0      0     False
5      6           0      0     False
7      8           0      0     False
8      9           0      0     False
9     10           0      0     False
10    11           0      0     False

Pages with substantial text:

    page  characters  lines  has_text
1      2        3204     41      True
2      3        1414     58      True
4      5         885    133      True
11    12        3455    108      True
12    13        1565    131      True
13    14         693     73      True
14    15        1830     67      True
15    16        1521     38      True

In [322]:
# Inspect the most information-dense pages of the 2018 flood report.
# Pages 12–16 are shown separately so we can understand the table structure.

import pymupdf

document = pymupdf.open(flood_pdf)

pages_to_inspect = [12, 13, 14, 15, 16]

for page_number in pages_to_inspect:

    page = document[page_number - 1]

    text = page.get_text("text").strip()

    print("\n")
    print("=" * 90)
    print(f"PAGE {page_number}")
    print("=" * 90)

    print(text)

document.close()

==========================================================================================
PAGE 12
==========================================================================================
Page 1 of 5

Landslide Early Warning



From 16:00 hrs on 22.05.2018 to 16.00 hrs on 23.05.2018
නායයෑම් පිළිබඳ පුර්ව අනතුරු ඇඟවීම

22.05.2018 දින.16.00, සිට 23.05.2018 දින 16.00.දක්වා
kz;rhpT Kd;ndr;rhpf;if



22.05.2018 kzp 16.00 ,ypUe;J 23.05.2018 kzp 16.00 tiu

NBRO
NATIONAL BUILDING RESEARCH ORGANISATION
ජාතික ග ාඩනැගිලි පර්ගේෂණ සංවිධානය
Njrpa fl;bl Muha;r;rp epWtdk;
No. 99/1, Jawatta Road, Colombo 05
අංක. 99/1, ජාවත්ත පාර, ගකාළඹ 05
,y.99/1> [htj;ij tPjp> nfhOk;G 05

Tele./දු.ක./njh.Ng-0112588946                                                   Fax/ෆැක්්
/njh.e-0112589943

Warning level 1:                Watch
Color Code:                        Yellow
අදියර 1:                                විමසිලිමත්
වර්ණ ගක්තය:
     කහ
vr;rhpf;if kl;lk; 1:    mtjhdpg;G
th;z FwpaPL:         kQ;rs;
Since the rainfall within the past 24 hours has exceeded 75mm, if the rain continues, be
watchful on the possibility of landslides, slope failures, rock falls, cutting failures and
ground subsidence.

පසු ගිය පැය 24 තුල වර්ෂාපතනය 75mm ඉක්මවා ඇති බැවින්, වර්ෂාව
තවදුරටත් පවතී නම් නායයෑගම්, බෑවුම් කඩා වැටීගම්,  ල් ගපරළිගම්, ප්

කණ්ඩි
 කඩා වැටීගම් සහ  ගපාගළාව ගිලා බැසීගම් අවදානම පිළිබදව
විමසිලිමත් වන්න.

fle;j 24 kzpj;jpahyq;fspy; kiotPo;r;rp 75 kp.kP fis NktpAs;sjdhy;- kio
njhlUkhapd; kz;rhpT> rha;T ,be;J tpOif> ghiw tpOif> epyntl;Lrha;T
,be;J tpOif kw;Wk; jiu cs;spwf;fk; vd;gtw;wpd; rhj;jpaq;fSf;fhd
mtjhdpg;Gld; ,Uf;fTk;.


Warning level 2:
  Alert
Color Code:
               Amber
අදියර 2:                              අවධාන
වර්ණ ගක්තය:                  ඇම්බර්
vr;rhpf;if kl;lk; 2:   vr;rhpf;if
th;z FwpaPL:        nrk;kQ;rs;
Since the rainfall within the past 24 hours has exceeded 100 mm, if the rains continue,
be on alert on the possibility of landslides, slope failures, rock falls, cut failures and
ground subsidence, being ready to evacuate to a safe location if the need arises.

පසුගිය පැය 24 තුළ වර්ෂාපතනය 100 mm ඉක්මවා ඇති බැවින්, වර්ෂාව
තවදුරටත් පවතී නම් නායයෑම්, බෑවුම් කඩා වැටීම්,  ල් ගපරළීම්, ගපාගළාව
ගිලා බැසීගම් සහ ප්
 කණ්ඩි
 කඩා වැටීම් අවධානම පිළිබද අවධානගයන්
සිට අවශ්‍ය වුවගහාත් ආරක්ෂාකාරී තැනකට යාමට සුදානම් වන්න.

fle;j 24 kzpj;jpahyq;fspy; kiotPo;r;rp 100 kp.kP fis NktpAs;sjdhy;- kio
njhlUkhapd; kz;rhpT> rha;T ,be;J-tpOif> ghiw-tpOif> epyntl;Lrha;T
,be;J-tpOif kw;Wk; jiu-cs;spwf;fk; vd;gtw;wpd; rhj;jpaq;fisapl;L
vr;rhpf;ifAld;- NjitNaw;gbd; ghJfhg;ghd ,lq;fSf;F ntspNaWk; jahh;
epiyapy; ,Uf;fTk;.

Warning level 3:
    Evacuation
Color Code:
                 Red
අදියර 3:                                ඉවත්වීම

වර්ණ ගක්තය:                    රතු
vr;rhpf;if kl;lk; 3:    ntspNaWif
th;z FwpaPL:         rptg;G
Since the rainfall within the past 24 hours has exceeded 150 mm, if the rains continue,
evacuate to a safe location to avoid the risk of landslides, slope failures, rock falls,
cutting failures and ground subsidence.

පසුගිය පැය 24 තුළ වර්ෂාපතනය 150mm ඉක්මවා ඇති බැවින්, වර්ෂාව
තවදුරටත් පවතී නම් නායයෑම්, බෑවුම් කඩා වැටීම්,  ල් ගපරළීම්, ගපාගළාව
ගිලා බැසීම් සහ ප්
 කණ්ඩි
 කඩා වැටීගම් අනතුරු වලින් වැලකීමට
ආරක්ි
ත ්
ථානයකට යන්න.

fle;j 24 kzpj;jpahyq;fspy; kiotPo;r;rp 150 kp.kP fis NktpAs;sjdhy;- kio
njhlUkhapd; kz;rhpT> rha;T ,be;J tpOif> ghiw tpOif> epyntl;Lrha;T
,be;J
tpOif
kw;Wk;
jiu
cs;spwf;fk;
vd;gtw;wpd;
mghaq;fis
jtph;g;gjw;fhf ghJfhg;ghd gFjpfSf;F ntspNawTk;.


==========================================================================================
PAGE 13
==========================================================================================
Page 2 of 5

Locations of potential risk
නායයෑමේ අවදානම පැවතිය හැකි ප්‍රමේශ                                 fdjpahd mghaKs;s ,lq;fs;

District
Divisional Secretariat Divisions and Locations
Level 1
(Yellow)
Level 2
(Amber)
Level 3
(Red)
Areas and places which
need special attention

Rathnapura




Ratnapura↓
Elapatha↓
Kuruwita↓
Ehaliyagoda↓
Ayaganma
Kahawatta
Kalawana
Kiriella
Kolona
Nivitigala
Pelmadulla
Balangoda
Godakawela
Imbulpe
Opanayaka
Weligepola

Divisional
secretariat divisions
and surrounding
areas.












All mountainous areas,
manmade cut slopes and
roads within the relevant
DS divisions

අදාල ප්‍රාගීය ය ගල්කම්
ගකාට්ඨාශ්‍ තුල පිහිටි
කඳුකර බෑවුම් හා ඒ
ආශ්‍රිත ප්‍රගීශ්‍ තුල පිහිටි
නිර්ි
ත

gpuNjr
nrayf
gphptpDs;shd
rfy
kiyg;ghq;fhd
gFjpfs;
kw;Wk; ntl;lg;gl;l epyr;
rha;Tfs;

Specially: All the landslide
susceptible areas previously
identified by NBRO.

විගේෂ:
ජාතික
ග ාඩනැගිලි පර්ගේෂණ
සංවිධානය
විසින්
නායයෑගම් අවදානමක්
ඇති ගලස පුර්වගයන්
හදුනාග න ඇති ප්‍රගීශ්‍

tpNrlkhf: NBROtpdhy;
Kd;dh;
milahsg;gLj;jg;gl;l
kz;rhpTf;fhd
VJepiyAs;s rfy
gpuNjrq;fs;.
Kegalle
Warakapola

Divisional
secretariat
division and
surrounding
areas.

Bulathkopitiya↓
Dehiovita↓
Deraniyagala↓
Ruwanwella↓
Aranayaka↓
Galigamuwa
Kellgalle
Mawanalle
Yatiyanthota
Rambukana

Divisional
secretariat divisions
and surrounding
areas.



Kandy
Thumpane

Divisional
secretariat
division and
Pasbage Korale
GangaIhala Korale
Udapalatha
Doluwa


==========================================================================================
PAGE 14
==========================================================================================
Page 3 of 5

surrounding
areas.

Divisional
secretariat divisions
and surrounding
areas.

Matale
Matale,
Rattota,
Ukkuwela

Divisional
secretariat
division and
surrounding
areas.



Nuwara Eliya

Ambagamuwa↓
Kothmale↓
Nuwara Eliya

Divisional
secretariat divisions
and surrounding
areas.



Badulla

Haldumulla
Divisional
secretariat
division and
surrounding
areas.


Kalutara

Palinda Nuwara↓
Agalawatta
Bulathsinhala
Ingiriya
Walalawita

Divisional
secretariat divisions
and surrounding
areas.




Galle

Elpitiya↓
Galle Four Gravest↓
Nagoda↓
Neluwa↓
Thawalama↓
Divisional
secretariat division
and surrounding
areas.


==========================================================================================
PAGE 15
==========================================================================================
Page 4 of 5


Kurunagala
Ibbagamuwa
Malwalapitiya
Mawathegama
Rideegama

Divisional
secretariat
divisions and
surrounding
areas.



Colombo

Seethawaka

Divisional
secretariat
division and
surrounding
areas.


Note:  ↑shifted one level up,  ↑↑shifted two levels up, ↓shifted one level down, ↓↓shifted two levels down.


විමේෂ සටහන: කරුණාකර ගමම නායයෑම් පිළිබඳ පූර්ව අනතුරු හැඟවීම් කාලසීමාව තුළ පහත කරුණු ගවත ඔගේ
අවධානය ගයාමු කරන්න.
1. පහත දැක්ගවන නායයෑම් පූර්ව ලක්ෂණ පිළිබඳ සැලකිලිමත් වන්න.

 ගපාළගේ ඇති වන ඉරි තැලීම්,  ැඹුරට හෑරුණු පැළුම් හා ගපාළගේ ගිලා බැසීම්
 ක්‍රමගයන් ඇලවී යන  ්
, විදුලි කණු, වැටවල් හා දුරකථන කුළුණු ආදිය
 ග ාඩනැගිලිවල ග බිම හා බිත්තිමත ඇතිවන පිපුරුම් හා ඒවාගේ ක්‍රි
ක වර්ධනය වීම්
 එක්වර ජල උල්පත් ඇතිවීම ගහෝ ගපර පැවති ජල උල්පත්ගබාරවීම, අවහිරවීම ගහෝ නැතිවීම

2. එවන් නායයාමක පූර්ව ලක්ෂණ දක්නට ලැගබන ප්‍රගීශ්‍ වලින් හැකි ඉක්මනින් ඉවත් වන්න.

3. ඊට අමතරව අනතුරට භාජනය වියහැකි යැයි අනුමාන කරන ප්‍රගීශ්‍ වල ිව
වත් වන පුී ලයින් වැි
 වශ්‍ගයන්
පරික්ෂාකාරී වියයුතු අතර දැි
 වර්ෂා තත්වය තවදුරටත් පැවතුනගහාත් සුරක්ි
ත ්
ථානයක් කරා ක්ෂණිකව
ඉවත්ව යාමට සූදානම්ව සිටිය යුතුය.
සැ.යු: ජාතික ග ාඩනැගිලි පර්ගේෂණ සංවිධානගයන් සහ ආපදා කළමනාකරණ මධය්
ථානගයන් ලැගබන වැි
දුර
උපගද්
 අනු මනය කරන්න.

Special Note: During this Landslide Early Warning period, please pay attention to the following:
1. Pay your attention to the following pre landslide signs,

 Development of cracks on the ground, deepened cracks and ground subsidence
 Slanting of trees, electrical posts, fences and telephone posts
 Cracks in the floors and walls of buildings which are built at slopes
 Sudden appearance of springs, emerging muddy water, blockage or disappearance of existing
springs
2. People should move immediately away from the areas where they noticed the above pre-landslide signs.


==========================================================================================
PAGE 16
==========================================================================================
Page 5 of 5

3. Furthermore, people living in landslide susceptible areas should be extra vigilant and should be ready to
move quickly to safe places if heavy rain continues.
Note: Communities are advised to follow the instructions given by National Building Research Organization and
Disaster Management Center.

tpNrl Fwpg;G: kz;rhpT Kd;ndr;rhpf;if fhyg;gFjpapy; gpd;tUtdtw;wpy; ftdk; vLf;fTk;
1. gpd;tUk; kz;rhpT Kd; mwpFwpfisapl;L ftdj;ij nrYj;jTk;.

 epyj;jpy; ntbg;G cUthFjy;> MokhFk; ntbg;Gfs; kw;Wk; jiu cs;spwf;fq;fs;.
 kuq;fs;>kpd; fk;gq;fs;> Ntypfs;> kw;Wk; njhiyNgrpf; fk;gq;fs; rha;tiljy;.
 rha;Tfspy; mike;Js;s fl;blq;fspd; jiukw;Wk; Rth;fspy; ntbg;Gfs; cUthFjy;.
 epyj;jpypUe;J jpBnud eP&w;Wfs;> Nrw;W ePh Njhd;Wjy; kw;Wk; jw;NghJs;s eP&w;Wfs;
jilg;gLjy; my;yJ ,y;yhJ NghFjy;.

2. kz;rhpTf;F Kd;duhd mwpFwpfis nfhz;l ,lq;fspypUe;J cldbahf kf;fs; mg;ghy; efu
Ntz;Lk;.

3. NkYk;> ghjpg;G VJepiyAs;s gFjpfspy; thOk; kf;fs; Nkyjpf tpopg;Gld; ,Uf;fNtz;Lk;
vd;gJld; fLk; kio njhUkhapd; tpiuthf ghJfhg;ghd ,lq;fSf;F efu Maj;jkhfTk;
,Uf;fNtz;Lk;.
Fwpg;G: jaTnra;J Njrpa fl;bl Muha;r;rp epWtdk; kw;Wk; mdh;j;j Kfhikj;Jt epiyak;
vd;gtw;wpd; mwpTWj;jy;fis gpd;gw;wTk;

    Issued by:                                                      Approved by:




Duty Officer                                                        (for) Director


Date and time issued:
2018/05/22 16.00 hrs.

Landslide Research and Risk Management Division
National Building Research Organisation

In [323]:
# Search the 2018 flood report for pages containing impact-related information.
# This helps us locate the actual historical impact tables.

import pymupdf
import pandas as pd

document = pymupdf.open(flood_pdf)

keywords = [
    "affected",
    "famil",
    "people",
    "death",
    "injur",
    "missing",
    "house",
    "damaged",
    "destroyed",
    "evacuat",
    "relocat",
    "district",
    "division",
    "DS Division"
]

matches = []

for page_number, page in enumerate(document):

    text = page.get_text("text")

    text_lower = text.lower()

    matched_keywords = [
        keyword
        for keyword in keywords
        if keyword.lower() in text_lower
    ]

    if matched_keywords:

        matches.append({
            "page": page_number + 1,
            "matched_keywords": ", ".join(matched_keywords),
            "characters": len(text.strip())
        })

document.close()

matches_df = pd.DataFrame(matches)

print("=" * 80)
print("IMPACT-RELATED CONTENT FOUND IN 2018 FLOOD REPORT")
print("=" * 80)

display(matches_df)

================================================================================
IMPACT-RELATED CONTENT FOUND IN 2018 FLOOD REPORT
================================================================================

   page                                     matched_keywords  characters
0     2  affected, famil, people, damaged, evacuat, district        3204
1     3              affected, famil, people, death, evacuat        1414
2     4                    affected, people, house, district         341
3     5                                             district         885
4    12                                              evacuat        3455
5    13                      district, division, DS Division        1565
6    14                                             division         693
7    15                                     people, division        1830
8    16                                     people, division        1521

In [324]:
# Inspect the DS/district-level pages of the 2018 flood report.
# We limit the displayed text so the notebook output remains manageable.

import pymupdf

document = pymupdf.open(flood_pdf)

for page_number in [13, 14, 15, 16]:

    page = document[page_number - 1]

    text = page.get_text("text").strip()

    print("\n")
    print("=" * 90)
    print(f"PAGE {page_number}")
    print("=" * 90)

    print(text[:2500])

    if len(text) > 2500:
        print("\n...[remaining text omitted]...")

document.close()

==========================================================================================
PAGE 13
==========================================================================================
Page 2 of 5

Locations of potential risk
නායයෑමේ අවදානම පැවතිය හැකි ප්‍රමේශ                                 fdjpahd mghaKs;s ,lq;fs;

District
Divisional Secretariat Divisions and Locations
Level 1
(Yellow)
Level 2
(Amber)
Level 3
(Red)
Areas and places which
need special attention

Rathnapura




Ratnapura↓
Elapatha↓
Kuruwita↓
Ehaliyagoda↓
Ayaganma
Kahawatta
Kalawana
Kiriella
Kolona
Nivitigala
Pelmadulla
Balangoda
Godakawela
Imbulpe
Opanayaka
Weligepola

Divisional
secretariat divisions
and surrounding
areas.












All mountainous areas,
manmade cut slopes and
roads within the relevant
DS divisions

අදාල ප්‍රාගීය ය ගල්කම්
ගකාට්ඨාශ්‍ තුල පිහිටි
කඳුකර බෑවුම් හා ඒ
ආශ්‍රිත ප්‍රගීශ්‍ තුල පිහිටි
නිර්ි
ත

gpuNjr
nrayf
gphptpDs;shd
rfy
kiyg;ghq;fhd
gFjpfs;
kw;Wk; ntl;lg;gl;l epyr;
rha;Tfs;

Specially: All the landslide
susceptible areas previously
identified by NBRO.

විගේෂ:
ජාතික
ග ාඩනැගිලි පර්ගේෂණ
සංවිධානය
විසින්
නායයෑගම් අවදානමක්
ඇති ගලස පුර්වගයන්
හදුනාග න ඇති ප්‍රගීශ්‍

tpNrlkhf: NBROtpdhy;
Kd;dh;
milahsg;gLj;jg;gl;l
kz;rhpTf;fhd
VJepiyAs;s rfy
gpuNjrq;fs;.
Kegalle
Warakapola

Divisional
secretariat
division and
surrounding
areas.

Bulathkopitiya↓
Dehiovita↓
Deraniyagala↓
Ruwanwella↓
Aranayaka↓
Galigamuwa
Kellgalle
Mawanalle
Yatiyanthota
Rambukana

Divisional
secretariat divisions
and surrounding
areas.



Kandy
Thumpane

Divisional
secretariat
division and
Pasbage Korale
GangaIhala Korale
Udapalatha
Doluwa


==========================================================================================
PAGE 14
==========================================================================================
Page 3 of 5

surrounding
areas.

Divisional
secretariat divisions
and surrounding
areas.

Matale
Matale,
Rattota,
Ukkuwela

Divisional
secretariat
division and
surrounding
areas.



Nuwara Eliya

Ambagamuwa↓
Kothmale↓
Nuwara Eliya

Divisional
secretariat divisions
and surrounding
areas.



Badulla

Haldumulla
Divisional
secretariat
division and
surrounding
areas.


Kalutara

Palinda Nuwara↓
Agalawatta
Bulathsinhala
Ingiriya
Walalawita

Divisional
secretariat divisions
and surrounding
areas.




Galle

Elpitiya↓
Galle Four Gravest↓
Nagoda↓
Neluwa↓
Thawalama↓
Divisional
secretariat division
and surrounding
areas.


==========================================================================================
PAGE 15
==========================================================================================
Page 4 of 5


Kurunagala
Ibbagamuwa
Malwalapitiya
Mawathegama
Rideegama

Divisional
secretariat
divisions and
surrounding
areas.



Colombo

Seethawaka

Divisional
secretariat
division and
surrounding
areas.


Note:  ↑shifted one level up,  ↑↑shifted two levels up, ↓shifted one level down, ↓↓shifted two levels down.


විමේෂ සටහන: කරුණාකර ගමම නායයෑම් පිළිබඳ පූර්ව අනතුරු හැඟවීම් කාලසීමාව තුළ පහත කරුණු ගවත ඔගේ
අවධානය ගයාමු කරන්න.
1. පහත දැක්ගවන නායයෑම් පූර්ව ලක්ෂණ පිළිබඳ සැලකිලිමත් වන්න.

 ගපාළගේ ඇති වන ඉරි තැලීම්,  ැඹුරට හෑරුණු පැළුම් හා ගපාළගේ ගිලා බැසීම්
 ක්‍රමගයන් ඇලවී යන  ්
, විදුලි කණු, වැටවල් හා දුරකථන කුළුණු ආදිය
 ග ාඩනැගිලිවල ග බිම හා බිත්තිමත ඇතිවන පිපුරුම් හා ඒවාගේ ක්‍රි
ක වර්ධනය වීම්
 එක්වර ජල උල්පත් ඇතිවීම ගහෝ ගපර පැවති ජල උල්පත්ගබාරවීම, අවහිරවීම ගහෝ නැතිවීම

2. එවන් නායයාමක පූර්ව ලක්ෂණ දක්නට ලැගබන ප්‍රගීශ්‍ වලින් හැකි ඉක්මනින් ඉවත් වන්න.

3. ඊට අමතරව අනතුරට භාජනය වියහැකි යැයි අනුමාන කරන ප්‍රගීශ්‍ වල ිව
වත් වන පුී ලයින් වැි
 වශ්‍ගයන්
පරික්ෂාකාරී වියයුතු අතර දැි
 වර්ෂා තත්වය තවදුරටත් පැවතුනගහාත් සුරක්ි
ත ්
ථානයක් කරා ක්ෂණිකව
ඉවත්ව යාමට සූදානම්ව සිටිය යුතුය.
සැ.යු: ජාතික ග ාඩනැගිලි පර්ගේෂණ සංවිධානගයන් සහ ආපදා කළමනාකරණ මධය්
ථානගයන් ලැගබන වැි
දුර
උපගද්
 අනු මනය කරන්න.

Special Note: During this Landslide Early Warning period, please pay attention to the following:
1. Pay your attention to the following pre landslide signs,

 Development of cracks on the ground, deepened cracks and ground subsidence
 Slanting of trees, electrical posts, fences and telephone posts
 Cracks in the floors and walls of buildings which are built at slopes
 Sudden appearance of springs, emerging muddy water, blockage or disappearance of existing
springs
2. People should move immediately away from the areas where they noticed the above pre-landslide signs.


==========================================================================================
PAGE 16
==========================================================================================
Page 5 of 5

3. Furthermore, people living in landslide susceptible areas should be extra vigilant and should be ready to
move quickly to safe places if heavy rain continues.
Note: Communities are advised to follow the instructions given by National Building Research Organization and
Disaster Management Center.

tpNrl Fwpg;G: kz;rhpT Kd;ndr;rhpf;if fhyg;gFjpapy; gpd;tUtdtw;wpy; ftdk; vLf;fTk;
1. gpd;tUk; kz;rhpT Kd; mwpFwpfisapl;L ftdj;ij nrYj;jTk;.

 epyj;jpy; ntbg;G cUthFjy;> MokhFk; ntbg;Gfs; kw;Wk; jiu cs;spwf;fq;fs;.
 kuq;fs;>kpd; fk;gq;fs;> Ntypfs;> kw;Wk; njhiyNgrpf; fk;gq;fs; rha;tiljy;.
 rha;Tfspy; mike;Js;s fl;blq;fspd; jiukw;Wk; Rth;fspy; ntbg;Gfs; cUthFjy;.
 epyj;jpypUe;J jpBnud eP&w;Wfs;> Nrw;W ePh Njhd;Wjy; kw;Wk; jw;NghJs;s eP&w;Wfs;
jilg;gLjy; my;yJ ,y;yhJ NghFjy;.

2. kz;rhpTf;F Kd;duhd mwpFwpfis nfhz;l ,lq;fspypUe;J cldbahf kf;fs; mg;ghy; efu
Ntz;Lk;.

3. NkYk;> ghjpg;G VJepiyAs;s gFjpfspy; thOk; kf;fs; Nkyjpf tpopg;Gld; ,Uf;fNtz;Lk;
vd;gJld; fLk; kio njhUkhapd; tpiuthf ghJfhg;ghd ,lq;fSf;F efu Maj;jkhfTk;
,Uf;fNtz;Lk;.
Fwpg;G: jaTnra;J Njrpa fl;bl Muha;r;rp epWtdk; kw;Wk; mdh;j;j Kfhikj;Jt epiyak;
vd;gtw;wpd; mwpTWj;jy;fis gpd;gw;wTk;

    Issued by:                                                      Approved by:




Duty Officer                                                        (for) Director


Date and time issued:
2018/05/22 16.00 hrs.

Landslide Research and Risk Management Division
National Building Research Organisation

In [325]:
# Find impact-related sections in pages 2–5 of the 2018 flood report.
# This avoids printing the entire PDF.

import pymupdf

document = pymupdf.open(flood_pdf)

impact_terms = [
    "affected",
    "families",
    "people",
    "death",
    "injured",
    "missing",
    "houses",
    "damaged",
    "destroyed",
    "evacuated",
    "relocated"
]

for page_number in [2, 3, 4, 5]:

    page = document[page_number - 1]

    lines = [
        line.strip()
        for line in page.get_text("text").splitlines()
        if line.strip()
    ]

    print("\n")
    print("=" * 90)
    print(f"PAGE {page_number} — IMPACT-RELATED LINES")
    print("=" * 90)

    found = False

    for i, line in enumerate(lines):

        line_lower = line.lower()

        if any(
            term in line_lower
            for term in impact_terms
        ):

            found = True

            start = max(0, i - 2)
            end = min(len(lines), i + 4)

            print(
                "\n".join(lines[start:end])
            )
            print("-" * 70)

    if not found:
        print("No impact-related terms found.")

document.close()

==========================================================================================
PAGE 2 — IMPACT-RELATED LINES
==========================================================================================
2018, caused heavy rains and flash floods mainly in twelve districts, including Southern,
Western, North-Western and Sabaragamuwa Provinces.
 Early-warning  reached  to the affected people and  evacuations were done covering the
people who are at risk . Search & rescue teams were pre-positioned  and boats were kept
as ready to launch in the affected districts. 557 military and police officials were mobilized
immediately for search and rescue operations while 5,826 military and police personnel
----------------------------------------------------------------------
Western, North-Western and Sabaragamuwa Provinces.
 Early-warning  reached  to the affected people and  evacuations were done covering the
people who are at risk . Search & rescue teams were pre-positioned  and boats were kept
as ready to launch in the affected districts. 557 military and police officials were mobilized
immediately for search and rescue operations while 5,826 military and police personnel
have been organized as stand-by teams for immediate deployment.
----------------------------------------------------------------------
 Early-warning  reached  to the affected people and  evacuations were done covering the
people who are at risk . Search & rescue teams were pre-positioned  and boats were kept
as ready to launch in the affected districts. 557 military and police officials were mobilized
immediately for search and rescue operations while 5,826 military and police personnel
have been organized as stand-by teams for immediate deployment.
 84,943  people (18,542 families) have been affected (the Disaster Situation Report , DMC &
----------------------------------------------------------------------
immediately for search and rescue operations while 5,826 military and police personnel
have been organized as stand-by teams for immediate deployment.
 84,943  people (18,542 families) have been affected (the Disaster Situation Report , DMC &
National Disaster Relief Services Centre (NDRSC) at 1000 hours on 23rd of May 2018).
NDRSC has provided 14.7 million cash allocations to the 12 District Secretaries to address
the immediate needs of the affected populations.
----------------------------------------------------------------------
National Disaster Relief Services Centre (NDRSC) at 1000 hours on 23rd of May 2018).
NDRSC has provided 14.7 million cash allocations to the 12 District Secretaries to address
the immediate needs of the affected populations.
 As per the immediate rapid impact analysis estimates, 23,000 people need emergency
flood relief and early recovery assistance.
 River water levels at many stations are  gradually decreasing, as the rainfall recorded in the
----------------------------------------------------------------------
NDRSC has provided 14.7 million cash allocations to the 12 District Secretaries to address
the immediate needs of the affected populations.
 As per the immediate rapid impact analysis estimates, 23,000 people need emergency
flood relief and early recovery assistance.
 River water levels at many stations are  gradually decreasing, as the rainfall recorded in the
catchments during the last 24 hours ending 0830 hours is lower compared to the rainfall
----------------------------------------------------------------------
loa 43.5mm, in Badulla 29.5mm, Vavuniya 28.5mm. The highest rainfall recorded was around 72.7mm in
Oddusudan in Mullative District. However, based on received rainfall since 22nd May 2018, rainfall has been
reduced in catchment areas and affected areas and flood waters are receding, allowing response and relief
services to be more effective.
Minister of Disaster Management, Hon Duminda Dissanayake has visited Kalutara area and State Minister of
Disaster Management, Hon Palitha Range Bandara  has visited Puttalam area together with Ministry and Dis-
----------------------------------------------------------------------
Minister of Disaster Management, Hon Duminda Dissanayake has visited Kalutara area and State Minister of
Disaster Management, Hon Palitha Range Bandara  has visited Puttalam area together with Ministry and Dis-
trict officials to provide effective relief to affected people. Hon Minister, has left his office to Ratnapura to-
day to observe the affected areas and provide immediate needs.
Dam leak was identified in Pulachchikulam tank in Puttalam District and settled with sand bags. Vijaya Katu-
potha tank and Waama-Eliya tank has been damaged due to massive rainfall during 21st May. A stability issue
----------------------------------------------------------------------
Disaster Management, Hon Palitha Range Bandara  has visited Puttalam area together with Ministry and Dis-
trict officials to provide effective relief to affected people. Hon Minister, has left his office to Ratnapura to-
day to observe the affected areas and provide immediate needs.
Dam leak was identified in Pulachchikulam tank in Puttalam District and settled with sand bags. Vijaya Katu-
potha tank and Waama-Eliya tank has been damaged due to massive rainfall during 21st May. A stability issue
has been identified in the Kaduwela main bridge and Kaduwela-Biyagama road is temporarily closed.
----------------------------------------------------------------------
day to observe the affected areas and provide immediate needs.
Dam leak was identified in Pulachchikulam tank in Puttalam District and settled with sand bags. Vijaya Katu-
potha tank and Waama-Eliya tank has been damaged due to massive rainfall during 21st May. A stability issue
has been identified in the Kaduwela main bridge and Kaduwela-Biyagama road is temporarily closed.
----------------------------------------------------------------------


==========================================================================================
PAGE 3 — IMPACT-RELATED LINES
==========================================================================================
3
As a result of  severe rains, 84,943 people (18,542 families)
have been affected (the Disaster Situation Report , National
Disaster Relief Services Centre (NDRSC) at 1000 hours on
23rd  of May 2018). People at flood risk have been evacuat-
----------------------------------------------------------------------
3
As a result of  severe rains, 84,943 people (18,542 families)
have been affected (the Disaster Situation Report , National
Disaster Relief Services Centre (NDRSC) at 1000 hours on
23rd  of May 2018). People at flood risk have been evacuat-
ed to safe locations and the total number of welfare cen-
----------------------------------------------------------------------
have been affected (the Disaster Situation Report , National
Disaster Relief Services Centre (NDRSC) at 1000 hours on
23rd  of May 2018). People at flood risk have been evacuat-
ed to safe locations and the total number of welfare cen-
tres. Approximately, 7,526 families have been evacuated
into 194 welfare centres due to flood and landslide risks. As
----------------------------------------------------------------------
23rd  of May 2018). People at flood risk have been evacuat-
ed to safe locations and the total number of welfare cen-
tres. Approximately, 7,526 families have been evacuated
into 194 welfare centres due to flood and landslide risks. As
of now 10 deaths were reported to the Disaster Manage-
ment Centre.
----------------------------------------------------------------------
tres. Approximately, 7,526 families have been evacuated
into 194 welfare centres due to flood and landslide risks. As
of now 10 deaths were reported to the Disaster Manage-
ment Centre.
Department of Irrigation has indicated that several major
river levels are decreasing as of 23 May 2018, at 0630 hours
----------------------------------------------------------------------


==========================================================================================
PAGE 4 — IMPACT-RELATED LINES
==========================================================================================
4
FLOOD STATUS AND FORECASTED IMPACT
FIGURE 03: Affected Districts and proposed prioritization for  response,
22 May 2018 16 00 hours
ESTIMATED PRIORTITY 01 using rapid impact assessment approach
 Estimated 23, 470 People Severely affected and needs
----------------------------------------------------------------------
22 May 2018 16 00 hours
ESTIMATED PRIORTITY 01 using rapid impact assessment approach
 Estimated 23, 470 People Severely affected and needs
emergency assistance
 Estimated Number of households at high risk— 447 houses
----------------------------------------------------------------------
 Estimated 23, 470 People Severely affected and needs
emergency assistance
 Estimated Number of households at high risk— 447 houses
----------------------------------------------------------------------


==========================================================================================
PAGE 5 — IMPACT-RELATED LINES
==========================================================================================
No impact-related terms found.

In [326]:
from pathlib import Path
import pandas as pd

# Project root
PROJECT_ROOT = Path("/Users/ohaseelanka/disaster_analytics_hub")

# Existing processed/interim flood datasets
flood_files = {
    "rainfall": PROJECT_ROOT / "data/interim/flood/rainfall_daily_long.parquet",
    "water_level": PROJECT_ROOT / "data/interim/flood/water_level_daily.parquet",
    "discharge": PROJECT_ROOT / "data/interim/flood/discharge_daily.parquet",
    "kelani_events": PROJECT_ROOT / "data/interim/flood/kelani/flood_candidate_events_station.parquet",
    "kelani_episodes": PROJECT_ROOT / "data/interim/flood/kelani/flood_regional_episodes.parquet",
    "census_ds": PROJECT_ROOT / "data/processed/census_ds_features.parquet",
    "flood_ds_features": PROJECT_ROOT / "data/processed/flood_ds_features.parquet",
}

print("=" * 80)
print("FLOOD DATASET INVENTORY")
print("=" * 80)

for name, path in flood_files.items():

    print(f"\n{name}")
    print("-" * 80)
    print("Path:", path)
    print("Exists:", path.exists())

    if path.exists():
        df = pd.read_parquet(path)

        print("Shape:", df.shape)
        print("Columns:", list(df.columns))

print("\n" + "=" * 80)
print("INVENTORY CHECK COMPLETE")
print("=" * 80)

================================================================================
FLOOD DATASET INVENTORY
================================================================================

rainfall
--------------------------------------------------------------------------------
Path: /Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/rainfall_daily_long.parquet
Exists: True
Shape: (24108, 4)
Columns: ['station_id', 'station_name', 'date', 'rainfall_mm']

water_level
--------------------------------------------------------------------------------
Path: /Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/water_level_daily.parquet
Exists: True
Shape: (42006, 5)
Columns: ['station_id', 'station_name', 'date', 'water_level', 'unit']

discharge
--------------------------------------------------------------------------------
Path: /Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/discharge_daily.parquet
Exists: True
Shape: (24108, 4)
Columns: ['station_id', 'station_name', 'date', 'discharge_m3s']

kelani_events
--------------------------------------------------------------------------------
Path: /Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/kelani/flood_candidate_events_station.parquet
Exists: True
Shape: (305, 10)
Columns: ['station_id', 'event_id', 'start_date', 'end_date', 'candidate_days', 'max_rainfall_3d', 'max_rainfall_7d', 'max_wl_zscore', 'max_q_zscore', 'duration_days']

kelani_episodes
--------------------------------------------------------------------------------
Path: /Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/kelani/flood_regional_episodes.parquet
Exists: True
Shape: (30, 11)
Columns: ['regional_episode_id', 'start_date', 'end_date', 'station_count', 'station_event_count', 'stations', 'max_rainfall_3d', 'max_rainfall_7d', 'max_wl_zscore', 'max_q_zscore', 'duration_days']

census_ds
--------------------------------------------------------------------------------
Path: /Users/ohaseelanka/disaster_analytics_hub/data/processed/census_ds_features.parquet
Exists: True
Shape: (340, 64)
Columns: ['district_name', 'ds_name_join', 'ds_code', 'total_population', 'male', 'female', 'age_total', 'age_0_14', 'age_15_59', 'age_60_64', 'age_65_plus', 'elderly_60_plus', 'occupied_housing_units', 'number_of_households', 'water_protected_well', 'water_semi_protected_well', 'water_unprotected_well', 'water_tube_well', 'water_spring_fountain', 'water_national_water_supply', 'water_local_authority', 'water_community_organization', 'water_private_supply', 'water_tank_river_stream', 'water_rain_water', 'water_bottled', 'water_filter_ro_plant', 'water_bowser', 'water_other', 'cooking_firewood', 'cooking_kerosene', 'cooking_gas', 'cooking_electricity', 'cooking_sawdust_paddy_husk', 'cooking_biogas', 'cooking_other', 'cooking_not_relevant', 'lighting_national_grid_hydro', 'lighting_kerosene_lamp', 'lighting_solar_grid', 'lighting_solar_standalone', 'lighting_biogas', 'lighting_generator', 'lighting_other', 'toilet_within_unit_exclusive', 'toilet_within_unit_shared', 'toilet_within_premises_exclusive', 'toilet_within_premises_shared', 'toilet_no_toilet_shared_elsewhere', 'toilet_common_public', 'toilet_no_toilet', 'children_0_14_ratio', 'elderly_60_plus_ratio', 'female_ratio', 'households_per_1000_population', 'housing_units_per_1000_population', 'unprotected_well_households', 'river_stream_water_households', 'no_toilet_households', 'public_toilet_households', 'unprotected_well_ratio', 'river_stream_water_ratio', 'no_toilet_ratio', 'public_toilet_ratio']

flood_ds_features
--------------------------------------------------------------------------------
Path: /Users/ohaseelanka/disaster_analytics_hub/data/processed/flood_ds_features.parquet
Exists: False

================================================================================
INVENTORY CHECK COMPLETE
================================================================================

In [327]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path("/Users/ohaseelanka/disaster_analytics_hub")

# Authentic census DS features
census_ds_path = (
    PROJECT_ROOT /
    "data/processed/census_ds_features.parquet"
)

# QGIS-generated DS feature matrix
qgis_path = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/ds79_feature_matrix.csv"
)

print("=" * 80)
print("AUTHENTIC FLOOD DS / GIS DATA CHECK")
print("=" * 80)

# ------------------------------------------------------------------
# Census
# ------------------------------------------------------------------

census_ds = pd.read_parquet(census_ds_path)

print("\nCENSUS DS DATA")
print("-" * 80)
print("Shape:", census_ds.shape)
print("Districts:", census_ds["district_name"].nunique())
print("DS divisions:", census_ds["ds_name_join"].nunique())

print("\nDistrict distribution:")
print(
    census_ds["district_name"]
    .value_counts()
    .to_string()
)

# ------------------------------------------------------------------
# QGIS
# ------------------------------------------------------------------

print("\n\nQGIS FEATURE MATRIX")
print("-" * 80)
print("Path:", qgis_path)
print("Exists:", qgis_path.exists())

if qgis_path.exists():

    qgis_ds = pd.read_csv(qgis_path)

    print("Shape:", qgis_ds.shape)
    print("Columns:")
    print(list(qgis_ds.columns))

    print("\nFirst 5 rows:")
    display(qgis_ds.head())

else:
    print("QGIS feature matrix was not found.")

print("\n" + "=" * 80)
print("CHECK COMPLETE")
print("=" * 80)

================================================================================
AUTHENTIC FLOOD DS / GIS DATA CHECK
================================================================================

CENSUS DS DATA
--------------------------------------------------------------------------------
Shape: (340, 64)
Districts: 25
DS divisions: 340

District distribution:
district_name
Kurunegala      30
Anuradhapura    22
Galle           22
Ampara          20
Kandy           20
Ratnapura       18
Matara          16
Puttalam        16
Jaffna          15
Badulla         15
Kalutara        14
Batticaloa      14
Colombo         13
Gampaha         13
Hambantota      12
Moneragala      11
Kegalle         11
Matale          11
Trincomalee     11
Nuwara Eliya    10
Polonnaruwa      7
Mullaitivu       6
Mannar           5
Kilinochchi      4
Vavuniya         4


QGIS FEATURE MATRIX
--------------------------------------------------------------------------------
Path: /Users/ohaseelanka/Desktop/disaster_project_gis/ds79_feature_matrix.csv
Exists: True
Shape: (79, 38)
Columns:
['fid', 'adm3_name', 'adm3_name1', 'adm3_name2', 'adm3_name3', 'adm3_pcode', 'adm2_name', 'adm2_name1', 'adm2_name2', 'adm2_name3', 'adm2_pcode', 'adm1_name', 'adm1_name1', 'adm1_name2', 'adm1_name3', 'adm1_pcode', 'adm0_name', 'adm0_name1', 'adm0_name2', 'adm0_name3', 'adm0_pcode', 'valid_on', 'valid_to', 'area_sqkm', 'version', 'lang', 'lang1', 'lang2', 'lang3', 'center_lat', 'center_lon', 'total_road_m', 'COUNT', 'road_density', 'facility_count', 'Hub distance_HubName', 'Hub distance_HubDist', 'facility_density']

First 5 rows:

,fid,adm3_name,adm3_name1,adm3_name2,adm3_name3,adm3_pcode,adm2_name,adm2_name1,adm2_name2,adm2_name3,adm2_pcode,adm1_name,adm1_name1,adm1_name2,adm1_name3,adm1_pcode,adm0_name,adm0_name1,adm0_name2,adm0_name3,adm0_pcode,valid_on,valid_to,area_sqkm,version,lang,lang1,lang2,lang3,center_lat,center_lon,total_road_m,COUNT,road_density,facility_count,Hub distance_HubName,Hub distance_HubDist,facility_density
0,1,Colombo,කොළඹ,கொழும்பு,NaN,LK1103,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,LK11,Western,බස්නාහිර පළාත,மேல் மாகாணம்,NaN,LK1,Sri Lanka,ශ්‍රී ලංකා,இலங்கை,NaN,LK,2022/08/16,NaN,24.537151,v03,en,si,ta,NaN,6.946987,79.865263,4.004475e+05,3133,16.320050,213,Old Town Hall,0.480685,8.680714
1,2,Kolonnawa,කොලොන්නාව,கொலன்னாவை,NaN,LK1106,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,LK11,Western,බස්නාහිර පළාත,மேல் மாகாணம்,NaN,LK1,Sri Lanka,ශ්‍රී ලංකා,இலங்கை,NaN,LK,2022/08/16,NaN,25.928037,v03,en,si,ta,NaN,6.934943,79.914709,3.693511e+05,2359,14.245240,56,Dharmapala Vidalaya,0.411989,2.159824
2,3,Kaduwela,කඩුවෙල,கடுவெலை,NaN,LK1109,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,LK11,Western,බස්නාහිර පළාත,மேல் மாகாணம்,NaN,LK1,Sri Lanka,ශ්‍රී ලංකා,இலங்கை,NaN,LK,2022/08/16,NaN,86.737826,v03,en,si,ta,NaN,6.901985,79.972773,1.016346e+06,6650,11.717451,219,Supreme City Children's Playground,0.345704,2.524850
3,4,Homagama,හෝමාගම,கோமகமை,NaN,LK1112,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,LK11,Western,බස්නාහිර පළාත,மேல் மாகாணம்,NaN,LK1,Sri Lanka,ශ්‍රී ලංකා,இலங்கை,NaN,LK,2022/08/16,NaN,120.316227,v03,en,si,ta,NaN,6.836353,80.024442,9.303959e+05,3892,7.732922,96,Pitipana Kiriberiyakele Crematorium and cemetery,0.648292,0.797897
4,5,Seethawaka,සීතාවක,சீதவாக்கை,NaN,LK1115,Colombo,කොළඹ දිස්ත්‍රික්ක,கொழும்பு மாவட்டம்,NaN,LK11,Western,බස්නාහිර පළාත,மேல் மாகாணம்,NaN,LK1,Sri Lanka,ශ්‍රී ලංකා,இலங்கை,NaN,LK,2022/08/16,NaN,145.976978,v03,en,si,ta,NaN,6.919902,80.152703,5.695109e+05,1602,3.901375,41,NaN,1.989135,0.280866

================================================================================
CHECK COMPLETE
================================================================================

In [328]:
import pandas as pd
import numpy as np

# Load the two authentic datasets
census_ds = pd.read_parquet(
    "/Users/ohaseelanka/disaster_analytics_hub/data/processed/census_ds_features.parquet"
)

qgis_ds = pd.read_csv(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/ds79_feature_matrix.csv"
)

# ------------------------------------------------------------
# Standardize names for matching
# ------------------------------------------------------------

def clean_name(value):
    if pd.isna(value):
        return np.nan

    return (
        str(value)
        .strip()
        .lower()
        .replace(" ", "")
        .replace("-", "")
        .replace("_", "")
    )

census_ds["ds_match"] = census_ds["ds_name_join"].apply(clean_name)
qgis_ds["ds_match"] = qgis_ds["adm3_name"].apply(clean_name)

# ------------------------------------------------------------
# Focus on the flood-study districts
# ------------------------------------------------------------

flood_districts = [
    "Colombo",
    "Gampaha",
    "Kegalle",
    "Ratnapura",
    "Nuwara Eliya"
]

census_flood = census_ds[
    census_ds["district_name"].isin(flood_districts)
].copy()

qgis_flood = qgis_ds[
    qgis_ds["adm2_name"].isin(flood_districts)
].copy()

# ------------------------------------------------------------
# Match
# ------------------------------------------------------------

matched = census_flood.merge(
    qgis_flood,
    on="ds_match",
    how="inner",
    suffixes=("_census", "_qgis")
)

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

print("=" * 90)
print("AUTHENTIC FLOOD DS MATCHING")
print("=" * 90)

print("\nCensus flood DS records:", len(census_flood))
print("QGIS flood DS records:", len(qgis_flood))
print("Matched DS records:", len(matched))

print("\nMatched DS by district:")
print(
    matched["district_name"]
    .value_counts()
    .sort_index()
    .to_string()
)

print("\n" + "-" * 90)
print("MATCHED DS DIVISIONS")
print("-" * 90)

display(
    matched[
        [
            "district_name",
            "ds_name_join",
            "adm3_name",
            "adm3_pcode",
            "area_sqkm",
            "total_road_m",
            "road_density",
            "facility_count",
            "facility_density"
        ]
    ]
    .sort_values(
        ["district_name", "ds_name_join"]
    )
    .reset_index(drop=True)
)

print("\n" + "=" * 90)
print("MATCHING CHECK COMPLETE")
print("=" * 90)

==========================================================================================
AUTHENTIC FLOOD DS MATCHING
==========================================================================================

Census flood DS records: 65
QGIS flood DS records: 65
Matched DS records: 55

Matched DS by district:
district_name
Colombo         13
Gampaha         13
Kegalle          7
Nuwara Eliya     7
Ratnapura       15

------------------------------------------------------------------------------------------
MATCHED DS DIVISIONS
------------------------------------------------------------------------------------------

   district_name               ds_name_join                  adm3_name adm3_pcode   area_sqkm  total_road_m  road_density  facility_count  facility_density
0        Colombo                    Colombo                    Colombo     LK1103   24.537151  4.004475e+05     16.320050             213          8.680714
1        Colombo                   Dehiwala                   Dehiwala     LK1130    8.458706  1.601775e+05     18.936403              36          4.255970
2        Colombo                   Homagama                   Homagama     LK1112  120.316227  9.303959e+05      7.732922              96          0.797897
3        Colombo                   Kaduwela                   Kaduwela     LK1109   86.737826  1.016346e+06     11.717451             219          2.524850
4        Colombo                    Kesbewa                    Kesbewa     LK1136   61.408264  6.686632e+05     10.888814              74          1.205050
5        Colombo                  Kolonnawa                  Kolonnawa     LK1106   25.928037  3.693511e+05     14.245240              56          2.159824
6        Colombo                 Maharagama                 Maharagama     LK1121   37.796756  5.274490e+05     13.954874              83          2.195956
7        Colombo                   Moratuwa                   Moratuwa     LK1133   19.303715  2.662371e+05     13.792011              42          2.175747
8        Colombo                    Padukka                    Padukka     LK1118  106.194605  3.417257e+05      3.217920              37          0.348417
9        Colombo                  Ratmalana                  Ratmalana     LK1131   12.862515  2.051699e+05     15.950996             130         10.106888
10       Colombo                 Seethawaka                 Seethawaka     LK1115  145.976978  5.695109e+05      3.901375              41          0.280866
11       Colombo  Sri Jayawardanapura Kotte  Sri Jayawardanapura Kotte     LK1124   16.315757  2.585207e+05     15.844846              82          5.025816
12       Colombo            Thimbirigasyaya            Thimbirigasyaya     LK1127   22.329376  4.515042e+05     20.220188             489         21.899403
13       Gampaha                Attanagalla                Attanagalla     LK1227  154.831362  6.849737e+05      4.423998              51          0.329391
14       Gampaha                   Biyagama                   Biyagama     LK1239   61.005986  5.491422e+05      9.001448              35          0.573714
15       Gampaha               Divulapitiya               Divulapitiya     LK1209  203.160287  6.894329e+05      3.393542              12          0.059067
16       Gampaha                      Dompe                      Dompe     LK1230  179.184923  6.375307e+05      3.557948              12          0.066970
17       Gampaha                    Gampaha                    Gampaha     LK1224   91.819558  1.041247e+06     11.340145             930         10.128561
18       Gampaha                     Ja-Ela                     Ja Ela     LK1221   62.450121  7.247639e+05     11.605484             414          6.629291
19       Gampaha                     Katana                     Katana     LK1206  107.799359  9.876830e+05      9.162235             187          1.734704
20       Gampaha                   Kelaniya                   Kelaniya     LK1236   21.939187  2.868008e+05     13.072537              60          2.734832
21       Gampaha                     Mahara                     Mahara     LK1233   95.748478  6.213145e+05      6.489028              35          0.365541
22       Gampaha                Minuwangoda                Minuwangoda     LK1215  132.120991  8.313622e+05      6.292431             151          1.142892
23       Gampaha                   Mirigama                   Mirigama     LK1212  188.811289  5.879966e+05      3.114202              41          0.217148
24       Gampaha                    Negombo                    Negombo     LK1203   29.189336  3.521724e+05     12.065103             110          3.768500
25       Gampaha                    Wattala                    Wattala     LK1218   57.170713  5.876861e+05     10.279497             128          2.238909
26       Kegalle               Deraniyagala               Deraniyagala     LK9233  222.157864  2.873356e+05      1.293385              11          0.049514
27       Kegalle                 Galigamuwa                 Galigamuwa     LK9215  124.589823  2.791251e+05      2.240352              32          0.256843
28       Kegalle                    Kegalle                    Kegalle     LK9212  106.253692  2.848075e+05      2.680448              38          0.357635
29       Kegalle                  Mawanella                  Mawanella     LK9206  120.094023  2.756508e+05      2.295291              47          0.391360
30       Kegalle                 Rambukkana                 Rambukkana     LK9203  127.792892  2.780569e+05      2.175840              22          0.172154
31       Kegalle                 Ruwanwella                 Ruwanwella     LK9221  140.637891  2.917489e+05      2.074469              17          0.120878
32       Kegalle                 Warakapola                 Warakapola     LK9218  196.982135  3.805960e+05      1.932134              22          0.111685
33  Nuwara Eliya              Kothmale East              Kothmale East     LK2303  140.002626  3.402754e+05      2.430493              20          0.142854
34  Nuwara Eliya              Kothmale West              Kothmale West     LK2321   86.792177  2.915136e+05      3.358754              22          0.253479
35  Nuwara Eliya                  Mathurata                  Mathurata     LK2318   92.839830  1.708429e+05      1.840190              19          0.204654
36  Nuwara Eliya              Nildandahinna              Nildandahinna     LK2309  171.235573  3.244131e+05      1.894543              34          0.198557
37  Nuwara Eliya                    Norwood                    Norwood     LK2330  351.246024  1.027532e+06      2.925391             103          0.293242
38  Nuwara Eliya               Nuwara Eliya               Nuwara Eliya     LK2312  222.063358  6.488606e+05      2.921962              69          0.310722
39  Nuwara Eliya                   Walapane                   Walapane     LK2324  151.646099  3.427857e+05      2.260432              28          0.184640
40     Ratnapura                    Ayagama                    Ayagama     LK9130  163.354507  5.058114e+05      3.096403               9          0.055095
41     Ratnapura                  Balangoda                  Balangoda     LK9118  183.451426  3.486612e+05      1.900564              16          0.087217
42     Ratnapura                Eheliyagoda                Eheliyagoda     LK9103  140.971448  3.843037e+05      2.726110              60          0.425618
43     Ratnapura                   Elapatha                   Elapatha     LK9127   85.606743  3.524448e+05      4.117022               6          0.070088
44     Ratnapura               Embilipitiya               Embilipitiya     LK9148  388.816920  8.996240e+05      2.313747              40          0.102876
45     Ratnapura                 Godakawela                 Godakawela     LK9142  152.121084  3.367296e+05      2.213563              23          0.151195
46     Ratnapura                    Imbulpe                    Imbulpe     LK9115  255.010385  4.050884e+05      1.588517              55          0.215677
47     Ratnapura                   Kalawana                   Kalawana     LK9133  382.398966  5.034578e+05      1.316577              11          0.028766
48     Ratnapura                   Kiriella                   Kiriella     LK9109   79.425895  2.789342e+05      3.511879              13          0.163675
49     Ratnapura                    Kolonna                    Kolonna     LK9151  177.845851  3.018316e+05      1.697153              16          0.089966
50     Ratnapura                   Kuruvita                   Kuruvita     LK9106  171.016346  4.374267e+05      2.557806              24          0.140337
51     Ratnapura                Nivithigala                Nivithigala     LK9136  153.456250  3.748324e+05      2.442601              25          0.162913
52     Ratnapura                 Pelmadulla                 Pelmadulla     LK9124  146.678668  4.194760e+05      2.859830              15          0.102264
53     Ratnapura                  Ratnapura                  Ratnapura     LK9112  327.733666  7.292466e+05      2.225119              83          0.253254
54     Ratnapura                 Weligepola                 Weligepola     LK9145  198.015452  1.961283e+05      0.990470               4          0.020200

==========================================================================================
MATCHING CHECK COMPLETE
==========================================================================================

In [329]:
# Identify DS divisions that exist in one authentic source
# but not the other.

census_names = set(census_flood["ds_match"].dropna())
qgis_names = set(qgis_flood["ds_match"].dropna())

census_only = census_flood[
    ~census_flood["ds_match"].isin(qgis_names)
].copy()

qgis_only = qgis_flood[
    ~qgis_flood["ds_match"].isin(census_names)
].copy()

print("=" * 90)
print("UNMATCHED AUTHENTIC DS DIVISIONS")
print("=" * 90)

print("\nCENSUS DS → NOT FOUND IN QGIS")
print("-" * 90)

if len(census_only) > 0:
    display(
        census_only[
            [
                "district_name",
                "ds_name_join",
                "ds_code",
                "total_population"
            ]
        ]
        .sort_values(
            ["district_name", "ds_name_join"]
        )
        .reset_index(drop=True)
    )
else:
    print("None")

print("\nQGIS DS → NOT FOUND IN CENSUS")
print("-" * 90)

if len(qgis_only) > 0:
    display(
        qgis_only[
            [
                "adm2_name",
                "adm3_name",
                "adm3_pcode",
                "area_sqkm"
            ]
        ]
        .sort_values(
            ["adm2_name", "adm3_name"]
        )
        .reset_index(drop=True)
    )
else:
    print("None")

print("\n" + "=" * 90)
print("COUNTS")
print("=" * 90)

print("Census-only:", len(census_only))
print("QGIS-only:", len(qgis_only))
print("Total unmatched:", len(census_only) + len(qgis_only))

==========================================================================================
UNMATCHED AUTHENTIC DS DIVISIONS
==========================================================================================

CENSUS DS → NOT FOUND IN QGIS
------------------------------------------------------------------------------------------

  district_name         ds_name_join  ds_code  total_population
0       Kegalle            Aranayaka        9             69075
1       Kegalle     Bulathkohupitiya       24             45237
2       Kegalle            Dehiovita       30             84967
3       Kegalle         Yatiyanthota       27             62255
4  Nuwara Eliya  Ambagamuwa Koralaya       15             42538
5  Nuwara Eliya        Hanguranketha        6             58931
6  Nuwara Eliya         Thalawakelle       13            129531
7     Ratnapura            Kahawatta       39             43708
8     Ratnapura              Kaltota       19             13018
9     Ratnapura            Opanayaka       21             27244

QGIS DS → NOT FOUND IN CENSUS
------------------------------------------------------------------------------------------

      adm2_name          adm3_name adm3_pcode   area_sqkm
0       Kegalle          Aranayake     LK9209  120.094898
1       Kegalle   Bulathkohipitiya     LK9224  125.266065
2       Kegalle          Dehiowita     LK9230  193.948087
3       Kegalle        Yatiyantota     LK9227  179.914723
4  Nuwara Eliya  Ambagamuwa Korale     LK2315  135.588779
5  Nuwara Eliya       Hanguranketa     LK2306  132.879199
6  Nuwara Eliya        Thalawakele     LK2327  260.521170
7     Ratnapura         Kahawattha     LK9139  104.248827
8     Ratnapura           Kalthota     LK9154   97.635369
9     Ratnapura          Opanayake     LK9121   79.287949

==========================================================================================
COUNTS
==========================================================================================
Census-only: 10
QGIS-only: 10
Total unmatched: 20

In [330]:
# ============================================================
# CELL 5 — STANDARDIZE FLOOD DS NAMES
# ============================================================

# Copy the existing tables so the original data remains unchanged
census_flood_std = census_flood.copy()
qgis_flood_std = qgis_flood.copy()

# ------------------------------------------------------------
# Standardization mapping
# Census spelling → common standardized spelling
# ------------------------------------------------------------

ds_name_mapping = {
    "Aranayaka": "Aranayake",
    "Bulathkohupitiya": "Bulathkohipitiya",
    "Dehiovita": "Dehiowita",
    "Yatiyanthota": "Yatiyantota",
    "Ambagamuwa Koralaya": "Ambagamuwa Korale",
    "Hanguranketha": "Hanguranketa",
    "Thalawakelle": "Thalawakele",
    "Kahawatta": "Kahawattha",
    "Kaltota": "Kalthota",
    "Opanayaka": "Opanayake"
}

# Apply mapping only to the Census side
census_flood_std["ds_match_std"] = (
    census_flood_std["ds_name_join"]
    .replace(ds_name_mapping)
)

# QGIS already contains the desired standardized names
qgis_flood_std["ds_match_std"] = (
    qgis_flood_std["adm3_name"]
    .astype("string")
    .str.strip()
)

# ------------------------------------------------------------
# Check matching after standardization
# ------------------------------------------------------------

census_names_std = set(
    census_flood_std["ds_match_std"].dropna()
)

qgis_names_std = set(
    qgis_flood_std["ds_match_std"].dropna()
)

census_only_std = census_flood_std[
    ~census_flood_std["ds_match_std"].isin(qgis_names_std)
].copy()

qgis_only_std = qgis_flood_std[
    ~qgis_flood_std["ds_match_std"].isin(census_names_std)
].copy()

matched_std = census_flood_std[
    census_flood_std["ds_match_std"].isin(qgis_names_std)
].copy()

print("=" * 90)
print("FLOOD DS MATCHING AFTER NAME STANDARDIZATION")
print("=" * 90)

print("\nCensus flood DS:", len(census_flood_std))
print("QGIS flood DS:", len(qgis_flood_std))
print("Matched Census DS:", len(matched_std))
print("Census-only:", len(census_only_std))
print("QGIS-only:", len(qgis_only_std))

print("\n" + "=" * 90)
print("REMAINING UNMATCHED RECORDS")
print("=" * 90)

if len(census_only_std) > 0:
    print("\nCENSUS ONLY")
    display(
        census_only_std[
            [
                "district_name",
                "ds_name_join",
                "ds_match_std"
            ]
        ]
        .sort_values(
            ["district_name", "ds_match_std"]
        )
        .reset_index(drop=True)
    )
else:
    print("\nCensus-only: NONE")

if len(qgis_only_std) > 0:
    print("\nQGIS ONLY")
    display(
        qgis_only_std[
            [
                "adm2_name",
                "adm3_name",
                "ds_match_std",
                "adm3_pcode"
            ]
        ]
        .sort_values(
            ["adm2_name", "ds_match_std"]
        )
        .reset_index(drop=True)
    )
else:
    print("\nQGIS-only: NONE")

print("\n" + "=" * 90)

==========================================================================================
FLOOD DS MATCHING AFTER NAME STANDARDIZATION
==========================================================================================

Census flood DS: 65
QGIS flood DS: 65
Matched Census DS: 64
Census-only: 1
QGIS-only: 1

==========================================================================================
REMAINING UNMATCHED RECORDS
==========================================================================================

CENSUS ONLY

  district_name ds_name_join ds_match_std
0       Gampaha       Ja-Ela       Ja-Ela

QGIS ONLY

  adm2_name adm3_name ds_match_std adm3_pcode
0   Gampaha    Ja Ela       Ja Ela     LK1221

==========================================================================================

In [331]:
# ============================================================
# CELL 6 — FINAL DS NAME STANDARDIZATION
# ============================================================

# Standardize Ja-Ela / Ja Ela
census_flood_std["ds_match_std"] = (
    census_flood_std["ds_match_std"]
    .replace({
        "Ja-Ela": "Ja Ela"
    })
)

# Recalculate matching
census_names_std = set(
    census_flood_std["ds_match_std"].dropna()
)

qgis_names_std = set(
    qgis_flood_std["ds_match_std"].dropna()
)

census_only_std = census_flood_std[
    ~census_flood_std["ds_match_std"].isin(qgis_names_std)
].copy()

qgis_only_std = qgis_flood_std[
    ~qgis_flood_std["ds_match_std"].isin(census_names_std)
].copy()

matched_std = census_flood_std[
    census_flood_std["ds_match_std"].isin(qgis_names_std)
].copy()

print("=" * 90)
print("FINAL FLOOD DS MATCHING")
print("=" * 90)

print("Census flood DS :", len(census_flood_std))
print("QGIS flood DS   :", len(qgis_flood_std))
print("Matched DS      :", len(matched_std))
print("Census-only     :", len(census_only_std))
print("QGIS-only       :", len(qgis_only_std))

print("\n" + "=" * 90)

if len(census_only_std) == 0 and len(qgis_only_std) == 0:
    print("SUCCESS: ALL FLOOD DS DIVISIONS MATCH")
else:
    print("WARNING: SOME DS DIVISIONS ARE STILL UNMATCHED")

print("=" * 90)

==========================================================================================
FINAL FLOOD DS MATCHING
==========================================================================================
Census flood DS : 65
QGIS flood DS   : 65
Matched DS      : 65
Census-only     : 0
QGIS-only       : 0

==========================================================================================
SUCCESS: ALL FLOOD DS DIVISIONS MATCH
==========================================================================================

In [332]:
# ============================================================
# CELL 7 — INSPECT AUTHENTIC FLOOD DS FEATURES
# ============================================================

print("=" * 90)
print("CENSUS FLOOD FEATURES")
print("=" * 90)

print("Shape:", census_flood_std.shape)

print("\nCensus columns:")
for i, col in enumerate(census_flood_std.columns, start=1):
    print(f"{i:02d}. {col}")


print("\n" + "=" * 90)
print("QGIS FLOOD FEATURES")
print("=" * 90)

print("Shape:", qgis_flood_std.shape)

print("\nQGIS columns:")
for i, col in enumerate(qgis_flood_std.columns, start=1):
    print(f"{i:02d}. {col}")


print("\n" + "=" * 90)
print("MATCHING CHECK")
print("=" * 90)

print("Unique standardized Census DS:",
      census_flood_std["ds_match_std"].nunique())

print("Unique standardized QGIS DS:",
      qgis_flood_std["ds_match_std"].nunique())

print("Expected matched DS: 65")

==========================================================================================
CENSUS FLOOD FEATURES
==========================================================================================
Shape: (65, 66)

Census columns:
01. district_name
02. ds_name_join
03. ds_code
04. total_population
05. male
06. female
07. age_total
08. age_0_14
09. age_15_59
10. age_60_64
11. age_65_plus
12. elderly_60_plus
13. occupied_housing_units
14. number_of_households
15. water_protected_well
16. water_semi_protected_well
17. water_unprotected_well
18. water_tube_well
19. water_spring_fountain
20. water_national_water_supply
21. water_local_authority
22. water_community_organization
23. water_private_supply
24. water_tank_river_stream
25. water_rain_water
26. water_bottled
27. water_filter_ro_plant
28. water_bowser
29. water_other
30. cooking_firewood
31. cooking_kerosene
32. cooking_gas
33. cooking_electricity
34. cooking_sawdust_paddy_husk
35. cooking_biogas
36. cooking_other
37. cooking_not_relevant
38. lighting_national_grid_hydro
39. lighting_kerosene_lamp
40. lighting_solar_grid
41. lighting_solar_standalone
42. lighting_biogas
43. lighting_generator
44. lighting_other
45. toilet_within_unit_exclusive
46. toilet_within_unit_shared
47. toilet_within_premises_exclusive
48. toilet_within_premises_shared
49. toilet_no_toilet_shared_elsewhere
50. toilet_common_public
51. toilet_no_toilet
52. children_0_14_ratio
53. elderly_60_plus_ratio
54. female_ratio
55. households_per_1000_population
56. housing_units_per_1000_population
57. unprotected_well_households
58. river_stream_water_households
59. no_toilet_households
60. public_toilet_households
61. unprotected_well_ratio
62. river_stream_water_ratio
63. no_toilet_ratio
64. public_toilet_ratio
65. ds_match
66. ds_match_std

==========================================================================================
QGIS FLOOD FEATURES
==========================================================================================
Shape: (65, 40)

QGIS columns:
01. fid
02. adm3_name
03. adm3_name1
04. adm3_name2
05. adm3_name3
06. adm3_pcode
07. adm2_name
08. adm2_name1
09. adm2_name2
10. adm2_name3
11. adm2_pcode
12. adm1_name
13. adm1_name1
14. adm1_name2
15. adm1_name3
16. adm1_pcode
17. adm0_name
18. adm0_name1
19. adm0_name2
20. adm0_name3
21. adm0_pcode
22. valid_on
23. valid_to
24. area_sqkm
25. version
26. lang
27. lang1
28. lang2
29. lang3
30. center_lat
31. center_lon
32. total_road_m
33. COUNT
34. road_density
35. facility_count
36. Hub distance_HubName
37. Hub distance_HubDist
38. facility_density
39. ds_match
40. ds_match_std

==========================================================================================
MATCHING CHECK
==========================================================================================
Unique standardized Census DS: 65
Unique standardized QGIS DS: 65
Expected matched DS: 65

In [333]:
# ============================================================
# CELL 8 — SHOW ALL CENSUS COLUMNS
# ============================================================

print("=" * 90)
print("ALL CENSUS FLOOD COLUMNS")
print("=" * 90)

for start in range(0, len(census_flood_std.columns), 15):
    end = min(start + 15, len(census_flood_std.columns))

    print(f"\nColumns {start + 1}–{end}")
    print("-" * 90)

    for i, col in enumerate(
        census_flood_std.columns[start:end],
        start=start + 1
    ):
        print(f"{i:02d}. {col}")

==========================================================================================
ALL CENSUS FLOOD COLUMNS
==========================================================================================

Columns 1–15
------------------------------------------------------------------------------------------
01. district_name
02. ds_name_join
03. ds_code
04. total_population
05. male
06. female
07. age_total
08. age_0_14
09. age_15_59
10. age_60_64
11. age_65_plus
12. elderly_60_plus
13. occupied_housing_units
14. number_of_households
15. water_protected_well

Columns 16–30
------------------------------------------------------------------------------------------
16. water_semi_protected_well
17. water_unprotected_well
18. water_tube_well
19. water_spring_fountain
20. water_national_water_supply
21. water_local_authority
22. water_community_organization
23. water_private_supply
24. water_tank_river_stream
25. water_rain_water
26. water_bottled
27. water_filter_ro_plant
28. water_bowser
29. water_other
30. cooking_firewood

Columns 31–45
------------------------------------------------------------------------------------------
31. cooking_kerosene
32. cooking_gas
33. cooking_electricity
34. cooking_sawdust_paddy_husk
35. cooking_biogas
36. cooking_other
37. cooking_not_relevant
38. lighting_national_grid_hydro
39. lighting_kerosene_lamp
40. lighting_solar_grid
41. lighting_solar_standalone
42. lighting_biogas
43. lighting_generator
44. lighting_other
45. toilet_within_unit_exclusive

Columns 46–60
------------------------------------------------------------------------------------------
46. toilet_within_unit_shared
47. toilet_within_premises_exclusive
48. toilet_within_premises_shared
49. toilet_no_toilet_shared_elsewhere
50. toilet_common_public
51. toilet_no_toilet
52. children_0_14_ratio
53. elderly_60_plus_ratio
54. female_ratio
55. households_per_1000_population
56. housing_units_per_1000_population
57. unprotected_well_households
58. river_stream_water_households
59. no_toilet_households
60. public_toilet_households

Columns 61–66
------------------------------------------------------------------------------------------
61. unprotected_well_ratio
62. river_stream_water_ratio
63. no_toilet_ratio
64. public_toilet_ratio
65. ds_match
66. ds_match_std

In [334]:
# ============================================================
# CELL 9 — CHECK FOR DISABILITY DATA
# ============================================================

print("=" * 90)
print("SEARCHING CENSUS WORKBOOK FOR DISABILITY DATA")
print("=" * 90)

# Show all sheets in the original population workbook
print("\nPopulation workbook sheets:")
print(population_xls.sheet_names)

# Search sheet names for disability-related terms
disability_keywords = [
    "disab",
    "disabled",
    "disability",
    "impair",
    "difficulty"
]

possible_sheets = [
    sheet for sheet in population_xls.sheet_names
    if any(
        keyword in sheet.lower()
        for keyword in disability_keywords
    )
]

print("\nPossible disability-related sheets:")
print(possible_sheets if possible_sheets else "NONE FOUND")

# Search the cleaned population table's columns
possible_columns = [
    col for col in census_flood_std.columns
    if any(
        keyword in str(col).lower()
        for keyword in disability_keywords
    )
]

print("\nPossible disability-related columns in current Census table:")
print(possible_columns if possible_columns else "NONE FOUND")

==========================================================================================
SEARCHING CENSUS WORKBOOK FOR DISABILITY DATA
==========================================================================================

Population workbook sheets:

NameError: name 'population_xls' is not defined

In [335]:
# ============================================================
# CELL 10 — SEARCH ORIGINAL POPULATION WORKBOOK FOR DISABILITY
# ============================================================

import pandas as pd
import os

population_file = "/Users/ohaseelanka/Downloads/GN_population_excel.xlsx"

# Open workbook structure
population_xls = pd.ExcelFile(population_file)

print("=" * 90)
print("ORIGINAL POPULATION WORKBOOK")
print("=" * 90)

print("\nFile:")
print(population_file)

print("\nAvailable sheets:")
for i, sheet in enumerate(population_xls.sheet_names, start=1):
    print(f"{i:02d}. {sheet}")

# ------------------------------------------------------------
# Search every sheet for disability-related words
# ------------------------------------------------------------

keywords = [
    "disab",
    "disabled",
    "disability",
    "impair",
    "difficulty"
]

print("\n" + "=" * 90)
print("DISABILITY SEARCH")
print("=" * 90)

found = []

for sheet in population_xls.sheet_names:

    try:
        temp = pd.read_excel(
            population_file,
            sheet_name=sheet,
            header=None
        )

        # Convert everything to lowercase strings
        text = temp.astype("string").fillna("")

        matches = text.apply(
            lambda col: col.str.contains(
                "|".join(keywords),
                case=False,
                regex=True,
                na=False
            ).any()
        )

        if matches.any():

            matched_columns = list(
                temp.columns[matches]
            )

            found.append({
                "sheet": sheet,
                "matched_columns": matched_columns
            })

            print(f"\nFOUND in sheet: {sheet}")
            print("Possible columns/locations:", matched_columns)

    except Exception as e:
        print(f"\nCould not read sheet '{sheet}': {e}")

if len(found) == 0:
    print("\nNO DISABILITY-RELATED CONTENT FOUND.")
else:
    print("\nDisability-related content was found.")

==========================================================================================
ORIGINAL POPULATION WORKBOOK
==========================================================================================

File:
/Users/ohaseelanka/Downloads/GN_population_excel.xlsx

Available sheets:
01. Population

==========================================================================================
DISABILITY SEARCH
==========================================================================================

NO DISABILITY-RELATED CONTENT FOUND.

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [336]:
# ============================================================
# CELL 11 — INSPECT REMAINING CENSUS FEATURES
# ============================================================

print("=" * 90)
print("CENSUS FEATURE DETAILS")
print("=" * 90)

feature_info = pd.DataFrame({
    "column": census_flood_std.columns,
    "dtype": census_flood_std.dtypes.astype(str).values,
    "non_null": census_flood_std.notna().sum().values,
    "unique_values": census_flood_std.nunique(dropna=True).values
})

display(
    feature_info.iloc[15:]
    .reset_index(drop=True)
)

==========================================================================================
CENSUS FEATURE DETAILS
==========================================================================================

                               column    dtype  non_null  unique_values
0           water_semi_protected_well    int64        65             63
1              water_unprotected_well    int64        65             59
2                     water_tube_well    int64        65             64
3               water_spring_fountain    int64        65             57
4         water_national_water_supply    int64        65             65
5               water_local_authority    int64        65             62
6        water_community_organization    int64        65             64
7                water_private_supply    int64        65             63
8             water_tank_river_stream    int64        65             49
9                    water_rain_water    int64        65             20
10                      water_bottled    int64        65             44
11              water_filter_ro_plant    int64        65             16
12                       water_bowser    int64        65             11
13                        water_other    int64        65             17
14                   cooking_firewood    int64        65             65
15                   cooking_kerosene    int64        65             55
16                        cooking_gas    int64        65             65
17                cooking_electricity    int64        65             53
18         cooking_sawdust_paddy_husk    int64        65             17
19                     cooking_biogas    int64        65             19
20                      cooking_other    int64        65             31
21               cooking_not_relevant    int64        65             63
22       lighting_national_grid_hydro    int64        65             65
23             lighting_kerosene_lamp    int64        65             59
24                lighting_solar_grid    int64        65             40
25          lighting_solar_standalone    int64        65             39
26                    lighting_biogas    int64        65             12
27                 lighting_generator    int64        65             18
28                     lighting_other    int64        65             54
29       toilet_within_unit_exclusive    int64        65             65
30          toilet_within_unit_shared    int64        65             64
31   toilet_within_premises_exclusive    int64        65             64
32      toilet_within_premises_shared    int64        65             63
33  toilet_no_toilet_shared_elsewhere    int64        65             64
34               toilet_common_public    int64        65             39
35                   toilet_no_toilet    int64        65             36
36                children_0_14_ratio  float64        65             65
37              elderly_60_plus_ratio  float64        65             65
38                       female_ratio  float64        65             65
39     households_per_1000_population  float64        65             65
40  housing_units_per_1000_population  float64        65             65
41        unprotected_well_households    int64        65             59
42      river_stream_water_households    int64        65             49
43               no_toilet_households    int64        65             36
44           public_toilet_households    int64        65             39
45             unprotected_well_ratio  float64        65             65
46           river_stream_water_ratio  float64        65             64
47                    no_toilet_ratio  float64        65             65
48                public_toilet_ratio  float64        65             62
49                           ds_match   object        65             65
50                       ds_match_std   string        65             65

In [337]:
# ============================================================
# CELL 12 — INSPECT QGIS FLOOD FEATURES
# ============================================================

print("=" * 90)
print("QGIS FLOOD FEATURE DETAILS")
print("=" * 90)

qgis_info = pd.DataFrame({
    "column": qgis_flood_std.columns,
    "dtype": qgis_flood_std.dtypes.astype(str).values,
    "non_null": qgis_flood_std.notna().sum().values,
    "unique_values": qgis_flood_std.nunique(dropna=True).values
})

display(qgis_info)

==========================================================================================
QGIS FLOOD FEATURE DETAILS
==========================================================================================

                  column    dtype  non_null  unique_values
0                    fid    int64        65             65
1              adm3_name   object        65             65
2             adm3_name1   object        65             65
3             adm3_name2   object        65             65
4             adm3_name3  float64         0              0
5             adm3_pcode   object        65             65
6              adm2_name   object        65              5
7             adm2_name1   object        65              5
8             adm2_name2   object        65              5
9             adm2_name3  float64         0              0
10            adm2_pcode   object        65              5
11             adm1_name   object        65              3
12            adm1_name1   object        65              3
13            adm1_name2   object        65              3
14            adm1_name3  float64         0              0
15            adm1_pcode   object        65              3
16             adm0_name   object        65              1
17            adm0_name1   object        65              1
18            adm0_name2   object        65              1
19            adm0_name3  float64         0              0
20            adm0_pcode   object        65              1
21              valid_on   object        65              1
22              valid_to  float64         0              0
23             area_sqkm  float64        65             65
24               version   object        65              1
25                  lang   object        65              1
26                 lang1   object        65              1
27                 lang2   object        65              1
28                 lang3  float64         0              0
29            center_lat  float64        65             65
30            center_lon  float64        65             65
31          total_road_m  float64        65             65
32                 COUNT    int64        65             64
33          road_density  float64        65             65
34        facility_count    int64        65             50
35  Hub distance_HubName   object        38             38
36  Hub distance_HubDist  float64        65             65
37      facility_density  float64        65             65
38              ds_match   object        65             65
39          ds_match_std   string        65             65

In [338]:
# ============================================================
# CELL 13 — CREATE CLEAN FLOOD DS FEATURE LIBRARY
# ============================================================

# ------------------------------------------------------------
# 1. Select Census features
# ------------------------------------------------------------

census_features = census_flood_std[
    [
        "district_name",
        "ds_name_join",
        "ds_code",
        "ds_match_std",
        "total_population",
        "number_of_households",
        "children_0_14_ratio",
        "elderly_60_plus_ratio",
        "female_ratio",
        "unprotected_well_ratio",
        "river_stream_water_ratio",
        "no_toilet_ratio",
        "public_toilet_ratio"
    ]
].copy()


# ------------------------------------------------------------
# 2. Select QGIS features
# ------------------------------------------------------------

qgis_features = qgis_flood_std[
    [
        "adm3_name",
        "adm3_pcode",
        "area_sqkm",
        "center_lat",
        "center_lon",
        "total_road_m",
        "road_density",
        "facility_count",
        "facility_density"
    ]
].copy()


# ------------------------------------------------------------
# 3. Merge Census + QGIS
# ------------------------------------------------------------

flood_ds_features = census_features.merge(
    qgis_features,
    left_on="ds_match_std",
    right_on="adm3_name",
    how="inner",
    validate="one_to_one"
)


# ------------------------------------------------------------
# 4. Rename identifiers clearly
# ------------------------------------------------------------

flood_ds_features = flood_ds_features.rename(
    columns={
        "ds_name_join": "census_ds_name",
        "ds_match_std": "ds_name",
        "adm3_name": "qgis_ds_name"
    }
)


# ------------------------------------------------------------
# 5. Arrange columns
# ------------------------------------------------------------

flood_ds_features = flood_ds_features[
    [
        "district_name",
        "ds_name",
        "census_ds_name",
        "qgis_ds_name",
        "ds_code",
        "adm3_pcode",

        # Exposure
        "total_population",
        "number_of_households",

        # Sensitivity
        "children_0_14_ratio",
        "elderly_60_plus_ratio",
        "female_ratio",
        "unprotected_well_ratio",
        "river_stream_water_ratio",
        "no_toilet_ratio",
        "public_toilet_ratio",

        # Infrastructure / spatial context
        "area_sqkm",
        "total_road_m",
        "road_density",
        "facility_count",
        "facility_density",

        # Mapping
        "center_lat",
        "center_lon"
    ]
].copy()


# ------------------------------------------------------------
# 6. Check result
# ------------------------------------------------------------

print("=" * 90)
print("FLOOD DS FEATURE LIBRARY")
print("=" * 90)

print("Shape:", flood_ds_features.shape)

print("\nUnique DS:", flood_ds_features["ds_name"].nunique())

print("\nMissing values:")
display(
    flood_ds_features.isna()
    .sum()
    .to_frame("missing")
    .query("missing > 0")
)

print("\nDuplicate DS names:",
      flood_ds_features["ds_name"].duplicated().sum())

print("\nDuplicate PCODEs:",
      flood_ds_features["adm3_pcode"].duplicated().sum())

print("\nDistrict distribution:")
display(
    flood_ds_features["district_name"]
    .value_counts()
    .sort_index()
    .to_frame("DS_count")
)

print("\nFirst 10 rows:")
display(
    flood_ds_features.head(10)
)

print("\n" + "=" * 90)

==========================================================================================
FLOOD DS FEATURE LIBRARY
==========================================================================================
Shape: (65, 22)

Unique DS: 65

Missing values:

Empty DataFrame
Columns: [missing]
Index: []

Duplicate DS names: 0

Duplicate PCODEs: 0

District distribution:

               DS_count
district_name
Colombo              13
Gampaha              13
Kegalle              11
Nuwara Eliya         10
Ratnapura            18

First 10 rows:

,district_name,ds_name,census_ds_name,qgis_ds_name,ds_code,adm3_pcode,total_population,number_of_households,children_0_14_ratio,elderly_60_plus_ratio,female_ratio,unprotected_well_ratio,river_stream_water_ratio,no_toilet_ratio,public_toilet_ratio,area_sqkm,total_road_m,road_density,facility_count,facility_density,center_lat,center_lon
0,Colombo,Colombo,Colombo,Colombo,3,LK1103,292089,72479,0.207902,0.155323,0.502213,0.000110,0.000069,0.000510,0.035528,24.537151,4.004475e+05,16.320050,213,8.680714,6.946987,79.865263
1,Colombo,Dehiwala,Dehiwala,Dehiwala,30,LK1130,93815,25565,0.163428,0.203741,0.518467,0.000196,0.000078,0.000156,0.002582,8.458706,1.601775e+05,18.936403,36,4.255970,6.856856,79.871595
2,Colombo,Homagama,Homagama,Homagama,12,LK1112,280771,80298,0.160910,0.186543,0.512792,0.001768,0.000037,0.000286,0.000075,120.316227,9.303959e+05,7.732922,96,0.797897,6.836353,80.024442
3,Colombo,Kaduwela,Kaduwela,Kaduwela,9,LK1109,277918,80373,0.147558,0.203010,0.511687,0.000771,0.000037,0.000348,0.000137,86.737826,1.016346e+06,11.717451,219,2.524850,6.901985,79.972773
4,Colombo,Kesbewa,Kesbewa,Kesbewa,36,LK1136,263541,76405,0.151339,0.211045,0.520147,0.000654,0.000065,0.000183,0.000196,61.408264,6.686632e+05,10.888814,74,1.205050,6.804772,79.927436
5,Colombo,Kolonnawa,Kolonnawa,Kolonnawa,6,LK1106,214070,56756,0.189938,0.166133,0.511080,0.000141,0.000088,0.000317,0.009796,25.928037,3.693511e+05,14.245240,56,2.159824,6.934943,79.914709
6,Colombo,Maharagama,Maharagama,Maharagama,21,LK1121,196500,57114,0.136539,0.216300,0.525547,0.000298,0.000105,0.000158,0.000105,37.796756,5.274490e+05,13.954874,83,2.195956,6.855809,79.943828
7,Colombo,Moratuwa,Moratuwa,Moratuwa,33,LK1133,160199,44872,0.163790,0.195376,0.515727,0.000067,0.000067,0.000357,0.002273,19.303715,2.662371e+05,13.792011,42,2.175747,6.767099,79.886569
8,Colombo,Padukka,Padukka,Padukka,18,LK1118,73014,20880,0.177117,0.191306,0.514463,0.003927,0.002059,0.000287,0.000192,106.194605,3.417257e+05,3.217920,37,0.348417,6.829202,80.122845
9,Colombo,Ratmalana,Ratmalana,Ratmalana,31,LK1131,88063,25358,0.158148,0.205171,0.512417,0.000552,0.000000,0.000749,0.002839,12.862515,2.051699e+05,15.950996,130,10.106888,6.827587,79.879129

==========================================================================================

In [339]:
# ============================================================
# CELL 14 — FLOOD DS FEATURE CORRELATION ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

# Candidate numerical variables
candidate_features = [
    "total_population",
    "number_of_households",
    "children_0_14_ratio",
    "elderly_60_plus_ratio",
    "female_ratio",
    "unprotected_well_ratio",
    "river_stream_water_ratio",
    "no_toilet_ratio",
    "public_toilet_ratio",
    "area_sqkm",
    "total_road_m",
    "road_density",
    "facility_count",
    "facility_density"
]

corr = flood_ds_features[candidate_features].corr(
    method="pearson"
)

print("=" * 90)
print("CORRELATION MATRIX")
print("=" * 90)

display(corr.round(3))


# ------------------------------------------------------------
# Find highly correlated pairs
# ------------------------------------------------------------

print("\n" + "=" * 90)
print("HIGHLY CORRELATED FEATURE PAIRS (|r| >= 0.80)")
print("=" * 90)

high_corr_pairs = []

for i in range(len(candidate_features)):
    for j in range(i + 1, len(candidate_features)):

        feature_a = candidate_features[i]
        feature_b = candidate_features[j]

        r = corr.loc[feature_a, feature_b]

        if abs(r) >= 0.80:
            high_corr_pairs.append({
                "feature_1": feature_a,
                "feature_2": feature_b,
                "correlation": round(r, 3)
            })

high_corr_df = pd.DataFrame(high_corr_pairs)

if len(high_corr_df) > 0:
    display(
        high_corr_df.sort_values(
            "correlation",
            key=lambda x: x.abs(),
            ascending=False
        ).reset_index(drop=True)
    )
else:
    print("No feature pairs reached |r| >= 0.80.")

print("\n" + "=" * 90)

==========================================================================================
CORRELATION MATRIX
==========================================================================================

,total_population,number_of_households,children_0_14_ratio,elderly_60_plus_ratio,female_ratio,unprotected_well_ratio,river_stream_water_ratio,no_toilet_ratio,public_toilet_ratio,area_sqkm,total_road_m,road_density,facility_count,facility_density
total_population,1.000,0.996,-0.434,-0.264,0.082,-0.573,-0.391,-0.293,0.295,-0.229,0.707,0.619,0.480,0.398
number_of_households,0.996,1.000,-0.460,-0.240,0.092,-0.568,-0.397,-0.305,0.236,-0.222,0.727,0.605,0.476,0.375
children_0_14_ratio,-0.434,-0.460,1.000,-0.458,0.040,0.390,0.659,0.672,0.058,0.559,-0.109,-0.649,-0.296,-0.392
elderly_60_plus_ratio,-0.264,-0.240,-0.458,1.000,0.362,0.231,-0.312,-0.272,-0.350,-0.304,-0.387,-0.003,0.004,0.036
female_ratio,0.082,0.092,0.040,0.362,1.000,-0.025,-0.040,0.184,-0.247,-0.041,0.071,0.006,0.118,-0.020
unprotected_well_ratio,-0.573,-0.568,0.390,0.231,-0.025,1.000,0.332,0.221,-0.229,0.371,-0.322,-0.650,-0.360,-0.413
river_stream_water_ratio,-0.391,-0.397,0.659,-0.312,-0.040,0.332,1.000,0.806,-0.034,0.525,0.040,-0.424,-0.198,-0.269
no_toilet_ratio,-0.293,-0.305,0.672,-0.272,0.184,0.221,0.806,1.000,0.022,0.407,0.066,-0.359,-0.163,-0.223
public_toilet_ratio,0.295,0.236,0.058,-0.350,-0.247,-0.229,-0.034,0.022,1.000,-0.241,-0.045,0.435,0.230,0.532
area_sqkm,-0.229,-0.222,0.559,-0.304,-0.041,0.371,0.525,0.407,-0.241,1.000,0.331,-0.672,-0.234,-0.448
total_road_m,0.707,0.727,-0.109,-0.387,0.071,-0.322,0.040,0.066,-0.045,0.331,1.000,0.155,0.471,0.096
road_density,0.619,0.605,-0.649,-0.003,0.006,-0.650,-0.424,-0.359,0.435,-0.672,0.155,1.000,0.503,0.754
facility_count,0.480,0.476,-0.296,0.004,0.118,-0.360,-0.198,-0.163,0.230,-0.234,0.471,0.503,1.000,0.732
facility_density,0.398,0.375,-0.392,0.036,-0.020,-0.413,-0.269,-0.223,0.532,-0.448,0.096,0.754,0.732,1.000

==========================================================================================
HIGHLY CORRELATED FEATURE PAIRS (|r| >= 0.80)
==========================================================================================

                  feature_1             feature_2  correlation
0          total_population  number_of_households        0.996
1  river_stream_water_ratio       no_toilet_ratio        0.806

==========================================================================================

In [340]:
# ============================================================
# CELL 15 — FINALIZE FLOOD DS FEATURE LIBRARY
# ============================================================

final_flood_ds_features = flood_ds_features[
    [
        # ----------------------------------------------------
        # Identifiers
        # ----------------------------------------------------
        "district_name",
        "ds_name",
        "census_ds_name",
        "qgis_ds_name",
        "ds_code",
        "adm3_pcode",

        # ----------------------------------------------------
        # EXPOSURE
        # ----------------------------------------------------
        "total_population",

        # ----------------------------------------------------
        # SENSITIVITY
        # ----------------------------------------------------
        "children_0_14_ratio",
        "elderly_60_plus_ratio",
        "female_ratio",
        "unprotected_well_ratio",
        "no_toilet_ratio",
        "public_toilet_ratio",

        # ----------------------------------------------------
        # INFRASTRUCTURE / SPATIAL CONTEXT
        # ----------------------------------------------------
        "area_sqkm",
        "road_density",
        "facility_density",

        # ----------------------------------------------------
        # MAPPING ONLY
        # Not used directly as model predictors
        # ----------------------------------------------------
        "center_lat",
        "center_lon"
    ]
].copy()


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

output_path = (
    "data/processed/flood_ds_features.parquet"
)

final_flood_ds_features.to_parquet(
    output_path,
    index=False
)


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

print("=" * 90)
print("FINAL FLOOD DS FEATURE LIBRARY")
print("=" * 90)

print("Saved to:", output_path)
print("Shape:", final_flood_ds_features.shape)
print("Unique DS:", final_flood_ds_features["ds_name"].nunique())

print("\nMissing values:")
display(
    final_flood_ds_features.isna()
    .sum()
    .to_frame("missing")
    .query("missing > 0")
)

print("\nPredictor columns:")
predictor_columns = [
    "total_population",
    "children_0_14_ratio",
    "elderly_60_plus_ratio",
    "female_ratio",
    "unprotected_well_ratio",
    "no_toilet_ratio",
    "public_toilet_ratio",
    "area_sqkm",
    "road_density",
    "facility_density"
]

for i, col in enumerate(predictor_columns, start=1):
    print(f"{i:02d}. {col}")

print("\n" + "=" * 90)
print("FLOOD DS FEATURE LIBRARY READY")
print("=" * 90)

OSError: Cannot save file into a non-existent directory: 'data/processed'

In [341]:
from pathlib import Path

processed_dir = Path("data/processed")

processed_dir.mkdir(
    parents=True,
    exist_ok=True
)

print("Processed directory:", processed_dir.resolve())
print("Directory exists:", processed_dir.exists())

Processed directory: /Users/ohaseelanka/disaster_analytics_hub/notebooks/data/processed
Directory exists: True

In [342]:
# ============================================================
# CELL 15B — SAVE FINAL FLOOD DS FEATURE LIBRARY
# ============================================================

from pathlib import Path

# ------------------------------------------------------------
# Final flood DS predictors
# ------------------------------------------------------------

predictor_columns = [
    "total_population",
    "children_0_14_ratio",
    "elderly_60_plus_ratio",
    "female_ratio",
    "unprotected_well_ratio",
    "no_toilet_ratio",
    "public_toilet_ratio",
    "area_sqkm",
    "road_density",
    "facility_density"
]

# ------------------------------------------------------------
# Create final dataset
# ------------------------------------------------------------

final_flood_ds_features = flood_ds_features[
    [
        # Identifiers
        "district_name",
        "ds_name",
        "census_ds_name",
        "qgis_ds_name",
        "ds_code",
        "adm3_pcode",

        # Exposure
        "total_population",

        # Sensitivity
        "children_0_14_ratio",
        "elderly_60_plus_ratio",
        "female_ratio",
        "unprotected_well_ratio",
        "no_toilet_ratio",
        "public_toilet_ratio",

        # Infrastructure / spatial context
        "area_sqkm",
        "road_density",
        "facility_density",

        # Mapping only
        "center_lat",
        "center_lon"
    ]
].copy()

# ------------------------------------------------------------
# Correct project-level path
# ------------------------------------------------------------

project_root = Path.cwd().parent

processed_dir = project_root / "data" / "processed"
processed_dir.mkdir(
    parents=True,
    exist_ok=True
)

output_path = processed_dir / "flood_ds_features.parquet"

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

final_flood_ds_features.to_parquet(
    output_path,
    index=False
)

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

print("=" * 90)
print("FINAL FLOOD DS FEATURE LIBRARY")
print("=" * 90)

print("Saved to:")
print(output_path.resolve())

print("\nShape:")
print(final_flood_ds_features.shape)

print("\nUnique DS divisions:")
print(final_flood_ds_features["ds_name"].nunique())

print("\nMissing values:")
missing_values = (
    final_flood_ds_features
    .isna()
    .sum()
    .to_frame("missing")
)

display(
    missing_values[
        missing_values["missing"] > 0
    ]
)

print("\nPredictor columns:")
for i, col in enumerate(predictor_columns, start=1):
    print(f"{i:02d}. {col}")

print("\nFile exists:")
print(output_path.exists())

print("\n"

_IncompleteInputError: incomplete input (3062473737.py, line 121)

In [343]:
from pathlib import Path

# Final predictors
predictor_columns = [
    "total_population",
    "children_0_14_ratio",
    "elderly_60_plus_ratio",
    "female_ratio",
    "unprotected_well_ratio",
    "no_toilet_ratio",
    "public_toilet_ratio",
    "area_sqkm",
    "road_density",
    "facility_density"
]

# Create final flood DS feature library
final_flood_ds_features = flood_ds_features[
    [
        "district_name",
        "ds_name",
        "census_ds_name",
        "qgis_ds_name",
        "ds_code",
        "adm3_pcode",
        "total_population",
        "children_0_14_ratio",
        "elderly_60_plus_ratio",
        "female_ratio",
        "unprotected_well_ratio",
        "no_toilet_ratio",
        "public_toilet_ratio",
        "area_sqkm",
        "road_density",
        "facility_density",
        "center_lat",
        "center_lon"
    ]
].copy()

# Project root = one level above notebooks
project_root = Path.cwd().parent

# Create project-level processed folder
processed_dir = project_root / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

# Output file
output_path = processed_dir / "flood_ds_features.parquet"

# Save
final_flood_ds_features.to_parquet(
    output_path,
    index=False
)

# Results
print("=" * 80)
print("FINAL FLOOD DS FEATURE LIBRARY")
print("=" * 80)

print("Saved to:")
print(output_path.resolve())

print("\nShape:")
print(final_flood_ds_features.shape)

print("\nUnique DS divisions:")
print(final_flood_ds_features["ds_name"].nunique())

print("\nMissing values:")
missing = final_flood_ds_features.isna().sum()
display(missing[missing > 0].to_frame("missing"))

print("\nPredictors:")
for i, col in enumerate(predictor_columns, 1):
    print(f"{i}. {col}")

print("\nFile exists:")
print(output_path.exists())

print("=" * 80)

================================================================================
FINAL FLOOD DS FEATURE LIBRARY
================================================================================
Saved to:
/Users/ohaseelanka/disaster_analytics_hub/data/processed/flood_ds_features.parquet

Shape:
(65, 18)

Unique DS divisions:
65

Missing values:

Empty DataFrame
Columns: [missing]
Index: []

Predictors:
1. total_population
2. children_0_14_ratio
3. elderly_60_plus_ratio
4. female_ratio
5. unprotected_well_ratio
6. no_toilet_ratio
7. public_toilet_ratio
8. area_sqkm
9. road_density
10. facility_density

File exists:
True
================================================================================

In [344]:
# ============================================================
# CELL 16 — INSPECT REGIONAL FLOOD EPISODES
# ============================================================

import pandas as pd

episode_path = (
    "data/interim/flood/kelani/flood_regional_episodes.parquet"
)

flood_episodes = pd.read_parquet(episode_path)

print("=" * 90)
print("REGIONAL FLOOD EPISODES")
print("=" * 90)

print("Shape:", flood_episodes.shape)

print("\nColumns:")
for i, col in enumerate(flood_episodes.columns, 1):
    print(f"{i:02d}. {col}")

print("\nFirst 10 episodes:")
display(flood_episodes.head(10))

print("\nData types:")
display(
    flood_episodes.dtypes
    .to_frame("dtype")
)

print("\nDate range:")
print("Minimum:", flood_episodes["start_date"].min())
print("Maximum:", flood_episodes["end_date"].max())

print("\nNumber of unique episodes:")
print(flood_episodes["episode_id"].nunique())

print("=" * 90)

FileNotFoundError: [Errno 2] No such file or directory: 'data/interim/flood/kelani/flood_regional_episodes.parquet'

In [345]:
# ============================================================
# CELL 16A — LOAD REGIONAL FLOOD EPISODES
# ============================================================

from pathlib import Path
import pandas as pd

# Project root
project_root = Path.cwd().parent

# Correct project-level path
episode_path = (
    project_root
    / "data"
    / "interim"
    / "flood"
    / "kelani"
    / "flood_regional_episodes.parquet"
)

print("Looking for:")
print(episode_path.resolve())

print("\nFile exists:")
print(episode_path.exists())

# Load only if the file exists
if episode_path.exists():
    flood_episodes = pd.read_parquet(episode_path)

    print("\n" + "=" * 90)
    print("REGIONAL FLOOD EPISODES")
    print("=" * 90)

    print("Shape:", flood_episodes.shape)

    print("\nColumns:")
    for i, col in enumerate(flood_episodes.columns, 1):
        print(f"{i:02d}. {col}")

    print("\nFirst 10 episodes:")
    display(flood_episodes.head(10))

    print("\nData types:")
    display(flood_episodes.dtypes.to_frame("dtype"))

    print("\n" + "=" * 90)
else:
    print("\nERROR: The flood episode file was not found.")

Looking for:
/Users/ohaseelanka/disaster_analytics_hub/data/interim/flood/kelani/flood_regional_episodes.parquet

File exists:
True

==========================================================================================
REGIONAL FLOOD EPISODES
==========================================================================================
Shape: (30, 11)

Columns:
01. regional_episode_id
02. start_date
03. end_date
04. station_count
05. station_event_count
06. stations
07. max_rainfall_3d
08. max_rainfall_7d
09. max_wl_zscore
10. max_q_zscore
11. duration_days

First 10 episodes:

  regional_episode_id start_date   end_date  station_count  station_event_count                            stations  max_rainfall_3d  max_rainfall_7d  max_wl_zscore  max_q_zscore  duration_days
0        KELANI_EP001 2015-06-05 2015-06-05              1                    1                                KN16            154.1            248.1       1.836118      2.146417              1
1        KELANI_EP002 2015-10-13 2015-10-13              1                    1                                KN07            174.1            232.9       1.714657      2.532219              1
2        KELANI_EP003 2015-10-19 2015-10-24              3                    7                    KN02, KN18, KN21            200.7            332.9       2.755908      2.848592              6
3        KELANI_EP004 2015-11-02 2015-11-03              1                    1                                KN11            130.1            188.8       2.796370      3.501046              2
4        KELANI_EP005 2015-11-06 2015-11-07              1                    1                                KN07            182.8            227.2       1.509299      2.030471              2
5        KELANI_EP006 2015-11-13 2015-11-14              1                    1                                KN11            119.6            154.1       3.052885      2.744790              2
6        KELANI_EP007 2015-12-01 2015-12-01              1                    1                                KN11            117.2            117.2       2.698783      2.245964              1
7        KELANI_EP008 2015-12-14 2015-12-14              1                    1                                KN11            119.5            173.3       4.664466      5.546578              1
8        KELANI_EP009 2016-05-12 2016-05-31              6                   12  KN02, KN07, KN11, KN16, KN18, KN21            523.9            884.8      10.246449     18.658252             20
9        KELANI_EP010 2017-05-24 2017-06-03              6                   11  KN02, KN07, KN11, KN16, KN18, KN21            450.7            623.3       6.921974      9.254390             11

Data types:

                              dtype
regional_episode_id          object
start_date           datetime64[ns]
end_date             datetime64[ns]
station_count                 int64
station_event_count           int64
stations                     object
max_rainfall_3d             float64
max_rainfall_7d             float64
max_wl_zscore               float64
max_q_zscore                float64
duration_days                 int64

==========================================================================================

In [346]:
# ============================================================
# CELL 17 — INSPECT FLOOD EPISODE STATION PARTICIPATION
# ============================================================

print("=" * 90)
print("STATION PARTICIPATION IN REGIONAL FLOOD EPISODES")
print("=" * 90)

# Count how many regional episodes involved each station
station_counts = {}

for stations in flood_episodes["stations"].dropna():

    for station in stations.split(","):

        station = station.strip()

        station_counts[station] = (
            station_counts.get(station, 0) + 1
        )

station_counts_df = (
    pd.DataFrame(
        list(station_counts.items()),
        columns=["station", "episode_count"]
    )
    .sort_values(
        "episode_count",
        ascending=False
    )
    .reset_index(drop=True)
)

display(station_counts_df)

print("\nNumber of stations represented:")
print(len(station_counts_df))

print("\nStation list:")
print(
    station_counts_df["station"].tolist()
)

print("\n" + "=" * 90)
print("EPISODES BY STATION COUNT")
print("=" * 90)

display(
    flood_episodes[
        [
            "regional_episode_id",
            "start_date",
            "end_date",
            "station_count",
            "stations",
            "max_rainfall_3d",
            "max_rainfall_7d",
            "max_wl_zscore",
            "max_q_zscore"
        ]
    ]
    .sort_values(
        ["station_count", "start_date"],
        ascending=[False, True]
    )
    .reset_index(drop=True)
)

print("=" * 90)

==========================================================================================
STATION PARTICIPATION IN REGIONAL FLOOD EPISODES
==========================================================================================

  station  episode_count
0    KN16             13
1    KN07             13
2    KN18             13
3    KN11             13
4    KN02             12
5    KN21              7

Number of stations represented:
6

Station list:
['KN16', 'KN07', 'KN18', 'KN11', 'KN02', 'KN21']

==========================================================================================
EPISODES BY STATION COUNT
==========================================================================================

   regional_episode_id start_date   end_date  station_count                            stations  max_rainfall_3d  max_rainfall_7d  max_wl_zscore  max_q_zscore
0         KELANI_EP009 2016-05-12 2016-05-31              6  KN02, KN07, KN11, KN16, KN18, KN21            523.9            884.8      10.246449     18.658252
1         KELANI_EP010 2017-05-24 2017-06-03              6  KN02, KN07, KN11, KN16, KN18, KN21            450.7            623.3       6.921974      9.254390
2         KELANI_EP018 2018-05-20 2018-05-27              6  KN02, KN07, KN11, KN16, KN18, KN21            529.7            784.4       8.120074     12.883982
3         KELANI_EP011 2017-09-07 2017-09-10              4              KN07, KN16, KN18, KN21            294.0            382.7       3.707726      4.368024
4         KELANI_EP014 2017-10-14 2017-10-16              4              KN02, KN07, KN16, KN18            246.7            302.3       3.849181      4.263227
5         KELANI_EP026 2019-09-16 2019-09-16              4              KN02, KN11, KN16, KN18            161.3            267.7       3.084490      2.906143
6         KELANI_EP029 2019-10-13 2019-10-24              4              KN07, KN11, KN16, KN18            194.5            320.5       3.651233      3.847054
7         KELANI_EP003 2015-10-19 2015-10-24              3                    KN02, KN18, KN21            200.7            332.9       2.755908      2.848592
8         KELANI_EP012 2017-09-13 2017-09-14              3                    KN11, KN18, KN21            188.4            277.0       2.943577      3.125998
9         KELANI_EP019 2018-06-02 2018-06-10              3                    KN02, KN07, KN16            325.9            536.9       5.052393      5.939432
10        KELANI_EP021 2018-10-05 2018-10-07              3                    KN11, KN16, KN18            198.4            366.7       2.622790      2.517843
11        KELANI_EP025 2019-08-12 2019-08-14              3                    KN02, KN07, KN11            248.8            332.1       3.924183      4.247715
12        KELANI_EP013 2017-09-27 2017-09-27              2                          KN07, KN16            216.1            246.9       2.497697      2.560111
13        KELANI_EP024 2019-07-18 2019-07-20              2                          KN02, KN07            203.3            266.1       3.207034      3.385474
14        KELANI_EP027 2019-09-24 2019-09-25              2                          KN18, KN21            194.9            254.9       2.685793      2.701870
15        KELANI_EP030 2019-11-30 2019-12-01              2                          KN11, KN18            172.4            273.9       2.961774      3.398996
16        KELANI_EP001 2015-06-05 2015-06-05              1                                KN16            154.1            248.1       1.836118      2.146417
17        KELANI_EP002 2015-10-13 2015-10-13              1                                KN07            174.1            232.9       1.714657      2.532219
18        KELANI_EP004 2015-11-02 2015-11-03              1                                KN11            130.1            188.8       2.796370      3.501046
19        KELANI_EP005 2015-11-06 2015-11-07              1                                KN07            182.8            227.2       1.509299      2.030471
20        KELANI_EP006 2015-11-13 2015-11-14              1                                KN11            119.6            154.1       3.052885      2.744790
21        KELANI_EP007 2015-12-01 2015-12-01              1                                KN11            117.2            117.2       2.698783      2.245964
22        KELANI_EP008 2015-12-14 2015-12-14              1                                KN11            119.5            173.3       4.664466      5.546578
23        KELANI_EP015 2017-10-19 2017-10-19              1                                KN07            104.9            310.0       1.804822      1.007463
24        KELANI_EP016 2017-11-30 2017-12-01              1                                KN02             94.6            122.1       5.090774      8.889795
25        KELANI_EP017 2018-05-16 2018-05-16              1                                KN16            281.5            431.7       1.782757      1.754869
26        KELANI_EP020 2018-08-15 2018-08-20              1                                KN02            191.3            349.5       3.545722      3.471095
27        KELANI_EP022 2018-10-22 2018-10-22              1                                KN02             90.4            139.0       1.945871      1.302015
28        KELANI_EP023 2018-11-24 2018-11-24              1                                KN18            206.4            303.4       2.115706      1.790975
29        KELANI_EP028 2019-10-08 2019-10-08              1                                KN16            157.3            269.5       1.815138      1.741773

==========================================================================================

In [347]:
# ============================================================
# CELL 18 — KELANI STATION HYDROLOGICAL METADATA
# ============================================================

station_metadata = pd.DataFrame({
    "station": [
        "KN02",
        "KN07",
        "KN11",
        "KN16",
        "KN18",
        "KN21"
    ],

    "station_name": [
        "Norwood",
        "Kitulgala",
        "Holombuwa",
        "Deraniyagala",
        "Glencourse",
        "Hanwella"
    ],

    "river_reach": [
        "Kehelgamu Oya",
        "Kelani Ganga Upper",
        "Gurugoda Oya",
        "Seethawaka Ganga",
        "Kelani Ganga Midstream",
        "Kelani Ganga Lower"
    ],

    "x": [
        182051,
        160270,
        143948,
        152036,
        135963,
        123689
    ],

    "y": [
        182230,
        198922,
        220765,
        191688,
        197396,
        189980
    ]
})

print("=" * 90)
print("KELANI FLOOD STATION METADATA")
print("=" * 90)

display(station_metadata)

print("\nStation coordinates:")
display(
    station_metadata[
        ["station", "station_name", "x", "y"]
    ]
)

print("\nHydrological reaches:")
display(
    station_metadata[
        ["station", "station_name", "river_reach"]
    ]
)

print("=" * 90)

==========================================================================================
KELANI FLOOD STATION METADATA
==========================================================================================

  station  station_name             river_reach       x       y
0    KN02       Norwood           Kehelgamu Oya  182051  182230
1    KN07     Kitulgala      Kelani Ganga Upper  160270  198922
2    KN11     Holombuwa            Gurugoda Oya  143948  220765
3    KN16  Deraniyagala        Seethawaka Ganga  152036  191688
4    KN18    Glencourse  Kelani Ganga Midstream  135963  197396
5    KN21      Hanwella      Kelani Ganga Lower  123689  189980

Station coordinates:

  station  station_name       x       y
0    KN02       Norwood  182051  182230
1    KN07     Kitulgala  160270  198922
2    KN11     Holombuwa  143948  220765
3    KN16  Deraniyagala  152036  191688
4    KN18    Glencourse  135963  197396
5    KN21      Hanwella  123689  189980

Hydrological reaches:

  station  station_name             river_reach
0    KN02       Norwood           Kehelgamu Oya
1    KN07     Kitulgala      Kelani Ganga Upper
2    KN11     Holombuwa            Gurugoda Oya
3    KN16  Deraniyagala        Seethawaka Ganga
4    KN18    Glencourse  Kelani Ganga Midstream
5    KN21      Hanwella      Kelani Ganga Lower

==========================================================================================

In [348]:
# ============================================================
# CELL 19 — INSPECT FLOOD DS DIVISIONS
# ============================================================

print("=" * 90)
print("65 FLOOD-STUDY DS DIVISIONS")
print("=" * 90)

ds_overview = (
    final_flood_ds_features[
        [
            "district_name",
            "ds_name",
            "ds_code",
            "adm3_pcode",
            "center_lat",
            "center_lon"
        ]
    ]
    .sort_values(
        ["district_name", "ds_name"]
    )
    .reset_index(drop=True)
)

print("Total DS divisions:", len(ds_overview))

print("\nDS divisions by district:")
display(
    ds_overview
    .groupby("district_name")
    .size()
    .to_frame("ds_count")
)

print("\nComplete DS list:")
display(ds_overview)

print("=" * 90)

==========================================================================================
65 FLOOD-STUDY DS DIVISIONS
==========================================================================================
Total DS divisions: 65

DS divisions by district:

               ds_count
district_name
Colombo              13
Gampaha              13
Kegalle              11
Nuwara Eliya         10
Ratnapura            18

Complete DS list:

   district_name      ds_name  ds_code adm3_pcode  center_lat  center_lon
0        Colombo      Colombo        3     LK1103    6.946987   79.865263
1        Colombo     Dehiwala       30     LK1130    6.856856   79.871595
2        Colombo     Homagama       12     LK1112    6.836353   80.024442
3        Colombo     Kaduwela        9     LK1109    6.901985   79.972773
4        Colombo      Kesbewa       36     LK1136    6.804772   79.927436
..           ...          ...      ...        ...         ...         ...
60     Ratnapura  Nivithigala       36     LK9136    6.556131   80.458402
61     Ratnapura    Opanayake       21     LK9121    6.606780   80.620244
62     Ratnapura   Pelmadulla       24     LK9124    6.639002   80.493516
63     Ratnapura    Ratnapura       12     LK9112    6.742331   80.484428
64     Ratnapura   Weligepola       45     LK9145    6.541747   80.725760

[65 rows x 6 columns]

==========================================================================================

In [349]:
# ============================================================
# CELL 20 — INSPECT QGIS FEATURE LIBRARY FOR HYDROLOGICAL DATA
# ============================================================

from pathlib import Path
import pandas as pd

qgis_path = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/ds79_feature_matrix.csv"
)

print("=" * 90)
print("QGIS DS FEATURE LIBRARY")
print("=" * 90)

print("File exists:", qgis_path.exists())
print("Path:", qgis_path)

qgis_all = pd.read_csv(qgis_path)

print("\nShape:", qgis_all.shape)

print("\nAll columns:")
for i, col in enumerate(qgis_all.columns, 1):
    print(f"{i:02d}. {col}")

print("\nPotential hydrological / river-related columns:")

hydro_keywords = [
    "river",
    "stream",
    "water",
    "basin",
    "catch",
    "drain",
    "hydro",
    "flood",
    "ganga",
    "oya"
]

hydro_columns = [
    col
    for col in qgis_all.columns
    if any(
        keyword in col.lower()
        for keyword in hydro_keywords
    )
]

if hydro_columns:
    for col in hydro_columns:
        print("-", col)
else:
    print("No obvious hydrological columns found.")

print("=" * 90)

==========================================================================================
QGIS DS FEATURE LIBRARY
==========================================================================================
File exists: True
Path: /Users/ohaseelanka/Desktop/disaster_project_gis/ds79_feature_matrix.csv

Shape: (79, 38)

All columns:
01. fid
02. adm3_name
03. adm3_name1
04. adm3_name2
05. adm3_name3
06. adm3_pcode
07. adm2_name
08. adm2_name1
09. adm2_name2
10. adm2_name3
11. adm2_pcode
12. adm1_name
13. adm1_name1
14. adm1_name2
15. adm1_name3
16. adm1_pcode
17. adm0_name
18. adm0_name1
19. adm0_name2
20. adm0_name3
21. adm0_pcode
22. valid_on
23. valid_to
24. area_sqkm
25. version
26. lang
27. lang1
28. lang2
29. lang3
30. center_lat
31. center_lon
32. total_road_m
33. COUNT
34. road_density
35. facility_count
36. Hub distance_HubName
37. Hub distance_HubDist
38. facility_density

Potential hydrological / river-related columns:
No obvious hydrological columns found.
==========================================================================================

In [350]:
# ============================================================
# CELL 21 — CHECK AVAILABLE GIS FILES
# ============================================================

from pathlib import Path

search_roots = [
    Path("/Users/ohaseelanka/Desktop/disaster_project_gis"),
    Path("/Users/ohaseelanka/disaster_analytics_hub/gis")
]

gis_extensions = {
    ".shp",
    ".gpkg",
    ".geojson",
    ".json",
    ".kml",
    ".kmz"
}

print("=" * 90)
print("AVAILABLE GIS FILES")
print("=" * 90)

found_files = []

for root in search_roots:

    if not root.exists():
        continue

    for path in root.rglob("*"):

        if path.is_file() and path.suffix.lower() in gis_extensions:
            found_files.append(path)

if found_files:

    for path in sorted(found_files):
        print(path)

else:
    print("No GIS spatial files found in the checked folders.")

print("\nTotal spatial files found:", len(found_files))

print("=" * 90)

==========================================================================================
AVAILABLE GIS FILES
==========================================================================================
/Users/ohaseelanka/Desktop/disaster_project_gis/ds_79_target_divisions.gpkg
/Users/ohaseelanka/Desktop/disaster_project_gis/ds_79_target_divisions.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin0.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin2.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin3.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin4.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_adminlines.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_adminpoints.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_adminareas_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_buildings_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_landuse_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_natural_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_natural_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_places_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_places_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_pofw_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_pofw_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_pois_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_pois_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_protected_areas_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_railways_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_roads_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_traffic_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_traffic_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_transport_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_transport_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_water_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_waterways_free_1.shp

Total spatial files found: 29
==========================================================================================

In [351]:
# ============================================================
# CELL 22 — INSPECT WATERWAYS GIS LAYER
# ============================================================

import geopandas as gpd
from pathlib import Path

waterways_path = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/"
    "sri-lanka-260928-free.shp/"
    "gis_osm_waterways_free_1.shp"
)

print("=" * 90)
print("WATERWAYS GIS LAYER")
print("=" * 90)

print("File exists:")
print(waterways_path.exists())

# Load layer
waterways = gpd.read_file(waterways_path)

print("\nShape:")
print(waterways.shape)

print("\nCRS:")
print(waterways.crs)

print("\nColumns:")
for i, col in enumerate(waterways.columns, 1):
    print(f"{i:02d}. {col}")

print("\nGeometry types:")
display(
    waterways.geometry.geom_type.value_counts()
)

print("\nFirst 10 records:")
display(
    waterways.head(10)
)

print("=" * 90)

ModuleNotFoundError: No module named 'geopandas'

In [352]:
# ============================================================
# CELL 22A — CHECK GIS PYTHON PACKAGES
# ============================================================

import importlib.util

packages = [
    "geopandas",
    "shapely",
    "fiona",
    "pyogrio",
    "osgeo"
]

print("=" * 80)
print("GIS PYTHON PACKAGE CHECK")
print("=" * 80)

for package in packages:

    available = (
        importlib.util.find_spec(package)
        is not None
    )

    status = "AVAILABLE" if available else "NOT AVAILABLE"

    print(f"{package:12s} : {status}")

print("=" * 80)

================================================================================
GIS PYTHON PACKAGE CHECK
================================================================================
geopandas    : NOT AVAILABLE
shapely      : NOT AVAILABLE
fiona        : NOT AVAILABLE
pyogrio      : NOT AVAILABLE
osgeo        : NOT AVAILABLE
================================================================================

In [353]:
# ============================================================
# CELL 23 — INSPECT EXISTING GEOPACKAGE
# ============================================================

from pathlib import Path
import sqlite3

gpkg_path = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/"
    "ds_79_target_divisions.gpkg"
)

print("=" * 90)
print("GEOPACKAGE INSPECTION")
print("=" * 90)

print("File exists:", gpkg_path.exists())

if gpkg_path.exists():

    conn = sqlite3.connect(gpkg_path)

    # Find all layers/tables
    tables = conn.execute("""
        SELECT table_name
        FROM gpkg_contents
        ORDER BY table_name
    """).fetchall()

    print("\nLayers/Tables in GeoPackage:")
    
    if tables:
        for i, (table_name,) in enumerate(tables, 1):
            print(f"{i:02d}. {table_name}")
    else:
        print("No GeoPackage layers found.")

    conn.close()

print("=" * 90)

==========================================================================================
GEOPACKAGE INSPECTION
==========================================================================================
File exists: True

Layers/Tables in GeoPackage:
01. ds_79_target_divisions
==========================================================================================

In [354]:
# ============================================================
# CELL 24 — LOAD DS BOUNDARY ATTRIBUTES WITHOUT GEOPANDAS
# ============================================================

import sqlite3
from pathlib import Path

gpkg_path = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/"
    "ds_79_target_divisions.gpkg"
)

conn = sqlite3.connect(gpkg_path)

# Get column information from the DS layer
columns = conn.execute("""
    PRAGMA table_info(ds_79_target_divisions)
""").fetchall()

print("=" * 90)
print("DS BOUNDARY ATTRIBUTES")
print("=" * 90)

for col in columns:
    print(f"{col[0]:3d} | {col[1]:30s} | {col[2]}")

print("\nNumber of records:")

count = conn.execute("""
    SELECT COUNT(*)
    FROM ds_79_target_divisions
""").fetchone()[0]

print(count)

conn.close()

print("=" * 90)

==========================================================================================
DS BOUNDARY ATTRIBUTES
==========================================================================================
  0 | fid                            | INTEGER
  1 | geom                           | MULTIPOLYGON
  2 | adm3_name                      | TEXT(80)
  3 | adm3_name1                     | TEXT(80)
  4 | adm3_name2                     | TEXT(80)
  5 | adm3_name3                     | TEXT(80)
  6 | adm3_pcode                     | TEXT(80)
  7 | adm2_name                      | TEXT(80)
  8 | adm2_name1                     | TEXT(80)
  9 | adm2_name2                     | TEXT(80)
 10 | adm2_name3                     | TEXT(80)
 11 | adm2_pcode                     | TEXT(80)
 12 | adm1_name                      | TEXT(80)
 13 | adm1_name1                     | TEXT(80)
 14 | adm1_name2                     | TEXT(80)
 15 | adm1_name3                     | TEXT(80)
 16 | adm1_pcode                     | TEXT(80)
 17 | adm0_name                      | TEXT(80)
 18 | adm0_name1                     | TEXT(80)
 19 | adm0_name2                     | TEXT(80)
 20 | adm0_name3                     | TEXT(80)
 21 | adm0_pcode                     | TEXT(80)
 22 | valid_on                       | DATE
 23 | valid_to                       | DATE
 24 | area_sqkm                      | REAL
 25 | version                        | TEXT(80)
 26 | lang                           | TEXT(80)
 27 | lang1                          | TEXT(80)
 28 | lang2                          | TEXT(80)
 29 | lang3                          | TEXT(80)
 30 | center_lat                     | REAL
 31 | center_lon                     | REAL

Number of records:
79
==========================================================================================

In [355]:
# ============================================================
# CELL 25 — KELANI FLOOD STATION METADATA
# ============================================================

import pandas as pd

kelani_stations = pd.DataFrame([
    {
        "station": "KN02",
        "station_name": "Norwood",
        "river_reach": "Kehelgamu Oya",
        "x": 182051,
        "y": 182230
    },
    {
        "station": "KN07",
        "station_name": "Kitulgala",
        "river_reach": "Kelani Ganga Upper",
        "x": 160270,
        "y": 198922
    },
    {
        "station": "KN11",
        "station_name": "Holombuwa",
        "river_reach": "Gurugoda Oya",
        "x": 143948,
        "y": 220765
    },
    {
        "station": "KN16",
        "station_name": "Deraniyagala",
        "river_reach": "Seethawaka Ganga",
        "x": 152036,
        "y": 191688
    },
    {
        "station": "KN18",
        "station_name": "Glencourse",
        "river_reach": "Kelani Ganga Midstream",
        "x": 135963,
        "y": 197396
    },
    {
        "station": "KN21",
        "station_name": "Hanwella",
        "river_reach": "Kelani Ganga Lower",
        "x": 123689,
        "y": 189980
    }
])

print("=" * 90)
print("KELANI FLOOD STATIONS")
print("=" * 90)

display(kelani_stations)

print("\nNumber of stations:", len(kelani_stations))
print("Unique station IDs:", kelani_stations["station"].nunique())
print("=" * 90)

==========================================================================================
KELANI FLOOD STATIONS
==========================================================================================

  station  station_name             river_reach       x       y
0    KN02       Norwood           Kehelgamu Oya  182051  182230
1    KN07     Kitulgala      Kelani Ganga Upper  160270  198922
2    KN11     Holombuwa            Gurugoda Oya  143948  220765
3    KN16  Deraniyagala        Seethawaka Ganga  152036  191688
4    KN18    Glencourse  Kelani Ganga Midstream  135963  197396
5    KN21      Hanwella      Kelani Ganga Lower  123689  189980

Number of stations: 6
Unique station IDs: 6
==========================================================================================

In [356]:
# ============================================================
# CELL 26 — INSPECT STATION COORDINATE RANGES
# ============================================================

print("=" * 90)
print("STATION COORDINATE INSPECTION")
print("=" * 90)

print(kelani_stations[["station", "station_name", "x", "y"]])

print("\nX range:")
print(
    kelani_stations["x"].min(),
    "to",
    kelani_stations["x"].max()
)

print("\nY range:")
print(
    kelani_stations["y"].min(),
    "to",
    kelani_stations["y"].max()
)

print("\nThese are NOT longitude/latitude values.")
print("They appear to be projected GIS coordinates.")
print("=" * 90)

==========================================================================================
STATION COORDINATE INSPECTION
==========================================================================================
  station  station_name       x       y
0    KN02       Norwood  182051  182230
1    KN07     Kitulgala  160270  198922
2    KN11     Holombuwa  143948  220765
3    KN16  Deraniyagala  152036  191688
4    KN18    Glencourse  135963  197396
5    KN21      Hanwella  123689  189980

X range:
123689 to 182051

Y range:
182230 to 220765

These are NOT longitude/latitude values.
They appear to be projected GIS coordinates.
==========================================================================================

In [357]:
# ============================================================
# CELL 27 — READ DS GEOPACKAGE CRS
# ============================================================

import sqlite3
from pathlib import Path

gpkg_path = Path(
    "/Users/ohaseelanka/Desktop/disaster_project_gis/"
    "ds_79_target_divisions.gpkg"
)

conn = sqlite3.connect(gpkg_path)

print("=" * 90)
print("GEOPACKAGE CRS")
print("=" * 90)

# Get the CRS ID used by the DS layer
result = conn.execute("""
    SELECT srs_id, srs_name, organization, organization_coordsys_id, definition
    FROM gpkg_spatial_ref_sys
""").fetchall()

for row in result:
    print("\nSRS ID:", row[0])
    print("SRS Name:", row[1])
    print("Organization:", row[2])
    print("Organization CRS ID:", row[3])
    print("Definition:", row[4])

conn.close()

print("=" * 90)

==========================================================================================
GEOPACKAGE CRS
==========================================================================================

SRS ID: -1
SRS Name: Undefined Cartesian SRS
Organization: NONE
Organization CRS ID: -1
Definition: undefined

SRS ID: 0
SRS Name: Undefined geographic SRS
Organization: NONE
Organization CRS ID: 0
Definition: undefined

SRS ID: 4326
SRS Name: WGS 84 geodetic
Organization: EPSG
Organization CRS ID: 4326
Definition: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]

SRS ID: 5235
SRS Name: SLD99 / Sri Lanka Grid 1999
Organization: EPSG
Organization CRS ID: 5235
Definition: PROJCS["SLD99 / Sri Lanka Grid 1999",GEOGCS["SLD99",DATUM["Sri_Lanka_Datum_1999",SPHEROID["Everest 1830 (1937 Adjustment)",6377276.345,300.8017,AUTHORITY["EPSG","7015"]],AUTHORITY["EPSG","1053"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","5233"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",7.00047152777778],PARAMETER["central_meridian",80.7717130833333],PARAMETER["scale_factor",0.9999238418],PARAMETER["false_easting",500000],PARAMETER["false_northing",500000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","5235"]]
==========================================================================================

In [358]:
# ============================================================
# CELL 28 — INSPECT GIS CRS (.PRJ FILES)
# ============================================================

from pathlib import Path

search_roots = [
    Path("/Users/ohaseelanka/Desktop/disaster_project_gis")
]

print("=" * 90)
print("GIS CRS / PRJ FILE INSPECTION")
print("=" * 90)

prj_files = []

for root in search_roots:
    if root.exists():
        for path in root.rglob("*.prj"):
            prj_files.append(path)

if not prj_files:
    print("No .prj files found.")
else:

    for path in sorted(prj_files):

        print("\n" + "-" * 90)
        print("FILE:")
        print(path)

        try:
            text = path.read_text(errors="ignore").strip()

            print("\nCRS definition:")
            print(text[:1500])

        except Exception as e:
            print("Could not read:", e)

print("\nTotal .prj files found:", len(prj_files))
print("=" * 90)

==========================================================================================
GIS CRS / PRJ FILE INSPECTION
==========================================================================================

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/ds_79_target_divisions.prj

CRS definition:
PROJCS["SLD99_Sri_Lanka_Grid_1999",GEOGCS["GCS_SLD99",DATUM["D_Sri_Lanka_Datum_1999",SPHEROID["Everest_Adjustment_1937",6377276.345,300.8017]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",500000.0],PARAMETER["Central_Meridian",80.7717130833333],PARAMETER["Scale_Factor",0.9999238418],PARAMETER["Latitude_Of_Origin",7.00047152777778],UNIT["Meter",1.0]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin0.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin2.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin3.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_admin4.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_adminlines.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/lka_admin_boundaries.shp/lka_adminpoints.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_adminareas_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_buildings_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_landuse_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_natural_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_natural_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_places_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_places_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_pofw_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_pofw_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_pois_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_pois_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_protected_areas_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_railways_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_roads_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_traffic_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_traffic_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_transport_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_transport_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_water_a_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

------------------------------------------------------------------------------------------
FILE:
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_waterways_free_1.prj

CRS definition:
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]

Total .prj files found: 28
==========================================================================================

In [359]:
# ============================================================
# CELL 31 — FIND POSSIBLE STATION FILES
# ============================================================

from pathlib import Path

search_roots = [
    Path("/Users/ohaseelanka/Desktop/disaster_project_gis"),
    Path("/Users/ohaseelanka/Downloads"),
    Path("/Users/ohaseelanka/Desktop")
]

keywords = [
    "station",
    "stations",
    "kelani",
    "gauge",
    "gauges",
    "hydro",
    "water"
]

extensions = [
    ".shp", ".gpkg", ".geojson", ".csv", ".xlsx", ".xls"
]

matches = []

for root in search_roots:
    if root.exists():
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in extensions:
                name = path.name.lower()

                if any(keyword in name for keyword in keywords):
                    matches.append(path)

print("=" * 100)
print("POSSIBLE STATION / HYDROLOGICAL FILES")
print("=" * 100)

if matches:
    for path in sorted(set(matches)):
        print(path)
else:
    print("No possible station/hydrological files found.")

print("\nTotal files found:", len(set(matches)))
print("=" * 100)

====================================================================================================
POSSIBLE STATION / HYDROLOGICAL FILES
====================================================================================================
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_water_a_free_1.shp
/Users/ohaseelanka/Desktop/disaster_project_gis/sri-lanka-260928-free.shp/gis_osm_waterways_free_1.shp
/Users/ohaseelanka/Downloads/Met_Stations.xlsx
/Users/ohaseelanka/Downloads/Research_Study_Areas_Kalu_Kelani_Nuwara_Eliya.xlsx
/Users/ohaseelanka/Downloads/rain_gauge_shortlist.xlsx

Total files found: 5
====================================================================================================

In [360]:
# ============================================================
# CELL 32 — INSPECT METEOROLOGICAL STATIONS FILE
# ============================================================

import pandas as pd

station_file = "/Users/ohaseelanka/Downloads/Met_Stations.xlsx"

xls = pd.ExcelFile(station_file)

print("=" * 100)
print("METEOROLOGICAL STATIONS FILE")
print("=" * 100)

print("\nSheets:")
for sheet in xls.sheet_names:
    print(" -", sheet)

print("\n" + "=" * 100)

for sheet in xls.sheet_names:
    df = pd.read_excel(station_file, sheet_name=sheet)

    print(f"\nSHEET: {sheet}")
    print("Shape:", df.shape)
    print("Columns:")
    print(list(df.columns))

    print("\nFirst 5 rows:")
    display(df.head())

    print("-" * 100)

====================================================================================================
METEOROLOGICAL STATIONS FILE
====================================================================================================

Sheets:
 - All Stations
 - AWS Locations
 - Met Stations & Parameters
 - Agromet Stations & Parameters
 - RF_Online(10 mts)
 - Rainfall Stations & Parameters
 - ARG Stations
 - 3.2 & 2.1

====================================================================================================

SHEET: All Stations
Shape: (1961, 29)
Columns:
['Name', 'Station ID', 'unnamed (1)', 'unnamed (2)', 'Latitude', 'Longitude', 'Coord_Longitude', 'Coord_Latitude', 'id', 'longitude', 'latitude', 'elevation', 'Parameters Daily & Monthly', 'Parameters 3 hourly', 'Obsevation times( UTC )', 'Station_id', 'District', 'Elevation', 'Obsevation Times (UTC)', 'Main Station', 'LON', 'LAT', 'Rf', 'Parameter Daily/Monthly', 'Station Type', 'Lat', 'Lon', 'code', 'unnamed (3)']

First 5 rows:

,Name,Station ID,unnamed (1),unnamed (2),Latitude,Longitude,Coord_Longitude,Coord_Latitude,id,longitude,latitude,elevation,Parameters Daily & Monthly,Parameters 3 hourly,Obsevation times( UTC ),Station_id,District,Elevation,Obsevation Times (UTC),Main Station,LON,LAT,Rf,Parameter Daily/Monthly,Station Type,Lat,Lon,code,unnamed (3)
0,wagolla,C1,"7°17'32.6""N","80°23'15.9""E",7.292400,80.387750,80.387750,7.292400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Polonnaruwa,C2,7.866666667,81.05,7.866667,81.050000,81.050000,7.866667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Monaragala,C3,6.5,81.3,6.500000,81.300000,81.300000,6.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mathale,C4,"7°27'13.5""N","80°38'31.9""E",7.453800,80.642194,80.642194,7.453800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sewanagala,C5,"6°23'47.1""N","80°54'45.6""E",6.396400,80.912667,80.912667,6.396400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

----------------------------------------------------------------------------------------------------

SHEET: AWS Locations
Shape: (39, 9)
Columns:
['Source Layer', 'Name', 'Station ID', 'unnamed (1)', 'unnamed (2)', 'Latitude', 'Longitude', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

    Source Layer         Name Station ID   unnamed (1)    unnamed (2)  Latitude  Longitude  Coord_Longitude  Coord_Latitude
0  AWS Locations      wagolla         C1   7°17'32.6"N   80°23'15.9"E  7.292400  80.387750        80.387750        7.292400
1  AWS Locations  Polonnaruwa         C2   7.866666667          81.05  7.866667  81.050000        81.050000        7.866667
2  AWS Locations   Monaragala         C3           6.5           81.3  6.500000  81.300000        81.300000        6.500000
3  AWS Locations      Mathale         C4  7°27'13.5"N    80°38'31.9"E  7.453800  80.642194        80.642194        7.453800
4  AWS Locations   Sewanagala         C5   6°23'47.1"N   80°54'45.6"E  6.396400  80.912667        80.912667        6.396400

----------------------------------------------------------------------------------------------------

SHEET: Met Stations & Parameters
Shape: (24, 11)
Columns:
['Source Layer', 'Name', 'id', 'longitude', 'latitude', 'elevation', 'Parameters Daily & Monthly', 'Parameters 3 hourly', 'Obsevation times( UTC )', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

,Source Layer,Name,id,longitude,latitude,elevation,Parameters Daily & Monthly,Parameters 3 hourly,Obsevation times( UTC ),Coord_Longitude,Coord_Latitude
0,Met Stations & Parameters,BANDARAWELA,43476,80.986260,6.830904,1225.0,"Temp Max,Temp min,Rainfall,RH Day","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure(msl & sl)...","0000,0300,0600,0900,1200,1500,",80.986260,6.830904
1,Met Stations & Parameters,JAFFNA,43404,80.032947,9.693824,3.0,"Temp Max,Temp min,Rainfall,RH Day","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure(msl & sl)...","0000,0300,0600,0900,1200,1500,",80.032947,9.693824
2,Met Stations & Parameters,MULLATIVE,43410,80.819239,9.270556,3.0,"Temp Max,Temp min,Rainfall,RH Day","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure(msl & sl)...","0000,0300,0600,0900,1200,1500,",80.819239,9.270556
3,Met Stations & Parameters,MANNAR,43413,79.907610,8.987058,4.0,"Temp Max,Temp min,Rainfall,RH Day,RH Night","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure(msl & sl)...","0000,0300,0600,0900,1200,1500,1800,2100,",79.907610,8.987058
4,Met Stations & Parameters,VAVUNIYA,43415,80.496591,8.759978,98.0,"Temp Max,Temp min,Rainfall,RH Day","RH,Dry temp,Wet temp,Wind (Sp & Dir), Pressure(msl & sl)...","0000,0300,0600,0900,1200,1500,",80.496591,8.759978

----------------------------------------------------------------------------------------------------

SHEET: Agromet Stations & Parameters
Shape: (41, 11)
Columns:
['Source Layer', 'Name', 'Station_id', 'District', 'Longitude', 'Latitude', 'Elevation', 'Parameters Daily & Monthly', 'Obsevation Times (UTC)', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

                    Source Layer           Name Station_id  District  Longitude  Latitude  Elevation                                   Parameters Daily & Monthly Obsevation Times (UTC)  Coord_Longitude  Coord_Latitude
0  Agromet Stations & Parameters     AGALAWATTA      01AG1  KALUTARA  80.150000  6.530000       65.0  Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,RH Morning,...            0300 & 1000        80.150000        6.530000
1  Agromet Stations & Parameters   ELUWANKULAMA     01AG10  PUTTALAM  79.850000  8.270000      100.0  Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,RH Morning,...            0300 & 1000        79.850000        8.270000
2  Agromet Stations & Parameters  GIRADURUKOTTE     01AG11   BADULLA  81.022322  7.458215      292.0  Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,RH Morning,...            0300 & 1000        81.022322        7.458215
3  Agromet Stations & Parameters       KOTHMALE     01AG12     KANDY  80.580000  7.080000      716.0  Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,RH Morning,...            0300 & 1000        80.580000        7.080000
4  Agromet Stations & Parameters        KOTTAWA     01AG13     GALLE  80.320000  6.090000       18.0  Temp Max,Temp min,Dry Temp,Wet Temp,Rainfall,RH Morning,...            0300 & 1000        80.320000        6.090000

----------------------------------------------------------------------------------------------------

SHEET: RF_Online(10 mts)
Shape: (122, 8)
Columns:
['Source Layer', 'Name', 'Main Station', 'LON', 'LAT', 'Rf', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

        Source Layer                                Name Main Station       LON      LAT      Rf  Coord_Longitude  Coord_Latitude
0  RF_Online(10 mts)         Wathupitiwala Base Hospital          AWS  80.11083  7.12250     0.0         80.11083         7.12250
1  RF_Online(10 mts)                  Madolthenna Estate          AWS  80.18222  7.08222 -9999.0         80.18222         7.08222
2  RF_Online(10 mts)                     Dunumale Estate          AWS  80.20889  7.13611 -9999.0         80.20889         7.13611
3  RF_Online(10 mts)            Etana Estate, Warakapola          AWS  80.19055  7.21528     0.0         80.19055         7.21528
4  RF_Online(10 mts)  Mahayaya Area Estate,Dansalwaththa          AWS  80.11722  7.18055     0.0         80.11722         7.18055

----------------------------------------------------------------------------------------------------

SHEET: Rainfall Stations & Parameters
Shape: (464, 9)
Columns:
['Source Layer', 'Name', 'id', 'District', 'longitude', 'latitude', 'Parameter Daily/Monthly', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

                               Source Layer                     Name        id District  longitude  latitude Parameter Daily/Monthly  Coord_Longitude  Coord_Latitude
0  Rainfall Stations & Parameters 2023-2025             AMPARAI TANK  01AM0012  AMPARAI  81.666781  7.283278                Rainfall        81.666781        7.283278
1  Rainfall Stations & Parameters 2023-2025             ADDALACHENAI  01AM001E  AMPARAI  81.852060  7.245667                Rainfall        81.852060        7.245667
2  Rainfall Stations & Parameters 2023-2025  AKKARAIPATTU IRRIGATION  01AM001F  AMPARAI  81.825879  7.224130                Rainfall        81.825879        7.224130
3  Rainfall Stations & Parameters 2023-2025                IRAKKAMAN  01AM0182  AMPARAI  81.726095  7.254938                Rainfall        81.726095        7.254938
4  Rainfall Stations & Parameters 2023-2025            LAHUGALA TANK  01AM0269  AMPARAI  81.700000  6.880000                Rainfall        81.700000        6.880000

----------------------------------------------------------------------------------------------------

SHEET: ARG Stations
Shape: (135, 8)
Columns:
['Source Layer', 'Name', 'Station Type', 'unnamed (1)', 'Lat', 'Lon', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

   Source Layer                                Name   Station Type unnamed (1)      Lat       Lon  Coord_Longitude  Coord_Latitude
0  ARG Stations         Wathupitiwala Base Hospital  ARGATHTHANA01         NaN  7.12250  80.11083         80.11083         7.12250
1  ARG Stations                  Madolthenna Estate  ARGATHTHANA02         NaN  7.08222  80.18222         80.18222         7.08222
2  ARG Stations                     Dunumale Estate  ARGATHTHANA03         NaN  7.13611  80.20889         80.20889         7.13611
3  ARG Stations            Etana Estate, Warakapola  ARGATHTHANA04         NaN  7.21528  80.19055         80.19055         7.21528
4  ARG Stations  Mahayaya Area Estate,Dansalwaththa  ARGATHTHANA05         NaN  7.18055  80.11722         80.11722         7.18055

----------------------------------------------------------------------------------------------------

SHEET: 3.2 & 2.1
Shape: (1136, 12)
Columns:
['Source Layer', 'Name', 'id', 'unnamed (1)', 'unnamed (2)', 'longitude', 'latitude', 'elevation', 'code', 'unnamed (3)', 'Coord_Longitude', 'Coord_Latitude']

First 5 rows:

  Source Layer           Name     id unnamed (1) unnamed (2)  longitude  latitude  elevation  code  unnamed (3)  Coord_Longitude  Coord_Latitude
0    3.2 & 2.1  KANKASANTURAI  43400      JAFFNA    Synoptic  80.070000  9.800000       16.0   5.0          NaN        80.070000        9.800000
1    3.2 & 2.1         JAFFNA  43404      JAFFNA    Synoptic  80.030000  9.680000        3.0   5.0          NaN        80.030000        9.680000
2    3.2 & 2.1     MULLAITIVU  43410  MULLAITIVU    Synoptic  80.820000  9.250000       13.0   5.0          NaN        80.820000        9.250000
3    3.2 & 2.1         MANNAR  43413      MANNAR    Synoptic  79.907630  8.987100        4.0   5.0          NaN        79.907630        8.987100
4    3.2 & 2.1       VAVUNIYA  43415    VAVUNIYA    Synoptic  80.496653  8.760052       98.0   5.0          NaN        80.496653        8.760052

----------------------------------------------------------------------------------------------------

In [361]:
# ============================================================
# CELL 33 — SEARCH FOR KELANI HYDROLOGICAL STATIONS
# ============================================================

import pandas as pd

station_file = "/Users/ohaseelanka/Downloads/Met_Stations.xlsx"

target_ids = ["KN02", "KN07", "KN11", "KN16", "KN18", "KN21"]

print("=" * 100)
print("SEARCHING FOR KELANI HYDROLOGICAL STATIONS")
print("=" * 100)

found = []

xls = pd.ExcelFile(station_file)

for sheet in xls.sheet_names:
    df = pd.read_excel(station_file, sheet_name=sheet)

    # Search every cell for our station IDs
    for target in target_ids:
        mask = df.astype(str).apply(
            lambda col: col.str.strip().str.upper().eq(target)
        ).any(axis=1)

        matches = df.loc[mask]

        if not matches.empty:
            print(f"\nFOUND {target} in sheet: {sheet}")
            display(matches)
            found.append((sheet, target))

print("\n" + "=" * 100)
print("SUMMARY")
print("=" * 100)

if found:
    for sheet, station in found:
        print(f"{station} → {sheet}")
else:
    print("None of the six KN station IDs were found in Met_Stations.xlsx.")

print("=" * 100)

====================================================================================================
SEARCHING FOR KELANI HYDROLOGICAL STATIONS
====================================================================================================

====================================================================================================
SUMMARY
====================================================================================================
None of the six KN station IDs were found in Met_Stations.xlsx.
====================================================================================================

In [362]:
# ============================================================
# CELL 34 — SEARCH FOR KELANI GAUGE STATION NAMES
# ============================================================

import pandas as pd
from pathlib import Path

search_files = [
    Path("/Users/ohaseelanka/Downloads/Research_Study_Areas_Kalu_Kelani_Nuwara_Eliya.xlsx"),
    Path("/Users/ohaseelanka/Downloads/rain_gauge_shortlist.xlsx"),
]

target_names = [
    "NORWOOD",
    "KITULGALA",
    "HOLOMBUWA",
    "DERANIYAGALA",
    "GLENCOURSE",
    "HANWELLA"
]

print("=" * 100)
print("SEARCHING FOR KELANI STATION NAMES")
print("=" * 100)

found = []

for file in search_files:

    print(f"\nFILE: {file.name}")

    try:
        xls = pd.ExcelFile(file)

        for sheet in xls.sheet_names:

            df = pd.read_excel(file, sheet_name=sheet)

            for target in target_names:

                mask = df.astype(str).apply(
                    lambda col: col.str.strip().str.upper().str.contains(
                        target,
                        na=False,
                        regex=False
                    )
                ).any(axis=1)

                matches = df.loc[mask]

                if not matches.empty:
                    print(f"\nFOUND: {target}")
                    print(f"Sheet: {sheet}")
                    display(matches)

                    found.append(
                        (file.name, sheet, target)
                    )

    except Exception as e:
        print("Could not read:", file)
        print("Error:", e)

print("\n" + "=" * 100)
print("SUMMARY")
print("=" * 100)

if found:
    for item in found:
        print(item)
else:
    print("No Kelani station names were found.")

print("=" * 100)

====================================================================================================
SEARCHING FOR KELANI STATION NAMES
====================================================================================================

FILE: Research_Study_Areas_Kalu_Kelani_Nuwara_Eliya.xlsx

FILE: rain_gauge_shortlist.xlsx

====================================================================================================
SUMMARY
====================================================================================================
No Kelani station names were found.
====================================================================================================