In [1]:

import sys
import pandas as pd
import numpy as np
from pathlib import Path

print("Python executable:", sys.executable)
print("Python version:", sys.version)
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Python executable: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/.venv/bin/python
Python version: 3.12.10 (v3.12.10:0cc81280367, Apr  8 2025, 08:46:59) [Clang 13.0.0 (clang-1300.0.29.30)]
Pandas version: 3.0.6
NumPy version: 2.5.4

In [2]:
# Project directory
PROJECT_DIR = Path.cwd().resolve()

while not (PROJECT_DIR / "data" / "raw").is_dir():
    PROJECT_DIR = PROJECT_DIR.parent

# Excel file path
rainfall_file = (
    PROJECT_DIR / "data" / "raw" / "rainfall" / "kelani"
    / "2015 - 2025 daily rainfall.xlsx"
)

# Read the first 10 rows of every worksheet
with pd.ExcelFile(rainfall_file) as workbook:
    for sheet_name in workbook.sheet_names:
        print(f"\n{'=' * 60}")
        print(f"Worksheet: {sheet_name}")
        print("=" * 60)

        df = pd.read_excel(
            workbook,
            sheet_name=sheet_name,
            nrows=10
        )

        display(df)

============================================================
Worksheet: KN02-NORWOOD
============================================================

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,Norwood Daily Rainfall in mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Cordinate :-,NaN,182051 X,NaN,182230 Y,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,D7,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
3,14/15/04,2015,JAN,0,0,0,0,0,1.7,0,...,0,0,0,0,0,11.7,23.4,4.6,0.5,41.9
4,14/15/05,2015,FEB,0,0,10.4,0,25.9,23.9,0,...,5,7.2,0,12.5,20,31.7,NaN,NaN,NaN,182.2
5,14/15/06,2015,MAR,3.7,0,0,20.3,2.5,0,0,...,0,0,0,25.4,1.3,1.8,4.6,7,5.5,85.7
6,14/15/07,2015,APR,39,26.8,0.7,13.1,0,0.3,9.4,...,12.5,39.3,21.4,1.2,38.8,1.2,3.1,8.7,NaN,341.4
7,14/15/08,2015,MAY,1.9,0,0,3.6,29.9,9.7,1.2,...,1.7,0,0,0,0,0,0,0,5.1,125.2
8,14/15/09,2015,JUN,0,0,1.3,4.2,16.5,0,0,...,0,1.6,0,7.6,16.7,8.1,7.8,1.3,NaN,207.1
9,14/15/10,2015,JUL,0,0,1.7,2.4,4.1,0,1.1,...,6,0,0,0,0,0,0,0,0,196.8

============================================================
Worksheet: KN07-KITULGALA
============================================================

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,Kithulgala Daily Rainfall in mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Cordinate :-,NaN,160270 X,NaN,198922 Y,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,D7,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
3,14/15/04,2015,JAN,0,0,0,0,0,5.3,0,...,33.1,0,0,0,0,2.8,26.9,1.5,0,69.6
4,14/15/05,2015,FEB,0,0,21,0,0.4,1.7,0,...,0.3,0.5,11.2,31.3,37.4,8.1,NaN,NaN,NaN,151.6
5,14/15/06,2015,MAR,55.8,0,0,2.9,0,0,0,...,0,0,0,9,0,53.1,20.5,2.4,2.8,236.2
6,14/15/07,2015,APR,6.9,14.5,0,0,0,0,5.6,...,25.2,7.4,23.4,17.2,1.1,24.8,19,4.4,NaN,295.9
7,14/15/08,2015,MAY,18.6,9.6,13.2,12.4,46.5,35.7,47.9,...,44.3,1,0,3.6,2.8,0,8.6,22,43.2,524.2
8,14/15/09,2015,JUN,7.7,3,16.8,13.2,68.8,0,0,...,0,2.8,0,20.1,20,52,36.6,21.3,NaN,492.4
9,14/15/10,2015,JUL,16.5,5.6,5.7,22.1,6.9,0,2.6,...,4,0,3.6,8.6,0,0,0,0,0,311.7

============================================================
Worksheet:  KN11-HOLOMBUWA
============================================================

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,Holombuwa Daily Rainfall in mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Cordinate :-,NaN,143948 X,NaN,220765 Y,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,D7,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
3,14/15/04,2015,JAN,0,0,0,0,0,0,0,...,0,0,0,0,0,3.6,0,2.5,0,6.1
4,14/15/05,2015,FEB,0,0,13.5,0,0.3,0,0,...,12,18.5,0,2,2.3,0,NaN,NaN,NaN,65
5,14/15/06,2015,MAR,13.4,2.6,0,38.7,0,0,0,...,0,0,0,4.2,0,12.8,19.4,13.1,23.1,243.7
6,14/15/07,2015,APR,11.7,50.4,0,0,0,7,7.3,...,1.2,14.5,17.8,12.6,22.9,0,13.8,13.7,NaN,381.8
7,14/15/08,2015,MAY,0,16.8,6.4,0,0,0,39.2,...,0.5,0,0,0,0,0,0,0.6,32.6,209.2
8,14/15/09,2015,JUN,8.7,0,16,13.7,19.8,0,0,...,0,0.6,0,14,28.3,6.6,14.5,16.5,NaN,221.7
9,14/15/10,2015,JUL,8.1,0,0.6,5.6,4.2,0,0.3,...,10.7,0,0,13.7,0,0,0,0,0,80.7

============================================================
Worksheet: KN16-DERANIYAGALA
============================================================

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,Deraniyagala Daily Rainfall in mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Cordinate :-,NaN,152036 X,NaN,191688 Y,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,D7,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
3,14/15/04,2015,JAN,0,0,0,0,0,0,0,...,30,0,0,0,0,4.1,41.5,50.5,0,126.1
4,14/15/05,2015,FEB,0,0,9,0,0.7,2.3,0,...,3.8,41.2,0,1.7,10.3,30.7,NaN,NaN,NaN,333.9
5,14/15/06,2015,MAR,30.7,53.8,20.5,1.8,4,0,0,...,0,0,0,6.5,14.5,15.6,24.8,0,55.7,302.7
6,14/15/07,2015,APR,4.5,81.8,0,2.1,0,68.3,34.7,...,70.9,27.9,37,0,150.4,0,32.6,33.3,NaN,854.6
7,14/15/08,2015,MAY,6.7,1.4,35.3,113.7,6.3,6.3,58.5,...,4.8,0,0,9.2,0,0,0,0,74.9,440.3
8,14/15/09,2015,JUN,14.5,4.6,44.1,29.2,80.8,0,0,...,0,7.3,0,21.8,27.9,17.6,38.3,4.8,NaN,443.1
9,14/15/10,2015,JUL,1.9,5.8,3.2,21.8,7,0,1.5,...,0.9,0,7.9,9.4,0,0,0,0,0,165.8

============================================================
Worksheet: KN18-GLENCOURSE
============================================================

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,Glencourse Daily Rainfall in mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Cordinate :-,NaN,135963 X,NaN,197396 Y,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,D7,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
3,14/15/04,2015,JAN,0,0,0,0,0,0,0,...,38.9,0,0,0,0,0.3,36.8,6.7,0,82.7
4,14/15/05,2015,FEB,0,0,2.6,0,0.8,3.6,0,...,0,13.7,0,11.5,32,1.1,NaN,NaN,NaN,131.6
5,14/15/06,2015,MAR,0,14.8,0,22.4,0.8,0,0,...,0,0,0,59.7,7,87.2,16,15.1,18.2,323.5
6,14/15/07,2015,APR,15.4,7.3,0,0,0,80.6,19.39,...,1.7,24.8,3.3,48.8,2.3,11.5,62.2,0.3,NaN,581.69
7,14/15/08,2015,MAY,36.1,10.1,53.5,9,0.3,10,4.3,...,3.6,0.3,0,0,0,0,0.5,0.9,19.4,276.9
8,14/15/09,2015,JUN,22.2,0.6,10.7,104.8,16.5,0,0,...,0,0.9,1.4,30.2,11,14.3,5.1,0.9,NaN,423.5
9,14/15/10,2015,JUL,0.9,1.4,0.6,5.7,4.2,0,2,...,1.5,0,0.3,3.4,0,0,0,0,0,86.6

============================================================
Worksheet: KN21-HANWELLA
============================================================

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,Hanwella Daily Rainfall in mm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Cordinate :-,NaN,123689 X,NaN,189980 Y,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,D7,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
3,14/15/04,2015,JAN,0,0,0,0,0,0,0,...,16.4,16.6,0,0,0.6,8.4,39.9,10.5,0,92.4
4,14/15/05,2015,FEB,0,0,7.8,0,2.2,48.6,0,...,0,2.3,0,3.3,4.6,0.3,NaN,NaN,NaN,231.1
5,14/15/06,2015,MAR,0,0,1.3,19.6,0,0,0,...,0,0,0,2.3,2.5,68.5,1.2,15.1,29,272.7
6,14/15/07,2015,APR,56.8,2.2,0,0,0,0,17.7,...,0,7.3,1.5,0,34.2,0,6.7,12.8,NaN,257.3
7,14/15/08,2015,MAY,3.8,9.5,0,3.2,15,3.5,9.1,...,6.6,0,0,0,0,0,0,0.4,25.1,180.6
8,14/15/09,2015,JUN,7.9,0.8,22.8,98,5.5,1.4,1.3,...,0,0.8,0,23.5,15.8,23.5,6.1,0,NaN,375.9
9,14/15/10,2015,JUL,4.3,0.3,13.6,21.7,0,0,4.3,...,0.7,0,0.9,0,0,0,0,0,0,88

In [3]:

# Project paths
PROJECT_DIR = Path.cwd().resolve()

while not (PROJECT_DIR / "data" / "raw").is_dir():
    if PROJECT_DIR.parent == PROJECT_DIR:
        raise FileNotFoundError("Project directory not found")
    PROJECT_DIR = PROJECT_DIR.parent

input_file = (
    PROJECT_DIR / "data" / "raw" / "rainfall" / "kelani"
    / "2015 - 2025 daily rainfall.xlsx"
)

output_dir = PROJECT_DIR / "data" / "processed" / "kelani"
output_dir.mkdir(parents=True, exist_ok=True)

output_file = output_dir / "kelani_daily_rainfall.xlsx"


def preprocess_rainfall(input_file, output_file):
    """
    Process all worksheets:
    - Extract location from the worksheet name
    - Skip the title and metadata rows
    - Rename Year/Month to Date
    - Add Location as the first column
    - Save all processed worksheets into a new Excel file
    """
    with pd.ExcelFile(input_file) as workbook:
        with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

            for sheet_name in workbook.sheet_names:
                # Row 3 (Excel row number) contains the column headers
                df = pd.read_excel(
                    workbook,
                    sheet_name=sheet_name,
                    header=2
                )

                # Remove completely empty columns
                df = df.dropna(axis=1, how="all")

                # Clean column names
                df.columns = df.columns.astype(str).str.strip()

                # Remove empty rows
                df = df.dropna(how="all").copy()

                # Rename the date column
                df = df.rename(columns={"Year/Month": "Date"})

                # Extract station name from worksheet name
                location = sheet_name.split("-", 1)[-1].strip()

                # Add location as the first column
                df.insert(0, "Location", location)

                # Save each processed worksheet
                df.to_excel(
                    writer,
                    sheet_name=sheet_name[:31],
                    index=False
                )

                print(
                    f"Processed: {sheet_name} | "
                    f"Location: {location} | "
                    f"Rows: {len(df)}"
                )

    print(f"\nPreprocessing completed.")
    print(f"Saved file: {output_file}")


preprocess_rainfall(input_file, output_file)

Processed: KN02-NORWOOD | Location: NORWOOD | Rows: 133
Processed: KN07-KITULGALA | Location: KITULGALA | Rows: 133
Processed:  KN11-HOLOMBUWA | Location: HOLOMBUWA | Rows: 133
Processed: KN16-DERANIYAGALA | Location: DERANIYAGALA | Rows: 133
Processed: KN18-GLENCOURSE | Location: GLENCOURSE | Rows: 133
Processed: KN21-HANWELLA | Location: HANWELLA | Rows: 133

Preprocessing completed.
Saved file: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_daily_rainfall.xlsx

In [4]:

with pd.ExcelFile(output_file) as workbook:
    for sheet_name in workbook.sheet_names:
        df = pd.read_excel(
            workbook,
            sheet_name=sheet_name,
            nrows=10
        )

        print(f"\nWorksheet: {sheet_name}")
        print(f"Top 10 rows | Actual rows displayed: {len(df)}")
        display(df)

Worksheet: KN02-NORWOOD
Top 10 rows | Actual rows displayed: 10

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NORWOOD,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,NORWOOD,14/15/04,2015,JAN,0,0,0,0,0,1.7,...,0,0,0,0,0,11.7,23.4,4.6,0.5,41.9
2,NORWOOD,14/15/05,2015,FEB,0,0,10.4,0,25.9,23.9,...,5,7.2,0,12.5,20,31.7,NaN,NaN,NaN,182.2
3,NORWOOD,14/15/06,2015,MAR,3.7,0,0,20.3,2.5,0,...,0,0,0,25.4,1.3,1.8,4.6,7,5.5,85.7
4,NORWOOD,14/15/07,2015,APR,39,26.8,0.7,13.1,0,0.3,...,12.5,39.3,21.4,1.2,38.8,1.2,3.1,8.7,NaN,341.4
5,NORWOOD,14/15/08,2015,MAY,1.9,0,0,3.6,29.9,9.7,...,1.7,0,0,0,0,0,0,0,5.1,125.2
6,NORWOOD,14/15/09,2015,JUN,0,0,1.3,4.2,16.5,0,...,0,1.6,0,7.6,16.7,8.1,7.8,1.3,NaN,207.1
7,NORWOOD,14/15/10,2015,JUL,0,0,1.7,2.4,4.1,0,...,6,0,0,0,0,0,0,0,0,196.8
8,NORWOOD,14/15/11,2015,AUG,0,0,2.9,25.4,0,0,...,0,2.7,2.2,5.8,14.1,6.9,0,0.6,0,134.8
9,NORWOOD,14/15/12,2015,SEP,0,0,12.5,1.1,18.1,0.4,...,0,45.7,0.1,1.2,5,4.6,0,10.1,NaN,226.4

Worksheet: KN07-KITULGALA
Top 10 rows | Actual rows displayed: 10

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,KITULGALA,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,KITULGALA,14/15/04,2015,JAN,0,0,0,0,0,5.3,...,33.1,0,0,0,0,2.8,26.9,1.5,0,69.6
2,KITULGALA,14/15/05,2015,FEB,0,0,21,0,0.4,1.7,...,0.3,0.5,11.2,31.3,37.4,8.1,NaN,NaN,NaN,151.6
3,KITULGALA,14/15/06,2015,MAR,55.8,0,0,2.9,0,0,...,0,0,0,9,0,53.1,20.5,2.4,2.8,236.2
4,KITULGALA,14/15/07,2015,APR,6.9,14.5,0,0,0,0,...,25.2,7.4,23.4,17.2,1.1,24.8,19,4.4,NaN,295.9
5,KITULGALA,14/15/08,2015,MAY,18.6,9.6,13.2,12.4,46.5,35.7,...,44.3,1,0,3.6,2.8,0,8.6,22,43.2,524.2
6,KITULGALA,14/15/09,2015,JUN,7.7,3,16.8,13.2,68.8,0,...,0,2.8,0,20.1,20,52,36.6,21.3,NaN,492.4
7,KITULGALA,14/15/10,2015,JUL,16.5,5.6,5.7,22.1,6.9,0,...,4,0,3.6,8.6,0,0,0,0,0,311.7
8,KITULGALA,14/15/11,2015,AUG,0,2.8,18.6,71.8,0,0,...,11.6,40.2,5.7,19.6,39.9,21.5,11,50.7,0,450.5
9,KITULGALA,14/15/12,2015,SEP,0,0,41.7,8.7,0,0,...,7.6,3.1,0.7,48.7,47.4,1.5,0,13.6,NaN,521.5

Worksheet:  KN11-HOLOMBUWA
Top 10 rows | Actual rows displayed: 10

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,HOLOMBUWA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,HOLOMBUWA,14/15/04,2015,JAN,0,0,0,0,0,0,...,0,0,0,0,0,3.6,0,2.5,0,6.1
2,HOLOMBUWA,14/15/05,2015,FEB,0,0,13.5,0,0.3,0,...,12,18.5,0,2,2.3,0,NaN,NaN,NaN,65
3,HOLOMBUWA,14/15/06,2015,MAR,13.4,2.6,0,38.7,0,0,...,0,0,0,4.2,0,12.8,19.4,13.1,23.1,243.7
4,HOLOMBUWA,14/15/07,2015,APR,11.7,50.4,0,0,0,7,...,1.2,14.5,17.8,12.6,22.9,0,13.8,13.7,NaN,381.8
5,HOLOMBUWA,14/15/08,2015,MAY,0,16.8,6.4,0,0,0,...,0.5,0,0,0,0,0,0,0.6,32.6,209.2
6,HOLOMBUWA,14/15/09,2015,JUN,8.7,0,16,13.7,19.8,0,...,0,0.6,0,14,28.3,6.6,14.5,16.5,NaN,221.7
7,HOLOMBUWA,14/15/10,2015,JUL,8.1,0,0.6,5.6,4.2,0,...,10.7,0,0,13.7,0,0,0,0,0,80.7
8,HOLOMBUWA,14/15/11,2015,AUG,0,3.4,12.7,43.1,0.3,0,...,3.1,16.2,0.6,10.6,24.5,23.8,0,6.7,0,206.7
9,HOLOMBUWA,14/15/12,2015,SEP,0,0,29.7,0.8,17.7,1.1,...,12.1,6.1,3.7,1.2,1.7,6.5,5.6,15.8,NaN,289

Worksheet: KN16-DERANIYAGALA
Top 10 rows | Actual rows displayed: 10

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,DERANIYAGALA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,DERANIYAGALA,14/15/04,2015,JAN,0,0,0,0,0,0,...,30,0,0,0,0,4.1,41.5,50.5,0,126.1
2,DERANIYAGALA,14/15/05,2015,FEB,0,0,9,0,0.7,2.3,...,3.8,41.2,0,1.7,10.3,30.7,NaN,NaN,NaN,333.9
3,DERANIYAGALA,14/15/06,2015,MAR,30.7,53.8,20.5,1.8,4,0,...,0,0,0,6.5,14.5,15.6,24.8,0,55.7,302.7
4,DERANIYAGALA,14/15/07,2015,APR,4.5,81.8,0,2.1,0,68.3,...,70.9,27.9,37,0,150.4,0,32.6,33.3,NaN,854.6
5,DERANIYAGALA,14/15/08,2015,MAY,6.7,1.4,35.3,113.7,6.3,6.3,...,4.8,0,0,9.2,0,0,0,0,74.9,440.3
6,DERANIYAGALA,14/15/09,2015,JUN,14.5,4.6,44.1,29.2,80.8,0,...,0,7.3,0,21.8,27.9,17.6,38.3,4.8,NaN,443.1
7,DERANIYAGALA,14/15/10,2015,JUL,1.9,5.8,3.2,21.8,7,0,...,0.9,0,7.9,9.4,0,0,0,0,0,165.8
8,DERANIYAGALA,14/15/11,2015,AUG,0,0,20.3,73.8,0,0,...,3.2,45.1,35.9,4.1,43.7,3.5,5.7,16.9,0,306.6
9,DERANIYAGALA,14/15/12,2015,SEP,0,0,36.8,0.5,0,0,...,1,2.1,0,25.8,19.5,2.3,1.78,26.3,NaN,475.48

Worksheet: KN18-GLENCOURSE
Top 10 rows | Actual rows displayed: 10

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,GLENCOURSE,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,GLENCOURSE,14/15/04,2015,JAN,0,0,0,0,0,0,...,38.9,0,0,0,0,0.3,36.8,6.7,0,82.7
2,GLENCOURSE,14/15/05,2015,FEB,0,0,2.6,0,0.8,3.6,...,0,13.7,0,11.5,32,1.1,NaN,NaN,NaN,131.6
3,GLENCOURSE,14/15/06,2015,MAR,0,14.8,0,22.4,0.8,0,...,0,0,0,59.7,7,87.2,16,15.1,18.2,323.5
4,GLENCOURSE,14/15/07,2015,APR,15.4,7.3,0,0,0,80.6,...,1.7,24.8,3.3,48.8,2.3,11.5,62.2,0.3,NaN,581.69
5,GLENCOURSE,14/15/08,2015,MAY,36.1,10.1,53.5,9,0.3,10,...,3.6,0.3,0,0,0,0,0.5,0.9,19.4,276.9
6,GLENCOURSE,14/15/09,2015,JUN,22.2,0.6,10.7,104.8,16.5,0,...,0,0.9,1.4,30.2,11,14.3,5.1,0.9,NaN,423.5
7,GLENCOURSE,14/15/10,2015,JUL,0.9,1.4,0.6,5.7,4.2,0,...,1.5,0,0.3,3.4,0,0,0,0,0,86.6
8,GLENCOURSE,14/15/11,2015,AUG,0,0,3.1,16.6,0,0,...,3.1,18.9,9,10.3,23.6,5.8,1.2,0.8,0,155.2
9,GLENCOURSE,14/15/12,2015,SEP,0,0,49.2,0,0.6,5,...,8.8,0.8,1.8,15.9,1.7,6.2,7,34.7,NaN,300.3

Worksheet: KN21-HANWELLA
Top 10 rows | Actual rows displayed: 10

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,HANWELLA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,HANWELLA,14/15/04,2015,JAN,0,0,0,0,0,0,...,16.4,16.6,0,0,0.6,8.4,39.9,10.5,0,92.4
2,HANWELLA,14/15/05,2015,FEB,0,0,7.8,0,2.2,48.6,...,0,2.3,0,3.3,4.6,0.3,NaN,NaN,NaN,231.1
3,HANWELLA,14/15/06,2015,MAR,0,0,1.3,19.6,0,0,...,0,0,0,2.3,2.5,68.5,1.2,15.1,29,272.7
4,HANWELLA,14/15/07,2015,APR,56.8,2.2,0,0,0,0,...,0,7.3,1.5,0,34.2,0,6.7,12.8,NaN,257.3
5,HANWELLA,14/15/08,2015,MAY,3.8,9.5,0,3.2,15,3.5,...,6.6,0,0,0,0,0,0,0.4,25.1,180.6
6,HANWELLA,14/15/09,2015,JUN,7.9,0.8,22.8,98,5.5,1.4,...,0,0.8,0,23.5,15.8,23.5,6.1,0,NaN,375.9
7,HANWELLA,14/15/10,2015,JUL,4.3,0.3,13.6,21.7,0,0,...,0.7,0,0.9,0,0,0,0,0,0,88
8,HANWELLA,14/15/11,2015,AUG,4,1.2,8.1,23.2,0,0,...,17.6,6.2,7,13.9,15.2,9.9,0,4.7,0,156.5
9,HANWELLA,14/15/12,2015,SEP,0,0,56.8,0,10,25.5,...,1.2,0.6,7.8,14.4,33.8,24.6,10.4,44.4,NaN,395.4

In [5]:

# Reprocess all sheets with the correct column headers
with pd.ExcelFile(input_file) as workbook:
    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

        for sheet_name in workbook.sheet_names:
            df = pd.read_excel(
                workbook,
                sheet_name=sheet_name,
                header=2
            )

            # Remove completely empty columns and rows
            df = df.dropna(axis=1, how="all")
            df = df.dropna(how="all").copy()
            df.columns = df.columns.astype(str).str.strip()

            # Rename the first date column
            df = df.rename(columns={"Year/Month": "Date"})

            # Extract station name
            location = sheet_name.split("-", 1)[-1].strip()

            # Add Location as the first column
            df.insert(0, "Location", location)

            # Save the corrected sheet
            df.to_excel(
                writer,
                sheet_name=sheet_name[:31],
                index=False
            )

print("All worksheets corrected and saved.")
print("Output:", output_file)

All worksheets corrected and saved.
Output: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_daily_rainfall.xlsx

In [6]:

with pd.ExcelFile(output_file) as workbook:
    for sheet_name in workbook.sheet_names:
        df = pd.read_excel(
            workbook,
            sheet_name=sheet_name,
            nrows=10
        )

        print(f"\nWorksheet: {sheet_name}")
        display(df)

Worksheet: KN02-NORWOOD

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NORWOOD,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,NORWOOD,14/15/04,2015,JAN,0,0,0,0,0,1.7,...,0,0,0,0,0,11.7,23.4,4.6,0.5,41.9
2,NORWOOD,14/15/05,2015,FEB,0,0,10.4,0,25.9,23.9,...,5,7.2,0,12.5,20,31.7,NaN,NaN,NaN,182.2
3,NORWOOD,14/15/06,2015,MAR,3.7,0,0,20.3,2.5,0,...,0,0,0,25.4,1.3,1.8,4.6,7,5.5,85.7
4,NORWOOD,14/15/07,2015,APR,39,26.8,0.7,13.1,0,0.3,...,12.5,39.3,21.4,1.2,38.8,1.2,3.1,8.7,NaN,341.4
5,NORWOOD,14/15/08,2015,MAY,1.9,0,0,3.6,29.9,9.7,...,1.7,0,0,0,0,0,0,0,5.1,125.2
6,NORWOOD,14/15/09,2015,JUN,0,0,1.3,4.2,16.5,0,...,0,1.6,0,7.6,16.7,8.1,7.8,1.3,NaN,207.1
7,NORWOOD,14/15/10,2015,JUL,0,0,1.7,2.4,4.1,0,...,6,0,0,0,0,0,0,0,0,196.8
8,NORWOOD,14/15/11,2015,AUG,0,0,2.9,25.4,0,0,...,0,2.7,2.2,5.8,14.1,6.9,0,0.6,0,134.8
9,NORWOOD,14/15/12,2015,SEP,0,0,12.5,1.1,18.1,0.4,...,0,45.7,0.1,1.2,5,4.6,0,10.1,NaN,226.4

Worksheet: KN07-KITULGALA

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,KITULGALA,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,KITULGALA,14/15/04,2015,JAN,0,0,0,0,0,5.3,...,33.1,0,0,0,0,2.8,26.9,1.5,0,69.6
2,KITULGALA,14/15/05,2015,FEB,0,0,21,0,0.4,1.7,...,0.3,0.5,11.2,31.3,37.4,8.1,NaN,NaN,NaN,151.6
3,KITULGALA,14/15/06,2015,MAR,55.8,0,0,2.9,0,0,...,0,0,0,9,0,53.1,20.5,2.4,2.8,236.2
4,KITULGALA,14/15/07,2015,APR,6.9,14.5,0,0,0,0,...,25.2,7.4,23.4,17.2,1.1,24.8,19,4.4,NaN,295.9
5,KITULGALA,14/15/08,2015,MAY,18.6,9.6,13.2,12.4,46.5,35.7,...,44.3,1,0,3.6,2.8,0,8.6,22,43.2,524.2
6,KITULGALA,14/15/09,2015,JUN,7.7,3,16.8,13.2,68.8,0,...,0,2.8,0,20.1,20,52,36.6,21.3,NaN,492.4
7,KITULGALA,14/15/10,2015,JUL,16.5,5.6,5.7,22.1,6.9,0,...,4,0,3.6,8.6,0,0,0,0,0,311.7
8,KITULGALA,14/15/11,2015,AUG,0,2.8,18.6,71.8,0,0,...,11.6,40.2,5.7,19.6,39.9,21.5,11,50.7,0,450.5
9,KITULGALA,14/15/12,2015,SEP,0,0,41.7,8.7,0,0,...,7.6,3.1,0.7,48.7,47.4,1.5,0,13.6,NaN,521.5

Worksheet:  KN11-HOLOMBUWA

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,HOLOMBUWA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,HOLOMBUWA,14/15/04,2015,JAN,0,0,0,0,0,0,...,0,0,0,0,0,3.6,0,2.5,0,6.1
2,HOLOMBUWA,14/15/05,2015,FEB,0,0,13.5,0,0.3,0,...,12,18.5,0,2,2.3,0,NaN,NaN,NaN,65
3,HOLOMBUWA,14/15/06,2015,MAR,13.4,2.6,0,38.7,0,0,...,0,0,0,4.2,0,12.8,19.4,13.1,23.1,243.7
4,HOLOMBUWA,14/15/07,2015,APR,11.7,50.4,0,0,0,7,...,1.2,14.5,17.8,12.6,22.9,0,13.8,13.7,NaN,381.8
5,HOLOMBUWA,14/15/08,2015,MAY,0,16.8,6.4,0,0,0,...,0.5,0,0,0,0,0,0,0.6,32.6,209.2
6,HOLOMBUWA,14/15/09,2015,JUN,8.7,0,16,13.7,19.8,0,...,0,0.6,0,14,28.3,6.6,14.5,16.5,NaN,221.7
7,HOLOMBUWA,14/15/10,2015,JUL,8.1,0,0.6,5.6,4.2,0,...,10.7,0,0,13.7,0,0,0,0,0,80.7
8,HOLOMBUWA,14/15/11,2015,AUG,0,3.4,12.7,43.1,0.3,0,...,3.1,16.2,0.6,10.6,24.5,23.8,0,6.7,0,206.7
9,HOLOMBUWA,14/15/12,2015,SEP,0,0,29.7,0.8,17.7,1.1,...,12.1,6.1,3.7,1.2,1.7,6.5,5.6,15.8,NaN,289

Worksheet: KN16-DERANIYAGALA

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,DERANIYAGALA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,DERANIYAGALA,14/15/04,2015,JAN,0,0,0,0,0,0,...,30,0,0,0,0,4.1,41.5,50.5,0,126.1
2,DERANIYAGALA,14/15/05,2015,FEB,0,0,9,0,0.7,2.3,...,3.8,41.2,0,1.7,10.3,30.7,NaN,NaN,NaN,333.9
3,DERANIYAGALA,14/15/06,2015,MAR,30.7,53.8,20.5,1.8,4,0,...,0,0,0,6.5,14.5,15.6,24.8,0,55.7,302.7
4,DERANIYAGALA,14/15/07,2015,APR,4.5,81.8,0,2.1,0,68.3,...,70.9,27.9,37,0,150.4,0,32.6,33.3,NaN,854.6
5,DERANIYAGALA,14/15/08,2015,MAY,6.7,1.4,35.3,113.7,6.3,6.3,...,4.8,0,0,9.2,0,0,0,0,74.9,440.3
6,DERANIYAGALA,14/15/09,2015,JUN,14.5,4.6,44.1,29.2,80.8,0,...,0,7.3,0,21.8,27.9,17.6,38.3,4.8,NaN,443.1
7,DERANIYAGALA,14/15/10,2015,JUL,1.9,5.8,3.2,21.8,7,0,...,0.9,0,7.9,9.4,0,0,0,0,0,165.8
8,DERANIYAGALA,14/15/11,2015,AUG,0,0,20.3,73.8,0,0,...,3.2,45.1,35.9,4.1,43.7,3.5,5.7,16.9,0,306.6
9,DERANIYAGALA,14/15/12,2015,SEP,0,0,36.8,0.5,0,0,...,1,2.1,0,25.8,19.5,2.3,1.78,26.3,NaN,475.48

Worksheet: KN18-GLENCOURSE

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,GLENCOURSE,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,GLENCOURSE,14/15/04,2015,JAN,0,0,0,0,0,0,...,38.9,0,0,0,0,0.3,36.8,6.7,0,82.7
2,GLENCOURSE,14/15/05,2015,FEB,0,0,2.6,0,0.8,3.6,...,0,13.7,0,11.5,32,1.1,NaN,NaN,NaN,131.6
3,GLENCOURSE,14/15/06,2015,MAR,0,14.8,0,22.4,0.8,0,...,0,0,0,59.7,7,87.2,16,15.1,18.2,323.5
4,GLENCOURSE,14/15/07,2015,APR,15.4,7.3,0,0,0,80.6,...,1.7,24.8,3.3,48.8,2.3,11.5,62.2,0.3,NaN,581.69
5,GLENCOURSE,14/15/08,2015,MAY,36.1,10.1,53.5,9,0.3,10,...,3.6,0.3,0,0,0,0,0.5,0.9,19.4,276.9
6,GLENCOURSE,14/15/09,2015,JUN,22.2,0.6,10.7,104.8,16.5,0,...,0,0.9,1.4,30.2,11,14.3,5.1,0.9,NaN,423.5
7,GLENCOURSE,14/15/10,2015,JUL,0.9,1.4,0.6,5.7,4.2,0,...,1.5,0,0.3,3.4,0,0,0,0,0,86.6
8,GLENCOURSE,14/15/11,2015,AUG,0,0,3.1,16.6,0,0,...,3.1,18.9,9,10.3,23.6,5.8,1.2,0.8,0,155.2
9,GLENCOURSE,14/15/12,2015,SEP,0,0,49.2,0,0.6,5,...,8.8,0.8,1.8,15.9,1.7,6.2,7,34.7,NaN,300.3

Worksheet: KN21-HANWELLA

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,HANWELLA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,HANWELLA,14/15/04,2015,JAN,0,0,0,0,0,0,...,16.4,16.6,0,0,0.6,8.4,39.9,10.5,0,92.4
2,HANWELLA,14/15/05,2015,FEB,0,0,7.8,0,2.2,48.6,...,0,2.3,0,3.3,4.6,0.3,NaN,NaN,NaN,231.1
3,HANWELLA,14/15/06,2015,MAR,0,0,1.3,19.6,0,0,...,0,0,0,2.3,2.5,68.5,1.2,15.1,29,272.7
4,HANWELLA,14/15/07,2015,APR,56.8,2.2,0,0,0,0,...,0,7.3,1.5,0,34.2,0,6.7,12.8,NaN,257.3
5,HANWELLA,14/15/08,2015,MAY,3.8,9.5,0,3.2,15,3.5,...,6.6,0,0,0,0,0,0,0.4,25.1,180.6
6,HANWELLA,14/15/09,2015,JUN,7.9,0.8,22.8,98,5.5,1.4,...,0,0.8,0,23.5,15.8,23.5,6.1,0,NaN,375.9
7,HANWELLA,14/15/10,2015,JUL,4.3,0.3,13.6,21.7,0,0,...,0.7,0,0.9,0,0,0,0,0,0,88
8,HANWELLA,14/15/11,2015,AUG,4,1.2,8.1,23.2,0,0,...,17.6,6.2,7,13.9,15.2,9.9,0,4.7,0,156.5
9,HANWELLA,14/15/12,2015,SEP,0,0,56.8,0,10,25.5,...,1.2,0.6,7.8,14.4,33.8,24.6,10.4,44.4,NaN,395.4

In [7]:

# Read the final processed rainfall file
with pd.ExcelFile(output_file, engine="openpyxl") as workbook:
    for sheet_name in workbook.sheet_names:
        df = pd.read_excel(
            workbook,
            sheet_name=sheet_name,
            nrows=5
        )

        print(f"\nWorksheet: {sheet_name}")
        print(f"Rows displayed: {len(df)}")
        display(df)

Worksheet: KN02-NORWOOD
Rows displayed: 5

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NORWOOD,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,NORWOOD,14/15/04,2015,JAN,0,0,0,0,0,1.7,...,0,0,0,0,0,11.7,23.4,4.6,0.5,41.9
2,NORWOOD,14/15/05,2015,FEB,0,0,10.4,0,25.9,23.9,...,5,7.2,0,12.5,20,31.7,NaN,NaN,NaN,182.2
3,NORWOOD,14/15/06,2015,MAR,3.7,0,0,20.3,2.5,0,...,0,0,0,25.4,1.3,1.8,4.6,7,5.5,85.7
4,NORWOOD,14/15/07,2015,APR,39,26.8,0.7,13.1,0,0.3,...,12.5,39.3,21.4,1.2,38.8,1.2,3.1,8.7,NaN,341.4

Worksheet: KN07-KITULGALA
Rows displayed: 5

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,KITULGALA,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,KITULGALA,14/15/04,2015,JAN,0,0,0,0,0,5.3,...,33.1,0,0,0,0,2.8,26.9,1.5,0,69.6
2,KITULGALA,14/15/05,2015,FEB,0,0,21,0,0.4,1.7,...,0.3,0.5,11.2,31.3,37.4,8.1,NaN,NaN,NaN,151.6
3,KITULGALA,14/15/06,2015,MAR,55.8,0,0,2.9,0,0,...,0,0,0,9,0,53.1,20.5,2.4,2.8,236.2
4,KITULGALA,14/15/07,2015,APR,6.9,14.5,0,0,0,0,...,25.2,7.4,23.4,17.2,1.1,24.8,19,4.4,NaN,295.9

Worksheet:  KN11-HOLOMBUWA
Rows displayed: 5

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,HOLOMBUWA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,HOLOMBUWA,14/15/04,2015,JAN,0,0,0,0,0,0,...,0,0,0,0,0,3.6,0,2.5,0,6.1
2,HOLOMBUWA,14/15/05,2015,FEB,0,0,13.5,0,0.3,0,...,12,18.5,0,2,2.3,0,NaN,NaN,NaN,65
3,HOLOMBUWA,14/15/06,2015,MAR,13.4,2.6,0,38.7,0,0,...,0,0,0,4.2,0,12.8,19.4,13.1,23.1,243.7
4,HOLOMBUWA,14/15/07,2015,APR,11.7,50.4,0,0,0,7,...,1.2,14.5,17.8,12.6,22.9,0,13.8,13.7,NaN,381.8

Worksheet: KN16-DERANIYAGALA
Rows displayed: 5

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,DERANIYAGALA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,DERANIYAGALA,14/15/04,2015,JAN,0,0,0,0,0,0,...,30,0,0,0,0,4.1,41.5,50.5,0,126.1
2,DERANIYAGALA,14/15/05,2015,FEB,0,0,9,0,0.7,2.3,...,3.8,41.2,0,1.7,10.3,30.7,NaN,NaN,NaN,333.9
3,DERANIYAGALA,14/15/06,2015,MAR,30.7,53.8,20.5,1.8,4,0,...,0,0,0,6.5,14.5,15.6,24.8,0,55.7,302.7
4,DERANIYAGALA,14/15/07,2015,APR,4.5,81.8,0,2.1,0,68.3,...,70.9,27.9,37,0,150.4,0,32.6,33.3,NaN,854.6

Worksheet: KN18-GLENCOURSE
Rows displayed: 5

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,GLENCOURSE,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,GLENCOURSE,14/15/04,2015,JAN,0,0,0,0,0,0,...,38.9,0,0,0,0,0.3,36.8,6.7,0,82.7
2,GLENCOURSE,14/15/05,2015,FEB,0,0,2.6,0,0.8,3.6,...,0,13.7,0,11.5,32,1.1,NaN,NaN,NaN,131.6
3,GLENCOURSE,14/15/06,2015,MAR,0,14.8,0,22.4,0.8,0,...,0,0,0,59.7,7,87.2,16,15.1,18.2,323.5
4,GLENCOURSE,14/15/07,2015,APR,15.4,7.3,0,0,0,80.6,...,1.7,24.8,3.3,48.8,2.3,11.5,62.2,0.3,NaN,581.69

Worksheet: KN21-HANWELLA
Rows displayed: 5

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,HANWELLA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
1,HANWELLA,14/15/04,2015,JAN,0,0,0,0,0,0,...,16.4,16.6,0,0,0.6,8.4,39.9,10.5,0,92.4
2,HANWELLA,14/15/05,2015,FEB,0,0,7.8,0,2.2,48.6,...,0,2.3,0,3.3,4.6,0.3,NaN,NaN,NaN,231.1
3,HANWELLA,14/15/06,2015,MAR,0,0,1.3,19.6,0,0,...,0,0,0,2.3,2.5,68.5,1.2,15.1,29,272.7
4,HANWELLA,14/15/07,2015,APR,56.8,2.2,0,0,0,0,...,0,7.3,1.5,0,34.2,0,6.7,12.8,NaN,257.3

In [8]:
# Update the existing processed Excel file
temp_file = output_file.with_name("kelani_temp.xlsx")

with pd.ExcelFile(output_file, engine="openpyxl") as workbook:
    with pd.ExcelWriter(temp_file, engine="openpyxl") as writer:
        for sheet_name in workbook.sheet_names:
            df = pd.read_excel(workbook, sheet_name=sheet_name, header=None)

            # Delete the first row and promote the second row to headers
            df = df.iloc[1:].reset_index(drop=True)
            df.columns = df.iloc[0].astype(str).str.strip()
            df = df.iloc[1:].reset_index(drop=True)

            # Save the updated worksheet
            df.to_excel(writer, sheet_name=sheet_name, index=False)

# Replace the existing processed file
temp_file.replace(output_file)

print("Updated file:", output_file)

# Display the top 5 rows of every worksheet
with pd.ExcelFile(output_file, engine="openpyxl") as workbook:
    for sheet_name in workbook.sheet_names:
        print(f"\nWorksheet: {sheet_name}")
        display(pd.read_excel(workbook, sheet_name=sheet_name, nrows=5))

Updated file: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_daily_rainfall.xlsx

Worksheet: KN02-NORWOOD

,NORWOOD,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,NORWOOD,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,1.7,...,0.0,0.0,0.0,0.0,0.0,11.7,23.4,4.6,0.5,41.9
1,NORWOOD,14/15/05,2015,FEB,0.0,0.0,10.4,0.0,25.9,23.9,...,5.0,7.2,0.0,12.5,20.0,31.7,NaN,NaN,NaN,182.2
2,NORWOOD,14/15/06,2015,MAR,3.7,0.0,0.0,20.3,2.5,0.0,...,0.0,0.0,0.0,25.4,1.3,1.8,4.6,7.0,5.5,85.7
3,NORWOOD,14/15/07,2015,APR,39.0,26.8,0.7,13.1,0.0,0.3,...,12.5,39.3,21.4,1.2,38.8,1.2,3.1,8.7,NaN,341.4
4,NORWOOD,14/15/08,2015,MAY,1.9,0.0,0.0,3.6,29.9,9.7,...,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.1,125.2

Worksheet: KN07-KITULGALA

,KITULGALA,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,KITULGALA,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,5.3,...,33.1,0.0,0.0,0.0,0.0,2.8,26.9,1.5,0.0,69.6
1,KITULGALA,14/15/05,2015,FEB,0.0,0.0,21.0,0.0,0.4,1.7,...,0.3,0.5,11.2,31.3,37.4,8.1,NaN,NaN,NaN,151.6
2,KITULGALA,14/15/06,2015,MAR,55.8,0.0,0.0,2.9,0.0,0.0,...,0.0,0.0,0.0,9.0,0.0,53.1,20.5,2.4,2.8,236.2
3,KITULGALA,14/15/07,2015,APR,6.9,14.5,0.0,0.0,0.0,0.0,...,25.2,7.4,23.4,17.2,1.1,24.8,19.0,4.4,NaN,295.9
4,KITULGALA,14/15/08,2015,MAY,18.6,9.6,13.2,12.4,46.5,35.7,...,44.3,1.0,0.0,3.6,2.8,0.0,8.6,22.0,43.2,524.2

Worksheet:  KN11-HOLOMBUWA

,HOLOMBUWA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,HOLOMBUWA,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,3.6,0.0,2.5,0.0,6.1
1,HOLOMBUWA,14/15/05,2015,FEB,0.0,0.0,13.5,0.0,0.3,0,...,12.0,18.5,0.0,2.0,2.3,0.0,NaN,NaN,NaN,65.0
2,HOLOMBUWA,14/15/06,2015,MAR,13.4,2.6,0.0,38.7,0.0,0,...,0.0,0.0,0.0,4.2,0.0,12.8,19.4,13.1,23.1,243.7
3,HOLOMBUWA,14/15/07,2015,APR,11.7,50.4,0.0,0.0,0.0,7,...,1.2,14.5,17.8,12.6,22.9,0.0,13.8,13.7,NaN,381.8
4,HOLOMBUWA,14/15/08,2015,MAY,0.0,16.8,6.4,0.0,0.0,0,...,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.6,32.6,209.2

Worksheet: KN16-DERANIYAGALA

,DERANIYAGALA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,DERANIYAGALA,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,0.0,...,30.0,0.0,0,0.0,0.0,4.1,41.5,50.5,0.0,126.1
1,DERANIYAGALA,14/15/05,2015,FEB,0.0,0.0,9.0,0.0,0.7,2.3,...,3.8,41.2,0,1.7,10.3,30.7,NaN,NaN,NaN,333.9
2,DERANIYAGALA,14/15/06,2015,MAR,30.7,53.8,20.5,1.8,4.0,0.0,...,0.0,0.0,0,6.5,14.5,15.6,24.8,0.0,55.7,302.7
3,DERANIYAGALA,14/15/07,2015,APR,4.5,81.8,0.0,2.1,0.0,68.3,...,70.9,27.9,37,0.0,150.4,0.0,32.6,33.3,NaN,854.6
4,DERANIYAGALA,14/15/08,2015,MAY,6.7,1.4,35.3,113.7,6.3,6.3,...,4.8,0.0,0,9.2,0.0,0.0,0.0,0.0,74.9,440.3

Worksheet: KN18-GLENCOURSE

,GLENCOURSE,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,GLENCOURSE,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,0.0,...,38.9,0.0,0.0,0.0,0.0,0.3,36.8,6.7,0.0,82.70
1,GLENCOURSE,14/15/05,2015,FEB,0.0,0.0,2.6,0.0,0.8,3.6,...,0.0,13.7,0.0,11.5,32.0,1.1,NaN,NaN,NaN,131.60
2,GLENCOURSE,14/15/06,2015,MAR,0.0,14.8,0.0,22.4,0.8,0.0,...,0.0,0.0,0.0,59.7,7.0,87.2,16.0,15.1,18.2,323.50
3,GLENCOURSE,14/15/07,2015,APR,15.4,7.3,0.0,0.0,0.0,80.6,...,1.7,24.8,3.3,48.8,2.3,11.5,62.2,0.3,NaN,581.69
4,GLENCOURSE,14/15/08,2015,MAY,36.1,10.1,53.5,9.0,0.3,10.0,...,3.6,0.3,0.0,0.0,0.0,0.0,0.5,0.9,19.4,276.90

Worksheet: KN21-HANWELLA

,HANWELLA,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,HANWELLA,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,0.0,...,16.4,16.6,0.0,0.0,0.6,8.4,39.9,10.5,0.0,92.4
1,HANWELLA,14/15/05,2015,FEB,0.0,0.0,7.8,0.0,2.2,48.6,...,0.0,2.3,0.0,3.3,4.6,0.3,NaN,NaN,NaN,231.1
2,HANWELLA,14/15/06,2015,MAR,0.0,0.0,1.3,19.6,0.0,0.0,...,0.0,0.0,0.0,2.3,2.5,68.5,1.2,15.1,29.0,272.7
3,HANWELLA,14/15/07,2015,APR,56.8,2.2,0.0,0.0,0.0,0.0,...,0.0,7.3,1.5,0.0,34.2,0.0,6.7,12.8,NaN,257.3
4,HANWELLA,14/15/08,2015,MAY,3.8,9.5,0.0,3.2,15.0,3.5,...,6.6,0.0,0.0,0.0,0.0,0.0,0.0,0.4,25.1,180.6

In [9]:
# Update the existing processed Excel file
temp_file = output_file.with_name("kelani_temp.xlsx")

with pd.ExcelFile(output_file, engine="openpyxl") as workbook:
    with pd.ExcelWriter(temp_file, engine="openpyxl") as writer:
        for sheet_name in workbook.sheet_names:
            df = pd.read_excel(workbook, sheet_name=sheet_name)

            # Rename the first column to Location
            df.rename(columns={df.columns[0]: "Location"}, inplace=True)

            df.to_excel(writer, sheet_name=sheet_name, index=False)

# Replace the existing processed file
temp_file.replace(output_file)

print("Updated file:", output_file)

# Display the top 5 rows of every worksheet
with pd.ExcelFile(output_file, engine="openpyxl") as workbook:
    for sheet_name in workbook.sheet_names:
        print(f"\nWorksheet: {sheet_name}")
        display(pd.read_excel(workbook, sheet_name=sheet_name, nrows=5))

Updated file: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_daily_rainfall.xlsx

Worksheet: KN02-NORWOOD

,Location,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,NORWOOD,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,1.7,...,0.0,0.0,0.0,0.0,0.0,11.7,23.4,4.6,0.5,41.9
1,NORWOOD,14/15/05,2015,FEB,0.0,0.0,10.4,0.0,25.9,23.9,...,5.0,7.2,0.0,12.5,20.0,31.7,NaN,NaN,NaN,182.2
2,NORWOOD,14/15/06,2015,MAR,3.7,0.0,0.0,20.3,2.5,0.0,...,0.0,0.0,0.0,25.4,1.3,1.8,4.6,7.0,5.5,85.7
3,NORWOOD,14/15/07,2015,APR,39.0,26.8,0.7,13.1,0.0,0.3,...,12.5,39.3,21.4,1.2,38.8,1.2,3.1,8.7,NaN,341.4
4,NORWOOD,14/15/08,2015,MAY,1.9,0.0,0.0,3.6,29.9,9.7,...,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.1,125.2

Worksheet: KN07-KITULGALA

,Location,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,KITULGALA,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,5.3,...,33.1,0.0,0.0,0.0,0.0,2.8,26.9,1.5,0.0,69.6
1,KITULGALA,14/15/05,2015,FEB,0.0,0.0,21.0,0.0,0.4,1.7,...,0.3,0.5,11.2,31.3,37.4,8.1,NaN,NaN,NaN,151.6
2,KITULGALA,14/15/06,2015,MAR,55.8,0.0,0.0,2.9,0.0,0.0,...,0.0,0.0,0.0,9.0,0.0,53.1,20.5,2.4,2.8,236.2
3,KITULGALA,14/15/07,2015,APR,6.9,14.5,0.0,0.0,0.0,0.0,...,25.2,7.4,23.4,17.2,1.1,24.8,19.0,4.4,NaN,295.9
4,KITULGALA,14/15/08,2015,MAY,18.6,9.6,13.2,12.4,46.5,35.7,...,44.3,1.0,0.0,3.6,2.8,0.0,8.6,22.0,43.2,524.2

Worksheet:  KN11-HOLOMBUWA

,Location,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,HOLOMBUWA,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,3.6,0.0,2.5,0.0,6.1
1,HOLOMBUWA,14/15/05,2015,FEB,0.0,0.0,13.5,0.0,0.3,0,...,12.0,18.5,0.0,2.0,2.3,0.0,NaN,NaN,NaN,65.0
2,HOLOMBUWA,14/15/06,2015,MAR,13.4,2.6,0.0,38.7,0.0,0,...,0.0,0.0,0.0,4.2,0.0,12.8,19.4,13.1,23.1,243.7
3,HOLOMBUWA,14/15/07,2015,APR,11.7,50.4,0.0,0.0,0.0,7,...,1.2,14.5,17.8,12.6,22.9,0.0,13.8,13.7,NaN,381.8
4,HOLOMBUWA,14/15/08,2015,MAY,0.0,16.8,6.4,0.0,0.0,0,...,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.6,32.6,209.2

Worksheet: KN16-DERANIYAGALA

,Location,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,DERANIYAGALA,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,0.0,...,30.0,0.0,0,0.0,0.0,4.1,41.5,50.5,0.0,126.1
1,DERANIYAGALA,14/15/05,2015,FEB,0.0,0.0,9.0,0.0,0.7,2.3,...,3.8,41.2,0,1.7,10.3,30.7,NaN,NaN,NaN,333.9
2,DERANIYAGALA,14/15/06,2015,MAR,30.7,53.8,20.5,1.8,4.0,0.0,...,0.0,0.0,0,6.5,14.5,15.6,24.8,0.0,55.7,302.7
3,DERANIYAGALA,14/15/07,2015,APR,4.5,81.8,0.0,2.1,0.0,68.3,...,70.9,27.9,37,0.0,150.4,0.0,32.6,33.3,NaN,854.6
4,DERANIYAGALA,14/15/08,2015,MAY,6.7,1.4,35.3,113.7,6.3,6.3,...,4.8,0.0,0,9.2,0.0,0.0,0.0,0.0,74.9,440.3

Worksheet: KN18-GLENCOURSE

,Location,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,GLENCOURSE,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,0.0,...,38.9,0.0,0.0,0.0,0.0,0.3,36.8,6.7,0.0,82.70
1,GLENCOURSE,14/15/05,2015,FEB,0.0,0.0,2.6,0.0,0.8,3.6,...,0.0,13.7,0.0,11.5,32.0,1.1,NaN,NaN,NaN,131.60
2,GLENCOURSE,14/15/06,2015,MAR,0.0,14.8,0.0,22.4,0.8,0.0,...,0.0,0.0,0.0,59.7,7.0,87.2,16.0,15.1,18.2,323.50
3,GLENCOURSE,14/15/07,2015,APR,15.4,7.3,0.0,0.0,0.0,80.6,...,1.7,24.8,3.3,48.8,2.3,11.5,62.2,0.3,NaN,581.69
4,GLENCOURSE,14/15/08,2015,MAY,36.1,10.1,53.5,9.0,0.3,10.0,...,3.6,0.3,0.0,0.0,0.0,0.0,0.5,0.9,19.4,276.90

Worksheet: KN21-HANWELLA

,Location,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,HANWELLA,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,0.0,...,16.4,16.6,0.0,0.0,0.6,8.4,39.9,10.5,0.0,92.4
1,HANWELLA,14/15/05,2015,FEB,0.0,0.0,7.8,0.0,2.2,48.6,...,0.0,2.3,0.0,3.3,4.6,0.3,NaN,NaN,NaN,231.1
2,HANWELLA,14/15/06,2015,MAR,0.0,0.0,1.3,19.6,0.0,0.0,...,0.0,0.0,0.0,2.3,2.5,68.5,1.2,15.1,29.0,272.7
3,HANWELLA,14/15/07,2015,APR,56.8,2.2,0.0,0.0,0.0,0.0,...,0.0,7.3,1.5,0.0,34.2,0.0,6.7,12.8,NaN,257.3
4,HANWELLA,14/15/08,2015,MAY,3.8,9.5,0.0,3.2,15.0,3.5,...,6.6,0.0,0.0,0.0,0.0,0.0,0.0,0.4,25.1,180.6

In [10]:
# Input: existing processed Kelani rainfall workbook
input_file = output_file

# Output: new workbook with all sheets combined
combined_file = input_file.with_name("kelani_daily_rainfall_combined.xlsx")

# Read every worksheet
with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    all_sheets = {
        sheet_name: pd.read_excel(workbook, sheet_name=sheet_name)
        for sheet_name in workbook.sheet_names
    }

# Combine vertically without dropping rows
combined_df = pd.concat(
    list(all_sheets.values()),
    ignore_index=True,
    sort=False
)

# Save to a new Excel file
combined_df.to_excel(
    combined_file,
    sheet_name="Kelani_Rainfall",
    index=False,
    engine="openpyxl"
)

print("Combination completed successfully!")
print("Worksheets combined:", len(all_sheets))
print("Total rows:", len(combined_df))
print("Total columns:", len(combined_df.columns))
print("Saved to:", combined_file)

# Verify the first 5 rows
display(combined_df.head(5))

# Show the number of rows contributed by each original worksheet
print("\nRows from each worksheet:")
for sheet_name, df in all_sheets.items():
    print(f"{sheet_name}: {len(df)} rows")

Combination completed successfully!
Worksheets combined: 6
Total rows: 792
Total columns: 37
Saved to: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_daily_rainfall_combined.xlsx

,Location,Year/Month,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL,YEARMONTH
0,NORWOOD,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,1.7,...,0.0,0.0,0.0,0.0,11.7,23.4,4.6,0.5,41.9,NaN
1,NORWOOD,14/15/05,2015,FEB,0.0,0.0,10.4,0.0,25.9,23.9,...,7.2,0.0,12.5,20.0,31.7,NaN,NaN,NaN,182.2,NaN
2,NORWOOD,14/15/06,2015,MAR,3.7,0.0,0.0,20.3,2.5,0.0,...,0.0,0.0,25.4,1.3,1.8,4.6,7.0,5.5,85.7,NaN
3,NORWOOD,14/15/07,2015,APR,39.0,26.8,0.7,13.1,0.0,0.3,...,39.3,21.4,1.2,38.8,1.2,3.1,8.7,NaN,341.4,NaN
4,NORWOOD,14/15/08,2015,MAY,1.9,0.0,0.0,3.6,29.9,9.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.1,125.2,NaN

Rows from each worksheet:
KN02-NORWOOD: 132 rows
KN07-KITULGALA: 132 rows
 KN11-HOLOMBUWA: 132 rows
KN16-DERANIYAGALA: 132 rows
KN18-GLENCOURSE: 132 rows
KN21-HANWELLA: 132 rows

In [11]:

# Path to the existing combined workbook
combined_file = (
    PROJECT_DIR / "data" / "processed" / "kelani"
    / "kelani_daily_rainfall_combined.xlsx"
)

temp_file = combined_file.with_name("kelani_combined_temp.xlsx")

with pd.ExcelFile(combined_file, engine="openpyxl") as workbook:
    df = pd.read_excel(workbook, sheet_name=workbook.sheet_names[0])

# Identify the two Year/Month columns
print("Current columns:", df.columns.tolist())

year_month_cols = [
    col for col in df.columns
    if str(col).strip().upper() in ["YEARMONTH", "YEAR/MONTH"]
]

if len(year_month_cols) != 2:
    raise ValueError(
        f"Expected 2 Year/Month columns, found {len(year_month_cols)}: "
        f"{year_month_cols}. Check the printed column names."
    )

# Keep the first column's values where present; otherwise use the second
first_col, second_col = year_month_cols

df[first_col] = df[first_col].combine_first(df[second_col])

# Remove the duplicate column and standardize the name
df.drop(columns=[second_col], inplace=True)
df.rename(columns={first_col: "YEARMONTH"}, inplace=True)

# Save to a temporary file, then replace the existing combined workbook
with pd.ExcelWriter(temp_file, engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="Kelani_Rainfall", index=False)

temp_file.replace(combined_file)

print("\nUpdated file:", combined_file)
print("Total rows:", len(df))
print("Total columns:", len(df.columns))
print("\nTop 5 rows:")
display(df.head(5))

Current columns: ['Location', 'Year/Month', 'YEAR', 'MONTH', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31', 'TOTAL', 'YEARMONTH']

Updated file: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_daily_rainfall_combined.xlsx
Total rows: 792
Total columns: 36

Top 5 rows:

,Location,YEARMONTH,YEAR,MONTH,D1,D2,D3,D4,D5,D6,...,D23,D24,D25,D26,D27,D28,D29,D30,D31,TOTAL
0,NORWOOD,14/15/04,2015,JAN,0.0,0.0,0.0,0.0,0.0,1.7,...,0.0,0.0,0.0,0.0,0.0,11.7,23.4,4.6,0.5,41.9
1,NORWOOD,14/15/05,2015,FEB,0.0,0.0,10.4,0.0,25.9,23.9,...,5.0,7.2,0.0,12.5,20.0,31.7,NaN,NaN,NaN,182.2
2,NORWOOD,14/15/06,2015,MAR,3.7,0.0,0.0,20.3,2.5,0.0,...,0.0,0.0,0.0,25.4,1.3,1.8,4.6,7.0,5.5,85.7
3,NORWOOD,14/15/07,2015,APR,39.0,26.8,0.7,13.1,0.0,0.3,...,12.5,39.3,21.4,1.2,38.8,1.2,3.1,8.7,NaN,341.4
4,NORWOOD,14/15/08,2015,MAY,1.9,0.0,0.0,3.6,29.9,9.7,...,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.1,125.2

In [12]:
# Delete the individual processed dataset
file_to_delete = (
    PROJECT_DIR / "data" / "processed" / "kelani"
    / "kelani_daily_rainfall.xlsx"
)

if file_to_delete.exists():
    file_to_delete.unlink()
    print("Deleted:", file_to_delete.name)
else:
    print("File not found:", file_to_delete.name)

# Display the remaining Excel files
processed_dir = PROJECT_DIR / "data" / "processed" / "kelani"

print("\nRemaining processed Excel files:")
for file in processed_dir.glob("*.xlsx"):
    print(file.name)

Deleted: kelani_daily_rainfall.xlsx

Remaining processed Excel files:
kelani_daily_rainfall_combined.xlsx