In [55]:

import sys
from pathlib import Path

import pandas as pd
import numpy as np

# Display environment information
print("Python version:", sys.version)
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

# Find the project root directory
PROJECT_DIR = Path.cwd().resolve()

while not (PROJECT_DIR / "data" / "raw").is_dir():
    if PROJECT_DIR.parent == PROJECT_DIR:
        raise FileNotFoundError("Project directory not found.")
    PROJECT_DIR = PROJECT_DIR.parent

# Input: original hourly water-level Excel file
input_file = (
    PROJECT_DIR
    / "data"
    / "raw"
    / "water_level"
    / "kelani"
    / "2015 - 2025 hourly waterlevel.xlsx"
)

# Output: processed Kelani water-level folder
output_dir = (
    PROJECT_DIR
    / "data"
    / "processed"
    / "kelani"
)

output_dir.mkdir(parents=True, exist_ok=True)

print("\nProject directory:", PROJECT_DIR)
print("Input file:", input_file)
print("Input file exists:", input_file.exists())
print("Output directory:", output_dir)

Python version: 3.12.10 (v3.12.10:0cc81280367, Apr  8 2025, 08:46:59) [Clang 13.0.0 (clang-1300.0.29.30)]
Pandas version: 3.0.6
NumPy version: 2.5.4

Project directory: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment
Input file: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/raw/water_level/kelani/2015 - 2025 hourly waterlevel.xlsx
Input file exists: True
Output directory: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani

In [56]:

with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    print("Number of worksheets:", len(workbook.sheet_names))
    print("Worksheet names:", workbook.sheet_names)

    for sheet_name in workbook.sheet_names:
        df_preview = pd.read_excel(
            workbook,
            sheet_name=sheet_name,
            nrows=10
        )

        print(f"\nWorksheet: {sheet_name}")
        display(df_preview)

Number of worksheets: 7
Worksheet names: ['Norwood', 'Kithulgala', 'Deraniyagala', 'Holombuwa', 'Glencourse', 'Hanwella', "N'Street"]

Worksheet: Norwood

     Kehelgamu Oya at Norwood Unnamed: 1 Unnamed: 2   Unnamed: 3
0  Hourly Water Level in mMSL        NaN        NaN          NaN
1                         MSL   1097.76m        NaN          NaN
2                         NaN        NaN        NaN          NaN
3                        Year      Month       Date      Avg. WL
4                        1996          1          1  1098.211667
5                        1996          1          2  1098.253333
6                        1996          1          3  1098.202917
7                        1996          1          4  1098.143333
8                        1996          1          5    1098.1125
9                        1996          1          6    1098.0975

Worksheet: Kithulgala

   Kelani Ganga at Kithulgala Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Hourly Water Level in mMSL        NaN        NaN        NaN
1                         MSL    52.123m        NaN        NaN
2                         NaN        NaN        NaN        NaN
3                        Year      Month       Date    Avg. WL
4                        1996          1          1  53.476667
5                        1996          1          2     53.465
6                        1996          1          3  53.516667
7                        1996          1          4  53.475417
8                        1996          1          5  53.434167
9                        1996          1          6   53.40625

Worksheet: Deraniyagala

  Seethawaka Ganga at Deraniyagala Unnamed: 1 Unnamed: 2 Unnamed: 3
0       Hourly Water Level in mMSL        NaN        NaN        NaN
1                              MSL     73.21m        NaN        NaN
2                              NaN        NaN        NaN        NaN
3                             Year      Month       Date    Avg. WL
4                             2015          1          1  73.733872
5                             2015          1          2  73.689424
6                             2015          1          3  73.651326
7                             2015          1          4  73.636722
8                             2015          1          5  73.622117
9                             2015          1          6  73.622117

Worksheet: Holombuwa

    Gurugoda Oya at Holombuwa Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Hourly Water Level in mMSL        NaN        NaN        NaN
1                         MSL     44.55m        NaN        NaN
2                         NaN        NaN        NaN        NaN
3                        Year      Month       Date    Avg. WL
4                        2015          1          1  45.622168
5                        2015          1          2  45.496444
6                        2015          1          3  45.427233
7                        2015          1          4  45.394214
8                        2015          1          5  45.345957
9                        2015          1          6  45.318018

Worksheet: Glencourse

   Kelani Ganga at Glencourse Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Hourly Water Level in mMSL        NaN        NaN        NaN
1                         MSL  (-0.118)m        NaN        NaN
2                         NaN        NaN        NaN        NaN
3                        Year      Month       Date    Avg. WL
4                        2015          1          1   9.896627
5                        2015          1          2   9.694707
6                        2015          1          3   9.605811
7                        2015          1          4   9.381667
8                        2015          1          5    9.33087
9                        2015          1          6    9.33341

Worksheet: Hanwella

     Kelani Ganga at Hanwella Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Hourly Water Level in mMSL        NaN        NaN        NaN
1                         MSL      0.56m        NaN        NaN
2                         NaN        NaN        NaN        NaN
3                        Year      Month       Date    Avg. WL
4                        2015          1          1    2.51375
5                        2015          1          2   2.194167
6                        2015          1          3   2.063333
7                        2015          1          4      1.865
8                        2015          1          5   1.740833
9                        2015          1          6   1.760833

Worksheet: N'Street

      Kelani Ganga at N'Street Unnamed: 1 Unnamed: 2    Unnamed: 3
0  Hourly Water Level in ftMSL        NaN        NaN           NaN
1                          MSL      0.0ft        NaN           NaN
2                          NaN        NaN        NaN           NaN
3                         Year      Month       Date  Avg. WL (ft)
4                         2015          1          1      1.508333
5                         2015          1          2      1.516667
6                         2015          1          3      1.458333
7                         2015          1          4      1.585417
8                         2015          1          5       1.44375
9                         2015          1          6      1.370833

In [57]:
# Output file
output_file = output_dir / "kelani_hourly_waterlevel.xlsx"

with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

        for sheet_name in workbook.sheet_names:
            # Read actual data; Excel row 4 contains the column headers
            df = pd.read_excel(
                workbook,
                sheet_name=sheet_name,
                header=3
            )

            # Remove completely empty rows and columns
            df = df.dropna(axis=1, how="all")
            df = df.dropna(how="all").reset_index(drop=True)

            # Clean column names
            df.columns = df.columns.astype(str).str.strip()

            # Add Location as the first column
            df.insert(0, "Location", sheet_name)

            # Save the worksheet
            df.to_excel(
                writer,
                sheet_name=sheet_name[:31],
                index=False
            )

            print(
                f"Processed: {sheet_name} | "
                f"Rows: {len(df)}"
            )

print("\nAll worksheets processed successfully.")
print("Saved file:", output_file)

Processed: Norwood | Rows: 11319
Processed: Kithulgala | Rows: 11319
Processed: Deraniyagala | Rows: 4151
Processed: Holombuwa | Rows: 4151
Processed: Glencourse | Rows: 4151
Processed: Hanwella | Rows: 4151
Processed: N'Street | Rows: 4151

All worksheets processed successfully.
Saved file: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_hourly_waterlevel.xlsx

In [58]:
with pd.ExcelFile(output_file, engine="openpyxl") as workbook:
    for sheet_name in workbook.sheet_names:
        print(f"\nWorksheet: {sheet_name}")
        display(pd.read_excel(
            workbook,
            sheet_name=sheet_name,
            nrows=5
        ))

Worksheet: Norwood

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Norwood,Year,Month,Date,Avg. WL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Norwood,1996,1,1,1098.211667,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Norwood,1996,1,2,1098.253333,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norwood,1996,1,3,1098.202917,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Norwood,1996,1,4,1098.143333,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Worksheet: Kithulgala

     Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Kithulgala       Year      Month       Date    Avg. WL
1  Kithulgala       1996          1          1  53.476667
2  Kithulgala       1996          1          2     53.465
3  Kithulgala       1996          1          3  53.516667
4  Kithulgala       1996          1          4  53.475417

Worksheet: Deraniyagala

       Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Deraniyagala       Year      Month       Date    Avg. WL
1  Deraniyagala       2015          1          1  73.733872
2  Deraniyagala       2015          1          2  73.689424
3  Deraniyagala       2015          1          3  73.651326
4  Deraniyagala       2015          1          4  73.636722

Worksheet: Holombuwa

    Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Holombuwa       Year      Month       Date    Avg. WL
1  Holombuwa       2015          1          1  45.622168
2  Holombuwa       2015          1          2  45.496444
3  Holombuwa       2015          1          3  45.427233
4  Holombuwa       2015          1          4  45.394214

Worksheet: Glencourse

     Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Glencourse       Year      Month       Date    Avg. WL
1  Glencourse       2015          1          1   9.896627
2  Glencourse       2015          1          2   9.694707
3  Glencourse       2015          1          3   9.605811
4  Glencourse       2015          1          4   9.381667

Worksheet: Hanwella

   Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Hanwella       Year      Month       Date    Avg. WL
1  Hanwella       2015          1          1    2.51375
2  Hanwella       2015          1          2   2.194167
3  Hanwella       2015          1          3   2.063333
4  Hanwella       2015          1          4      1.865

Worksheet: N'Street

   Location Unnamed: 0 Unnamed: 1 Unnamed: 2    Unnamed: 3
0  N'Street       Year      Month       Date  Avg. WL (ft)
1  N'Street       2015          1          1      1.508333
2  N'Street       2015          1          2      1.516667
3  N'Street       2015          1          3      1.458333
4  N'Street       2015          1          4      1.585417

In [59]:
from pathlib import Path
import pandas as pd

# Project directory
PROJECT_DIR = Path.cwd().resolve()

while not (PROJECT_DIR / "data" / "processed" / "kelani").is_dir():
    if PROJECT_DIR.parent == PROJECT_DIR:
        raise FileNotFoundError("Project directory not found")
    PROJECT_DIR = PROJECT_DIR.parent

# File paths
processed_dir = PROJECT_DIR / "data" / "processed" / "kelani"

input_file = processed_dir / "kelani_hourly_waterlevel.xlsx"
output_file = processed_dir / "kelani_hourly_waterlevel_processed.xlsx"

# Read the existing Excel file and save a new copy
with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        for sheet_name in workbook.sheet_names:
            df = pd.read_excel(
                workbook,
                sheet_name=sheet_name
            )

            df.to_excel(
                writer,
                sheet_name=sheet_name,
                index=False
            )

print("File saved successfully:", output_file)

File saved successfully: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_hourly_waterlevel_processed.xlsx

In [60]:
with pd.ExcelFile(output_file, engine="openpyxl") as workbook:
    print("Worksheets:", workbook.sheet_names)

    for sheet_name in workbook.sheet_names:
        print(f"\nWorksheet: {sheet_name}")
        display(pd.read_excel(
            workbook,
            sheet_name=sheet_name,
            nrows=5
        ))

Worksheets: ['Norwood', 'Kithulgala', 'Deraniyagala', 'Holombuwa', 'Glencourse', 'Hanwella', "N'Street"]

Worksheet: Norwood

,Location,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Norwood,Year,Month,Date,Avg. WL,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Norwood,1996,1,1,1098.211667,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Norwood,1996,1,2,1098.253333,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norwood,1996,1,3,1098.202917,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Norwood,1996,1,4,1098.143333,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Worksheet: Kithulgala

     Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Kithulgala       Year      Month       Date    Avg. WL
1  Kithulgala       1996          1          1  53.476667
2  Kithulgala       1996          1          2     53.465
3  Kithulgala       1996          1          3  53.516667
4  Kithulgala       1996          1          4  53.475417

Worksheet: Deraniyagala

       Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Deraniyagala       Year      Month       Date    Avg. WL
1  Deraniyagala       2015          1          1  73.733872
2  Deraniyagala       2015          1          2  73.689424
3  Deraniyagala       2015          1          3  73.651326
4  Deraniyagala       2015          1          4  73.636722

Worksheet: Holombuwa

    Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Holombuwa       Year      Month       Date    Avg. WL
1  Holombuwa       2015          1          1  45.622168
2  Holombuwa       2015          1          2  45.496444
3  Holombuwa       2015          1          3  45.427233
4  Holombuwa       2015          1          4  45.394214

Worksheet: Glencourse

     Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Glencourse       Year      Month       Date    Avg. WL
1  Glencourse       2015          1          1   9.896627
2  Glencourse       2015          1          2   9.694707
3  Glencourse       2015          1          3   9.605811
4  Glencourse       2015          1          4   9.381667

Worksheet: Hanwella

   Location Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3
0  Hanwella       Year      Month       Date    Avg. WL
1  Hanwella       2015          1          1    2.51375
2  Hanwella       2015          1          2   2.194167
3  Hanwella       2015          1          3   2.063333
4  Hanwella       2015          1          4      1.865

Worksheet: N'Street

   Location Unnamed: 0 Unnamed: 1 Unnamed: 2    Unnamed: 3
0  N'Street       Year      Month       Date  Avg. WL (ft)
1  N'Street       2015          1          1      1.508333
2  N'Street       2015          1          2      1.516667
3  N'Street       2015          1          3      1.458333
4  N'Street       2015          1          4      1.585417

In [61]:
# Remove Unnamed columns from the Norwood sheet only

with pd.ExcelFile(output_file, engine="openpyxl") as workbook:
    sheets = {
        sheet_name: pd.read_excel(workbook, sheet_name=sheet_name)
        for sheet_name in workbook.sheet_names
    }

# Update only Norwood
norwood_sheet = next(
    name for name in sheets
    if name.strip().lower() == "norwood"
)

df = sheets[norwood_sheet]

# Remove columns whose names start with "Unnamed"
df = df.loc[
    :,
    ~df.columns.astype(str).str.startswith("Unnamed:")
]

sheets[norwood_sheet] = df

# Save all sheets back to the same file
with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    for sheet_name, sheet_df in sheets.items():
        sheet_df.to_excel(
            writer,
            sheet_name=sheet_name,
            index=False
        )

print("Updated Norwood sheet.")
print("Columns:", df.columns.tolist())
print("\nFirst 5 rows of Norwood:")
display(df.head(5))

Updated Norwood sheet.
Columns: ['Location']

First 5 rows of Norwood:

  Location
0  Norwood
1  Norwood
2  Norwood
3  Norwood
4  Norwood

In [62]:
import shutil

input_file = processed_dir / "kelani_hourly_waterlevel_processed.xlsx"
output_file = processed_dir / "kelani_hourly_waterlevel_final.xlsx"

shutil.copy2(input_file, output_file)

print("Copy saved successfully:", output_file)

Copy saved successfully: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_hourly_waterlevel_final.xlsx

In [63]:
import pandas as pd

# File path
input_file = processed_dir / "kelani_hourly_waterlevel_final.xlsx"

# Read all worksheets
with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    sheets = {
        sheet_name: pd.read_excel(workbook, sheet_name=sheet_name)
        for sheet_name in workbook.sheet_names
    }

# Process each worksheet
for sheet_name, df in sheets.items():

    # Convert numeric month values to integers, preserving text months
    month = pd.to_numeric(df["Month"], errors="coerce")
    day = pd.to_numeric(df["Date"], errors="coerce")
    year = pd.to_numeric(df["Year"], errors="coerce")

    # Build the actual date from Year, Month and day
    dates = pd.to_datetime(
        {"year": year, "month": month, "day": day},
        errors="coerce"
    )

    # Add the new Date column at the end
    df["Date"] = dates.dt.strftime("%Y-%m-%d")

    sheets[sheet_name] = df

# Update the same Excel file
with pd.ExcelWriter(input_file, engine="openpyxl") as writer:
    for sheet_name, df in sheets.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

print("Date column added and file updated successfully.")

# Verify the first 5 rows of every worksheet
with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    for sheet_name in workbook.sheet_names:
        print(f"\nWorksheet: {sheet_name}")
        display(pd.read_excel(workbook, sheet_name=sheet_name).head(5))

KeyError: 'Month'

In [ ]:
# Rename the first column to Location in every worksheet

with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    sheets = {
        sheet_name: pd.read_excel(workbook, sheet_name=sheet_name)
        for sheet_name in workbook.sheet_names
    }

for sheet_name, df in sheets.items():
    df.rename(columns={df.columns[0]: "Location"}, inplace=True)
    sheets[sheet_name] = df

# Save changes to the same file
with pd.ExcelWriter(input_file, engine="openpyxl") as writer:
    for sheet_name, df in sheets.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

print("First column renamed to Location in all worksheets.")

# Verify the first 5 rows of each sheet
with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    for sheet_name in workbook.sheet_names:
        print(f"\nWorksheet: {sheet_name}")
        display(pd.read_excel(workbook, sheet_name=sheet_name).head(5))

First column renamed to Location in all worksheets.

Worksheet: Norwood

,Location,Year,Month,Date,Avg. WL,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,Norwood,1996,1,1996-01-01,1098.211667,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Norwood,1996,1,1996-01-02,1098.253333,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Norwood,1996,1,1996-01-03,1098.202917,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norwood,1996,1,1996-01-04,1098.143333,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Norwood,1996,1,1996-01-05,1098.112500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Worksheet: Kithulgala

     Location  Year Month        Date    Avg. WL
0  Kithulgala  1996     1  1996-01-01  53.476667
1  Kithulgala  1996     1  1996-01-02  53.465000
2  Kithulgala  1996     1  1996-01-03  53.516667
3  Kithulgala  1996     1  1996-01-04  53.475417
4  Kithulgala  1996     1  1996-01-05  53.434167

Worksheet: Deraniyagala

       Location  Year Month        Date    Avg. WL
0  Deraniyagala  2015     1  2015-01-01  73.733872
1  Deraniyagala  2015     1  2015-01-02  73.689424
2  Deraniyagala  2015     1  2015-01-03  73.651326
3  Deraniyagala  2015     1  2015-01-04  73.636722
4  Deraniyagala  2015     1  2015-01-05  73.622117

Worksheet: Holombuwa

    Location  Year Month        Date    Avg. WL
0  Holombuwa  2015     1  2015-01-01  45.622168
1  Holombuwa  2015     1  2015-01-02  45.496444
2  Holombuwa  2015     1  2015-01-03  45.427233
3  Holombuwa  2015     1  2015-01-04  45.394214
4  Holombuwa  2015     1  2015-01-05  45.345957

Worksheet: Glencourse

     Location  Year Month        Date   Avg. WL
0  Glencourse  2015     1  2015-01-01  9.896627
1  Glencourse  2015     1  2015-01-02  9.694707
2  Glencourse  2015     1  2015-01-03  9.605811
3  Glencourse  2015     1  2015-01-04  9.381667
4  Glencourse  2015     1  2015-01-05  9.330870

Worksheet: Hanwella

   Location  Year Month        Date   Avg. WL
0  Hanwella  2015     1  2015-01-01  2.513750
1  Hanwella  2015     1  2015-01-02  2.194167
2  Hanwella  2015     1  2015-01-03  2.063333
3  Hanwella  2015     1  2015-01-04  1.865000
4  Hanwella  2015     1  2015-01-05  1.740833

Worksheet: N'Street

   Location  Year Month        Date  Avg. WL (ft)
0  N'Street  2015     1  2015-01-01      1.508333
1  N'Street  2015     1  2015-01-02      1.516667
2  N'Street  2015     1  2015-01-03      1.458333
3  N'Street  2015     1  2015-01-04      1.585417
4  N'Street  2015     1  2015-01-05      1.443750

In [ ]:


# File path
input_file = "../data/processed/kelani/kelani_hourly_waterlevel_final.xlsx"

# Read all sheets
with pd.ExcelFile(input_file, engine="openpyxl") as workbook:
    sheets = {
        sheet_name: pd.read_excel(workbook, sheet_name=sheet_name)
        for sheet_name in workbook.sheet_names
    }

# Remove Unnamed columns only from Norwood
sheets["Norwood"] = sheets["Norwood"].loc[
    :, ~sheets["Norwood"].columns.astype(str).str.startswith("Unnamed")
]

# Save all sheets back to the same file
with pd.ExcelWriter(input_file, engine="openpyxl") as writer:
    for sheet_name, df in sheets.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

# Verify Norwood output
print("Norwood sheet after removing Unnamed columns:")
display(sheets["Norwood"].head(5))

print("Remaining columns:", sheets["Norwood"].columns.tolist())
print("Total columns:", len(sheets["Norwood"].columns))

Norwood sheet after removing Unnamed columns:

  Location  Year Month        Date      Avg. WL
0  Norwood  1996     1  1996-01-01  1098.211667
1  Norwood  1996     1  1996-01-02  1098.253333
2  Norwood  1996     1  1996-01-03  1098.202917
3  Norwood  1996     1  1996-01-04  1098.143333
4  Norwood  1996     1  1996-01-05  1098.112500

Remaining columns: ['Location', 'Year', 'Month', 'Date', 'Avg. WL']
Total columns: 5

In [ ]:
# Input and output file paths
input_file = Path("../data/processed/kelani/kelani_hourly_waterlevel_final.xlsx")
output_file = Path("../data/processed/kelani/kelani_hourly_waterlevel_combined.xlsx")

# Read and combine all worksheets
all_sheets = pd.read_excel(input_file, sheet_name=None, engine="openpyxl")

combined_df = pd.concat(
    all_sheets.values(),
    ignore_index=True
)

# Save as one worksheet
combined_df.to_excel(
    output_file,
    sheet_name="Combined",
    index=False,
    engine="openpyxl"
)

# Verify the output
print("Combined file saved successfully:", output_file.resolve())
print("Total rows:", len(combined_df))
print("Total columns:", len(combined_df.columns))
print("\nFirst 5 rows:")
display(combined_df.head())

print("\nLocations included:")
print(combined_df["Location"].unique())

Combined file saved successfully: /Users/amashasinhalagoda/Desktop/IT4010 - Research Project/flood-severity-assessment/data/processed/kelani/kelani_hourly_waterlevel_combined.xlsx
Total rows: 43386
Total columns: 6

First 5 rows:

  Location  Year Month        Date      Avg. WL  Avg. WL (ft)
0  Norwood  1996     1  1996-01-01  1098.211667           NaN
1  Norwood  1996     1  1996-01-02  1098.253333           NaN
2  Norwood  1996     1  1996-01-03  1098.202917           NaN
3  Norwood  1996     1  1996-01-04  1098.143333           NaN
4  Norwood  1996     1  1996-01-05  1098.112500           NaN

Locations included:
<StringArray>
[     'Norwood',   'Kithulgala', 'Deraniyagala',    'Holombuwa',
   'Glencourse',     'Hanwella',     'N'Street']
Length: 7, dtype: str

In [ ]:
from pathlib import Path

file_path = Path("../data/processed/kelani/kelani_hourly_waterlevel_processed.xlsx")

if file_path.exists():
    file_path.unlink()
    print("File deleted successfully:", file_path.name)
else:
    print("File not found:", file_path.resolve())

File deleted successfully: kelani_hourly_waterlevel_processed.xlsx

In [65]:
# File path
file_path = Path("../data/processed/kelani/kelani_hourly_waterlevel_combined.xlsx")

# Read the combined dataset
df = pd.read_excel(file_path, engine="openpyxl")

# 1. Dataset overview
print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

# 2. Count missing values in each column
missing_summary = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (df.isnull().sum().values / len(df) * 100).round(2)
})

missing_summary = missing_summary.sort_values(
    by="Missing_Count", ascending=False
)

print("\nMissing values by column:")
display(missing_summary)

# 3. Total missing values
print("\nTotal missing cells:", df.isnull().sum().sum())
print("Total rows containing missing values:", df.isnull().any(axis=1).sum())

# 4. Display rows containing missing values
print("\nRows containing missing values:")
display(df[df.isnull().any(axis=1)].head(10))

Dataset shape: (37978, 5)

First 5 rows:

  Location  Year  Month        Date      Avg. WL
0  Norwood  1996      1  1996-01-01  1098.211667
1  Norwood  1996      1  1996-01-02  1098.253333
2  Norwood  1996      1  1996-01-03  1098.202917
3  Norwood  1996      1  1996-01-04  1098.143333
4  Norwood  1996      1  1996-01-05  1098.112500

Missing values by column:

     Column  Missing_Count  Missing_Percentage
0  Location              0                 0.0
1      Year              0                 0.0
2     Month              0                 0.0
3      Date              0                 0.0
4   Avg. WL              0                 0.0

Total missing cells: 0
Total rows containing missing values: 0

Rows containing missing values:

Empty DataFrame
Columns: [Location, Year, Month, Date, Avg. WL]
Index: []